### ISSUE TITLE
discussion: e10s

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#100]
I've been performing some testing on e10s.

What's weird is that e10s keeps on turning itself off.  All extensions in the profile are marked as e10s-compatible.  It seems to happen whenever I add a new extension, even if it marked as e10s-compatible.

I've noticed that `extensions.e10sBlockedByAddons` keeps flipping from `false` to `true`.  When that happens, e10s turns off.

Any idea how to fix this?

I set `browser.tabs.remote.autostart` to `true`, but it didn't help.  BTW, does anyone really understand what that pref does?  I need to go through the Firefox code again, but so many things going on.

**Comment by Thorin-Oakenpants** [comment]
I suspect that an add-on is causing this - not directly, but FF code determining that your shouldn't be in e10s due to non e10s addon(s). Mine for example is "user set" and I have never touched it (cogito ergo sum => mozilla internals). I assume you're on FF53? Can you dump a list of your add-ons for us?

**Comment by Thorin-Oakenpants** [comment]
https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProviderUtils.js#1365

```js
 updateAddonsBlockingE10s() {
    let blockE10s = false;

    Preferences.set(PREF_E10S_HAS_NONEXEMPT_ADDON, false);
    for (let [, addon] of this.addonDB) {
      let active = (addon.visible && !addon.disabled && !addon.pendingUninstall);

      if (active && XPIProvider.isBlockingE10s(addon)) {
        blockE10s = true;
        break;
      }
    }
    Preferences.set(PREF_E10S_BLOCKED_BY_ADDONS, blockE10s);
  },
```

**Comment by earthlng** [comment]
@Gitoffthelawn, have you deleted the e10srollout system addon? I noticed the same thing (e10s being disabled) in an ESR52 with only 2 addons installed and both are e10s compatible. AFAIK FF ships with the e10s prefs disabled and that system addon is responsible for checking your addon compatibility and turning e10s on if possible.

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants Thank you for your help.  It was an extension.  It turns out the mechanism I was using to detect non-e10s extensions is faulty.  Actually, it's Mozilla's fault. :)  In *extensions.ini*, there is a list of non-e10s extensions.  It turns out, for whatever reason, that list is not accurate.  I'm not sure why Mozilla even makes that list, given that it is incomplete.  If you have a better understanding, I'm interested.

@earthlng Thank you as well!  I have not deleted that system add-on.  It's been so long since I've (properly) deleted a system add-on, that I don't recall the procedure.  Can you refresh my memory?

**Comment by Thorin-Oakenpants** [comment]
@Gitoffthelawn Yeah, my extensions.ini does not list all my legacy addons, but does correctly identify 5 add-ons as non e10s (one is actually shimmed, but it thinks it isn't). I do not use that ini file, but it's interesting.

System add-ons are in <application>\browser\features
