### ISSUE TITLE
Disabling all of this for the Firefox fork GNUZilla / GNU Icecat

### ISSUE THREAD

**Issue by BullShark** [ghacksuserjs/ghacks-user.js#1008]
https://github.com/mozilla-mobile/fenix/issues/14653

https://www.gnu.org/software/gnuzilla/

**Comment by Thorin-Oakenpants** [comment]
What rubbish is this?
- **ONE** : this repo is not Icecat - **fuck** your shitty fork which according to the website, the latest build is 60.7 (June 3rd 2019) : you're at least 15 months and a dozen releases behind security patches and improvements
- **TWO** : this repo is explicitly for desktop - **WTF** does it have to do with Fenix. Read the [wiki page](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android)
- **THREE** : a complete and utter failure to investigate/differentiate connections in any context (you know, like their purpose)
- **FOUR** : calling all connections spyware/trackers (see point three)
- **FIVE** : fuck off again
- **SIX** : fuck off again
