### ISSUE TITLE
this repo is moving: new org name suggestions appreciated

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#1009]
Nah, you can't ask why, sorry - well, you can, but I will not answer that question.

It will however be staying at Github, and nothing (important) should be lost. Followers still follow, commit histories etc are kept. And AFAIK almost every link will redirect to the new one. There will be some teething issues such as the updater scripts - but we'll fix those. Note: I plan to move TZP first as a test

What I do want to know is what to use for a new organization name - maybe something that means something about what we do, but I'm open to all suggestions (something unique perhaps). Something short and memorable

TIA

**Comment by rusty-snake** [comment]
Brainstorming:
- pants-user.js
- veil-fox
- better-fox (add-on)
- secfox (add-on)
- Chameleon (not really unique)
- ChameleonBrowser (There is a browser with that name fron 1999)
- ChameleonFox 
- NoMoreFP (Used has hashtag in social-media)
- JohnsFP
- Ants
- MakeMeUnique
- DoNotTrackMe

**Comment by crssi** [comment]
thorins-user.js

**Comment by rprimus** [comment]
Fri Sep  4 11:56:57 BST 2020

hard-user-js
hardened-fox

**Comment by geeknik** [comment]
Hush Fox
Hushed Fox

These seem pretty unique and convey what you're trying to accomplish, making Firefox less chatty with the Internet. (;

**Comment by ArchangeGabriel** [comment]
I like hardened-user.js.

**Comment by Thorin-Oakenpants** [comment]
some notes:
- no to anything `hush` or similar- that's not what we're aiming to do: while I appreciate many like to make "firefox quiet" = there's nothing dodgy or bad about automatic connections (updating safe browsing, blocklists, revocations (CRLite), checking for portals, etc) - even telemetry is OK if you want to help out (there's no PII involved)
- not keen on anything `FP*` because that's a zero sum end game
   - or similar like `chameleon`

If I had to sum up what we do the main thing would be **unlinkability**: i.e not letting sites link your traffic (by helping minimizing or eliminating tracking techniques such as local persistent web storage, 3rd parties, FPI, FPing which most rely on canvas to achieve, referers, and so on). Hardening sounds like a security thing (and FF is pretty much secure out of the box). The other two things are anonymity (which you need Tor or a VPN) and privacy (which no one can give except you). Privacy is such an over-used term to describe everything these days, I don't want to use that

...the beatings will continue until the suggested new name improves...
Keep thinking about it

**Comment by parseword** [comment]
Firefox Compartmentalizer 9000
Silozilla
Confined Vulpine

**Comment by zdat** [comment]
Oak  /  Oak-fox
Shy  /  Shy-fox
Mask/Masked  /  Masked-fox
Freedom  /  Freedom-fox
Cleanse  /  Cleansed-fox
Clear  /  Clear-fox

you like? :)

**Comment by KOLANICH** [comment]
IMHO anything already suggested with "harden" in repo name. But hig IMHO - the config is famous under the name `ghacksuserjs`, changing it will only make unneeded confusion and frustration.

>Hardening sounds like a security thing

And disabling shit like WebGL and WebGPU (allowing websites to interact with complex software compiling programs in a Turing-complete language to be executed on a hardware sitting on PCIE bus and having direct access to physical memory on the systems without iommu) and ServiceWorkers is a security thing. And privacy is IMHO a part of security in its broad sense.

>(and FF is pretty much secure out of the box).

it's not, as long as Mozilla tries to not to scare away "ordinary people". Ordinary people don't need a browser that is not allowed to be used by websites` owners on the basis that they are website owners and block access to anyone they consider unprofitable to the website. Ordinary people don't want security and privacy. They want free as in "free lunch" content and are ready to get infected by malware in order to get access to it. Any browser trying to be really secure will get out of favour of ~99% people.

**Comment by atomGit** [comment]
* isoFox - isolated/isolating Firefox
* segFox - segregating Firefox
* FoxShield
* safeFox
* armorFox
* Foxification
* masterFox
* FoxyPants

**Comment by rprimus** [comment]
Mon Sep  7 08:14:49 BST 2020

depend-a-Fox (Depend - stops leaks)

prefix: (used with `FF`, `Fox`, `user.js`)
  - plugged
  - strict
  - stingy
  - selfish (wanting to keep my data to myself)
  - no-share
  - go-away
  - let-me-be
  - MYOB (Mind Your Own Business)

**Comment by Thorin-Oakenpants** [comment]
mozStuff ? mozThings? mozNilla ? TorZilla?
- https://github.com/mozStuff/user.js/
- https://github.com/mozStuff/TZP/

The more I think about it, the more I like TorZilla - we're 95% practically Tor Browser without the Tor protocol

**Comment by bodisor** [comment]
FoxZilla

**Comment by icpantsparti** [comment]
tightenzilla, setzilla, foxsetup :smiley::laughing:

**Comment by geeknik** [comment]
My kiddo suggested CootieShield but YMMV 🤣

**Comment by quistor** [comment]
What about StealFox(Stealth + Fox)? Sound nice and at the same time kinda suited if we look after evading tracking and stuff - we are stealthy move around evading notice of hunters

**Comment by crssi** [comment]
^^This one, despite wrong IMHO, is option that sound best for now IMHO.

I would change it to something simmilar: `SteelFox`

There is something similar already on the net, but has nothing to do with IT.

**Comment by Thorin-Oakenpants** [comment]
mandoFox .. lols .. not sure if I'm serious or not, might need to drink some more beer

tagline: *"wear your fucking mask, you filthy animals"* 
or more likely : *keep your mask on. this is the way*

![mando](https://user-images.githubusercontent.com/16656956/92539602-734d8180-f231-11ea-957a-36ba59a5de04.jpg)

I could envisage an icon/image of a firefox wearing a mandalorian mask .. kinda like [Marvin the Martian](https://en.wikipedia.org/wiki/Marvin_the_martian) .. i.e just the head/mask with (orange?) eyes showing .. maybe a tail poking out

**Comment by earthlng** [comment]
- foxilla
- foXfiles
- foxcave (or foxpit, foxnest, foxhole)
- [color]fox - fe redfox, grayfox, blackfox
- polarfox

**Comment by earthlng** [comment]
- oakenfox
- arkenfox (like the [Arkenstone](https://lotr.fandom.com/wiki/Arkenstone))

**Comment by Jee-Hex** [comment]
> it says it's already taken

maybe:
- TorZillaFox
- TorZilla Firefox
- TorZillaPants so both can be abbreviated as TZP?

**Comment by Thorin-Oakenpants** [comment]
I quite like TorZillaFox ... as we're basically following the same design as Tor Browser: unlinkability (FPI among others), anti-FPing .. everything but the protocol ... or just use TZF (it will encourage people on the web to use the acronym)

TZF/userjs/
TZF/tzp/

My only concern is that people might get the wrong impression that we're incorporating Tor. whereas we say the opposite: use Tor Browser if it fits your need.

shame about the Polar Bears .. man, those guys can't catch a break

**Comment by earthlng** [comment]
nooooo, please nothing with Tor in its name!!!

It's appropriate for your TZP because you're comparing TB and FF, and you can keep that under the new repo but please let's pick another repo name for the user.js.

Tor is The Onion Router ie mainly the protocol and we explicitly tell people not to use the user.js with Tor. We shouldn't hijack/bandwagon that name. The user.js has nothing to do with Tor. It can also scare people away. Not to mention that TorZillaFox is just a terrible and contrived name IMHO. Also way too long

> we're 95% practically Tor Browser without the Tor protocol

yeah maybe, but Tor is like 99.9999% of what makes the Tor Browser

**Comment by Thorin-Oakenpants** [comment]
well... fuck.

Anyway, the migration test was easy as fuck. The repo transferred fine, nothing was lost. But github pages break - they end up 404'ed. Just as well the user.js doesn't use github pages (besides the one generated by the readme and I don't care about that ,in fact I should disable it)

As already noted, since I control the original org, I **recreated the repo**: this allowed me to create pages to replace those people might link to: it also causes some linkage/redirects to then break (since the github redirect no longer works now an orig repo is back in it's place) - i.e think of `#issuenumber` (which is good) vs a full url link in another repo (it would then break).

![eh-sorry](https://user-images.githubusercontent.com/16656956/92726519-3a123000-f35d-11ea-837b-a6e0439a9318.png)

Anyway, the user.js doesn't use github pages, and we won't be recreating the original repo: as that hijacks the internal redirects

---

I want TZP to be in the same repo as the user.js, and I have a couple of other repos I want to add/start at some stage. I want them bundled under the same umbrella. I don't mind moving TZP again (fuck it), but lets make a decision as soon as possible

So now what...?

> Not to mention that TorZillaFox is just a terrible and contrived name IMHO. Also way too long

How on earth is it contrived? Or too long. Sure, two syllables is easier.

also... **...the beatings will continue until the suggested new name improves...** 😀

**Comment by polyzen** [comment]
camoufox (camouflage)
anonyfox
foxhole
arcane

**Comment by Thorin-Oakenpants** [comment]
> foxhole

tried all these .. foxden, foxhouse ... 

----

`hardenFF` it is - it's already been set up and TZP has moved there

honestly, I tried so many things to get something unique and memorable and short and somewhat descriptive

available
- foxilla
- folderfox 
- foxdocs
- foxdepo
- foxbinder
- foxquest  (lols, no way .. foxPROBE !!!)
- foxtweak / fftweak
- hardenFF

So many things were already taken, or didn't pan out: I looked at whacky ideas to combine with "fox" or "moz" or "ff" or even "fx" or whatever: things like metals, gems, fictional metals, creatures, fictional creatures, dr fucking seuss's fox in sox on box on  knox, fox dens (the fox inn) , colors and just so many more. And all of these I flipped the word order round as well to see what they sound like. I thought about just using my name in it.

I searched github for "hardenFF" and got zero results .. I'm done trying to find anything better, and I probably couldn't. It's short, no hyphens or spaces, perfectly explains what it does

Sometimes simpler is better. I know it's a bit generic but it will catch on

So pending earthlng's arrival (and feedback) .. I'm going to pull the fucking trigger

**Comment by earthlng** [comment]
not super stoked about hardenFF. I was hoping for something more witty. I don't think it has to be so "descriptive" as long as it has "fox" or so in the name.

"Have you heard about the hardenFF user.js?" - sounds kinda lame and stupid, doesn't it?

You don't like Arkenfox? The Arkenstone is the highly sought-after gemstone in the LotR lore and this user.js is kinda like the gem among userjs's out there :)
It has a lore connection to your nickname and even if people don't get the meaning immediately it still sounds like a proper and kinda cool name.

> The Arkenstone was a gem, **the object most prized by Thorin Oakenshield of all the treasures** of the Lonely Mountain. Such did he consider its value that he was willing to trade 1/14th of all the gold and silver of Smaug's hoard for it.

Steelfox (Steel=hard=hardening) would've been cute too but unfortunately it's also already taken.
steel=hard/robust is at least true as long as you keep it away from jet fuel ;)

**Comment by Thorin-Oakenpants** [comment]
well I was trying not to make it about **me** .. although I did look at *mithril* - I do like arkenfox, and the I also like the idea of adding that blurb as the description the org

**Comment by syncng** [comment]
This is just my opinion but...
Although I do understand why you wouldn't want to make it only about yourself, I don't think any of the major contributors would mind that at all (do correct me if I'm wrong about that).
Whatever the case may be, you've been an essential pillar to this project, aka it wouldn't exist without you, so **_Arkenfox_** would be just fine, don't you think?
😄

**Comment by Thorin-Oakenpants** [comment]
[Already done](https://github.com/arkenfox). I do get that something too generic (even if unique) is not the best. I didn't even care if it described the repo purposes or not (that's what the repo names do) .. and I even spent time looking at random gibberish generated words and weird-A-F names that have nothing to do with anything

arkenfox it is. This is why we have discussions - PS, not into the capitalization / mixed case

**Comment by Thorin-Oakenpants** [comment]
Thanks everyone for the brainstorming 💋  🍻

**Comment by dngray** [comment]
Congrats on thinking of a new name, and yeah Arkenfox is certainly the best suggestion.

If something happened to @Thorin-Oakenpants it would still be a suitable name to remember the project in memoriam.

**Comment by Thorin-Oakenpants** [comment]
well, to be fair, he did die in the battle of the five armies . .... aaaaaand now I'm feeling a little uneasy and insecure ...
