### ISSUE TITLE
FF53.0 prefs - Windows vs Linux

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#101]
In response to the massive popular demand (1 guy) for a Linux prefs diff or list, I bring you this.
Despite what I said earlier in another issue, I'm not gonna do diffs for Linux versions in the near future, so this will have to do for now.

```js
/******************************************************************************************
 * diffs between FF prefs v53.0-linux64 and v53.0-win64
 *
 * prefs: 2854
 *        2545 matching prefs
 *         309 diffs ( 170 "Windows only", 24 "Linux only", 115 different values )
 ******************************************************************************************/
```

<details><summary>"Windows only" prefs</summary><p>

```js
pref("accessibility.delay_plugin_time", 10000);
pref("accessibility.delay_plugins", false);
pref("app.update.service.enabled", true);
pref("browser.taskbar.lists.enabled", true);
pref("browser.taskbar.lists.frequent.enabled", true);
pref("browser.taskbar.lists.maxListItemCount", 7);
pref("browser.taskbar.lists.recent.enabled", false);
pref("browser.taskbar.lists.refreshInSeconds", 120);
pref("browser.taskbar.lists.tasks.enabled", true);
pref("browser.taskbar.previews.cachetime", 5);
pref("browser.taskbar.previews.enable", false);
pref("browser.taskbar.previews.max", 20);
pref("dom.ipc.plugins.hangUIMinDisplaySecs", 10);
pref("dom.ipc.plugins.hangUITimeoutSecs", 11);
pref("dom.ipc.plugins.sandbox-level.default", 0);
pref("dom.ipc.plugins.sandbox-level.flash", 2);
pref("font.name.cursive.ar", "Comic Sans MS");
pref("font.name.cursive.el", "Comic Sans MS");
pref("font.name.cursive.he", "Guttman Yad");
pref("font.name.cursive.ko", "Gungsuh");
pref("font.name.cursive.th", "Tahoma");
pref("font.name.cursive.x-cyrillic", "Comic Sans MS");
pref("font.name.cursive.x-ethi", "Visual Geez Unicode Title");
pref("font.name.cursive.x-math", "Comic Sans MS");
pref("font.name.cursive.x-unicode", "Comic Sans MS");
pref("font.name.cursive.x-western", "Comic Sans MS");
pref("font.name.cursive.zh-CN", "KaiTi");
pref("font.name.cursive.zh-HK", "DFKai-SB");
pref("font.name.cursive.zh-TW", "DFKai-SB");
pref("font.name-list.cursive.he", "Guttman Yad, Ktav, Arial");
pref("font.name-list.cursive.ko", "Gungsuh");
pref("font.name-list.cursive.zh-CN", "KaiTi, KaiTi_GB2312");
pref("font.name-list.monospace.he", "Fixed Miriam Transparent, Miriam Fixed, Rod, Courier New");
pref("font.name-list.monospace.ja", "MS Gothic, MS Mincho, MS PGothic, MS PMincho,Meiryo");
pref("font.name-list.monospace.ko", "GulimChe");
pref("font.name-list.monospace.x-armn", "Arial AMU");
pref("font.name-list.monospace.x-beng", "Likhan, Mukti Narrow");
pref("font.name-list.monospace.x-cans", "Aboriginal Sans, OskiDakelh, Pigiarniq, Uqammaq");
pref("font.name-list.monospace.x-devanagari", "Mangal, Nirmala UI");
pref("font.name-list.monospace.x-ethi", "Ethiopia Jiret");
pref("font.name-list.monospace.x-geor", "BPG Classic 99U");
pref("font.name-list.monospace.x-gujr", "Shruti");
pref("font.name-list.monospace.x-guru", "Raavi, Saab");
pref("font.name-list.monospace.x-khmr", "Khmer OS, Khmer OS System");
pref("font.name-list.monospace.x-knda", "Tunga, AksharUnicode");
pref("font.name-list.monospace.x-mlym", "AnjaliOldLipi, Kartika, ThoolikaUnicode");
pref("font.name-list.monospace.x-orya", "Kalinga, ori1Uni");
pref("font.name-list.monospace.x-sinh", "Iskoola Pota, AksharUnicode");
pref("font.name-list.monospace.x-tamil", "Latha");
pref("font.name-list.monospace.x-telu", "Gautami, Akshar Unicode");
pref("font.name-list.monospace.x-tibt", "Tibetan Machine Uni, Jomolhari, Microsoft Himalaya");
pref("font.name-list.monospace.zh-CN", "MS Song, SimSun, SimSun-ExtB");
pref("font.name-list.monospace.zh-HK", "MingLiU_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB");
pref("font.name-list.monospace.zh-TW", "MingLiU, MingLiU-ExtB");
pref("font.name-list.sans-serif.ar", "Segoe UI, Tahoma, Arial");
pref("font.name-list.sans-serif.ja", "MS PGothic, MS Gothic, MS PMincho, MS Mincho,Meiryo");
pref("font.name-list.sans-serif.ko", "Gulim");
pref("font.name-list.sans-serif.x-beng", "Vrinda, Akaash, Likhan, Ekushey Punarbhaba");
pref("font.name-list.sans-serif.x-devanagari", "Nirmala UI, Mangal");
pref("font.name-list.sans-serif.x-knda", "Tunga, AksharUnicode");
pref("font.name-list.sans-serif.x-mlym", "AnjaliOldLipi, Kartika, ThoolikaUnicode");
pref("font.name-list.sans-serif.x-orya", "Kalinga, ori1Uni");
pref("font.name-list.sans-serif.x-sinh", "Iskoola Pota, AksharUnicode");
pref("font.name-list.sans-serif.x-telu", "Gautami, Akshar Unicode");
pref("font.name-list.sans-serif.x-tibt", "Tibetan Machine Uni, Jomolhari, Microsoft Himalaya");
pref("font.name-list.sans-serif.zh-CN", "Microsoft YaHei, SimHei");
pref("font.name-list.sans-serif.zh-HK", "MingLiU_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB");
pref("font.name-list.sans-serif.zh-TW", "PMingLiU, MingLiU, MingLiU-ExtB");
pref("font.name-list.serif.he", "Narkisim, David");
pref("font.name-list.serif.ja", "MS PMincho, MS Mincho, MS PGothic, MS Gothic,Meiryo");
pref("font.name-list.serif.ko", "Batang, Gulim");
pref("font.name-list.serif.x-armn", "Sylfaen");
pref("font.name-list.serif.x-beng", "Vrinda, Akaash, Likhan, Ekushey Punarbhaba");
pref("font.name-list.serif.x-cans", "Aboriginal Serif, BJCree Uni");
pref("font.name-list.serif.x-devanagari", "Kokila, Raghindi");
pref("font.name-list.serif.x-ethi", "Visual Geez Unicode, Visual Geez Unicode Agazian");
pref("font.name-list.serif.x-geor", "Sylfaen, BPG Paata Khutsuri U, TITUS Cyberbit Basic");
pref("font.name-list.serif.x-gujr", "Shruti");
pref("font.name-list.serif.x-guru", "Raavi, Saab");
pref("font.name-list.serif.x-khmr", "PhnomPenh OT,.Mondulkiri U GR 1.5, Khmer OS");
pref("font.name-list.serif.x-knda", "Tunga, AksharUnicode");
pref("font.name-list.serif.x-mlym", "AnjaliOldLipi, Kartika, ThoolikaUnicode");
pref("font.name-list.serif.x-orya", "Kalinga, ori1Uni");
pref("font.name-list.serif.x-sinh", "Iskoola Pota, AksharUnicode");
pref("font.name-list.serif.x-tamil", "Latha");
pref("font.name-list.serif.x-telu", "Gautami, Akshar Unicode");
pref("font.name-list.serif.x-tibt", "Tibetan Machine Uni, Jomolhari, Microsoft Himalaya");
pref("font.name-list.serif.zh-CN", "MS Song, SimSun, SimSun-ExtB");
pref("font.name-list.serif.zh-HK", "MingLiu_HKSCS, Ming(for ISO10646), MingLiU, MingLiU_HKSCS-ExtB");
pref("font.name-list.serif.zh-TW", "PMingLiu, MingLiU, MingLiU-ExtB");
pref("geo.provider.ms-windows-location", false);
pref("gfx.direct2d.disabled", false);
pref("gfx.direct2d.force-enabled", false);
pref("gfx.font_rendering.cleartype.always_use_for_content", false);
pref("gfx.font_rendering.cleartype.use_for_downloadable_fonts", true);
pref("gfx.font_rendering.cleartype_params.cleartype_level", -1);
pref("gfx.font_rendering.cleartype_params.enhanced_contrast", -1);
pref("gfx.font_rendering.cleartype_params.force_gdi_classic_for_families", "Arial,Consolas,Courier New,Microsoft Sans Serif,Segoe UI,Tahoma,Trebuchet MS,Verdana");
pref("gfx.font_rendering.cleartype_params.force_gdi_classic_max_size", 15);
pref("gfx.font_rendering.cleartype_params.gamma", -1);
pref("gfx.font_rendering.cleartype_params.pixel_structure", -1);
pref("gfx.font_rendering.cleartype_params.rendering_mode", -1);
pref("gfx.font_rendering.directwrite.force-enabled", false);
pref("gfx.font_rendering.directwrite.use_gdi_table_loading", true);
pref("intl.imm.composition_font", "");
pref("intl.imm.composition_font.japanist_2003", "MS PGothic");
pref("intl.imm.japanese.assume_active_tip_name_as", "");
pref("intl.imm.vertical_writing.always_assume_not_supported", false);
pref("intl.keyboard.per_window_layout", false);
pref("intl.tsf.enable", true);
pref("intl.tsf.hack.atok.create_native_caret", true);
pref("intl.tsf.hack.atok.do_not_return_no_layout_error_of_composition_string", true);
pref("intl.tsf.hack.easy_changjei.do_not_return_no_layout_error", true);
pref("intl.tsf.hack.free_chang_jie.do_not_return_no_layout_error", true);
pref("intl.tsf.hack.ms_japanese_ime.do_not_return_no_layout_error_at_caret", true);
pref("intl.tsf.hack.ms_japanese_ime.do_not_return_no_layout_error_at_first_char", true);
pref("intl.tsf.hack.ms_simplified_chinese.do_not_return_no_layout_error", true);
pref("intl.tsf.hack.ms_simplified_chinese.query_insert_result", true);
pref("intl.tsf.hack.ms_traditional_chinese.do_not_return_no_layout_error", true);
pref("intl.tsf.hack.ms_traditional_chinese.query_insert_result", true);
pref("intl.tsf.support_imm", true);
pref("layers.allow-d3d9-fallback", false);
pref("layers.gpu-process.enabled", true);
pref("layers.prefer-d3d9", false);
pref("layers.prefer-opengl", false);
pref("media.directshow.enabled", true);
pref("media.gpu-process-decoder", true);
pref("media.windows-media-foundation.allow-d3d11-dxva", true);
pref("media.wmf.allow-unsupported-resolutions", false);
pref("media.wmf.decoder.thread-count", -1);
pref("media.wmf.disable-d3d11-for-dlls", "igd11dxva64.dll: 20.19.15.4463, 20.19.15.4454, 20.19.15.4444, 20.19.15.4416, 20.19.15.4404, 20.19.15.4390, 20.19.15.4380, 20.19.15.4377, 20.19.15.4364, 20.19.15.4360, 20.19.15.4352, 20.19.15.4331, 20.19.15.4326, 20.19.15.4300; igd10iumd32.dll: 20.19.15.4444, 20.19.15.4424, 20.19.15.4409, 20.19.15.4390, 20.19.15.4380, 20.19.15.4360, 10.18.10.4358, 20.19.15.4331, 20.19.15.4312, 20.19.15.4300, 10.18.15.4281, 10.18.15.4279, 10.18.10.4276, 10.18.15.4268, 10.18.15.4256, 10.18.10.4252, 10.18.15.4248, 10.18.14.4112, 10.18.10.3958, 10.18.10.3496, 10.18.10.3431, 10.18.10.3412, 10.18.10.3355, 9.18.10.3234, 9.18.10.3071, 9.18.10.3055, 9.18.10.3006; igd10umd32.dll: 9.17.10.4229, 9.17.10.3040, 9.17.10.2857, 8.15.10.2274, 8.15.10.2272, 8.15.10.2246, 8.15.10.1840, 8.15.10.1808; igd10umd64.dll: 9.17.10.4229, 9.17.10.2857, 10.18.10.3496; isonyvideoprocessor.dll: 4.1.2247.8090, 4.1.2153.6200; tosqep.dll: 1.2.15.526, 1.1.12.201, 1.0.11.318, 1.0.11.215, 1.0.10.1224; tosqep64.dll: 1.1.12.201, 1.0.11.215; nvwgf2um.dll: 10.18.13.6510, 10.18.13.5891, 10.18.13.5887, 10.18.13.5582, 10.18.13.5382, 9.18.13.4195, 9.18.13.3165; atidxx32.dll: 21.19.151.3, 21.19.142.257, 21.19.137.514, 21.19.137.1, 21.19.134.1, 21.19.128.7, 21.19.128.4, 20.19.0.32837, 20.19.0.32832, 8.17.10.682, 8.17.10.671, 8.17.10.661, 8.17.10.648, 8.17.10.644, 8.17.10.625, 8.17.10.605, 8.17.10.581, 8.17.10.569, 8.17.10.560, 8.17.10.545, 8.17.10.539, 8.17.10.531, 8.17.10.525, 8.17.10.520, 8.17.10.519, 8.17.10.514, 8.17.10.511, 8.17.10.494, 8.17.10.489, 8.17.10.483, 8.17.10.453, 8.17.10.451, 8.17.10.441, 8.17.10.436, 8.17.10.432, 8.17.10.425, 8.17.10.418, 8.17.10.414, 8.17.10.401, 8.17.10.395, 8.17.10.385, 8.17.10.378, 8.17.10.362, 8.17.10.355, 8.17.10.342, 8.17.10.331, 8.17.10.318, 8.17.10.310, 8.17.10.286, 8.17.10.269, 8.17.10.261, 8.17.10.247, 8.17.10.240, 8.15.10.212; atidxx64.dll: 21.19.151.3, 21.19.142.257, 21.19.137.514, 21.19.137.1, 21.19.134.1, 21.19.128.7, 21.19.128.4, 20.19.0.32832, 8.17.10.682, 8.17.10.661, 8.17.10.644, 8.17.10.625; nvumdshim.dll: 10.18.13.6822");
pref("media.wmf.disable-d3d9-for-dlls", "igdumd64.dll: 8.15.10.2189, 8.15.10.2119, 8.15.10.2104, 8.15.10.2102, 8.771.1.0; atiumd64.dll: 7.14.10.833, 7.14.10.867, 7.14.10.885, 7.14.10.903, 7.14.10.911, 8.14.10.768, 9.14.10.1001, 9.14.10.1017, 9.14.10.1080, 9.14.10.1128, 9.14.10.1162, 9.14.10.1171, 9.14.10.1183, 9.14.10.1197, 9.14.10.945, 9.14.10.972, 9.14.10.984, 9.14.10.996");
pref("media.wmf.enabled", true);
pref("media.wmf.low-latency.enabled", false);
pref("media.wmf.skip-blacklist", false);
pref("media.wmf.vp9.enabled", false);
pref("memory.low_commit_space_threshold_mb", 128);
pref("memory.low_memory_notification_interval_ms", 10000);
pref("memory.low_physical_memory_threshold_mb", 0);
pref("memory.low_virtual_memory_threshold_mb", 128);
pref("mousebutton.4th.enabled", true);
pref("mousebutton.5th.enabled", true);
pref("mousewheel.emulate_at_wm_scroll", false);
pref("mousewheel.enable_pixel_scrolling", true);
pref("mousewheel.system_settings_cache.enabled", true);
pref("mousewheel.system_settings_cache.force_enabled", false);
pref("network.auth.use-sspi", true);
pref("network.protocol-handler.external.ms-windows-store", true);
pref("network.protocol-handler.warn-external.ms-windows-store", false);
pref("plugin.mousewheel.enabled", true);
pref("plugin.scan.plid.all", true);
pref("print.extend_native_print_dialog", true);
pref("security.sandbox.content.level", 1);
pref("security.sandbox.content.tempDirSuffix", "");
pref("security.sandbox.windows.log", false);
pref("security.sandbox.windows.log.stackTraceDepth", 0);
pref("ui.elantech_gesture_hacks.enabled", -1);
pref("ui.osk.debug.keyboardDisplayReason", "");
pref("ui.osk.detect_physical_keyboard", true);
pref("ui.osk.enabled", true);
pref("ui.osk.on_screen_keyboard_path", "");
pref("ui.osk.require_win10", false);
pref("ui.scrollToClick", 0);
pref("ui.trackpoint_hack.enabled", -1);
pref("ui.window_class_override", "");
pref("webgl.angle.force-d3d11", false);
pref("webgl.angle.force-warp", false);
pref("webgl.angle.try-d3d11", true);
pref("webgl.dxgl.enabled", true);
pref("webgl.dxgl.needs-finish", false);
```
</p></details>

<details><summary>"Linux only" prefs</summary><p>

```js
pref("autocomplete.grab_during_popup", true);
pref("autocomplete.ungrab_during_mode_switch", true);
pref("browser.drag_out_of_frame_style", 1);
pref("content.sink.pending_event_mode", 0);
pref("gfx.font_rendering.fontconfig.fontlist.enabled", true);
pref("gfx.font_rendering.fontconfig.max_generic_substitutions", 3);
pref("gfx.xrender.enabled", false);
pref("helpers.global_mailcap_file", "/etc/mailcap");
pref("helpers.global_mime_types_file", "/etc/mime.types");
pref("helpers.private_mailcap_file", "~/.mailcap");
pref("helpers.private_mime_types_file", "~/.mime.types");
pref("intl.ime.use_simple_context_on_password_field", false);
pref("media.ffmpeg.enabled", true);
pref("media.gmp.insecure.allow", false);
pref("media.libavcodec.allow-obsolete", false);
pref("memory.system_memory_reporter", false);
pref("network.protocol-handler.warn-external.file", false);
pref("network.tcp.keepalive.probe_count", 4);
pref("print.print_color", true);
pref("print.print_landscape", false);
pref("print.print_paper_size", 0);
pref("print.print_reversed", false);
pref("print.printer_list", "");
pref("ui.allow_platform_file_picker", true);
```
</p></details>

<details><summary>different values</summary><p>

pref | Windows | Linux
--- | --- | ---
browser.backspace_action | 0 | 2
browser.gesture.pinch.in | "cmd_fullZoomReduce" | ""
browser.gesture.pinch.in.shift | "cmd_fullZoomReset" | ""
browser.gesture.pinch.out | "cmd_fullZoomEnlarge" | ""
browser.gesture.pinch.out.shift | "cmd_fullZoomReset" | ""
browser.preferences.instantApply | false | true
browser.tabs.drawInTitlebar | true | false
browser.urlbar.doubleClickSelectsAll | false | true
font.default.x-devanagari | "sans-serif" | "serif"
font.name.monospace.ar | "Courier New" | "monospace"
font.name.monospace.el | "Courier New" | "monospace"
font.name.monospace.he | "Fixed Miriam Transparent" | "monospace"
font.name.monospace.ja | "MS Gothic" | "monospace"
font.name.monospace.ko | "GulimChe" | "monospace"
font.name.monospace.th | "Tahoma" | "monospace"
font.name.monospace.x-armn | "Arial AMU" | "monospace"
font.name.monospace.x-beng | "Mitra Mono" | "monospace"
font.name.monospace.x-cans | "Aboriginal Sans" | "monospace"
font.name.monospace.x-cyrillic | "Courier New" | "monospace"
font.name.monospace.x-devanagari | "Mangal" | "monospace"
font.name.monospace.x-ethi | "Ethiopia Jiret" | "monospace"
font.name.monospace.x-geor | "BPG Classic 99U" | "monospace"
font.name.monospace.x-gujr | "Shruti" | "monospace"
font.name.monospace.x-guru | "Raavi" | "monospace"
font.name.monospace.x-khmr | "Khmer OS" | "monospace"
font.name.monospace.x-knda | "Tunga" | "monospace"
font.name.monospace.x-math | "Courier New" | "monospace"
font.name.monospace.x-mlym | "Rachana_w01" | "monospace"
font.name.monospace.x-orya | "ori1Uni" | "monospace"
font.name.monospace.x-sinh | "Iskoola Pota" | "monospace"
font.name.monospace.x-tamil | "Latha" | "monospace"
font.name.monospace.x-telu | "Gautami" | "monospace"
font.name.monospace.x-tibt | "Tibetan Machine Uni" | "monospace"
font.name.monospace.x-unicode | "Courier New" | "monospace"
font.name.monospace.x-western | "Courier New" | "monospace"
font.name.monospace.zh-CN | "SimSun" | "monospace"
font.name.monospace.zh-HK | "MingLiu_HKSCS" | "monospace"
font.name.monospace.zh-TW | "MingLiU" | "monospace"
font.name.sans-serif.ar | "Segoe UI" | "sans-serif"
font.name.sans-serif.el | "Arial" | "sans-serif"
font.name.sans-serif.he | "Arial" | "sans-serif"
font.name.sans-serif.ja | "MS PGothic" | "sans-serif"
font.name.sans-serif.ko | "Gulim" | "sans-serif"
font.name.sans-serif.th | "Tahoma" | "sans-serif"
font.name.sans-serif.x-armn | "Arial AMU" | "sans-serif"
font.name.sans-serif.x-beng | "Vrinda" | "sans-serif"
font.name.sans-serif.x-cans | "Aboriginal Sans" | "sans-serif"
font.name.sans-serif.x-cyrillic | "Arial" | "sans-serif"
font.name.sans-serif.x-devanagari | "Nirmala UI" | "sans-serif"
font.name.sans-serif.x-ethi | "GF Zemen Unicode" | "sans-serif"
font.name.sans-serif.x-geor | "BPG Classic 99U" | "sans-serif"
font.name.sans-serif.x-gujr | "Shruti" | "sans-serif"
font.name.sans-serif.x-guru | "" | "sans-serif"
font.name.sans-serif.x-khmr | "Khmer OS" | "sans-serif"
font.name.sans-serif.x-knda | "Tunga" | "sans-serif"
font.name.sans-serif.x-math | "Arial" | "sans-serif"
font.name.sans-serif.x-mlym | "Rachana_w01" | "sans-serif"
font.name.sans-serif.x-orya | "ori1Uni" | "sans-serif"
font.name.sans-serif.x-sinh | "Iskoola Pota" | "sans-serif"
font.name.sans-serif.x-tamil | "" | "sans-serif"
font.name.sans-serif.x-telu | "Gautami" | "sans-serif"
font.name.sans-serif.x-tibt | "Tibetan Machine Uni" | "sans-serif"
font.name.sans-serif.x-unicode | "Arial" | "sans-serif"
font.name.sans-serif.x-western | "Arial" | "sans-serif"
font.name.sans-serif.zh-CN | "Microsoft YaHei" | "sans-serif"
font.name.sans-serif.zh-HK | "Arial" | "sans-serif"
font.name.sans-serif.zh-TW | "Arial" | "sans-serif"
font.name.serif.ar | "Times New Roman" | "serif"
font.name.serif.el | "Times New Roman" | "serif"
font.name.serif.he | "Narkisim" | "serif"
font.name.serif.ja | "MS PMincho" | "serif"
font.name.serif.ko | "Batang" | "serif"
font.name.serif.th | "Tahoma" | "serif"
font.name.serif.x-armn | "Sylfaen" | "serif"
font.name.serif.x-beng | "Vrinda" | "serif"
font.name.serif.x-cans | "Aboriginal Serif" | "serif"
font.name.serif.x-cyrillic | "Times New Roman" | "serif"
font.name.serif.x-devanagari | "Kokila" | "serif"
font.name.serif.x-ethi | "Visual Geez Unicode" | "serif"
font.name.serif.x-geor | "Sylfaen" | "serif"
font.name.serif.x-gujr | "Shruti" | "serif"
font.name.serif.x-guru | "Raavi" | "serif"
font.name.serif.x-khmr | "PhnomPenh OT" | "serif"
font.name.serif.x-knda | "Tunga" | "serif"
font.name.serif.x-mlym | "Rachana_w01" | "serif"
font.name.serif.x-orya | "ori1Uni" | "serif"
font.name.serif.x-sinh | "Iskoola Pota" | "serif"
font.name.serif.x-tamil | "Latha" | "serif"
font.name.serif.x-telu | "Gautami" | "serif"
font.name.serif.x-tibt | "Tibetan Machine Uni" | "serif"
font.name.serif.x-unicode | "Times New Roman" | "serif"
font.name.serif.x-western | "Times New Roman" | "serif"
font.name.serif.zh-CN | "SimSun" | "serif"
font.name.serif.zh-HK | "Times New Roman" | "serif"
font.name.serif.zh-TW | "Times New Roman" | "serif"
font.name-list.serif.x-math | "Latin Modern Math, STIX Two Math, XITS Math, Cambria Math, Libertinus Math, DejaVu Math TeX Gyre, TeX Gyre Bonum Math, TeX Gyre Pagella Math, TeX Gyre Schola, TeX Gyre Termes Math, STIX Math, Asana Math, STIXGeneral, DejaVu Serif, DejaVu Sans, Symbol, Times New Roman" | "Latin Modern Math, STIX Two Math, XITS Math, Cambria Math, Libertinus Math, DejaVu Math TeX Gyre, TeX Gyre Bonum Math, TeX Gyre Pagella Math, TeX Gyre Schola, TeX Gyre Termes Math, STIX Math, Asana Math, STIXGeneral, DejaVu Serif, DejaVu Sans, serif"
full-screen-api.transition-duration.enter | "200 200" | "0 0"
full-screen-api.transition-duration.leave | "200 200" | "0 0"
general.autoScroll | true | false
gfx.canvas.azure.backends | "direct2d1.1,skia,cairo" | "skia"
gfx.content.azure.backends | "direct2d1.1,skia,cairo" | "skia"
gfx.font_loader.delay | 120000 | 8000
gfx.font_loader.interval | 1000 | 50
layers.shared-buffer-provider.enabled | false | true
layout.word_select.eat_space_to_next_word | true | false
media.eme.enabled | true | false
media.getusermedia.playout_delay | 40 | 50
media.mediasource.webm.enabled | false | true
media.peerconnection.capture_delay | 50 | 70
mousewheel.system_scroll_override_on_root_content.enabled | true | false
network.notify.IPv6 | false | true
print.print_extra_margin | 90 | 0
slider.snapMultiplier | 6 | 0
ui.panel.default_level_parent | false | true
urlclassifier.downloadAllowTable | "goog-downloadwhite-digest256" | ""
</p></details>

**Comment by Radagast** [comment]
Thanks for doing this. I guess as the sole Linux user, I'll have to learn how to do this for myself  ᕕ( ᐛ )ᕗ

**Comment by Thorin-Oakenpants** [comment]
`network.protocol-handler.warn-external.file` (linux only) looks interesting

**Comment by nodiscc** [comment]
> pref("network.protocol-handler.warn-external.file", false);

Check https://github.com/pyllyukko/user.js/pull/285

**Comment by earthlng** [comment]
> Thanks for doing this.

You're welcome

**Comment by Atavic** [comment]
http://kb.mozillazine.org/Network.protocol-handler.external-default

Default value: true
Effect: This protocol should be handled by an external application. 

I leave as is, then under Option > Appications I change the Action column to _Always ask_ for all the available Conntet Types. In this way, once I open a pdf the option is either to download or open with the default executable set on the OS level.

**Comment by grauenwolfe** [comment]
In following this project over 1.5 years I've repeatedly noticed differences on Mac prefs, i.e. their defaults, some entries not existing on Mac, and some that are Mac only. I can start relaying these exceptions and omissions if there's anyone else around here is interested.

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe  That would be excellent info to add. I'll create a new issue, we'll make it a sticky. I'm thinking we can use [MAC-ONLY] and [LINUX-ONLY] tags at end of description lines

**Comment by earthlng** [comment]
https://earthlng.github.io/FFprefs-diffs/Firefox-v54.0.html

**Comment by Thorin-Oakenpants** [comment]
I think I'll close this and we'll just use issue 109 - which I will rename "sticky: platform specific prefs" - and in the first post we can maintain a list to the diffs

**Comment by Thorin-Oakenpants** [comment]
^^ done .. refer to #109 from now on
