### ISSUE TITLE
5x ClientID

### ISSUE THREAD

**Issue by git70** [ghacksuserjs/ghacks-user.js#1013]
Hi everyone!
I searched through prefs.js manually and found 5 settings containing some kind of identifier:

app.normandy.user_id
security.sandbox.content.tempDirSuffix
security.sandbox.plugin.tempDirSuffix
toolkit.telemetry.cachedClientID
browser.newtabpage.activity-stream.impressionId

I added such entries to the overrides file:
user_pref ("app.normandy.user_id", "");
user_pref ("security.sandbox.content.tempDirSuffix", "");
user_pref ("security.sandbox.plugin.tempDirSuffix", "");
user_pref ("toolkit.telemetry.cachedClientID", "");
user_pref ("browser.newtabpage.activity-stream.impressionId", "");

After starting FF, the first three received new IDs in the prefs.js file, and the last two were left blank.
Can you help me decide if I did the right thing?
I improved anonymity thanks to the fact that I have different IDs every time I restart?
Or have I broken something else?

Thank you for your great job!

**Comment by rusty-snake** [comment]
> user_pref ("app.normandy.user_id", "");

Normandy/Shield is disable (0503), don't care.

> user_pref ("security.sandbox.content.tempDirSuffix", "");
> user_pref ("security.sandbox.plugin.tempDirSuffix", "");

It is on your disk and not send to the internet, don't care.

>  // ID (a UUID when set by gecko) that is used to form the name of a
>  // sandbox-writable temporary directory to be used by content processes
>  // when a temporary writable file is required in a level 1 sandbox.

https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#1097

**Comment by git70** [comment]
Isn't that weird?
Telemetry is disabled and toolkit.telemetry.cachedClientID remains empty after boot.
While Normandy / Shield is also disabled, but app.normandy.user_id gets new value after startup?

**Comment by Thorin-Oakenpants** [comment]
try #739 for a good read

**Comment by Cade66** [comment]
Indeed `toolkit.telemetry.cachedClientID` is set something like a minute after Firefox start.
With Autoconfig I manged to have it blank with theses two settings in my Autoconfig's config.js:
```
defaultPref("toolkit.telemetry.cachedClientID", "");
lockPref("toolkit.telemetry.cachedClientID", "");
```
I don't know the impact of this `toolkit.telemetry.cachedClientID`, I have no certitude about its implication or not in the user's privacy; all that I know is that whatever userID, clientID, iLoveLucyID ... IDs in general bother me in digital life.
