### ISSUE TITLE
VOTE: enable Tracking Protection [Edit: and SB]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#103]
see #102 for the discussion, and make comments there, so its in one place.

This issue is just so I can get a handle on what people want. I will make a decision on when I get some reasonable numbers of votes.

Vote by adding a reaction to this post

### Proposal

In this user.js, the master branch, (we will have a lite/relaxed branch in future), to enable TP (tracking protection).

Notes:
- We recommend in numerous places that we expect users to be using uBo, which has advantages (default all windows, more comprehensive options). Despite this, as a FALLBACK for users who do not read (and one of our/my aims is to make this more accessible to everyone) and for those who do not use uBo, we should be RESPONSIBLE and enable TP (we're already responsible eg warnings etc, but we should cover as many case scenarios as possible)
- TP (at defaults) is only used in PB mode, whereas uBo is used by default on all windows. We should really MAKE people use uBo - right? - which we can still do with our warnings etc, but some people never read or are afraid of uBo etc.
- TP uses ~~the same list as uBo~~ a list (note: there are two lists, simple+strict, default is simple and we would leave it at that but include the pref for info/enforcing strict)
  * UPDATE: uBo uses multiple lists in default mode and covers almost everything TP does (and more), but there are some items only TP does (rare). No-one has done a comparison.
- TP (at defaults) and uBo do not clash in any way
- There are no issues over TP re security, privacy, or hourly connections for checks, or downloads - but for uBo users, it's redundant, that's all. [Edit: there are no issues over fingerprinting thru HSTS]
- The make up of what settings we use are irrelevant - this vote is about enabling it (either defaults, or enforcing to normal windows is irrelevant at this stage)
- We could leave this for a lite/relaxed branch, which will happen

That's about it really. Either turn TP on in this branch (which is our default branch), or wait until a lite branch.

Note: this would require approx 4 prefs to be made inactive (and reset in about:config), plus one new pref (inactive), and some changes to the wiki and the user.js's readme, and the 0400 section header description. That's about it.

:+1:  =  don't disable TP (in other words end users are at default, prefs become inactive)
:-1:  =  hell no, leave TP disabled by the user.js

**Comment by Atavic** [comment]
If enabled, leave it on the relaxed branch only.
Reason: Anti-fingerprinting.

**Comment by kaliostro2** [comment]
We have uBlock Origin , uMatrix and soon full-fledged containers with "Always open in this conteiner".

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants I think the issue at hand that needs resolving is bigger than Tracking Protection.  The underlying issue you need to decide (or have the community decide if you prefer) is whether you consider uBO is an *officially required* addition to this `user.js` (rather than just a *"nice to have"*.  If this projects considers uBO a baseline requirement, then there is no need to invest any time putting up safeguard for people who don't have uBO.

The TP decision is just a manifestation of the issue, but there could be others in the future.

**Comment by Thorin-Oakenpants** [comment]
I totally get that - i.e "officially required" - but to me it's not - 95% of the user.js does not require it and It is *extremely* easy to comment out or remove section 0400. It just sooooo easy. It's more a "uBo is officially required if you use 0400 section".

[If it stays as status quo] the user.js readme can be made even clearer - I don't even say uBo in that part (its explained slightly better in section 0400 itself). Both could do with better wording. I'm more concerned about SB being off than TP. Other than that I can see no other downsides.

Maybe I should also enforce app+extension update checks (checks only).

I will commit some changes in the meantime.

**Comment by Thorin-Oakenpants** [comment]
OK, I made some changes: readme.md, user.js, and wiki implementation page. uBo was never meant to be a *nice to have* (I didn't think it came across as that, but I am but one person, and probably tunnel blind/too knowledgable on the matter), it was always meant to be *required* (or something similar, IDK why I used that as nothing compares to uBo) if section 0400 was used. This is for THIS branch and only for this section. It's not intrinsic to the entire js. Hopefully this is now super clear.

@RoxKilly , thanks. Without these sorts of discussions, improvements wouldn't be made. Whatever we decide to do re TP (and there is SB, update checking to look at perhaps), the wording has certainly been made far far better. Exactly the wording we need in our "hardened" branch going forward (the master branch is the medium version). So thanks :)

When we get a `lite` branch going, "newbies" will be highly encourage to start with that, which should help mitigate any damage should someone refuse to comprehend/read (assuming Tp or SB etc stay the same as is)

RoxKilly => :beers: :heart: :beer:

**Comment by grauenwolfe** [comment]
I prefer it all disabled personally. uBlock Origin does a splendid job of handling tracking with on-the-fly control as well. There's too much of a grey area involving the companies and services that are supposed to prevent tracking. While I'm not 100% convinced that they are collecting and selling the very info that they protect us from I am certain I don't 100% trust any of them either.

**Comment by Thorin-Oakenpants** [comment]
I fail to see how using a local list (provided/updated from mozilla) is used against you for tracking. Clearly uBo is superior, the issue is actually about making the prefs inactive as a fallback for people who can't or don't read our warnings (I'm more concerned about SB for those people) - the other side to that is there are no clashes with uBo, so why not?. Looks like so far about a 2 to 1 in favor of, as RoxyKilly puts it, making uBo a *required* add-on for this branch and keeping the status quo.

**Comment by Thorin-Oakenpants** [comment]
Note: edited this bullet point from first post

- TP uses ~~the same list as uBo~~ a list (note: there are two lists, simple+strict, default is simple and we would leave it at that but include the pref for info/enforcing strict)
  * UPDATE: uBo uses multiple lists in default mode and covers almost everything TP does (and more), but there are some items only TP does (rare). No-one has done a comparison.

**Comment by Atavic** [comment]
uBlock manages more lists that can be activated or not.
https://github.com/chrisaljoudi/uBlock/issues/1406
https://github.com/pyllyukko/user.js/issues/16

**Comment by crssi** [comment]
Question.

Since TP is disabled by master switches:
`privacy.trackingprotection.enabled`
`privacy.trackingprotection.pbmode.enabled`

Is there really need to clear the following:
`browser.safebrowsing.provider.mozilla.gethashURL`
`browser.safebrowsing.provider.mozilla.updateURL`

?

**Comment by fmarier** [comment]
> ` browser.safebrowsing.provider.mozilla.updateURL`

Also used by the flash blocking lists.

> ` browser.safebrowsing.provider.mozilla.gethashURL`

Not currently used by anything. Also, if you disable updates via `updateURL`, you will never get a `gethash` request.

So even if we were doing `gethash` calls, you wouldn't see any if the other pref is cleared.

**Comment by crssi** [comment]
Thank you @fmarier. Is `browser.safebrowsing.provider.mozilla.gethashURL` deprecated or will be used in the future?

**Comment by fmarier** [comment]
It will be used in the future if we start serving lists that contain hash prefixes (they end in `-shavar`) instead of lists of hashes (which end in `-digest256`).

**Comment by Thorin-Oakenpants** [comment]
Just a heads up, I am going to enable TP and SB in all branches (i.e by making the prefs inactive, note I will leave the google real-time binary checking blocks in place). If you don't like it, feel free to modify YOUR own user.js (I will keep the info in the js, and we will keep it up to date for those who want to disable them). Essentially, RoxKilly and recent events have reinforced the fact that these CAN and DO increase privacy / security (over just uBo) - in fact, they cannot lessen it by their very nature. You cannot argue against that. Cogito ergo sum, they will be made inactive.

---

1. TP will be inactive so assume user is on defaults. TP default is PB Mode only (the user.js does not start in PB mode). TP default is simple list. There are zero issues over privacy, security, and FP'ing. Checking every 60 minutes - big deal. I feel a lot of people got the wrong idea about the "quiet" part of keeping FF quiet (from the early ghacks days, and from Wilders Security thread). There are items in TP that are not covered by default in uBo. Having TP on can only ever INCREASE privacy, it cannot lessen it. And for the ignorant who can't read (i.e they do not have uBo as we state a hundred times), then it's a fallback for them. But TP is MINOR, it's a tiny wee thing hardly worth an argument. :fist_oncoming: 

2. SB - now THIS is worth an argument. SB is important. Tracking is not malicious per se, it's just trying to monetize you. But SB protects against a raft of nasties (ask Francois for details). What has pushed me over the edge, off the fence, and into the camp of turning it on (thru inactive prefs disabling it) is the gmail oAuth hack thingie. SB pushed a fix within 60 minutes. I do not care for any arguments that you could do this or that or wouldn't fall for it, blah blah. SB can only INCREASE security, not decrease it.

3. I'm not pissing around with either TP or SB on - it's the whole thing or nothing at all.

4. There is no reason why all the "USE UBO" warnings can't stay in the wiki, readme, user.js header and section description - we want to encourage people to use uBo etc - I will tweak the wording a smidgen. 

5. It's getting messy dealing with all the URLs (shared between TP, SB, Flash and more, not to mention all the changes - I blame Francois) and quite frankly, blarg! I would be quite happy not dealing with them but (see next point)

6. We will still keep the info up to date in the user,js, and YOUR user.js, do what you like with it.

7. TP/SB and uBo do not "clash", they easily work together

8. In hindsight, this would not affect 12bytes config - TP and SB can only enhance, not lessen

So yes, uBo allows more lists, is customizable, etc (and we will PUSH the message on using it). And people like us who use uBo and NS and uM and other things, who understand web tech better than most, sure, do what we like - we have out own fallbacks like default-deny JS etc. But TP at defaults is simple list and PB Mode only - hardly a big deal. And SB, like TP does with privacy, can only ENHANCE security (plus you can allow an exception). Therefore, disabling them will be made inactive in the user.js.

Feel free to vent a little, but do it somewhere else if you're going to be abusive

NOTE: If you can prove that TP lessens privacy or SB lessens security, then contact Francois. Don't give me arguments that SB lessens privacy (google real time binary check), I did not ask that. I said TP = privacy and SB = security. Anyway, I will leave real time binary checks enabled, Francois will sleep soundly I am sure.

PS: Give me all the thumbs down you like. It won't change anything. Also, feel free to give me a hooray or thumbs up. Don't care :)

**Comment by crssi** [comment]
Just for to be sure.
TP will be PB enabled only, except when manually set the `privacy.trackingprotection.enabled = true` ?
SB will be non-PB and PB enabled?
I don't ask for changes, I am just asking for my personal setting: is there any real reason for PB surfing and not to enable TP on non-PB browsing?

Otherwise, bravo, you are my Queen and lon live the Queen. :)
Cheers

**Comment by Thorin-Oakenpants** [comment]
@crssi section 0400 TP+SB prefs will be made inactive .. i.e with // in front of them. The settings and descriptions will stay the same - i.e if you make them active, then their behavior will be to disable TP+SB.

So an end-user applying the user,.js will have whatever settings they set from the UI options - probably at Firefox defaults. TP default is PB Mode only. TP default is simple list (rather than strict). SB applies to all windows (normal & PB mode).

All the information is still in the user.js - so an end user can still change the setting to enforce TB on all windows. I will also add the pref for which list to use (strict vs simple).

**Comment by crssi** [comment]
OK. What in your short opinion (not related to user.js): to enable TP also in non-PB or not?
I am asking because I don't use PB. It has too many cons for me. ;)
Thanky you

**Comment by earthlng** [comment]
> I have weighed that up against the expertise of the voters

no need to insult us, thx

@crssi wrote:

> I don't use PB. It has too many cons for me. ;)

Why did you initially vote against enabling TP and are now jumping ship? Just curious

@fmarier what stops the big G from creating something like a rainbow table with SB hashes for every site they crawl and use it to easily know exactly which sites someone just visited when they send the hash to google for SB lookup?

**Comment by Thorin-Oakenpants** [comment]
> no need to insult us, thx

Umm, that was not the intent. We (with some expertise/knowledge) probably find TP/SB fairly minor. It's a small sample size of votes, and all of us here are not ignorant of the issues or mechanisms that we can use to protect any tracking and malware and phishing and so on. MOST people don't have that expertise. So I would have expected votes against TP in this regard. If anything, it was a compliment.

> what stops the big G from creating something like a rainbow table...

The lists are LOCAL .. everyone gets the same list. Google doesn't have a clue what got blocked in your browser from these lists. The exception is binaries not in the local list which is checked in real time. Unless I misunderstood what you are talking about

**Comment by earthlng** [comment]
Whenever you visit a "bad" page (thepiratebay for example, at least it used to be according to G) or a page that shares the same partial 32-bit hash as a bad page, google is contacted and will know approximately which pages you could have visited. If that was not a problem how do you explain this:

> When requesting complete hashes for a 32-bit prefix, Firefox throws in a number of extra "noise" entries to obfuscate the original URL further.

The following suggests that FF only sends the 32-bit hash and retrieves all full hashes that start with the same hash. But afaik that's not the case or there would be no reason to "add noise".

> In order resolve such conflicts, Firefox requests from the Safe Browsing server (browser.safebrowsing.provider.mozilla.gethashURL) all of the hashes that start with the affected 32-bit prefix and adds these full-length hashes to its local database. 

And btw the URL also seems to be incorrect because @fmarier explicitly told us that this pref is not used atm. What it really seems to do is send the full url together with some "noise" urls. And you think G won't know which of those urls even match the hash and which ones are "noise"?
Maybe it's all completely safe and fine but I don't know that it really is and would just like to understand and confirm that it is.

And what about this:

> Google explicitly states that the information collected as part of operating the Safe Browsing service "is only used to flag malicious activity and is never used anywhere else at Google" and that "Safe Browsing requests won't be associated with your Google Account".

hmmm, why the need to say something like that? "information collected" - yeah G is totally not interested in tracking users all across the internet - I totally take their word for it.

**Comment by earthlng** [comment]
https://developers.google.com/safe-browsing/v4/lists

> When using the Lookup API to check URLs, the client sends the actual URL in the request and Safe Browsing server converts the URL to a hash before performing the check

**Comment by fmarier** [comment]
> And btw the URL also seems to be incorrect because @fmarier explicitly told us that this pref is not used.

You're right, the pref name was wrong in my blog post. I've updated it. Thanks!

> What it really seems to do is send the full url together with some "noise" urls. And you think G won't know which of those urls even match the hash and which ones are "noise"?

The input to the API for getting the full hashes is a list of **prefixes**. We never send the full hash. Also, the noise entries are real prefixes that are part of the list.

>> When using the Lookup API to check URLs, the client sends the actual URL in the request and Safe Browsing server converts the URL to a hash before performing the check

We're not using the [Lookup API](https://developers.google.com/safe-browsing/v4/lookup-api), we're using the [Update API](https://developers.google.com/safe-browsing/v4/update-api). Also, we're not yet using version 4 of the API, we're still on [version 2.2](https://web.archive.org/web/20160422212049/https://developers.google.com/safe-browsing/developers_guide_v2) until Firefox 57 or 58.

**Comment by earthlng** [comment]
@fmarier wrote

> `browser.safebrowsing.provider.mozilla.gethashURL`
> Not currently used by anything.


https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/

> In order resolve such conflicts, Firefox requests from the Safe Browsing server (`**browser.safebrowsing.provider.mozilla.gethashURL**`) all of the hashes that start with the affected 32-bit prefix and adds these full-length hashes to its local database

**Comment by earthlng** [comment]
Thx! that clarifies a few things.
Are all full length hashes from the response stored, including for the "noise"?
I hope the "real" hash is not always the 3rd from the top or so ;)

**Comment by Atavic** [comment]
@Thorin-Oakenpants 

> Google doesn't have a clue what got blocked in your browser from these lists.

But [here](http://www.google.com/tools/firefox/safebrowsing/faq.html#q12) it says that

> In addition, a very condensed version of the page's content may be sent to compare similarities between authentic and forged pages.

**Comment by fmarier** [comment]
> But here it says that
>
>> In addition, a very condensed version of the page's content may be sent to compare similarities between authentic and forged pages.

That's an ancient page talking about a long-gone version of Safe Browsing, back when it was a Firefox extension, not built into the browser.

**Comment by crssi** [comment]
@earthlng, I never hide that I am for enabling TP and SB (without G of course) and I waited a long time before voting against TP for one simple reason, this was about hardened version and relaxing setting would fit into light version.
Since I am very sure that @Thorin-Oakenpants invested a lot of time into investigating and thinking, and I do not question about his/hers expertise (I also do not question in yours and I really greatly admire you both and also others here), I changed the vote after @Thorin-Oakenpants decides to enable TP and SB (without G).
Anyway, whatever decision at the end I will take it gratefully with open hands, but will still have enabled TP and SB (without G) in my version of user.js.
But, please, do not fight too much (a little is always good), since you two are really a perfect team and you do complement each other perfectly.
Damn, expressing my self is hard and I hope you understood my answer in a good way, since it meant to be in a good way.

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants  thanks for taking the time to explain your decision so thoroughly. I don't think you need to be defensive about it though.

---

@crssi wrote:
> OK. What in short is your opinion (not related to user.js): to enable TP also in non-PB or not?

I have Tracking Protection ON for all browsing modes (easy list) because I just don't see any downside to using it. It is only triggered if uBlock Origin fails to catch a tracker so it doesn't replace uBO in any way, and it has yet to break a site in a way I've noticed.

**Comment by grauenwolfe** [comment]
What exact entry do I need to reset to get these back? Been vacant for a very long time.
![screen- 2017-05-10 at 6 53 00 pm](https://cloud.githubusercontent.com/assets/25858089/25926069/4f112f86-35b2-11e7-923d-c9adacdd60fc.png)

**Comment by fmarier** [comment]
> What exact entry do I need to reset to get these back? Been vacant for a very long time.

Probably these:

- `urlclassifier.trackingTable`
- `urlclassifier.trackingWhitelistTable`
- `browser.safebrowsing.provider.mozilla.lists.*`

**Comment by grauenwolfe** [comment]
Thank you. All of my entries had been changed to blank values, resetting them did repopulate the Block Lists. Again, thanks very much.

![screen- 2017-05-10 at 7 36 32 pm](https://cloud.githubusercontent.com/assets/25858089/25926947/212732cc-35b8-11e7-8afc-8dee6a68bd5f.png)

**Comment by Thorin-Oakenpants** [comment]
Just to clarify: the user.js does not contain any settings for `browser.safebrowsing.provider.mozilla.lists*` - that would have had to have been done independently by an end user. The two lists are still shown in a vanilla FF with the curernt master user.js applied

**Comment by Thorin-Oakenpants** [comment]
@fmarier 
> You're right, the pref name was wrong in my blog post. I've updated it. Thanks!

I'm lost. Can you please tell me WHAT pref you are talking about. And do I now have incorrect info in the user.js - because the whole 0400 section was initially based on your blog post.

0410c = google
0410d = mozilla
^^ is the notation/description for these still correct? Does killing the google URLs negate the effectiveness of the mozilla URLs (since they can no longer be updated via google's master list?)

What is the diff in usage between mozilla URLs and google URLs as per code below?

```js
/* 0410c: disable Google safebrowsing downloads, updates ***/
user_pref("browser.safebrowsing.provider.google.updateURL", ""); // update google lists
user_pref("browser.safebrowsing.provider.google.gethashURL", ""); // list hash check
user_pref("browser.safebrowsing.provider.google4.updateURL", ""); // (FF50+)
user_pref("browser.safebrowsing.provider.google4.gethashURL", ""); // (FF50+)
/* 0410d: disable Mozilla safebrowsing downloads, updates
 * [NOTE] These two prefs are also used for Tracking Protection (see 0420) ***/
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", ""); // resolves hash conflicts
user_pref("browser.safebrowsing.provider.mozilla.updateURL", ""); // update FF lists
```

**Comment by Thorin-Oakenpants** [comment]
@fmarier 

```js
/* 0410a: disable "Block dangerous and deceptive content" (under Options>Security)
 * Until FF48 this was titled "Block reported web forgeries"
 * It covers deceptive sites such as phishing and social engineering ***/
   // user_pref("browser.safebrowsing.malware.enabled", false);
   // user_pref("browser.safebrowsing.phishing.enabled", false); // (FF50+)
```

Both these prefs must be true for the *single* checkbox in Options>Security to be ticked. Why are there two prefs for a single option?

**Comment by Thorin-Oakenpants** [comment]
@fmarier `browser.safebrowsing.provider.google4.gethashURL` (FF53) defaults to a blank string but `browser.safebrowsing.provider.google4.updateURL` does not. Is this the v4 Update API you're talking about? Both prefs were introduced in FF50.

Will the google.* be eventually replaced by the google4.* ?

```js
/* 0410c: disable Google safebrowsing downloads, updates ***/
   // user_pref("browser.safebrowsing.provider.google.updateURL", ""); // update google lists
   // user_pref("browser.safebrowsing.provider.google.gethashURL", ""); // list hash check
   // user_pref("browser.safebrowsing.provider.google4.updateURL", ""); // (FF50+)
   // user_pref("browser.safebrowsing.provider.google4.gethashURL", ""); // (FF50+)
```

**Comment by crssi** [comment]
@RoxKilly 

> It is only triggered if uBlock Origin fails to catch a tracker so it doesn't replace uBO in any way, and it has yet to break a site in a way I've noticed

Isn't it oposite, the TP within FF acts first and then uBO?

**Comment by Thorin-Oakenpants** [comment]
@crssi - order is irrelevant if it exists in one but not the other

**Comment by crssi** [comment]
@Thorin-Oakenpants - I am aware of that, but what when it exists in both?

**Comment by Thorin-Oakenpants** [comment]
>I am aware of that, but what when it exists in both?

Who cares? It's blocked

**Comment by Thorin-Oakenpants** [comment]
@fmarier Now my FF updates TP+SB, but comparing a nilla (and updated TP/SB) FF to mine, I notice I have these 15 persistent (they do not vanish on close) "cache" entries which the nilla FF never produces. Note I have sorted by date, and these "cache" items haven;t been updated since Nov-2016 / Jan-2017. Are these left-overs? [Note: I use a portable FF, so the update/unpacker from portableapps.com might not be cleaning up]

![cache](https://cloud.githubusercontent.com/assets/16656956/25938159/6e841542-3682-11e7-8f2c-2b7842a7a95f.png)

PS: The bottom un-highlighted 8 items that are still dated 19-11-2016, I compared their hashes to those in a nilla FF, the same.

**Comment by RoxKilly** [comment]
@crssi wrote:
> Isn't it oposite, the TP within FF acts first and then uBO?

This is definitely not the case. It's easy to check though. 
1. Start a Private Browsing session
2. Disable uBO
3. Go to nytimes.com and you will see a Tracking Protection alert. 
4. Exit browser and start a regular session with uBO enabled
5. Go back to nytimes.com and you will *not* see a Tracking Protection alert b/c uBO caught the trackers first.

Alternatively, you could look at [this comment](https://blog.mozilla.org/nnethercote/2014/11/12/quantifying-the-effects-of-firefoxs-tracking-protection/#comment-36233) from  one of the original authors of TP:

> [AdBlock Plus] and similar generally use nsIContentPolicy.shouldLoad to stop resources from loading. These content policy checks happen before the network channel is created, and before tracking protection checks. If you run ABP and tracking protection, it just means that ABP will most likely prevent many resources from loading before tracking protection sees them

**Comment by crssi** [comment]
Thank you @RoxKilly

**Comment by fmarier** [comment]
> I notice I have these 15 persistent (they do not vanish on close) "cache" entries which the nilla FF never produces.

The only leftover files are the `test-forbid-simple.*` ones. That's an old test list that's been removed from Firefox. If you delete it, it shouldn't come back. The reason for the old timestamps is that some of these lists change very infrequently (especially the test lists).

If you want to clean up old files, you can also just delete that Safe Browsing cache directory and restart your browser. The lists that are needed will be re-downloaded within 5 minutes of startup if they're not available on disk.

**Comment by fmarier** [comment]
>> You're right, the pref name was wrong in my blog post. I've updated it. Thanks!
> I'm lost. Can you please tell me WHAT pref you are talking about. And do I now have incorrect info in the user.js - because the whole 0400 section was initially based on your blog post.

My blog post was incorrectly referred to `browser.safebrowsing.provider.mozilla.gethashurl`  instead of `browser.safebrowsing.provider.google.gethashurl` when talking about Safe Browsing lists (from Google).

> Does killing the google URLs negate the effectiveness of the mozilla URLs (since they can no longer be updated via google's master list?)
> What is the diff in usage between mozilla URLs and google URLs as per code below?

The `browser.safebrowsing.provider.mozilla.*` prefs are only for the Mozilla lists (TP and flash blocking). The `browser.safebrowsing.provider.google.*` and `browser.safebrowsing.provider.google4.*` prefs are only for the Google Safe Browsing lists.

So if someone wants to disable Safe Browsing only, they shouldn't touch the mozilla prefs. Similarly, if someone only wants to disable TP, they shouldn't touch the google prefs.

> `browser.safebrowsing.provider.google4.gethashURL` (FF53) defaults to a blank string but `browser.safebrowsing.provider.google4.updateURL` does not. Is this the v4 Update API you're
talking about? Both prefs were introduced in FF50.

Yes, we've never used the Lookup API and never will. That's true both on v2.2 and v4.

> Will the google.* be eventually replaced by the google4.* ?

Yes, we're aiming to move from `google` (version 2.2 of the Safe Browsing API) to `google4` (version 4 of the API) in the 57/58 timeframe. The details are on https://wiki.mozilla.org/Security/Safe_Browsing/V4_Implementation.

>     // user_pref("browser.safebrowsing.malware.enabled", false);
>     // user_pref("browser.safebrowsing.phishing.enabled", false); // (FF50+)
>
> Both these prefs must be true for the *single* checkbox in Options>Security to be ticked. Why are there two prefs for a single option?

The two prefs control two different things (malware v. phishing). We have the ability to control both independently but we don't think it's worth the space in the UI, so we leave it in `about:config` for our power users.

**Comment by Thorin-Oakenpants** [comment]
@fmarier 
I wondered about that, clearing the files. Deleted the lot, repopulated after 20 minutes .. zilla ones immediately, google ones 20 minutes later. Now I have 40 items, not 53 - cheers.

See commit above (and subsequent one) - fixed up that misconception about sharing urls between TP+Flash vs SB. Always thought that was strange, certainly made it messy to document.
 - 0410's = google + SB only
 - 0420's = mozilla + TP+Flash only

Much cleaner. Thanks for clearing that up.

**Comment by crssi** [comment]
@fmarier - are there any plans for SB to migrate from G to shavar Mozilla?

**Comment by crssi** [comment]
@Thorin-Oakenpants - just thinking out loud, not demandig or whining:
Some are really unhappy for the latest changes.
What about to split now into "lite" version and leave this one still "hard"?
It will please all audience and push-up morale.
It doesn't matter for me, since I am just fine to do some diffs for myself and I am not selfish.
The version I am using I do consider "light" and there are only about 20 changes to yours.

Hmmm... this might be for a new topic?

Love you all

**Comment by fmarier** [comment]
> are there any plans for SB to migrate from G to shavar Mozilla?

No plans. It's an incredibly expensive service to run, both from a network traffic point and list curation point of view. Given that the service is quite good, there are better uses of our money and engineers (e.g. working with Tor) IMHO.

**Comment by Thorin-Oakenpants** [comment]
@crssi "Some are really unhappy for the latest changes" - you mean making TP+SB disabling=> inactive. Well, a sample size of 13 votes from regulars and contributors has given some indication. I am aware of this. There is also the wider community and making this more accessible (to less-techy less-firefoxy people). It's not as if the options to do it have been removed.

As far as I am concerned, essentially leaving TP+SB alone (i.e most prefs to disable them are inactive) *is* hardening. (Already I have had one instance of TP blocking something that uBo did not.)

A lite version would not reverse this. "Lite" or "relaxed" in my definition means we only change (by commenting out) those prefs which cause some level of breakage - so 99% of users can grab the "lite" branch and never have a problem.

An "hardened" version would not reverse this either. It depends on your definition of "hard". To me it means breakage be damned. But it also means more clashes with security vs privacy.

--
Yes, this is best left for another topic. I would like to do these lite/hardened branches soon (before FF57 lands). The more we improve and refine the master branch, the less maintenance later. Not sure about a "hardened" version being necessary - the master branch pretty much there - might be easier for a "hardened" branch to simply be a sticky FYI of 10 prefs or so to flip.

**Comment by Atavic** [comment]
FYI: pyllyukko's gone [relaxed-branch](https://github.com/pyllyukko/user.js/tree/relaxed).

**Comment by crssi** [comment]
^^ hmm: this one bothers me:
IndexedDB could be used for tracking purposes, but is required for some add-ons to work (**notably uBlock**), so is left enabled

**Comment by Atavic** [comment]
It has been resolved.
