### ISSUE TITLE
kaliostro2's special little topic on typing fast

### ISSUE THREAD

**Issue by kaliostro2** [ghacksuserjs/ghacks-user.js#104]
Ok. When using **user_pref("browser.startup.page", 1);** , there is one property that I do not like. When the browser just opened and I start entering the address in the address bar, it jumps to the search line under the logo. Is there any chance to disable this?

**Comment by Thorin-Oakenpants** [comment]
The user.js doesn't even use this setting - 0102: which is inactive and set as blank (value 0).

I don't quite understand what you mean @kaliostro2 . Value 1 is to use the "home" page, which is the value in the pref `browser.startup.homepage` (which the user.js does not use). What is your "home" page. It is like google.com or something? Search line under the logo?

**Comment by earthlng** [comment]
about:home I guess

**Comment by Thorin-Oakenpants** [comment]
So I had a look in a vanilla FF53. The default homepage is about:home, which is basically the FF logo with a search field under it. In no circumstances could I get any typing in the urlbar to jump to the page search field.

**Comment by kaliostro2** [comment]
I open browser and start type addres and sometimes hapen this:

<a href='https://hostingkartinok.com/show-image.php?id=22d3708d63f363517d6b14b2582703fb' title='image host'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/05/22d3708d63f363517d6b14b2582703fb.png'  /></a>

**Comment by crssi** [comment]
Hmmm... looks like, when you open a FF, you are too fast.
FF starts to open its default home page... you start to type in, but before you finish typing, the default page loading is finished and JS event on page loaded set focus to text box on the page.

**Comment by kaliostro2** [comment]
Yes. Precisely.

**Comment by kaliostro2** [comment]
What, there is no solution to this problem?

**Comment by Gitoffthelawn** [comment]
This extension (WebExtension API compatible) might be of some use:
  https://addons.mozilla.org/firefox/addon/custom-new-tabs/
It allows the focus to be set for new tabs.  Not sure how it works for the startup tab.

**Comment by earthlng** [comment]
> What, there is no solution to this problem?

easiest way to solve this is to set about:blank as your homepage with `browser.startup.page;0`
What's so great about `about:home` anyway?
