### ISSUE TITLE
Typo in 1202

### ISSUE THREAD

**Issue by glitsj16** [ghacksuserjs/ghacks-user.js#105]
Hi, there's a typo in 1202: 2-min --> 2=min

git HEAD:
 * 1=min version of TLS 1.0, 2-min version of TLS 1.1, 3=min version of TLS 1.2 etc

corrected:
 * 1=min version of TLS 1.0, 2=min version of TLS 1.1, 3=min version of TLS 1.2 etc

Keep up the amazing & much appreciated work you all put in. Regards.

**Comment by Thorin-Oakenpants** [comment]
Now these are types of commits I like, .. so easy :) https://github.com/ghacksuserjs/ghacks-user.js/commit/fc0a0450699e33dbf7099b9f5cef7ca1bc7a7706
