### ISSUE TITLE
Add "general.autoScroll" to 3000 for completeness

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#108]
Maybe?

Just to be clear, I am not trying to push anything... as always. :)
I have this set to false, since I makes me bite the mouse when scrolling cursor appears. :)

**Comment by Thorin-Oakenpants** [comment]
I've mentioned before about even doing away with the personal section. I hate it (people use as an excuse all the time .. for all sorts of things - not u crssi). I've really tried to stay away from adding to it.

Things like tweaks for speed (pipelining etc) I have refused in the past saying that there are too many variable for a one fits all. I think this might be one of them, plus different people will want different degrees (fast, slow, whatever). I don't even know what that pref does, so I'm winging it here.

atomGit's repo has all this stuff, btw - and I've linked him and his article in the readme

**Comment by crssi** [comment]
Got it... I have somehow missed your statement of avoiding the section 3000.
I will tattoo it into my brain cells. :)

**Comment by Thorin-Oakenpants** [comment]
No no no .. that's not what I meant. We still need to assess every pref individually. And some prefs are not documented well/anywhere and are not in the options UI, so they may make sense to include them if they are universal (not sure if a mouse scroll setting is "universal").

Tell me what the pref does?

**Comment by Thorin-Oakenpants** [comment]
@crssi What did you want to make the pref = true or false. Default is false

**Comment by earthlng** [comment]
On Windows the default is false and on Linux it's true. Because in Linux in general middle-click is "copy selected content" for copy/paste.
If we want to add it we should mark it as somewhat of a "Windows mostly" pref, fe.

```
/* disable middle-click enabling auto-scrolling on Windows ***/
   // user_pref("general.autoScroll", false);
```

**Comment by Thorin-Oakenpants** [comment]
sounds cool to me. I'm ok with adding it, because it helps linux users.. but I'm off to bed (*hint)

**Comment by earthlng** [comment]
It doesn't help linux users at all ... yeah go take a nap you seem to need it xD
good night and sweet dreams soft Pants

**Comment by crssi** [comment]
Its just the opposite, default on windows is true and on linux is false
I am using false as a value

**Comment by grauenwolfe** [comment]
Mac default is set to true.

**Comment by Thorin-Oakenpants** [comment]
> It doesn't help linux users at all ... yeah go take a nap you seem to need it xD

Ummmm... yeah it does. It informs them (IDK if it even works on Linux). Windows/Mac users would not have that issue (where middle-mouse-click was hijacked)

**Comment by Thorin-Oakenpants** [comment]
Done. @grauenwolfe So you're a Mac user? If so, that's good to know. BTW, changed Windows to Windows/Mac in the description, thanks)
