### ISSUE TITLE
sticky: platform specific prefs & values

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#109]
Use this issue to post info about Mac / Linux / Windows / Android specific preferences and differences

- Mac or Linux or Windows or Android only prefs
- Prefs where the default is different for a reason
   - eg `general.autoScroll` defaults to false in Linux because it would interfere with middle-mouse-click
- We will use [MAC], [LINUX], [WINDOWS], [ANDROID] etc tags for OS specific prefs

**Please note: The comments here will be regularly cleaned out to keep this sticky usable**

**Diffs**: https://earthlng.github.io/FFprefs-diffs/index.html

**Comment by grauenwolfe** [comment]
_INTRODUCTORY NOTE - INTENDED TO BE DELETED
Here is an initial list of Mac-specific differences, just a few of the more obvious ones to get the ball rolling. There are a number of differences in the Mac default settings but I don't know them offhand since I've never documented them and so will just have to wait until I come across them again. They will be noted and then added to this thread as they come up._

_Also, I welcome any input on the manner in which I've posted, i.e., hierarchy, formatting, overall clarity, etc._

---
### Mac-specific / macOS / OS X
The following entries do not exist in Mac versions of Firefox installations.

---
**SECTION 0600 : BLOCK IMPLICIT OUTBOUND**

- **0607: stop links launching Windows Store on Windows 8/8.1/10**

   - network.protocol-handler.external.ms-windows-store

---
**SECTION 0800: LOCATION BAR / SEARCH BAR / SUGGESTIONS / HISTORY / FORMS**

- **0870: disable Windows jumplist**

   - browser.taskbar.lists.enabled	
   - browser.taskbar.lists.frequent.enabled
   - browser.taskbar.lists.recent.enabled
   - browser.taskbar.lists.tasks.enabled

 
- **0871: disable Windows taskbar preview**

   - browser.taskbar.previews.enable

---
**SECTION 1800: PLUGINS**

- **1805: disable scanning for plugins**

   - plugin.scan.plid.all

---
**SECTION 2000: MEDIA / CAMERA / MIKE**
<i>(should be "MIC" unless there's some guy named Mike that's been a problem I don't know about.)</i>

- **2012: two more webgl preferences**

   - webgl.dxgl.enabled

---
**SECTION 2500: HARDWARE FINGERPRINTING**

- **2508: disable hardware acceleration to reduce graphics fingerprinting**

   - gfx.direct2d.disabled

**Comment by earthlng** [comment]
https://earthlng.github.io/FFprefs-diffs/Firefox-v53.0.html

**Comment by grauenwolfe** [comment]
> https://earthlng.github.io/FFprefs-diffs/Firefox-v53.0.html

Ahaha. All done then. Good job everyone. Lol.

Awesome find by the way.

**Comment by RoxKilly** [comment]
@earthlng is a machine

**Comment by atomGit** [comment]
linux mint 18.x - these were found in a minimal preconfigured prefs.js

`user_pref("network.protocol-handler.app.apt", "/usr/bin/apturl");
user_pref("network.protocol-handler.app.apt+http", "/usr/bin/apturl");
user_pref("network.protocol-handler.warn-external.apt", true);
user_pref("network.protocol-handler.warn-external.apt+http", true);`

also the default browser check is disabled in mint (and probably all of debian distros at a minimum i would imagine) - you guys already have this in your .js though...

`user_pref("browser.shell.checkDefaultBrowser", false);`

**Comment by Thorin-Oakenpants** [comment]
Thanks. Haven't forgotten about this. I just want to close up some other issues first (1. auto-updates, 2. web workers section redo (more links better explanations), 3. fixup of use of "enable/disable/set" for numbered descriptions 4. add something to Start in PB mode pref 0001 (see issue #80 )

5. I also want to create a folder called searchplugins to hold OUR sanitized XML files with base64 embedded icons etc. And to create a wiki search page (with an intro) that lists them and their keywords etc. Like how to add them and make sure the names don't clash etc

So this is like number 6 on my list of items - to properly label win/mac/nix only items as such, and to see if there are any we are missing that could be added

**Comment by Atavic** [comment]
Dapper Linux [hardened-browser config](https://github.com/dapperlinux/dapper-hardened-browser/blob/master/mozilla.cfg).

**Comment by Thorin-Oakenpants** [comment]
There are now 10 [WINDOWS] tags, 1 [MAC], and zero [LINUX] or [ANDROID], done during cleaning up of descriptions and other commits. Now we just need to work our way thru earthlng's diff etc

**Comment by earthlng** [comment]
https://earthlng.github.io/FFprefs-diffs/Firefox-v54.0.html

**Comment by Thorin-Oakenpants** [comment]
I had a look at the "FF53.0 prefs - Windows vs Linux" last night and almost everything is covered - maybe a couple to look at. I also found out that 2503 `dom.netinfo.enabled` is only used on android - see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1372072#c2) - but this may change, and I don't think its worth adding that info

**Comment by icpantsparti** [comment]
I notice `dom.presentation.device.name` on Android Firefox, it contains the exact device model number.  On reset or blanking it repopulates, seems to hold if changed to something else.  Wondering if it is a fingerprinting issue, cannot find any info.  Grateful for any advice.

**Comment by Thorin-Oakenpants** [comment]
its used in mDNS (multicasting DNS)

[DXR](https://dxr.mozilla.org/mozilla-central/source/dom/presentation/provider/MulticastDNSDeviceProvider.cpp#171) if string is empty, reset it (not sure when this code is called)

See [1382533](https://bugzilla.mozilla.org/show_bug.cgi?id=1382533) which covers this under privacy.resistFingerprinting. However, that pref is not great for mobile, as web pages tend to get served as if you are on a desktop, as the UA spoof lies (for non-Windows OS) and every site thinks you are on Windows. In FF59+ the UA spoof will auto-use Android as a platform in its "spoof" if you're on Android (see [1404608](https://bugzilla.mozilla.org/show_bug.cgi?id=1404608) which is the original bug for the mobile/desktop thing, but was used to make the spoof changes)

also see https://bugzilla.mozilla.org/show_bug.cgi?id=1185806 which was linked in the DXR above

I'm not entirely sure exactly what mDNS is, when it gets used, and how websites could grab this info.

**Comment by Thorin-Oakenpants** [comment]
https://en.wikipedia.org/wiki/MDNS

I'm guessing this would cover things like device discovery/connection for casting eg a youtube video to chromecast?

**Comment by Atavic** [comment]
`dom.presentation.device.name` is used to identify the connected device.

Similar to Apple Bonjour and [NSD](https://developer.android.com/training/connect-devices-wirelessly/nsd.html).

**Comment by Thorin-Oakenpants** [comment]
Yup.. says it right there in the pref name :) and outlined in the links

https://bugzilla.mozilla.org/show_bug.cgi?id=1185806#c1
> mDNS requires name uniqueness and can detect conflict from its protocol

**Comment by Thorin-Oakenpants** [comment]
As an aside... after this discussion, when I went to bed and was about to watch a movie using Plex, before I did, I went into FF, reset the pref etc - it did everything that @icpantsparti said. I was just checking it out, not doubting.

Then my Plex app couldn't find my bedroom chromecast (I have two, and LlamaHub was nowhere to be found, GoatHub was not on as I power them via USB - do not mock my naming convention xD). I just quickly rebooted my phone and all was well .. except THIS time, as Plex connected (I think it's when you do a refresh for devices in the Plex app), my device name was displayed on the TV center top - **never seen that before**. Likely not related, I mean how could it be.

/end of useless story :)

**Comment by crssi** [comment]
Chromecast has wifi problems or more correctly is a wifi problem. 
AFAIK, the patch was just released.

**Comment by Thorin-Oakenpants** [comment]
>  as I power them via USB

doesn't affect me. when not in use, they are off - anyway I have bandwidth to spare (but yeah, who ever thought (tens of) hundreds of millions of devices downloading screen papers all the time was a good idea needs a bullet

**Comment by icpantsparti** [comment]
Thanks for your replies. 👍 :)

**Comment by Thorin-Oakenpants** [comment]
going to retire this sticky, it's served its initial purpose for fixing up labeling some existing prefs. New prefs we deal with as we get to them
