### ISSUE TITLE
0400: QUIET FOX (and a bit more)

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#113]
`/*** 0400: QUIET FOX [PART 2] [WARNING]`

* should we rename the section because almost everything in 0400 is now enabled and it has nothing to do with QUIET FOX anymore? fe. `Blocklists, Safe Browsing and Tracking Protection`
  * 0430: SSL reporting could go to 1200 because it fits there better anyway
* the Warning tag: isn't that tag for things that break? Wouldn't the SETUP tag be better, if any?
* 0402: the 4 collection prefs are maybe not easy to understand in the current form. Can we set them to empty string and comment them out, so it's easier to disable them should someone choose to do so?
Enforcing the default values doesn't make much sense IMO

similar to the last point above, I also think 2617 (pdfJS) would be better if we change the value and the title (to: disable) and comment it out. It currently enforces the default value (=enable pdfjs) which I think is weird in a file that aims to enhance security. Idc whether we enable or disable pdfJS by default btw.

The idea is that it shouldn't be necessary to change the pref _**values**_, but rather being able to disable/enable something by un-commenting or commenting out the prefs.

**Now you:** do you have pdfJS enabled or not?
(not doing votes anymore because we just end up ignoring it anyway ;)

**Comment by RoxKilly** [comment]
> Enforcing the default values doesn't make much sense IMO...The idea is that it shouldn't be necessary to change the pref values, but rather being able to disable/enable something by un-commenting or commenting out the prefs.

I agree with this, especially in places where it isn't explicitly stated that you're enforcing the default. This is because I research every deviation from the default by looking for discussions about the setting online, and given hundreds of settings, this took me many hours the first time. Knowing that something is left at default makes it less interesting (ie. I can just quickly read the description and move on). This change would make the file a lot more user-friendly I think.

**Comment by Atavic** [comment]
Maybe the warning should be included in the following sentence?

```
[WARNING]
This section has security & tracking protection implications vs privacy concerns
vs effectiveness vs 3rd party 'censorship'. We DO NOT advocate no protection.
If you disable Tracking Protection (TP) and/or Safe Browsing (SB), then
SECTION 0400 REQUIRES YOU HAVE uBLOCK ORIGIN INSTALLED.
```
I adjusted the beginning:

```
WARNING: This section has implications regarding [1] security & tracking protection vs privacy 
concerns and [2] built-in mitigations vs 3rd party 'boycott'...
```

**Comment by Thorin-Oakenpants** [comment]
0402 : I had already noticed that this sticks out as inconsistent
- the title (which we can tweak) is about "quiet"
- the pref values in 0400 (in general) are about turning things off
- the descriptions in 0400 (in general) are about turning things off

So 0402 should do the same. It has nothing to do with enforcing default values.

---
> should we rename the section because almost everything in 0400 is now enabled

We can improve the name. A pref (if used) should reflect the description. The prefs "if used" reflect the title. It is not about the title/descriptions reflecting the "active/inactive" state of anything. Consider this

```js
/*** PREVENT NUCLEAR WAR ***/
/* 666: disable Trump's access to the red button ***/
   // user_pref("red.button.enabled", false)
```

The description of pref 666 matches the intent of the pref if uncommented. And the pref(s) combined have the intent of the section header. Let me re-write that

```js
/*** KEEP FIREFOX QUIET ***/
/* 666: disable all TP & SB ***/
   // user_pref("tp.and.sb.enabled", false)
```

Now "QUIET FOX" is not the best title but it describes the section's purpose correctly. We also use the term in section 0300, and 400 was originally split off from 0300. We could do better. They don't have to have the same name (eg part 1 etc). So I'm all ears.

---
> Warning tag: isn't that tag for things that break? Wouldn't the SETUP tag be better

Well, TBH, warning seems appropriate as making the prefs active can put a person at risk. It's not just for breakage. But no reason it can't have both (see section 0300, see pref 1020). It's not indicative of a pref's active/inactive status either (see pref 1201).

- I see [Warning] as informing people that using this pref either causes breakage or adds risk
- I see [Setup} as informing people of some items of interest they may want to check before implementing the js or for toubleshooting (warning also troubleshoots)

---
ToDo:
- [ ] replace 0400 and 0300 section titles. Definitely remove the part 1 and part 2 titles
- [ ] change 0402 to "disable" in description, change pref values to false and nulls and make it all inactive
- [ ] change 0401 to same as 0402: , i.e description to disable but make `.enabled` inactive
- [ ] what else?
- [ ] 2617 (pdfjs) - debatable (see next comment)

**Comment by Thorin-Oakenpants** [comment]
2617 (pdfjs).

We have four options:
1. enforce default value (false) <- currently what we have
2. inactive default (false)
3. enforce using an external app (true)
4. inactive use an external app (true)

FALSE
- Option 1 = current
- Option 2 seems reasonable at first glance. Change `2617: enable pdf.js...` wording to `2617: enforce pdf.js...` and make the pref inactive. This means that the default is still observed, and the js no longer meddles with experienced users' who have switched to a possibly more secure pdf reader.

TRUE
- Option 3 should not be a no no IMO. *Enforcing* an external app, we have no idea what app they use, might be a 2 yrs old adobe acrobat. They might not even have a pdf reader on their system. Not a responsible thing to do.
- Option 4 seems problematic. *Suggesting* an external app. It would encourage users to use an external app, but we provide no help with that. IMO 99% of users are best off with the internal viewer.

**Comment by Thorin-Oakenpants** [comment]
@fmarier Does the pref `extensions.blocklist.enabled` (0401) still contain updates for revoked certs? Is it even still relevant considering we have Kinto

user_pref("services.blocklist.addons.collection", "addons"); <== extension blocks
user_pref("services.blocklist.onecrl.collection", "certificates"); <== revoked certificates

**Comment by fmarier** [comment]
> Does the pref extensions.blocklist.enabled (0401) still contain updates for revoked certs? Is it even still relevant considering we have Kinto.

I don't know, I'm not familiar with that code. You could ask on [dev-security](https://www.mozilla.org/en-US/about/forums/#dev-security).

**Comment by Thorin-Oakenpants** [comment]
- [ ] move SSL Error Reporting to 1200

I am keen on this, it reduces 0400 to just blocklists, tp and sb. Where in 1200 do I position it?

**Comment by earthlng** [comment]
I only wanted to comment out the 4 "collection" prefs, not everything else too. Enforcing the blocklist updates is a good thing IMO. "Enforcing" already hints at the pref being enforced to the default value. But we can also add a `(default true/false)` in the title lines (as we already do for some items) or in the other lines of the description, or behind the pref: `"pref.enabled", true); // default: true`

**Comment by Thorin-Oakenpants** [comment]
I just can't win with you girls. I am about to do commit which adds subsection headers (like we did in 1200s). The section title is immaterial now. Would you like

```js
/** BLOCKLISTS ***/
/* 0401: enforce extension blocklist, but sanitize blocklist url
 * [NOTE] It now includes updates for "revoked certificates"
 * [1] https://blog.mozilla.org/security/2015/03/03/revoking-intermediate-certificates-introducing-onecrl
 * [2] https://trac.torproject.org/projects/tor/ticket/16931 ***/
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.blocklist.url", "https://blocklist.addons.mozilla.org/blocklist/3/%APP_ID%/%APP_VERSION%/");
/* 0402: enforce Kinto blocklist updates (FF50+)
 * What is Kinto?: https://wiki.mozilla.org/Firefox/Kinto#Specifications
 * As Firefox transitions to Kinto, the blocklists have been broken down into entries for certs to be
 * revoked, add-ons and plugins to be disabled, and gfx environments that cause problems or crashes. Use
 * .update_enabled as a master switch or remove the .collection name to disable each individually ***/
user_pref("services.blocklist.update_enabled", true);
user_pref("services.blocklist.signing.enforced", true);
   // user_pref("services.blocklist.onecrl.collection", ""); // revoked certificates
   // user_pref("services.blocklist.addons.collection", "");
   // user_pref("services.blocklist.plugins.collection", "");
   // user_pref("services.blocklist.gfx.collection", "");
```

this means blocklists we are making it clear that we do not condone turning them off

**Comment by earthlng** [comment]
> will fix 0300 title when I deal with auto-update checks

Why? I think it fits nicely on that section. I was only talking about 0400 where it doesn't seem to fit anymore.

**Comment by Thorin-Oakenpants** [comment]
I'm doing it ^^

**Comment by Thorin-Oakenpants** [comment]
> Why? I think it fits nicely on that section. I was only talking about 0400 where it doesn't seem to fit anymore.

See topic on auto-updates - i made a note for myself to remove the [Part 1] bit and *maybe* a better title

**Comment by earthlng** [comment]
`extensions.blocklist.enabled` should be set to true IMO, same as we had before your most recent change.
the title for 0402 isn't quite right with all the prefs in there. Maybe something like this (?)...

```js
/* 0402a: enforce Kinto blocklist updates (FF50+)
 * ... ***/
user_pref("services.blocklist.update_enabled", true);
user_pref("services.blocklist.signing.enforced", true);
/* 0402b: disable unwanted/unneeded parts of the blocklists
 * .... ***/
   // user_pref("services.blocklist.onecrl.collection", ""); // revoked certificates
   // user_pref("services.blocklist.addons.collection", "");
   // user_pref("services.blocklist.plugins.collection", "");
   // user_pref("services.blocklist.gfx.collection", "");
```

**Comment by earthlng** [comment]
oh, only the` [Part 1] `bit, I see, yeah nothing wrong with that

**Comment by Thorin-Oakenpants** [comment]
thanks for that, forgot the false=>true bit - all done

I will now do subheaders for SB and TP. SB will get proper numbers 0410, 0411 etc

**Comment by Thorin-Oakenpants** [comment]
OK .. so many changes ... yes or no, leave as it or move the collection parts to 0403?

**Comment by earthlng** [comment]
I didn't check, that's why I used 0402 a+b, but yeah if 0403 is free, that's fine too

**Comment by earthlng** [comment]
> "QUIET FOX" ... describes the section's purpose correctly.

I agree 100%, please don't change it - I like it, a lot! :)

**Comment by Thorin-Oakenpants** [comment]
^^ 0400 is already renamed - 0300 can keep it though

**Comment by earthlng** [comment]
lol, this form of communication causes sooo much problems. I meant please keep "quiet fox" for 0300.
since I myself suggested changing the title for 0400 I assumed it was clear what I meant, but yeah, sorry. shit happens

**Comment by earthlng** [comment]
> I see [Warning] as informing people that using this pref either causes breakage or adds risk

I have a bit of a problem with "or adds risk" because it's really hard to determine that. IMO [WARNING] should mean "can/will cause breakage" only.
That's also what I understand the line at the top of the file means:

> Search this file for the "[WARNING]" tag to troubleshoot or prevent SOME common issues

.. no mention of "or adds risk" in that. I think only very few items/prefs need a Warning tag that way, fe the disable cookie. If it should also mean "or add risk" then we would need to maybe add a lot more.
If something needs special mention ie. risk or something like that, it should be behind [NOTE] IMO

**Comment by Thorin-Oakenpants** [comment]
^^ I understood that. But it has ramifications - QUIET FOX [PART 1] with no part 2 anywhere would look stupid - hence I brought that up :)

Go look up what a WARNING is: it's implied

**Comment by earthlng** [comment]
IMO 0400 shouldn't have a WARNING tag because we basically already yell that at the reader in the readme point 2 at the top of the file:

> IF YOU MODIFY SECTION 0400 AND DISABLE TP+SB, YOU MUST HAVE uBLOCK ORIGIN INSTALLED

**Comment by Thorin-Oakenpants** [comment]
We can look at that later. I will probably remove it. Since TP+SB FF defaults are not changed by the js, and once I do the same for auto-update checking, then the big scary warning can go.

**Comment by Thorin-Oakenpants** [comment]
quick review dude

```js
/** TRACKING PROTECTION (TP)
    There are NO privacy concerns here, but we strongly recommend to use uBlock Origin as well,
    as it offers more comprehensive and specialized lists. It also allows per domain control. ***/
/* 0420: enforce Tracking Protection in all windows
 * [1] https://wiki.mozilla.org/Security/Tracking_protection
 * [2] https://support.mozilla.org/en-US/kb/tracking-protection-firefox ***/
   // user_pref("privacy.trackingprotection.pbmode.enabled", false); // private browsing pref
user_pref("privacy.trackingprotection.enabled", true); // enforces ALL windows if true (not just private)
/* 0421: enable more Tracking Protection choices under Options>Privacy>Use Tracking Protection
 * Displays three choices: "Always", "Only in private windows", "Never" ***/
user_pref("privacy.trackingprotection.ui.enabled", true);
/* 0422: use "basic" or "strict" tracking protecting list - ONLY USE ONE!
 * [SETTINGS] Options>Privacy>Use Tracking Protection>Change Block List ***/
   // user_pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256"); // simple/basic
   // user_pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256,content-track-digest256"); // strict
/* 0423: disable Mozilla's blocklist for known Flash tracking/fingerprinting (FF48+)
 * [1] http://www.ghacks.net/2016/07/18/firefox-48-blocklist-against-plugin-fingerprinting/
 * [2] https://bugzilla.mozilla.org/show_bug.cgi?id=1237198 ***/
   // user_pref("browser.safebrowsing.blockedURIs.enabled", false);
/* 0424: disable Mozilla's tracking protection and Flash blocklist updates ***/
   // user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
   // user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
```

will do SB subsection next. Is the subsection indent OK or do I add `*`

**Comment by earthlng** [comment]
we first need to decide if "enforce" means "enforce the same values as Firefox's default value", or not.
If we want to use it that way then 0420 should not be titled "enforce" but only "enable".
Either way I think we need to split up the 2 prefs in 0420, because it's against "our logic" atm ie. enforce in title->pb.enabled;false
The rest looks good, but don't take my word for it - I'm pretty tired atm

> Is the subsection indent OK or do I add *

you decide. you're in charge of formatting decision. I think atm we don't have *'s for section titles/descriptions or subsections, but feel free to change that

**Comment by Thorin-Oakenpants** [comment]
Enforce to me is just a word. It usually has a verb (or implied verb) after that which describes the effect of the preference+value

eg 
```js
/* 0401: enforce (using <- verb implied) extension blocklist
user_pref("extensions.blocklist.enabled", true); // ff default

/* 0910: enforce disabling autofilling saved password on HTTP pages and show warning (FF52+)
user_pref("signon.autofillForms.http", false); // ff default

/* 1222: enforce (using<-verb implied) strict pinning
user_pref("security.cert_pinning.enforcement_level", 2); // NOT ff default
```

**Comment by earthlng** [comment]
Ok, np, was only an idea. It IS just a word but we _could_ give it _that_ meaning, but we by no means `have to`. Ok, enforce is just a word then (agreed?).
But 0420 is still weird if the title says enforce and one of the 2 prefs is commented out and set to false. I'd say we either split it into 2 numbers (:thumbsdown:) or simply activate the 2nd pref too and set it to true (pb.enabled;true) (:thumbsup:). Either way we should clarify that one is default false in FF atm and the other one is default true in FF atm. Just do whatever changes you want and I'll do a side-by-side compare later today with the latest version and the old unchanged version and then get back to you.

**Comment by earthlng** [comment]
> Ok, enforce is just a word then (agreed?).

to clarify, I only brought it up because it could IMO be confusing if we randomly use enable, disable and (for no reason) sometimes "enforce".
the way I look at it is, a feature that's disabled by default in Firefox can be (a) enabled or (b) force-disabled ie "enforced" (and vice-versa if a feature is enabled by default in FF)
Everything we have in the user.js is "enforced" in a way anyway. If "enforced" is _just a word_ then we should stick to `enable` and `disable` IMO

**Comment by Thorin-Oakenpants** [comment]
Yes, enforce is just a word

---
not sure if you're looking at my now deleted post in here, or what I actually committed. The effect is TP is enforced. No way do I want 2 numbers (thumbs down as you said) - this is 2 prefs which give three options so best to keep them together. But you're right, looks a little weird.

commit
```js
/* 0420: enforce Tracking Protection (to disable set both prefs as false)
 * If .enabled = true then .pbmode.enabled is IGNORED and TP is enabled for ALL windows
 * If .pbmode.enabled = true (and enabled = false) then TP is Private Browsing windows only
 * [1] https://wiki.mozilla.org/Security/Tracking_protection
 * [2] https://support.mozilla.org/en-US/kb/tracking-protection-firefox ***/
   // user_pref("privacy.trackingprotection.pbmode.enabled", true); // private browsing pref
user_pref("privacy.trackingprotection.enabled", true); // enforces ALL windows if true (not just private)
```

mod - just make the first pref active - thumbs up if you agree. It will have no effect and the info is in the description
```js
user_pref("privacy.trackingprotection.pbmode.enabled", true); // PB mode only, if next pref is false
```

**Comment by earthlng** [comment]
/* 0420: ~~enforce~~ enable Tracking Protection ~~(to disable set both prefs as false)~~
 * If .enabled = true then .pbmode.enabled is IGNORED and TP is enabled for ALL windows
 * If .pbmode.enabled = true (and enabled = false) then TP is Private Browsing windows only
 * [1] https://wiki.mozilla.org/Security/Tracking_protection
 * [2] https://support.mozilla.org/en-US/kb/tracking-protection-firefox ***/
user_pref("privacy.trackingprotection.pbmode.enabled", true); // ~~private browsing pref~~ default: true
user_pref("privacy.trackingprotection.enabled", true); // ~~enforces ALL windows if true (not just private)~~ default: false

note:
* enable instead of enforce (see above ;)
* drop `(to disable set both prefs as false)`
* changed comments behind the prefs - no need to repeat what the description already makes very clear, but instead let users know which ones are enabled/disabled by default in Firefox
* and yes, "activate" the 1st pref too to be in line with the title ("enable TP")

**Comment by Thorin-Oakenpants** [comment]
already have another issue in for bulk replacement of words in favor of enable/disable

**Comment by Thorin-Oakenpants** [comment]
if I drop `(to disable set both prefs as false)` then the third setting is not mentioned or shown how to achieve

**Comment by earthlng** [comment]
the third setting?

**Comment by Thorin-Oakenpants** [comment]
Three settings:
- disabled
- enabled for PB mode only
- enabled for ALL windows

**Comment by earthlng** [comment]
`If .enabled = true then .pbmode.enabled is IGNORED and TP is enabled for ALL windows`

Are you sure that .pbmode.enabled is IGNORED in that case?? Even if .pbmode.enabled is false?

> Three settings:

yeah, but come on, the pref names are pretty easy to understand, aren't they? They both end in .enabled - how hard can it be to figure out how to disable them? :)

**Comment by Thorin-Oakenpants** [comment]
> Are you sure that .pbmode.enabled is IGNORED in that case?? Even if .pbmode.enabled is false?

I no longer know dude. I've almost had enough of section 0400.

> yeah, but come on, the pref names are pretty clear, aren't they? They both end in .enabled - how hard can it be to figure out how to disable them? :)

Some people are stupid and there is nothing I can do about it

**Comment by Thorin-Oakenpants** [comment]
OK simple test
- Open about:config, type in privacy.trackingprotection*enabled, rest the two prefs
- Go to Options>Privacy>Use Tracking Protection
- Change from PB only to Always
- `privacy.trackingprotection.pbmode.enabled` stays at true
- Change from Always to Never
- Change `privacy.trackingprotection.pbmode.enabled` to false
- Change from Never to Always - both prefs get changed to true

So I guess both must be on for ALL windows to be on.

**Comment by Thorin-Oakenpants** [comment]
I'm changing it to this - people can work it out for themselves
```js
/* 0420: enable Tracking Protection
 * [1] https://wiki.mozilla.org/Security/Tracking_protection
 * [2] https://support.mozilla.org/en-US/kb/tracking-protection-firefox ***/
user_pref("privacy.trackingprotection.pbmode.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
```

**Comment by earthlng** [comment]
I've looked at the new 0400 and these are my nits:

* `0401: enable extension blocklist, but sanitize blocklist url` - _extension blocklist_ sounds like it is a blocklist for blacklisted extensions, but it's just the "old" but still used version of the blocklist ie it contains blocked addons, plugins, gfxitems and revoked certs. (open blocklist.xml in an editor and see for yourself)
   * a better title would be "enable Firefox' blocklist" for example
* the default indicators (that you already said you don't want to add) would be nice for 0420 + 0422

the rest is nice - good work! thx!
