### ISSUE TITLE
Starting in Work Offline Mode

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#117]
I've been working on a related user.js for a profile to load local files.  The idea is for it to load fast, be relatively secure, and not access the internet at all.

Do any of you know if there is a pref to start Firefox in Work Offline mode?

I've tried a handful of prefs, but nothing has worked so far...

**Comment by RoxKilly** [comment]
Don't know the answer, but just curious (b/c I've never used Offline mode): is the idea that the user will start the browser in Offline mode, then use a UI switch to disable Offline mode, then navigate to the internet?

**Comment by crssi** [comment]
What do you mean with no Internet access?
You could "play" with the manual proxy, setting it to idk 127.0.0.1 and you can also set an exclusions there.

**Comment by earthlng** [comment]
> I've tried a handful of prefs, but nothing has worked so far...

have you tried `network.online`?

**Comment by Gitoffthelawn** [comment]
@RoxKilly wrote:
> Don't know the answer, but just curious (b/c I've never used Offline mode): is the idea that the user will start the browser in Offline mode, then use a UI switch to disable Offline mode, then navigate to the internet?

@crssi wrote:
What do you mean with no Internet access?

Ah, I see more info is needed.  The idea is to have a truly offline browser to only browse local HTML files.  The intention is to never allow these files to connect to the internet, even if the user clicks on a link.

"Why?" you may ask.  One common situation is if your browser is closed, and then you run application XYZ.  In the process of using XYZ, you click on something (perhaps Help) that needs to load an HTML file.  Traditionally, your default browser will then load, and the appropriate local file would be opened.  Depending on the system, this can be relatively slow, as all add-ons will be loaded.  Furthermore, the interface will be cluttered with all your unneeded add-ons (unneeded for the task of simply viewing a local HTML file).

From a privacy and security point of view, allowing that local HTML file to access the internet is often a bad idea.  The local HTML page can easily transmit data about the local system to external servers without your consent.  **This is a trivial way that applications can bypass many firewalls.**

@crssi mentioned setting the proxy to 127.0.0.1.  I've been experimenting with this, but of course, it won't be advised for any systems running a server on that address.  I recall that there is an RFC that provides an actual IP address that is never valid.  *Does anyone know that RFC or IP address?*

Overall, it would be best just to start the browser in Work Offline mode.  There used to be an extension, called Work Offline, that would do just that.  It's no longer on AMO.  I would prefer just a simple pref to get the job done (easier to set up the profile without having to add an extension), but I suppose an extension would be okay.

P.S. As I am writing this, @earthlng just posted:
> have you tried `network.online`

Thanks. I have, and it didn't enable Work Offline mode.  But I'll take a second look at it.

**Comment by crssi** [comment]
Block it as application on firewall.

**Comment by Gitoffthelawn** [comment]
@crssi wrote:
> Block it as application on local firewall.

You mean block Firefox or block Application XYZ?

Blocking Firefox won't work if you also want, separately, to use Firefox as an internet browser.

For most (but not all) firewalls, blocking Application XYZ won't work, because once it opens an HTML file in Firefox, Firefox will (generally) have internet access.

**Comment by Atavic** [comment]
For Seamonkey -offline as argument is listed [here](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options)

I have a similar idea implementation:
Install Netscape 9.0.0.6
Set it as default browser, block it on the firewall and use it locally only.

If something launches an URL on your default browser, it's blocked.

**Comment by Thorin-Oakenpants** [comment]
Soz, quick reply before I skule-skoll-scoll (I cannot spell that word) my coffee and head out for date night

Take a snapshot of prefs.js, go File>Work Offline, then compare live prefs.js with snapshot prefs.js - there is no difference. I do not think this is behind a pref at all, but rather a state held in memory

----
NOTE: I guess you may want to make sure this is true. Also, if you read that second link about events, you will see that it is triggered internally when it detects a change in connectivity (eg after a user action, eg site will not load, dns not returned etc, I guess)
```js
/* 3013: disable automatic "Work Offline" status
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=620472
 * [2] https://developer.mozilla.org/en-US/docs/Online_and_offline_events ***/
user_pref("network.manage-offline-status", false);
```

---
https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options - I do not think there are any startup options for you on this

---
I think this is the wrong approach (but I haven't had time to digest it all. The default program associated with htm(l) files is Firefox. Firefox will always open in Online mode. Even if you could start it in Offline Mode, whats to stop the user from accessing the menu, changing the mode, and leaving the browser open. I fully understand that the user must be able to access the internet.

- Find a solution (extension?) that if a local file is opened, FF is changed to offline mode (not foolproof)
- Denies all other sources - eg some rule if `file:///` is used then deny all `https` and `http` (more robust)

**Comment by Thorin-Oakenpants** [comment]
uMatrix uses `file-scheme` - not sure if a rule here would work to block all other sources. Also, then every workstation's FF would need uMatrix (and yes, I know how terribly slow and shitty enterprise workstations can be - older PCs depreciated multiple times over their value to minimize tax, save money etc - as long as the CEO has the latest)

**Comment by RoxKilly** [comment]
My idea is pretty much the same as @Atavic . Have a 2 browser solution. You could make Firefox Portable (or another browser) your default browser, and deny it access to the internet from a firewall. For your regular web browsing, use installed Firefox.

**Comment by Thorin-Oakenpants** [comment]
^^ And if the secondary FF is open (the one that is "online"), then it will bypass the intended block

**Comment by RoxKilly** [comment]
Didn't think of that. Guess the default would need to be another browser. Tor browser maybe? It has disabled so many things that it would probably start up fast and parse those local HTML files in a jiffy

**Comment by earthlng** [comment]
I agree with @Atavic's approach but wouldn't necessarily use an ancient Netscape to do it.
On Windows you could just make IE the default browser, block it in the Firewall and use FF for normal browsing

**Comment by Gitoffthelawn** [comment]
@earthlng FF Offline Mode WFM.

**Comment by earthlng** [comment]
@Gitoffthelawn can you elaborate? WFM I guess means "works for me"? So you can enable it in the File menu and sites don't load anymore?

**Comment by earthlng** [comment]
One thing I just noticed is that while I had Offline Mode enabled other tabs of this github page loaded just fine but didn't see the cookie anymore

**Comment by Gitoffthelawn** [comment]
@earthlng wrote:
> @Gitoffthelawn can you elaborate? WFM I guess means "works for me"?

Yep.

> So you can enable it in the File menu and sites don't load anymore?

Exactly.  Once I enable Work Offline from the File menu, FF can no longer load non-cached pages.  Instead, it provides the following message:

`Offline Mode.  Firefox is currently in offline mode and can’t browse the Web.`

**Comment by Thorin-Oakenpants** [comment]
@Gitoffthelawn Do you mean that you manually set "Work Offline". And this state is persistent, and the next time the browser is opened, it is still in Offline mode (we already know the effect of the mode)?

If so... what is to stop a user changing the mode (and not changing it back = extremely likely if they need to access to web). Or if they never change it, then they can't access the internet via the browser, which means you might as well use a more robust solution. I thought you wanted to enable both modes.

**Comment by earthlng** [comment]
> what is to stop a user changing the mode

I guess he is the only user

> FF can no longer load non-cached pages

Interesting. That doesn't work for me at all. Just checked with a site that's definitely not in my cache and I get no such message. Maybe because I'm using a proxy? idk
