### ISSUE TITLE
browser.download.folderList

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#120]
I'm struggling to see what this setting does in terms of security. PK's merely mentions a " CIS 2.3.2" which I assume is the Center for Internet Security ( https://www.cisecurity.org/ ) but I can't find anything. I can see a case for privacy, as the desktop is generally visible. I know I prefer to stash my goat porn mkv titles out of site. So is that all it is, shoulder surfers? Or is there something else?

[modified a tad as I clean up my local copy for consistency of descriptions]
```js
/* 2602: discourage downloading on desktop (0=desktop 1=downloads 2=last used)
 * [NOTE] To set your default "downloads": Options>General>Downloads>Save files to ***/
user_pref("browser.download.folderList", 2);
```

**Comment by Atavic** [comment]
It's from [Security Configuration Benchmark For Mozilla Firefox](https://www.cisecurity.org/cis-benchmarks/)
(email needed to send download link)

Disable Downloading on Desktop.
Remediation: `browser.download.folderList=2`

**Comment by Thorin-Oakenpants** [comment]
It actually doesn't disable downloading to the desktop, it just sets the initial dir used (either with "save as" or auto-saved). That benchmark list doesn't tell me WHY exactly this is a concern

**Comment by Atavic** [comment]
Because it's a standard folder and has its culprits - even on [Linux](https://github.com/DonnchaC/desktop-file-social-engineering) - as tailored shortcuts on the desktop.

**Comment by earthlng** [comment]
I use `browser.download.folderList;0` because I usually download to the desktop anyway, and with 0 it doesn't store the last path in `browser.download.lastDir`. But this pref is not very important anyway IMO because the important one to set is `browser.download.useDownloadDir` to always ask when downloading something. You changed the description in your latest commits and I think we can close this issue.

**Comment by Thorin-Oakenpants** [comment]
I just opened the issue to find out why it was such a security issue, but no-one seems to know and all I get is maybe it's because the desktop is visually always present/open and it's like a shoulder surfer thing. I still have it to revisit in Standardize Part2
