### ISSUE TITLE
Do 0906 really need to be forced to false and/or be enabled?

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#1243]
Do 0906 really need to be forced to false and/or be enabled?

Cheers

**Comment by Thorin-Oakenpants** [comment]
> then I again force the user to opposite "choice".

that's what a binary choice is. They are either forced to be true or false

> There are o365 users which would like to have SSO

That's what overrides are for. By **default**, we do not want to allow this for privacy reasons
