### ISSUE TITLE
icloud: Did Not Connect: Potential Security Issue [RFP bug: 1621729, 1618537]

### ISSUE THREAD

**Issue by RupertEverton** [ghacksuserjs/ghacks-user.js#1265]
Browser: Firefox 93.0
Affected website: https://www.icloud.com/
Screenshot: https://i.ibb.co/ZXxBkRn/screenshot.png
Error:

> Did Not Connect: Potential Security Issue
> 
> Firefox detected a potential security threat and did not continue to idmsa.apple.com because this website requires a secure connection.
> 
> What can you do about it?
> 
> The issue is most likely with the website, and there is nothing you can do to resolve it.
> 
> If you are on a corporate network or using anti-virus software, you can reach out to the support teams for assistance. You can also notify the website’s administrator about the problem.

This error manifested only after implementing user.js
I have tried setting the following parameters to false, without however resolving the issue:

```
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.resistFingerprinting.letterboxing", false);
```

Thank you in advance for your help.

**Comment by RupertEverton** [comment]
> What's under `Advanced…`?
If I click on it, nothing happens.



> https://bugzilla.mozilla.org/show_bug.cgi?id=1621729
Ah I see it's almost 2 years old. But why am I still unable to use iCloud after setting `privacy.resistFingerprinting` to false?

**Comment by RupertEverton** [comment]
>     1. Do not use `frame,redirect=click2load.html` in uB (for that site)
> 
>     2. Disable RFP (letterboxing don't care)
> 
>     3. Set XOriginPolicy=0 (XOriginTrimmingPolicy don't care)

1, I don't have uB. 2 and 3 done. Didn't work.



> Don't change everything. How are you changing them? By directly changing the value in the user.js, or using OVERRIDES?

I added one by one the values to user-overrides.js and run updater.sh to append. I never manually edited user.js 


> 
> ```js
> // my overrides: make icloud work
> user_pref("network.http.referer.XOriginPolicy", 0); // 1601
> user_pref("privacy.firstparty.isolate", false); // 4001
> user_pref("privacy.resistFingerprinting", false); // 4501
> ```
> 
> Replace your user.js with a new copy of user.js. Close Firefox, add the overrides above to the bottom of the user.js. Restart Firefox.

I tried exactly that, it still does not work.


> Personally, I would just use a secondary browser for icloud.

I might end up doing this if we can't find a solution.

Cheers

**Comment by Thorin-Oakenpants** [comment]
@RupertEverton you must have fucked something up with your settings

In a brand new profile, in Firefox 93, I added the user.js

At the end of the user.js I added these
```js
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("privacy.firstparty.isolate", false);
user_pref("privacy.resistFingerprinting", false);
```

Then I went to https://www.icloud.com/ and there were no errors and I am presented with the login form

**Comment by Thorin-Oakenpants** [comment]
that and the user.js might be a mess: sounds like the values (and lots of them) were edited instead of adding overrides at the end

@RupertEverton , if I were you I would
- replace your user.js with a new clean one
- with Firefox closed run prefsCleaner (place it in the same folder as your user.js, it's in the release download) so that everything is reset
- add the overrides to the user.js, and then start Firefox

@rusty-snake : did you log in with FPI? I don't have an account

**Comment by crssi** [comment]
> Well, you're not going to find a solution for RFP + iCloud as that would take a fix upstream at Mozilla: if that fix is feasible: they can't compromise timing mitigations. However, RFP is not everyone's cup of tea or threat model (do you hide your IP address?)

When someone does not hide IP... what benefits they get using RFP in the real world?

**Comment by rusty-snake** [comment]
security

https://github.com/arkenfox/user.js/blob/85438d00e457bff692303af519da618c6372476b/user.js#L987

---

You do not need hide your IP. But it must not be stable over a long time.

**Comment by RupertEverton** [comment]
> > Could it be that the user agent doesn't match my system?
> 
> Shouldn't be. You're not modifying it in any way. What is your userAgent? Do you mind confirming your OS and what Firefox version you're using?

Firefox 93 on Linux -- the user agent is modified after implementing user.js to Windows NT (I haven't manually edited it)



> > I tired all that on the existing profile and I still got an error. I then created a new profile, added user.js with the three edited parameters appended at the bottom but still got an error.
> 
> What was the error? Was it in the console? What's in the console (ctrl-shift-K)
> 

The error is a different one when inserting the three parameters, it still appears in the center of the page (where the login box is supposed to be): 

```
Secure Connection Failed

An error occurred during a connection to idmsa.apple.com. The OCSP server experienced an internal error.

Error code: SEC_ERROR_OCSP_SERVER_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

Console shows the following:

```
Cookie “” has been rejected as third-party. cloudkit.js
Cookie “” has been rejected as third-party. authService.latest.min.js
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://cdn.apple-cloudkit.com/ck/2/cloudkit.js
Source Map URL: resources/cloudkit.js.map
```

> Otherwise, I'm scraping the barrel, so don't get mad: 

Not at all mate, actually thanks for all the help!


> are you editing the right profile, is the user throwing errors, what does the parrot say in about:config (just search for "parrot" in about:config) - add a final line to the user.js. I assume, being a new profile there were no extensions. Do you have antivirus running?
>
> ```js
> user_pref("network.http.referer.XOriginPolicy", 0);
> user_pref("privacy.firstparty.isolate", false);
> user_pref("privacy.resistFingerprinting", false);
> user_pref("_user.js.parrot", "PROFILE X: RUPERT OVERRIDES: SUCCESS");
> ```

I can confirm I'm editing the right profile. 
Parrot: `PROFILE X: RUPERT OVERRIDES: SUCCESS`
And you're correct, new profile with no extensions - completely vanilla. No antivirus.


> Not all errors in user.js cause an abort: so you should also open the console after starting (ctrl-shift-J) and see if anything is in there
> 
> We can't replicate the issue, and need more details: otherwise we're stabbing in the dark

Ctrl-shift-J shows the following on browser opening:

```
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: resource:///modules/BrowserGlue.jsm :: _collectStartupConditionsTelemetry :: line 1624"  data: no] BrowserGlue.jsm:1624:9
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.jsm:1624
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.jsm:1731
    BG_observe resource:///modules/BrowserGlue.jsm:1013
    _delayedStartup chrome://browser/content/browser.js:2115
    _delayedStartup self-hosted:1175
```

When I open icloud.com :

```
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebNavigation.loadURI] 3 ViewSourceChild.jsm:146
    loadSourceFromURL resource://gre/actors/ViewSourceChild.jsm:146
    loadSource resource://gre/actors/ViewSourceChild.jsm:120
    viewSource resource://gre/actors/ViewSourceChild.jsm:67
    receiveMessage resource://gre/actors/ViewSourceChild.jsm:21
```

```
Status 421 Misdirected Request
Referrer Policy strict-origin-when-cross-origin
error | "Invalid or missing Origin header"
```

**Comment by rusty-snake** [comment]
> Firefox 93 on Linux -- the user agent is modified after implementing user.js to Windows NT (I haven't manually edited it)

RFP which you need to disable anyway.

> SEC_ERROR_OCSP_SERVER_ERROR

Now the question is why is the OCSP check failing for you?

**Comment by Thorin-Oakenpants** [comment]
I used to have `user_pref("security.OCSP.require", false);` in my overrides until about a year+ ago. I think people's mileage on this one varies quite a bit and I'm not sure what other factors play a role (timing, latency, ISP, cert lab being contacted? not my area sorry)

Feel free to add it to your overrides - but if it's just one website (icloud) that already requires sacrificing too many other protections/benefits, then I wouldn't ... but I consider the risk to be low if you do

**Comment by RupertEverton** [comment]
So I did some testing:

- adding `user_pref("security.OCSP.require", false);` and then also `user_pref("privacy.resistFingerprinting", false);` returned the following error, both times:
```
Firefox Can’t Open This Page

To protect your security, idmsa.apple.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.
```

- adding `user_pref("network.http.referer.XOriginPolicy", 0);` and `user_pref("security.OCSP.require", false);` did not show any error, but neither the login box; instead I was presented with the "loading" wheel.

- adding all three parameters worked, I was finally shown the login box.

However if disabling these three parameters is what's necessary to make just one website work, I'll follow your advice of using an alternative way to use icloud.

Cheers to everyone!
