### ISSUE TITLE
0374: Social API

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#136]
Investigate moving these to section 9999

https://developer.mozilla.org/en-US/Firefox/Releases/48#Changes_for_add-on_and_Mozilla_developers

> The Social Worker API has been removed

```js
/* 0374: disable "social" integration
 * [1] https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API ***/
user_pref("social.whitelist", "");
user_pref("social.toast-notifications.enabled", false);
user_pref("social.shareDirectory", "");
user_pref("social.remote-install.enabled", false);
user_pref("social.directories", "");
user_pref("social.share.activationPanelEnabled", false);
user_pref("social.enabled", false); // (hidden pref)
```

**Comment by earthlng** [comment]
well the prefs still have a value when you reset them in about:config in FF53.0.3

**Comment by Thorin-Oakenpants** [comment]
I haven't tested - just threw this up as a reminder to follow up on. I read somewhere that some code remains, but its basically no longer used

https://dxr.mozilla.org/mozilla-central/search?q=social.&redirect=false

I keep using the word legacy, and I don't think I'm using it right
- deprecated = removed?
- legacy = still there but not used?
- ^^ Thats how I've been using these terms and I think I have it wrong with all you young whipper-snappers (in my fortran days I was better understood!)

**Comment by earthlng** [comment]
[quoting](https://github.com/ghacksuserjs/ghacks-user.js/issues/5#issuecomment-280871726) Francois

> "Deprecated" usually means it's still there but not for long and you should stop using it. It's the step before the actual removal :)

**Comment by earthlng** [comment]
> > The Social Worker API has been removed

yes but there are a bunch of other ones still available:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API

**Comment by Thorin-Oakenpants** [comment]
I'll try and use the right term. So when I say legacy do u all think I am saying the code is "removed" ?

**Comment by earthlng** [comment]
> So when I say legacy do u all think I am saying the code is "removed" ?

To me legacy means code that's not used anymore but nobody bothered to remove it yet or it's kept around because there are plans to re-use parts of it again in the future or to bring back that functionality

**Comment by Thorin-Oakenpants** [comment]
That's what it's always meant to me too, but then when I use it, people say .. "but its still in the code", so IDK, I guess I'll be more precise and use long sentences instead of a single word

**Comment by Thorin-Oakenpants** [comment]
Oh man .. snap. Not paying attention, I totally missed the word "worker" in "The Social Worker API has been removed". All those prefs are still in DXR and bar the first two, all totally look they do things. So nothing to do here, closing.
