### ISSUE TITLE
POLL: 57 vs ESR

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#139]
At this stage I think I'm just going to bite the bullet and go full on 57, as not all changes make it to ESR. I think I can live without the legacy add-ons and quickly find replacements - it may just be a couple of releases of slightly painful testing and waiting, but I think it will quickly catch up - notwithstanding the loss of some add-on functions which can't be replaced.

I do hope some regulars decide to go ESR, so that way we can have feedback on both - not that we can't work out which prefs apply to which, but it sure helps to have a wider test-bed.

Am just curious as to where people think they will go.

:heart: for ESR
:+1:  for 57

**Comment by Thorin-Oakenpants** [comment]
I have a couple of provisos tho: I might hang back in my main live FF on v56 for 4 or 5 weeks and also, without exception, uBo + uMatrix + NS WebExtensions must be ready for prime time.

**Comment by atomGit** [comment]
i'll likely be going the ESR route - too many extensions that can't be ported

at this point i'm keeping a keen eye open for a non-chrome, privacy friendly browser - the only reason i still stick with mozilla is because of the extensions and customization capability - as for the company itself, i have near zero respect anymore

**Comment by Thorin-Oakenpants** [comment]
I'll stick with mozilla simply for all the privacy features/tweaks, no-one else comes close. Even if FF only had 1 extension (uMatrix), I'd stick with it (and gorhill has that covered, and uBo). I do have 2 other portable browsers I use for one off sites and bits and bobs on a daily basis -  chrome (pizza orders and some backend mySQL, myPhp stuff), and opera (couple of sites, everything else that won't work in FF, and the VPN comes in handy) - ditched everything else

**Comment by Gitoffthelawn** [comment]
Isn't ESR only going to support "legacy" extensions for the first ESR (and subsequent bugfixes)?  IOW, once the next ESR is released, won't it be WebExtensions-only?

**Comment by Atavic** [comment]
Yes. [ESR52](https://blog.mozilla.org/addons/2017/02/28/compatibility-for-firefox-53/) for me.
Then it will be Pale-Moon.

**Comment by Gitoffthelawn** [comment]
People can let Mozilla know their opinions, and provide feedback, here: https://input.mozilla.com

**Comment by zymase** [comment]
Running FF ESR here (52.2.0 now) because I most likely will not jump to FF 57 when it arrives in November. This way I have the time to build my decision calmly as to what I'll choose at 52ESR's EOL : either make the move to FF "standard" either switch to another default browser, presumably Waterfox or maybe (really "maybe") Pale Moon.

**Comment by earthlng** [comment]
Has anyone else noticed problems with missing favicons in FF54? f.e. github?

**Comment by earthlng** [comment]
btw I read somewhere that FF55 will include changes to the profile that are incompatible with earlier versions, meaning that if you want to move to ESR before 57 hits you're likely gonna lose all your bookmarks and/or history. Bookmarks can be exported and re-imported but history (afaik) will be gone.

**Comment by Gitoffthelawn** [comment]
@earthlng If you find a link to that info, please post it. :)

**Comment by earthlng** [comment]
you don't believe me, eh? :) here you go: https://bugzilla.mozilla.org/show_bug.cgi?id=977177#c78

> ... It's not possible to downgrade a newly created profile to a previous Firefox version.

I assume this will also be the case for a "migrated" profile, not just "newly created". IDK if history or bookmarks are lost though, maybe it'll keep working but without favicons.
Since I'm planning to move to ESR anyway, I might as well do it now already and not risk losing anything. That's why I made the comment above.

**Comment by earthlng** [comment]
I wrote "likely gonna lose all your bookmarks and/or history." because places.sqlite is the only file with any meaningful data in it that could be impacted by the change, and since that stores all the bookmarks and history I felt it's reasonable to assume that it could "likely" break. Yeah, yeah, maybe a bit of FUD but better safe than sorry, right? ;)

**Comment by Thorin-Oakenpants** [comment]
There are already parts of "legacy" that are being removed/deprecated well before 57. Already legacy addons are breaking, for example - pure url, no resource uri. People are in for a rude shock. I think shims get removed soon too

**Comment by Thorin-Oakenpants** [comment]
> Has anyone else noticed problems with missing favicons in FF54? f.e. github?

Not me. The github favicon is dark, and I use a dark theme - it's almost invisible.

**Comment by earthlng** [comment]
Do you have missing favicons, Pants? fe. github + ghacks don't have icons on the tabs anymore recently, nobody else have this problem?

**Comment by Thorin-Oakenpants** [comment]
^^ See above

**Comment by earthlng** [comment]
It's only on the tabs itself that the icons don't show. Bookmarks and history are (mostly) okay. Thanks, it helps to narrow it down if I'm the only having this problem.

**Comment by Thorin-Oakenpants** [comment]
Re https://bugzilla.mozilla.org/show_bug.cgi?id=977177#c78

I do not see a problem with this. If a user rolls back, they will lose their favicons. Guess what. They come back when you visit the bookmark - big deal. I wiped all mine in testing (deliberately) when we did the cache & favicons revamps. I didn't lose any sleep over it (Side note: I only have about 30 bookmarks xD)

**Comment by Gitoffthelawn** [comment]
@earthlng Thanks for the link.  :)

**Comment by earthlng** [comment]
@Gitoffthelawn You're welcome. It's now also mentioned [here](https://www.mozilla.org/en-US/firefox/55.0beta/releasenotes/) (referring to the same thing I assume)

> Breaking profile changes - do not downgrade Firefox and use a profile that has been opened with Firefox 55+.


To whom it may concern, my favicon problem was caused by the following rule in uBO's Fanboy’s Enhanced Tracking List: `/favicon.ico$image,third-party,domain=~reddit.com`

**Comment by Thorin-Oakenpants** [comment]
I'm going to use this issue to spam you all with my experiences in getting ready for 57 - only 4 months to go. I want to be ready to rock n roll and used to it, so no time to piss around

- I ditched FT Deep Dark, and am using Compact Dark. Benefits include a decent current tab indication/color (I previously used a stylish script to change the text color for use with FT Deep Dark), and also containers now properly display their color in the tabs, as well as icons in menus and preferences. But since it's not a full theme, things like internal pages, menus, link info bottom right when hovering, etc etc are all bright etc. Getting used to it. Been a few days.
- I used Scrapbook X in an always showing sidebar. Without FT Deep Dark, it's coloring is ugggh (I'm a vampire, hate that bright shit), so now I hide it and use alt-k to pull it up when I need it (which may be a couple dozen times a day) - that's OK for now (Scrapbook X will not be made into a WE by the way, but that's a different obstacle for me to overcome later)
- One thing I used Scrapbook for, was a for a couple of "Notes" where I kept bits and pieces for copypasta. The ones I use All. The. Time. I instead put in a new Web Extension called [Note Taker](https://addons.mozilla.org/en-US/firefox/addon/note-taker/). Its on the nav bar far right and is uber handy and quick - its actually better for me personally because the width is wider than my sidebar used to be, but of course it's a single "note" (maybe it will be expanded on later)
- With the removal of the sidebar, the browser is not as wide - muscle memory is a slight issue as 1) the browser window is no longer in the exact same position, and the navigation toolbar has changed (more scrunched up - less room for the urlbar, searchbar)
- To compound matters, since I have less width, I removed extension buttons I hardly ever use. On my navigation toolbar on the far left, I used to have HTTPS Everywhere and Screengrab (fix version). Both of these are wide with dropdown menus. I have never needed to use HTTPS Everywhere in the last year or so, and screengrab is not that often. Instead I can access them via the Tools menu. This freed up a bit of real estate and now the urlbar is a lot further left (something I click in hundreds of times a day) - so muscle memory. What's that key combo to jump to urlbar?
- Note: I use the bookmarks toolbar like this
   * [extension icons] [space] [space] [a few uber regular bookmarks] [right-aligned extension bookmarks]
- I got rid of a menu editor extension (I forget the exact name now, s3 something). As my extensions shrank over time, I have found I don't really need to clean them up, especially context ones. Not missing it at all. Some slight muscle memory issues, but used to it now.
- Disabled all the tweaks in CTR that aren't controlled by an internal pref - except a couple. 1) old search enabled so I can use lists and not fucking buttons which auto-load the search site when sleected 2) couple of settings about back-forward buttons & reload (I need to test this a bit more - last time the additional button makes the urlbar shove to the right and when not there, it slides back to the left - what a shitty concept, just disable the button, don't hide it). Done away with a restart option in menu. Did away with the status bar months ago.
- Did away with Slim Addons Manager and a couple of user styles. While I used to get 25 extensions listed in my current 1366x768 window, I now get 11. Big deal. Its not like I'm in there very often
- Ditched about 20 other user styles I wrote which were for hiding crap, and instead now use cosmetic filters in uBo - this is preparation of moving to Stylus (I do not trust the mofo who owns Stylish if and when he ports his shitty chrome version to AMO). The remaining styles are all custom ones, cept one, about 20, for making websites "dark"

I am slowly ditching non WE extensions .. either going without, or testing replacements. Will keep you all posted

Next up: (stay tuned, same time, same channel, next week)
- About to move to Violent Monkey
- About to move to Cookie Auto-Delete

PS: FF, and I'm only on 54, is really becoming a hell of a lot snappier

**Comment by Thorin-Oakenpants** [comment]
Here's a picture

![musclememory](https://user-images.githubusercontent.com/16656956/28624020-e21eccd4-726b-11e7-9b5c-096188d37b4d.png)

Frequently accessed extensions are top left bookmark toolbar - uM, uBo, NS, Cookie Controller, GM, Stylish, Request Control. Far right navbar are eCleaner (testing it) and my Note Taker. I can add some more if need be underneath these two.

Bookmarks toolbar I try to keep clean as possible, just for some uber-used items or something I need to check/test/follow-up on. FYI - I check my res once a day .. its kinda like an OCD thing now xD. Seriously, I've developed OCD with it. The about folder contains links to some regular about pages including about:about. The WS is a wilders security followup, the ET is that ETag test page, and the FF reddit page is this one: https://www.reddit.com/r/firefox/

Also FYI: the home page shown is FVD Speed Dial but hidden (double click), which is where I have 12 tabs with up to 72 dials per tab before scrollbars show. Since the inner window is still the same 1366x768 I have used for so long now, muscle memory is not an issue - yet!

**Comment by stevesharp** [comment]
Jump between Nightly 56, and Firefox 54 here (Only use 54 for Evernote clipping, and when Nightly gets broken). Nightly feels so much faster than 54 that I find it hard to default to 54.  I also like the photon UI in 56.

Down to 5 non-WE here - UBlockOrigin, uMatrix, Canvas Blocker, Decentraleyes, HTTPS Everywhere

**Comment by Gitoffthelawn** [comment]
@stevesharp How does 55 beta compare to 54 release and 56 nightly in regards to performance?

**Comment by stevesharp** [comment]
Performance on beta is pretty much the same as 54, other than the initial start up being faster as it is lazy loading tabs.  The features in this release of beta aren't the major ones giving performance benefits in Nightly as far as I can tell.

https://www.mozilla.org/en-US/firefox/55.0beta/releasenotes/

**Comment by Thorin-Oakenpants** [comment]
Awww poop .. Stylus uses indexedDB

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants Just use userchrome.css and usercontent.css.  Best performance.

**Comment by Thorin-Oakenpants** [comment]
@Gitoffthelawn I'm not interested in the UI, I am interested in tweaking content by domain

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants That's what userContent.css is designed for.

**Comment by Thorin-Oakenpants** [comment]
CA-D: does not work with `privacy.firstparty.isolate` - [Issue](https://github.com/mrdokenny/Cookie-AutoDelete/issues/75) | [1381197](https://bugzilla.mozilla.org/show_bug.cgi?id=1381197)

I can probably get away with not using an addon - site exceptions is good enough. But man, its one thing after another - indexedDB for Stylus, dom storage for eCleaner, FPI for CA-D .. wot's next?

**Comment by Gitoffthelawn** [comment]
Yes, the whole browser storage thing is a true mess.  They need to deprecate almost everything and have a single standard that works and is transparent.

**Comment by Thorin-Oakenpants** [comment]
CTR (which I am still using for only two tweaks) will break in 56 for "using old search" .. great. I was hoping the new 57 search would render this obsolete. I will have to change how I use the search bar - because selecting an icon auto loads the web page (even if no text is in the search bar), and this is problematic - I will have to make sure the tab I am on is blank if I want to keep my current web page when I change engines, I will have to make sure any old search text is cleared first or altered to the new one before I change engines .. etc.

Maybe I'll rethink the whole thing and load a local html with my search engines in it

**Comment by Thorin-Oakenpants** [comment]
Cookie Controller is now removed. I also deleted all entries in my cookies exceptions (they were added via cookie controller's interface and included items with "allow as first part only" which is not a FF option). If items were not added via CC's interface they did not work with CC. So clean slate. Removed CC prefs in about:config as well. Turned on default block for all cookies in uMatrix as well (as I may have to allow cookies in about config - damnit - more on that later).

Everything is working perfectly. 6 sites, 6 cookie exceptions (4 allow, 2 allow for session) .. running nicely.

uBo WebExt (i think) uses dom ... it uses this to hold the advanced settings ... fuuuuuuuu.. I hope I read that wrong. - see `https://github.com/gorhill/uBlock/issues/2795` re Background Page LocalStorage

**Comment by Thorin-Oakenpants** [comment]
Bye bye FindbarTweak. I loved ctrl-F to toggle the findbar (whether it had focus or not). Without FBT now I'll simply have to train myself to use Esc when the findbar has focus. I will also miss the indicator of where the next matches were (like marks on a ruler in the left hand margin)

I set my user js to include
```
// Findbar
user_pref("findbar.modalHighlight", true);
user_pref("findbar.highlightAll", true);
```

modal is the yellow coloring and dimming of the background, just hit enter again (in the findbar) to jump to the next result. At first it didn't seem to work, but now functions just sweet as can be after a restart.
--

Bye bye Screengrab (fix version). This was a really good addon. I will miss the "Copy to clipboard" (great way to show stuff in emails), but that's about it. Screenshots is not quite as sophisticated but will develop (eg full page was removed from 55 as it wasn't quite ready). Screenshots has a really cool snapping to dom elements.

So that's all for this week folks. two more dinosaur addons vanquished :) Remember to tune in next week, same time, same channel

**Comment by Thorin-Oakenpants** [comment]
@zymase How many addons do you have now bro? 80?

**Comment by zymase** [comment]
@Thorin-Oakenpants the number is variable. At this time I have:

Add-ons: 68
User Scripts: 9
User Styles: 52 (many for per-site cosmetic)
Appearance: none
Plugins: none
Dictionaries: 1 (French because I default FF to English)
Custom Buttons: 13 (built with the Custom Buttons FF legacy add-on (not portable to WebExtensions: cries)

Now ain't that nice? I also have 2 cats, 3 dogs and 4 women, a sens of humor (one only) and a tremendous lack of money, LOL!

.

**Comment by Thorin-Oakenpants** [comment]
Holy cowabunga dude! 2 cats AND 3 dogs? That's insane. I'm down to 1 cat, no dogs, 1 partner (the same one I had 75 years ago), and 24 addons active with 4 more WE disabled for testing. My sense of humoUr dried up (its very dry).

> User Styles: 52 (many for per-site cosmetic)

Flick those to uMatrix, more efficient I believe

**Comment by crssi** [comment]
Nah... even when you think you don't have sense of humor, you still have, at least for me. :)

**Comment by Thorin-Oakenpants** [comment]
I keep forgetting crssi .. its lost in translation - [dry humor](https://en.wikipedia.org/wiki/Dry_humor) is a type of humor

> Deadpan or dry humor/wit[1] describes the deliberate display of a lack of or no emotion, commonly as a form of comedic delivery to contrast with the ridiculousness of the subject matter. The delivery is meant to be blunt, sarcastic, laconic, or apparently unintentional.

.. apparently unintentional ... 

PS: I am going to put a dollar in a jar everything I teach crssi some idiom or slang :) Each week I will spent it on beer and get smashed

**Comment by crssi** [comment]
LOL, you have got me again. :)
I am learning a lot from you every day. And I will not dare to touch your soapbox again. :)

**Comment by zymase** [comment]
Somewhere in between Oscar Wilde and Voltaire, if such a portrait is reliable when drawn from a few words free of our computing topics and obsessions :)

**Comment by Thorin-Oakenpants** [comment]
> Somewhere in between Oscar Wilde and Voltaire

So `gay` and `electrifying` .. great! Unless you meant the large drunk percentage of Wilde's life in which case .. yup! That's me!

We're getting so OT

**Comment by zymase** [comment]
Voltaire and Oscar Wilde had much in common, to what I referred when quickly elaborating on this approach of dry humor...

> [...] a form of comedic delivery to contrast with the ridiculousness of the subject matter. The delivery is meant to be blunt, sarcastic, laconic, or apparently unintentional.

The targets of their less dry humor may have been different they nevertheless shared a common approach, such as a blend of sarcasm and kindness. I believe they were both intelligent and romantic, but shy of demonstrating either. It's less with whom you sleep than the way you sleep with.

Sixty-eight add-ons, oh my!

**Comment by ArchangeGabriel** [comment]
JFYI, support for non-WE addons has been removed in current Nightly.

**Comment by Thorin-Oakenpants** [comment]
Bloody hell .. VM doesn't work if you block cookies

https://github.com/violentmonkey/violentmonkey/issues/169

It will be fixed though. Was about to migrate from GM (I know GM is spose to be ported, but I'm not waiting - no time like the present)

@earthlng - I guess this is just another example of the wrong Storage API being used, like eCleaner?

**Comment by Atavic** [comment]
Yes, that seem one of the changes.

**Comment by Atavic** [comment]
Yes, that seems one of the changes.

**Comment by Thorin-Oakenpants** [comment]
I waved goodbye to SSleuth ... :sadface:  .. although to be honest, I hardly ever looked at the info, just the icon (and effectively that is almost/kinda already covered by FF's own icons) .. so another legacy addon gone ... Stylus (for Stylish) & VM (for GM) up next

**Comment by Thorin-Oakenpants** [comment]
Found someone to rival @ghost (for those not paying attention this is/was zymase) - see [ghacks comments](https://www.ghacks.net/2017/08/17/all-in-one-sidebar-developer-announces-death-of-firefox-add-on/#comment-4221101) or just look at the [picture](https://i.imgur.com/1NgKbYg.png) - bit of a mess of an image with some bits shown twice, but I quickly counted around 110+ addons. French too .. maybe @ghost 's twin or long lost brother .. or maybe a potential date and some romance in the air :grin:

**Comment by crssi** [comment]
That FF must be opening for ages. But some are interesting, worth to check.
I am down to 15 now.

**Comment by Thorin-Oakenpants** [comment]
The most I ever had was maybe 55 - cool things like scrolling search engines in the search bar .. tons of little things - most don't impact performance at all. I am down to 19 loaded total (and 2 disabled Web Ext for testing). I have actually found that the less clutter and crap the better, and things I liked and thought I needed, I didn't really need (never used, not enough to justify them). Was stable at around 35-40 for the last year+). Even now, down to 20'ish I still do not miss what is gone.

Almost ready to ditch CTR (old search fix breaks next release anyway, and the only other reason is the back/forward/reload button BS'ery). CTR+FullThemes+UI+XUL is a real slowdown - when FT Deep Dark went is made a noticeable difference. Can't wait for 57 :jism:

**Comment by crssi** [comment]
I am missing one thingy from "FindBar Tweak"... that is markings on the scrollbar.
The was another "Scrollbar Search Highlighter" which is RIP now too.

**Comment by Thorin-Oakenpants** [comment]
^^ It was handy - I have simply trained myself to actually look at the number of matches shown on the find bar, and to just hit enter, enter, enter to jump to the next occurence - its actually quicker. With FBTweak I used to scroll

**Comment by crssi** [comment]
Integrated search is full of BUGs. They should polish those years ago. :(

**Comment by Thorin-Oakenpants** [comment]
Goodbye CTR .. was nice knowing you. The `Old search` feature of CTR will break with 56. THIS is the only reason I was hanging on to it -- well, that and BS'ry of urlbar movement due to appearing and disappearing forward/back buttons (note, the latest Photon newsletter says that the download button will only show when needed and cannot be moved - hmm, another decision that makes things move around). 

- Old Search behavior: select an engine and it did not auto load the url behind it. You could change engines _whenrever_ you wanted and the current tab was safe from exposure or losing your tab. The order of picking the engine did not matter. You couldn't accidentally send "moose porn" to google images by mistake when switching to the google images engine.
- New search behavior since whenever/ages: directly selecting an engine has consequences of when you do it: eg you need to replace the old search text first, you need to open a new tab depending on your settings if you do not wish to lose the current tab - basically change the engine last.

What I do now, is drop the engine list down, and right click the engine and select "set as default" - THIS will change the engine without causing the search page to load.
- sucks, extra, precise mouse movements etc, at least one extra click
- sucks, can't use up/down arrows
- sucks, search engine name and icon not displayed, so you need to check just in case

Here's hoping this shit has some upsides with the new photon, but I doubt it. I wonder if any tickets exists for 1) get the engine name back into the searchbar as placeholder text and 2) disable loading web pages on search engine selection?

It's not the end of the world, but I do see it as a privacy issue that could easily be fixed. That, and (don't ask), I do this "thing" once or twice a week where I do around 300-400 searches (using a dozen engines, any one at any given time) in about 3 hours, and loss of FBT and now this CTR old search severely cripples me

Oh well .. bye bye dinosaur .. next up T-Rex, same time, same channel, next week

**Comment by Thorin-Oakenpants** [comment]
PS: also removal of CTR (had to manually reset a bunch of left over extention.* prefs) means that resistFP gets the inner window size correct now. Current layout also shrank the padding between tabs+urlbar+toolbar - its so squashed up. I like a little padding :sadface:

**Comment by Thorin-Oakenpants** [comment]
Spooky... 

Comparison of file diffs (size change) minutes before and after removing CTR (newer on the right). Spooky because those safebrowsing files updated at that precise moment, probably a red herring. BUT whoa ... was CTR blocking some sort of internal FF mechanisms re the startupCache - 17MB's worth? Also, I removed an extension and the indexedDB for extensions exploded in size.

![ctr-removed](https://user-images.githubusercontent.com/16656956/29698053-e46d16e2-89a6-11e7-8688-fc2ce77db002.png)

**Comment by crssi** [comment]
What is CTR and which proggy^^ did you use for file comparison?
Thank you as always. :smiley:

**Comment by Thorin-Oakenpants** [comment]
- CTR = Classic Theme Restorer
- Proggy^^ is a portable version of Free File Sync (and not the latest because the author went retard) - https://www.portablefreeware.com/?id=1475 - I use it to sync me and my girlfriend's moosie porn media drives when she visits once a year, and also in Mirror mode to back my sh*t up

**Comment by Thorin-Oakenpants** [comment]
Getting used to the search engine is going to drive me nuts. If it has text in it already it auto drops down all the icons etc. Ugghhh

**Comment by Atavic** [comment]
What happened behind the scene? Were you online?

**Comment by Thorin-Oakenpants** [comment]
> What happened behind the scene? Were you online?

Huh? Who are you asking, .. and what the heck is it referring too? :)

**Comment by Atavic** [comment]
Pants, I'm asking how unistalling CTR modifies other files as startupCache.

**Comment by Thorin-Oakenpants** [comment]
^^ I have no idea. Online, but not loading any websites. Like I said, I backed up FF (while closed). Opened FF, removed CTR, restarted FF, removed left over prefs, restarted. Closed. Did a file diff out of interest. It's just an observation, and note that I have been on 55.00 (yet to go to 55.01, or .02 or .03) since around the 9th August. Why the startup Cache suddenly expanded is no doubt legit (think speed boost on startup, lazytabs etc, not that I have any of that) .. just makes me think CTR was causing an issue somewhere.

**Comment by Thorin-Oakenpants** [comment]
So I've come to grips with losing "old search" .. I didn't realize until I used it, but default search is not changed with using a secondary engine - they're distinct. This actual makes it easier, somewhat. And any text in the search bar slides the panel down and is quicker than the old method of clicking the drop down arrow. Still, I've inadvertently searched on the wrong engine a couple of times, just need to pay attention and train myself a bit better

Am still dealing with uBo => WebExt issues, but next week I should be good to migrate Stylish => Stylus. Stay tuned :)

**Comment by Thorin-Oakenpants** [comment]
OK .. so (currently) its 9:9 .. [All right; we'll call it a draw](http://www.sacred-texts.com/neu/mphg/mphg.htm#Scene 4)

No need to bore you all with any more of my migration stories

**Comment by Forsaked** [comment]
Now 10:9... ;-)

**Comment by Thorin-Oakenpants** [comment]
Now 11:9 .. oooh, this is exciting

**Comment by Gitoffthelawn** [comment]
We have progressed to 12:9... tension mounts....
