### ISSUE TITLE
What about some Linux prefs? huh! :)

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#14]
https://cat-in-136.github.io/
https://www.wilderssecurity.com/threads/firefox-lockdown.368003/page-10#post-2633173

@Roman-Nopantski: just check this, then you can remove this post.

**Comment by Roman-Nopantski** [comment]
We need to bulk up (from nothing) prefs for Linux. That's could be a bit of a starter of a list. I'll just change the topic and tag it as need help.

**Comment by earthlng** [comment]
I propose that we create a `preferences` folder and put a `linux.js` file in there for all the linux-specific prefs.

**Comment by Roman-Nopantski** [comment]
Just like Android specific prefs, as we come across Linux only ones, simply open a new issue, discuss it, and if we add it, denote it as such.

**Comment by Atavic** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/12#issuecomment-285674797
