### ISSUE TITLE
Why does user.js have Windows line endings?

### ISSUE THREAD

**Issue by carmenbianca** [ghacksuserjs/ghacks-user.js#145]
This is a bit inconvenient. When I modify the file locally on a Linux machine, I get mixed line endings (LF on the lines I modified, CRLF on the lines I did not modify). Or, when I configure my editor to input CRLF line endings, Git starts to throw a hissy fit when I want to commit my changes.

[This article](https://help.github.com/articles/dealing-with-line-endings/) is a good guideline on how to deal with line endings in Git (basically, LF line endings in the repo, native line endings in the working directory). But `user.js` is CRLF in the repo and CRLF in the working directory.

Can this be fixed? A single `dos2unix user.js` should do it, but that would (1) cause a massive commit that would break merges from/to previous revisions and (2) not solve the problem if the thing that _caused_ the file to have CRLF file endings is not resolved (probably a configuration error on the main contributor's machine?).

Thanks!

**Comment by Thorin-Oakenpants** [comment]
I'm not sure what to do here. Besides your links, I have read [this](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf) and [this](https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types) and [this](https://blog.codinghorror.com/the-great-newline-schism/) and I still do not know what to do.

I looked at PK's user.js - and it's using CRLF. Github seems to default to CRLF (I think I uploaded the user.js initially - I am on WIndows and user Notepad++). I may be wrong on these points.

>  When I modify the file locally on a Linux machine, I get mixed line endings

I see this as an end user issue - why don't you use an IDE that auto-detects and respects the convention? That's the gist of what I get from some of the links above, not bitchin' at you :), I've never even considered this, you see. Or are you using git? I'm a bit lost here.

What will happen to all the users on WIndows who use notepad, they'll be f**ked? What about Mac users? I still have no idea what to do here.

**Comment by pyllyukko** [comment]
> I looked at PK's user.js - and it's using CRLF.

No it's not.

**Comment by nodiscc** [comment]
If you download from raw.githubusercontent.com you will always get CRLF line endings. Learned this the hard way.

**Comment by Thorin-Oakenpants** [comment]
> > I looked at PK's user.js - and it's using CRLF.
> No it's not.

As I said, "I may be wrong on these points". What I did was copy/paste from the browser window and ended up with double lines spaces in both here and yours. Not very scientific I know :)

I'm still confused. Why should I change what github did by default? Can someone EIL5.

**Comment by carmenbianca** [comment]
> I see this as an end user issue - why don't you use an IDE that auto-detects and respects the convention? That's the gist of what I get from some of the links above, not bitchin' at you :), I've never even considered this, you see. Or are you using git? I'm a bit lost here.

Well I'm not going to use an IDE for editing simple files. But that issue is resolved by using a different editor/changing some settings, I will grant you that. The issue that remains, is git bitching:

```
carmen@carmen-laptop:~/Projects/ghacks-user.js$ git diff
diff --git a/user.js b/user.js
index 21fa11b..db66cce 100644
--- a/user.js
+++ b/user.js
@@ -35,7 +35,7 @@
  * Yes, this next pref setting is redundant, but we like it!
  * [1] https://en.wikipedia.org/wiki/Dead_parrot
  * [2] https://en.wikipedia.org/wiki/Warrant_canary ***/
-user_pref("ghacks_user.js.parrot", "Oh yes, the Norwegian Blue... what's wrong with it?");
+user_pref("ghacks_user.js.parrot", "Actually I want this to be something different");^M
 
 /* 0001: start Firefox in PB (Private Browsing) mode
  * [SETTING] Options>Privacy>History>Custom Settings>Always use private browsing mode
```

Notice the ^M. It's a "warning" that I'm staging with CRLF. It was rather disconcerting at first, because I'd never encountered it before.

> What will happen to all the users on WIndows who use notepad, they'll be f**ked?

They won't be, because Git converts the files to CRLF for them upon cloning (and apparently, as @nodiscc noted, you also get CRLF line endings from the web page). All the other files in this repository are already LF; it's just `user.js` that has CRLF.

> I'm still confused. Why should I change what github did by default? Can someone EIL5.

I have no idea why GitHub does it like that, I'm afraid. Generally the idea with line endings in Git is to let Git handle and convert it for the user. So all line endings are LF inside of the repository, and native (LF if Unix, CRLF if Windows) in your working directory. It converts back and forth when checking in/out, and this is generally seemless (the added .gitattributes makes this extra seemless for Windows contributors who haven't configured `core.autocrlf=true`).

Generally it's good etiquette to let people have their native line endings. And the way to do this in Git is to enforce LF line endings inside the repo. It's by no means mandatory, but very good etiquette. You'll find that all cross-platform projects do this. I did a `find . -not -type d -exec file "{}" ";" | grep CRLF` in the Django repo, and found just a single LICENSE.txt that had CRLF endings. Similarly, in the *massive* LibreOffice core repo, there were only a couple straggler files with CRLF line endings.

**Comment by Thorin-Oakenpants** [comment]
> because Git converts the files to CRLF for them upon cloning

Who said anything about cloning. Most users don't use git (I don't), let alone have an account here, and would simply download the zip file. I will assume the zip file will be whatever we set it (currently CRLF).

**Comment by Thorin-Oakenpants** [comment]
For anyone's info .. in Notepad++, for your existing user.js
- To convert:`Edit>EOL Conversion>Unix (LF)`
- To see them: `View>Show Symbol>Show End of Line` (toggle)

**Comment by Thorin-Oakenpants** [comment]
@earthlng Do we need to redo the alpha release before any more commits, so the next diff doesn't end up with every single line?

**Comment by earthlng** [comment]
> Do we need to redo the alpha release before any more commits, so the next diff doesn't end up with every single line?

No, my scripts don't care about line endings if that's what you mean. The compare link that's included in the changelog, at least the part for the files, will not be very useful next time but that's okay.

**Comment by Thorin-Oakenpants** [comment]
> The compare link that's included in the changelog, at least the part for the files, will not be very useful next time but that's okay.

I think we need a 54.01-alpha or a 54.0-alpha rev 1, otherwise github compares will suck, either 54->55 if we do nothing, or 53-54 if we replace the current one
