### ISSUE TITLE
incontent drag-n-drop side-effect

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#147]
Is there a pref that has the side-effect of selecting everything below the cursor during drag and drop?

For example, in any webmail app, when I drag-and-drop an email into a folder, all the text below the cursor gets selected.

I've performed normal testing procedures, and have yet to come up with culprit.  Before I continue along that long process, I thought I would ask you nice people. :)

**Comment by Thorin-Oakenpants** [comment]
> I've performed normal testing procedures

So you mean it doesn't happen in a nilla FF, or a nilla FF with default user.js? Can you give a step by step (and/or screenshot)? Is this on gmail? I'm also confused - draging what from where to where? dragging within a webpage - like dragging an email from your "inbox" to a "custom" folder? Soz, but I do not use any web based mail sites, so might be hard for me to troubleshoot. Can't say I've ever seen the behavior you describe.

**Comment by Thorin-Oakenpants** [comment]
Is it similar to this: https://bugzilla.mozilla.org/show_bug.cgi?id=881989

**Comment by Thorin-Oakenpants** [comment]
Also this: https://productforums.google.com/forum/#!msg/gmail/_-BCYja4_ms/1CA4LHLrHAAJ

**Comment by Thorin-Oakenpants** [comment]
If it's gmail .. select between the star and the checkbox .. you have 1.5mm .. so no drinking beforehand

**Comment by Gitoffthelawn** [comment]
Wow! You are impressive with finding search results!

That bug is 4 years old, and it is still unassigned.  I never understand how Mozilla can just ignore bugs for that long.  I now probably only report 25% of the bugs I find because I know they might get ignored indefinitely, and I don't want to waste my time.

**Comment by Thorin-Oakenpants** [comment]
Well, I hardly blame FF for it. It's the website IMO. Just click between the star and checkbox. You never answered if it was gmail, btw.

**Comment by Gitoffthelawn** [comment]
I just signed up for test accts on Gmail, Yahoo, and Microsoft.  Firefox does it on all 3 sites. :(

I tried it on a fresh profile, with only uBo (with default lists) installed.

**Comment by fmarier** [comment]
> That bug is 4 years old, and it is still unassigned. I never understand how Mozilla can just ignore bugs for that long. I now probably only report 25% of the bugs I find because I know they might get ignored indefinitely, and I don't want to waste my time.

In general, Firefox is such a large (and still growing) project that it will never get its bug level down to 0. It's a matter of continuously prioritizing the most important bugs, which is of course an error-prone process.

In this particular case, however, bug 881989 was filed against Firefox Metro, a project which was abandoned a number of years ago. That greatly reduces the likelihood that anybody will look at it. I've asked the bug reporter to check if he can reproduce it on regular Firefox.

**Comment by crssi** [comment]
@fmarier 
Please, don't take my comment personally, since its not meant to be so.

But some old bugs and some new functionality breakage bugs not being resolved fast is just **lame as hell.**

Two are crossing my mind:
1. (old) URI resource leakage, see [https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/)
2. (new) WE still doesn't support cleaning local storage for extensions like [https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)

If you ask me, both should be implemented in Firefox as high priority years ago without needing extensions for resolution.

cheers

**Comment by fmarier** [comment]
> (old) URI resource leakage, see https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/, see https://bugzilla.mozilla.org/show_bug.cgi?id=863246

That one is actively being worked on as part of the Tor uplift project. It's tricky to get right because IIRC many of our regression tests rely on that old behavior.

I'm pushing for it to get fixed in Firefox directly, not just in Tor. That would make the extension unnecessary.

**Comment by Gitoffthelawn** [comment]
@fmarier It's frustrating to see questionable stuff being tweaked, added, or removed, without basic usability issues being fixed.

For example, let's say the user searches for a bookmark and then needs to know in which folder the bookmark is located.  How does the user do this?

**Comment by crssi** [comment]
@fmarier I am sure you will make the day for all of us. :)

Thank you a lot

@Gitoffthelawn maybe you don't know, but @fmarier is security guy, not bookmark. :)

**Comment by Gitoffthelawn** [comment]
@crssi Thanks.  I did not know. :)
