### ISSUE TITLE
dom.workers.enabled functionality breakage

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#148]
Preference `dom.workers.enabled = true` breaks some pages, which is already known, but hereis a new sample.
Try this one as a sample: [https://docs.microsoft.com/en-us/advanced-threat-analytics/modifying-ata-config-centercert](https://docs.microsoft.com/en-us/advanced-threat-analytics/modifying-ata-config-centercert)

On this sample all menu around article dissapears when false.

As always, this is not a request for a change, but just to let you know together with a sample page.

In addition the preference `dom.workers.maxPerDomain` puzzles me.
When I set `dom.workers.enabled = true` and `dom.workers.maxPerDomain = 0` (zero from 512 as default) the sites which I stumbled on that are using workers, still work.

@Thorin-Oakenpants: after ACK you can easily close this issue. ;)

**Comment by Thorin-Oakenpants** [comment]
FYI: https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js#154
```js
// The number of workers per domain allowed to run concurrently.
// We're going for effectively infinite, while preventing abuse.
pref("dom.workers.maxPerDomain", 512);
```

Other than that (all.js and greprefs.js), I cannot find any reference to it in DXR.

And yes, more and more sites are going to use web workers, because 1. it's slightly more powerful AFAIK 2. it means the web page is lighter/more responsive because 3. the heavy lifting can be done elsewhere (it's probably more efficient too). I'm not sure when they first came about ( https://en.wikipedia.org/wiki/Web_Workers ), but its been years. I'm hoping FPI, in the future, allows us to maybe turn workers on (not service workers - eg like PB mode doesn't allow service workers), because I can see the day when just too many sites break.

**Comment by RoxKilly** [comment]
This is for quick reference on Web Worker

Most sites run on a single thread; the computation the site performs competes with the UI. As a results sites that involve heavy computation will cause laggy UI. Web Workers are one tool to fix this: they put the computation on a second thread, so the UI is not laggy. IMO, the only reason they're not much more popular is that coding multi-threading apps is a complete change in paradigm, and most devs are paid to just make things work as quickly as they can.  As websites do increasingly more complex work, and as the trend towards single-page web apps continues, web workers are bound to increase in popularity especially among big sites with good devs. 

I have Web Workers enabled, Service Workers disabled.

**Comment by earthlng** [comment]
> When I set `dom.workers.enabled = true` and `dom.workers.maxPerDomain = 0` (zero from 512 as default) the sites which I stumbled on that are using workers, still work.

https://dxr.mozilla.org/mozilla-central/source/dom/workers/RuntimeService.cpp#103

> static_assert(MAX_WORKERS_PER_DOMAIN >= 1,
>              "We should allow at least one worker per domain.");

**Comment by earthlng** [comment]
> When I set `dom.workers.enabled = true` and `dom.workers.maxPerDomain = 0` (zero from 512 as default) the sites which I stumbled on that are using workers, still work.

from that site's global.min.js
```js
var workerUrl = relativeToGlobal('js/worker.js', true);
var worker = new Worker(workerUrl);
```
with maxPerDomain=0 it still loads the worker.js - check the Network Monitor - I guess 0 is not allowed and results in 1 maybe, idk

**Comment by Atavic** [comment]
When the MaxWorkersPerDomain is reached, the next ones are queued and a warning is logged. `pref("dom.workers.maxPerDomain", 512);` is a treshold.

**Comment by earthlng** [comment]
> is a threshold value >= 1

yeah but at that point MAX_WORKERS_PER_DOMAIN is still and always 512, isn't it?
Actually MAX_WORKERS_PER_DOMAIN is never changed and gMaxWorkersPerDomain is what's used to store and access the value.

**Comment by Atavic** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/70
