### ISSUE TITLE
meta: tor uplift: the rest

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#15]
Locked sticky issue for tracking other Tor Uplift items of interest (after RFP #7 and FPI #8 )
 - [Tor Uplift](https://wiki.mozilla.org/Security/Tor_Uplift/Tracking)
 - [MVP Tracking](https://wiki.mozilla.org/Security/Fingerprinting)
- [Bugzilla META Tor Uplift ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1260929)
 - [Tor Uplift Dependency Tree](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1260929&hide_resolved=0)

Last updated: see changelog at foot

### RESOLVED & ADDED TO USER.JS <sup>if applicable</sup>

:small_red_triangle_down: FF52
 * [1121643](https://bugzilla.mozilla.org/show_bug.cgi?id=1121643) only expose whitelisted system fonts (FF52+)
   // user_pref("font.system.whitelist", ""); // (hidden pref)

:small_red_triangle_down: FF56
 * [1266495](https://bugzilla.mozilla.org/show_bug.cgi?id=1266495) remove `<isindex>`

:small_red_triangle_down: FF57
 * [1388881](https://bugzilla.mozilla.org/show_bug.cgi?id=1388881) Stylo respects mathml.disabled
 * [863246](https://bugzilla.mozilla.org/show_bug.cgi?id=863246) disable/limit resource://, chrome:// and about:// URI leaks
   :exclamation: `security.all_resource_uri_content_accessible` - may add this to user.js [reminder]
   [TEST] https://www.browserleaks.com/firefox
   [1] https://trac.torproject.org/projects/tor/ticket/8725

:small_red_triangle_down: FF59
* [1222924](https://bugzilla.mozilla.org/show_bug.cgi?id=1222924) stop exposing moz-icon URL scheme

:small_red_triangle_down: FF60
* [1359076](https://bugzilla.mozilla.org/show_bug.cgi?id=1359076) disable all Device Sensor APIs except orientation
   * here's an [article](https://blog.lukaszolejnik.com/stealing-sensitive-browser-data-with-the-w3c-ambient-light-sensor-api/)
* [1382359](https://bugzilla.mozilla.org/show_bug.cgi?id=1382359) treat .onion as a secure context

:small_red_triangle_down: FF64
* [680300](https://bugzilla.mozilla.org/show_bug.cgi?id=680300) restrict discoverability of protocol handlers
* [583181](https://bugzilla.mozilla.org/show_bug.cgi?id=583181) don't expose navigator.buildID to web content - [compat info](https://www.fxsitecompat.com/en-CA/docs/2018/navigator-buildid-has-been-removed/)

:small_red_triangle_down: FF68
* [1541958](https://bugzilla.mozilla.org/show_bug.cgi?id=1541958) nsUserInfo removed
   * original ticket: [1433350](https://bugzilla.mozilla.org/show_bug.cgi?id=1433350) remnant code, windows user name/accounts etc loaded into memory, was available to extensions, blah blah, read the ticket

:small_red_triangle_down: FF70
* [467035](https://bugzilla.mozilla.org/show_bug.cgi?id=467035) dtd locale leaks

### PENDING

 * [1314443](https://bugzilla.mozilla.org/show_bug.cgi?id=1314443) preference to fully disable WebRTC JS API
 * [967979](https://bugzilla.mozilla.org/show_bug.cgi?id=967979) disable "This Plugin is Disabled" overlay
   `? user_pref("privacy.plugin_disabled_barrier.enabled`
 * [1041818](https://bugzilla.mozilla.org/show_bug.cgi?id=1041818) disable/mitigate canvas fingerprinting
 * [1330675](https://bugzilla.mozilla.org/show_bug.cgi?id=1330675) add support for style API for disabled SVG nodes
* [1314778](https://bugzilla.mozilla.org/show_bug.cgi?id=1314778) disable Account Manager

### INVALID / WONTFIX / DUPLICATE
 * ~~[732096](https://bugzilla.mozilla.org/show_bug.cgi?id=732096) prevent local font enumeration~~
   * ^^ duplicate of [1121643](https://bugzilla.mozilla.org/show_bug.cgi?id=1121643) = FF52+ `1409` font whitelist

### CHANGELOG
* Apr 05: 1541958 & 1433350 (remove nsUserInfo) → FF68+
* Jul 11: 467035 (dtd locale leaks) → FF70+

...

**Comment by Atavic** [comment]
- 1400 gives away system OS easily and gives uniqueness issues with non-standard installed fonts.

**Comment by Roman-Nopantski** [comment]
Stay on topic please. Well of course, that's why the section exists - to limit the font fingerprint attack surface

**Comment by Roman-Nopantski** [comment]
@Atavic The Tor Uplift is in a constant state of change. A lot of tickets don't even involve preferences, and lot are "individual" fixes. But two major items/preferences exist (`privacy.resistFingerprinting` and `privacy.firstparty.isolate`) where multiple tickets and solutions for multiple issues will be addressed and assigned to that one preference. Basically a META ticket is a ticket that groups lots of other tickets together.

In order for us here to more easily follow up on (and not forget) to include this information in the user.js when they become applicable, I have  created these three `meta: tor uplift` sticky topics (one each for those two prefs and a third for all the rest we're interested in - eg they have a preference)

For example: if you look at section 2699 there are currently three items but one preference. As relevant tickets get closed, we can add the information to that section, so end users are aware of all the consequences.

**Comment by Roman-Nopantski** [comment]
@earthlng `1200's: Isolate the HSTS and HPKP cache by first party domain` is now resolved. I can't see any preference (I don't expect one, but haven't looked), but should this be under #8 meta: FPI - and eventually added to `2698: FIRST PARTY ISOLATION (FPI)` ?

**Comment by crssi** [comment]
Observation report:
- **`privacy.resistFingerprinting`**
Overall havent found any serious problems yet, but there is an "inconvenience".
I guess this "login.aliexpress.com" is a perfect site for testing... lol
When `privacy.resistFingerprinting = true` and together with NoScript, it raises ClearClick event in NoScript.
Funny, when `privacy.resistFingerprinting = false`, there are no "ClearClick" events in NoScript extension.

- **`privacy.firstparty.isolate`**
Oh man, this one is a problem maker. I know, its still in development, but just FYI.
It was somehow expected where I can find a problem.
`privacy.firstparty.isolate = true` isolates session in a way that even some FF extensions stops working.
For example "Self-Destructing Cookies" (SDC) does not destruct cookies after session, obviously SDC cannot access the session namespace.
Haven't tested uBlocker, uMatrix, NoScript... etc.

**Comment by Atavic** [comment]
@crssi Regarding your first observation, you can use ublock for that: https://github.com/ghacksuserjs/ghacks-user.js/issues/7#issuecomment-281363027

**Comment by crssi** [comment]
@Atavic Thank you, but here we have two different approaches with two different results (uBlock vs NoScript).
uBlock blocks frames which is undesired action in this case.
I would guess that this is a feature/bug in NoScript. Will investigate further.

**Comment by Thorin-Oakenpants** [comment]
Should we include this? I didn't think FF could actually visit onion sites
`network.http.referer.hideOnionSource`
https://bugzilla.mozilla.org/show_bug.cgi?id=1305144 (FF54+)

**Comment by gr8gnd4r** [comment]
FF can be configured to use TOR (not the same as TBB), as can other
apps. For example, download and install tor-win32-0.2.9.10 (or whatever
the latest is), and set proxy to SOCKS localhost port 9050 or 9150
(depending on how TOR is configured).

**Comment by Thorin-Oakenpants** [comment]
Oh boy .. so much time spend changing bugzilla ticket priorities and flags/details such as `[tor][fingerprinting][fp:m1]` ). Sometimes I wish they would just get on and do it. Look at [1222285](https://bugzilla.mozilla.org/show_bug.cgi?id=1222285), 10 months and all we have to show is 11 changes to status/flags/priority/whiteboard and 2 links to meta - ZERO actual work. Dozens of these tickets are like this. It's coming up on a year since anything was added to resistFingerprinting (but two have now been resolved for 55, which is still 10 weeks away) JUST. GET. ON. WITH. IT. 

Anyway, this is interesting: they started using `[fp:m1]`, `[fp:m2], and `[fp:m3]` in the whiteboard section, so I guess this is some sort of priority for these (mark 1, mark 2, mark 3 etc). Just use these links

note the fp%3Am1 part which is the search string.
```js
https://bugzilla.mozilla.org/buglist.cgi?list_id=13572960&status_whiteboard_type=anywordssubstr&status_whiteboard=fp%3Am1&resolution=---&query_format=advanced
```
* [fp:m1](https://bugzilla.mozilla.org/buglist.cgi?list_id=13572960&status_whiteboard_type=anywordssubstr&status_whiteboard=fp%3Am1&resolution=---&query_format=advanced)
* [fp:m2](https://bugzilla.mozilla.org/buglist.cgi?list_id=13572960&status_whiteboard_type=anywordssubstr&status_whiteboard=fp%3Am2&resolution=---&query_format=advanced)
* [fp:m3](https://bugzilla.mozilla.org/buglist.cgi?list_id=13572960&status_whiteboard_type=anywordssubstr&status_whiteboard=fp%3Am3&resolution=---&query_format=advanced)

Looking at fp:m1, (we already have rounded to hundreds inner windows and UA time zone 0 spoofing both resolved), looks like spoof navigator objects is coming soon. In other words, the items from Panopticlick v1 from 4? 5? years ago. Hope they patch those navigator holes properly, including iframes and all JS methods to get that data (hint: it's not just navigator.*).

**Comment by earthlng** [comment]
@Thorin-Oakenpants 
I often see these stickies getting updated but it's always hard to spot what you changed.
IMO it would be very helpful and great if you could (a) add a date to changes (b) keep a (short) changelog at the bottom of the first comment (or in a 2nd comment) with the latest changes or (c) post a new comment with the changes you made. For (c) you could delete the comments again after 1 or 2 weeks or so.
It would not only be very helpful but would also show how much work you put into these stickies.
Thanks

**Comment by Thorin-Oakenpants** [comment]
last change was the removal of isindex from forms etc - there is still another isindex ticket - not much has happened in here - usually any change is the last item in the Resolved section - same in the privacy.FP - last added items in the resolved section, plus their is a corresponding commit. isolate is almost done, there are some more issues such as favicons not isolated in history dropdowns, but its pretty much done.

history of changes .. aww man .. more work .. ok

**Comment by publicarray** [comment]
@earthlng FYI Github shows you a little popup of the last edit date when you hover over the `edited` text, right after `Thorin-Oakenpants commented on Feb 19 • `

**Comment by Thorin-Oakenpants** [comment]
^^ Never noticed that. Meanwhile... in the three Tor Uplift stickies where I only really edit the first post, you can just look at the changelog at the end which I have now been doing for the last 4 weeks :)

**Comment by Thorin-Oakenpants** [comment]
[863246](https://bugzilla.mozilla.org/show_bug.cgi?id=863246): resource:// URIs leak information has landed

> Status: ASSIGNED → RESOLVED
Last Resolved: 35 minutes ago
status-firefox57: --- → fixed

**Comment by Thorin-Oakenpants** [comment]
@earthlng : there is a `security.all_resource_uri_content_accessible` with the resource URI ticket pref. Should we just ignore this until 57 lands and pick up on diffs?

**Comment by earthlng** [comment]
I think it's a hidden pref and used only for some of their test files. We will probably not see it in the diffs.
It's possible/likely that they'll get rid of it again once they've adjusted all their test files. But we can add it and enforce it to false, just in case.

**Comment by Thorin-Oakenpants** [comment]
Its added to sticky items to follow up items. Lets wait til closer to 57

**Comment by Thorin-Oakenpants** [comment]
Yay .. [680300](https://bugzilla.mozilla.org/show_bug.cgi?id=680300) is getting some attention

**Comment by Thorin-Oakenpants** [comment]
Closing this as it's not really maintained: for these sorts of bugs (and there are many more) that provide fixes for all users, i.e not directly tied to RFP or FPI, it doesn't matter if it originates from Tor Project or Firefox or is listed as part of the Tor Uplift or not - it's just a general bug / enhancement: and there are loads of them: e.g

- [231852](https://bugzilla.mozilla.org/show_bug.cgi?id=231852) ETags
- [1534581](https://bugzilla.mozilla.org/show_bug.cgi?id=1534581) `chrome://` + `resource//`
- [1562290](https://bugzilla.mozilla.org/show_bug.cgi?id=1562290) gyroscope

I'll stop there. If something is tied to RFP or FPI then I'll track it in the other two stickies: otherwise it's just a general bug and I'm not interested in providing an incomplete and unmaintained list (it's not possible)
