### ISSUE TITLE
FF just hardening 

### ISSUE THREAD

**Issue by bonbonboi** [ghacksuserjs/ghacks-user.js#151]
Could you add another user.js that just hardening  FF e.g. cipher suites, etc without any cleaning-up .e.g. history, site preferences, dom stuff...

That's because I use a personal FF on an encrypted partition, so cleaning up FF is not my primary concern for now, plus I have changed a lot of stuff  in your user.js to let some functions to work. e.g. FF sync, LastPass add-ons to remember email/password.

Thanks you

**Comment by Forsaked** [comment]
You can always comment out part `2700: COOKIES & DOM STORAGE` in the user.js.

**Comment by Thorin-Oakenpants** [comment]
These are not cleared by the default user.js, only histories. Also dom storage (2705) is not blocked
>  site preferences, dom stuff

If you're not worried about persistent data on disk (as opposed to persistent data being re-read by sites = website tracking vs forensics), just comment them out. They're all labelled.

I plan on putting out a more relaxed version at some stage, but to be honest, it's like only 20 changes. I think it might be easier to just list them in a sticky topic.

Off the top of my head: location bar/search usage (section 0800, read the section header),  session restore/disk cache stuff (section 1000), section 2800 (clearing stuff on close - just disable them all and change your settings in the preferences UI, see 2803+2804 for where to find the settings). Also allowing cookies by default seems to trip people up (2701 - as Forsaked has already pointed out)

Other items for less breakage or consideration (still off the top of my head) .. workers (section 2300), indexeddb (2404), cut/copy/paste (2402), fonts (1401, some people want fonts!), GMP (eg drm/eme/widevine etc for video - see 1820, 1825, 1830), site zoom (2515)

Maybe WebRTC, WebGL ..  about 10-20 numbered items at a rough estimate. All of these are tagged with [SETUP] or [WARNING]

**Comment by Thorin-Oakenpants** [comment]
BTW, if you've already tweaked your user.js to fit your needs, then there's no need for me to do it for you. Everyone will want something different.

https://github.com/ghacksuserjs/ghacks-user.js/issues/124 - there's a good example here of how to use the ghacks user.js in its default, and put your changes to override them in a separate file.

Or you can do what atomGit from 12bytes does, append the override prefs at the end of the user.js - see his [article](http://12bytes.org/articles/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs) and his [repo](https://github.com/atomGit/Firefox-user.js)

**Comment by bonbonboi** [comment]
I see, thanks for telling me about the override thing, I'm gonna read it over .. by the way user_pref("dom.indexedDB.enabled", false); it breaks Twitter, but not the whole thing, just if you wanted to follow/unfollow someone you couldn't unless you turn that to true. Also it could breaks some other web sites , right now I could remember Telegram Web.. Also FF is weak some how in Video/Audio connections compared to e.g. chrome, I do not know if recent FF got better than before in that area, in the past e.g Facebook video calling couldn't established that easy, I go to chrome to make a call, do you think disabling WebRTC would break Facebook video calling or any voice calls e.g. Web skype, Web Telegram, Web whatever..

**Comment by Thorin-Oakenpants** [comment]
Not into FB at all, and I've never used WebRTC, so I don't really have any experience with it. But seeing as it's used for exactly those things you describe, then probably.

And yes, if a pref is listed twice, the second instance will be the one that "sticks" - eg line 1058
```js
user_pref("dom.indexedDB.enabled", false);
```

and way down the bottom in you own section .. lines 1900+
```js
// bonbonboi overrides
user_pref("dom.indexedDB.enabled", true);
```

Then this means that indexeddb will enabled on every startup. This will make it easier to just replace/update the whole ghacks js part, and keep your overrides.

**Comment by Thorin-Oakenpants** [comment]
That said, I do plan on releasing a relaxed version - would be interested for you to post us your changes :)

**Comment by bonbonboi** [comment]
As I understood why someone wants to block/disable WebRTC, it's about when using a vpn/proxy or whatever thing, that WebRTC may leaks the real IP, thus that is the main reason behind the WebRTC buzz, otherwise it's a modern feature to support the A/V communications between clients. 
[A Study of WebRTC Security](http://webrtc-security.github.io)

**Comment by bonbonboi** [comment]
Speaking of indexedDB, I was using this add-on before even I knew this project. it enables/disables indexedDB on the fly.. I was using it mainly to follow/unfollow on Twitter. ;) 
[Disable IndexedDB, for Firefox](https://github.com/ChrisAntaki/disable-indexeddb)

**Comment by crssi** [comment]
^^ SDC is dealing very good in those cases sparing you with manual cleaning work.

**Comment by bonbonboi** [comment]
> ^^ SDC is dealing very good in those cases sparing you with manual cleaning work.
- What SDC?

**Comment by RoxKilly** [comment]
@bonbonboi wrote:
> block/disable WebRTC, it's about when using a vpn/proxy or whatever thing, that WebRTC may leaks the real IP

This weakness of WebRTC can be fixed in Firefox with the following setting:
```
user_pref("media.peerconnection.ice.default_address_only", true);
```

Once you've done this, your real IP will no longer leak over WebRTC when you're properly using a VPN. A few sites will allow you to [test for IP leak](https://browserleaks.com/webrtc).

**Comment by bonbonboi** [comment]
> user_pref("media.peerconnection.ice.default_address_only", true);
-Thanks for your input.

**Comment by bonbonboi** [comment]
I have no clue why this add-on complaining a lot about those insecure mixed contents even I blocked dealing with those stuff.. 
here it's link:

[HTTPSpatrol](https://addons.mozilla.org/en-us/firefox/addon/httpspatrol/)

**Comment by Atavic** [comment]
@bonbonboi [SDC](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/)

**Comment by bonbonboi** [comment]
> @bonbonboi SDC

- ah I see ;)
