### ISSUE TITLE
A GUI Config Tool

### ISSUE THREAD

**Issue by bonbonboi** [ghacksuserjs/ghacks-user.js#153]
Before I knew this git, I was using something called "ConfigFox" works on Windows..
Here at [ConfigFox](http://configfox.sourceforge.net)
- Let me know if that still valid or outdated or better to stick with ghacks-user-js solely.. 
- What do you think about a GUI tool to work with ghacks-user.js settings. ;)

**Comment by Thorin-Oakenpants** [comment]
ConfigFox has bugs, hasn't been updated for over 18 months, is procedurally flawed and not properly explained. The developer has abandoned it AFAIK.

I already have a GUI tool - it's called an IDE

**Comment by bonbonboi** [comment]
I see, thanks for the info..

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants What IDE are you using to manage FF prefs?

**Comment by Thorin-Oakenpants** [comment]
I just use Notepad++, but i have a few others - all portable/windows

**Comment by bonbonboi** [comment]
> I just use Notepad++, but i have a few others - all portable/windows

So am I , notepad++ is my old friend, I like the lite version of it, more than enough for simple tasks ;)

**Comment by bonbonboi** [comment]
In past, I emailed the dev of ConfigFox, he told me that tools also modifies prefs.js in order to complete the process of the user.js , that time when I asked him if you could just copy user.js to Linux, he mentioned that wouldn't be just enough since ConfigFox also change some settings in prefs.js

**Comment by Forsaked** [comment]
I also use [Notepad++](https://notepad-plus-plus.org/) with the Compare plug-in or sometimes i use [DiffChecker](https://www.diffchecker.com/) when i am at work, since i can't install plug-ins there.

**Comment by bonbonboi** [comment]
> Notepad++ with the Compare plug-in 

ah good to mention that plug-in, I'm going to check out since I use the minimal version..
