### ISSUE TITLE
Purpose of kinto.sqlite

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#164]
Does anyone know the purpose of `kinto.sqlite`?

It is present in profile folders, including new ones.

Searching DXR comes up *nil*... why is that?

**Comment by earthlng** [comment]
It stores the individual kinto blocklists all in one file (from addons, gfx, plugins).
Why does it need addons.sqlite, etc AND kinto.sqlite? IDK!

**Comment by Gitoffthelawn** [comment]
@earthlng Thanks.  So we can all delete the separate gfx and plugins blocklists in the profiles?

What does *kinto* mean in "kinto blocklists"?

BTW, I no longer see `addons.sqlite`, but I do see `blocklist.xml`.

Still curious why the string "kinto" is not showing up in a DXR search.

**Comment by Thorin-Oakenpants** [comment]
My kinto.sql was last updated 12-April-2017 and I have kinto enabled. Surely in all the time since then, I would have expected at least some revoked certs.

**Comment by earthlng** [comment]
> So we can all delete the separate blocklist-addons,json, blocklist-gfx.json and blocklist-plugins.json blocklists in the profiles?

Um, I have never seen any of those in my profile. But I'm now using ESR so that doesn't mean much.

> What does kinto mean in "kinto blocklists"?

https://wiki.mozilla.org/Firefox/Kinto
> Kinto is a simple JSON storage service that is used in Firefox for remote settings and the storage.sync API. 

> Still curious why the string "kinto" is not showing up in a DXR search.

Um, https://dxr.mozilla.org/mozilla-central/search?q=kinto&redirect=false
> 407 results from the mozilla-central tree

??

> Surely in all the time since then, I would have expected at least some revoked certs.

Um ...

> (from addons, gfx, plugins)

revoked certs are handled differently

**Comment by Thorin-Oakenpants** [comment]
> revoked certs are handled differently

Ahh that's right. Still, it's disconcerting to see that date last modified (is it working as advertised?) .. or it could be taken as a sign that the vetting process at AMO is robust (plugins is basically obsolete? and gfx would be few and far between?).

**Comment by Thorin-Oakenpants** [comment]
![blocklist](https://user-images.githubusercontent.com/16656956/27969613-a17084be-639f-11e7-8393-9173f5e52434.png)

FWIW, the *-addons, *-gfx and *-plugins do not exist in a nilla 54 profile (but the profile has never been up and running for more than 2 or 3 minutes for testing a few things).

**Comment by Thorin-Oakenpants** [comment]
> Why does it need addons.sqlite

Like Gitoffthelawn, I don't have this file either

**Comment by Atavic** [comment]
A JSON document store with sharing and synchronisation capabilities, which can block
- addons
- plugins
- gfx
- certificates

I added mozilla.com to the partial URLs on bottom page [here](https://github.com/mozilla-services/kinto-amo) and got rediretced to:
https://blocked.cdn.mozilla.net/

**Comment by Gitoffthelawn** [comment]
@earthlng Thanks.  BTW, DXR search must have been broken when I tried, because the same search performed now returns results.  Thanks again.

**Comment by Thorin-Oakenpants** [comment]
bump* ... so are these three blocklist.* json files still used, or redundant due to the kinto sqlite?

**Comment by Atavic** [comment]
Aren't the addons labeled as Legacy with this method?

**Comment by Thorin-Oakenpants** [comment]
No sure what you mean by that Atavic. Legacy addons will still be supported in ESR and I think developer. And the addon blocklist still needs to be supported even for web extensions.

Or do you mean that this is used to add the "legacy" badge in about:addons>Extensions? My answer would be I doubt it - its not getting updated and comes nowhere near big enough to hold all the legacy addons (around 16K?, plus 3K+ blacklisted). I would have thought that FF can determine WE from legacy purely from code.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1257565

Well I already can see that blocklist.xml is updated every day (watch that ticket above). The addons json and the kinto.sqlite haven't changed for 3 months, and the gfx and plugins haven't changed for 8 months.

**Comment by Atavic** [comment]
The bagde is what I meant.

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants wrote
> so are these three blocklist.* json files still used, or redundant due to the kinto sqlite?

Redundant.  Delete 'em.

@Thorin-Oakenpants  wrote:
> the kinto.sqlite in a brand new portable 54 is a different size (slightly smaller)

I noticed this too.  Weird.  Not sure if best to delete it and let Firefox recreate it, or just leave it as is.

**Comment by earthlng** [comment]
Starting with FF54 the 4 json files are included in omni.ja. It will now only create/update copies in the profile folder if there's an update on the remote server. That could explain the older last modified dates.

**Comment by Thorin-Oakenpants** [comment]
FYI: There's talk of using kinto to provide bundled fonts for FPing

**Comment by Gitoffthelawn** [comment]
@earthlng Hmmm... isn't the point of kinto to (largely) store those json files within the kinto sqlite database?

@Thorin-Oakenpants That's exciting news... hopefully they can do it.

**Comment by earthlng** [comment]
> Hmmm... isn't the point of kinto to (largely) store those json files within the kinto sqlite database?

Yes, afaik. Why, what's your point? You guys were wondering if the json files are obsolete. They are definitely not because copies of them are now shipped with FF.

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1336208#c6

OT: what a [shitstorm](https://www.reddit.com/r/firefox/comments/6mt8i4/security_fuckup_aboutaddons_uses_google_analytics/) .. read https://github.com/mozilla/addons-frontend/issues/2785 .. as gorhill says, I already have removed `about-scheme` from the default whitelist, not to mention in the case of the get addons tab discovery is nixed by pref 0320 `"extensions.webservice.discoverURL`. GA is auto blocked in uBo anyway from lists (I do not block it app wide since I need to allow it for a couple of sites).

I hope they do not, as has been mooted, tie this to DNT @fmarier . Opting-in to DNT is the same as opting out of GA - not privacy friendly

**Comment by Thorin-Oakenpants** [comment]
I went to post a question asking why onboarding had GA and 20 seconds before I posted, the topic was locked - bastards! :)

**Comment by Thorin-Oakenpants** [comment]
@earthlng - in a brand new FF portable, there are no such json files. I left a nilla FF running for around 12 hrs and they did not manifest. This is 54. ESR may be different - I haven't had time to check. I haven't deleted mine, because of your earlier comment. Blockist updates every day, the three json files I would expect to have very little activity (as I said).

**Comment by earthlng** [comment]
> I already have removed `about-scheme` from the default whitelist

lol, I noticed and mentioned GA on the addons page ages ago. What took you so long? xD

**Comment by Thorin-Oakenpants** [comment]
It didn't take me long at all. When we set up the wiki scripts, that when I cleaned out the default whitelist - months ago.

**Comment by earthlng** [comment]
> in a brand new FF portable, there are no such json files. I left a nilla FF running for around 12 hrs and they did not manifest. This is 54

yes, that's because they are now shipped with FF. Unless they change after the release you won't see them anymore in the profile folder.

>  I haven't deleted mine

you can delete them, np. Any action based on those blocklists would have long been done already by now.

**Comment by earthlng** [comment]
> but come WebExtension it says its blocked but it isn;t (on about pages)

still looking forward to FF57 ?? ;)

**Comment by Gitoffthelawn** [comment]
Blocking GA via `hosts` should always work.

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants For 0320, in the comments, add something regarding GA.

**Comment by fmarier** [comment]
> OT: what a shitstorm .. read mozilla/addons-frontend#2785

The tracking protection regression is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1380409.

**Comment by Thorin-Oakenpants** [comment]
While I appreciate the above ticket (web content in about pages should be treated like all other web pages - it should abide by DNT, it should abide your cookies prefs, it SHOULD allow access to WebExtension control FFS), there is a higher expectation on about pages that they are internal.

The master switch for telemetry (lets face it, its not really a master switch) should control *ALL* telemetry, including about pages.

I'm quite keen now to set up a nilla 56 and wireshark that mother as I load every. single. about and UI page known to man - because I can bet you top dollar that this is not the only instance - go ask Kev Needham.

**Comment by Thorin-Oakenpants** [comment]
What a cop-out - https://github.com/mozilla/addons-frontend/issues/2785#issuecomment-315212909

This does nothing to fix the underlying overall issue

**Comment by Thorin-Oakenpants** [comment]
We block the addons discovery page anyway, we are going to block onboarding, and this is all OT from the kinto discussion - sorry for derailing the thread.

@Gitoffthelawn `kinto`.sqlite is used by `kinto` - that's the answer. Well done :)
