### ISSUE TITLE
How does network.stricttransportsecurity.preloadlist update and deploy?

### ISSUE THREAD

**Issue by zymase** [ghacksuserjs/ghacks-user.js#165]
This is just for information, sorry opening an issue when it is not, but I've spent hours searching for an answer on the Web, unsuccessfully.

Concerns:
`user_pref("network.stricttransportsecurity.preloadlist", true);  // Default=true`

I've had this set to false since always. I've set it to true and am faced to two misunderstandings.

1- When, how is this preloadlist updated?
2- Where is it located?

I just cannot find any file in my profile, be it new, be it modified.
I am wondering if this setting, to be functional (to have it downloaded) would depend on another setting that I would have disabled., i.e. one of the numerous safebrowsing settings found in about:config and more specifically a whatever url that I would have set to "" or 127.0.0.1

When this preload list is in place, how do I know it, how do I access it? Is it automatically merged to my SiteSecurityServiceState.txt file? If so that file shows nothing but the visited sites' HSTS ...

I cannot _conceptualize_ the whole process!

Thanks.

**Comment by earthlng** [comment]
Bonjour Tom, the list is compiled into FF from the file security/manager/ssl/nsSTSPreloadList.inc on DXR. I'm not sure it ever gets updated between releases but if so then it's probably done with `services.blocklist.pinning.*` but I think that's only used for HPKP updates. Atm the update data for that is empty.
You can find more information about services.blocklist.pinning if you search for it [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/47), ie the bugzilla, where it gets the updates from, how to disable it etc. I guess if there's ever any data to be updated it would likely get stored in SecurityPreloadState.txt, judging by the name and the fact that the file is empty atm.

**Comment by zymase** [comment]
Bonjour @earthlng , thanks. So it appears I had totally misunderstood the process -- even after havig read all I could find about the setting -- as I believed the file, a file, was regularly updated with latest domains having been accepted for https : hence, I was searching for it everywhere. I did know that it was included in Firefox builds, I thought that basis was hardcoded and then updated regularly ... 

OK, that's clear now. Before opening this thread I searched here but found no immediate topic related to mine which is why I opened a new "issue".

I'll close the door. Have a nice, sunny week-end!

**Comment by earthlng** [comment]
> Have a nice, sunny week-end!

Thanks! You too buddy

**Comment by zymase** [comment]
> Thanks! You too buddy
Please : mate, dude, pal ... but not _buddy_

Pants wasn't fond of "_just fine_" and zymase isn't of "_buddy_" :)

**Comment by earthlng** [comment]
Lol, okay, I realized it sounded kinda bad but it was already too late xD

Buddy is more fitting for dogs but dude to be fair your profile pic **is** a dog with what I assume are your eyes and mouth - what do you expect :)

btw you don't need to re-open an issue to comment again

**Comment by zymase** [comment]
I know some people actually talk to dogs but this is the first time I discover someone stating he writes to them!

**Comment by earthlng** [comment]
And guess what - they *answer* too xD
All I'm saying is that your avatar must have subconsciously influenced me to think that "buddy" is an appropriate word to use. I usually never use that word. DAMN I'm easily influenced - bad earthlng, bad ;)

**Comment by zymase** [comment]
An avatar doesn't answer :)
In fact I was talking about avatars and she proposed (she's an artist) to imagine something original given "_tu as du chien_". In French "_avoir du chien_" mean "to "_to be sexy_". She was playing on words as you did, but I guess her subconscious had been quite differently fed.

Computing leads to everything nowadays.

**Comment by Thorin-Oakenpants** [comment]
Get a room you two .. https://s-media-cache-ak0.pinimg.com/originals/3a/5f/6c/3a5f6c33244354d27fadf9714ffe0005.jpg
