### ISSUE TITLE
When to use arkenfox-cleanup.js

### ISSUE THREAD

**Issue by git70** [ghacksuserjs/ghacks-user.js#1669]
I wanted to dispel doubts because I didn't find information on the wiki: basically when should I use [arkenfox-cleanup.js](https://github.com/arkenfox/user.js/blob/master/scratchpad-scripts/arkenfox-cleanup.js) ?

Is it as regular as prefsCleaner or only in special cases (for example very old profile with very old user.js)?

If I have a fresh install of FF + applied AF111 + I will regularly update AF (and run prefsCleaner) = I don't have to worry about arkenfox-cleanup.js?

**Comment by Thorin-Oakenpants** [comment]
the cleanup is for existing profiles - basically as a backstop to reset things users may have changed in the past, and to get rid of noise e.g. deprecated prefs (so they get cleared).

If you're using 102+, a new profile only needs the user.js and prefsCleaner

**Comment by Thorin-Oakenpants** [comment]
Yup. I keep all relevant ESR stuff in the user.js until it reaches EOL (end of life) and then remove it the version after the following version.

So ESR/FF 115 will start, and ESR102 reaches EOL at https://wiki.mozilla.org/Release_Management/Calendar at same time as FF117, So I keep all that in for FF118 release, so the prefs cleaner still works for those who change _AFTER_ ESR102 EOL, and then remove it all in FF119

It used to be quite a bit in the past, but these days there is almost no change as FF features have made it to default/mainstream - and AF has been cleaned up
