### ISSUE TITLE
Raise TLS min to v1.1 (or v1.2)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#167]
- [SSL_HANDSHAKE_VERSION](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-07-08&keys=__none__!__none__!__none__&max_channel_version=nightly%252F56&measure=SSL_HANDSHAKE_VERSION&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-06-12&table=1&trim=1&use_submission_date=0) = 98.5% is TLS 1.2+ (nightly v56 a few weeks worth of data)

> TLS1.0 - 12.91M (1.52%)
> TLS1.1 - 442.17k (0.05%)
> TLS1.2 - 820.88M (96.94%)
> TLS1.3 - 12.52M (1.48%)

Currently (1202) `security.tls.version.min` has a default of `1` (meaning it allows TLS 1.0 as the minimum). The above nightly data I think shows page views.

I think we could actually flip this pref active and disable TLS 1.0 at the very least. The [article](https://www.ssl.com/how-to/turn-off-ssl-3-0-and-tls-1-0-in-your-browser/) linked in the user.js is now almost two and a half years old, and I think the landscape has changed significantly since then. I remember trying this back then (or shortly thereafter) and too many sites broke.

Class, discuss!

**Comment by earthlng** [comment]
Yes, I have disabled TLS1.0 ever since I created my user.js and nowadays I very rarely encounter pages that break. I'd say lets disable both 1.0 and 1.1 while we're at it.
One of the sites that didn't used to work was the securityartwork.es link in 1200's description but they seem to have recently updated to TLS1.2 as well.

Btw your linked article hides all the content by default. Fuck that! - let's replace the link with an archived version: https://archive.is/hY2Mm (created today)

**Comment by Atavic** [comment]
` * [WARNING] Sites with TLS 1.0 won't load with Error code: SSL_ERROR_NO_CYPHER_OVERLAP`

**Comment by Thorin-Oakenpants** [comment]
What error does one get if a site tries to use TLS1 or 1.1 ?

**Comment by Thorin-Oakenpants** [comment]
nits or :+1: 

```js
/* 1202: control TLS versions with min and max
 * 1=min version of TLS 1.0, 2=min version of TLS 1.1, 3=min version of TLS 1.2 etc
 * [WARNING] Jul-2017: Telemetry indicates approx 2% of TLS web traffic uses 1.0 or 1.1
 * [1] http://kb.mozillazine.org/Security.tls.version.*
 * [2] https://www.ssl.com/how-to/turn-off-ssl-3-0-and-tls-1-0-in-your-browser/
 * [2] archived: https://archive.is/hY2Mm ***/
user_pref("security.tls.version.min", 3);
user_pref("security.tls.version.fallback-limit", 3);
user_pref("security.tls.version.max", 4); // 4 = allow up to and including TLS 1.3
```

note the `archived:` - we also have one in 2668, which I will edit as well to use the same number. i.e the last time we archived one off to link, we still kept the original link, but when we renumbered [1]. [2] etc we should have kept the same number

```js
/* 2668: lock down allowed extension directories
 * [WARNING] This will break add-ons that do not use the default XPI directories
 * [1] https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
 * [1] archived: http://archive.is/DYjAM ***/  <<< THIS IS CURRENTLY A [2]
user_pref("extensions.enabledScopes", 1); // (hidden pref)
user_pref("extensions.autoDisableScopes", 15);
````

**Comment by 2glops** [comment]
TLS 1.2 min seems good.
Only very few sites should break.

**Comment by earthlng** [comment]
> we also have one in 2668, which I will edit as well to **use the same number**

:+1: 

nits:
* I'd make the WARNING a NOTE and add a `[WARNING] If you get an "SSL_ERROR_NO_CYPHER_OVERLAP" error temporarily set a lower value for 'security.tls.version.min' in about:config` or something like that.
* simply replace link [2] because fuck them and their shenanigans. The original link can still be seen at the top of the archived page
* I also don't like `version.max=4` because 0-RTT still sucks in TLS1.3 but that's just me

**Comment by Thorin-Oakenpants** [comment]
I like keeping the original url - there's only two on them

Huh? Wot? What's wrong with max=4? I'm the one that held off for ages by keeping it inactive while you pushed and pushed for it (and got salty!), and finally I made it active at 4 (https://github.com/ghacksuserjs/ghacks-user.js/commit/0006ee04b4bc3470894059a85727ef7f513548e0) a month ago, and it is the default (pending) for 55+, and now you're saying not to? We're also doing something about `pref("security.tls.enable_0rtt_data", true); // prev: false - (FF51+)` in the 54-55 diffs

**Comment by earthlng** [comment]
> while you pushed and pushed for it (and got salty!)

I always said "IF/WHEN the change lands in stable"! I still feel that way btw. So far it's beta-only.
I also don't remember getting salty about it

**Comment by Thorin-Oakenpants** [comment]
Salty, persistent, insistent .. same diff :) Anyway I pushed it 8 weeks & 1 release early (assuming value 4 lands in 55) because I thought you were dead keen on it, and I don't see any real problems with it (my argument before was to leave it inactive then whatever FF did would happen, but instead ~~we~~ I ramped it up). No big deal. 0rtt is false in 54, so no clash (not read up on this fully yet).

**Comment by Thorin-Oakenpants** [comment]
FYI: [telemetry](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2018-03-12&keys=__none__!__none__!__none__&max_channel_version=nightly%252F60&measure=SSL_HANDSHAKE_VERSION&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2018-01-22&table=1&trim=1&use_submission_date=0)

Nightly 60, 7 weeks worth of data .. <TLS1.2 = 0.91% (down from 1.57% 9 months ago)

![tls](https://user-images.githubusercontent.com/16656956/38747803-90fdd3de-3f3b-11e8-8d9c-54bba29c003c.png)

Personally, I have in the last 9 months since we changed the min pref to `3`, only ever had about 4 sites that failed - old research sites, nothing mainstream

**Comment by Thorin-Oakenpants** [comment]
Read this the other day - https://blog.mozilla.org/security/2018/02/28/analysis-alexa-top-1m-sites-2/

The HTTPS stats are interesting
- HTTPS: 54.31%
- HTTP->HTTPS redirection: 32.82%

Not sure if there is overlap in that - so maybe 87+% of the top 1M sites are now HTTPS (compared to 68+% eight months earlier). That's sites, not traffic - makes sense that page loads would be higher as I would expect the most traffic heavy sites to now be secure

Now that I've typed all that out, this is the wrong issue - it was more about the mixed passive content when we flipped that. Oh well. FYI, enjoy :)

PS: Mozilla should change the default for schemeless URLs in the urlbar to HTTPS - @fmarier is there a bugzilla for this

**Comment by Thorin-Oakenpants** [comment]
- https://bugzilla.mozilla.org/show_bug.cgi?id=1158191
- https://bugzilla.mozilla.org/show_bug.cgi?id=1002724

https://bugzilla.mozilla.org/show_bug.cgi?id=1158191#c47 & link to telemetry graphs
> About 30-40% of page loads are done over HTTP, as of December 2017 

The subsequent comment mentions 90% being a threshold. Oh well, hurry up internet, get your sh^t together already ! :) More useless free FYI courtesy of :jeans:

**Comment by Thorin-Oakenpants** [comment]
[telemetry up to and including nightly 61](https://telemetry.mozilla.org/new-pipeline/evo.html#!aggregates=bucket-0!bucket-1!bucket-2&cumulative=0&end_date=null&keys=&max_channel_version=nightly%252F61&measure=HTTP_PAGELOAD_IS_SSL&min_channel_version=nightly%252F56&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=null&trim=1&use_submission_date=0) .. looks like nightly 61 is more around the 70-75% mark now. So maybe another 6 months?
