### ISSUE TITLE
extras 2300: web workers [notifications/push/updates]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#170]
https://support.mozilla.org/en-US/questions/1165867#answer-981820

There is some good info here about what exactly each pref does. Should be write this up as a FYI issue, or as a Wiki Article (the first) and link to it? Or add some of this into the js?

**Comment by earthlng** [comment]
IMO just add the link as [2] to 2304.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/54cf998f789fe76882d4f3eba612b04961efd19b
