### ISSUE TITLE
investigate: site exceptions Maintain Offline Storage

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#173]
Maintain Offline Storage is a site permission. It used to be in the preferences UI, but was dropped in FF46. You now get to it per site via urlbar info icon > Right Arrow > More Information > Permissions

- Clarify just WTF is this meant to control. The default setting (regardless of prefs for various storage items) seems to be "Always Ask"
- Is there a way to make the default "block", and then users can apply site overrides for allow?
- When a site has this blocked, there is a plain square icon with a stroke thru it in your urlbar next to the info icon. If you mouse over, it says "You have blocked data storage for this site". If you click that icon, you get an option to undo the block (which sets the permission back to default)
- Weird fact: in playing around with this, `google.com` always showed a blocked-data-storage icon and the permissions when I looked them up were always "default". But as soon as I clicked unblock, now the only way to get `google.com` to block-data-storage is to override in permissions. Sorcery!
- Update on above bullet point. I haven;t cleaned out my site permissions for like 2.5 years since I did a clean profile. It was probably an old site permission hanging around - I will of course check it out in a nilla FF. NotSorcery!?

Relevant discussion: https://www.wilderssecurity.com/threads/firefox-and-indexeddb.395113/

This is meant to control indexedDB as far as I know (and it has said that in the user.js since the start over 2 years ago). As per the above link, user `summerheat` said that toggling this site pref made no difference (something about some content on New York Times is not shown when indexedDB is off, but shows when indexedDB is on).

We should replicate this test, and confirm in a vanilla Firefox. First, find a test page where a) with indexedDB=true we see the stuff, and b) after clearing cache with indexedDB=false we don't see the stuff and c) clear cache and do a site exception

Maybe @zymase can tell us a website, since he toggles this pref a lot. Personally, I think this is broken.

**Comment by Thorin-Oakenpants** [comment]
earthlng said

> > [quoting Thorin] What is the pref that changes "Always ask" to "block" - that way I can have a default deny-all and assign site exceptions
> 
> https://dxr.mozilla.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.dtd#232
-> it should definitely be "indexedDB" if it says "You have blocked data storage for this website" as you wrote above
https://dxr.mozilla.org/mozilla-central/source/browser/modules/SitePermissions.jsm#532
-> looks like not all permissions can be set to "block" by default. Currently (nightly) it's only possible for image, cookie, popup and install. For me everything except popup and install is either defaulting to "allow" or "always ask" (I allow cookies and control them with uMatrix - everything else should match what you get) Maybe there's other code somewhere that I can't find that also looks at other prefs for that GUI but I think that's largely it.

**Comment by 2glops** [comment]
https://www.nextinpact.com/news/104602-windows-10-s-ses-capacites-et-restrictions-en-11-questions.htm

IndexedDB enabled = see comments under the article
IndexedDB disabled = don't see comments
IndexedDB disabled + site permission allow = still don't see comments

**Comment by Thorin-Oakenpants** [comment]
@2glops Excellent. I haven't looked at it, will do tomorrow. Have run out of time.

PS: I assume you cleared the cache between tests?

**Comment by 2glops** [comment]
Yes, cache cleared.

**Comment by Thorin-Oakenpants** [comment]
heh: seems it has been "broken" a long long time ( https://bugzilla.redhat.com/show_bug.cgi?id=1122985 ). Told you me and Tom talked about this like a year+ ago.

From 5 years ago but may be relevant (and clears a few things up if this has largely stayed the same) - https://bugzilla.mozilla.org/show_bug.cgi?id=832660#c1

> LocalStorage is treated like Cookies:
>  - if cookies are blocked then so is localStorage
>  - if you forget all cookies for a site then localStorage is cleared
>  - if your cookie settings are such that cookies last for the session only then localStorage is only held in memory and also go away when you shut down the browser otherwise there's no visibility into how much or what is stored
> 
> There's an "Appcache" feature to store web pages and sub-resources (scripts, images, style-sheets, etc) for offline use. THIS is what the visible preference controls (the sub-resources are what it's calling "data").
> 
> IndexedDB
>  - Like cookies and localStorage, if the feature isn't disabled sites get to use it. A need to ask first was deemed a bad experience and likely to make it too unreliable a feature for sites to use.
>  - If a site uses "too much" data (the "warningQuota" defaults to 50Mb) then the user gets asked
>  - unlike localStorage the "session only" cookie setting is irrelevant
>  - Like localStorage the feature was implemented before any UI was designed. There is no visibility into which sites are using it, how much data is stored, nor any way I know of getting rid of it (maybe the "forget this site" feature that blows everything away, but maybe not)

**Comment by 2glops** [comment]
https://blog.nightly.mozilla.org/2017/07/17/preview-storage-api-in-firefox-nightly/

Preview Storage API lands in Nightly
Just in time !

**Comment by Thorin-Oakenpants** [comment]
FYI: [eCleaner](https://github.com/andy-portmen/ecleaner/issues) cleans indexedDB

**Comment by Thorin-Oakenpants** [comment]
closing this - see the meta issue #188

**Comment by earthlng** [comment]
> FYI: eCleaner cleans indexedDB

FYI: eCleaner definitely does not clean indexedDB in Firefox at the moment!
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/remove#Browser_compatibility
> Firefox does not support removal of: 'fileSystems', 'indexedDB', 'localStorage', or 'serverBoundCertificates'

**Comment by Thorin-Oakenpants** [comment]
Yeah, that comment was almost 5 weeks ago, eCleaner was early days, and I had issues with it (haven't looked at it since). Was busy focused on 55... since then we have more info on what Web Exts are having issues with and new bugs coming along re persistant storage etc. I linked a couple in 188.

> Firefox does not support removal of: 'fileSystems', 'indexedDB', 'localStorage', or 'serverBoundCertificates'

Its a dynamic landscape right now. WE APIs is like a black canvas and with enough hammering we might get what we would like. local storage has already been opened up, they just need to apply by host I believe. indexedDB is being hammered away at by a persistent dedicated person (I will give him the internet award when he succeeds with this outcome -> [1340511](https://bugzilla.mozilla.org/show_bug.cgi?id=1340511) .. see comment0 .. the uber-enthusiastic guy is comment1

- https://bugzilla.mozilla.org/show_bug.cgi?id=1388428 - remove local storage BY HOST
- https://bugzilla.mozilla.org/show_bug.cgi?id=1333050 - removed indexedDB (read on, by host)
- we already have remove cookies by host, but issues with FPI

those are the big three IMO, followed by serviceWorkers (which we block), cacheStorage, applicationCache  .. we already disable cache on disk, and disable OfflineCache, not 100% sure what applicationCache is (I do not want to lose web ext settings)
