### ISSUE TITLE
A few questions (activity-stream, RFP, File types)

### ISSUE THREAD

**Issue by hashbi** [ghacksuserjs/ghacks-user.js#1749]
I would open a discussion but its not enabled for this repo

1. 
    Is there a way to disable activity stream? I dont use it and I have 10 prefs disabling features with it

    Before this pref was used and seems to still work but is not documented here (deprecated?):
    ```user_pref("browser.newtabpage.activity-stream.enabled", false);```

2.
    Tor-browser changed to landscape for RFP with these prefs:
    ```user_pref("privacy.window.maxInnerWidth", 1400); user_pref("privacy.window.maxInnerHeight", 900); ```

    Question: Wouldnt it be better to increase crowd blending score and use the same prefs as that browser?
3.
    Is there a way to set these file types to Always ask by default? changing them does not update firefox prefs.js

![Screenshot](https://github.com/arkenfox/user.js/assets/148921709/fc5c87e5-5b61-4188-a310-d3a69bff1500)

**Comment by Thorin-Oakenpants** [comment]
> I have these any many more but doesnt answer the question

1. We don't use AS by default. If users want to change to firefox home as default, then there is a UI they can use to decide what to display. This (AS) is not a privacy or tracking issue, and only mozilla has access to this and they don't care (i.e it's first party): regional lists of pocket stories/links stored locally, snippets, recommendation/cfr, etc - are all just noise you can turn on/off. Telemetry is already covered by the master pref(s) and once again telemetry in mozilla is not a privacy issue - if you don't trust mozilla to be doing the right thing here (and there is ample documentation, proof and history) then why are you using Firefox (rhetorical question) - not to be confused with checking things and keeping them "honest"? The one area I am not 100% sure on is pocket links/clicks, which I think are aggregated in some form (as a 3rd party, but owned by mozilla) to measure engagement - its nothing to worry about IMO - if you don't want to see them, then turn it off in the UI. 

It is not arkenfox's purview to arbitrarily decide any of this - believe it or not, but Pocket recommended story links, and Pocket as a service (i.e sign up) actually provide useful services that many users use and enjoy. But AF does actually disable some as unwanted noise universally not wanted by the AF crowd, or at odds (e.g. recommending extensions), or a concern (however mild: e.g sponsored shortcuts: I forget the details as to WHY I added it)

I'm also not interested in diving down the AS "rabbit hole" or it's maintenance (it used to change a lot, all the fucking time, but is probably somewhat stable now). it's not a security or FP issue, so knock yourself wasting time and energy on it all

> newwin sizes

2. what c3d1c06c-bf26-477e-b0eb-c50ef4477ba6 said - for the record, I initiated and pushed for that change at TB - it was my research that decided the size

Did you read the wiki? https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-summary - tl;dr: Firefox does not have a crowd to blend into
