### ISSUE TITLE
Just a heads up for Nightly users: browser.urlbar.speculativeConnect.enabled

### ISSUE THREAD

**Issue by publicarray** [ghacksuserjs/ghacks-user.js#175]
Nightly users concerned with privacy probably want to turn this off: `browser.urlbar.speculativeConnect.enabled`

It is designed to improve performance by starting a connection to an autocompleted hostname from the awesomebar. e.g. type `fb` and Firefox makes an autocompletion to `facebook.com` and may start connecting to facebook.

https://bugzilla.mozilla.org/show_bug.cgi?id=1348275

https://hg.mozilla.org/integration/autoland/rev/071beab1c31e

**Comment by Thorin-Oakenpants** [comment]
Thanks @publicarray

**Comment by Thorin-Oakenpants** [comment]
Sheeshus christ ... speculative connection is now added to the Current Search Engine https://bugzilla.mozilla.org/show_bug.cgi?id=1355443

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1385453 - Speculatively warm up tabs - not sure if this just for rendering pre-loaded tabs, tl;dr but speculative caught my eye :)

**Comment by earthlng** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1355443#c10

> `browser.search.suggest.enabled` is the general pref that controls suggestions in both the location bar AND the search bar.
> `browser.urlbar.suggest.searches` is a sub-pref that controls the behavior only in the location bar.
> Additionally, `keyword.enabled` is a pref that controls whether the default action from the location bar should be a search.
