### ISSUE TITLE
Using VirusTotal to scan files with Firefox Mobile or Firefox Focus?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#176]
A bit OT, but is anyone able to use VirusTotal to scan files with Firefox Mobile or Firefox Focus/Klar?

I've tried requesting the mobile site as well as the desktop site, but the file chooser is never shown (thus unable to scan files).  I've tweaked settings, but nothing has worked so far.

Any solution?  Or has Google designed VirusTotal to no longer work with Firefox Mobile?

**Comment by Forsaked** [comment]
Firefox mobile works for me, but not Focus/Klar.
But this is very OT und shouldn't discussed here.

For Focus/Klar open an issue here: https://github.com/mozilla-mobile/focus-android/issues

**Comment by Gitoffthelawn** [comment]
@Forsaked Thanks.  I wonder why it's working for Firefox Mobile for you, but not myself.  What version are you running?  Any settings that might help get it to work?

**Comment by Forsaked** [comment]
Could it be that your Firefox mobile has no rights to use the camera/local storage, check this under App-Settings.
Everything else is nearly stock except my search pages and uBlock Origin.

**Comment by Gitoffthelawn** [comment]
Thanks again.  It has storage permission, but not camera.  But not working with VT.
