### ISSUE TITLE
follow-on-search system addon - Why the secrecy??

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#177]
Pants the master detective [found something pretty interesting](https://github.com/ghacksuserjs/ghacks-user.js/issues/144#issuecomment-310110044):

> What the hell is this: https://bugzilla.mozilla.org/show_bug.cgi?id=1367561  - a system add-on to track searches (a lot of tickets are access denied).

5 (!!!) ACCESS DENIED tickets for a simple system addon ???!!!
https://bugzilla.mozilla.org/show_bug.cgi?id=1367554
https://bugzilla.mozilla.org/show_bug.cgi?id=1367582
https://bugzilla.mozilla.org/show_bug.cgi?id=1369435
https://bugzilla.mozilla.org/show_bug.cgi?id=1369513
https://bugzilla.mozilla.org/show_bug.cgi?id=1369802

And this shit is now deployed to 100% of 54 users (you included if you let them)

@fmarier do you have access to these tickets? Can you please give us some insight?
This certainly has nothing to do with keeping tickets private for security reasons, right?
Does mozilla keep certain tickets private forever or will we eventually be able to see them?
Can comments on bugzilla be edited or deleted? ie scrubbing the tickets before letting the public in?

**Comment by Thorin-Oakenpants** [comment]
> And this shit is now deployed to 100% of 54 users (you included if you let them)

I never got it with FF54 or FF54.0.1 portable. Of course due to #172 I do not receive system updates, so it is possible that they have already "pushed" it.

Personally, I am really starting to think of blocking system updates viz the URL, adding a bunch of xpi files to CCleaner for backup, and manually checking the features folder every update (which I do anyway) .. in order to keep deleted items deleted. I think I might delete all of them at this rate - even screenshots (because better extensions exist - or will soon, it;s being ported)

**Comment by Atavic** [comment]
Some `distributionId` or Build ID [info](https://wiki.mozilla.org/Firefox_Rebranding:Worksheet#Build_Identification).

`Each unique configuration must be identified separately through a unique distribution ID. `

It is optional and it's the last entry in the user agent string. Every mobile build has it BTW

**Comment by Atavic** [comment]
> we test our new [search_count telemetry](https://github.com/mozilla/python_mozetl/blob/7b0ca99bb1c0801048fb72777c994d87aacfafe9/mozetl/constants.py) developed in:
> https://bugzilla.mozilla.org/show_bug.cgi?id=1367554

**Comment by Thorin-Oakenpants** [comment]
@Atavic That's all for UI driven counters (urlbar, searchbar, activity stream, newtab, etc). What we want to know more about is this additional counting, or "follow on searches" - i.e if you use a Mozilla partner search engine (eg Yahoo - I do not know if it needs to be the one provided or eg a sanitized one you added yourself) it would count that, and then if you searched on the yahoo page, it would count that as well (I do not know if that means the page must have been loaded from a yahoo UI search, or just any yahoo search page such as a bookmark loaded page).

**Comment by Atavic** [comment]
>if you use a Mozilla partner search engine it would count that

Yes. (wait, ìreopening pages...)

**Comment by Thorin-Oakenpants** [comment]
https://dxr.mozilla.org/mozilla-central/source/browser/extensions/followonsearch/content/followonsearch-fs.js  - lists the SAPs

**Comment by Thorin-Oakenpants** [comment]
> follow-on-search system addon - Why the secrecy??

Regardless of the tickets being hidden for whatever reason (commercial sensitivity?), you will not get any answers to this question, and the resulting code from the system add-on is open source.
