### ISSUE TITLE
Typos and some questions

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#178]
- [x] for tracking protection. but many steps >> something isn't right
- [x] //user_pref("general.appname.override", "Netscape"); // (hidden pref) >> space missing
- [x] dom & DOM >> inconsistent usage
- [x] eg & e.g & e.g. >> inconsistent usage
- [x] by bundling it's own code >> its???
- [x] /* 2705: disable dom storage >> expand to (Document Object Model)???
- [x] combined in the firefox interface >> firefox with capital letter "F"

P.S.:
- [ ] e.g. but i.e >> inconsistent usage
- [ ] but many steps >> something isn't right

Some quick questions:

1. I'm considering configuring **browser.cache.memory.enable** to TRUE. Is this pref about memory consumption only, or it has privacy / security implications?

2. If I set **network.http.sendRefererHeader** to 0 do I have to set **network.http.referer.userControlPolicy** to 0 as well? What's the difference between these two prefs?

**Comment by Atavic** [comment]
1. [Implications](https://www.grepular.com/Preventing_Web_Tracking_via_the_Browser_Cache)

2. https://github.com/ghacksuserjs/ghacks-user.js/issues/5#issuecomment-280867769

**Comment by Thorin-Oakenpants** [comment]
* `browser.cache.memory.enable` - why on earth did you make the pref active and false? Are you mad? Are you a super secret Russian spy? Wait .. are you Guccifer 2.0? Seriously, using RAM is all good for performance. Extracting stuff from RAM is not impossible but really requires possession of your device. If your device is secure (sole user, not left untended, locked when not in use, chained/bolted to a desk, you use a strong password to log in, the drives are encrypted, you own a dozen attack/guard dogs and a small personal army of murder-death-kill bots and/or ninjas), then well hell, son, what were you thinking?

* `network.http.sendRefererHeader` (1601) and `network.http.referer.userControlPolicy` (1605) are not the same type of thing
   * 1601 is what OBJECTS are allowed referrers - options are combinations of links, images, and nothing
   * 1605 is a default policy to use when sites have no policy. It refers to what INFORMATION goes in the referer
   * So one has nothing to do directly with the other, or rather the value of one should not decide/affect the value in the other. (although if you block all referers in 1601, the other prefs become moot)

**Comment by Just-me-ghacks** [comment]
This [test](http://lucb1e.com/rp/cookielesscookies/) would make me think twice before enabling **browser.cache.memory.enable**

**Comment by Thorin-Oakenpants** [comment]
ETags are well known. I like that test page

**Comment by Thorin-Oakenpants** [comment]
@Just-me-ghacks 
> but many steps >> something isn't right

Reads fine to me

> **These do rely on 3rd parties** (Google for SB and Disconnect for TP)**, but many steps**, which are continually being improved, **have been taken to preserve privacy**.

or let me put it another way

> These do rely on 3rd parties, but many steps have been taken to preserve privacy.

Yup, I see I still left in the period, it should be a comma - my bad.

**Comment by Thorin-Oakenpants** [comment]
* [x] addon-ons

How did you not pick this up Just-me. Bitterly disappointed bro!

**Comment by Thorin-Oakenpants** [comment]
FYI: I added that test to the Wiki: [Appendix C: Test Sites](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites)

**Comment by Just-me-ghacks** [comment]
- [ ]  //bookmarks toolbar >> space missing after //

**Comment by Thorin-Oakenpants** [comment]
* [ ] //bookmarks toolbar >> space missing after //

will do when I do another commit for something else. I might even look at the inconsistencies with spaces and the = sign when I list preference values eg `1=never 2=always` vs `1 = never 2 = always`

**Comment by Just-me-ghacks** [comment]
Sure. The less commits the better.
