### ISSUE TITLE
add pref to delete using `user-overrides.js`?

### ISSUE THREAD

**Issue by Obegg** [ghacksuserjs/ghacks-user.js#1832]
There is a perf I want to remove
```
user_pref("browser.bookmarks.addedImportButton", true);
```
But If I add this to `user-overrides.js` it will be added to perfs,
so how can I make sure this perf is deleted?

**Comment by rusty-snake** [comment]
You can not delete prefs using `user.js`. You can empty their value (`user_pref("foo.bar", "");`).

If you want to delete a hidden pref, use `about:config` or edit `prefs.js` when Firefox is closed.
