### ISSUE TITLE
user perf for search shortcuts

### ISSUE THREAD

**Issue by Obegg** [ghacksuserjs/ghacks-user.js#1833]
I'm trying to find the perf for search shortcuts, it doesn't seem to have any on `about:config`, anyone have any ideas?

![image](https://github.com/arkenfox/user.js/assets/13978119/736a455c-e430-4d16-97db-19b8a583a16b)

**Comment by rusty-snake** [comment]
What do you mean with "the perf for search shortcuts"? You want to disable them? Configure/Change them? Add new ones?

**Comment by rusty-snake** [comment]
`browser.urlbar.shortcuts.*`
