### ISSUE TITLE
VOTE: disable form history

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#186]
First to one million wins :) Nah, I just want some feedback.

It has been mooted that forms history be disabled. I mean how often does this come in handy (I know it does for me for a few minutes at a time for specific tasks - eg some searches - I assume this affects search history in the search bar). I can live without it. I actually clear form history in ctrl-shift-del. Form history is also cleared on close.
I'm happy to set `0860` to active [ user_pref("browser.formfill.enable", false); ]

Vote (non-binding, I just want feedback)
:+1: to make user_pref("browser.formfill.enable", false); ACTIVE
:-1:  to keep the status quo where this pref is INACTIVE

**Comment by Thorin-Oakenpants** [comment]
Also 0861 (browser.formfill.saveHttpsForms) could be made active as well to be consistent - or weas this one that was about to be deprecated, earthlng?

**Comment by Just-me-ghacks** [comment]
They are both FALSE and ACTIVE in my user.js

**Comment by earthlng** [comment]
> Also 0861 (browser.formfill.saveHttpsForms) could be made active as well to be consistent - or was this one that was about to be deprecated, earthlng?

yes that's the one. But since we keep the deprecated/removed prefs in the same state but group-commented-out in 9999, if we make .enable active we should also make .saveHttpsForms active before we move it to 9999 IMO

**Comment by Thorin-Oakenpants** [comment]
^^ Yup. Planned on that too, specially now most people will be split off into two camps - ESR based on 52 and now 55+. That deprecated section is going to come in handy
