### ISSUE TITLE
Are `network.dns.disablePrefetch`/`network.dns.disablePrefetchFromHTTPS` master switches of   `dom.prefetch_dns_for_anchor_http_document`/`dom.prefetch_dns_for_anchor_https_document`?

### ISSUE THREAD

**Issue by Jee-Hex** [ghacksuserjs/ghacks-user.js#1870]
@mik0l commented in https://github.com/arkenfox/user.js/pull/1862#discussion_r1666888418

> network.dns.* main switches, they already cover dom.prefetch_dns_for_anchor_http(s)_document

So I used the following test case (inspired by [bug 1596935 comment 28](https://bugzilla.mozilla.org/show_bug.cgi?id=1596935#c28)):

1. Start [HTTP logging](https://firefox-source-docs.mozilla.org/networking/http/logging.html).
2. Open a new tab and open the Network Monitor beforehand.
3. Visit `https://en.wikipedia.org/wiki/Main_Page`. AFAICT the page do not request any resources from `meta.wikimedia.org` yet contains `<link rel="dns-prefetch" href="//meta.wikimedia.org" />` in its source, so that's what we will be watching out for.
4. Stop HTTP logging.
5. Open `about:networking#dns` to confirm any resolved hostnames.
6. Check the Network Monitor to see if any resources were requested from these hostnames.
7. Check the HTTP logs for entries like `D/nsHostResolver Resolving Host [meta.wikimedia.org]<^partitionKey=%28https%2Cwikipedia%2Corg%29> type 0. [this=blahblahblah]`

Using a vanilla 127.0.2 (i.e. `dom.prefetch_dns_for_anchor_https_document`= false, `network.dns.disablePrefetchFromHTTPS`= false):

```
 I see DNS lookups for `meta.wikimedia.org` (Expected Behavior).
```

with `dom.prefetch_dns_for_anchor_https_document`= __true__, `network.dns.disablePrefetchFromHTTPS`= false:

```
In addition to `meta.wikimedia.org`, I also see DNS lookups for other Wikipedia editions (e.g. `ja.wikipedia.org`) (Expected Behavior).
```

with `dom.prefetch_dns_for_anchor_https_document`= __true__, `network.dns.disablePrefetchFromHTTPS`= __true__:

```
No DNS lookups for `meta.wikimedia.org` or other Wikipedia editions (Expected if `network.dns.disablePrefetchFromHTTPS` is the master switch for `dom.prefetch_dns_for_anchor_https_document`).
```

with `dom.prefetch_dns_for_anchor_http_document`= true, `dom.prefetch_dns_for_anchor_https_document`= __true__, `network.dns.disablePrefetch`= __true__, and `network.dns.disablePrefetchFromHTTPS`= false:

```
No DNS lookups for `meta.wikimedia.org` or other Wikipedia editions!
```

with `dom.prefetch_dns_for_anchor_http_document`= __false__, `dom.prefetch_dns_for_anchor_https_document`= __true__, `network.dns.disablePrefetch`= false, and `network.dns.disablePrefetchFromHTTPS`= false:

```
DNS lookups for `meta.wikimedia.org` and other Wikipedia editions (Expected Behavior).
```

with `dom.prefetch_dns_for_anchor_http_document`= __false__, `dom.prefetch_dns_for_anchor_https_document`= __true__, `network.dns.disablePrefetch`= __true__, and `network.dns.disablePrefetchFromHTTPS`= false:

```
No DNS lookups for `meta.wikimedia.org` or other Wikipedia editions!
```

with `dom.prefetch_dns_for_anchor_http_document`= __false__, `dom.prefetch_dns_for_anchor_https_document`= false, `network.dns.disablePrefetch`= __true__, and `network.dns.disablePrefetchFromHTTPS`= __true__:

```
No DNS lookups for `meta.wikimedia.org` or other Wikipedia editions (Expected Behavior).
```

Am I missing something or is there a bug somewhere?

**Comment by Thorin-Oakenpants** [comment]
okie dokie - thanks for testing
