### ISSUE TITLE
Firefox Labs: possible tracking?

### ISSUE THREAD

**Issue by Tiagoquix** [ghacksuserjs/ghacks-user.js#1893]
https://www.mozilla.org/en-US/firefox/130.0/releasenotes/

"Firefox now offers an easy way to try experimental features with a new Firefox Labs page in Settings."

Wondering if this is either new tracking (like Firefox Studies) or if it's something we should disable in the user.js. What are your opinions?

**Comment by rusty-snake** [comment]
A new page in the settings that allows *you* to enable some experimental feature without going to about:config. Where's the tracking?

**Comment by Thorin-Oakenpants** [comment]
> I thought there would be some way for Mozilla to add some sort of telemetry for those who enable the experimental features

There is. It's called telemetry
