### ISSUE TITLE
Additional comment for 1002

### ISSUE THREAD

**Issue by Tiagoquix** [ghacksuserjs/ghacks-user.js#1898]
We could add "increase its maximum size" for `1002`, similar to the Tor Browser comment.

https://gitlab.torproject.org/tpo/applications/tor-browser/-/blob/tor-browser-128.2.0esr-14.0-1/browser/app/profile/001-base-profile.js#L82

**Comment by Thorin-Oakenpants** [comment]
sure: https://github.com/arkenfox/user.js/pull/1892/commits/6b11be78beb7f68969abf22ed63224149d1e500a
