### ISSUE TITLE
About 0200: GEOLOCATION

### ISSUE THREAD

**Issue by rebrovov** [ghacksuserjs/ghacks-user.js#194]
Is it a good idea to spoof these preferences :

user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("intl.locale.matchOS", false);
user_pref("general.useragent.locale", "en-US");
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoSpecificDefaults.url", "");
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);

If I do not use VPN and English is not common in my location it will only make me unique among the other users. Am I not right?

**Comment by Thorin-Oakenpants** [comment]
Why bother then - you're GIVING AWAY your IP. What's worse?

**Comment by rebrovov** [comment]
I have dynamic ip ?

**Comment by Thorin-Oakenpants** [comment]
Your fingerprint is already high (we all are). And you are right to think about smaller subsets. Yes, in the land of the blind, the one eyed man is king. If I go visit France to see Tom, and take my laptop, which is on English UK local, UK time zone, UK date format etc, and I'm in Paris surfing the net, I stand out like a dog's balls.

You just need to weigh your options and make a decision.

For what's it worth, resistFingerprinting will enforce English (or at least warn you when not in english), so IDK. Tricky for non-English as a first language users, in non-English countries.
