### ISSUE TITLE
Awesome: NOT! pingsender.exe

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#198]
https://bugzilla.mozilla.org/show_bug.cgi?id=1336360

Class, discuss! Now I have external exe's trying to send telemetry. Needs investigation

**Comment by rebrovov** [comment]
I spent the whole day with FF 55. pingsender.exe did not attempt to connect to the Internet. The firewall would have warned me. But for a long time already I block access firefox.exe to localhost. Maybe that's the reason there is no connection.

**Comment by Thorin-Oakenpants** [comment]
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false); // (FF55+)

We have it covered
