### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by nodiscc** [ghacksuserjs/ghacks-user.js#2]
Ref. https://github.com/pyllyukko/user.js/issues/205

> Anyway - pillage away .. arrrh :)

:) It would be good to add a License to this work to make it clear how you allow it to be copied/used/redistributed. https://github.com/pyllyukko/user.js uses the [MIT](https://github.com/pyllyukko/user.js/blob/master/LICENSE.txt) license, but you could choose any other permissive license (no restriction on usage/redistribution, but copies must retain authors info).

For example for [this repo](https://github.com/Kickball/awesome-selfhosted) we used [CC-BY-SA](https://github.com/Kickball/awesome-selfhosted/blob/master/LICENSE), and it worked [quite well](https://github.com/Kickball/awesome-selfhosted/blob/master/AUTHORS.md).

Some links to help you pick one:
 * https://choosealicense.com/licenses/
 * https://blog.codinghorror.com/pick-a-license-any-license/
 * https://tldrlegal.com/

**Comment by Roman-Nopantski** [comment]
Thanks - it's all over my head. I guess I better add this repo's url to the js. I'll have a read up when I get time. MIT sounds good. I don't care if anyone else claims it as their own - those in the know, know where to go to keep getting the good stuff :) Although it would be nice to make sure no-one can profit from it - it should always be free. I am so confused what to pick.

**Comment by Atavic** [comment]
GPL, MIT and Mozilla licenses allow a commercial use. 

https://tldrlegal.com/license/creative-commons-attribution-noncommercial-sharealike-4.0-international-(cc-by-nc-sa-4.0) doesn't allow it.

**Comment by Roman-Nopantski** [comment]
OK .. I'm going with MIT .. zero restrictions except the license needs to tag along with it. Seems about right. Who am I to deny anyone ... adding in 3... 2... 1...

**Comment by pyllyukko** [comment]
The MIT license seems the most straightforward.
