### ISSUE TITLE
Disable lock window resolution 1000x900 on Firefox 55

### ISSUE THREAD

**Issue by rebrovov** [ghacksuserjs/ghacks-user.js#200]
Is there any way to disable lock window resolution 1000x900 on Firefox 55 ? Maybe some kind of preference is responsible for this.

**Comment by Thorin-Oakenpants** [comment]
see section 2699. It is part of privacy.resistFingerprinting (2699a) and the relevant info is in 2699b with some override values you can use. Note that inner windows will still be rounded to width (200s) and height (100s)

```js
/* 2699b: set new window sizes to round to hundreds (FF55+) [SETUP]
 * [NOTE] Width will round to multiples of 200s and height to 100s, to fit your screen.
 * The override values are a starting point to round from if you want some control
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1330882
 * [2] https://metrics.mozilla.com/firefox-hardware-report/ ***/
user_pref("privacy.window.maxInnerWidth", 1400); // (hidden pref)
user_pref("privacy.window.maxInnerHeight", 800); // (hidden pref)
```

I open mine as 1600x900

**Comment by rebrovov** [comment]
No. I want to disable this completely. Make it as it was on Firefox 54 and lower.

**Comment by earthlng** [comment]
> No. I want to disable this completely. Make it as it was on Firefox 54 and lower.

set `privacy.resistFingerprinting` to false

**Comment by rebrovov** [comment]
What other preferences will it disable except privacy.window.maxInnerWidth and privacy.window.maxInnerHeight.

**Comment by Thorin-Oakenpants** [comment]
> What other preferences will it disable

If you make `privacy.resistFingerprinting` back at default false, then you will not get any of the items listed in 2699 - there's a huge list right there. Some of these are already covered by existing prefs - I have added (see xxxx) comments to them.

Not all existing prefs do the exact same thing - eg
` ** 1372072 - spoof network information API as "unknown" (see 2503) (FF56+)`
As  you can see `privacy.resistFingerprinting` will override pref 2503 and return "unknown" whereas pref 2503 just refuses to provide anything

**Comment by earthlng** [comment]
No prefs afaik but you will disable these
 ** 1281949 - spoof screen orientation (FF50+)
 ** 1281963 - hide the contents of navigator.plugins and navigator.mimeTypes (FF50+)
 ** 1330890 - spoof timezone as UTC 0 (FF55+)
 ** 1360039 - spoof navigator.hardwareConcurrency as 2 (also see 2514) (FF55+)
      This spoof *shouldn't* affect core chrome/Firefox performance
 ** 1217238 - reduce precision of time exposed by javascript (FF55+)
The numbers are bugzilla tickets, fe https://bugzilla.mozilla.org/show_bug.cgi?id=**1281949**

**Comment by Thorin-Oakenpants** [comment]
Some things you will lose and not be able to fix
- spoofing screen res, browser windows, inner window, etc as all the same and stop multiple leaks about res etc from css media and other techniques
- you will no longer be able to block plugins and mimetypes being enumerated
- you cannot spoof your time zone (non Linux - in nixland yu can set a TMZ thingie to do with when you load the app, not my area)
- you will not get all the timing attack mitigations, including perfomance API
- you will not be able to properly spoof your UA and navigator objects

That's it so far (up to FF56), everything else has previous prefs. But there is a lot more to go

Just open your browser in some config of 200sx100s and be done with it man. Adapt or die :)

**Comment by rebrovov** [comment]
Yes you are right. I can not sacrifice all of this. Will have to get used to.

**Comment by Thorin-Oakenpants** [comment]
Good. You have gained +10 Evolution-from-dinousaurs

**Comment by Theemim** [comment]
My feeling is that it is a mistake for Mozilla to remove, or otherwise not support, individual prefs which can be used to control the same things that resistFingerprinting can.  Because there are cases where enabling things with fingerprinting potential makes sense and could (should) be controllable on a per site basis.  For example, fingerprinting is used by some banks and other orgs to recognize the devices you log in from.  Am I alone in thinking this way?
