### ISSUE TITLE
Probably don't set `media.eme.chromium-api.enabled` to `false`

### ISSUE THREAD

**Issue by Okamoi** [ghacksuserjs/ghacks-user.js#201]
https://dxr.mozilla.org/mozilla-central/source/dom/media/eme/MediaKeySystemAccess.cpp#108
https://dxr.mozilla.org/mozilla-central/source/dom/media/eme/MediaKeys.cpp#347
https://dxr.mozilla.org/mozilla-central/source/dom/media/gmp/GMPParent.cpp#743
https://dxr.mozilla.org/mozilla-central/source/dom/media/gmp/GMPParent.cpp#825
https://dxr.mozilla.org/mozilla-central/source/dom/media/platforms/agnostic/gmp/GMPDecoderModule.cpp#82

Double check this one:
https://dxr.mozilla.org/mozilla-central/source/dom/media/platforms/agnostic/eme/EMEDecoderModule.cpp#360

I don't think ChromiumCDMVideoDecoder and EMEVideoDecoder correspond to different GMP plugins, they are probably both Widevine, so there should be no hidden Chromium CDM GMP to disable. But that's more gut feeling than certitude.

[The bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1315850) related to this is large and includes the creation of `media.eme.chromium-api.enabled`. I didn't read much of it but from the little I could read, the Chromium API is more advanced and is privileged in Mozilla's code. When EME is enabled we want to use it, and when EME is disabled I don't see anything that lets me think it is going to be used. Finally, my guts don't believe a separate GMP thingy is tied to this Chromium API, it should be Widevine.

If a user enables EME temporarily through the Options menu and we have the Chromium GMP API disabled he will get the inferior one, which may have issues, so probably the pref shouldn't be set to false.

**Comment by earthlng** [comment]
Hi and thanks for your comment

if someone wants to (temporarily) enable EME they already need to change more than just that pref. (1820, 1825, 1830 and at least parts of 1840)
We disable the installation and/or update of these plugins, hide the "Play DRM Content" checkbox, etc.

@Thorin-Oakenpants we should probably move the last 3 prefs in 1840 to 1820

**Comment by Okamoi** [comment]
Hi :)

Sorry I dumped links as a first pass and later on forgot to format them and give context and greetings :)
Went a little too fast.

Indeed, if you even hide the checkbox there's no way a person is going to enable EME without going into about:config. Well at least I provided some background regarding this pref, which should be enabled any time EME is enabled. (i.e. Only on this time of the year when hell has frozen over, here, although I don't turn this chromium-api pref since I want to minimize unneeded tweaks to Firefox so it stays on battle-tested code paths as much as possible)

**Comment by earthlng** [comment]
yeah np mate, nice to meet you :)

TBH I didn't bother to dive into the code when we added that pref because I simply don't care about EME. It sounded like we may need it and it's just one more pref that fits nicely under 1830.

> Thanks for all the work regarding Firefox prefs :)

You're welcome. Thanks for participating.

**Comment by Thorin-Oakenpants** [comment]
Thanks @Okamoi , I'll address this later on, hence re-opened. Meanwhile go to https://github.com/ghacksuserjs/ghacks-user.js/invitations and there's an invite for you to become a collaborator, so we can type @O and select yur name to holler at you anywhere in the repo.

Good to have you around, the more people the better. There's so much code change in FF (and more to come - so much legacy code is going to start to get stripped) that we'd be uber happy for you to join us and help navigate all that

PS: Ask Atavic, he'll confirm: "being a collaborator, gets you the girls, man!"

**Comment by Thorin-Oakenpants** [comment]
Note: portable FF ships with both 32bit and 64bit versions

My portable FF54 (with my profile, addons etc) = 293mb
That same portable FF54 upgraded to 55 using the update feature (meaning it ONLY updated the 64bit app version) = 356mb

My point being that a lot of code must have been "replicated" - so a tonne must be going to get ripped starting with 57 - loads of shims and rubbish

**Comment by Thorin-Oakenpants** [comment]
> @Thorin-Oakenpants we should probably move the last 3 prefs in 1840 to 1820

Why? Are they only used for Widevine?

**Comment by earthlng** [comment]
> Why? Are they only used for Widevine?

No, but they aren't only used for OpenH264 either. They disable the installation (and/or update) of both, therefore fit better under `1820: disable all GMP` IMO

**Comment by Thorin-Oakenpants** [comment]
I'm inclined to agree that the whole 1820+1825+1830+1840 should be all inclusive, all disabled and users can use profiles and/or edit those sections out en masse. Rather than enable one and not others, and maybe provide a reason or link - its too complicated
