### ISSUE TITLE
Microsoft Teams: "Doh! Something went wrong..."

### ISSUE THREAD

**Issue by passboltUser** [ghacksuserjs/ghacks-user.js#202]
Which settings in `user.js` need to be changed from Microsoft Teams to work?

**Comment by crssi** [comment]
I would guess:
```javascript
/* 2404  */ user_pref("dom.indexedDB.enabled", true); // false breaks sites like OWA
```

**Comment by passboltUser** [comment]
I already set this to false for Outlook Web App to work (https://github.com/ghacksuserjs/ghacks-user.js/issues/180).

**Comment by crssi** [comment]
You mean to you have changed it to true? False will break OWA.

**Comment by passboltUser** [comment]
Yes, true :)

**Comment by crssi** [comment]
First try with disabled firefox extensions, to be sure some extension does not create a mess.
If there is still a problem, then make a backup of your profile folder and continue with step 7 here[https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting)

**Comment by Thorin-Oakenpants** [comment]
WTF is MS Teams? Is it some "chat" thing. Try WebRTC

**Comment by Thorin-Oakenpants** [comment]
Compromising your main browser for specific sites is no a solution (not that I know your setup/needs) - in this case, personally - I would just use MICROSOFT Teams in a secondary browser (probably IE/Edge)

**Comment by crssi** [comment]
MS Team is lite version of SPPS (Share Point Portal Server) used for team collaboration.
Until @passboltUser finds out which setting is the breakage reason, it is maybe premature to jump into a conclusion. Maybe there is no user.js "problem" at all and might be some extension(s) itself or extension miss configuration that causes it.

**Comment by passboltUser** [comment]
@crssi Of course I'm not using any extensions (I linked to https://github.com/ghacksuserjs/ghacks-user.js/issues/180 and there I said that too).

**Comment by passboltUser** [comment]
Found it. It is `user_pref("privacy.firstparty.isolate", true);`.

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info

Wow .. how does FPI break it? (don't answer) - must surely be some sort of cross domain logins/auth etc - a load of bugzillas on those. Did you try pref 2699b `privacy.firstparty.isolate.restrict_opener_access` - set it to `false` to loosen up some restrictions

indexedDB I think we are going to make inactive soon - leaning that way

**Comment by crssi** [comment]
I don't believe any cross domain login is involved. Normally here everything goes over SSO.

**Comment by Thorin-Oakenpants** [comment]
> What about IP leaks from WebRTC, still an issue?

I'm not sure. A couple of patches and prefs landed in the last year, but my gut feeling is it needs a through vetting - see https://bugzilla.mozilla.org/show_bug.cgi?id=1314443 for the Tor Uplift ticket

**Comment by Thorin-Oakenpants** [comment]
@crssi - I have no idea and can't test it. It depends how FPI decides origin attributes - hence the second pref due to so many issues. Look at all the tickets listed for logins in the sticky #8

**Comment by passboltUser** [comment]
@Thorin-Oakenpants Tried your suggestion and set `privacy.firstparty.isolate.restrict_opener_access` to `false`, and to `true` to test. Doesn't matter what I set, `privacy.firstparty.isolate` needs to be `false`.

I think `indexedDB` needs to be disabled (this rather big database keeps too much data).

Wouldn't be surprised if cross domain login is involved.

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info :+1:  FPI and cross domain has a long way to go.

The IndexedDB pref is _highly likely_ to be changed to inactive - it's just starting to "break" too many things including FF internals (although I only see one sqlite being updated, the extensions one), and although I have yet to test, I suspect WebExts which use it such as Stylus will not work. I haven't had any issues with websites personally that I know of - I do loads one off sites sometimes into a secondary browser. That said, there are clearly sites that need it.

Opening up indexedDB then raises the issue of how to deal with and control the persistent data, which is in another issue #173 touches on it and #188 despite the topic title is about coming up with cookie and storage strategies

**Comment by passboltUser** [comment]
I also have only sometimes sites that need indexedDB, but those are also not my main sites, but are found randomly. 
Yes indeed, one I think nice way, if indexedDB is enabled, to control its data, would be to somehow delete its contents when Firefox is closed. Similar to cookies (I modded your users.js to i.e. delete my cookies when I close Firefox).

**Comment by Thorin-Oakenpants** [comment]
@passboltUser See #226 which summarizes the whole thing. We flipped indexedDB to inactive (and users should enable it by resetting it) since too many WE's need it - such as uMatrix, uBo etc. That issue lays out your options to deal with persistent data. There are also some tickets in bugzilla that look to open up indexedDB by host etc - because the new WE APIs have opened up new opportunities that we didn't have before
