### ISSUE TITLE
How prevent the accessibility tools annoying trouble with e10s

### ISSUE THREAD

**Issue by WagnerGMD** [ghacksuserjs/ghacks-user.js#207]
`## To give one example : pref("accessibility.force_disabled",1);`
Hello,

after a few restart, I was disappointed because **e10s** was disable. Apparently, the cause are the **accessibility tools** (maybe aka a11y).
I had found a few articles on the matter :

1. [About Electrolysis and the Accessibility](https://wiki.mozilla.org/Electrolysis/Accessibility)  (via wiki.mozilla.org)
2. [Accessibility-and-ppt](https://support.mozilla.org/en-US/kb/accessibility-and-ppt) (via support.mozilla.org but there is nothing related to the page **about:config**)

```
pref("dom.ipc.processCount",1);
pref("dom.ipc.processCount.web",1);
```
But it isn't very clear and it doesn't seem to work fine.
Because as you can maybe guess, that's right it didn't restore the right value (at the first start, no the value wasn't 1).
I had check several times the page **about:support**. And no it doesn't match to the original value (for the both).

Do you know a solution to prevent this trouble ? How to restore e10s at full capacity ?

Kind regards.

**Comment by Thorin-Oakenpants** [comment]
Are you using any full themes such as FT Deep Dark?

**Comment by earthlng** [comment]
From your first link: 
> When electrolysis is blocked by accessibility the reason will be reported to the Browser Console at startup.

Is something reported in the Browser Console?

You can also force e10s:

> `browser.tabs.remote.force-enable` - Force electrolysis on regardless of accessibility use. 

OR force disable accessibility instead: 
> `accessibility.force_disabled` - Force disable accessibility use, useful if you run into stability issues running electrolysis. **Note: if you change this pref you also need to reset the two time-related ones below in order for e10s to reactivate.**

> `accessibility.lastLoadDate`
> `accessibility.loadedInLastSession`

Are these 2 set for you?

**Comment by WagnerGMD** [comment]
`pref("lightweightThemes.selectedThemeID",'firefox-compact-dark@mozilla.org');`
No @Thorin-Oakenpants I only have the **Compact Dark** (and maybe one day I will find (or replace it again by) a [Personas Theme](https://addons.mozilla.org/en-US/firefox/themes/)).

On the moment, I couldn't check because I wasn't aware... But right now, no there is nothing (in the Browser Console and I had discover these articles after I had notice the trouble).
```
pref("accessibility.force_disabled",1);
pref("accessibility.lastLoadDate",1502482004);
pref("accessibility.loadedInLastSession",true);
pref("dom.ipc.processCount",2);
pref("dom.ipc.processCount.web",4);
## What are the right value ?
## The reset of these settings was done (such as below)
pref("accessibility.force_disabled",0);
pref("accessibility.lastLoadDate",'');
pref("accessibility.loadedInLastSession",false);
```
In fact, it doesn't seem to be enough to just force e10s... It's seem to be block because I can't restore them (the both **processCount**).

**Comment by Thorin-Oakenpants** [comment]
@WagnerGMD I'm not sure what I can do. Since I have a couple of legacy non e10s add-ons, I am resigned to the fact that e10s will not happen for me until 57. I haven't even really cared about adding the info to the user.js, as come 57+ it will just happen - so I'm not clued up on it at all. I will assume you have no extensions holding you back.

I use portable FF. Have you tried a vanilla profile and got it to run multi-process?

* [x] :heavy_check_mark: no full themes
* [x] :heavy_check_mark: accessibility
* [x] :heavy_check_mark: process counts (Options>Performance)
   * [ ] NOTE that this requires using hardware acceleration. You should do this manually from the UI and restart, as it has related prefs
* [ ] Check about:config for
   * `browser.tabs.remote.autostart` = true
* [ ] Force enable if you have to - create boolean if needed, it is a hidden pref
   * `browser.tabs.remote.force-enable` = true
* [ ] Check `extensions.e10sBlockedByAddons` = false
* [ ] Maybe check you have e10srollout and webcompat etc system addons
* [ ] Use a 64bit version ?

Other than that, I have no idea.

**Comment by earthlng** [comment]
```
## What are the right value ?
## The reset of these settings was done (such as below)
pref("accessibility.force_disabled",0);
pref("accessibility.lastLoadDate",'');
pref("accessibility.loadedInLastSession",false);
```

You should reset the last 2 of these but still set .force_disabled to 1, and you have to restart FF:


https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js#950
> // This pref is checked only once, and the browser needs a restart to
> // pick up any changes.
> //
> // Values are -1 always on. 1 always off, 0 is auto as some platform perform
> // further checks.
> pref("accessibility.force_disabled", 0);

**Comment by Thorin-Oakenpants** [comment]
To be frank (besides changing my name), this is outside our scope (except the fact the multiprocess is a good thing and enables sandboxing, OOP etc). Come 57 everyone will be on it. Come EOL for ESR 52.x and I know I will be stripping the informational e10s section out.

I know this doesn't help Wagner, but it also doesn't help with us repeating the same instructions and getting no response (I'm impatient). There's information missing for  us to properly troubleshoot for starters. For all I know his hardware is not capable.

**Comment by WagnerGMD** [comment]
That's right, you are impatient...  No it won't help and the fact is I haven't design Firefox and that's definitely a good reason. Another good reason, the people need times to understand :
- that's wrong
- it's a long process to recreate the profil
- to check
- and to determine the cause.

It would be wise to avoid such behavior (a human bug) because no it isn't very respectful and I really dislike them. Bad choice of words and don't blame me because it won't (and never) be my fault. That's right, it isn't too much to ask (a little patience). Like would say Blaine : "I don't play a foolish game". Be smart because really I don't think that I need to remind you simple facts such as the people have a life and sometimes they are just absent (I'm not connected every day or another IRL reason). That's all because you can forget this part (I won't see the point to argue).

Then no you're totally wrong about the hardware... Because it's just can't be (Core i5 or i7 6xxx). Nevertheless, I had check it once again (each files exist) and yes I have the latest version (Firefox-v55.0.2-x64 under Windows10-v1607-x64). You're right about my addons because according to [Compatibility Reporter, ](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) they are all fine.
Also I had try to apply :
```
pref("browser.tabs.remote.autostart",true);
pref("browser.tabs.remote.force-enable",true);
pref("accessibility.force_disabled",1);
pref("extensions.e10sBlockedByAddons",false);
pref("extensions.e10sBlocksEnabling",false);
pref("extensions.e10sMultiBlockedByAddons",false);
pref("extensions.e10sMultiBlocksEnabling",false);
```
However when it's refuse to work, it's will be better to give another try another day.
To conclude, I can't be sure but it's seem the solution might be : `pref("accessibility.force_disabled",1);`
To prevent, it has to be modify at the first launch ? What else ? I don't remember but a few times I had remove it (clean or vanilla profile). 
Because like I said the multi-process was indeed enable but no it wasn't totally restore by Firefox.
