### ISSUE TITLE
mHeaderControl looks good

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#208]
A new extension has been released that looks very useful and powerful: mHeaderControl

From https://addons.mozilla.org/firefox/addon/mheadercontrol/

mHeaderControl is a Firefox Plugin which provides a bunch of features to manipulates HTTP headers of requests.

*Individual features can be turned on and off globally or on a per page basis.*

**Block Cookie SameSite**
Removes all cookie headers from requests to resources with the same domain as the site.

**Block Cookie 3rd-Party**
Removes all cookie headers from requests to resources with a different domain as the site.

**Allow CORS**
Adds the Access-Control-Allow-Origin: * header to all responses.
It is planned to have a proper logic for adding these headers and support all Access-Control-Allow-* headers.

**Remove Referer**
Removes the referer from all requests.

**Fake Referer**
Removes the referer from all requests and replaces it with a referer which is the same as the requested resource.

**Prevent Caching**
Adds Cache-Control, Pragma and Expires header to prevent caching.

**Comment by Thorin-Oakenpants** [comment]
I have [Headers Middleman](https://addons.mozilla.org/firefox/addon/chrome-headers-middleman/) | [Github](https://github.com/DingoEatingFuzz/chrome-headers-middleman) installed but zero idea on how to use it.

**Comment by Atavic** [comment]
Repository [here](https://github.com/maheee/mHeaderControl).

**Comment by Thorin-Oakenpants** [comment]
Closing this - item added to addons sticky which I am cleaning up
