### ISSUE TITLE
Change "https://127.0.0.1" to "http://127.0.0.1"

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#21]
```// 0201: disable location-aware browsing
user_pref("geo.wifi.uri", "https://127.0.0.1");
```

```// 0370: disable "Snippets" (Mozilla content shown on about:home screen)
user_pref("browser.aboutHomeSnippets.updateUrl", "https://127.0.0.1");
```
A secure connection involves a Trusted Authority: https://github.com/pyllyukko/user.js/issues/133

With a simple **http://** request, no Certificate Authority is called.

**Comment by earthlng** [comment]
the problem is that parts of the FF code expect a https url or the code fails prematurely.
it's 127.0.0.1 after all so it doesn't send anything out anyway.

**Comment by Roman-Nopantski** [comment]
http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/#comment-3811231

> the reason it's not blank is that unless you specify a secure connection (HTTPS), then it can open up MiTM attacks - there's some info somewhere buried in the TOR tickets

--
http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/#comment-3934084

> https://127.0.0.1 vs http://127.0.0.1 vs blank/null vs "data:text/plain," - I just do what TBB (Tor) does. Most of them, assuming no bugs in FF, are already controlled by another preference.

--
And as earthlng says, it's not going out of the network
