### ISSUE TITLE
When two tribes go to war... uMatrix & uBo updates [hosts+lists]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#210]
[♫ ♩ When two tribes go to war... ♬ ♪](https://en.wikipedia.org/wiki/Two_Tribes)

This has taken me a couple of hours to troubleshoot (but in the process I cleaned out about 60 dead prefs in my prefs.js, so yay for me!)

- Because automation is cool, and I'm a lazy bastard, I added [BarbBlock](https://ssl.bblck.me/install)'s list to uBo. It added it, but completely blank.
- Then I noticed I had lists (and hosts) not updated. When I tried manually (using the Update now button), an icon with a mouse-over tooltip displaying `A network error prevented the resource from being updated` would appear next to each subscribed list.
- Fired up FF54 from 7 days ago, it all updated fine. My profile hasn't changed. So I thought maybe it's 55 and something like FPI or one of the new prefs.
- So off to a nilla FF. Added uBo. Lists updated fine. Added my exact same user.js from my live 55, restarted, purged the lists, and they updated fine. Hmmm, not the user.js
- Did a compare of the 55-NILLA prefs.js (with my user.js applied) to my 55-LIVE version's (which also has the user.js applied, doh!) - nothing do with any manual pref changes or something silly I did
   * ignored all the extensions.* and timestamps etc
   * cleaned about 60 dead prefs not cleaned up by mozilla (***my profile is like 4 years old*** - stuff in there set by mozilla and never removed, I tell ya)
- I exported all my uBo bits and bobs and reset uBo. Updates still failed.
- Eventually I turned off uMatrix and voila - uBo was all good.

Had to add this uMatrix rule which scares the shit out me a little: `behind-the-scene * xhr allow`

Now I have done nothing to uBo's settings, and nothing to uMatrix. I am not sure if either of them updated recently. I have only been on 55 for 7 days. I did do some cleaning out of "My Rules" in uBo. Just the usual per domain tweaks in either extension. I do not know how or why this happened.

I have never had to have uMatrix allow XHR behind-the-scenes, and uBo always updated lists etc fine. I do not think I screwed anything up in uBo (because it updated when uM was disabled, and it failed when reset?), and I'm almost certain I didn't change anything in uMatrix, especially in a global context.

Not sure if I can test default uBo in NILLA (which I already have set up), and add uM to it, because I do not think uM default is hard-mode.

Ideas? PS: I took some piccies if you want me to post them

**Comment by Thorin-Oakenpants** [comment]
using
- uMatrix 1.0 which has been out since April
- uBlock Origin v1.13.8 which was released July 18, 2017

I must have done something? I'm baffled (I can rule out corruption I think)

**Comment by Forsaked** [comment]
On my config with uMatrix blocking everything except image & css by default and uBlock in hard mode i don't have the problem to update the 3rd-party filters:
![ublock](https://user-images.githubusercontent.com/14877660/29325754-207b4296-81e9-11e7-8609-5588077eea47.PNG)

**Comment by Thorin-Oakenpants** [comment]
OK, I think it is corruption. Someone else had a similar issue (in ghacks article comments). I think it has been caused by an improperly configured rule. I manually added the rules a few days ago. Someone else has had Vivaldi and Chrome and FF all do this. He just restored his 2 day old ublock0.sqlite

I will remove the uM rule, reset uM, replace the sqlite, and re-import all my shizzle .. and retest

Can I ask how you added BarbBlock. My doesn;t say BarbBlock, it says "https://ssl.bblck.me/blacklists/ublock-origin.txt"

**Comment by Forsaked** [comment]
By clicking this [link](abp:subscribe?location=https://ssl.bblck.me/blacklists/ublock-origin.txt&title=BarbBlock).

**Comment by Thorin-Oakenpants** [comment]
Yeah, I already worked it out. When you click on the link a confirmation dialog opens like this

```
Block₀: Add the following URL to your custom filter lists?

Title: "BarbBlock"
URL: https://ssl.bblck.me/blacklists/ublock-origin.txt
```

See the Title part? In uBo if you restore a backup, you lose the titles for custom lists - hence why mine said the file. Sucks to be me

**Comment by Forsaked** [comment]
Just unsubscribe and re-add them, if there aren't to much?

**Comment by Thorin-Oakenpants** [comment]
OK, am getting annoyed. Its not corruption of any sort. I did all this 
> I will remove the uM rule, reset uM, replace the sqlite, and re-import all my shizzle .. and retest

No dice. It poked without the uM rule. I will set up a nilla 55 (no user,js stuff) with nilla uM and uBo - damnit.

**Comment by Thorin-Oakenpants** [comment]
> Just unsubscribe and re-add them, if there aren't to much?

Not sure what you mean. I purged em all in early tests. I have added and removed Barb a few times. I have removed and imported and backed up and restored a dozen things a dozen times.

**Comment by Forsaked** [comment]
Just to regain the title, nothing more.

**Comment by Thorin-Oakenpants** [comment]
What uM rules do you have for behind the scenes and for xhr?

**Comment by Forsaked** [comment]
Take a look [here](https://github.com/gorhill/uBlock/issues/1496).

**Comment by earthlng** [comment]
You probably removed some of the default rules in uMatrix

**Comment by Forsaked** [comment]
The default rules on a uMatrix install would be:

> https-strict: behind-the-scene false
> matrix-off: about-scheme true
> matrix-off: behind-the-scene true
> matrix-off: chrome-extension-scheme true
> matrix-off: chrome-scheme true
> matrix-off: localhost true
> matrix-off: opera-scheme true
> referrer-spoof: behind-the-scene false
> ua-spoof: behind-the-scene false
> * * * block
> * * css allow
> * * frame block
> * * image allow
> * 1st-party * allow
> * 1st-party frame allow

**Comment by Thorin-Oakenpants** [comment]
`matrix-off: behind-the-scene true` <- this fucker - it was missing. I guess I removed it.

I loaded my old 54, exported matrix rules, did the same with current 55 and that fukker there stood out like a donkey's testicles

**Comment by Forsaked** [comment]
Yep take a look at the uMatrix Wiki [here](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests) and the Issues [here](https://github.com/gorhill/uBlock/issues/1496#issuecomment-199874996).

**Comment by Thorin-Oakenpants** [comment]
I can search anything in uMatrix issues - its all shutout due to the number of silly issues

**Comment by Thorin-Oakenpants** [comment]
PS: Mine is almost identical to yours @Forsaked  - I am only missing `* * xhr` block - how many sites do you need to ok that on? If its only a few sites for posting, then I'll follow suit - and I don't block media

**Comment by Forsaked** [comment]
Nearly everything with a login page needs XHR, so i have many sites on my whitelist for XHR.

**Comment by Thorin-Oakenpants** [comment]
I am now officially a "human bug" award winner :)
