### ISSUE TITLE
proposal: fixup hardware acceleration

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#212]
current: (to save you looking it up)
```js
/* 2508: disable hardware acceleration to reduce graphics fingerprinting
 * [SETTING] Options>Advanced>General>Use hardware acceleration when available
 * [NOTE] Changing this option changes BOTH these preferences
 * [WARNING] [SETUP] Affects text rendering (fonts will look different) and impacts video performance
 * [1] https://wiki.mozilla.org/Platform/GFX/HardwareAcceleration ***/
user_pref("gfx.direct2d.disabled", true); // [WINDOWS]
user_pref("layers.acceleration.disabled", true);
```

proposed: make inactive, fix [SETTING] (it is now under Options>General>Performance), and maybe add that HW acceleration is required for multi-process. In my world, the security/stability of multi-process which is still developing (core/content, OOP, grafx, etc) far outweigh potential gfx FP

**Comment by Forsaked** [comment]
I also have HW acceleration disabled and multi-process works fine on my end.
Where did you get the info that it is required for multi-process?

**Comment by Thorin-Oakenpants** [comment]
In Options>General>Performance "Content process limit" ~~are~~ looks like a subset of "Use hardware acceleration when available". Probably also compounded by the fact that "Content process limit" is disabled for me. I can see now that it is not (all this sparked by that other issue with someone's multi-process woes)

Wonder what `Use recommended performance settings` toggles.

If it isn't needed then well fine then :)

At least I can fix the [SETTINGS] info for this and process counts

**Comment by Thorin-Oakenpants** [comment]
Always a pleasure @Forsaked , thanks :kiss:
