### ISSUE TITLE
Rejected disagreement for Skip Redirect WE

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#213]
[Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/) addon is being rejected as not being WE which is very wrong.
Its really well done WE and I can't name any better for the job.
It is a way better replacement for for example [Google search link fix](https://addons.mozilla.org/firefox/addon/google-search-link-fix/), [Link Cleaner](https://addons.mozilla.org/firefox/addon/link-cleaner/) (redirection control part), [Request Control](https://addons.mozilla.org/firefox/addon/requestcontrol/)  (redirection control part). or any similar, since now it has the same domain detection with which there are almost none "false positives" and it does the job generally for any domain redirection skipping/stripping not only google/yandex or similar.
I the last month or longer I have had only one issue with ebay rover being redirected all over different domains, but this can be whitelisted with `.ebay.co`.
I am using Skip Redirect and Request Control (removing tracking properties out of URL) together. RC for better controlled replacement for Link Cleaner.

Cheers

**Comment by Thorin-Oakenpants** [comment]
No worries. I wasn't aware it had been ported

> Version 2.0.0 Released May 26, 2017 21.7 KiB Works with Firefox for Android 38.0a1 - 56.*, Firefox > 38.0a1 - 56.*
> Switch to embedded webextension
> Added whitelist mode

**Comment by Thorin-Oakenpants** [comment]
The sticky "pending" section is really just a list for follow up. It's not a bad list, but some items could be removed - the thing is there is going to be a flux of Web Exts coming, many ported from their chrome equivalents, and more from devs as they now feel its worthwhile re code maintenance etc. I think another six months and we should have a fairly good selection
