### ISSUE TITLE
Native Messaging

### ISSUE THREAD

**Issue by Theemim** [ghacksuserjs/ghacks-user.js#217]
Have any of you seen a pref or other **in-the-browser** mechanism that completely disables Native Messaging?  I mean a global deny that would apply even if there are installed Web Extensions (or System Addons, if they can use it) that have the permission and it is setup and working.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

**Comment by earthlng** [comment]
No. You could open a bugzilla report and hope they agree that it should be implemented.
Atm there's only this: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/NativeMessaging.jsm#49

**Comment by Theemim** [comment]
OK, thanks.
