### ISSUE TITLE
uBlock (webext) + uMatrix (webext) + AMO website = google crap leak

### ISSUE THREAD

**Issue by arno29** [ghacksuserjs/ghacks-user.js#228]
Testing the web extension from Raymond I discovered a leak. On legacy extensions (uBlock 1.13.8 and uMatrix 1.0.1b2) nothing like this.I do not even know how to tell him. He blocked access all except trusted persons.
 I'm tired of being a testing ground for its extensions. I will use legacy addon until he makes normal webext.

**Comment by Atavic** [comment]
Nice topic, with no references to uBo issues.
Does it happen with ghacks-user.js ?
Can you find the about:config entry that does the crap ?

**Comment by arno29** [comment]
Not interested? OK. Fine.

**Comment by earthlng** [comment]
ghost opened this Issue 15 hours ago
ghost closed this 15 hours ago
> Not interested? OK. Fine.
+ deleted the account again. LOL

It's not gorhill's fault that mozilla added limitations to the webrequest API, and yes it fucking sucks that they did that while at the same time still keep google-tracking shit on those "protected" pages.
It's one of the reasons why I switched to ESR. I don't like it any more than you do, "ghost", whoever you were. Only thing you can do about it if you want to keep using FF Release channel + WEs-only, is to enable Tracking Protection which should hopefully block that GA-shit on all "protected" mozilla domains.

**Comment by Thorin-Oakenpants** [comment]
I believe the only protected content that uses GA so far is about:addons>get addons which we killed the url for anyway. That and stay away from onboarding, activity tab etc. I don't see anything else really using any GA.

However, it still sucks. I have FVD Speed Dial (with 350+ dials etc) and that sucker wants to access google for favicons, which I currently block using uMatrix

```
speeddial.chrome-scheme google.com * block
speeddial.chrome-scheme googleusercontent.com * block
speeddial.chrome-scheme s2.googleusercontent.com * block
speeddial.chrome-scheme www.google.com * block
```

This is my landing page: chrome://fvd.speeddial/content/fvd_about_blank.html
^^ I hope that isn't a protected page

**Comment by earthlng** [comment]
Pretty sure those rules don't do anything anymore with uMatrix WE-only.
OP was talking about AMO and afaik that's one of the domains that they "hide" from the webrequest API.
Meaning no Webextension will be able to block requests on AMO and other "protected" domains. chrome-scheme is also a protected scheme afaik.

**Comment by Thorin-Oakenpants** [comment]
> chrome-scheme is also a protected scheme afaik.

I'll find out when I update uM to WE
