### ISSUE TITLE
uBo WE & ghacks user.js

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#229]
https://www.reddit.com/r/uBlockOrigin/comments/6xdgg2/firefox_aboutconfig_settings_that_affect_ublock/

We already knew about indexedDB, but workers? Really?

> - dom.workers.enabled is required for looking up the origin of filters in the logger (and even with it enabled, I notice the pointer doesn't turn into a magnifying glass when hovering over a filter)

**Comment by earthlng** [comment]
https://github.com/gorhill/uBlock/commit/  060a43fe818ed55565300db4fa1cfc789c54726a#diff-1a21bc24eaf200fc978ec9e3a90b651cR65

= added more than 2 years ago. I've never had a problem with workers disabled, the logger works fine without it ie I see the magnifying glass and can click on a blocked line to show the list(s) it's coming from.

**Comment by Thorin-Oakenpants** [comment]
I'm not on Web Ext yet (will wait until 56 and I need to ditch more legacy addons - read about GM being the cause of weird uBo issues). I'll leave this open until I can test uBo WE still works fine with workers=false

PS: Why are your links lately getting spaces in them and all FUBARed

**Comment by earthlng** [comment]
Because I don't want to create those github references everywhere

**Comment by Thorin-Oakenpants** [comment]
ahh .. capisci gucci

**Comment by Thorin-Oakenpants** [comment]
Nilla FF portable, nilla profile. Added uBo WE latest. Tested on loading amazon.com

![anyonewannabuildasnowman](https://user-images.githubusercontent.com/16656956/30043351-f5b77f4e-924a-11e7-992d-9a226a6ca2de.png)

Mouse pointer turns into a magnifying glass in the column designated by the grey square (alt-print didn't capture it), the column with "--" the mouse pointer turns into a hand

Quit, added user.js, restarted - exact same result. `dom.workers.enabled` does not affect uBo WE (at least in FF55)

**Comment by earthlng** [comment]
Maybe the pref doesn't disable workers for extensions

**Comment by Atavic** [comment]
[Forrester Log Service](http://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-port-requirements.html) 'round half the page.

That thing was added to AdguardFilters [exclusions](https://github.com/AdguardTeam/AdguardFilters/issues/3898).

**Comment by Thorin-Oakenpants** [comment]
> Maybe the pref doesn't disable workers for extensions

Wouldn't it be nice if some prefs did not affect WE - eg if indexedDB pref didn't affect WE or FF itself using it... Or if local storage was for WE wasn't affected by cookie settings and (i have not tested this one) if `dom.storage.enabled` did not affect WE etc

Separation of "content" vs "application/extension"

Needs more cowbell... we don't want rogue WEs, but WE by their very nature have a permissions model and are far more restricted - so it's nothing new - AMO vetting/reviews etc.
