### ISSUE TITLE
UA spoofing: general.*.override & navigator objects

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#23]
[TCP/IP OS Fingerprinting](https://browserleaks.com/ip) returns my actual Windows NT kernel version even though I use

user_pref("general.oscpu.override", "Windows NT 6.1");

Is there something that can be done?

**Comment by Roman-Nopantski** [comment]
Welcome @Just-me-ghacks  - good to see you migrate here :)

I did do some quick tests myself (and the section has some notes), but I am Windows 6.1 :).  I used http://browserspy.dk/ for various UA values and for os it showed I was 32bit not 64bit 0 which meant that bit (excuse the pun) worked. What were you supposed to have returned @Just-me-ghacks ?

I think we should revisit 2627 sometime in the future: I whipped it up so help get rid of all those suggestions. I did commented that A (useragent) and E (platform) leak thru navigator. I'm not surprised  if oscpu does as well.

I'm actually thinking of making all of 2627 inactive (except maybe `general.buildID.override`).
- There are too many holes in UA and other methods such as quite a few ways to get locale that can make your UA stand out as a lie
- there is feature detection that can defeat this
- The Tor Uplift has a ticket to enforce all this with `privacy.resistFingerprinting` (which will at least make a large subset of users consistent with each other), and hopefully they will patch these navigator leaks.
- even just using `general.buildID.override` (at TBB values) makes your entropy sky high

I'm not saying it doesn't need addressing, but I think the Tor Uplift approach is best, and until it lands, I am inclined now to just do away with UA Spoofing. I also don't believe the numbers for those online test results, as the data is quickly out of date, and is skewed by people like us playing around on it. A more realistic result would be the default, IMO.

**Comment by crssi** [comment]
OS, bitness and browser is almost impossible to spoof.
You can safelly spoof browser version, but not faking FF as for example Chrome, IE, or something else.
Even when the results on some test pages show that you have done it succesfully, there is a methoh over iFrame, which allways reveals the real data. ;)
The same goes with screen resolution spoofing. There is no real solution for now.

I would really suggest to remove those from your user.js.
Otherwise you are fingerprinted as a spoofer. ;)

Maybe I am wrong here, so don't kill me for my comment. ;)

**Comment by Roman-Nopantski** [comment]
@crssi I held off adding UA stuff for 18 months. When basically this current version was publlished at ghacks 2 weeks ago, I had finally added it for completeness, along with warnings in the description that getting it right is hard, and that its not a complete solution etc - eg navigator objects, that iframe issue, resource://URIs, feature detection, and other leaks such as locale. So here we are 2 weeks later and I think it should all be de-activated. I think UA spoofing is useless, except when it is used to make a small subset indentical (such as TBB, or Firefox users with resistFingerprinting), but before I do that, I will wait for comments.

**Comment by crssi** [comment]
Great. You guys did a tremendous job in very short time.
All I can say is in two words: THANK YOU

:)
Cheers

**Comment by Just-me-ghacks** [comment]
Hi, Pants! So user.js updates are now basically real time, I like that :)

IMHO the current 2627 prefs work surprisingly well to spoof OS and FF version. They produce plausible results when you don't make big changes. I wouldn't remove them, the included comments are sufficient. The **TCP/IP OS Fingerprinting** method used by BrowserLeaks to reveal the actual Windows NT kernel version might have nothing to do with Firefox?

I know spoofing your browser (instead of just the browser version) and resolution won't really work.

**Comment by Roman-Nopantski** [comment]
@Just-me-ghacks . Yes, create yourself a fork, modify it to your liking. Then whenever you need to, do a compare and merge thru any changes you want, and keep modifying to your heart's content. I also do a FF stable release. So for example, go to the [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases) and you will version 51, next to which it says "27 commits to master since release" - click that and you will see all the changes.

As for the UA spoofing: the point is to lower entropy (or in the case of RAS to raise it, but change it frequently, and that is a different approach/discussion). Lets take 500 million FF users, whittle that down to 50m on version 51, and down to 10 million on 51.01 64 bit windows build (`navigator.buildID` is a real problem). Now how many people will spoof the same, and how many will mistakenly play with it and try to be clever? My guess is absolutely small numbers, minuscule numbers, will spoof - and of those numbers, how many will be the same as you? Most! And even those the values used in this js are the same as TBB, the TBB has a captive audience and can enforce these settings - for TBB users, this *IS* their default. I would rather be one of 10 million, than one of 50 or 100, or even unique.

When `privacy.resistFingerprinting` enforces a common set of values for UA spoofing (and hopefully maybe patches the navigator leaks, and that iframe one), then the subset of FF users who enable the pref become a subset like TBB where their default is forced on them. This is the best way forward in my opinion.

**Comment by Atavic** [comment]
Tools like Nmap and P0f look at the TCP/IP stack parameters of the system.

**Comment by Roman-Nopantski** [comment]
Bit OT there Atavic :) The TCP/IP part is just part of a raft of tests on that site and page. The title of this issue is not very informative, it's really about [navigator.oscup](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/oscpu)

**Comment by Atavic** [comment]
@Just-me-ghacks 
>Is there something that can be done?
You can chenge reg values.

**Comment by earthlng** [comment]
With all the things we already do (dom.*, disabled ciphers, etc.) worrying about spoofing your OS is really not worth the effort IMHO. with 1600 downloads we are in a pretty small group anyway.
From all the 2627 stuff I only use `general.buildID.override` but now that I think about, I don't even need that. Those things are maybe useful if you compile your own FF on linux but my buildID on Windows is the same for everyone who has the same FF version. And I don't spoof my UA anymore either, so yeah, not needing this any longer.

**Comment by Roman-Nopantski** [comment]
I'm just leaving it open to remind me to disable the whole 2627 and reword the intro to it. There is no solution to UA spoofing. I've already said what the best road forward is.

There may be a fix for closing the navigator.oscup and other naviagtor.* leaks, just like User-Agent JS Fixer does for  navigator.userAgent, but if we turn UA spoofing off, we don't care anymore and can dump it. Yes, here is a bug here. What can we do about it, nothing - we're not add-on developers. Bug acknowledged, close issue.

**Comment by Atavic** [comment]
User Agent spoofing without JS works fine.

**Comment by earthlng** [comment]
`User Agent spoofing without JS works fine.` that depends on what you spoof as.
If it's anything but Firefox then the available ciphers and their order already make you pretty unique.
CSS can also be used to some degree to identify if you're using FF, Chrome or whatnot.
And honestly, if you spoof another FF version what good does that really do?

**Comment by Atavic** [comment]
I spoof the latest FF on previous versions.

**Comment by crssi** [comment]
Spoof to FF version that has biggest market share.
That would normally be the latest standard. If you are using ESR or nightly, then spoofing makes sense if we assume that fingerprinting isn't beyond that.
[https://techblog.willshouse.com/2012/01/03/most-common-user-agents/](url)

**Comment by Atavic** [comment]
Googlebot 2.1 User Agent String:
`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`

**Comment by Roman-Nopantski** [comment]
Proposed patch to turn off all UA spoofing, make it a separate section

```
/*** 2697: USER AGENT (UA) SPOOFING
     Spoofing your UA to *LOWER* entropy *does* *not* *work*. It may even cause site breakage
     depending on your values. Even if you spoof, like TBB (Tor Browser Bundle) does, as the 
     lastest ESR, it still *does* *not* *work*. There are two main reasons for this.
       1. Many of the components that make up your UA can be derived by other means. And when
          those values differ, you provide more bits and raise entropy. Examples of leaks include
          navigator objects, resource://URIs, <isindex> locale, feature detetction and more.
       2. You are not in a controlled set of signifcant numbers, where the values are enforced
          by default. It works for TBB because for TBB, the spoofed values ARE their default.
     * WE DO NOT RECOMMEND UA SPOOFING
     * Values below are for example only based on the current ESR/TBB at the time of writing
***/
// 2697-A: general UA string (navigator.userAgent leaks in JS)
   // NOTE: setting this will break any UA spoofing add-on whitelisting
   // user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"); // (hidden pref)
// 2697-B: navigator.buildID (see gecko.buildID in about:config) reveals build time
   // down to the second which defeats user agent spoofing and can compromise OS etc
   // https://bugzilla.mozilla.org/show_bug.cgi?id=583181
   // user_pref("general.buildID.override", "20100101"); // (hidden pref)
// 2697-C: navigator.appName
   //user_pref("general.appname.override", "Netscape"); // (hidden pref)
// 2697-D: navigator.appVersion
   // user_pref("general.appversion.override", "5.0 (Windows)"); // (hidden pref)
// 2697-E: navigator.platform (leaks in JS)
   // user_pref("general.platform.override", "Win32"); // (hidden pref)
// 2697-F: navigator.oscpu (leaks in JS)
   // user_pref("general.oscpu.override", "Windows NT 6.1"); // (hidden pref)
```

**Comment by Atavic** [comment]
Good choice. That's unclear territory, must be investigated.

**Comment by earthlng** [comment]
sure, why not.
I prefer if the user_pref line isn't indented, but hey, you're in charge of formatting ;)

**Comment by Roman-Nopantski** [comment]
> I prefer if the user_pref line isn't indented

But every single commented out user_pref(* is indented, in the entire js. Or am I missing something?

Commit: https://github.com/ghacksuserjs/ghacks-user.js/commit/32c4e5a1dc97ee02e625ead6dbe7a405fc3c16a9  

I am closing the topic. Mozilla/Tor Uplift know about these various leaks.

**Comment by earthlng** [comment]
> is indented, in the entire js

Yes, but my idea is to use multi-line JS comments, like so ...

```
/* 2697-A: navigator.userAgent leaks in JS
   // NOTE: setting this will break any UA spoofing add-on whitelisting ***/
//user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"); // (hidden pref)
/* 2697-B: navigator.buildID (see gecko.buildID in about:config) reveals build time
   // down to the second which defeats user agent spoofing and can compromise OS etc
   // https://bugzilla.mozilla.org/show_bug.cgi?id=583181 ***/
//user_pref("general.buildID.override", "20100101"); // (hidden pref)
```

or like this:

```
/* 2697-A: navigator.userAgent leaks in JS
 * NOTE: setting this will break any UA spoofing add-on whitelisting ***/
//user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0"); // (hidden pref)
/* 2697-B: navigator.buildID (see gecko.buildID in about:config) reveals build time
 * down to the second which defeats user agent spoofing and can compromise OS etc
 * https://bugzilla.mozilla.org/show_bug.cgi?id=583181 ***/
//user_pref("general.buildID.override", "20100101"); // (hidden pref)
```

**Comment by Roman-Nopantski** [comment]
I still think the commented out pref should be indented i.e every // item in column 0 means a new number. Not a fan of having to deal with a trailing ***/, that just seems like more work. although example 2 looks quite nice IF the commneted out user pref was still indented. But I am not going to edit the entire js to change for some slight visual tweak.

**Comment by earthlng** [comment]
Well, if it was example 2, it makes sense to have all the //user_pref lines on column 0 when you collapse all items with your editors shortcut. I also prefer if the actual commented out JS code ie the user_prefs lines, don't have a single space between // and the 'user_pref'. But it's just MY programming style.
If we ever gonna make the change we should do it sooner rather than later, before more people start a fork.
Should we be democratic about it and create a poll with all possible formats and let the majority decide?
IMO it's more than just a 'slight' improvement, especially if you edit a local copy in an editor.
It makes such a big difference in terms of better overview, easier to organize, etc.
We don't necessarily have to change the entire file at once IMO.

**Comment by Roman-Nopantski** [comment]
Not going to run a poll with 5 or 6 people. I will make the change, and I will do it in one hit. Not here to piss around. I will not change the inactive prefs from being indented, as that is visually important for people not using an IDE that creates start/end bits and bobs.

Speak now or forever hold you peace. Choose A or B
A
```
/* 2303: disable push notifications (FF44+) [requires serviceWorkers to be enabled]
   * web apps can receive messages pushed to them from a server, whether or
   * blah blah */
user_pref("dom.push.enabled", false);
```
B
```
/* 2303: disable push notifications (FF44+) [requires serviceWorkers to be enabled]
   web apps can receive messages pushed to them from a server, whether or
   blah blah */
user_pref("dom.push.enabled", false);
```

**Comment by Roman-Nopantski** [comment]
Not every numbered item exceeds 1 line, so those do not stand out (see 2303) , another reason I want // in column 0 to mean a new item (or something tacked on to that number).
![untitled-1](https://cloud.githubusercontent.com/assets/16656956/23306089/a397b1a6-fb06-11e6-9d64-32b97de8ea2e.png)

PS: I'm just using Notepad++ for this. I do like it, being able to fold/unfold the entire doc

**Comment by Roman-Nopantski** [comment]
Here's what I mean about indenting
![untitled-1](https://cloud.githubusercontent.com/assets/16656956/23306304/d6ba063c-fb07-11e6-9174-914c4f38289f.png)

**Comment by earthlng** [comment]
```
/*** 2700: COOKIES & DOM STORAGE ***/
/* 2701: single line pref ***/
user_pref("blabla", true);
/* 2702: multi-line active
 * blabla
 * more blabla ***/
user_pref("blablub", true);
/* 2703: single or multi-line inactice ***/
//user_pref("blibli", true);
```
note: 

1. always use `***/` to end-comment, makes it easier to see
2. also use `/* ... ***/` for single line numbers, so only inactive user_pref lines would have //
2a. hence having the //user_pref's on column 0 would be nice

take it or don't, I've said my peace, please don't hate me for not picking A or B ;)

ps. ok your last pic also looks nice. I don't mind, do what you prefer

**Comment by Roman-Nopantski** [comment]
1 & 3, yup . 2 makes no sense. every one starts with /* and ends with ***/, regardless of number of lines. I fail to see what pointing //(nospace)user_pref in column one does visually. Don't answer. Choice made and will do so soon (maybe tomorrow as I listen to 7 hours of cricket, not that it will take me 7 hrs).
