### ISSUE TITLE
mozAddonManager [check] and extensions.getAddons.showPane [add]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#232]
```js
/* xxxx: disable access to mozAddonManager web API for "developer" sites listed in [3]
 * [1] https://addons-frontend.readthedocs.io/en/stable/moz-addon-manager/
 * [2] https://bugzilla.mozilla.org/show_bug.cgi?id=1255039 [META]
 * [3] https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp  ***/
user_pref("extensions.webapi.testing", false); // (hidden pref)
```

I am having trouble working out the default value of this hidden pref. I still think it's a good idea to ***enforce disabled*** (what number/section?). [Here](https://gitweb.torproject.org/user/gk/tor-browser.git/commit/?h=bug_21684&id=b2f8585b66dc2856463950c7239015585a8481e3) is what Tor did - they stripped out all whitelisted domains. The best we can do is disable the second set called "developer"

**Comment by earthlng** [comment]
On DXR for nightly it's currently used in [3 places](https://dxr.mozilla.org/mozilla-central/search?q=extensions.webapi.testing) (the rest are tests) :
* https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser-addons.js#621
  * pref needs to exist as true to do anything - ie not necessary to enforce false
* https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManager.jsm#2971
  * assigned as PREF_WEBAPI_TESTING on line 47
  * same as above, it needs to exist and be set to true for the code to continue ie no need to enforce
* https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp#46
  * it checks the pref but defaults to false if the pref isn't set. = no need to enforce

> The best we can do is disable the second set called "developer"

theoretically you can hit the `return false` on line 34 in AddonManagerWebAPI.cpp by **locking** `xpinstall.enabled` to false.

**Comment by Thorin-Oakenpants** [comment]
Thanks. So nothing to do then. Sweeeet.

FYI: They are probably going to use this for the new AMO to detect browser version and thus bypass all the UA spoofing

**Comment by Thorin-Oakenpants** [comment]
FYI: [HA](https://bugzilla.mozilla.org/show_bug.cgi?id=1394578) .. and the example is ... wait for it ... `xpinstall.enabled`

**Comment by Thorin-Oakenpants** [comment]
Wait a minute ... we don't even have `xpinstall.enabled` in the user.js - should we?

https://bugzilla.mozilla.org/show_bug.cgi?id=1359837

**Comment by earthlng** [comment]
OT:
```js
/* 0320: disable extension discovery
 * featured extensions for displaying in Get Add-ons panel ***/
user_pref("extensions.webservice.discoverURL", "http://127.0.0.1");
```

setting the hidden pref `extensions.getAddons.showPane` to false disables/hides the Get Add-ons panel completely and makes 0320 redundant. (but we can still keep it)
I never liked that you set the discoverURL this way because it creates an unnecessary request and there could be something running on 127.0.0.1. empty string would be better and is what I use too.

I suggest we change 0320 to this:
```js
/* 0320: disable about:addons' Get Add-ons panel ***/
user_pref("extensions.getAddons.showPane", false); // hidden pref
user_pref("extensions.webservice.discoverURL", "");
```
Maybe add some info that it was (or still is?) GA-infected [and that WebExtensions can't block that anymore (TP can and does block it though)]

**Comment by Thorin-Oakenpants** [comment]
^^ how the f did i miss that post. I only saw it cuz I came in to post this

https://reviewboard.mozilla.org/r/179706/diff/1#index_header

hidden pref `privacy.resistFingerprinting.block_mozAddonManager` will kill this, but I do not think we need to worry. This is going to be used for AMO (I think, not 100% decided) so AMO detects the correct FF version

As for that change - hellyeah, works for me - do a commit

**Comment by Thorin-Oakenpants** [comment]
my get addons used to be completely blank, now I get a wee bit of text

"what are addons (title) .. addons are blah blah" - I'm not sure where that is coming from. It took like half a second to load and I saw a loading message. It should be local?

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/6900924aa6ef24fb401db18b745457e0fd33128b
