### ISSUE TITLE
GitHub upload feature broken [solved: extension settings]

### ISSUE THREAD

**Issue by ArchangeGabriel** [ghacksuserjs/ghacks-user.js#233]
Trying to “attach files by dragging & dropping, selecting them or pasting from the clipboard” to an issue doesn’t work. I’m not sure which settings cause this though.

**Comment by Thorin-Oakenpants** [comment]
I know. I just flick open opera, login and make my post there when I want to attach a file. I also had major issues with dropbox (which I no longer use), and it was all sorts of things (context menus, uploading, seeing folder contents - you name it - gave on it) - other than that, I'm peachy.

Never bothered to track the cause of this upload on github business. I also get an error viewing some image files in diffs/commits etc.

I'll see if I can work it out

**Comment by earthlng** [comment]
![25846669](https://user-images.githubusercontent.com/25846669/30333845-39aee0a0-97de-11e7-9f99-41371af32dc4.jpg)

works fine for me. You need to allow github-something-something.s3.amazonaws.com in NoScript and the XHR to that domain in uMatrix and/or uBO

**Comment by Thorin-Oakenpants** [comment]
I do not see any github-something-something.s3.amazonaws.com in NoScript

**Comment by crssi** [comment]
^^Nice chimp.
Where do you pull all those stuff. You should be a stand up comedian, :)

**Comment by Thorin-Oakenpants** [comment]
That's the famous [selfie monkey](https://www.techdirt.com/blog/?tag=monkey+selfie) .. have a read, hilarity ensues

Wiki: https://en.wikipedia.org/wiki/Monkey_selfie_copyright_dispute

**Comment by ArchangeGabriel** [comment]
Well I have no uMatrix, no uBO, no NoScript cause I don’t like the UI of the first twos and I’m living on Nightly (so no non-webextension addons). And it still doesn’t work.

**Comment by Thorin-Oakenpants** [comment]
So in a new profile on Nightly, with no tweaks, it works? And then if you add the v55 user.js, it breaks? Is that what you're saying?

**Comment by Thorin-Oakenpants** [comment]
This is me on a default brand new 56.0b10 (which want to auto update when I checked the about Firefox)

![selfie](https://user-images.githubusercontent.com/16656956/30423633-92aa5116-9997-11e7-95c9-1d2a8ef63fda.jpg)

Success

**Comment by Thorin-Oakenpants** [comment]
This is me on that same default nilla profile but now on 56.0b11 - BUT with the default user.js (no changes)

![selfie](https://user-images.githubusercontent.com/16656956/30423903-6a421cb2-9998-11e7-9285-73db6c0bf1e5.jpg)

Success

I do not have a 57 to test on

**Comment by earthlng** [comment]
> and I’m living on Nightly

well, our user.js is maintained and tested only for Release, not Nightly. Nightly users should expect some breakage, with or without this user.js. Thorin's tests prove that the user.js in its current form is not the problem, at least not until up to and including 56 beta11. Maybe you didn't reset some of the things we made inactive over the last couple releases? Or you made your own changes to the user.js that cause this. Nightly users should be able to figure things like this out for themselves.

https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

**Comment by Thorin-Oakenpants** [comment]
To be fair, I did not test pasting - but file select and drag'n'drop work

**Comment by Thorin-Oakenpants** [comment]
pasting doesn't work :) not copying an image, or an image file.

**Comment by ArchangeGabriel** [comment]
This is really strange. I’ve installed uMatrix and whitelisted the XHR (from github-production-user-asset-6210df.s3.amazonaws.com), and it worked. I don’t understand why it wasn’t working without uMatrix, but anyway now I’m on uMatrix, so… :p

**Comment by Thorin-Oakenpants** [comment]
^^ so where's your monkey picture? Pics or it didn't happen .. as they say

**Comment by ArchangeGabriel** [comment]
![30423903-6a421cb2-9998-11e7-9285-73db6c0bf1e5](https://user-images.githubusercontent.com/490531/32753846-c3cdabf6-c8ce-11e7-8052-e346cf0a66ec.jpg)

Even by Ctrl+V’ing it. :p

![image](https://user-images.githubusercontent.com/490531/32753835-b696c3be-c8ce-11e7-91eb-e2f2d6f591f4.png)
