### ISSUE TITLE
reminder: investigate IDB

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#234]
SOLVED: some sites use service workers to spawn their IDB entries

--
I use the user,js as is - I always do. The exception being since 55 landed I allowed IDB (indexedDB) and also turned off OCSP [edit: OCSP hard fails) (`security.OCSP.require`) which has nothing to do with this investigation

So 4 weeks in, and I still haven't had a single entry created in my IDB folders `default` or `temporary` and I've even gone to youtube (because of earthlng!) and I still got nothing. YT is one of the examples given which creates a FPI indexedDB entry. Note: 2 sqlite files in `permanent` get an occasional change.

I have just tested allowing cookies and nothing happened. I want to follow up on this. I do not clean the folders with any external app, I have no denied permissions to the folders.

I also tested with site permissions for Maintain Offline Storage - no dice.

I wonder if it has anything to do with 2664: `device.storage.enabled`. Whatever it is, it's either an issue or a miracle cure for dealing with IDB (for now).

Do any of you guys get cr*p in your IDB folders?

Edit: It could also be extension settings of course. I will, when I get time, do some testing in a nilla Firefox with no extensions

**Comment by grauenwolfe** [comment]
**default:**
1. https+++www.youtube.com^firstPartyDomain=youtube.com
2. moz-extension+++79bb2d6e-0838-8a47-a753-a558bca97419 > **idb**
  _fairly sure this is uBo's filter lists..._ 

**permanent:**
* chrome > **idb**
* moz-safe-about+home^firstPartyDomain=about.ef2a7dd5-93bc-417f-a698-142c3116864f.mozilla > **idb**

**temporary:**
1. never has anything in it

Additionally, about:cache always shows 0 entries, even after YouTube, etc. The only cache entries I occasionally get are from certain Mozilla pages and uBo's filter lists.

**Comment by Thorin-Oakenpants** [comment]
> So what is the final verdict with extensions, specifically uBo and having to enable IDB, dom storage

IDB should be on for uBo, uM Web Extensions including the hybrids. And it will have to be on for other extensions. We just have to suck it up. I just created a new issue #235 which kind of covers this long term - where a decent section header can answer these questions, etc.

As for local dom, I'm not entirely sure. First it is controlled by cookies, so for Extensions to use local dom, they need a cookie exception - everyone will be different I assume due to the UUID? I have yet to add a WE that uses this, so I cannot confirm or deny if `dom.storage.enabled` is required - but we don't block that anyway. The problem is cookies IMO, as they control local dom.

PS: not sure on that string .. I'll edit that out

**Comment by Thorin-Oakenpants** [comment]
FYI: I am still on legacy uBo (will wait for 56), hence no uBo cached assets in IDB. Youtube though, I get nothing but you do. So definitely something different. Maybe we can pastebin our user.js for a compare?

**Comment by earthlng** [comment]
> turned off OCSP (security.OCSP.require)

FYI: that pref doesn't "turn off" OCSP, it only disables hard-fail.

re: youtube - you maybe don't get the IDB stuff because of some of your uBlock filters and/or rules. I think you once said you're using the full "Youtube: Pure Video Experience" - I use only parts of it and I've also seen the IDB files/folders when I open YT in a non-private window.

@grauenwolfe about:cache is currently broken due to first-party-isolation afaik

**Comment by Thorin-Oakenpants** [comment]
> FYI: that pref doesn't "turn off" OCSP, it only disables hard-fail.

Trying to keep it simple :) Yeah, I already noted extensions - since I am deny-all then whitelist in NS, uBo (cept 1st party) and uM (cept css + images). When i get some time I will test in a nilla

**Comment by Atavic** [comment]
I have crap there.

**Comment by Thorin-Oakenpants** [comment]
> @grauenwolfe about:cache is currently broken due to first-party-isolation afaik

https://bugzilla.mozilla.org/show_bug.cgi?id=1371651

**Comment by grauenwolfe** [comment]
If I'm understanding the bug report correctly, it looks like FPI = true is hiding cache entries even though they are still actually being collected? And here I am thinking that at last I had completely disabled any caching...

I've noticed that changing `browser.cache.use_new_backend_temp` = false instantly causes cache entries to become visible _(after refreshing about:cache)_ even with FPI = true. I don't know what this means ultimately other than Mozilla's caching implementation is one of the most convoluted systems I've dealt with.

If anyone likes to check:
1. set `browser.cache.use_new_backend_temp` = false
1. load a few websites
1. refresh about:cache and viola - cache entries are there
1. set `browser.cache.use_new_backend_temp` = true
1. refresh about:cache and now they've all disappeared

What do you guys see when you load about:cache? Here's mine with these settings:
  * `privacy.firstparty.isolate` = true
  * `browser.cache.use_new_backend_temp` = false 

![screen](https://user-images.githubusercontent.com/25858089/30410950-c71523dc-98d3-11e7-8612-9d8945093af7.png)
-----
And now with these settings:
  * `privacy.firstparty.isolate` = true
  * `browser.cache.use_new_backend_temp` = true

![screen2](https://user-images.githubusercontent.com/25858089/30411189-1b1f1824-98d5-11e7-99e4-ee019c9c1d44.png)
-----
And finally, shouldn't the **disk** section's entries be all "0"? Yes, it clearly states "Storage disk location: none, only stored in memory" but I'd be more comfortable if it showed all "0" just like the **appcache** section does. I don't get it. I have every cache option disabled except in memory only.

**Comment by Thorin-Oakenpants** [comment]
I have that issue open about cache not clearing(?) and that ETAG test site - and when I get to it I was going to test combos of things such as FPI causing issues, and to muddy things up there are numerous cache entries now including new ones in 56. Note FPI applies to "media cache", so I am not sure if that means images (which that ETAG site uses). The point of that issue is that clearing cache should clear the cache.

Without wanting to get OT, I think RFP should block outgoing ETAGs in headers. I fully plan on testing the sh*t out of this - PB mode seems to clear properly from memory, but not normal windows (either from ctrl-shift-del or on close), and yet ccleaner (which doesn't even remove anything except in my setup it removes the formhistory sqlite and sessionstore backup files - all of which are recreated on FF start and not used anyway) fixes it. So I'm flummoxed for now on this cache + ETAG business. I wish I could get HTTP header modify whatever to do as it says

**Comment by crssi** [comment]
I have no time, at the moment, to do some tests. :(

But what about
``` js
user_pref("privacy.firstparty.isolate.restrict_opener_access", true);
```
Does this preference block the cache cleaning?

Otherwise out of ghacksuser.js default I have additionally
``` js
user_pref("browser.cache.memory.enable", false);
user_pref("privacy.firstparty.isolate", false);
```
The `privacy.firstparty.isolate = false` is for a reason that, otherwise cookies are not cleaned by "Cookies Exterminator" or any other WE that deals with those.
"Cookies Exterminator" I use until "Cookie AutoDelete" is not able to remove local storage.

It might be a bit slower rendering (or its a placebo effect only), but I have 0 cache and got effectively rid of ETAG cookieless tracking/fingerprinting too.

**Comment by Thorin-Oakenpants** [comment]
This cached info should be under #179

**Comment by earthlng** [comment]
@grauenwolfe 

> And finally, shouldn't the disk section's entries be all "0"?

If that bothers you, you can set `browser.cache.disk.capacity` to 0.

**Comment by Thorin-Oakenpants** [comment]
Back OT... I disabled NS, uM and uBo, allowed cookies and local dom, indexedDB was already allowed .. and STILL i got nothing except I had to sit thru 30 seconds of Taylor Swift .. the things I do for u guys!

Guess it's off to nillaland and pref tweaking one by one

**Comment by Forsaked** [comment]
Was the PB mode active?

**Comment by Thorin-Oakenpants** [comment]
Not using PB mode, I never do, it's massively overrated and in fact I lose some control - but I have narrowed it down. It is not extensions for sure. So far

Using my 56.0b11 installed version (normally I am on portable) which I open with `-p`, create new profile etc

1. Default 56 nilla
   * got https+++www.youtube.com folder under permanent
2. Block all cookies
   * got https+++www.youtube.com folder under permanent
3. disable `device.storage.enabled` (default was false anyway)
   * no change
4. turn on FPI (ie privacy.firstparty.isolate)
   * note: privacy.firstparty.isolate.restrict_opener_access default is true
   * got https+++www.youtube.com^firstPartyDomain=youtube.com

BACKUP PROFILE and THEN

5. apply whole user.js as is (note the above settings are the same)
   * got NOTHING :tada: 

ROLLBACK PROFILE to end of test 4 and now what. Will keep digging. How come you guys get crap. Don't you use the js like your master does?

**Comment by earthlng** [comment]
>  I wish I could get HTTP header modify whatever to do as it says

It only allows modifying **request** headers and afaik some of the cache-dependent request headers are impossible to remove because they're probably added by FF *after* extensions had their hands on the headers. You need something that allows removing the Etag from the **response** headers.

**Comment by Thorin-Oakenpants** [comment]
IN the case of youtube, the reason I do not get any IDB is because of workers - section 2300. Am narrowing it down now

**Comment by Thorin-Oakenpants** [comment]
That's interesting. I created a brand new nilla profile. Changed `dom.serviceWorkers.enabled` to false, loaded Taylor Swift youtube video, and the storage folder did not even create subfolders for default or temporary.

I wonder if service workers are going to be needed for uBo and uM and extensions - I don't think so since no one has complained yet

**Comment by Atavic** [comment]
>Don't you use the js like your master does?

ESR with minor changes here.

**Comment by Thorin-Oakenpants** [comment]
OK .. so I fired up a new nilla (FF56), and hunted all over the net finding some sites that set IDB data...

https://www.youtube.com/watch?v=3tmd-ClpJxA
http://www.huffingtonpost.com/section/politics
https://www.theguardian.com/international
https://www.washingtonpost.com/
https://twitter.com/i/moments
pinterest.com << redirects to localised domain
https://www.dropbox.com/
https://web.whatsapp.com/

Here are the results
![idbcrap](https://user-images.githubusercontent.com/16656956/30439754-ba6e3466-99c8-11e7-895f-bcd002f00367.png)

I cleared everything, manually wiped IDB, closed, started FF, set `dom.serviceWorkers.enabled` to false, revisited those 8 sites .. here are the results
![idblesscrap](https://user-images.githubusercontent.com/16656956/30439870-0cfe6958-99c9-11e7-8782-c8a52c741c44.png)

So clearly some sites use service workers to spawn their devil children, and some don't.

I visited all these 8 sites in my main FF, and got ZERO idb crap. Of the four that still dump idb litter without service workers, I actually allow HuffPo and Guardian, but I guess I must block the bit that causes the trash.

So this explains why I haven't seen any IDB entries since I've had it on for over a month. 1. sites using IDB are hard'ish to find (I wasted ages loading sites from the top 500). 2. service workers being denied would account for some 3. NS, uBo, uM default deny/hard-mode would explain a lot of the rest. Mystery solved.

PS: Oh boy.. loading those sites in a nilla FF - OMG .. the CPU was racing, adverts and shit everywhere. I do not want to ever do that again. I even loaded pornhub and other top 500 sites in my quest to find a decent sample. Trust she-males to be on the front and center of Categories (often its not the landing page that triggers the IDB, so you have to click around .. or at least that's what I told myself!) .. crssi .. stop laughing

**Comment by Thorin-Oakenpants** [comment]
> I think you once said you're using the full "Youtube: Pure Video Experience"

Not me. I almost never go to YT, in fact I virtually never play vids (which is why I couldn't care less about GMP, EME, CDM, Widevine etc). Today's TayTay avalanche in testing is enough to last me 3 months

**Comment by crssi** [comment]
OMG, I was in tiers laughing, even before way before you mentioned me. :)
