### ISSUE TITLE
a few things to reconsider

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#237]
* [x] 1261, 1262 + 1263 - IMO we should comment these out by default.
Even if someone never allows JS and therefore eliminates most FP vectors, these prefs still puts them in a very small group. Not even the Tor guys disable those in TBB even though they could do it *without* increasing their users uniqueness. Not worth it IMO. - https://github.com/ghacksuserjs/ghacks-user.js/commit/89474d014f866c365e3292a4aa71657c9ded3484

* [x] 2500: things that are not necessary to disable if one doesn't have the hardware for it, fe.
   * 2501 - gamepads
   * 2504 - VR
   * 2509 - touch support
   * 2512 - devices with sensors
   * 2513 - presentation API (added by Thorin)

IMO we should makes those inactive by default. EDIT: done => https://github.com/ghacksuserjs/ghacks-user.js/commit/598ee751f5faba6f602db8f2ae0a5ca97f562bd2 & https://github.com/ghacksuserjs/ghacks-user.js/commit/39594629e521a529f66cb1f0de197931f30ad52e (thanks Pants)

* [x] rename `ghacks_user.js.parrot` to `_user.js.parrot` to make it the first pref in about:config - https://github.com/ghacksuserjs/ghacks-user.js/commit/bdf0e5ed569523e934a93d61905ce9a9f7de26ea

* [x] 2024 MSE (Media Source Extensions) => inactive and moved to 5000s - https://github.com/ghacksuserjs/ghacks-user.js/commit/a93ce5d9f145146a3be9346fe2adff06d8db5c82

* [x] 1404: set legible fonts - move to 1402, shove the others down, make inactive as it affects OS' differently - https://github.com/ghacksuserjs/ghacks-user.js/commit/80ac9dfa1f916f0db80d7b10faa998e6c6b9cf23

* [x] 2804: clarify Clear Recent History - https://github.com/ghacksuserjs/ghacks-user.js/commit/7fa0025bafd968b7dbc5fd0db5b36e3bd7cfd2f1

**Comment by Thorin-Oakenpants** [comment]
gamepads (56), device sensors (56), touch (57) are covered by RFP .. VR might be added since they see to be first and foremost focused on hardware issues

Agree. Either people need these (smartphone/tablet=touch) and have peripherals plugged in, otherwise no one would ever bother to lock them down. Since they're almost all under RFP, no big deal.

Am thinking about the cyphers and parrot

**Comment by Thorin-Oakenpants** [comment]
^^ with all this hardware => inactive, it's going to make 4600 alt look like a joke

**Comment by Thorin-Oakenpants** [comment]
Now I'm not convinced. These **do** tighten leaks, and 3 of the 4 will be redundant very soon for stable - which is when they move to 4600. So it comes down to the 4 releases left for ESR - why not just leave them as they have been for the last 2 years.

**Comment by Thorin-Oakenpants** [comment]
device light they rounded to integers, but its like the whole battery thing over again - I'll try to find the ticket

**Comment by Thorin-Oakenpants** [comment]
Here it is: https://bugzilla.mozilla.org/show_bug.cgi?id=1299454

**Comment by earthlng** [comment]
> These do tighten leaks

what does it leak when I don't have the hardware? Lots of people don't have that hardware but very few people have those APIs disabled.

**Comment by Thorin-Oakenpants** [comment]
The way I see it is that it's meant to be a **catch-all**. What about people who do have the hardware? Enumerating device IDs and high entropy fingerprinting of eg sensor ambient light far outweigh single bits (is the API on or off) IMO. We're all FP'able anyway, and as you point out anti-FP measures are FP'able in their own right. A default of active doesn't add much, a default of inactive can land someone in the crapper, that's all I'm saying.

I get your point though - that most users of this user.js are desktop and do not have this hardware. 

So what should we do?
- Sensor => inactive but add a setup/warning for mobile/tablet?
- VR and gamepad => inactive but add a WARNING for people with this hardware plugged in
- Touch => inactive but add a WARNING for mobile/tablet/touch

**Comment by earthlng** [comment]
> So what should we do? ...

Yes that's what I would do. VR is default false in ESR52 anyway but we can add a warning regardless.

**Comment by Thorin-Oakenpants** [comment]
> rename `ghacks_user.js.parrot` to `_user.js.parrot` to make it the first pref in about:config

I like this idea but it would impact 12bytes users and @atomGit, not to mention existing users could get caught out (at least the parrot part is still there) . FWIW I just type `parr` when I need to check. Should we really change it this late in the game?

**Comment by Thorin-Oakenpants** [comment]
> Yes that's what I would do. VR is default false in ESR52 anyway but we can add a warning regardless.

Do a commit then, for all four

**Comment by earthlng** [comment]
> Should we really change it this late in the game?

IMO it's more useful if you can see it right away. I would also make the last one a bit clearer, and if you want to make it really cute it's also possible to use unicode fe for the last one:
`user_pref("_user.js.parrot", "\u2713 All good! The parrot survived");`

**Comment by earthlng** [comment]
> Do a commit then, for all four

Can *you* do it please, you're a better writer than I am :)

**Comment by Thorin-Oakenpants** [comment]
>  I would also make the last one a bit clearer,

But that's a classic line from Monty Python :cry:  WTF does that `u2713 do. Not into cute. How about

```js
user_pref("_user.js.parrot", "START: Oh yes, the Norwegian Blue... what's wrong with it?");
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");
```

**Comment by earthlng** [comment]
\u2713 = ✓

> How about

yeah whatever. nerd! ;) Should 9999 also get a parrot?

**Comment by Thorin-Oakenpants** [comment]
why should 9999 get a birdy ... u ESR laggards just want everything

**Comment by Thorin-Oakenpants** [comment]
Do we REALLY want to force change on everyone for the sake of alphabetization?

As for a 9999 parrot, it has crossed my mind since we have effectively created a hybrid ESR/Stable. We can do that. But we need to involve @atomGit for a pref name change - so he can mod his supplementary js, change his article, and let his readers know

@atomGit .. get in here :)

**Comment by earthlng** [comment]
It was just something to consider. If you don't want to do it that's fine.

**Comment by Thorin-Oakenpants** [comment]
Nah, I'm keen, but we just need to make sure atom is fine, and consider others

> 1261, 1262 + 1263 

The only reason this stuff is in here is from PK. I'm not a encryption nerd. The last time I encrypted text, I then ran the results thru an image viewer and it turned out to be a nude redhead on a motorcycle.

My gut feeling is that browsers do not leave us insecure - they may be slightly slow to remove items, due to breakage (I think they have marks of < 0.3% or something). The other thing is that the chances of coming across these ciphers are probably slim to none? Especially now after another year+. So that just leaves us with FPing cipher suites - the answer to which is use defaults

So lets make then inactive and change the Options in the 1200 header

**Comment by earthlng** [comment]
Yeah, I suck at crypto too but if not even the TBB guys disable these then I don't think we need to either.

**Comment by Thorin-Oakenpants** [comment]
So who's turn to do the commit?

**Comment by Thorin-Oakenpants** [comment]
That doesn't work for me, btw (on windows)

![stupidparrot](https://user-images.githubusercontent.com/16656956/30498261-236a20a6-9aaa-11e7-9b88-3f6d80470d30.png)

**Comment by Thorin-Oakenpants** [comment]
That parrot pref name is genius, every time I go to about:config it stares at me, assuming I didn't change the column order - I wonder if that gets reset on start?

@earthlng :kiss: :beer: :+1: :tada:

**Comment by Thorin-Oakenpants** [comment]
Presentation API should be the same, i.e => inactive. Those who need it, need it. Those who dont, it makes no difference. Will do a commit

**Comment by Thorin-Oakenpants** [comment]
all 6 `dom.presentation*` prefs were default false anyway in FF55 windows

**Comment by earthlng** [comment]
a few more things I noticed while updating my user.js: 

* 1404 - these fonts are Windows-only. I think they are mostly only useful if 1401 is used, right?
Maybe consider moving 1404 to 1401b, commenting the prefs out and instead of using actual font names that are Windows-only use "your-chosen-font-name-here" or something like that.
But there's also the problem for Russians for example because they will probably also want to change `font.name.serif.x-cyrillic` - so maybe it would be better not to include the prefs at all (?).
Or maybe just get rid of 1404 and add a [NOTE] to 1401 fe.
[NOTE] you can set more legible default fonts in Options>Fonts & Colors>Advanced>Serif|Sans-serif|Monospace
maybe with an additional note if you want:
[NOTE] Georgia or Constantia are pretty nice 'serif' alternatives on Windows for example

* 2024 - do we really need these? if you want to keep them how about setting them to false and inactive? **and**/or move them to 5000 where the other media prefs are, idk.

* 4700 - we once had this [TEST] http://browserspy.dk/showprop.php?navigator, which was pretty useful IMO

* `2804: set what history items to clear with Ctrl-Shift-Del (to match above)`
  * it doesn't clear it though, it only auto-selects them ...
 "auto selection of items to delete with Ctrl-Shift-Del (to match above)" or so would be more accurate

**Comment by Thorin-Oakenpants** [comment]
> 4700 - we once had this [TEST] http://browserspy.dk/showprop.php?navigator, which was pretty useful IMO

I was actually trying to code a script myself that covered all methods of obtaining the UA and navigator objects (I think there are about 3 ways to call these?), including across an iframe, and all relevant bits (locale, format, language) into a single test page to put up here - but I gave up because I am limited to FORTRAN

I was going to do one because everything we want is spread over about 5 test pages and even then it's lacking. Maybe you could code one up some day

**Comment by Thorin-Oakenpants** [comment]
1404: this actually causes issues for Linux and tofu's <sup>1</sup>

[1] Slang for the empty boxes shown in place of undisplayable code points in computer character encoding

**Comment by Thorin-Oakenpants** [comment]
I don't get your point with 2804
- `set what history items to clear with Ctrl-Shift-Del`
- `auto selection of items to delete with Ctrl-Shift-Del`

"it doesn't clear it though" << I don't follow. Nothing is deleted or cleared unless you hit the `Clear Now` button. The action is "setting", "to clear" is the subsequent action.

Deleting vs clearing - I fail to see the distinction. The dialog is called `Clear All History`, the button is named `Clear Now` and the dialog is brought up from the menu item `Clear Recent History` .. so `history items to clear` is EXACTLY what we want

"Set" or "auto select" is the the same thing IMO. When we went thru and standardized all the actions for prefs, `set` is one of them - I believe we have 22 of them now.

Or am I missing something?

**Comment by earthlng** [comment]
> I was going to do one because everything we want is spread over about 5 test pages and even then it's lacking. Maybe you could code one up some day

https://browserleaks.com/javascript offers exactly what you want on a single page, no? yeah it misses the INTL.DateFormat stuff but other than that is there anything else missing you would want?

> I don't get your point with 2804

my point is that "set" sounds like everything you don't "set" there cannot be cleared/deleted, but all it does is pre-select the items to clear. Nvm the clear vs delete, that was just because I copy-pasted it from my user.js. IDC if it's clear or delete. If you like "set" better then something like "set what items are pre-selected to clear with Ctrl-Shift-Del" would still be easier to understand IMO.

**Comment by Thorin-Oakenpants** [comment]
when RFP bundles fonts thru Kinto and sets 1409 - then 1401 (block fonts) and 1402 (legible fonts dicking around) will be obsolete - i.e off the RFP ALT and forgotten. This will actually make the web slightly easier to read, although after 2+ years I never really have any issues (sometimes menus get out of line but that's about it)

**Comment by Thorin-Oakenpants** [comment]
https://browserleaks.com/javascript - it's not using all methods to obtain objects, is missing headers, doesn't show iframe side by side, other stuff (lots)

**Comment by Thorin-Oakenpants** [comment]
> my point is that "set" sounds like everything you don't "set" there cannot be cleared/deleted

Ahh OK. Look up [verbal reasoning](https://en.wikipedia.org/wiki/Verbal_reasoning) ... it's used a lot in psychometric tests. I can tell you I score top 1% (pro tip, the answer is usually `can't tell` if you are in any doubt)

---test---

> When you set the values for preferences in 2804 as true or false, they `pre-select` what history items to clear with Ctrl-Shift-Del. This dialog can also be accessed from the menu History>Clear Recent History

Based on the previous statement, if you go Ctrl-Shift-Del to bring up the Clear All History dialog, you can not change what items are cleared?
 - A) true
 - B) false
- C) can't tell

If you selected C, then you win.

--maybe--

I will change it to `reset default history items` - like 2805, any changes made in the dialog stick until a restart

**Comment by Thorin-Oakenpants** [comment]
a girl's allowed to change her mind xD

Nah, its not about changing minds - if it makes sense, then we do it. Some of these have been on my mind eg I *knew* my font choices can screw up Linux (because of the issue with tofu's and nodiscc), I knew Touch was [almost] pointless (I'm reminded every time I look at Panoticlick), I remember presentation being all false anyway but we enforced it (which is probably a bit silly if someone needs it, they would have to turn it on, plus we have diffs to pick up on these things). I remember our discussions re ciphers almost 6 months ago

It just takes time, reminding, refining - the more eyes, ideas the better. This RFP has prompted a lot of change

> no arguing at all

I hate you xD there! .. and NO to the UA test unless ~~we~~ you build a better one
