### ISSUE TITLE
"browser.display.use_document_fonts", FFv55 - uBO and uM display corruption

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#238]
after installing FFv55, i noticed the icons at the top of both uMatrix (1.0.0) and uBlock O (1.14.8) are mangled/missing - i found the cause to be `"browser.display.use_document_fonts" = 0`

setting that to '1' solves the issue

this was apparently an old problem, but i'm wondering if it's resurfaced with v55?

related:

[test: browser.display.use_document_fonts · Issue #126 · ghacksuserjs/ghacks-user.js](https://github.com/ghacksuserjs/ghacks-user.js/issues/126)

[Firefox 41: Mozilla modifies how icon fonts are handled by the browser - gHacks Tech News](https://www.ghacks.net/2015/07/21/firefox-41-mozilla-modifies-how-icon-fonts-are-handled-by-the-browser/)

**Comment by Thorin-Oakenpants** [comment]
Works perfectly fine for me in WINDOWS

The problem with tofu is the default fonts - that is in Linux, the fallback fonts under Content>Fonts & Colors>Advanced> .. those three font choices .. one of them doesn't map to a character

@nodiscc - what was the font you used/changed so it worked on debian

**Comment by Thorin-Oakenpants** [comment]
NOTE: We made this inactive, but only a few days ago, so already existing users would need to reset these (maybe check your values in a new profile to see what they would be for your OS) - https://github.com/ghacksuserjs/ghacks-user.js/commit/80ac9dfa1f916f0db80d7b10faa998e6c6b9cf23

**Comment by 2glops** [comment]
browser.display.use_document_fonts = 0
I set fonts to Liberation (Sans, Serif) to unbreak uBo GUI
FF 55.0.3 on Debian

**Comment by Thorin-Oakenpants** [comment]
side note: diffs for 54->55 #144 included 53 `font.name*` NEW prefs and 114 `font.name*` prefs CHANGES - this could be why it showed in 55 as per first popst

**Comment by atomGit** [comment]
i couldn't get the uBO or uM icons to appear by changing fonts - i tried about every reasonable font i had installed and started with a fresh prefs.js - so i'm leaving the option for sites to choose their own fonts enabled (this is on Linux btw)

on another note (and i'll open a new ticket depending on feedback) ... when the user.js is updated, there can be old sections that are commented out, depreciated stuff, etc. - i'm wondering about how to handle removing/resetting the affected prefs in prefs.js - i'm wondering if you guys could create a batch script with all the old/commented prefs that would run on prefs.js to remove the clutter?

**Comment by Thorin-Oakenpants** [comment]
> when the user.js is updated, there can be old sections that are commented out, depreciated stuff, etc

Do you mean how do people know to eg reset touch API (which we just made inactive). There is no easy answer **for items we make inactive in the main section**. For those that are deprecated, they are all nicely listed in a section by FF version for them. Same for the resist fingerprinting prefs that are redundant. I added this info to the readme in the user.js under "EACH RELEASE CHECK:"...

Otherwise there is the changelog (and commits, diffs). As RoxKilly once said, it would be nice if a `reset_pref` existed

Another way would be to sort the js by column 1 to get all the `"  // user_"`  lines grouped, and to manually go thru and make sure they are reset

**Comment by earthlng** [comment]
A simple scratchpad script could do the job:
```js
(function() {
  let ops = [
    /* deprecated/removed in FF55 */
    'browser.formautofill.enabled',
    'browser.formfill.saveHttpsForms',
    'browser.fullscreen.animate',
    'browser.newtabpage.directory.ping',
    'browser.selfsupport.enabled',
    'browser.selfsupport.url',
    'browser.tabs.animate',
    'dom.enable_user_timing',
    'dom.keyboardevent.code.enabled',
    'geo.security.allowinsecure'
  ]
  
  for (let i=0, len=ops.length; i < len; i++) {
    //Services.prefs.clearUserPref(ops[i]);
  }
})();
```
open about:blank (so that Services is available for scratchpad) then press Shift+F4, paste the script and run it. We could add every pref we either removed, commented out or deprecated/removed since 52-alpha to the ops array. But it would be one more thing we would need to maintain and IDK if we want to do that.

**Comment by Thorin-Oakenpants** [comment]
> A simple scratchpad script could do the job:

`could`? or `does`? ...

**Comment by earthlng** [comment]
"could" because 
> it would be one more thing we would need to maintain and IDK if we want to do that.

but "does" if we decide to provide that.

**Comment by Thorin-Oakenpants** [comment]
I didn't mean that we provide it (FukNo™), was just questioning whether or not your code worked

**Comment by Thorin-Oakenpants** [comment]
We could add a new wiki page for bulk clearing via scratchpad - sample would include non-existant pref names

**Comment by atomGit** [comment]
> A simple scratchpad script ...

that's a damn good idea

i might be willing to maintain the script, the problem is that you guys do a lot of releases, sometimes multiple releases a day, and i don't have the time for that

if i updated the script once a week (oe so), would that work? i'm not sure how i'd get a list of prefs though unless i parsed every version of user.js since the last time i updated the script - i'm not into that either

is there maybe a GitHub repo tool that could run a RegEx on ALL of the released user.js files that could help? or could all of them be downloaded at once?

**Comment by Thorin-Oakenpants** [comment]
^^ all you need is the inactive ones - you can get that in 2 easy steps - sort by column, copypasta

**Comment by atomGit** [comment]
well, i'd like the depreciated ones too just to cut the garbage in prefs that could be misleading to someone trying to troubleshoot - i think a RegEx run against every release could be used, the ? is; how to d/l or access in one place every version of user.js

**Comment by Thorin-Oakenpants** [comment]
deprecated are inactive - I'm about to paste u the 126 prefs

**Comment by earthlng** [comment]
> We could add a new wiki page for bulk clearing via scratchpad - sample would include non-existant pref names

that would be pretty nonsensical because people would need to check our changelogs for the relevant prefs and add them to the script and that would probably end up taking longer than just resetting each one in about:config.

**Comment by Thorin-Oakenpants** [comment]
but wot about the l33t amongst us :) Why downgrade our info to lowest common denominator?

**Comment by Thorin-Oakenpants** [comment]
https://pastebin.com/9B0hZAk8 - dies in 2 weeks

- 139 inactive prefs in user.js - i.e ` // user_pref`
- 78 active prefs in user.js in section 9999 deprecated
- nothing to add from RFP ALT inactive as it only has one entry which is inactive and got picked up in the 139 items above

:warning: dirty quick job, suggest you check for errors! I did a few search and replaces

Also: as per first line - you should run this thru a nilla profile to spot any errors

**Comment by earthlng** [comment]
you don't need to include all the inactive prefs, only the ones we made inactive since the last release.

"commented out" output from my script for the next changelog:
```js
//user_pref("device.sensors.enabled", false);
//user_pref("dom.gamepad.enabled", false);
//user_pref("dom.indexedDB.enabled", false);
//user_pref("dom.presentation.controller.enabled", false);
//user_pref("dom.presentation.discoverable", false);
//user_pref("dom.presentation.discovery.enabled", false);
//user_pref("dom.presentation.enabled", false);
//user_pref("dom.presentation.receiver.enabled", false);
//user_pref("dom.presentation.session_transport.data_channel.enable", false);
//user_pref("dom.vr.enabled", false);
//user_pref("dom.w3c_touch_events.enabled", 0);
//user_pref("font.name.monospace.x-unicode", "Lucida Console");
//user_pref("font.name.monospace.x-western", "Lucida Console");
//user_pref("font.name.sans-serif.x-unicode", "Arial");
//user_pref("font.name.sans-serif.x-western", "Arial");
//user_pref("font.name.serif.x-unicode", "Georgia");
//user_pref("font.name.serif.x-western", "Georgia");
//user_pref("media.mediasource.enabled", false); // previously active with value: true
//user_pref("media.mediasource.mp4.enabled", false); // previously active with value: true
//user_pref("media.mediasource.webm.audio.enabled", false); // previously active with value: true
//user_pref("media.mediasource.webm.enabled", false); // previously active with value: true
//user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
//user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
//user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
//user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
//user_pref("security.ssl3.rsa_des_ede3_sha", false);
```

**Comment by Thorin-Oakenpants** [comment]
^^ Depends on what you're trying to do

- We set prefs inactive for a reason, so this is a way for users to ***make sure*** they are reset
- If users follow our guidelines to use overrides (eg at end of user.js or override.js) then they do not lose any settings - it merely does what we want in the above point
- BUT .. I should have excluded the personal section

I'm actually going to modify this list to exclude personal and run it

**Comment by earthlng** [comment]
http://pasted.co/059329d0/fullscreen.php?hash=fc7c9889db6ebacd661900f5afc0d4be&toolbar=true&linenum=false

**Comment by atomGit** [comment]
> 139 inactive prefs in user.js

is that a running list? does it include all inactive since you guys started? if so, this will be easier than i thought

an idea: i'll maintain the list/script - i can do this in the wiki, or you could put it in the repo alongside user.js and i'll make pull requests

you guys point users to the script in user.js and wherever else is appropriate

since peeps will have the script to refer to, in user.js i think you could remove 9999: DEPRECATED (maybe just link the script there) and shorten the file

might be best to have 2 scratchpad scripts? 1 for depreciated and 1 for inactive? or 1 script that is commented to indicated what's what

as pants says, people need to be sure they add custom prefs at the end so they don't lose and settings from removed inactive prefs

i like this/your ideas guys - i, and certainly others i'm sure, would like to make updating user.js as quick and hassle-free as possible and resetting prefs in about:config isn't an option IMHO

**Comment by earthlng** [comment]
well I'm willing to do this if and when you finally find the time to upload the pics for your uBlock/uMatrix article to your own server and update the `<img>` tags xD

**Comment by atomGit** [comment]
@earthlng - i get an error when running your script (modified to include all [this](https://pastebin.com/9B0hZAk8), with commas in the right places and some cleanup)...

`Exception: ReferenceError: Services is not defined
@Scratchpad/1:220:5
@Scratchpad/1:1:2`

this is referencing...

`  for (let i=0, len=ops.length; i < len; i++) {
    Services.prefs.clearUserPref(ops[i]);
  }`

**Comment by earthlng** [comment]
> **open about:config (so that Services is available for scratchpad) then press Shift+F4, paste the script and run it.**

**Comment by atomGit** [comment]
> well I'm willing to do this if and when you finally find the time to upload the pics for your uBlock/uMatrix article to your own server ...

already got much of that done - i've been updating the article and replacing as i go

**Comment by atomGit** [comment]
> open about:config (so that Services is available ...

lol - i guess it helps to actually READ the directions :)

is there any feedback when you run a script? i clicked 'run' and nothing appears to happen (about:config was active tab)

**Comment by atomGit** [comment]
> is there any feedback when you run a script? i

never mind - i checked a pref and the script is indeed working

**Comment by Thorin-Oakenpants** [comment]
> is that a running list? does it include all inactive since you guys started?

That was everything that was commented out in MY user.js (which is slightly different - so a few items missed, see post above with the :warning: sign) - but yes, imagine I used the master js here at github, then it is everything since we started (but the 139 number does not include the deprecated section)

> never mind - i checked a pref and the script is indeed working
check the **last** pref before running and after running

**Comment by earthlng** [comment]
[clearUserPref()](https://dxr.mozilla.org/mozilla-central/source/modules/libpref/nsIPrefBranch.idl#237) doesn't return anything so it's not possible to add meaningful checks or counts. If nothing appears to happen it worked. That's why I think we should include the _user.js.parrot in the list, which is the first pref in about:config, to make it easy to spot if the script worked or not.

**Comment by Thorin-Oakenpants** [comment]
^Would it not be better to have the parrot change at the end?

**Comment by earthlng** [comment]
> does it include all inactive since you guys started?

all the prefs we removed from the user.js are missing in that list

**Comment by Thorin-Oakenpants** [comment]
^^ I was about to say that - off the top of my head there would only be three or four

**Comment by earthlng** [comment]
> Would it not be better to have the parrot change at the end?

doesn't really matter, but sure, why not. I wanted to include a non-existent pref at the end anyway to make it easier for people to remove blocks they don't want to reset and not have to worry about the commas, but the parrot at the end would work too.

**Comment by earthlng** [comment]
> clearUserPref() doesn't return anything so it's not possible to add meaningful checks or counts.

scratch that. Calling 'prefHasUserValue' before and after each call to clearUserPref can be used as a check (+count)

**Comment by Thorin-Oakenpants** [comment]
In reality, users should reset every single pref in the user.js, both active and inactive AND those removed ones above, and on a restart, they would lose nothing. This approach would cover people who have made changes to the js - the purist in me like the fact that for everyone this would mean inactive in js = reset in about:config. It'd almost be like starting with a new profile

**Comment by atomGit** [comment]
so this is what i came up with as an example...

`/*
  NAME: Scratchpad prefs.js cleanup script
  VERSION: ?
  AUTHOR/MAINTAINER: the ghacks boys and atomGit

  This is a Firefox Scratchpad cleanup script intended to reset all depreciated and unused preferences from your prefs.js file.

  The purpose of running this script is to cleanup your prefs.js file after you update your user.js file with a newer ghacks version in order to remove bloat and thus potentially help you when troubleshooting a problem. Running this script each time you update your user.js avoids having to manually reset preference values, thus making updating your user.js a bit less painful.

  The source of the depreciated preferences is Mozilla while the source of the unused preferences is the ghacks user.js files. After resetting the preference values, all of the depreciated preferences will be removed from your prefs.js file upon restarting Firefox. The values for the unused preferences will be emptied in your prefs.js file.

  WARNING: If you have set the values of any preferences in this list but have not copied them to your user.js, then those preference values will be lost.

  How to run this script:
  
  1) BACKUP YOUR CURENT FIREFOX PROFILE - you have been warned :)
  2) Copy this script
  3) Open about:config in Firefox
  4) Press Shift + F4 to open Scratchpad
  5) Press Ctrl + A and then Ctrl + V to paste the script in Scratchpad
  6) Click the "Run" button on Scratchpad (there will be no indication that it ran, but there should be a log message appended to the script if there was a problem)
  7) Restart Firefox
*/

(function() {
  let ops = [
    'accessibility.typeaheadfind',
    'app.update.enabled',
    [content removed for brevity]
    'security.tls.unrestricted_rc4_fallback',
    'toolkit.telemetry.unifiedIsOptIn'
  ]
  
  for (let i=0, len=ops.length; i < len; i++) {
    Services.prefs.clearUserPref(ops[i]);
  }
})();`

assuming you guys really want to do this, given i'll maintain it, then i got a Q: how can comments be added within the list? i want to identify depreciated and unused if you think it's a good idea

**Comment by Thorin-Oakenpants** [comment]
I do not believe you need to differentiate anything. The script should include every single pref (plus those we removed). When they restart, their user.js and override.js etc will simply set everything as they wanted it to be. In other words, a blanket reset to cover everyone's customized user.js

**Comment by earthlng** [comment]
I don't like the idea to reset every single pref in the user.js, it's unnecessary. We already have "commented out", "removed from the user.js" and "moved to deprecated" sections in the changelogs and that covers everything we need to include in the reset-script. It also allows for commented blocks in the script and can therefore also be useful for ESR users.

> how can comments be added within the list?

@atomGit see my [pasty](http://pasted.co/059329d0/fullscreen.php?hash=fc7c9889db6ebacd661900f5afc0d4be&toolbar=true&linenum=false)

**Comment by Thorin-Oakenpants** [comment]
^^ I'm not saying we provide it AT ALL  - the script is damn handy and I want it documented in the wiki with a tiny sample of made up pref names - but f**ked if I'm going to provide anyone with a list

My point above was that in order to cover everyone (which atomGit wants to do) then the way to do it IMO is to reset the entire lot - that way the js matches prefs exactly. Anyway, moot point - up to atomGit if he want to do anything :)

OT: Holy cow .. we have some action: https://trac.torproject.org/projects/tor/ticket/23104

**Comment by atomGit** [comment]
@earthlng "see my pasty" - got it - thanks (at first i couldn't open that link when you first posted it - sorry)

@Thorin-Oakenpants re: resetting ALL prefs - not sure if you're referring to user or prefs, but either way, i would humbly agree with earthing

**now, for something a bit different...**

could the process of updating the user.js and the cleaning of prefs.js (equivalent to running the Scratchpad script) be **totally automated** by, say, a GM script that would prompt first and show a changelog perhaps?

**Comment by Thorin-Oakenpants** [comment]
> not sure if you're referring to user or prefs, but either way, i would humbly agree with earthing

All ghacks user.js prefs including the ones we removed (definitely not referring to prefs.js - that has FF internals etc in it). Not sure if u guys get it - resetting them ALL does not break anything, because ALL active prefs get re-applied. What it does ensure is that ALL inactive prefs get reset including those commented out or even removed by the end user - u know, cuz the ghacks user.js is a TEMPLATE :) Anyway .. I know I'm right :)

**Comment by atomGit** [comment]
no, you're not right - i am because i'm perfect ... well, there was this ONE time i THOUGHT i was wrong, but i was wrong :)

i get what you're saying and i realize it shouldn't break anything as long as the user appended changes rather than editing user.js (and if not, well, tough cookies) so yeah, i don't care, but i'd like you guys to argue about more cause i like watching you fight ... and i really don't feel qualified to make that decesion

what about the GM thingy to automate the entire process?

**Comment by Thorin-Oakenpants** [comment]
> it shouldn't break anything as long as the user appended changes rather than editing user.js

That's irrelevant, because the active prefs are still active no matter where they are

**Comment by Thorin-Oakenpants** [comment]
Draft: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Bulk-Pref-Resetting-[Scratchpad]

**Comment by atomGit** [comment]
i ran it - seems to work but i'm still not seeing any feedback in the web or browser console

i'll have more feedback regarding the wiki and stuff shortly...

**Comment by atomGit** [comment]
fresh, dedicated issue for the scratch-script discussion [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/242)
