### ISSUE TITLE
followup: OAs: FPI, PB, Containers

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#240]
OriginAttribute types: firstPartyDomain, privateBrowsing, containerID

FPI is apparently "global" - that is if true it is used in normal, pb mode and containers. However, even Arthur is only 90% sure on this. It needs testing.

There is a new pref being touted (edit: [1397624](https://bugzilla.mozilla.org/show_bug.cgi?id=1397624)) that would make FPI into PB mode only (maybe for Mozilla to turn on for PB mode in trials and later permanently, as firstPartyDomain has many benefits over privateBrowsing ). How would this pref then affect containers?

> [10:35] `<arthuredelstein>` Here's the key place where OriginAttributes get compared. If two OAs are not equal (this function returns false) then the associated (cookies, cache entries, DOM storage, etc.) will be isolate in separate "jars".
> [10:35] `<arthuredelstein>` https://dxr.mozilla.org/mozilla-central/rev/2cd3752963fc8f24f7c202687eab55e83222f608/caps/OriginAttributes.h#50
> [10:36] `<arthuredelstein>` So basically isolation happens if userContextId (container) is different, or firstPartyDomain is different, or if one from a PB window and one is from a normal window.
> [10:37] `<arthuredelstein>` So you can see that the mechanism that determines whether something gets isolate can handle containers, FPI, and PBM all at the same time.

We need to test and confirm FPI is indeed `global`

Knowing this will help us to understand what happens with access to OA persistent data down the track

Edit: I am also slightly confused by this. If FPI replaces containerIDs, then would this not break container jar separation - eg `ContainerA + gmail` is not isolated from `ContainerB + gmail` ?

**Comment by Thorin-Oakenpants** [comment]
¯\_(ツ)_/¯  how do we test this

**Comment by Atavic** [comment]
>ContainerA + gmail is not isolated from ContainerB + gmail...

Aren't these different containers?

>`<arthuredelstein>` So basically isolation happens if userContextId (container) is different...

**Comment by Thorin-Oakenpants** [comment]
I think this answers my question - https://bugzilla.mozilla.org/show_bug.cgi?id=1301617#c0

tests for
> `https://example.com^firstPartyDomain=example.com`
> `https://example.com^userContextId=1`
> `https://example.com^userContextId=1&firstPartyDomain=example.com`

They were testing "permissions". I think I can assume the same would happen in PB mode.

**Comment by Thorin-Oakenpants** [comment]
Update: example of OA for PB is `^privateBrowsingId=1`
