### ISSUE TITLE
Service Workers - about:debugging

### ISSUE THREAD

**Issue by grauenwolfe** [ghacksuserjs/ghacks-user.js#241]
A little irritated at seeing `resource://gre/modules/PageThumbsWorker.js` listed since I had supposedly disabled all worker, service worker and all thumbnail entries. Can you guys check about:debugging and see what's listed under **Workers**? Here's what I have:

![define disable](https://user-images.githubusercontent.com/25858089/30768144-57d62622-9fc9-11e7-9f3c-992fe5a6650b.png)

P.S. - I'll follow up in a secondary post with additional information and the cause of concern.

**Comment by grauenwolfe** [comment]
Maybe I'm overreacting to something I don't fully understand but seriously, how goddamn hard can it be to really turn something off? Below are my entries + values related to thumbnails and workers.

-----

**A) relevant settings for thumbnails:** 
 

* `browser.newtab.preload` = false
 
* `browser.newtabpage.activity-stream.enabled` = false
 
* `browser.newtabpage.columns` = "0"
 
* `browser.newtabpage.rows` = "0"
 
* `browser.newtabpage.directory.source` = data:text/plain,
 
* `browser.newtabpage.enabled` = false
 
* `browser.newtabpage.enhanced` - false
 
* `browser.newtabpage.storageVersion` = "1" _(no idea what value actually means)_
 
* `browser.newtabpage.thumbnailPlaceholder` = false
 
* `browser.pagethumbnails.capturing_disabled` = false
 
* `browser.pagethumbnails.storage_version` = "3" _(no idea what value actually means)_
 
* `app.update.lastUpdateTime.browser-cleanup-thumbnails` = "1506123042" _(?)_
-----
 
**B) relevant settings for workers:**

* `dom.serviceWorkers.enabled` = false
 

* `dom.serviceWorkers.openWindow.enabled` = false
 

* `dom.serviceWorkers.testUpdateOverOneDay` = false
 

* `dom.webnotifications.serviceworker.enabled` = false
 

* `dom.workers.enabled` = false

-----

So am I missing something specific detail, minutia, or maybe even a larger, unfamiliar perspective? Honestly, I really just want to know and understand it all. Why things are seemingly left intact or active when they should be disabled, I mean fully disabled.

**Comment by Thorin-Oakenpants** [comment]
AFAIK they're just internals. Pagethumbs are disabled - you're not getting any. Internal workers are fine - they increase speed, efficiency etc. Here's mine (I'm not on e10s yet due to 3 legacy addons)

![workin-9-til-5](https://user-images.githubusercontent.com/16656956/30769746-ac7eb608-a073-11e7-87ab-6060dd786843.png)

**Comment by Atavic** [comment]
**Stop Firefox from Capturing Thumbnails**:
In about:config page right-click and create a new Boolean preference
`browser.pagethumbnails.capturing_disabled` 
and set it to true.

Do not know if still works...
See: https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preference_reference/browser.pagethumbnails.capturing_disabled

>1506123042

Unix Epoch Time

**Comment by Atavic** [comment]
1506123042 it's unix epoch time

**Comment by 2glops** [comment]
Got only these two workers on FF 55.0.3 Linux:
resource:///modules/sessionstore/SessionWorker.js
resource://gre/modules/osfile/osfile_async_worker.js

**Comment by Thorin-Oakenpants** [comment]
With the js settings, we are definitely not capturing pagethumbs - not in the original new tab tiles etc. Interesting that 2glops on linux doesn't have this js library loaded (maybe it can't work on linux?). Not too concerned about it, but just thinking about this a little in the whole revamp of the landing pages with onboarding and other changes. I know we kill onboarding with a pref (in fact I remove the xpi). I wonder if screenshots requires it?

Worth rechecking when 57 stable lands. Meanwhile, I guess if anyone wants to search DXR and dig a little deeper, be my guest

**Comment by grauenwolfe** [comment]
Weekend over and yeah, not really too worried about it running per se, especially since nothing's in the thumbnails folder, but moreso just frustration with how convoluted some of Mozilla's pref settings are, i.e., is it milliseconds, seconds, days, no clear-cut "this value" = "this result" associations for many integer values, but mostly it's the 62-different-preference-entries-to-change-one-function that I don't have much patience for. Moving on, thanks for pitching in.

**Comment by Thorin-Oakenpants** [comment]
@2glops - if you create a new nilla profile on linux in 55.0.3, and turn off pagethumbs and close and reopne FF - do you still have PageThumbsWorker.js loaded? I only ask because I'm intrigued as to why yours is off

**Comment by Thorin-Oakenpants** [comment]
heh ... https://bugzilla.mozilla.org/show_bug.cgi?id=884458

**Comment by Thorin-Oakenpants** [comment]
> *  browser.pagethumbnails.storage_version = "3" (no idea what value actually means)

See https://dxr.mozilla.org/mozilla-central/source/toolkit/components/thumbnails/PageThumbs.jsm#757 (or read the bit below)

```
    // Storage version 1 never made it to beta.
    // At the time of writing only Windows had (ProfD != ProfLD) and we
    // needed to move thumbnails from the roaming profile to the locale
    // one so that they're not needlessly included in backups and/or
    // written via SMB.

    // Storage version 2 also never made it to beta.
    // The thumbnail folder structure has been changed and old thumbnails
    // were not migrated. Instead, we just renamed the current folder to
    // "<name>-old" and will remove it later.

    if (version < 3) {
      this.migrateToVersion3();
    }

    this.currentVersion = LATEST_STORAGE_VERSION;
  },
```

**Comment by Thorin-Oakenpants** [comment]
I searched DXR for thumbnail (and bugzilla with several terms) - couple of ideas (not that I am saying these use the PageThumbsWorker, but why would they reinvent the wheel? - newtab/activity stream use it)

- Windows Ctrl-Tab show thumbnails (when you have x tabs with content open) (interestingly bugzilla does not show a thumbnail) - WindowsPreviewPerTab.jsm
- Screenshots uses some sort of thumbnailing as well
- Lots of things with drag and drop may use a thumb of some sort
- Dev tools and pdfjs use thumbs I think

^^ I am on Windows, I have Screenshots enabled (only used it once!), I use pdfjs. These are not being saved to disk, just used in display I think, but still. Anyway, this is a chrome worker and I have no issues with it. Persistent disk data of thumbs certainly is not happening. If it's running there must be a reason

**Comment by Atavic** [comment]
> app.update.lastUpdateTime.browser-cleanup-thumbnails = "1506123042" (epoch time)

*update timers (move far into the future)*:

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", "2476106725");

See [here](https://www.cs.kau.se/pulls/hot/tb-6.0.6-noise/).
