### ISSUE TITLE
discussion: HW acceleration / wasm => inactive: convince me NOT to

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#244]
I see no reason to disable this (or even keep it) unless there is some security risk. It was added in 52 (we don't have a diffs 51-52, not sure what the default was - not that it matters now). Default in 55 is true.

```js
/* 2422: disable WebAssembly for now (FF52+)
 * [1] https://developer.mozilla.org/docs/WebAssembly ***/
user_pref("javascript.options.wasm", false);
```

---

Same goes for hardware acceleration, which is a FP concern. While I like to lock down as much FP as possible, sometimes it is a balance. I feel with e10s, sandboxing, OOP, Quantum/Stylo/WebAssembly and so much more, that locking out the GPU seems silly now.

```js
/* 2508: disable hardware acceleration to reduce graphics fingerprinting
 * [SETTING] Options>General>Performance>Custom>Use hardware acceleration when available
 * [NOTE] Changing this option changes BOTH these preferences
 * [WARNING] [SETUP] Affects text rendering (fonts will look different) and impacts video performance
 * [1] https://wiki.mozilla.org/Platform/GFX/HardwareAcceleration ***/
user_pref("gfx.direct2d.disabled", true); // [WINDOWS]
user_pref("layers.acceleration.disabled", true);
```

---

Class discuss!

**Comment by earthlng** [comment]
WebAssembly - "This is an experimental technology". How many sites actually use this?
> unless there is some security risk.

unless you're a security expert who can audit it and verify that it's not a security risk, I don't think the potential performance benefits are worth the risk. Should we make it inactive? IMO absolutely not.

> I feel with e10s, sandboxing, OOP, Quantum/Stylo/WebAssembly and so much more, that locking out the GPU seems silly now.

do any of those things actually make use of the GPU? source(s) please. Afaik they make more efficient use of multiple CPUs. Should we make it inactive? IMO absolutely not.

Class discuss!

**Comment by Thorin-Oakenpants** [comment]
Well poop! Lets keep driving around in our carts and horsies, and enact the [Red Flag Act](https://en.wikipedia.org/wiki/Red_Flag_Act#The_Locomotive_Act_1865_.28Red_Flag_Act.29). xD

I may have been getting WebAssembly mixed up with WebRender, I no longer know, too much happening.

I didn't mean to imply that all the above required the GPU (and some parts in future can use the GPU, whatever they are called) - what I meant was in a new shiny speedy improved FF (57+) where a thousand tiny fixes and massive effort went into minuscule incremental improvements, it seems odd to create a "bottleneck" (for lack of a better  word) with GPU. Regardless of all the above Quantum'y things, enabling the GPU makes a difference already by its very nature - not including the obvious video. So I was asking if it was really necessary given the potential FP'ng. What exactly is this FP threat? It needs evaluation and I'm not qualified and do not know the answers

Class discuss!

**Comment by Thorin-Oakenpants** [comment]
[SETTINGS] Options>General>Performance>Custom>Use hardware acceleration when available
[NOTE] Changing this option changes BOTH these preferences

On windows, this now only changes the pref `layers.acceleration.disabled` - we can remove `gfx.direct2d.disabled` - it barely even registers at [DXR](https://dxr.mozilla.org/mozilla-central/search?q=gfx.direct2d.disabled&redirect=false)

**Comment by Thorin-Oakenpants** [comment]
earthlng
> do any of those things actually make use of the GPU? source(s) please

me
> I may have been getting WebAssembly mixed up with WebRender

Hardware acceleration being made inactive definitely still on the table. I read this several weeks ago (and more about it since) - https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/ . Awesome article, btw.

I am not entirely sure on when most of WebRender lands (I suspect 59-61!), but there ya go. Something making use of the GPU and a source with loads of cool cartoony pics. Whether we do or don't make it inactive is up for discussion, as well as when. Note: there's a bunch of settings to enable WebRender, but we can ignore those since they are not in the user.js, and some are for controlling it in nightly before it lands.

I guess it will remain to be seen how much difference it makes (and everyone's mileage may differ) - I mean, I am yet to get e10s going due to 2 legacy addons. I am yet to get 57. I do struggle with some websites (cpu goes bonkers, some lag - eg sorting 5K plus bugzilla tickets), but in general everything is already sweet (lets face it - minimum JS and XSS help)

reopening so @earthlng sees this message :)

**Comment by Thorin-Oakenpants** [comment]
> Well poop! Lets keep driving around in our carts and horsies, and enact the [Red Flag Act](https://en.wikipedia.org/wiki/Red_Flag_Act#The_Locomotive_Act_1865_.28Red_Flag_Act.29). xD

"A speed limit of 4 mph (2 mph in towns) was imposed for road locomotives" - holy crap, that's insane. 4mph is approx a brisk walk .. 2mph is an old-person's speed, using a zimmer frame .. blind .. with their shoelaces tied together .. going uphill .. into a headwind

**Comment by Thorin-Oakenpants** [comment]
FYI: Not that I profess to understand this fully .. but here's another article > https://hacks.mozilla.org/2017/11/entering-the-quantum-era-how-firefox-got-fast-again-and-where-its-going-to-get-faster/

Check out the pictures
- Quantum Compositor -> GPU
- Quantum Render (lands in 2018) -> GPU
   * meanwhile, "Advanced Layers project" optimizes/uses GPU stuff

**Comment by RoxKilly** [comment]
@Thorin-Oakenpants linked to:

> https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/

A pleasure to read. I'm only half-way through but have to take a break, so I figured I'd come here to thank you for sharing.

**Comment by Thorin-Oakenpants** [comment]
^^ if you read the comments, from memory, she answered someone who asked her how log it took to put together - I think she said 3 months or more. BTW, she also does the cartoons

**Comment by Thorin-Oakenpants** [comment]
Another article - https://mozillagfx.wordpress.com/2017/12/05/off-main-thread-painting/

I'm no expert, but that there is talking about using the GPU if I am not mistaken - Advanced Layers landed in 57 and Off-Main-Thread painting lands in 58.

IDK what the answer is, and everyone will get different mileage. It'll be interesting to see what Tor does (probably nothing)

**Comment by Atavic** [comment]
Skia, Cairo are libraries; Direct2D is an API used by gecko rendering engine. These are called for SVG and Canvas layouts. Tor has SVG disabled on the highest security settings only.

**Comment by Thorin-Oakenpants** [comment]
@RoxKilly & co .. another Lin Clarke article :+1: 
- https://hacks.mozilla.org/2018/01/making-webassembly-even-faster-firefoxs-new-streaming-and-tiering-compiler/

**Comment by Thorin-Oakenpants** [comment]
So I just did some tests at https://lukewagner.github.io/test-tanks-compile-time/ re WebAssembly (wasm)

- `FF57`: didn't write it down and my portable is now gone: about `4.x MB/s`
- `FF59.01b` (I updated to be on latest 58 and ended up with 59)
   * control: WebAssembly.instantiate took 280.6 ms (44.1 MB/s)
   * disable baseline ONLY -> WebAssembly.instantiate took 1877.7 ms (6.6 MB/s)
   * disable ionjit ONLY -> no real change -> WebAssembly.instantiate took 289.7 ms (42.7 MB/s)
   * disable .wasm => doesn't work at all (duh!)

prefs
```
javascript.options.wasm
javascript.options.wasm_baselinejit
javascript.options.wasm_ionjit
```

As per Lins article (and the one at ghacks), I get similar results (about 10 times faster) - this comes from the new pref `javascript.options.wasm_baselinejit` in FF58.

WASM was disabled when added back in FF52. I see **no point** is keeping it disabled (ESR users and earthlng can use an override).

What I do not understand is how widespread WebAssembly/wasm is. Or just what the difference is in reality - eg in the above example does that mean I get to see stuff almost 1.6 seconds faster (1877.7 -  280.6 = 1597.1ms)? Does wasm apply to every website? IDK, I'm a dummy.

Sooner or later WebRender and WebAssembly are landing and HW acceleration and wasm are going to be inactive - unless there is a real compelling argument against them. I lack the full picture - I mean its all good and well to get excited by 10-15 times performance gains, but its f**king useless if it only happens on 0.0001% of websites - capisce? Someone fill me in.

**Comment by Atavic** [comment]
FF ESR 52.0 (32-bit):

`javascript.options.wasm false`
`javascript.options.wasm_baselinejit false`

**Comment by Thorin-Oakenpants** [comment]
sorry, my bad.. `javascript.options.wasm_baselinejit` was flipped in 58, not new in 58

Thanks Atavic. ESR users would not be affected. I am proposing the prefs be made inactive (i.e commented out) when and if we do it. It may not be until FF62 when ESR52.x reaches EOL, in which case by then everyone should be on the same page

**Comment by Atavic** [comment]
Can't remember a page with Webassembly. The [org](https://github.com/webassembly) is active, though.

**Comment by Thorin-Oakenpants** [comment]
For myself I do not need the extra speed (but I'd like it) with HW acceleration - but WebRender is at least a few releases away. I think the FP'ing aspect is not that bad (there are so many other ways of doing FPing), and the best way to beat most client-side FP is to control JS etc. I'm not sure what else exactly is using GPU as new things are added (Off thread painting, accelerated layers, WebRender itself, etc). At some stage, holding back the GPU will not be worth it - it barely is now IMO. But I am happy to wait until 60/62.

WebAssembly is not affected by HW acceleration (it made no difference in my test). wasm by the sounds of it can also wait. I just want to be more knowledgeable on this matter. I suppose I better do some googling (yup, because all the other search engines suck as complex searches)

**Comment by StanGets** [comment]
FYI, in case as if myself you weren't aware, _uBlock Origin_ offers the option to disable _WebAssembly_:

uBlock Dashboard / Settings / I am an advanced user / advanced settings (far right icon) :

disableWebAssembly - false (default).

I've set it to true for whatever it may enforce Ghacks user.js `pref("javascript.options.wasm", false);`

I don't know what version of _uBlock Origin_ added this advanced setting but it does mean IMO that _WebAssembly_ is sufficiently problematic to have uBO include it as an option to disable it.

**Comment by Thorin-Oakenpants** [comment]
^^
https://github.com/gorhill/uBlock/search?q=disableWebAssembly&type=Wikis
https://github.com/gorhill/uBlock/wiki/Advanced-settings#disablewebassembly
added in uBO 1.17.3rc4 and above

I don't think it means what you think it means. I think it means that uBO won't use wasm when doing **it's own stuff**

**Comment by StanGets** [comment]
`I don't think it means what you think it means. I think it means that uBO won't use wasm when doing it's own stuff - i.e development purposes when gorhill is testing all those speed things with tryhard (yeah I know that's not how you spell it!)`

OK but then why add it as an option, especially that `disableWebAssembly` is set to false by default?

Thanks for the links, means you follow uBO developments when I must admit I haven't been on uBO's repository for some time now ...

P.S. I just read the latest link, uBO 1.17.4 Release, and i understand you better. In fact the option is irelevant for users who have set `pref("javascript.options.wasm", false);` and concerns those who haven't and if they wish or not uBO to bring "WebAssembly ("wasm") versions of key portions of code where it is found to be beneficial."

So, for those who haven't disabled WebAssembly it's better to keep uBO's `disableWebAssembly` to false, if I understand correctly.

**Comment by Thorin-Oakenpants** [comment]
> In fact the option is irelevant for users who have set pref("javascript.options.wasm", false); and concerns those who haven't

AFAICT this is nothing to with the pref. Only a few prefs are accessible for extensions to change thru the Privacy API - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy

I'm knackered and need a good sleep. I can't find an up to date list, but it is really small from memory - like 20 items

**Comment by Thorin-Oakenpants** [comment]
here are some of them: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy/websites

you can change some cookie settings, FPI, RFP .. etc

**Comment by StanGets** [comment]
That's what I understood indeed : uBO's option concerns only  uBO, it bringing or not WebAssembly ("wasm") versions of key portions of code where it is found to be beneficial, nothing to do with Firefox's `javascript.options.wasm` setting, even if, the latter being disabled, the former becomes irrelevant.

Your analysis is of course tailored, deeper. I'm only trying to get things clear from my point of view. I think I understood the essentials of your explanations, thanks again!
