### ISSUE TITLE
'beacon.enabled' causing havoc in ffv55

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#246]
ff v55.1.0

don't recall this in v54, but `beacon.enabled  = false` is causing page load problems in certain instances possibly web-wide - i'm especially noticing it in the WordPress backend where i'll load a page to edit, then click another menu item in the WP sidebar and, though the URL changes as expected, the page never loads

**Comment by mazesy** [comment]
`beacon.enabled `is advised to be set to _false_, but you certainly have your reasons and beyond all there shouldn't be any problem, especially that the default value is _true_.

**Comment by Thorin-Oakenpants** [comment]
Do me a favor - load a brand new profile. turn beacons => false. Log into word press and tell me if the problem persists. I really doubt beacon has anything to do with your issue - so humour me

**Comment by Thorin-Oakenpants** [comment]
>  though the URL changes as expected, the page never loads

This is exactly the behavior that happens with those stand-alone images - noticeable when you load in the same tab as eg a currently loaded website. I'm going to go out on a limb here and say this is a GM script & uBo webext clashing again

**Comment by atomGit** [comment]
i meant FALSE - sorry - setting to false causes WP backend issues

you are right - loading a new profile and setting beacon.enabled to false does not cause an issue, so yeah, there's something going on with GM, uBO and uM and ffv55 i think

**Comment by Thorin-Oakenpants** [comment]
ok, so it's not the setting that's faulty then - I'll close this, it's a red herring
