### ISSUE TITLE
About the safety of addons from AMO

### ISSUE THREAD

**Issue by EchoDev** [ghacksuserjs/ghacks-user.js#248]
https://www.reddit.com/r/firefox/comments/737kze/mining_codes_been_discovered_in_two_reviewed/

Bitcoin miners in browsers (On sites, in addons) are popping up more and more often.  Now that Mozilla is switching partially (maybe fully soon?) to automatic reviewing of addons, I think we should be more careful with the addons we install from AMO. Maybe it is time to recommend to user to turn off automatic updates of addons? Ofcourse bitcoin miners are not the only danger, other types of malware/adware might (probably will) show up on AMO with the new system.

What would be the smart way to handle the new AMO system?

**Comment by Thorin-Oakenpants** [comment]
> Maybe it is time to recommend to user to turn off automatic updates of addons? 

We already do this. We auto-CHECK both app + extensions (see 0301s), but we do not auto-UPDATE (see 0302s). This is mentioned in
- the readme section at the top of the user.js
- the 0300 section header
- the [wiki implementation page](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.3-Implementation) under :exclamation: `ULTRA SUPER UBER IMPORTANT`
   * and we point to the implementation page in about 5 places to shove that down people's throats

Not sure what else we can do. The only drawback is system add-on updates do not get picked up - zilla bug - see #172

**Comment by EchoDev** [comment]
Hmm I didn't see that since I don't use the user.js, the discussion in the issues tab kept me here heh

I wonder if people would be up to do manual checks on addons for recommended addons (at minimum webextension?). I feel like the only problematic addons would be NoScript (No source available/No Git, and the next version will be a full webextension, there might be a lot of changes) and Greasemonkey (Pretty complex and a lot of work is being done at the moment for version 4.0)

When uMatrix, NoScript, DecentralEyes, CanvasBlocker, Greasemonkeyt, HTTPS everywhere and Smart Referer would make the transition to WE it would leave us with 13 recommended WE for Firefox 57 users. Most of them seem to be updated not that very often, so the workload for most is not that high.

Most of the work would be uBlock, NoScript and Greasemonkey, due to complexity or update speed.

**Comment by Thorin-Oakenpants** [comment]
Even if users did not auto-update (but get reminders eg in about:addons), I doubt they would vet it. I think the likes of established devs and popular extensions, there is safety in numbers and reputation.

**Comment by EchoDev** [comment]
That's true I guess. 

Still, I'm a bit annoyed that every once in a while a developer goes rogue and implements something like a miner in fairly popular extension. This is the second time this week I'm reading about it in combination with Firefox addons. I only use a few addons outside the recommended addons from the wiki but I might stick with recommended addons only soon I guess...

**Comment by Thorin-Oakenpants** [comment]
> since I don't use the user.js

![say-wot](https://user-images.githubusercontent.com/16656956/31043140-7ad1f8ea-a613-11e7-806b-7ef471533d1a.jpg)

I think we can close this
