### ISSUE TITLE
history.length test fails [solved: uBo WE vs legacy extensions]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#251]
edit: nvm - this is a symptom of the biggest issue of uBo + legacy exetnsions

---

To reproduce (I have all 3 of our scripts enabled, hence the windows.name result included below). Clearly different methods are being used

- Open a tab, load the [wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki) and quickly load ten different pages in the same tab so `tab history` exists and then click on "user scripts"
- Click on the [Browserspy](http://browserspy.dk/document.php) test for history.length
   * Number of pages visited in History should fail :x:  and show the number 10 (which is our limit in preferences)
- Go back one page to re-land on the wiki, and now click the JoDonym [landing page](http://ip-check.info/?lang=en) test link for window.name
   * `Tab name` (windows.name) and `Tab history` should be green :white_check_mark:  and Protected

**Comment by Thorin-Oakenpants** [comment]
The console error that comes up with GM + uBo when a stand-alone image fails to load is

> http channel Listener OnDataAvailable contract violation

Meanwhile, I am simply using GM with the 3 scripts disabled. Maybe I'll try TM one day

**Comment by Atavic** [comment]
Browserspy source is JS:
```javascript
<script type="text/javascript">
//<![CDATA[

		(history && typeof(history.length) != "undefined") ? document.writeln(history.length) : document.writeln("Property not supported or blank!");
	//]]>
</script>
```

**Comment by earthlng** [comment]
It took me a long time to figure out what the problem is here; must have been at least 30 seconds!
I had to copy-paste the console error into a search engine and click literally the first link and read it.

https://github.com/adsbypasser/adsbypasser/issues/1544

solution: get rid of your legacy extensions that aren't e10s-compatible and then enable e10s.

**Comment by gorhill** [comment]
> solution: get rid of your legacy extensions that aren't e10s-compatible and then enable e10s.

That's what I document in uBO's release notes for the webext version of uBO:
https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext

**Comment by Thorin-Oakenpants** [comment]
I can live without those 3 scripts until GM WE is out. I won't be jumping into 57 immediately, probably 2 or 3 weeks afterwards (NoScript, GM, couple of others are a bit late to the party). I'll leave any more migrations til the last minute. Thanks gorhill, earthlng. That closes the issue re uBo WE vs weird effects. TIL to use the console more.

HOWEVER .. does this explain why the test works on JoDonym and not Browserspy
