### ISSUE TITLE
Firefox 56 drop download speed if at the same time upload something.

### ISSUE THREAD

**Issue by zelenko5** [ghacksuserjs/ghacks-user.js#252]
Hi.

By the nature of my work, I often use cloud storage. With the release of Firefox 56, I noticed that if download and upload something, in the same time, the download speed drops 4-5 times. If upload is stopped then the download speed immediately grows. My real speed 100/100Mb. If you use ESR or a browser v55 or lower then nothing of the sort happens. I think that this is somehow connected with Firefox electrolysis. Advise what can be done?

PS: user.js latest version.

**Comment by earthlng** [comment]
Hi 

> Advise what can be done?

set `network.http.throttle.enable` to false

**Comment by zelenko5** [comment]
YES! It works! Thank you very much. You do not know what caused the speed drop in FF56?

**Comment by Gitoffthelawn** [comment]
@earthlng What's a good summary of what that pref controls?

**Comment by earthlng** [comment]
> You do not know what caused the speed drop in FF56?

it's a new feature that throttles downloads (+ a few other things) when something more "important" happens, like a page load or an upload apparently.

**Comment by Gitoffthelawn** [comment]
@earthlng Thank you!
