### ISSUE TITLE
wiki: NoScript ABE rule

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#257]
https://trac.torproject.org/projects/tor/ticket/10419

I am interested by the discussion in this old ticket. I profess that NS's ABE is a mystery to me. But we have a wiki NS scripts page (its in the menu but not created yet), and I think this is a good one to add. I just need someone who can test it and give me a clean working version (there are a few shown in the ticket)

This is about blocking 127.0.0.1 - which I am not saying is a good or bad thing, or that it leaks or not. It's just to add to the wiki.

```
# Prevent Internet and LAN sites from requesting 127.0.0.1's resources.
Site 127.0.0.1
Accept from 127.0.0.1
Deny

# Prevent 127.0.0.1 from requesting Internet and LAN resources.
Site ALL
Deny from 127.0.0.1
```

Not sure if I would use it myself. Not that I use privoxy anymore, but doesn't that use 127.0.0.1:portXXX? Also my plex server uses that (although I could always just use a different browser).

**Comment by Atavic** [comment]
I had no problems with privoxy and Noscript, but ABE can work on [single ports](https://hackademix.net/2010/01/08/nat-pinning-and-abe/).

**Comment by Atavic** [comment]
Recent [inclusion types](https://forums.informaction.com/viewtopic.php?f=23&t=23104) which can be used as:

```
# This one allows Facebook scripts and objects to be included only
# from Facebook pages
Site .facebook.com .fbcdn.net
Accept from .facebook.com .fbcdn.net
Deny INCLUSION(SCRIPT, OBJ, SUBDOC)
```

[Source](https://github.com/sbworth/abe-fragments/blob/8ab0494ce859dfecf386a91561fcac2ea07c8852/README.rst)

**Comment by Thorin-Oakenpants** [comment]
This was already in my SYSTEM ABE

```
# Prevent Internet sites from requesting LAN resources.
Site LOCAL
Accept from LOCAL
Deny
```

It was just a thought to get something going on ABE stuff for the wiki, but seems no one knows enough, or cares, or has any decent scripts (cept Atavic)

Not really interested in scripts like the FB one, because all that can be done with uMatrix, uBo since they allow granular per domain control

**Comment by Atavic** [comment]
[Get .onion and .i2p links working with Noscript ABE enabled](https://github.com/cryptostorm-dev/noscript-abe-tor-i2p).

```
Site *.onion *.i2p 
Accept GET 
Site LOCAL 
Accept from LOCAL 
Deny
```

**Comment by Thorin-Oakenpants** [comment]
^^^ Not recommended - use TOR

```
/* 1607: .... blah blah
 * [NOTE] Firefox cannot access .onion sites by default. We recommend you use
 * TBB (Tor Browser Bundle) which is specifically designed for the dark web
```
