### ISSUE TITLE
chit chat: WebAPI Manager [Extension]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#258]
- https://addons.mozilla.org/firefox/addon/webapi-manager/
- https://github.com/snyderp/web-api-manager

I'm intrigued. I've installed it. And I've unpacked it.

First up: 
```js
  "web_accessible_resources": [
    "lib/init.js",
    "lib/js.cookie.js",
    "lib/storage.js",
    "lib/URI.js",
    "content_scripts/dist/defaults.js" ]
```
^^ maybe someone can tell me if that's a problem - as it does inject AFAIK when required. If only we had someone with the skills to do this .. hmmm

Secondly - there's a fair bit of stuff here. I played with the conservative and aggressive modes, and thought I might list all the items here for us to look at. Some we do not need to worry about, others need investigation, etc - and we could come up with a good default.

Note1: I tested blocking `HTML: The canvas element` (I assume this means `canvas`) and CanvasBlocker seemed to override it and I still spoofed a canvas.

Note2: Clicking conservative sets the list to just the preset `defaults.conservative` list, and clicking aggressive **concatenates** the `defaults.aggressive` list (i.e concatenate = adds, ie agressive = aggressive list + conservative list)

---

If you unpack the xpi, the `content_scripts\dist` folder holds a `defaults.js` with these two lists, but what I would really like is for someone to parse the `standards.js` and extract me the following

```
{"name":"Ambient Light Sensor API","subsection_number":null,"subsection_name":null,"url":"https://w3c.github.io/ambient-light/","idenitifer":"Ambient Light Sensor API"}
```
==>
* Ambient Light Sensor
   * https://w3c.github.io/ambient-light/

So this way we can list the entire lot with links and come up with a good set of things to default block on. Also .. assuming web accessible resources is not a problem long term (FF bug fix?) or that these are not a problem (not sure on the `lib/*` items but `content_scripts/dist/defaults.js` seems to be only for the options interface

**Comment by Thorin-Oakenpants** [comment]
PS: There are 74 items in total ( you can view the 74 json files in `data\standards` ). The `conservative` settings "ticks" 14 items (i.e disables their respective APIs) and `aggressive` "ticks" an additional 30 for a total of 44

Note: Indexed Database API is among conservative - no idea if this will break extensions (we know moz-extension is exempt from (other) extensions right?). Maybe this will allow IDB to be blocked at a web content level, but not at an extension level. IDK. I do not really care about IDB myself since I block ALL but 8 cookies

Note: some items not in conservative or aggressive (30 items in all) could/should be "ticked" - eg Aggressive mode leaves `beacon` and `vibration` APIs working (as an example of two obvious items we would kill in a heartbeat)

No idea how or what they based their two quick-set lists on

**Comment by EchoDev** [comment]
This should make it more readable

https://paste.kthnxbai.xyz/?66ca6958c57438f6#foGznhCBHiNPdOI5W+GdjTlKNas6LNyoe1k2+5pCzrU=

**Comment by Thorin-Oakenpants** [comment]
* [ ] XMLHttpRequest
   * https://xhr.spec.whatwg.org/
* [ ] Ambient Light Sensor API
   * https://w3c.github.io/ambient-light/
* [ ] Battery Status API
   * https://www.w3.org/TR/battery-status/
* [ ] Beacon
   * https://www.w3.org/TR/beacon/
* [ ] Console API
   * https://github.com/DeveloperToolsWG/console-object
* [ ] CSS Conditional Rules Module Level 3
   * https://drafts.csswg.org/css-conditional-3/
* [ ] CSS Font Loading Module Level 3
   * https://drafts.csswg.org/css-font-loading/
* [ ] CSS Object Model (CSSOM)
   * https://drafts.csswg.org/cssom/
* [ ] CSSOM View Module
   * https://drafts.csswg.org/cssom-view/
* [ ] DeviceOrientation Event Specification
   * https://www.w3.org/TR/orientation-event/
* [ ] DOM Parsing and Serialization
   * https://w3c.github.io/DOM-Parsing/
* [ ] DOM
   * https://dom.spec.whatwg.org/
* [ ] Document Object Model (DOM) Level 1 Specification
   * https://www.w3.org/TR/REC-DOM-Level-1/
* [ ] DOM Level 2: Core
   * https://www.w3.org/TR/DOM-Level-2-Core/
* [ ] DOM Level 2: Events
   * https://www.w3.org/TR/DOM-Level-2-Events/
* [ ] DOM Level 2: HTML
   * https://www.w3.org/TR/DOM-Level-2-HTML/
* [ ] DOM Level 2: Style
   * https://www.w3.org/TR/DOM-Level-2-Style/
* [ ] DOM Level 2: Traversal and Range
   * https://www.w3.org/TR/DOM-Level-2-Traversal-Range/
* [ ] DOM Level 3: Core
   * https://www.w3.org/TR/DOM-Level-3-Core/
* [ ] DOM Level 3: XPath
   * https://www.w3.org/TR/DOM-Level-3-XPath/
* [ ] W3C DOM4
   * https://www.w3.org/TR/dom/
* [ ] Directory Upload
   * https://wicg.github.io/directory-upload/proposal.html
* [ ] Encoding
   * https://encoding.spec.whatwg.org/
* [ ] execCommand
   * https://w3c.github.io/editing/execCommand.html
* [ ] Encrypted Media Extensions
   * https://w3c.github.io/encrypted-media/
* [ ] Fetch
   * https://fetch.spec.whatwg.org/
* [ ] File API
   * https://w3c.github.io/FileAPI/
* [ ] Fullscreen API
   * https://fullscreen.spec.whatwg.org/
* [ ] Geolocation API
   * https://www.w3.org/TR/geolocation-API/
* [ ] Geometry Interfaces Module Level 1
   * https://drafts.fxtf.org/geometry/
* [ ] Gamepad
   * https://w3c.github.io/gamepad/
* [ ] HTML: Broadcasting
   * https://html.spec.whatwg.org/multipage/comms.html#dom-broadcastchannel-postmessage
* [ ] HTML: The canvas element
   * https://html.spec.whatwg.org/multipage/scripting.html#the-canvas-element
* [ ] HTML: Channel Messaging
   * https://html.spec.whatwg.org/multipage/comms.html#channel-messaging
* [ ] HTML: History Interface
   * https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface
* [ ] HTML: Plugins
   * https://html.spec.whatwg.org/multipage/webappapis.html#plugins-2
* [ ] HTML: Web Storage
   * https://html.spec.whatwg.org/multipage/webstorage.html
* [ ] HTML: Web Sockets
   * https://html.spec.whatwg.org/multipage/comms.html#network
* [ ] HTML: Web Workers
   * https://html.spec.whatwg.org/multipage/workers.html
* [ ] High Resolution Time Level 2
   * https://w3c.github.io/hr-time/
* [ ] HTML
   * https://html.spec.whatwg.org
* [ ] HTML 5
   * https://www.w3.org/TR/html5/
* [ ] HTML 5.1
   * https://www.w3.org/TR/html51/
* [ ] Indexed Database API
   * https://www.w3.org/TR/IndexedDB/
* [ ] Media Capture from DOM Elements
   * https://w3c.github.io/mediacapture-fromelement/
* [ ] Media Capture and Streams
   * https://www.w3.org/TR/mediacapture-streams/
* [ ] Media Source Extensions
   * https://www.w3.org/TR/media-source/
* [ ] MediaStream Recording
   * https://www.w3.org/TR/mediastream-recording/
* [ ] Non-Standard
   * null
* [ ] Navigation Timing
   * https://www.w3.org/TR/navigation-timing/
* [ ] Proximity Events
   * https://w3c.github.io/proximity/
* [ ] Pointer Lock
   * https://w3c.github.io/pointerlock/
* [ ] Performance Timeline
   * https://www.w3.org/TR/performance-timeline
* [ ] Performance Timeline Level 2
   * https://w3c.github.io/performance-timeline
* [ ] Page Visibility (Second Edition)
   * https://www.w3.org/TR/page-visibility/
* [ ] Resource Timing
   * https://w3c.github.io/resource-timing/
* [ ] Shadow DOM
   * https://www.w3.org/TR/shadow-dom/
* [ ] Selection API
   * http://w3c.github.io/selection-api/
* [ ] Selectors API Level 1
   * https://www.w3.org/TR/selectors-api
* [ ] The Screen Orientation API
   * https://w3c.github.io/screen-orientation/
* [ ] Scalable Vector Graphics (SVG) 1.1 (Second Edition)
   * https://www.w3.org/TR/SVG/
* [ ] Service Workers
   * https://www.w3.org/TR/service-workers/
* [ ] Timing Control for Script-Based Animations
   * https://www.w3.org/TR/animation-timing
* [ ] Tracking Preference Expression (DNT)
   * https://www.w3.org/TR/tracking-dnt/
* [ ] UI Events Specification
   * https://w3c.github.io/uievents/
* [ ] URL
   * https://url.spec.whatwg.org/
* [ ] User Timing Level 2
   * https://w3c.github.io/user-timing/
* [ ] Vibration API
   * https://www.w3.org/TR/vibration/
* [ ] Web Cryptography API
   * https://www.w3.org/TR/WebCryptoAPI/
* [ ] Web Audio API
   * https://webaudio.github.io/web-audio-api
* [ ] WebGL Specification
   * https://www.khronos.org/registry/webgl/specs/latest/1.0/
* [ ] WebVTT: The Web Video Text Tracks Format
   * https://w3c.github.io/webvtt/
* [ ] Web Notifications
   * https://notifications.spec.whatwg.org/
* [ ] WebRTC 1.0: Real-time Communication Between Browser
   * https://www.w3.org/TR/webrtc/",

**Comment by Thorin-Oakenpants** [comment]
Not sure how to go about this. There are clearly some items we can ignore (battery status) or are covered by RFP (timing attacks, screen orientation) or would just break sh*t (html anyone?). Then there are items we could ignore because we already disable them and they are obscure (vibration)

And what's left we could split into two groups
- APIs we have no prefs for (eg Ambient Light Sensor API)
   * recommendation: set API in default deny and whitelist domains where needed
- APIs we have prefs for (eg Service Workers)
   * recommendation: reset pref(s) in about:config, set API in default deny and whitelist domains where needed

Class: discuss!

**Comment by Thorin-Oakenpants** [comment]
Hmmm .. not even sure this works - maybe I'm doing something wrong. I killed `CSSOM View Module` which contains all the screen and window measurements etc and JoDonym still got all the info

**Comment by earthlng** [comment]
> And no, it does not require cookies

it passes the rules with a temporary cookie: https://github.com/snyderp/web-api-manager/blob/master/background_scripts/background.js#L111

and that's probably why it did nuttin for you.

btw a site can also easily detect if the addon is installed: `if (window.WEB_API_MANAGER != undefined)`


> APIs we have no prefs for (eg Ambient Light Sensor API) 

afaik Ambient Light Sensor API is disabled with the sensors pref.

**Comment by earthlng** [comment]
The whole cookie thing is weird and I'm not sure it's always gonna work as expected. Meaning it's maybe possible to create a site that overwrites the rules. 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/get
> If more than one cookie with the same name exists for a given URL, the one with the longest path will be returned. For cookies with the same path length, the cookie with the earliest creation time will be returned.

**Comment by 2glops** [comment]
Installed WebAPI Manager on FF56, no configuration:
Not able to login on any site I used to, which have FF cookie exceptions.
Network console shows a bunch of icons files from assets-cdn.github.com

**Comment by Thorin-Oakenpants** [comment]
@earthlng "afaik Ambient Light Sensor API is disabled with the sensors pref" - my bad. But there are items here that we have no prefs for - see the list of objects in EchoDevs prettified pastebin.

Cookies, ahhh, so global cookies else it will not work - including 3rd party, how else can it control any XSS thru, right?

@2glops If you disable WAM, are you still affected?

**Comment by Thorin-Oakenpants** [comment]
> If more than one cookie with the same name exists for a given URL, the one with the longest path will be returned. For cookies with the same path length, the cookie with the earliest creation time will be returned.

Well my cookies all contain ^firstparty or whatever it is so likely longer (without looking) and also the 8 sites I allow permanent cookies - those cookies were created months ago

**Comment by Thorin-Oakenpants** [comment]
> btw a site can also easily detect if the addon is installed: if (window.WEB_API_MANAGER != undefined)

So is this something to tell the developer? Also, what is the answer on the web accessible resources - does this reveal the UUID?

**Comment by 2glops** [comment]
@Thorin-Oakenpants 
Disabling WAM solved the issue, I can login as usual on Github.
FPI enabled too

**Comment by earthlng** [comment]
> and also the 8 sites I allow permanent cookies - those cookies were created months ago

"more than one cookie **with the same name** " ! ie `wam-temp-cookie`

> Also, what is the answer on the web accessible resources - does this reveal the UUID?

the latest version on github doesn't have the web accessible resources anymore.

ps the login issues should be fixed in version 0.9.2 as well

**Comment by Thorin-Oakenpants** [comment]
> more than one cookie with the same name " ! ie wam-temp-cookie

Well, I assumed if it tries to set a cookie for the domain, it will follow the same rules eg containerId, FPI etc and would thus be the same name - if it's setting a different name then why mention same names? Totally confusing me.

I do not understand this cookie thing now. Under who's quota manager is this cookie?

**Comment by earthlng** [comment]
the addon is adding an additional cookie to the response header and therefore the cookie will get the same FPI etc as if the site itself set it. Why mention same names? because I (or a site) can set a specially crafted cookie which perhaps can overwrite the addon's rules. I haven't tested it yet because I don't think I will use this extension anyway. Just throwing ideas out there in case someone else wants to do some testing.

**Comment by atomGit** [comment]
if this is what it takes to offer a semblance of privacy, it simply is not worth it IMO

another ext. that offers similar functionality is [http-useragent-cleaner](https://addons.mozilla.org/en-US/firefox/addon/http-useragent-cleaner/) - i used to use it and i wrote an EN manual for it - what a f'n joke - the ego-laden dev is impossible to deal with

if you have to configure stuff on this kind of granular level, it's hardly worth browsing the www - you'll spend more time un-breaking shit than actually reading the sites content

just dealing with uM and uBO is enough of a hassle IMO - more layers just add to the hassle

**Comment by Thorin-Oakenpants** [comment]
It certainly is a much more sophisticated attempt at control - if 10 of these 74 items were of "real benefit" (i.e not already covered but could make a lot of difference) and they were presented in the same way uM/uBo are (i.e a default deny-all and grid/matrix to click green per domain) then I could see it being useful - eg indexedDB allowed on a granular level.

Nothing wrong looking at the breakdown and seeing what could tor could not be useful, or lead to other avenues - but yeah, this is something I would maybe use on say TBB (but it needs more evaluation)

**Comment by snyderp** [comment]
@2glops Just pinging you on this b/c I had a hell of a time working out the issue with the login issue.  The most recent commit (and what I'll be pushing as a .9.2 w/in 24 hrs) should have fixed it.  I'm all but certain its a FF issue (specifically a bug in how their webExtension#webRequests implementation handles adding additional Set-Cookie headers, which seems to cause previous Set-Cookie headers to be coalesced incorrectly…)

Anyway, if you're still interested in the extension and end up using 0.9.2, and could let me know if you're still seeing the issue, I'd appreciate it a ton :)

**Comment by snyderp** [comment]
Also, re: the discussion about configuring this thing is a pain in the butt

I completely agree :)

The goal is to have a possible EasyList/ABP/etc subscription style service set up for it before a 1.0 release.  Fingers crossed…

**Comment by crssi** [comment]
My guts/balls/6th sense is telling me tho WE have a lot of potential.
@snyderp nice job

**Comment by 2glops** [comment]
@snyderp 
Good, update 0.9.2 solve the login issue on FF56 / Linux

**Comment by atomGit** [comment]
> if 10 of these 74 items were of "real benefit" (i.e not already covered but could make a lot of difference) and they were presented in the same way uM/uBo are (i.e a default deny-all and grid/matrix to click green per domain) then I could see it being useful

agreed - as @crssi said, i think there's a lot of potential here but i (and i'm sure others) am not keen on messing with yet another ext. in addition to uM, uBO, etc. - i think if it could essentially cover the same functionality that they do and wrap it all into a single ext., then bingo - i guess it would almost have to use the existing blocklists since there's so many out there

maybe WebAPI Manager already does cover the basic functionality of uBO/uM - i don't know - much of the stuff it does is over my head

**Comment by snyderp** [comment]
FWIW, from a high level, the way to think about this project vs. things like uBO, uM, NoScript etc, is that those tools control who's code can execute on your machine.  WebAPI Manager controls *what* code can do.

From my perspective, the approaches that these other extensions (along with Ghostery, PrivacyBadger, etc.) take is useful in the common case, but (for most categories) easily circumvented by an attacker / ad company / etc.  

My approach is to constrain the capabilities of code, regardless of the origin of the script.

Hope that helps :)

**Comment by Atavic** [comment]
Sure! That's what is written in the 3rd pdf [here](https://github.com/snyderp/web-api-manager#background-1), specifically @chapter: *7.2 Blocked Browser Features*

**Comment by Atavic** [comment]
Sure!
That's what is written in the 3rd pdf [here](https://github.com/snyderp/web-api-manager#background-1), specifically chapter: *7.2 Blocked Browser Features*

**Comment by Thorin-Oakenpants** [comment]
Just to elaborate ... I would use this in my everyday main FF (after evaluation how much could be used) - I get the argument that for most users this is just toooooo much - but I treat my main FF as pretty much "hardened" - and it works for my 500 odd sites I visit (i.e configured to work under default-deny: NS, uBo, uM, and the user.js as is, etc). Adding WAM with say 20 or so APIs at default-deny and whitelisting so my 500 odd sites still work is no big deal in my book. It's a one-off job.

Sites not in my 500 I use - most work OK to grab info (text) and others I just use another browser (opera, chrome) or when I get my A into G (a diff FF profile)

I like this approach: a method where rather than a global switch (prefs) it's granular. Loads of potential - thanks @snyderp . What is probably hardest about this ATM for end users is understanding it, and this is where some nice groupings could come in handy, and more info (eg tooltext on info icons)

eg:

* Level1 (minimal impact)
  * Battery
  * Beacon
  * DeviceOrientation Event Specification
  * Sensors
* Level2 (slight breakage / annoyance)
  * Fullscreen API
* Level5 (common breakage)
  * Encrypted Media Extensions
* Level 10 (prepare to die)
  * DOM
  * HTML

**Comment by publicarray** [comment]
@snyderp are you aware that the blocking is bypassed on https://browserleaks.com/javascript? click on `iframe.contentWindow` at the top ( only `DOM`, `DOM Level 1`, `DOM Level 2: Core` and `DOM Level 2: Events` needs to be enabled)

**Comment by psnyde2** [comment]
@publicarray Very interesting, no I did not know about this!  I should be able to easily extend the blocking technique to this point as well, but its surprising to find out they don't actually share the same view of the DOM.   Thank you for the point!

If you could open an issue on the extension, that would be extremely helpful.   Otherwise, I'll do so when I'm back at the keyboard in a while.

Thanks for the find 👍

**Comment by atomGit** [comment]
anybody try this thing with google/maps? i couldn't get earth view to work with all filters disabled - i had to disable the extension

this is with the ghacks config with...
```
webgl.disabled = false
webgl.disable-extensions = false
webgl.min_capability_mode = false
```
... all of which break earth view according to my tests

dunno if you guys use earth view, but to activate it you apparently need to click on something on the map that will produce a thumbnail image, like a street, then click on the thumbnail, then zoom out using the scroll wheel - this should get you there, all you need to do is try zooming out: https://tinyurl.com/y8tro8c3

i'll open a ticket on the WebAPI Manager page if we think the problem is on that end

**Comment by psnyde2** [comment]
@atomGit Hmm, interesting, possible another bug, though things seem to be working for me.  I'm visiting www.google.com/maps with the following settings blocked:

`["Ambient Light Sensor API", "Battery Status API", "Beacon", "Geolocation API", "Geometry…", "Gamepad", "SVG", "Web Audio", "WebGL", "WebVTT"]`

Can you make sure you're using the 0.9.3 version (which fixed some relevant CSP issues), and if you're still seeing problems, please open an issue?  I'll make sure to get things straightened out ASAP.  Thanks!

**Comment by snyderp** [comment]
@publicarray Thank you again for raising this.  I've added it as [issue 20](https://github.com/snyderp/web-api-manager/issues/20) and will get it sorted out right away

**Comment by B00ze64** [comment]
@snyderp 

> Also, re: the discussion about configuring this thing is a pain in the butt, I completely agree :) The goal is to have a possible EasyList/ABP/etc subscription style service set up for it before a 1.0 release. Fingers crossed…

What I don't understand is why we can't just select all the things we want disabled all the time, and then on a per-site basis re-enable some stuff. Why do we have to chose between your pre-defined sets of rules? I haven't tried the extension yet because I'm still on FF52, but from what I understand, we must chose between Conservative and Aggressive and then adjust each website based on how different we need to be from these 2 sets of rules. Why not let *me* decide the base set? Seriously, what if your base set disables something I want enabled most of the time? Am I going to edit every single website I visit to re-enable this? It would be much better if I could decide what the baseline is...

Regards,

**Comment by snyderp** [comment]
@B00ze64 Oh, I think there is some misunderstanding. You for sure can set all the standards to be disabled in the "(default)" case.  The "Lite" / "Standard" / "Aggressive" cases are just conveniences.  There is nothing stopping you from doing what you describe (there just isn't a one button, pre-configuration setting for it currently).  

Does that address you concern?  If I'm still misunderstanding, please let me know!

**Comment by Thorin-Oakenpants** [comment]
@B00ze64 The "presets" are just that - quick click presets (clear all, select all, conservative, aggressive) which auto-select/auto-clear .. you can still change selections <= global default settings

My understanding of `EasyList/ABP/etc subscription style service` is for domain specific rulesets <== overrides to reduce breakage

**Comment by B00ze64** [comment]
@snyderp @Thorin-Oakenpants Oh! I'm sorry, my bad. I can't test the extension, so I didn't get it. That AddOn is on my "AddOns to get once I upgrade FF" because it controls some stuff that I am currently forced to enable globally (e.g. beacons (eBay breaks for me without this)). It will be nice to be able to control things on a per-site basis. Thanks!

**Comment by atomGit** [comment]
@psnyde2 - yes, i'm using 0.9.3

visiting google.com/maps alone won't reveal the issue i discovered - you have to get into "earth view" specifically which is different than satellite view

if you use the URL i provided (https://tinyurl.com/y8tro8c3) that should get you into "street view" - from there, you have to use the mouse wheel and scroll backwards (zoom out in other words) and after about 2-3 clicks of the scroll wheel, your view should change noticeably to where you can move around with the arrow keys, the mouse (drag) and the Shift key just like you would see if you were running google earth locally

make sure these are "false"...

```
webgl.disabled = false
webgl.disable-extensions = false
webgl.min_capability_mode = false
```
... and if you cannot enable earth view, then disable WebAPI, reload the map page and try again - this time you should be able to zoom out to activate earth view

just so you understand the diff, with street view you are limited to where you can go on the map according to where google sent their mapping vehicles (the roads and, in some cases, locations photographed with hand-held cameras) whereas with earth view, you can 'fly' anywhere you want without being restricted by roads or altitude - in street view the mouse wheel zooms, but your location never changes - in earth view the mouse wheel moves your position

**Comment by snyderp** [comment]
@atomGit Ah, I am able to see the issue now.  Thank you for the detailed description :)

As of `0.9.6` though, this shouldn't be an issue anymore.  If you have an empty blocking configuration for the domain, then all extension functionality will be disabled for those domains.

So, if you allow all the standards on google.com now, you can get back to satellite view again (while still having the extension blocking for other domains).

Thanks again and hope that helps!

**Comment by Thorin-Oakenpants** [comment]
Added WebAPI Manager to the wiki extension sticky. Closing this. Issues with the Extension are best handled at right repo - but defintitely keeping an eye on this - thanks @snyderp :kiss: - I have it installed (disabled) to remind me (as well as out sticky topic), and I have your repo starred - can't wait until it doesn't need a temp cookie, and the UI interface becomes more mature/informative (not that **we** needs it, but to expand it's user base).
