### ISSUE TITLE
proposal: set 4503 `*block_mozAddonManager` to active

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#259]
privacy.resistFingerprinting.block_mozAddonManager which landed in FF57 will allow uBlock Origin (and other extensions) to work on zilla's three protected hard-coded domains, the only one we really care about is AMO itself (godamn GA) - the downside is that AMO will **always** get your spoofed UA from RFP. Personally this is not a big deal
- there is no guarantee yet that the new AMO will use the mozAddonManager
- come 57, its all WE anyway and breakage within WE is likely to be rare (but of course extension devs can set min FF version numbers as APIs open up)
- its no big deal to just download the file as an xpi and install if from local

I guess someone better test it first. **Anyone running 57/58 with uBo?** Just implement a cosmetic filter to detect the diff (or block GA and sniff your traffic)

**Comment by earthlng** [comment]
> to work on zilla's three protected hard-coded domains

I'm pretty sure that's **not** what this pref does.

> AMO will always get your spoofed UA from RFP

because of this I think keeping the pref inactive is better for most people

**Comment by Thorin-Oakenpants** [comment]
I think you are misunderstanding what I am proposing this for

**Comment by earthlng** [comment]
> I am proposing this so AMO is no longer protected from extensions

and I am saying that this is not what this pref does :)

**Comment by Thorin-Oakenpants** [comment]
> I guess someone better test it first

Which is why I said the above. The reason I mentioned this whole thing at all is that in a bugzilla it was mentioned that this was a workaround (side-effect) and someone else confirmed it (or at least no-one disputed it)

**Comment by Atavic** [comment]
[This](https://bugzilla.mozilla.org/show_bug.cgi?id=1384330#c16) one?

>its no big deal to just download the file as an xpi and install if from local

Yep, that's me! I do that for security reasons, as if someone gets a malicious extension, there's a possible problem: https://bugzilla.redhat.com/show_bug.cgi?id=1395101

**Comment by Thorin-Oakenpants** [comment]
> This one?

No. It was comment in an (somewhat unrelated?) ticket where it was to bypass the restriction (it was about AMO and scripts or something) you could use that pref

**Comment by Thorin-Oakenpants** [comment]
https://www.reddit.com/r/firefox/comments/792209/psa_use_hidden_pref/

Well .. soooo glad I brought this up over a week ago - https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c24  & comment 25. Thank for all the doubters :burn-the-heretics:

**Comment by Thorin-Oakenpants** [comment]
geee .. join the party ... https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/

**Comment by earthlng** [comment]
ok you were right, I was wrong, sorry for doubting you :)
Up to you if you want to make it active. IMO inactive is fine because users need to understand what the pros and cons are and then make the decision themselves.

> the downside is that AMO will always get your spoofed UA from RFP. 

the upside is that you can use an extension to send the real UA to AMO.

**Comment by Thorin-Oakenpants** [comment]
UA - I have not tested with any extensions, does an extension override RFP? i.e does it inject it's changes after RFP looks up its bits?

The upside is that AMO will now be treated like any other page. I am not worried about AMO tracking, and at the end of the day - 1 site & GA (first party isolated) is not a big deal. I am not even sure GA gets anything because FF blocks all cookies by default - or use a site block exception). But I will be glad I can remove some elements via uBo picker.

The downside is, and I need to check, that some protections for AMO are now removed - something about injected scripts can now cause silent extension installs. I am not 100% convinced of this

from https://www.reddit.com/r/firefox/comments/792209/psa_use_hidden_pref/

> AMO has permissions to install add-ons without the permission prompt (regardless of the pref enabled), and since WE now have access to AMO, they can take advantage of that to silently install malicious add-ons.
> 
> There's a loophole in this pref that gives WebExtensions access to mozAddonManager. Add-ons can register a Service Worker that makes use of mozAddonManager, then once that pref is turned off, the add-on has full access mozAddonManager.

So... a user must be on AMO, and another WE you have installed needs to be rogue, and service workers must be enabled. [As for his FP'ing downside - there is none (it is AMO only) - if you have a rogue extension you have bigger issues]

---
What to do ... I think I will leave the pref inactive (security trumps privacy in general), but add some more info (personally I will flip this in 57). If it's good enough for TBB ... but I want to check the security claims

**Comment by earthlng** [comment]
Thanks for the quotes. I think the first part can be easily disabled by setting `permissions.manager.defaultsUrl` to an empty string. I actually suggested to set this a long time ago. The 2nd part sounds like a pretty serious bug to me. so, extensions can know and possibly change information about other installed extensions? anything else that's possibly worse? It kind of doesn't matter whether it can change information in the mozAddonManager because with the pref enabled it's never used anywhere anyway, right? I can't quite wrap my head around the potential problems tbh other than information leakage about installed extensions.

**Comment by Thorin-Oakenpants** [comment]
The current value in 56 is `resource://app/defaults/permissions`. I don't exactly follow what this "permissions" thing is. If it is set to blank, does this affect manually installing from AMO (I assume not, as I can still install from places like github), and does it affect manually updating via addons panel? Where do we put it and how do we word it?

```
/* xxxx: remove default permissions **blah blah** (FF35+)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=506446
 * [2] https://dxr.mozilla.org/mozilla-central/source/browser/app/permissions ***/
user_pref("permissions.manager.defaultsUrl", "");
```

**Comment by earthlng** [comment]
> does this affect manually installing from AMO

no, I have the pref set to blank for a while and can still install from AMO. I think all it does is show a prompt instead of silently allowing it to install.

> and does it affect manually updating via addons panel? 

nope

> Where do we put it and how do we word it?

2600 as something like "xxxx: remove special permissions for certain mozilla domains". I don't think we need link [1] and instead of [2] maybe directly linking to `resource://app/defaults/permissions` would be better because it shows the permissions for your current FF version instead of the one for the latest nightly.

**Comment by Thorin-Oakenpants** [comment]
^^ sounds good to me - feel free to do a direct commit

**Comment by earthlng** [comment]
yes it can be loaded in FF58.

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1406795 - didn't link to this earlier, but seems Zilla aren't concerned about the (possible) privilege escalation
