### ISSUE TITLE
browser.xul.error_pages.expert_bad_cert

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#26]
write up a pull-request to set this one to true and give props to @crssi

**Comment by earthlng** [comment]
@Roman-Nopantski can you give @crssi some kind of membership? He helps out a lot.
No write-access, just so everyone knows he's a part of this and to make his name show up when I type an @

**Comment by Roman-Nopantski** [comment]
@crssi - you've been invited as a collaborator, appreciate it thanks

@earthlng - what's the benefit/ of this enhancement, what does it doe exactly? Need more info/discussion before a pull.

**Comment by earthlng** [comment]
@Roman-Nopantski https://github.com/ghacksuserjs/ghacks-user.js/issues/10#issuecomment-281733579

**Comment by crssi** [comment]
Guys, I have much to learn. Now I have to find out what "collaborator" mean. Until I get shot for that, I guess its fine. lol

**Comment by earthlng** [comment]
I wanted to title the pref as something like "blabla on **Insecure Connection** warning pages".
To make sure that's correct, I clicked all insecure links on badssl.com, and turns out it's not 100% correct.
There's one exception with HSTS:

https://subdomain.preloaded-hsts.badssl.com/
_This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. **As a result, it is not possible to add an exception for this certificate.**_

In those cases the pref doesn't display the advanced info.

Damn, now I have to incorporate that somehow :(

```
// 12xx: display Advanced information on Insecure Connection warning pages (thanks @crssi)
   // only works when it's possible to add an exception, fe. doesn't work for HSTS (https://subdomain.preloaded-hsts.badssl.com/)
   // testpage: https://expired.badssl.com/
user_pref("browser.xul.error_pages.expert_bad_cert", true);
```

@Roman-Nopantski how is that?

**Comment by Roman-Nopantski** [comment]
Thanks @crssi

**Comment by Roman-Nopantski** [comment]
For those who are wondering, the extra information is the white box section (I am using FT DeepDark Theme, normally the whole page would be white)
![insecure_connection_-_2017-02-24_05 32 15](https://cloud.githubusercontent.com/assets/16656956/23269217/b0c66e88-fa54-11e6-834c-9f620a4f052b.png)

**Comment by earthlng** [comment]
Thanks for committing it for me.
