### ISSUE TITLE
[wiki] search engines

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#261]
apparently i don't have permission to edit the wiki and that's perfectly fine, but...

over here...
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Search-Engines
and over here...
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2-Sanitizing

this link...
`http://12bytes.org/articles/tech/firefox-search-engine-cautions-and-recommendations`

should be changed to this...
`http://12bytes.org/tech/firefox-search-engine-cautions-and-recommendations`

also i see a placeholder "Search Engines" at `/wiki/4.1-Search-Engines` - you can check this out and see if you want to link to it (i just broke the alternative engines out of the firefox-search-engine-cautions-and-recommendations article and gave it its own page)

Alternative Search Engines That Respect Your Privacy
`http://12bytes.org/tech/alternative-search-engines-that-respect-your-privacy`

**Comment by earthlng** [comment]
Thanks, I've updated the link in 4.1 + 4.2. Pants can decide about linking to your Search Engines article.

**Comment by Thorin-Oakenpants** [comment]
done

**Comment by crssi** [comment]
@atomGit You really have great and complete articles. 👍

**Comment by atomGit** [comment]
thanks :)
