### ISSUE TITLE
Its A Trap! Blocked test is not very informative [if blocking is in place]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#263]
@fmarier

Using the links (all HTTPS) in the Wiki Test Pages [Mozilla section](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites#small_orange_diamond-mozillas-safe-browsing-tracking-protection), I got the following

![its-a-trap](https://user-images.githubusercontent.com/16656956/32404219-a0853cba-c1b0-11e7-9bce-a03afa82649b.png)

Same order as tabs in pic, Attack, Malware and Phishing (all three work fine), Tracking (all good: diff theme, i.e not scary red, but note it's missing a favicon) .. and Block loads a blank page. I loaded the page in Opera - it loads a similarly themed page to the Tracking one (and no favicon)

> I'm naughty Web content ... OK, not really, but Firefox can be configured to block certain content. If that feature is enabled in your browser and you are using Firefox 48 or later, you should have seen a blank page instead of this one.

User's have no idea if its working or not, because the page is blocked, so you can't tell them - catch 22. Is there any way to make this better - such as

:bulb: make the blocking landing page NOT blocked ( blocked.html ) and explain it (as per existing) but provide a TEST link to a secondary page ( eg blocked-test.html )

**Comment by fmarier** [comment]
Yeah, that test page could be better.

> 💡 make the blocking landing page NOT blocked ( blocked.html ) and explain it (as per existing) but provide a TEST link to a secondary page ( eg blocked-test.html )

That's a good idea. Instead of a link, we could also iframe the blocked page and on the top-level page say something to the effect that the iframe should be empty.

It's not going to be a huge priority because only very advanced users (such as anybody watching this repo) is ever likely to encounter this page, but feel free to open a bug on <https://github.com/mozilla/itisatrap>. This is definitely a P5, not a WONTFIX :)

**Comment by Thorin-Oakenpants** [comment]
I'll reproduce this issue in your repo later. As for iframes, not everyone allows iframes - else I would have suggested that there be a single test page with five iframes for the five tests. In fact I like this better.

Keep the original five pages, but add a `https://itisatrap.org/firefox/its-a-test.html` :)
