### ISSUE TITLE
WebExtension to clear Flash LSO

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#268]
Flash is not used nearly as much these days, but if anyone is using it, and wants an extension to clear Flash LSO, here is one that was just released:

https://github.com/cpeterso/clear-flash-cookies/

It doesn't actually delete the LSO on exit, but does it when the browser is opened (not ideal, but may be better than nothing).  See https://github.com/cpeterso/clear-flash-cookies/blob/master/src/background.js

**Comment by Thorin-Oakenpants** [comment]
> And that's what Flash is, the Queen of Refuse. So bow down to her if you want, bow to her. Bow to the Queen of Slime, the Queen of Filth, the Queen of Putrescence. Boo. Boo. Rubbish. Filth. Slime. Muck. Boo. Boo. Boo.  <sup>[source](http://www.imdb.com/character/ch0003796/quotes)</sup>

:grin:

**Comment by Thorin-Oakenpants** [comment]
in case that's not clear .. screw Flash :-1:  and in no way do I want to encourage it, sorry Gitoffthelawn - I still love ya man, don't be upset at me .. mkay?

**Comment by Gitoffthelawn** [comment]
Ya, I feel the same way about flash... just posted the extension if someone had to use Flash.

Oh, and don't worry, I still love you too!  ❤️
