### ISSUE TITLE
What about some Android prefs and testing? huh! :) 

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#27]
Is someone testing this on android? I have no android devices. I looked at recent watchers here and they seem into android repos.

https://github.com/pyllyukko/user.js/issues/14

**Comment by earthlng** [comment]
I have an android but browsing on that thing is a fucking joke. I don't understand how people can do it.
Hardening a mobile browser is futile anyway with all the built-in tracking.

**Comment by Roman-Nopantski** [comment]
From the user.js: "* FF version: 51 (DESKTOP)". This was primarily based on widows desktop users.

**Comment by Atavic** [comment]
Addon to try on Android: https://addons.mozilla.org/En-us/firefox/addon/fake-location/
Geo Test: http://html5demos.com/geo

**Comment by Atavic** [comment]
https://github.com/nylira/prism-break/issues/1608#issuecomment-262653552

**Comment by Roman-Nopantski** [comment]
Closing this - if and when we come across a useful android-specific pref, then we sill simply denote it as android only. In 2+ years, I have yet to come across any.

**Comment by bogachenko** [comment]
![15437492427090](https://user-images.githubusercontent.com/8535285/49484362-db1baf00-f88a-11e8-9edc-4ba0ee4c5a0c.png)

**Comment by Thorin-Oakenpants** [comment]
@bogachenko I don't know what that says. If you have any specific Android prefs that you think might be useful, open a new issue.

**Comment by bogachenko** [comment]
@Thorin-Oakenpants No .. this is just a screenshot, as proof, or something.
I gave the file rights and everything works.
