### ISSUE TITLE
Enable the DNT header

### ISSUE THREAD

**Issue by Exodion** [ghacksuserjs/ghacks-user.js#270]
It is true that most sites do not honor the DNT header but that is not the problem. When I test myself on [Panopticlick](https://panopticlick.eff.org/) using my hardened Firefox profile with DNT enabled, this is what I get.

![true](https://user-images.githubusercontent.com/31079484/32746312-4af2b76a-c8c6-11e7-8637-0c4f177ca9e6.png)

But when using a fresh new profile with DNT disabled the results are different.

![false](https://user-images.githubusercontent.com/31079484/32746415-a18acae0-c8c6-11e7-9e40-db7ffd9de8ae.png)

I know it's not a big difference but what do you guys think? Should we perhaps enable the DNT header?

**Comment by Atavic** [comment]
Previous: https://github.com/ghacksuserjs/ghacks-user.js/issues/163

DNT doesn't work. The DNT header easies your browser's fingerprint.  It has been abandoned, bugzilla has the latest discussions from 4 years ago. Your panoptclick results are reasonable IMHO

**Comment by Thorin-Oakenpants** [comment]
The data is flawed. 1. it has years of old date 2. it is not a big enough data set 3. it is tainted by the type of people who use it (privacy conscious) 4. it is tainted by repeat visitors (come on, who here hasn't smashed their browser at it a couple dozen times 5. it is not real world or real time

I am not sure if the FF telemetry page lets you pull out DNT figures for normal windows (private mode no data is collected) - https://telemetry.mozilla.org/ - you can pull out some whacky stuff

We went thru this in an issue recently. Oh as I type there is Atavic with #163 . read that and the descriptions for the two prefs.
