### ISSUE TITLE
Changes in telemetry for Firefox 58+

### ISSUE THREAD

**Issue by ArchangeGabriel** [ghacksuserjs/ghacks-user.js#271]
See https://medium.com/georg-fritzsche/data-preference-changes-in-firefox-58-2d5df9c428b5.

**Comment by Thorin-Oakenpants** [comment]
cheers - seen that. If the pref is deprecated we'll pick up on it diffs

**Comment by earthlng** [comment]
It won't be deprecated, they'll **lock** it!

**Comment by Thorin-Oakenpants** [comment]
^^ Is that you Appster?

**Comment by ArchangeGabriel** [comment]
They already have on Nightly, I expect the new 58 beta/dev to be affected already.

Apparently though, on release the pref should be locked to off.

**Comment by earthlng** [comment]
> ^^ Is that you Appster?

??!!??!! ...

> toolkit.telemetry.enabled: This preference is now **locked** to reflect prerelease or release builds (true and false respectively).

**Comment by ArchangeGabriel** [comment]
It surfaces at the top of `about:config`, in italics. `Status` is `locked`.

**Comment by Thorin-Oakenpants** [comment]
so `user_pref("toolkit.telemetry.enabled", false);` will be locked to false in stable? Is that what you're saying?

I said something would be deprecated, well - there are two checkboxes (send data, now there will be one - so probably something will go, maybe not immediately - probably `toolkit.telemetry.unified` - but nvm, 58 is next year

**Comment by ArchangeGabriel** [comment]
Yes, that’s what I’m saying. As well as @earthlng quote above.

**Comment by Gambit78** [comment]
Just great. What should I do now? I do not accept any telemetry (spying). Mozilla what are you doing?

**Comment by ArchangeGabriel** [comment]
Normally telemetry should not be sent anywhere, just collected locally (but that’s an issue, I agree — at the very least because it impacts performance). You should verify that `datareporting.healthreport.uploadEnabled` is set to `false`.

**Comment by Thorin-Oakenpants** [comment]
> Just great. What should I do now? I do not accept any telemetry (spying). Mozilla what are you doing?

Well, if it doesn't *know* where to send it.... see user_pref("toolkit.telemetry.server", "");  .. of course we would want to make sure that this is the value used and it's not hardcoded

**Comment by KOLANICH** [comment]
I just leave this link here: https://dxr.mozilla.org/mozilla-central/source/modules/libpref/Preferences.cpp#3213

**Comment by Thorin-Oakenpants** [comment]
I don't follow. What is the significance of this? Is this some change in Nightly that just happened? Got a bugzilla?

**Comment by earthlng** [comment]
FYI nightly and beta users can still use autoconfig to lock the telemetry pref to `false`

**Comment by KOLANICH** [comment]
@earthlng Thank you for the info, I have never heard about this feature before.

**Comment by Thorin-Oakenpants** [comment]
maybe we should add that to the user.js

`0330` (current)
```
 * [NOTE] FF58+ `toolkit.telemetry.enabled` is now LOCKED to reflect prerelease
 * or release builds (true and false respectively), see [2]
```

to maybe something like
```
 * [NOTE] FF58+ `toolkit.telemetry.enabled` is locked true in prerelease builds, see [2]
 * Nightly and beta users can still use autoconfig to lock the telemetry pref to false
```

**Comment by KOLANICH** [comment]
That works. Thank you.
