### ISSUE TITLE
Homepage setting

### ISSUE THREAD

**Issue by RoxKilly** [ghacksuserjs/ghacks-user.js#277]
While trying to figure out where in the settings I should add this rule:
```
user_pref("browser.startup.homepage", "https://example.com");
```
I figured the best place would be the `5000: PERSONAL SETTINGS` section, which is described as
> Settings that are handy to migrate and/or are not in the Options interface. Users can put their own non-security/privacy/fingerprinting/tracking stuff here

But since no existing sub-section seems to fit, I am unsure where to appropriately insert this setting.  I ended up creating a section `5099` figuring I would decrement to 5098... for each new personal setting that has no home. This feels wrong since eventually there will be conflict with official section numbering

Has there been discussion on adding a commented-out setting for the homepage?

**Comment by earthlng** [comment]
`browser.startup.homepage` is mentioned in 0102.
Pants said he doesn't want to mess with people's homepage and that's why it's not in the user.js as a (commented-out) pref.
