### ISSUE TITLE
FF version detection on AMO broken

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#278]
Hi guys. My projects are killing me, almost no time for anything else. :(
IDK if someone already mentioned it here, but in case it didn't, here we go:

I have noticed that `/* 4501  */ user_pref("privacy.resistFingerprinting", true);` prevents AMO to detect Firefox version, at least version 57.

On FF 57 visit, for example, [Cookie AutoDelete AMO page](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/).
You will be unable to install that addon with a notice on that page: _This add-on requires a newer version of Firefox (at least version 56.0). You are using Firefox 52.0._

Change `privacy.resistFingerprinting` to `false` and revisit/reload CAD AMO page.
Now you will be able to install it.

Maybe, this should be mentioned on Wiki.

Cheers

**Comment by earthlng** [comment]
Hi, yes we are aware of it. There are 2 ways around this atm:
1. temporarily disable privacy.resistFingerprinting to install new addons from AMO
2. set `privacy.resistFingerprinting.block_mozAddonManager` to `true` and use an addon that can modify headers for certain websites, and configure it to send your real User-Agent for addons.mozilla.org.
If you don't set that pref to true WEs won't be able to modify headers on the restricted domain addons.mozilla.org (and they won't be able to inject content-scripts to modify the site either, fe. try to block an element with uBO - it won't work unless you change that pref to true)

**Comment by 2glops** [comment]
You could also save the xpi file and install the addon manually

**Comment by earthlng** [comment]
Damn! I totally forgot about the simplest solution lol. Thanks @2glops 

> **Cannot see the forest for the trees**
> 
> To say the idiom "cannot see the forest for the trees" means that a person cannot see the big picture because the focus is too much on the details.

I think I need a break. Wake me up when ESR52 is EOL xD

**Comment by fmarier** [comment]
To add to what @2glops said, if you want to install [SuperStop](https://addons.mozilla.org/en-US/firefox/addon/superstop/), for example:

1. Click on the ["See all versions"](https://addons.mozilla.org/en-US/firefox/addon/superstop/versions/).
2. Click on ["Download Anyway"](https://addons.mozilla.org/firefox/downloads/file/765133/type:attachment/superstop-0.2-an+fx.xpi?src=version-history) next to "Version 0.2".
3. When prompted, choose to open the file using Firefox instead of saving it to disk.

**Comment by crssi** [comment]
Thx @fmarier, obviously there is even simplest solution. :)

**Comment by claustromaniac** [comment]
I simply right click on the greyed-out "+ Add to Firefox" button, then I click on Copy Link Location and paste in the address bar.

**Comment by Thorin-Oakenpants** [comment]
All I've been doing is downloading from the version section same as Francois. This AMO needing a whitelisting (or other mechanism to version detect) was brought up ***over 10 months ago*** - someone should give that guy a medal, or a job

[source](https://bugzilla.mozilla.org/show_bug.cgi?id=1333933#c2)
>  a built-in whitelist should be considered, eg mozilla AMO
