### ISSUE TITLE
JS problem?

### ISSUE THREAD

**Issue by Virusrud** [ghacksuserjs/ghacks-user.js#279]
Hello,

first a big THANK YOU for the great work! Really!

I have a big problem with java, I guess. I tried now for over 5 hours to get it to work but I don`t find a solution. I have FF 57 installed. My problem is, when I login into my web.de account I can not open one of my mails which are listed left beside the window where the content of my mails are shown. When I hover over the mail the box gets blue and the date disapears but when I click on it nothing happens. Normally the date disappears and three little logos come up (spam logo, trash logo, etc.) but in my case no logo comes up. All other things work fine like to select the different folders on the left side etc...

On a another website I had a similar problem. There I should click on man or woman, but it was not possible.

I tried to adjust several things in the user.js but nothing helps! For real! I read a lot of things (5 hours) and nothing worked! I investigate what kind of box this is and it is a js-box. Thats because I think I have a problem with javascript...

I am sorry for my bad english (Iam not a native speaker) and for the bad explaination of my problem (I am not an IT Guru).

Thank you all in advance for your help!

**Comment by Atavic** [comment]
See: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

Try changing:
// user_pref("dom.indexedDB.enabled", false);
// user_pref("browser.privatebrowsing.autostart", true);

**Comment by crssi** [comment]
Just commenting out will not help.

I am sure @Atavic meant to change it to:
`user_pref("dom.indexedDB.enabled", true);`
`user_pref("browser.privatebrowsing.autostart", false;`

cheers

**Comment by Virusrud** [comment]
A big thank you to both of you for the help! I deleted FF completely and tried it with the portable version of FF and followed the instructions of the link you gave me @Atavic ;)

It works very fine! Thanks a lot!!! Now I just have to find out how I can change the UA and the difference between the local- and systemtime and then I am completely happy 💃
