### ISSUE TITLE
Change timezone from UTC to CET

### ISSUE THREAD

**Issue by Virusrud** [ghacksuserjs/ghacks-user.js#280]
Hello,
I try to change the system timezone from UTC 0 to CET +1. I already change the line under 4500 from "** 1330890 - spoof timezone as UTC 0 (FF55+)" to "** 1330890 - spoof timezone as CET +1 (FF55+)" but this does not work.

I want to change that because whoer.net says that it is a minor remark for my anonymity, which is clear because it is conspicuous that my browser has two different timezones (system - local).

I of course looked up the problem here and all I found to my topic was this, which was not really helpfull and the last entry was on September:
https://github.com/ghacksuserjs/ghacks-user.js/issues/230

Thank you in advance for your help! ;)

**Comment by Virusrud** [comment]
Thanks for your fast reply!

But when I do that all, other settings which are tabled under 4500 are obsolete too or not? Like the window size and spoofing the networkinformation API etc.

Is it that complicated to change the timesettings from UTC to CET? Which part of the code or which file is responsible for displaying the system time?

**Comment by earthlng** [comment]
> But when I do that, all other settings which are listed under 4500 are obsolete too or not?

Yes it's all-or-nothing.

**Comment by Virusrud** [comment]
Better all than nothing ;) Thanks a lot for your help!
