### ISSUE TITLE
Task: wiki page on updater scripts

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#283]
- [x] complete updater scripts to required standard
   * Updater.bat v3.0 FINAL :tada:
- [x] does the mac version need finalizing?
   * No, it does the "downloading + appending" part but doesn't support multiple .js files or any of the other parameters that the Windows version has.
- [x] rearrange wiki pages to make more sense
- [x] update user.js readme header 
- [x] rewrite bulk pref resetting wiki - add in prefsCleaner bat
- [x] rewrite wiki page on extra .js file(s)
- [x] write updater scripts page

**Comment by earthlng** [comment]
I wrote a HOWTO for the Windows version to which we can link in the wiki to keep that nice and short.
As the person in charge now, I delegate the updating of the Wiki and the other tasks to Lady Thorina of House Oakenpants. When finished, report to my quarters for debriefing and nightly duties, sincerest your Sir Earthling of House Terra

**Comment by Thorin-Oakenpants** [comment]
>  to which we can link in the wik

Wondered why you used a new issue. Looks good. But it **must** be in the wiki. I will re-arrange the wiki numbering and create a new page for windows updater and one for mac/linux (unless you think we can combine them) eg (off the top of my head, just bouncing ideas)

### Getting Started
* 1.1 - 1.4
* 1.5 - Setting Extension Permissions

### Updating, Maintenance
* 1.7 - Bulk Pref Resetting [Scratchpad]
* 1.8 - Updating (stuff about keeping your overrides in separate files)
   * 1.8a - old method up to ff58 (eventually we can strikethru it when ESR59 lands)
   * 1.8b - windows
   * 1.8c - mac/linux

### How To
* 2.1 etc

**Comment by earthlng** [comment]
I'd keep the wiki short and just link to this issue.

**Comment by Thorin-Oakenpants** [comment]
I think you mean the other issue you created, not this one. But nah, the info should be in one location (wiki), not two (wiki + issues). You'll see. I'm not in any hurry, I have other things to deal with. As long as I get it done before FF58 stable lands

**Comment by earthlng** [comment]
Look, the wiki is already way too confusing with too much text, even for the ones who actually try to read it. Lets try to keep it relevant and short, with links to "more details" for the people that it concerns:
for example:

> - Follow our easy, succinct [changelogs](https://github.com/ghacksuserjs/ghacks-user.js/search?q=label%3Achangelog&type=Issues&utf8=✓) to discover new items and changes
> - Follow our [deprecated items](https://github.com/ghacksuserjs/ghacks-user.js/issues/123) sticky issue
> - You can also follow all the [commits](https://github.com/ghacksuserjs/ghacks-user.js/commits/master)
>    * Commits per release start with the description "Start XX commits"
>    * The descriptions should be short but informative (we're getting better at it)
> - You can also do compares/diffs between [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases) right here on github

the deprecated items are listed in the changelogs; following commits is something probably nobody wants to do, and the compares between the releases is actually linked in each changelog as well. IMO those lines should not be in the wiki at all:

> - Follow our easy, succinct [changelogs](https://github.com/ghacksuserjs/ghacks-user.js/search?q=label%3Achangelog&type=Issues&utf8=✓) to discover new items and changes
> - ~~Follow our [deprecated items](https://github.com/ghacksuserjs/ghacks-user.js/issues/123) sticky issue~~
> - ~~You can also follow all the [commits](https://github.com/ghacksuserjs/ghacks-user.js/commits/master)~~
>    * ~~Commits per release start with the description "Start XX commits"~~
>    * ~~The descriptions should be short but informative (we're getting better at it)~~
> - ~~You can also do compares/diffs between [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases) right here on github~~

And add to that that nobody is notified of changes to the wiki while Issues are easy to see. We can keep that Howto about the "new" script open for sometime until after FF58 is released and then close it, and people can still follow the link to it from the wiki if they want to use the Windows updater.bat and need some info about it. They can also give feedback or ask questions right in that issue. And we could even add links to the github compare site for new versions, which show all the changes made since the last version.

**Comment by earthlng** [comment]
> add "Updatable" etc to list of aims on readme.md

seriously? LOL. Right after "Innovative (formatting, special tags, and future plans such as branches)".
I'm sorry but that whole "our aims" is kinda ridiculous, just some marketing words that nobody actually reads.
> ~~We won't set you wrong.~~

I'd just write something like: "some useful links to help you get started around here: xxx, yyy, zzz"

**Comment by Thorin-Oakenpants** [comment]
> Look, the wiki is already way too confusing with too much text

Bollocks. Yes some lines could be simplified, but overall every single page is f**king short for what it contains. Kinda getting pissed off now. Soz

**Comment by Thorin-Oakenpants** [comment]
various links removed from readme

```js
[test sites](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-C:-Test-Sites)
[deprecated section](https://github.com/ghacksuserjs/ghacks-user.js/issues/123)
[releases](https://github.com/ghacksuserjs/ghacks-user.js/releases)
[changelogs](https://github.com/ghacksuserjs/ghacks-user.js/search?q=label%3Achangelog&type=Issues&utf8=%E2%9C%93)
[wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki)
[extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions)
[user scripts](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-User-Scripts)
[references](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-D:-References)
```

**Comment by Thorin-Oakenpants** [comment]
looks really lopsided (the acknowledgments and footnotes are almost as big as everything else put together), the section headers look like dick with sections being so short, and it's embarrassingly short on helpful links and information. Well done

**Comment by Thorin-Oakenpants** [comment]
Removed a section header, removed text not needed from the acknowledgments, shortened the footnotes. Not sure what else you want

**Comment by Thorin-Oakenpants** [comment]
Done - I've simplified the readme. Happy now?

**Comment by Thorin-Oakenpants** [comment]
I suppose I better finish this off *sigh* ... I am *soooo* procrastinatic <sup>1</sup> about it

Suggest
-    3.1 Bulk Pref Resetting ~~[Scratchpad]~~
-    3.2 Applying & Keeping Your Changes ~~Additional JS Files~~
-    3.3 Updater Scripts

Notes:
- 3.1 Drop the scratchpad part in the title. Slightly restructure the contents: A) issue B) our new clearprefs.bat with proviso on removed items C) scratchpad. I'll try to simplify/shorten the issue
- 3.2 I think this a much better name. Simply put, stick overrides including a parrot at the end of user.js,  and keep a local copy as `user-overrides.js` in same folder or keep it in preferences subdir - link to/mention updater scripts
   * @earthlng - that's the file name, right? also what are the rules about using multiple files in a preferences subdir - any name for .js files, and it processes them in alphabetical order?
3.3 self explanatory

Does this sound alright?

<sup>1</sup> I am totally unsure if this derivative of the word even exists :)

**Comment by Thorin-Oakenpants** [comment]
@earthlng @claustromaniac 

I have redone the 3.1 wiki page on prefs clearing. The name needs to be changed (and links in the scratchpad files updated, although I am very close to releasing a 57final and we want to redo all those scripts anyway)

Current
- Bulk Pref Resetting [Scratchpad]

Suggestions
- Bulk Pref Resetting << doesn't do much for me TBH
- Syncing Inactive Pref Scripts

IDK .. someone come up with a nice short title

**Comment by Thorin-Oakenpants** [comment]
I have rewritten 3.2 - this needs review
- https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes

**Comment by Thorin-Oakenpants** [comment]
updater.bat currently has

```bat
REM ### ghacks-user.js updater for Windows
REM ## author: @claustromaniac
REM ## version: 4.0
```

The #'s are uneven. Also we need to add a comment linking to the wiki (which is yet to be done) as it will contain all the switches etc

```bat
REM ## ghacks-user.js updater for Windows
REM ## author: @claustromaniac
REM ## version: 4.0
REM ## instructions: https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-Updater-Scripts
```

^^ is this ok?

**Comment by Thorin-Oakenpants** [comment]
3.3 is done except it needs a sentence for the Mac/Linux part. I assume its the same as this

> Download the script and save it in your profile folder. You can run it and it will backup your current user.js, download the latest ghacks user.js and if it finds a user-overrides.js in the same folder it will append that to the user.js.

**Comment by Thorin-Oakenpants** [comment]
I only realized yesterday that we didn't check for a preferences subfolder and instead went with user-overrides subfolder - but it doesn't really matter in the long run

**Comment by claustromaniac** [comment]
Yeah, I wrote the script so it reads files from that subfolder because I wanted to avoid using files and folders that we know Firefox uses/used, to avoid potential conflicts.

**Comment by Thorin-Oakenpants** [comment]
That makes sense

**Comment by Thorin-Oakenpants** [comment]
Man,,, it's so quiet... must be Xmas (which is a single day) and yet we have a month of Xmas music in Malls etc, a month of Xmas specials on TV - in fact most TV seems to take a month break as well, an extraordinary disproportional influx of Xmas albums, endless streams of people saying things they don't mean like Merry Xmas etc ... Christ! That baby jesus has a lot to answer for

**Comment by Thorin-Oakenpants** [comment]
3.3 all done - closing this. I've read thru the 3 pages a dozen times each, and I can't see any errors. @earthlng when he returns from his Elf duties, can give it a review

**Comment by claustromaniac** [comment]
Caveats from [3.3](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-Updater-Scripts)...

> The user.js has some one-char switches for sections to make it easy to turn the entire section on or off (eg deprecated items by ESR version). Unfortunately, the script cannot detect any changes with these, and therefore does not reapply them if they differ.

I might be misunderstanding something, but I think that sounds potentially confusing/misleading. The script treats inactive preferences within multi-line comments differently depending on the mode of operation (append or merge). Are those the ones we're talking about?

The default mode appends all lines indiscriminately, meaning that inactive preferences in `user.js` will be made active (turned on) when there are active overrides for those preferences in `user-overrides.js`, and **active** preferences in `user.js` can't be turned off the same way by overrides. However, the merging mode doesn't turn on preferences that way as long as they are lines that begin with `user_pref` within multi-line comments in `user.js`, as explained (in different words) by @earthlng [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/296).

I've been wondering for a while whether it would be worthwhile or not to make the script smarter interpreting and handling preferences, considering all the ways they can appear in user.js. What do you think? What would be an ideal criteria for you?

**Comment by claustromaniac** [comment]
To elaborate on my previous comment, a -hopefully- concise example:

**source user.js contains:**
```
/* Begin multi-line comment
user_pref("example", false);
   end multi-line comment */
```

**user-overrides.js contains:**

`user_pref("example", true);`

### Resulting user.js with append mode (default):
```
/* Begin multi-line comment
user_pref("example", false);
   end multi-line comment */
user_pref("example", true);
```
### Resulting user.js with merge mode:
```
/* Begin multi-line comment
user_pref("example", true);
   end multi-line comment */
```

**Comment by Thorin-Oakenpants** [comment]
The point about the one-char switches is that the user.js is overwritten with the one on github which has those sections disabled -> thus if the end-user has flipped eg ESR52.x deprecated on, it will not get picked up at all because you can't add an override for our one-char switches

95% of people will probably use normal mode? => append

As for merge, the writeup by earthlng (which is the windows section on 3.3) touches on this and has a workaround IIRC

I'm just going to leave this for more eyeballs

**Comment by Thorin-Oakenpants** [comment]
I was thinking that BOTH updater scripts, when appending only, should add an override parrot at the start and end - just a thought

```js
user_pref("_user-overrides.js.parrot", "overrides section syntax error");
// MY OVERIDES blah

user_pref("_user-overrides.js.parrot", "overrides section success");
```

**Comment by claustromaniac** [comment]
I figured I was probably missing something in my reasoning. Thanks for the clarification.

> I was thinking that BOTH updater scripts, when appending only, should add an override parrot at the start and end - just a thought

I considered that too some time ago, but didn't bother with it in the end. It's easy to implement though, just a couple of lines of code.

**Comment by earthlng** [comment]
3.1: 
> * Disable the network connection
>   * Optional: recommended for large lists

I would rewrite that to: 
> [optional] disable the network connection (recommended for `ghacks-clear-all-up-to-57-[the-rest-active].js` !)

IMO we can also remove the Script Example from that page.

3.2: 👍 
3.3:
* the folder for multi-js must be named `user.js-overrides`
* Mac/Linux
  * ~~You can run it and it will backup ... ~~ => It will backup ...

**Comment by Thorin-Oakenpants** [comment]
3.1
*  changed it to
   *  [Optional] Disable the network connection (recommended)
* removed script example, no point having two of the same thing now we have a removed script - good thinking earthlng

I still don't really understand why disconnection is needed, even the largest script is done within seconds. If its not the size but some other reason, eg prefs getting reset by FF in that short window?, then please tell me

3,3
- fixed the info on naming convention to two bullet points so it sticks out like a dogs balls
- corrected the dir name (my bad!)

**Comment by earthlng** [comment]
> I still don't really understand why disconnection is needed

mostly to keep a clean profile. If you reset all active+inactive prefs then basically everything is reset to FF's default, ie it could start to download all kinds of updates. For example if someone takes a while to look at the remaining user-set prefs in about:config, or the log in the console, or doesn't immediately restart FF for whatever other reason.

**Comment by Thorin-Oakenpants** [comment]
Ahh .. that would be about the only ones - DRM/GMP/etc, app + extension updates

Are we happy to leave it as is with just the "recommended" in brackets at the end?

**Comment by earthlng** [comment]
... and system addons!

well it's a bit weird/confusing that it says optional and then recommended. Maybe `(recommended for *[the-rest-active].js + *[the-rest-inactive].js)` - that should maybe fit on a single line. Or if it doesn't, use a sub-bullet-point for that line (and in that case perhaps use the full names of those 2 files).

We should also add a recommendation in 3.2 to use parrot prefs in override files.

**Comment by Thorin-Oakenpants** [comment]
> We should also add a recommendation in 3.2 to use parrot prefs in override files.

What timing - already done

**Comment by Thorin-Oakenpants** [comment]
I think it is better to explain why vs listing two file names (which may get replaced/removed in the future)

**Comment by Thorin-Oakenpants** [comment]
* (Recommended) Disable the network connection <sup>1</sup>

<sup>1</sup> The reason for being offline is in case Firefox acts on your reset preference, such as app or extension auto-updating, downloading system addons or other items such as GMP/CDM/EME.

**Comment by earthlng** [comment]
IDK. it's totally unnecessary for [changes-only].js, [RFP-alternatives].js, [deprecated].js, [removed].js, and all future [changes-only].js files. And you also only need to run the other 2 files at most ONCE, so I don't think it makes sense to recommend to disable the network connection as a general rule.

**Comment by Thorin-Oakenpants** [comment]
already edited it to optional and reworded the footnote

**Comment by earthlng** [comment]
the files are named `clear-all-up-to-57` for a reason. ESR52 users shouldn't run any of these, at least not without editing them.

**Comment by Thorin-Oakenpants** [comment]
true to a point. Since 53, we have also added items that exist in ESR, the whole point is that the current version still works for ESR people - that's what the one-char switch is for. So the current 57 version **IS** the ESR version

I'm happy with the technical reason given and the step being optional
