### ISSUE TITLE
blocklists: awww man... where's the cleanup crew?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#288]
@fmarier 

In my FF profile (56) I have
- **profile**\blocklist-addons.json + blocklist-gfx.json + blocklist-plugins.json  (and a blocklist.xml dated today's date)
   - various dates (for the three duplicated json files) from late 2016 -> 12-April-2017
- **profile\blocklists**\addons.json + gfx.json + plugins.json
   - these are all dated 28-Sept-2017

:question: Can I safely delete the three json files in the profile root directory? Also, can't this sort of stuff be automagically cleaned up in future?

Question: why isn't blocklist.xml in the subdir yet

**Comment by earthlng** [comment]
You can delete them all. If you don't install dozens of shady addons for testing they don't have to be there all the time. Delete them, restart FF and you're gucci

**Comment by Thorin-Oakenpants** [comment]
I know they'll repopulate .... :)

**Comment by earthlng** [comment]
and who doesn't like *that* :)

**Comment by Thorin-Oakenpants** [comment]
Just for the record ... 11 hours later they have not been re-spawned
