### ISSUE TITLE
Firefox is OVERRIDING installed Add-ons when visiting addons.mozilla.org 

### ISSUE THREAD

**Issue by theDuckIsAlive** [ghacksuserjs/ghacks-user.js#289]
I havn't realized this before but when visiting the AMO site Firefox is OVERRIDING / DISABLING installed Add-ons.
That means content-filters like uMatrix or uBlock are disabled and third-party scripts and tracking-images can NOT be blocked (including Google-Analytics).

One thing I found out is at least they respect the "Do Not Track" header.
If the DNT header is set, Google-Analytics will NOT be loaded.

: (  This is extremely annoying.

**Comment by earthlng** [comment]
If you're using `privacy.resistFingerprinting` you can set `privacy.resistFingerprinting.block_mozAddonManager` to true to disable that behavior.

**Comment by theDuckIsAlive** [comment]
Thank you very much !

Yes ... I'm using privacy.resistFingerprinting
and that hidden pref solved the problem.

**Comment by Thorin-Oakenpants** [comment]
@theDuckIsAlive - FYI: now uM and uBo (and other WE such as Skip Redirect, Stylus, ViolentMonkey etc) can work on AMO

**Comment by earthlng** [comment]
np you're welcome
