### ISSUE TITLE
RFP & inner window height w/icons on BM toolbar [Bug 1418537]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#297]
Is anyone else getting this. Can someone test on 58/Nightly?

### Steps to reproduce

* Create a new profile
* Show the bookmarks toolbar - EMPTY the bookmarks toolbar
* Choose any theme (default, dark, light), choose any density, choose to allow extra drag space or not, choose to display title bar or not (these do not seem to make any difference)
* Set privacy.resistFingerprinting to true
   * note: also tested with privacy.window.maxInnerWidth & privacy.window.maxInnerHeight - these do not make any difference
 * close the browser, restart
 * visit http://browserspy.dk/screen.php
 * Screen res will be a combo of 200's (w) and 100's (h)

![01-bmblank](https://user-images.githubusercontent.com/16656956/33442578-57101280-d65a-11e7-993c-15865863110f.png)

* Now add something to the toolbar, eg a bookmark of the website, with or without text. Or even just a folder
* Note: a separator has no effect
* Refresh the page
* The height is thrown out because the toolbar height is changing (in the pic below in this new profile it is 2 pixels)
* In my main FF it is being thrown out by 1 pixel - no idea why it is different (I do have a couple of tweaks in userChrome.css)

![02-bmicon](https://user-images.githubusercontent.com/16656956/33442701-af371d8c-d65a-11e7-9094-d4441c6bda4f.png)

 * Restart the browser now you have an item on the bookmarks toolbar
 * restest the res at http://browserspy.dk/screen.php
 * You are still 2 pixels out in height
 * Note: most users who display the bookmarks toolbar probably have something on it with an icon, but for some people, they may disable favicons, or they may just use it for extension buttons
 * Extension buttons do not cause the height to change

Seems icons in the bookmarks toolbar causes the toolbar height to grow (padding or whatever) and this will affect *most* people who display it.

**Comment by Thorin-Oakenpants** [comment]
Update: While my new profile test was 2px diff, my main FF long time profile is out by only 1px. My few userChrome* tweaks are not the issue. Maybe it's the removal of a couple of items in customize?

**Comment by earthlng** [comment]
someone already reported it: https://bugzilla.mozilla.org/show_bug.cgi?id=1418537

**Comment by Thorin-Oakenpants** [comment]
this is tracked under the RFP sticky - closing
