### ISSUE TITLE
OT: userChrome.css help required

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#299]
@overdodactyl 

Hey man, I'm having trouble nailing this sucker on my speed dial
![grrr](https://user-images.githubusercontent.com/16656956/33480160-eeb79942-d6f4-11e7-9a53-d4b413db6caa.png)

I'm talking about the url being displayed bottom left on mouseovers, which seeing as almost every square inch is a dial, becomes f**klin annoying. I want to hide it, or change colors to become the same as background, but I can't grab it's name. I'm using this [extension](https://addons.mozilla.org/en-US/firefox/addon/groupspeeddial/) . The previous extension I used did not show this and I although I have tweaked the new extension to remove all the distractions, this one eludes me

Also, for some reason, despite enabling the Browser Toolbox ( https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox ) I am no longer able to use the selector or inspect the chrome. Been like this for about 2 weeks. Same in a new nilla FF57. Any help on that?

**Comment by Thorin-Oakenpants** [comment]
OK, I've semi worked it out, but not sure how to apply this just to the extension page (it does not work in userContent.css because it is chrome)

```css
statuspanel[type="overLink"] .statuspanel-label {display:none!important;}
```

speed dial is
```css
@-moz-document url-prefix("moz-extension://8a1a8222-6b59-4639-b488-48ef03fa3b57/dial.html")
```

Is this even doable?

**Comment by Thorin-Oakenpants** [comment]
Sorted: used 
```css
#main-window[title*="GroupSpeedDial"] statuspanel[type="overLink"] .statuspanel-label {display:none!important;}
```

**Comment by overdodactyl** [comment]
Hi @Thorin-Oakenpants, my apologies for just seeing this! I've been bad about checking my email associated with this account (does github not have any built in notification system for things like mentions??)

Looks like you may have figured it out though? If not, I'd be happy to look into it!

**Comment by Thorin-Oakenpants** [comment]
I only wailed on you because of your repo/knowledge - turns out I was just being a lazy son of a bitch :)

But still really miffed I can't get the inspector (Browser Toolbox) to work on chrome. It worked fine about 3 or 4 weeks ago, because I looked up a stupid in-urlbar icon I wanted to get rid of. Now I'm f**ked. (Even seems to happen in a new profile - might test again)

Eg, I was keen on detecting this by `id` (ie the extension icon and name part)
![blah](https://user-images.githubusercontent.com/16656956/33535421-538c09a6-d912-11e7-992a-aacc5ce94439.png)

**Comment by overdodactyl** [comment]
I'm glad you stumbled across the repo! It's pretty new, but I feel like I'm making some decent progress on it :) Kind of  took a different turn than initially planned, but oh well I gess haha

It appears you can target the icon with `#identity-box.extensionPage > #extension-icon` and the name via `#identity-box.extensionPage > #identity-icon-labels`.

It's odd the Browser Toolbox isn't working - is it not targeting items or just not opening at all?

**Comment by Thorin-Oakenpants** [comment]
nevermind ... I wasn't doing the browser toolbox thing properly. I was using Hamburger>Web Dev>Dev Toolbar and from there opening the Developer Tools

I should have used Hamburger>Web Dev>Browser Console - and then finally I get the prompt and shit works

***All sorted, kinda. Can I hide an element based on the value of another element?***

**Comment by Thorin-Oakenpants** [comment]
```css
#identity-icon-label[value="Extension (Group Speed Dial)"] {display: none !important;}
```

If the above can I then hide the jigsaw-shaped icon etc (yes, there's a higher div for the whole info bit, but I can't hide it for everything)
![icon-be-gone](https://user-images.githubusercontent.com/16656956/33535808-bc85bbb2-d914-11e7-81ee-487ccfd19232.png)

Here's what I would like it to look like
![ideal](https://user-images.githubusercontent.com/16656956/33535883-53b3c092-d915-11e7-8b54-91bbb36b792f.png)

**Comment by overdodactyl** [comment]
It depends - I think the general rule is CSS can only style elements that are siblings or children of the element you're targeting.

You'd like to remove the icon and text just for the speed dial extension then? Or always hide the jigsaw puzzle?

**Comment by overdodactyl** [comment]
I beleive

```
#identity-box.extensionPage > #extension-icon {
  display: none !important;
}
```

should always remove the jigsaw icon

**Comment by Thorin-Oakenpants** [comment]
I only want to hide stuff if the extension speed dial is loaded (otherwise it impacts info and menus etc available in webpages etc

parent element is #identity-box
![idbox](https://user-images.githubusercontent.com/16656956/33536110-3154dfd4-d917-11e7-9811-54a42b40fe99.png)

Inside that are the `#identity-icon` (circle with the i in it), `#extension-icon` (in this case a jigsaw piece), and the `#identity-icon-label` (which is hidden atm due to my current css)

If I could just hide the parent element that would be cool, otherwise how do I hide the two remaining siblings?

**Comment by Thorin-Oakenpants** [comment]
> nevermind ... I wasn't doing the browser toolbox thing properly. I was using Hamburger>Web Dev>Dev Toolbar and from there opening the Developer Tools
> 
> I should have used Hamburger>Web Dev>Browser Console - and then finally I get the prompt and shit works

This is not true either. I am having real issues getting this to work from either method. Sometimes it works, usually it doesn't - I get no prompt to allow a connection. May not help when I remove the `chrome_debugger_profile` folder, but that should just regenerate anyway

**Comment by overdodactyl** [comment]
I'll see if I can figure out some code to do that!

>I still get the Dev Tools opened, but selection of chrome items will not work

Are you staying within the same Firefox window that you opened up the toolbox from?

For example, if you open the toolbox from window A, then you can't select items from any FF window other than window A

**Comment by Thorin-Oakenpants** [comment]
Yeah, same window. But I'm not too worried about it. I have all my info now :)

I am playing with something, almost got a solution. Will post back

**Comment by overdodactyl** [comment]
You could give something like this a go:

`#main-window[title="GroupSpeedDial"] #identity-box { display: none !important; }`

**Comment by Thorin-Oakenpants** [comment]
userChrome.css does not like `>` in it

```cs
#identity-box.extensionPage > #extension-icon {
  display: none !important;
}
```

**Comment by overdodactyl** [comment]
Really? I didn't know that....I tested ^^ that out and it seemed to work as expected.

I grabbed `#identity-box.extensionPage > #extension-icon ` from the inspector

**Comment by Thorin-Oakenpants** [comment]
I got it sussed - will do - required an `image` in front of the` #` 

```css
/* GROUP SPEED DIAL EXTENSION - hide extension marker */
#identity-icon-label[value="Extension (Group Speed Dial)"] {display: none !important;} */

/* always HIDE extension icon, not needed, decoration only */
image#extension-icon {display: none !important;}
```

If I remove the last icon (circle with i in it) or remove the whole `identity-box`, there is no padding on the left and it looks shit.

With the above it's almost as close as normal (or when you clear the urlbar), except I have in info icon instead of a search icon

speeddial
![speeddial](https://user-images.githubusercontent.com/16656956/33537020-f415877a-d91d-11e7-9b8e-167ff22672f1.png)
normal/clear
![normal](https://user-images.githubusercontent.com/16656956/33537027-fbfd3be0-d91d-11e7-998d-4472beafc2d5.png)

Sweeet .. sorted bro .. thanks for your help

**Comment by Thorin-Oakenpants** [comment]
PS: re getting the browser toolbar - I was screwing up (cuz I do not use it regularly) ... I was MISSING the step where after setting the options in the dev toolbar, I have to go BACK to the hamburger and select browser toolbar

**Comment by overdodactyl** [comment]
Unfortunately I did very little to help here haha. Glad you got it (mostly) working..when I have some time I'll play around with it and see if I can get it so the search button appears

**Comment by overdodactyl** [comment]
I took a slightly (more convoluted) approach:

```
#main-window[title="GroupSpeedDial"] #identity-box { 

  list-style-image: url(chrome://browser/skin/search-glass.svg);
  padding-inline-start: 8px !important;
  padding-inline-end: 0px !important;
  margin-inline-end: 3px !important;
  fill-opacity: .1 !important;
  --urlbar-separator-color: transparent !important;
  filter: invert(60%) !important;
   
}

#main-window[title="GroupSpeedDial"] #identity-icon-label, 
#main-window[title="GroupSpeedDial"] #extension-icon, 
#main-window[title="GroupSpeedDial"] #identity-icon {
  display: none !important;
}
```

which I believe gives you the desired look:

![screen shot 2017-12-03 at 11 10 13 pm](https://user-images.githubusercontent.com/33071129/33538596-220f1984-d8ba-11e7-8152-8b2f779374e3.png)

**Comment by Thorin-Oakenpants** [comment]
^^^ Hmmm .. none of that worked (FF57) and I spelt yur nick wrong in a hurry

![well---fuck](https://user-images.githubusercontent.com/16656956/33541727-05a1e4fe-d935-11e7-8f95-80cdbdb10935.png)

**Comment by crssi** [comment]
^^Hey pants, which color scheme is that?

**Comment by Thorin-Oakenpants** [comment]
Obsidian

**Comment by overdodactyl** [comment]
>none of that worked (FF57)

Hmm that's really odd...

I tested it on FF57 as well, only difference being I'm on a mac, but I don't see why that would matter in this case...

**Comment by Thorin-Oakenpants** [comment]
If I get time I will test on a new profile - it may be some setting to do with dev - IDK. But I'm actually quite happy keeping the `i` icon because it signifies an extension

**Comment by overdodactyl** [comment]
Sounds good! Glad you figured something out :)
