### ISSUE TITLE
Referer blocked with Section 1600 excluded

### ISSUE THREAD

**Issue by Forsaked** [ghacksuserjs/ghacks-user.js#300]
Hi there,

i noticed that even with the full section 1600 excluded from the user.js somehow the referer get's blocked.
With a fresh profile everything is fine, but with only the user.js and excluded/deleted section 1600 the websites always get a direct hit / no referer.

I want this to be handled by an extension (Smart Referer or since yesterday uMatrix has this feature).
Did i miss something, except section 1600?

Regards Forsaked

**Comment by Thorin-Oakenpants** [comment]
I'm assuming you tried a new profile with no extensions, and added the user.js without the 1600 section?

**Comment by Forsaked** [comment]
Test 1:

1. Create new Profile
2. start Firefox with this Profile
3. go to Google and search for `[https://www.whatismyreferer.com/](https://www.whatismyreferer.com/)` and [`http://browserspy.dk/headers.php`](http://browserspy.dk/headers.php), then click the links (to have Google as my test referer)
4. works, both report Google as referer


Test 2:

1. Create new Profile
2. download user.js from GitHub and add it to the Profile folder
3. remove section 1600 from the user.js
4. start Firefox with this Profile
5. go to Google and search for `[https://www.whatismyreferer.com/](https://www.whatismyreferer.com/)` and [`http://browserspy.dk/headers.php`](http://browserspy.dk/headers.php), then click the links (to have Google as my test referer)
6. works, both report Google as referer


Result:

I don't Know what happend, but today it works, which didn't the whole day yesterday.
Looks like i can let uMatrix handle my referers!
