### ISSUE TITLE
12bytes link change

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#301]
front page: ghacksuserjs/ghacks-user.js

**acknowledgments**

this: `http://12bytes.org/articles/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs`

should be: `http://12bytes.org/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs`

thanks :)
byby

**Comment by Thorin-Oakenpants** [comment]
Done : ) https://github.com/ghacksuserjs/ghacks-user.js/commit/edec5cc366d690fe9ff9f3c614437ff0c1f4a6a7
