### ISSUE TITLE
FF59+ privacy.spoof_english

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#304]
reminder: follow up on adding `privacy.spoof_english` 1039069 as 4504. This seems to be controlled internally when users make language changes and/or flip RFP etc

https://bugzilla.mozilla.org/show_bug.cgi?id=1039069#c71
https://hg.mozilla.org/mozilla-central/rev/4036881d8ab0#l5.103
https://hg.mozilla.org/mozilla-central/rev/ab3d38eb9e7d#l1.64

This affects `0207: intl.accept_languages` and `0208: javascript.use_us_english_locale` ?

We could enforce as `2` and move 0207+0208 to RFP Alt ?

**Comment by Atavic** [comment]
It affects `0207: intl.accept_languages` https://hg.mozilla.org/mozilla-central/rev/69af55073d39#l1.12

**Comment by Thorin-Oakenpants** [comment]
^^ if you look at my second link, it can change both, unless I'm missing something

The issue is:
- we (currently) enforce a value for 0207 and 0208 - i..e use English US
- if we add `privacy.spoof_english`, we could enforce a value of `2`, in order to be the same as 0207/0208 .. and 0207/0208 move to RFP Alt .. however, I do not think this changes the set langauges - *that* is done when the user interacts with the UI. So we could end up with contradictory settings

This doesn't land until 59, so we should be able to pick up on it when 58->59 diffs come along, and test in say 59aurora to see exactly what happens.

I think we shouldn't even list the `privacy.spoof_english` pref (just list the bugzilla in the main header section and link back to 0207/0208) - IMO the pref needs to left alone and handled internally
