### ISSUE TITLE
FF59+: indicate HTTP as insecure

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#305]
Any objections? I do not have a FF59 to play with. What is the display? A red padlock or a grey padlock with a red stroke thru it or a yellow warning symbol or what?

```js
/* 1273: display HTTP sites as insecure (FF59+) ***/
user_pref("security.insecure_connection_icon.enabled", true); // all windows
   // user_pref("security.insecure_connection_icon.pbmode.enabled", true); // private windows only
```

Reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1310447

**Comment by earthlng** [comment]
That padlock icon is a fucking joke. Cloudflare for example is MitM-ing literally millions of websites and the padlock shows no indication of that. Instead it tells you that your connection to those sites is end-to-end encrypted and your data is protected when in reality it absolutely is not!
CF knows which sites you visit, what you do and and write on those sites and all your passwords as well. They could also inject anything they want into those sites if let's say they're "encouraged" to. *winkwink*
Surprised? only if you trusted that padlock :)

CF is a surveillance state' wettest dream come true and they just so happen to offer their services for free

**Comment by Thorin-Oakenpants** [comment]
That may be so... but what I am asking is if we should add this and flip the switch for 59 before Mozilla do (which could be years away for all we know). It's just a visual thing (still have no idea what icon/overlay is used), and I have to say (after missing SSleuth) that with dark theme, a padlock with a yellow warning symbol such as mixed content from memory really stands out. I'd quite like to have this when 59 lands.

And yes .. CF is a worry ... as bad as many other 3rd parties that effectively act as 1st party eg google apis if you want websites to function/interact, or disqus as a single point for using commenting, or gravatar, google fonts for glyphs, CDNs etc - at least for most of these you can block em with little to no effect. CF is a special kind of giant shitburger - but not really asking about that

**Comment by earthlng** [comment]
The user.js is already pretty long and we don't need to add more prefs just for a visual thing.
Mozilla will eventually flip it to true, or not - who cares.

> I do not have a FF59 to play with.

https://downloads.sourceforge.net/portableapps/FirefoxPortableNightly_59.0_Alpha_1_Pre_English_online.paf.exe

**Comment by overdodactyl** [comment]
For what it's worth, I think it's a worth while change even if it is just a visual thing.  

>What is the display?

Grey icon, red slash through it:

![http_non-secure](https://user-images.githubusercontent.com/33071129/33675045-410cc9c6-daa9-11e7-90b7-f2b6ba538752.png)

**Comment by Thorin-Oakenpants** [comment]
I don't think the length of the user.js is an issue - we passed that point long ago
