### ISSUE TITLE
0850b->false is not applied if 0850a is at default true

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#308]
0850a = `browser.urlbar.autocomplete.enabled` (default = true)
0850b = `browser.urlbar.suggest.history/boomark/openpage` (3 prefs, default = true)

we currently have 0850a inactive and 0850b as active

### observations

* using about:config
   - If 0850a is toggled to false, then all of 0850b is flipped to false
   - if 0850a is toggled to true then all of 0850b is flipped to true
   - if **any** (or all) of 0850b is set to true it makes sure 0850a is also true
   - if **all** of 0850b are set to false it will flip 0850a to false
      * as long as one of the three are true, then 0850a must be true

* using the UI (you can only toggle the three 0850b prefs here)
   - if any of the three are checked (true) then 0850a -> true
   - only when all three are unchecked is 0850a -> false

So far so good. Exactly as expected. Works both ways.

---
* user.js
   - a) if 0850a is set active (and 0850b is inactive) = works as advertised. The three 0850b prefs are also set to false or true as per value of 0850a
   - b) If 0850a is inactive, then 0850b may not be applied from the user.js depending on the currently set value for 0850a
   - c) not tested if 0850a **AND** at least one of 0850b is active

more to follow

**Comment by Thorin-Oakenpants** [comment]
the user.js behaviour is kinda hit and miss. for example, in a) above:

if the 3prefs are already false in prefs.js, and from the user.js I ONLY set 0850a as true, then all 3prefs are flipped. BUT if only one or two of the 3prefs are already set as false (i.e at least one pref is already true) then none of the 3prefs change, because no rule was broken.

It makes sense, that if it needs to flip the 3prefs, then rather than decide which one as a minimum. it does all three, otherwise if at least one is true then nothing needs to be done.

Just need to work out how to combine this/word it. But for sure, 0850a is more of a master than the 0850b's when it comes to the user.js

**Comment by Thorin-Oakenpants** [comment]
this is about the best I came come up with for now
- clarified the rules listed in 0850b 
- made them all active false to be consistent

```js
/* 0850a: disable location bar autocomplete [controls 0850b] ***/
user_pref("browser.urlbar.autocomplete.enabled", false);
/* 0850b: disable location bar suggestion types [controls 0850a]
 * [SETTING-56+] Options>Privacy & Security>Address Bar>When using the address bar, suggest
 * [SETTING-ESR] Options>Privacy>Location Bar>When using the location bar, suggest
 * [NOTE] If any of these are set true from the UI or about:config, 0850a will be FORCED to true
 * and if all three are set as false from the UI or about:config, 0850a will be FORCED to false
 * [NOTE] Setting all three as false from the user.js does not change 0850a
 * [WARNING] If all three are false, search engine keywords are disabled ***/
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
```

**Comment by earthlng** [comment]
looks good to me

**Comment by Atavic** [comment]
A nice choice!

**Comment by Thorin-Oakenpants** [comment]
tweaked it, see edited version above, but its still not 100% true. Maybe we could use something simpler

```js
/* 0850: disable location bar autocomplete and suggestion types
 * If you enforce any of the suggestion types, you MUST enforce 'autocomplete'
 * If *ALL* of the suggestion types are false, 'autocomplete' must also be false
 * If *ANY* of the suggestion types are true, 'autocomplete' must also be true
 * [SETTING-56+] Options>Privacy & Security>Address Bar>When using the address bar, suggest
 * [SETTING-ESR] Options>Privacy>Location Bar>When using the location bar, suggest
 * [WARNING] If all three suggestion types are false, search engine keywords are disabled ***/
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
```

This seems simpler (and saved 1 whole line?)

**Comment by Thorin-Oakenpants** [comment]
^^ removes all the rubbish about the ui & about:config (which btw conforms to the two rules I left in) which just confuses things. This refers just to the user.js and makes it as basic as I can get it

**Comment by earthlng** [comment]
> removes all the rubbish about the ui & about:config which just confuses things.

I didn't dare to say that myself, but I totally agree :) 
Doesn't really need the 4th line (5th if you count the title) IMO.

**Comment by Thorin-Oakenpants** [comment]
`* If you do not enforce the above, the settings may not be applied by the user.js`

I added it as a bit of an afterthought - cuz people will ask .. but why? what happens if... ? It shoudl be kinda obvious. Maybe I should stop pandering...
