### ISSUE TITLE
company environment specific settings

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#31]
Not meant to be included, but worth to mention which are and why and maybe for to be added to knowledge base.
I am using the following:

`network.automatic-ntlm-auth.allow-non-fqdn`
boolean: Set to true to enable SSO auth when using non-FQDN url.

`network.automatic-ntlm-auth.trusted-uris`
string: enter domain name where SSO is desired, multiple domain are comma separated

`security.enterprise_roots.enabled`
boolean: when true, the computer certificate store is used

`plugins.load_appdir_plugins`
boolean: I dont know yet the security implications, but when using "skype for business" (S4B) and when you click a meeting URL in for example email, the S4B meeting client is invoked over a browser and fails to open S4B meeting client... setting this one to true resolves this "problem"
It doesn't work for me personally, since I am browsing with sandboxed FF.... obviously. ;)

**Comment by Roman-Nopantski** [comment]
`plugins.load_appdir_plugins` -> default false.
`security.enterprise_roots.enabled` -> default false (hidden pref)
`network.automatic-ntlm-auth.trusted-uris` -> default blank string
`network.automatic-ntlm-auth.allow-non-fqdn` -> default false

I don't think we need these at all. If anything we would enforce the defaults and that's it. But these seem pretty specific to enterprise, and in that case, they're not private anyway. Even a home user wanting to use S4B, that's their problem. People should learn to use multiple browsers and multiple profiles for specific tasks.

**Comment by crssi** [comment]
No meant to be included... just for KB, if someone would need such.
