### ISSUE TITLE
let's talk about our little buddy cloudflare

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#310]
https://trac.torproject.org/projects/tor/ticket/24351 -  Earthlng, begin ~~rant~~ discussion xD

> HTTPS Cloudflare is MITMed.
> HTTP Cloudflare is MITMed(proxied via company with zero TLS protection).

Is there such a thing as `HTTP cloudflare` if one runs `HTTPS Everywhere` (assuming default rules)

have good read, tis entertaining

Edit: Definitely useful on TBB depending on what you are doing
- https://addons.mozilla.org/firefox/addon/block-cloudflare-mitm-attack
- https://github.com/nym-zone/block_cloudflare_mitm_fx

**Comment by earthlng** [comment]
> Of course, we can block cloudflare by default in uBo, uM, and allow a per site exception - that's what I do. 

How do you do that?

**Comment by Thorin-Oakenpants** [comment]
> How do you do that?

uBo seems to control what uM sees, maybe that's by design, or the order in which they were installed

### uBo

uBo is set up to block all 3rd party (dashboard, settings, click I am an advanced user). This allows the dropdown panel to display `global` rules. If you mouse over the `+all` row, the columns use tooltips to tell you the left column is global rules, the right column is local rules. But you know all this

![global](https://user-images.githubusercontent.com/16656956/33888578-549aa45a-dfb2-11e7-988d-c743aa300fb9.png)

The three dark red global blocks
```
* * 3p block
* * 3p-frame block
* * 3p-script block
```

### uMatrix

Not really needed, but if lets say I allow cloudflare thru uBo, my default uM only allows css and image by default. To keep rules to a minimum, depending on the domain (eg *.mozilla I treat the same) I select a scope (eg blog.domain.org or domain.org) and set horizontal rules for first parties (green) and vertical rules for say scripts (pale red) rather than accumulate thousands of individual cell rules.

I would need to go find some cloudflare examples to show some uM screenies to double check now - I know some *.cloudflares are preceded by garbage strings, but it's uisually always that same one for that site - again, just enable the cell, or the row

Is that what you meant?

**Comment by earthlng** [comment]
You don't seem to understand the CF problem. For example ghacks.net is a CF MitM-ed site.
What I was getting at is that you can't really block CF with uBO or uM unless you find + use a list with all the 6+ million sites that go through CF.

**Comment by Thorin-Oakenpants** [comment]
You're right. But I do see cloudflare rows in the uM and uBo panels - I guess that confused me

**Comment by grumpygeek** [comment]
I'm interested in fighting cloudfare (and others like it) but I can't think of any user.js related solution.  And of course domain blockers won't work for this.  I'd like a better explanation of what the extensions do.  Also, both of those are web extensions so no good for PM or old browser versions.  (I do have Fx57 installed but don't see using it as practical.)  I've read the links but I am not sure I understand what cloudfare is doing, but I know they need the cooperation of the site owner.  Would be nice to hear from someone who has worked with cloudfare on setting up such connections to their site.

**Comment by earthlng** [comment]
the extension should work on ESR as well. CF don't need cooperation - as soon as a site owner registers and makes the necessary changes on his side, CF will have full access to everything you send to that site.

**Comment by grumpygeek** [comment]
as soon as a site owner registers and makes the necessary changes on his side,

duh..huh, that is cooperation, as opposed to doing it without consent or prior knowledge

**Comment by earthlng** [comment]
Yeah I mean that part should be obvious, they can't **force** you to signup, duh

**Comment by theWalkingDuck** [comment]
I'm sure that they are going to remove those unique headers soon. 
This is not something which can be solved on a browser level.
This goofy network is now a case for Firewalls.

**Comment by Thorin-Oakenpants** [comment]
FYI: https://arstechnica.com/information-technology/2017/12/nope-this-isnt-the-https-validated-stripe-website-you-think-it-is/

Another reason the little green padlock is not what you think :) Class .. discuss!

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
Hi :)

https://github.com/mozilla-mobile/focus-android/issues/1743

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@grumpygeek Take a look at my comment, it's easy to understand.

https://github.com/mozilla-mobile/focus-android/issues/1743#issuecomment-351553457

**Comment by grumpygeek** [comment]
nope, that told me nothing.  What I wanted to know was more like does Cloudfare just add a header without decrypting content.  I know with email the body can be encrypted but the headers aren't.  I don't know if I have any way to look at http or tcp/ip traffic.  I had a similar question about the VPN I use sometimes but they did not answer.  It seems like users aren't really supposed to know what goes on behind the curtain.

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@grumpygeek They can't add any headers without decryption. It's technologically impossible.
Without decryption, Cloudflare can't read or modify the packet.

>  I had a similar question about the VPN
Interesting. What's your question, exactly?

**Comment by YouMustKnowPrivacyIsOurRight** [comment]
@grumpygeek

TLS connection(https://) encrypt "request header" and "body data".
TCP layer's base data, such as IP address and port number, is not encrypted.

So they can't add any headers *without decryption*. It's technologically impossible.
Without decryption, Cloudflare can't read or modify the packet.

> I had a similar question about the VPN

Interesting. What's your question, exactly?

**Comment by earthlng** [comment]
We raised awareness a little bit but there's nothing more that we can do about it. Users can block CF with a Firewall or use the extension that blocks CF-protected sites based on the headers. This isn't the place to start an anti-CF revolution and thus I'm closing this.

**Comment by Atavic** [comment]
According to: https://trends.builtwith.com/ssl

1/10 in the Top 1 Million Sites uses Cloudflare:

Technology | Websites | %
--------------- | -------- | -------
Cloudflare SSL | 108,881 | 10.89

**Comment by Thorin-Oakenpants** [comment]
^^ lulz .. according to @claustromaniac 's True Sight extension, every website in the known universe uses CDNs (slight exaggeration, maybe)
