### ISSUE TITLE
FYI: A comparison of web privacy protection techniques

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#316]
A comparison of web privacy protection techniques : https://arxiv.org/abs/1712.06850 .. click the PDF link top right .. I'm about to read it - only had a very quick skim so far.

@gorhill FYI since uBo is one of the products. Table1 lists the version as 1.6 which doesn't exist yet - maybe they meant 1.06? You can contact one of the authors,  Johan Mazel, from that landing page should you need to.

**Comment by Thorin-Oakenpants** [comment]
I'm a bit confused by the overlap figures in Fig7a (page11) .. the uBo/uBo cell shows `590` for 3rd party requests

**Comment by Atavic** [comment]
:+1: Good find!

**Comment by Thorin-Oakenpants** [comment]
Its a shame uM wasn't included - and of course bad timing what with NoScript moving to WebEx where it's nature has changed to be more granular. By that I mean look at the co-ordinate plotting on the three graphs top of page 14 - all the blocking list type ones are top right, NS is bottom left. I also assume they use default modes (Privacy Badger got training), which is a shame, because uBo can be configured to do way more than just block lists

At the end of the day I have uBo & uM in pretty much hard mode deny everything. Not missing anything from NS (yet).

**Comment by Atavic** [comment]
That figure just compares the numbers of blocked requests and domains, with the common ones into the green square. The diagonal has the items blocked exclusively by a specific addon.

...it's on prev page, right side.

**Comment by Thorin-Oakenpants** [comment]
^^ I'm just still skimming and spot picking .. so the `590` = 590 items uniquely in uBo's list? .. that's good for uBo, not so good for the others - shows the uBo filters are in great shape .. **wonder what those `336` items ghostery has are - someone should check that out**

**Comment by Thorin-Oakenpants** [comment]
> The DoNotTrack HTTP header provides almost no protection

lulz .. let me FTFY ... **The DoNotTrack HTTP header provides ZERO protection**

**Comment by Atavic** [comment]
Yes.

Seems like specific blocks of the same script, while Gorhill has neutered them:
https://github.com/gorhill/uBlock/issues/902#issuecomment-153952519 and
https://github.com/gorhill/uBlock/issues/1385

**Comment by Thorin-Oakenpants** [comment]
^^ already edited my comment above. Some blocked requests may never show up because they are neutered higher up

**Comment by Atavic** [comment]
Seems like Ghostery has specific blocks of the same script, while Gorhill has neutered it:
gorhill/uBlock#902 (comment)

**Comment by gorhill** [comment]
Sorry I didn't have time yet to read all the details of the papers, I just quickly scanned it.

> Table1 lists the version as 1.6 which doesn't exist yet - maybe they meant 1.06?

 [Version 1.6](https://github.com/gorhill/uBlock/releases/tag/1.6.0)  was released on Feb. 10, 2016.

Not too long after 1.6 came out I started to make more use of uBO's ability to redirect to local neutered resources, to foil widely used 3rd parties, for example `googletagservices.com` -- not blocked by EasyPrivacy. So nowadays the authors would find much better results for uBO.

> Its a shame uM wasn't included

Or even just uBO's medium mode, given they have covered NoScript and RequestPolicyContinued. I would say it's even weird given that uMatrix has a larger user base than RPC. But anyways, it's questionable to include such default-deny extensions in such test, of course they will always have the upper hand whrn it comes to foil 3rd parties, at the cost of web page breakage, that sort of extensions can never be meaningfully compared to install-and-forget blockers.

**Comment by Thorin-Oakenpants** [comment]
I always do that .. get uM and uBO versions mixed up (need MOAR ~~covfefe~~ coffee!)

It's interesting for sure, and even though they only used uBo in default mode when it can do so much more - imagine what users can do with uBo **AND** uM both in pretty much VERY hard mode (I don't have to imagine). Shame too that the versions are around 2 years old and since then its now WebExt and NoScript is pretty much completely different (and ugly as sin :vomit: )

--
FWIW: I used to have NS + uBo + uM (note they were actually installed in that order). Everything was basically default deny/hard mode. NS would block first, uBo saw what NS let thru and allowed domain XSS control, uM only ever saw what uBo let thru and allowed granular control

My uBo stats over a couple of years was around 5 or 6% blockage. With the move to WebExt I started squeaky clean and the last month has also been with no NS (I further hardened uM instead), and my uBo stats are 19% << uBo ALONE in advanced mode far outweighs NS because uBo can control XSS on a per domain basis (NS can too, but not from the interface)

--
tl;dr: Thanks gorhill :kiss:

Question: I still do not fully follow what NS offers that uBo+uM don't. Something about XSS (isn't that covered or is this some special NS thing), something about ABE (?) and something about ClearClick - I'll open a new topic for this

**Comment by Thorin-Oakenpants** [comment]
see https://github.com/ghacksuserjs/ghacks-user.js/issues/319

**Comment by earthlng** [comment]
> uBo can control XSS on a per domain basis

just FYI, [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) is a term used for a common vulnerability, and I think what you mean is [XHR](https://en.wikipedia.org/wiki/XMLHttpRequest).

**Comment by Thorin-Oakenpants** [comment]
Yup, XSS (cross site scripting) is how I use it term wise, and uBo allows domain->domain control, and uM even further control and I use uM for XHR

I do not have a legacy NoScript (or a WebExt version and I am not sure it is in the new version), but there is a specific **XSS** warning that comes up - it was in the options as a separate checkbox. I'll see if I can find some screenshots of the old options interface

**Comment by Thorin-Oakenpants** [comment]
![noscript-screenshot-options-advanced-trusted](https://user-images.githubusercontent.com/16656956/34343663-c2403a58-ea3c-11e7-8d44-78437f026c52.png)

having trouble getting images - might have to install it in a nilla ESR - there's the ABE and ClearClick, there might be something under that XSS (IDK), and I think there is a `forbid XSLT` under Untrusted.

**Comment by Atavic** [comment]
It's under notifications where 5 options are enabled:
- blocked scripts 
- XSS 
- blocked META redirections 
- ABE 
- ClearClick Warning
