### ISSUE TITLE
Ideas for Android (how to inject the config files)

### ISSUE THREAD

**Issue by TerkiKerel** [ghacksuserjs/ghacks-user.js#318]
Hi,

the new web-extension API does not allow add-ons to edit about:config references. We can change the user.js file on our desktop operating systems. But how we can edit user.js on mobile Android Firefox? We can change them manually from about:config but these takes long time. Also I always reset my settings/or I reset the mobile phone completely. It is difficult to set all these settings from mobile.

It would be great if you have an idea for Android Firefox.

Thank you

**Comment by Atavic** [comment]
>The entire Mozilla profile is not visible to the non-rooted Android user.

http://codeverge.com/mozilla.support.firefox/why-would-mozilla-developers-disallow/2044673

**Comment by Thorin-Oakenpants** [comment]
Nothing much you can do except root the phone - its an Android permissions thing, only the owner app can access its stash, so unless Mozilla build that in, and I doubt it, it'll have to be manually via about:config

FF accounts can sync some stuff, FWIW (not much, search for `services.sync.prefs` in about:config)

**Comment by Thorin-Oakenpants** [comment]
1- With the removal of XUL, you cannot change about:config entries via extensions (some are available thru APIs, but very little).

3- pretty sure you can't run JS from the urlbar (or its a pref we set for security reasons)

2- remote debugging?

Well, we can reset prefs via Scratchpad using scripts - see https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-Resetting-Inactive-Prefs-%5BScripts%5D#small_orange_diamond-how-to-run-a-scratchpad-script . Is scratchpad available on mobile, and can the scratchpad write values?

**Comment by Atavic** [comment]
2 - Android has strict permissions and a single user by default.

**Comment by Thorin-Oakenpants** [comment]
Can't find any way to bring up a Scratchpad or other tools in FF on Android. - Menu>Settings>Advanced>Remote Debugging via USB> toggle on/off .. now what.

**Comment by TerkiKerel** [comment]
I try remote debugging from my desktop Firefox. I did not installed any extension or ADB on my operating system. It is very easy to debug remote android.

I try a very simple script to execute javascript on about:config page. I tested it. I write it here to stay maybe someone will need it.

var user_pref = function(pref, val){

  try{
    if(typeof val == "string"){

         Services.prefs.setStringPref(pref, val);      
    }
    else if(typeof val == "number"){

         Services.prefs.setIntPref(pref, val);      
    }
    else if(typeof val == "boolean"){

         Services.prefs.setBoolPref(pref, val);      
    }
  } catch(e){
    console.log("pref:" + pref + " val:" + val + " e:" + e);
  }
}
//paste your user.js file content here

**Comment by Thorin-Oakenpants** [comment]
So this works then? You can apply all your changes in a single script? Do the prefs pasted underneath only take the active ones? I take it you were running 57+? I've never connected via remote debugging, we'll need proper documentation on steps, which we should write up as a wiki page

**Comment by TerkiKerel** [comment]
@Thorin-Oakenpants yes it works. I tested it.

First you start remote debugging from desktop Firefox (without any extension or Android-SDK). Desktop Firefox has build-in WebIDE module. After you connect to android firefox app, you go to about:config page. You can also inject a script to a web page that opened from Android. Copy my script, also copy your userjs file below it, and execute whole script to android firefox.

I am using:
- desktop Firefox 57.0.3
- android mobile firefox beta 58.0b12
- android mobile firefox stable 57.0.1

"only take the active ones?" --> I don't know if I understand your question exactly. But I see this: If I will call my user_pref method with any parameter it works. I mean If I have "media.navigator.this.pref.is.not.exist" it works. But does it matters ? Who cares if I have a pref which is not using by anyone?...

I think this topic should be clearly documented. Mobile privacy is more terrible status than Desktop.

**Comment by Thorin-Oakenpants** [comment]
> "only take the active ones?" --> I don't know if I understand your question exactly.

```js
your code
//paste your user.js file content here

// user_pref("one", "this is an inactive pref as it is commented out")
user_pref("one", "this is an active pref as it is not commented out")
```

Stupid question (forgot to screw my head on), because the inactive prefs are comment lines and won't be executed. Just want to check that FF reads all the syntax OK and doesn't try to parse something silly

> I think this topic should be clearly documented

Agree

>  But does it matters ?

Nah, it's just a pref entry that will do nothing and never be called

**Comment by Thorin-Oakenpants** [comment]
Do I have to do everything? /s

Should we create a wiki page `1.6 Android [non-rooted]`

**Comment by Atavic** [comment]
:+1: Android [Generic]

**Comment by Thorin-Oakenpants** [comment]
I don't quiet like the name, but generic doesn't mean anything. The page can also have the basic info to stop FF, force unload it, and where to put the user.js, so basically a sentence or two about rooted, but the whole thing is mainly about non-rooted. I'd probably just call the page `Android`

...**but my question wasn't about the name, it was should we do the page**

**Comment by Atavic** [comment]
I didn't mean that as title, but as an idea that a wiki page for non-rooted devices only seems limited IMHO

**Comment by icpantsparti** [comment]
I managed to set some Firefox preferences on my non-root Android using TerkiKerel's javascript.  It is straight forward, but not entirely obvious at first.  Here are some notes which might help towards an Android wiki page.

<details><summary>Using remote debugging to inject user.js preferences to Android Firefox</summary>

<H3>1) Choose a) Wi-Fi (easier) or b) USB connection</H3>

<H4>1a) Connecting Firefox on your Desktop Computer and Android Device via Wi-Fi</H4>

[mozilla - Debugging_Firefox_for_Android_over_Wifi](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_over_Wifi)

<ul>
<li>Install the ZXing Team Barcode Scanner Android app</li>
<li>Enable "Remote debugging via Wi-Fi" on Android Firefox (Options|Settings|Advanced)</li>
(You might have to toggle this off/on later if troubleshooting)
<li>On desktop Firefox visit and set true: about:config?filter=devtools.webide.enabled</li>
<li>Open WebIDE on desktop Firefox (Shift+F8 or menu|Tools|Web Developer)</li>
<li>Click "Refresh Devices" icon (upper right), click on your Android device</li>
<li>Scan the QR code with your Android to connect</li>
</ul>

Troubleshooting, if the device is not seen (note any settings changes for reversal later):
(Visit the troubleshooting link on the Mozilla page for more details.)
<ul>
<li>Is desktop firewall stopping connection?
<li>Is Android firewall app stopping connection? (eg NetGuard, No-root firewall, etc)
<li>Is Network/router settings/firewall stopping connection?
<li>Desktop needs to be on Wi-Fi too and not wired? (wired can work)
<li>Desktop firefox version is too much older than Android firefox?
</ul>

<H4>1b) Connecting Firefox on your Desktop Computer and Android Device with a USB cable</H4>

[mozilla - Debugging_Firefox_for_Android_with_WebIDE](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE)

<ul>
<li>Enable "Remote debugging via USB" on Android Firefox (Options|Settings|Advanced)</li>
<li>Enable Android's "USB debugging" (Settings app|Developer options)</li>
(You might have to toggle either of these off/on later if troubleshooting.)<br>
Note: to unhide "Developer options" tap "Build number" 7 times (Settings app|About Device)
<li>Watch out for any Android allow/connect prompts.</li>
<li>On desktop Firefox visit and set true: about:config?filter=devtools.webide.enabled</li>
<li>Open WebIDE on desktop Firefox (Shift+F8 or menu|Tools|Web Developer)</li>
<li>You need the ADB Helper Add-on (menu|Project|Manage Extra Components)</li>
(Click uninstall/install to update, <a href="https://ftp.mozilla.org/pub/labs/fxos-simulator/adb-helper/">or get it here if you have trouble.</a>)
<li>Click "Refresh Devices" icon (upper right), click on your Android device</li>
</ul>

Troubleshooting, if the device is not seen (note any settings changes for reversal later):
(Click the troubleshooting link on the Mozilla page for more details.)
<ul>
<li>Did you plug in your USB cable? ;-D</li>
<li>Windows: you might need to install Google USB Driver from Android SDK?</li>
<li>Linux: you may need a <a href="https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/android/51-android.rules">/etc/udev/rules.d/51-android.rules</a> file, then restart udev (or reboot)?</li>
<li>Linux: you might need to install android-tools-adb / adb? (it can work without)</li>
<li>Desktop firefox version is too much older than Android firefox?</li>
</ul>

<H3>2) Remote access</H3>
<ul>
<li>Open "about:config" page on Android Firefox</li>
It will show under WebIDE "TABS" on Desktop Firefox too (use tabs refresh icon)
<li>Click the remote tab name and the "web developer tools" panel will open</li>
(if you exit the panel by accident use: F12 or Project|Debug App)
<li>Select the "Scratchpad" button</li>
(If there is no button for "Scratchpad" click the cog and enable it)
</ul>

<H3>3) Inject the preferences</H3>
<ul>
<li>Paste the javascript (by TerkiKerel), and your user.js into the scratchpad</li>


```js
var user_pref = function(pref, val){
  try{
    if(typeof val == "string"){
         Services.prefs.setStringPref(pref, val);      
    }
    else if(typeof val == "number"){
         Services.prefs.setIntPref(pref, val);      
    }
    else if(typeof val == "boolean"){
         Services.prefs.setBoolPref(pref, val);      
    }
  } catch(e){
    console.log("pref:" + pref + " val:" + val + " e:" + e);
  }
}
//paste your user.js file content here
```

<li>The script sets a function called user_pref so wherever that appears in the rest of the code (ie in the part from your user.js) that function is called to set the user preference.  Any code for preferences that are commented out will not be run.  If a preference name does not exist or is mistyped it will still be created without any warnings.</li>
<li>Use "Display" (Ctrl+L) to run the javascript as it adds a result message in a comment after the script, which will say "undefined" or show errors.</li>
<li>Also click the "Console" button to look for any other error messages.</li>
<li>If errors occur on a line, the script might have stopped at that line, and you will need to correct the error in the code and re-run.</li>
<li>Check your Android Firefox about:support and about:config pages for your modified preferences, and see if the "_user.js.parrot" preference is showing success.</li>
</ul>

<H3>4) Finish</H3>
<ul>
<li>Disconnect: WebIDE menu|Runtime|Disconnect</li>
<li>For security, reverse settings you temporarily changed in any steps above:</li>
<ul>
<li>Desktop Firefox's WebIDE preference back to false</li>
<li>Android Firefox's debugging off</li>
<li>Android's USB debugging off (if used)</li>
<li>Troubleshooting changes (desktop firewall, android firewall, router, etc)</li>
</ul>
</ul>
</details>

**Comment by Thorin-Oakenpants** [comment]
@icpantsparti  sweeeeet, that's awesome :kiss: thanks for that. I'll get around to this sometime after FF58alpha user.js is released

**Comment by icpantsparti** [comment]
May be also worth a mention on a Android wiki page.  You can view the prefs you have set on about:support, but if you want to get the contents of prefs.js on non-root Android.

Enter into the firefox url address bar: <code>file:///data/data/org.mozilla.firefox</code> (if using beta append _beta).  Navigate your way through to the file inside your profile directory, such as: <code>file:///data/data/org.mozilla.firefox/files/mozilla/????????.default/prefs.js</code>

Tap on the prefs.js file and it displays, long press, select all, copy and paste into a text editor type app (such as QuickEdit, etc) for saving.  (Note that firefox updates the prefs.js file on app exit so settings made during the current session would not be visible yet.)

**Comment by Thorin-Oakenpants** [comment]
That's handy. Can't be arsed firing up FF on my phone, but you can also get a nice list via about:support > Important Modified Preferences

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android - first draft

**Comment by jghq** [comment]
I am rooted but FF wouldn't pick up user.js for some reason. This method worked perfectly. THANK YOU.

**Comment by Thorin-Oakenpants** [comment]
@jghq  Thanks for the feedback. I'll reopen this to remind me to write up the rooted section

**Comment by Thorin-Oakenpants** [comment]
bump!

reminder to add the text re rooted devices and close this

**Comment by Thorin-Oakenpants** [comment]
Done

**Comment by ohhai** [comment]
This doesn't work for now:
`Services.prefs.setIntPref(pref, val);`

Tried to prepend it with
`const Services = require("Services");`
or
`const { Services } = Components.utils.import("resource://gre/modules/Services.jsm");`
but these statements throw errors as well.

Is there any way to read/write FF preferences in remote debugging console?

**Comment by rusty-snake** [comment]
Did you saw #1147?

**Comment by ohhai** [comment]
No, thanks a lot!

For google: I was able to get and set preferences for Firefox 90.0.3 @ Android staying on about:support page. Related: https://github.com/arkenfox/user.js/issues/1147#issuecomment-804037914
Used remote JS console inside about:debugging on desktop PC. Don't forget to turn off remote debugging in both FF and Android settings after all.

So, no need to live with Firefox Nightly on Android just because of about:config availability.
