### ISSUE TITLE
Firefox does not override some settings from user.js

### ISSUE THREAD

**Issue by TerkiKerel** [ghacksuserjs/ghacks-user.js#320]
Hi,

I have some preferences on my user.js file. But firefox ignores some of these variables and does not override them.

As example it ignores this one:
browser.safebrowsing.provider.google4.gethashURL

I try these many times:

1- Close all firefox instances/processes
2- open new profile and start firefox
3- Close all firefox instances/processes
4- add user.js file inside profile folder (same directory with pref.js)
5- Open firefox and about:config

I check the variable: browser.safebrowsing.provider.google4.gethashURL. It is not same as user.js file. I re-open firefox million times. It does not work :(

I use Firefox 57.0.1 (64-bit). 

Have you any idea about this issue?

Is there any way to debug/or see detailed logs of firefox when it starts?

Thank you

**Comment by earthlng** [comment]
Hi, you probably have 1 or more syntax errors in your user.js.
That's why we have all those debug pref lines in our user.js:
```js
user_pref("_user.js.parrot", "START: Oh yes, the Norwegian Blue... what's wrong with it?");
```

**Comment by TerkiKerel** [comment]
@earthlng oh thank you so much... It was a syntax error :/
It fixed now.
