### ISSUE TITLE
privacy.resistFingerprinting breaks firefox addons installation

### ISSUE THREAD

**Issue by Utini2000** [ghacksuserjs/ghacks-user.js#328]
Hey again,

yesterday I noticed that "privacy.resistFingerprinting=true" breaks the installation of addons from the official firefox website. This is because a wrong version of Firefox is getting reported.

I then noticed that with "privacy.resistFingerprinting=true" the reported user agent is windows, version 52.0 (although I am on Linux with 57.0).

**Comment by crssi** [comment]
#278 ;)

Cheers
