### ISSUE TITLE
some additional settings

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#33]
Just putting here some settings I have stumbled upon.
I haven't investigate into those yet, so don't kill me, please. :)
Some might be deprecated already, some might not be existing, etc.

* [x] browser.addon-watch.deactivate-after-idle-ms
browser.addon-watch.interval
browser.addon-watch.percentage-limit
  * wontfix: commented by @earthlng: only for Nightly; we don't need this
* [x] browser.customizemode.tip0.shown
  * wontfix: I would guess, like a firstrun, its already been triggered for everyone
* [x] browser.formfill.expire_days
  * see #10 
* [x] browser.sessionstore.enabled
  * wontfix: deprecated
* [x] browser.xul.error_pages.enabled
  * wontfix: commented by @earthlng: false is bad, true is default; we don't need this
* [x] network.http.use-cache
  * wontfix: deprecated
* [x] toolkit.telemetry.optoutSample
  * wontfix: deprecated and not messing with telemetry settings (just master switches, urls, ids)
* [x] toolkit.telemetry.previousBuildID
  * wontfix: deprecated
* [x] toolkit.telemetry.rejected
  * wontfix: deprecated
* [x] toolkit.telemetry.server_owner
  * wontfix: not messing with telemetry settings (just master switches, urls, ids)
* [x] browser.download.manager.quitBehavior
  * wontfix: see http://kb.mozillazine.org/Browser.download.manager.quitBehavior
don't really know what would be the best for wider audience... or default (the value = 0) or is this privacy issue (then the value = 2)
* [x] media.hardware-video-decoding.enabled
  * wontfix: not messing with video playback (only those accessible via options)
* [x] dom.maxHardwareConcurrency
  * wontfix: at this stage

==
* [x] browser.sessionstore.restore_on_demand
  * NFI .. why do we get lists dumped on us

I am out for a few days.
If anyone already know for some of those, I would be happy for your comment.

**Comment by earthlng** [comment]
`browser.xul.error_pages.enabled` is pretty terrible when set to false, and it's true by default.
We could enforce true and just add it with the other browser.xul.error_pages or not include it at all.

`addon-watch` is only enabled in Nightly and used for performance monitoring, I don't think we need this

**Comment by earthlng** [comment]
// return the maximum number of cores that navigator.hardwareCurrency returns
pref("dom.maxHardwareConcurrency", 16);

**Comment by Atavic** [comment]
https://github.com/pyllyukko/user.js/issues/181

**Comment by Roman-Nopantski** [comment]
@earthlng heh .. it's [text] and then (url) .. not [url] then (the string "url") .. that just makes the hyperlink point back to this article .. lulz

**Comment by Roman-Nopantski** [comment]
The only privacy reason for `browser.download.manager.quitBehavior` would be if someone else started up FF, they could see the download resume (we clear all sorts of history on shutdown) which would in effect  be a leak. Are we really this far down the rabbit hole? At this stage the computer would be compromised, there is already a partial download on the drive, etc. I think we can just ignore this setting.

**Comment by earthlng** [comment]
> heh .. it's [text] and then (url) .. not [url] then (the string "url") .. that just makes the hyperlink point back to this article .. lulz

what? I copied the URL (dxr) into the Write field and submitted. The link works for me or did you correct it in the meantime? If it's about the edited OP comment, I didn't edit that at all, I think crssi added the info himself based on my comment.

**Comment by Roman-Nopantski** [comment]
I edited them, whatever you did (blonde moment or something) you had
```
[http://foobar.foo/](url)
```
exactly like that with the word `url` where the url goes

**Comment by Roman-Nopantski** [comment]
We're got two left to check and then we can close this (I'm tired).

`media.hardware-video-decoding.enabled` I think can be ignored. I do not want to mess with video decoding. The one pref (well two linked ones really) I will do is the one set from options. Not keen to mess with any others.

`browser.sessionstore.restore_on_demand` .. well, we already disable session data, so this is moot, right.

**Comment by Roman-Nopantski** [comment]
@earthlng I looked at `dom.maxHardwareConcurrency` already (it was in the 50->51 diff as new right?) and will not touch it. Besides the fact i'm not supporting ua spoofing, I'm also not going to mess with processes etc that will screw with performance

**Comment by earthlng** [comment]
`browser.sessionstore.restore_on_demand` default is true and IMO that's the preferred value.
afaik Session Manager also uses that pref and it's used to not reload restored tabs. Maybe this only makes sense when cache is enabled, idk.
@crssi only dropped us a list of prefs, idk if he suggests we set this to false. (??)

**Comment by earthlng** [comment]
`dom.maxHardwareConcurrency` I'm not sure it would impact performance at all. FF itself is in charge of how many cores it wants to use, and maybe this pref only exposes the number of cores to sites.
It's a max value, so it would only make sense for spoofing purposes if we set this very low.
If that's indeed the case, we would need a site with the most common core-numbers.
Idk, maybe this deserves some more digging, but I don't mind if we discard it.
The issue that @Atavic linked to, mixes number of cpus with number of threads. limiting the number of threads a serviceworker can use is of course impacting performance, but spoofing the amount of cores probably shouldn't.

**Comment by Roman-Nopantski** [comment]
I did read up on this until my head bleed .. and the distinct impression I got was to leave it alone. TBB uses 20. I also think any attempt to spoof will probably cause extra bits and raise entropy.

**Comment by Atavic** [comment]
Demo test page: https://github.com/oftn-oswg/core-estimator

Core Estimator uses navigator.hardwareConcurrency API with `.google-analytics.com/ga.js`
then opens up a progressive number (_1-2-4-8_...) of [Web Workers](https://w3c.github.io/workers/#the-workernavigator-object) and by looking at the time needed to execute them it gives an extimation of the number of cores.
