### ISSUE TITLE
RFP interfers with cmd on OSX [Bug 1405810]

### ISSUE THREAD

**Issue by overdodactyl** [ghacksuserjs/ghacks-user.js#330]
Hi there!

Any chance you guys know what pref is preventing the use of copy/paste/undo on some sites and extensions?

The two that I've particularly noticed are GitHub (when editing a file, not when writing comments) and Stylus.

In a fresh profile, I'm not noticing this behavior, but I am in a fresh profile+user.js.

The likeley culprits seemed to be 2402 and 2403: 

```js
/* 2402: disable website access to clipboard events/content
 * [WARNING] This will break some sites functionality such as pasting into facebook, wordpress
 * this applies to onCut, onCopy, onPaste events - i.e. you have to interact with
 * the website for it to look at the clipboard
 * [1] https://www.ghacks.net/2014/01/08/block-websites-reading-modifying-clipboard-contents-firefox/ ***/
user_pref("dom.event.clipboardevents.enabled", false);
/* 2403: disable clipboard commands (cut/copy) from "non-privileged" content (FF41+)
 * this disables document.execCommand("cut"/"copy") to protect your clipboard
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1170911 ***/
user_pref("dom.allow_cut_copy", false); // (hidden pref)
```

but reverting those didn't seem to fix the problem.  Any thoughts?

Edit: select all `cmd+a` can also be problematic 

Edit: Thorin is editing this comment as a test

**Comment by Thorin-Oakenpants** [comment]
I have no issues with copy-cut/paste/undo on github using ctrl keys. Is this the method you mean? Almost sounds like a shortcut key conflict - disable extensions 1 by 1 until the problem goes away - or is there a way to view all mapped shortcut keys?

**Comment by overdodactyl** [comment]
>I have no issues with copy-cut/paste/undo on github using ctrl keys. Is this the method you mean?

I don't notice any issues on the comments sections (such as typing here), but only if I try editing a file (for example if you use githubs editor to try and alter [user.js](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js). For example, if I'm in the editor, select a section of text and cmd+c (to copy), the selected text gets replaced with a "c").

The only reason I figured it was a `user.js` issue was that it didn't happen in a fresh profile, but immediately after adding it, I had the same odd behavior.

>Edit: OK you're on a Mac then using cmd, right?

Correct, `cmd` is essentially Macs `ctrl`.    If you're not noticing this behavior though, I guess it could be some odd OS dependent thing...

**Comment by overdodactyl** [comment]
@Thorin-Oakenpants - it's happening for me because of `privacy.resistFingerprinting`.

If i toggle that off in the same browsing session, the problem goes away.

**Comment by earthlng** [comment]
Sounds like something worth reporting to mozilla, IMO.

**Comment by Thorin-Oakenpants** [comment]
^^ damnit was gonna say that. Need STR in nilla profile

**Comment by Thorin-Oakenpants** [comment]
Ooh, I know .. its the OS spoof part of the UA spoof, I bet ya

**Comment by Thorin-Oakenpants** [comment]
Scrap that - its already documented - https://bugzilla.mozilla.org/show_bug.cgi?id=1405810

**Comment by overdodactyl** [comment]
Thanks Pants! Sorry for wasting your time - should have done more to look into this before posting

**Comment by Thorin-Oakenpants** [comment]
^^ no worries, it's not like you live and breathe bugzilla issues. If you have an issue, bring it up. 50 heads are better than one (usually)

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl .. https://bugzilla.mozilla.org/show_bug.cgi?id=1404608 (do not lie about OS) - patches being written now, first review was like 15 minutes ago - so I would expect 59 to resolve this problem. Highly likely IMO to backport to 58 since it's a pretty simple patch (it's just a UA spoof)

**Comment by overdodactyl** [comment]
Thanks Pants! That's great news - appreciate the update.  

I have to imagine they would backport this one...from the other bug link it sounds like they had some growing concern about users flipping off RFP due to the same problem in google docs

**Comment by overdodactyl** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1404608 (do not lie about OS)  has been marked as RESOLVED..

In Nightly, my UA is now reported as a mac and no issues with cmd functions :+1:

**Comment by Thorin-Oakenpants** [comment]
^^ Then report it as resolved fixed for 59+ at https://bugzilla.mozilla.org/show_bug.cgi?id=1405810 so they know (although I am sure they will test)

**Comment by overdodactyl** [comment]
Just did!  Not sure if you want to close this or leave it around until it gets backported/reaches stable

**Comment by Thorin-Oakenpants** [comment]
I'm already monitoring OS spoof bugzilla it in the RFP sticky - and I'll pick up on if it is backported `resolved->58`, so yeah, we can close this

**Comment by Thorin-Oakenpants** [comment]
@overdodactyl - can you tell OP in [this reddit q](https://www.reddit.com/r/firefox/comments/7ve3vb/help_ctrlc_not_working_in_websites_that_capture/) that this is the bug: [1433592](https://bugzilla.mozilla.org/show_bug.cgi?id=1433592)

**Comment by overdodactyl** [comment]
Just did :)

**Comment by Thorin-Oakenpants** [comment]
good dactyl *pat* *pat*
