### ISSUE TITLE
user.js and uBlock logger

### ISSUE THREAD

**Issue by FTno** [ghacksuserjs/ghacks-user.js#331]
In the logger in uBlock Origin you should be able to click on a filter to see which list it belongs to. But this does not work for me, nothing happens when I click a filter.

I have now done a test to find out what's causing this, and tested with a new portable version of Firefox (57.0.4) and with uBlock Origin 1.14.22.
It worked just fine clicking the filter. I then added user.js (v57) to the profile folder and then it did not work.
So it seems that something in the user.js file causes this issue. I don't know which setting.
Have anyone else experienced this issue?

**Comment by Thorin-Oakenpants** [comment]
I couldn't capture the pointer but in the pic below do you mean when the mouse pointer turns into magnifying glass when in the `||github.com/ _private/browser/stats` cell?

![ubo-logger](https://user-images.githubusercontent.com/16656956/34640284-ac8fb3d4-f354-11e7-82ef-66c095f09b32.png)

**Clicking this does nothing for me either**. I didn't know that trick. The other cell columns work fine (eg second column brings up the panel, the fourth column which uses a hand pointer brings up dynamic and static filtering. At least those work :)

**Comment by ArchangeGabriel** [comment]
I confirm the issue here.

**Comment by FTno** [comment]
'in the pic below do you mean when the mouse pointer turns into magnifying glass when in the ||github.com/ _private/browser/stats cell?'

Yes, and a small popup should appear when clicking.

**Comment by Thorin-Oakenpants** [comment]
If noone else does it, then I'll go thru the halving method tomorrow to nail the pref and then we can talk to gorhill

**Comment by Thorin-Oakenpants** [comment]
It's `2301: user_pref("dom.workers.enabled", false);` - you can toggle it in about:config and refresh the logger to confirm

**Comment by Thorin-Oakenpants** [comment]
Heh, even after resetting the pref back to false, clearing the cache, clearing the logger .. it now works until you restart FF

**Comment by Thorin-Oakenpants** [comment]
The prefs is `2301: user_pref("dom.workers.enabled", false);` - you set it to true and you do not even need to refresh the logger, just ciick at least once to enable the worker. As long as the worker runs once per session, even after resetting the pref back to false, clearing the cache, clearing the logger .. it now works until you restart FF.

The worker is `reverselookup-worker.js` - go to about:debugging#workers and click the debug button to view it in Developer Tools - it is part of uBo's code. 

I wonder if this is a chromeworker - https://developer.mozilla.org/docs/Web/API/ChromeWorker

**Comment by Thorin-Oakenpants** [comment]
You can either just remember this for troubleshooting, or if you are on FF57+ and use uMatrix, see issue #326 - you can enable workers and web workers (prefs 2301+2302) in about:config etc, and default deny these in uM and allow a per scope (you won't need to do anything for the logger since it's a moz-extension and privileged, I think)

**Comment by Thorin-Oakenpants** [comment]
> Chrome Workers are a Firefox-only type of worker that you can use if you are developing add-ons and want to use workers in extensions and have access to js-ctypes in your worker. - source: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API

@gorhill .. is `reverselookup-worker.js` a chromeworker - link: https://developer.mozilla.org/en-US/docs/Web/API/ChromeWorker? I do not use Chrome, so I do not know if this feature is in the Chrome uBo version, and a "ChromeWorker" is FF only.

anyone: Does `dom.workers.enabled` control ChromeWorkers?

**Comment by gorhill** [comment]
> is `reverselookup-worker.js` a chromeworker

Just a standard web worker. It removes itself after a few minutes of inactivity.

**Comment by Thorin-Oakenpants** [comment]
Thanks

**Comment by FTno** [comment]
Changing to 'user_pref("dom.workers.enabled", true);' fixed the issue. Thanks.
