### ISSUE TITLE
cannot access my router [solved: network.http.referer.XOriginPolicy]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#332]
@silviuapostolescu wrote

> Hi guys. I'm appreciating your work here. I'm not at all a professional in your field of action. I'm only a user. In this case a Firefox user. I dont know if here is the right place or moment to inform you that after I change Firefox configuration row by row according to your recomandations from the master file, somewhere after the first half (I think) of the master file a code line or what you call it ruined my router interface which says: "You have no authority to access this router!" and up to now I did not figured it out which is. Can you please help me to revert/reset that config line? Mention: if I use a fresh install of Firefox I'm able to access my router interface. My router is a TP-Link model TL-WR1043ND. I checked many times all the warnings from the master file but still not find the culprit line.

**Comment by Thorin-Oakenpants** [comment]
What is the address in the URL bar for you accessing your router interface?

**Comment by Thorin-Oakenpants** [comment]
some routers require a cookie. Click on the `I` icon in the urlbar, click the `right arrow`, and then `More Information`, click the `Permissions` icon, scroll down to `Set Cookies` and untick "Use Default" and select "Allow"

**Comment by kgbm3** [comment]
Yup, it's one of the **network.http.referer.** settings; probably **network.http.referer.XOriginPolicy** (a value of "1" will do just fine. :))

**Comment by Thorin-Oakenpants** [comment]
@kgbm3 Thanks :+1: 

---
There's also this video ( https://www.youtube.com/watch?v=BZBWrbkL1xc  1m23s long, no audio) from 18months ago which says you try using `tplinkwifi.net` to connect (it shows in the video as http which is not good) and should get you thru. Not a real solution - I assume you have to be online? Or is this mapped to local? IDK.


--
**From 3+ years ago**: http://forum.tp-link.com/showthread.php?74815-You-have-no-authority-to-access-this-router!

> The problem with Firefox is that it does not send out the referer header the router expects to see.
When the referer is not the same as the LAN IP address (e.g. 192.168.1.1), the router will send the error message.

>  I try to login from lan subnet and is work fine for me. But when i try to login remotely - i see this message (from subnet 192.168.0.0/16 (!)) Buuuut when i try to login from wan from subnet 192.168.0.0/24 (!) - work very good

> You can open Firefox, enter "about:config" and search "network.http.sendRefererHeader", change value from 0 to 2.

^^ You should already have this value, we left it at default `2`

> Don't know if it helps anyone but i get the error only when using the dns name. I can access the router without problems when using the wan ip

What is the address you are using to access the router

**Comment by silviuapostolescu** [comment]
TY for your comments and appologize my late answer. 
The address in the URL bar that I access my router interface is 192.168.1.1 . 
Regarding "network.http.referer.XOriginPolicy" the value is 1 and still I can not access the router interface. 
Regarding the youtube solution > doesn't worked. The message was: "Oops! It looks like you aren't connected to your TP-Link network.Please check your network connection and try again."
"network.http.sendRefererHeader" the value is 2 by default.

**Comment by Thorin-Oakenpants** [comment]
OK, try something for me - on the `192.168.1.1` page, click the `i` icon in the urlbar, click the `right arrow` and then choose `more information`. This will pop open a Page Info dialog.

Chose the `Permissions` button and under the setting `Set Cookies`, untick "use default" and instead select "allow"

**Comment by silviuapostolescu** [comment]
I missed to inform you that this issue appeared a few versions of Firefox ago (if I may say in this way). I was waiting to see if somebody else has the same problem and notified it. When I change line by line the values according with your master and your explanations, somewhere in the "web workers" or "DOM" area I start missing to check the router interface if it could be accessed. Later on I just noticed that I'm not allowed to do it only if I install a fresh Firefox. If I add later the modified file "prefs.js" things go back to the same problem.

**Comment by silviuapostolescu** [comment]
I did and the result is the same: no authority...

**Comment by silviuapostolescu** [comment]
Am I the only person who is using a TP-link router and have this problem?

**Comment by Thorin-Oakenpants** [comment]
I do not think this is an issue - since you seem to connect in order to get the message, but it *could* be the TLS version

1201: user_pref("security.tls.version.min", 3); << you could try changing this to `1`

**Comment by silviuapostolescu** [comment]
Still not working. I try this modification before and no change.

**Comment by Thorin-Oakenpants** [comment]
I'm having a bit of a hard time following your English, so I want to clarify some things

- What OS are you on (because I might step by step you thru a portable Firefox test)
- Don't touch the `prefs.js` - the user.js writes to it, so not need to mess with it, especially if Firefox is open
- So how long have you been using **our** user.js? Are you using the latest version?
- So when you say this happened a few versions of Firefox ago, do you mean like 3 months ago, or a year ago?
- Are you running Antivirus that monitors your web traffic?

`1206` security.pki.sha1_enforcement_level -> change to value `3` and test again

**Comment by silviuapostolescu** [comment]
I think I use a portable Firefox as you guys recomanded some time ago.
My OS is W7 64bit.

**Comment by silviuapostolescu** [comment]
I used your "user.js" file initialy but I dont know how to change values there. Therefore I use the "about:config" command.

**Comment by silviuapostolescu** [comment]
Yes, about 3 months ago.

**Comment by silviuapostolescu** [comment]
I'm not using an antivirus. Oh no, I'm lying because I'm using Windows Defender. Should I deactivate it?

**Comment by silviuapostolescu** [comment]
security.pki.sha1_enforcement_level > I changed the value to 3 > no positive result.

**Comment by Thorin-Oakenpants** [comment]
No, do not deactive Windows Defender

Note: If you do not change the values in the user.js,, and only change them in about:config, then the original user.js values will be re-applied on each Firefox start. It is fine to change them only from about:config for testing and finding the culprit, but be aware that you WILL have to edit the user.js file - you can open it with Notepad

**Comment by Thorin-Oakenpants** [comment]
Do you have TeamViewer? Because since we're both here simultaneously - if you are willing, give me your email in here (and I will edit it out as soon as I get it) and I will email you and we can connect remotely and I will troubleshoot it for you.

**Comment by silviuapostolescu** [comment]
I understand. I'm not sure what to write in the Notepad as a line. This is why I was afraid to ruine it. So, what should I do now?

**Comment by silviuapostolescu** [comment]
One more info that I forgot to tell you (maybe counts or not) : I'm using a Wi-Fi connection from this PC to access the damn router.

**Comment by Thorin-Oakenpants** [comment]
Wifi connection is not a problem

**Comment by silviuapostolescu** [comment]
Ok. Ty.

**Comment by silviuapostolescu** [comment]
Where should I find that "user.js" file? It is not in "C:\....|AppData\Roaming\Mozilla\Firefox\Profiles\gh8mzdws.default-1513020322639" path ?

**Comment by Thorin-Oakenpants** [comment]
> I understand. I'm not sure what to write in the Notepad as a line. This is why I was afraid to ruine it. So, what should I do now?

I don't think you'll be able to troubleshoot this on your own, as you lack a little knowledge (no offense meant). I am willing to remote in via TeamViewer - I can even talk you thru installing a portable TeamViewer (so that when you close it, it is not still open in the background as a service). TeamViewer also means you can see everything I do (not as a hidden secondary login). Not that I would want you to just let anyone in.

If you give me your email (**and I will edit it out of your comment as soon as I get it**, so it doesn't stay public in this thread) then we can solve this properly and not bombard everyone with hundreds of posts :)

**Comment by silviuapostolescu** [comment]
OK. No problem for me. My e-mail is: silviu.apostolescu@gmail.com

**Comment by silviuapostolescu** [comment]
I just open my e-mail and I saw a lot of e-mails from you. Sorry about that.

**Comment by silviuapostolescu** [comment]
192.168.1.1

Silviu Apostolescu

2018-01-06 15:57 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by silviuapostolescu** [comment]
I did. Same result.

Silviu Apostolescu

2018-01-06 16:03 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by Thorin-Oakenpants** [comment]
> I just open my e-mail and I saw a lot of e-mails from you. Sorry about that.

No, they are the notifications from Github - you get them because you commented in this issue - just delete them all

**Comment by Thorin-Oakenpants** [comment]
I just sent you an email - we will converse via email from now. The subject line is **Thorin-Oakenpants here re Firefox problem**

**Comment by silviuapostolescu** [comment]
You right. I need a lot of knoledge in this field. I'm not felt offended.
So, I have to look after a TeamViewer programm in order to install it?


Silviu Apostolescu

2018-01-07 13:27 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by Thorin-Oakenpants** [comment]
I will talk you thru getting TeamViewer via email

**Comment by silviuapostolescu** [comment]
I dont have TeamViewer.

Silviu Apostolescu

2018-01-07 13:17 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by silviuapostolescu** [comment]
OK.

Silviu Apostolescu

2018-01-07 13:36 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by silviuapostolescu** [comment]
Fine. Where is better to look for TeamViewer?
FileHippo is OK?


Silviu Apostolescu

2018-01-07 13:38 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by Thorin-Oakenpants** [comment]
Check your email - took me a while to add pictures for you

**Comment by silviuapostolescu** [comment]
I saw. Ty for yor tutorial. Save a lot of time for me to know what to do.

Silviu Apostolescu

2018-01-07 13:49 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by silviuapostolescu** [comment]
Issue solved due to the professionalism of Thorin (aka Pants).
I really appreciate your efforts and your time consumed for me.
Hat off.
Thank you very much again.
I have a lot to learn from you guys.
You are great.
Keep doing this. I'm sure ppl will appreciate all your efforts.
See you.
Have a wonderfull day.

**Comment by Thorin-Oakenpants** [comment]
Solved: it was `network.http.referer.XOriginPolicy` - which required a default setting of `0`

There was no ghacks user.js file, the pref values had simply been applied one by one over a period of time via about:config. @silviuapostolescu has his installed FF with no user.js working, but he NOW also has a portable 57.0.4 with unmodififed user.js and both running concurrently, so he can test things :)

**Comment by earthlng** [comment]
@Thorin-Oakenpants I wrote a scratchpad script to troubleshoot problems with sites.
It basically does the halfing described in the wiki but without the need to constantly restart FF + restore the profile. Interested? I could also create a demo video to show how it works.

**Comment by Thorin-Oakenpants** [comment]
But is it an **African** scratchpad script for heavy ~~[coconuts](https://en.wikiquote.org/wiki/Monty_Python_and_the_Holy_Grail#Coconuts)~~ tasks?

Throw up some details in a new issue, sounds good. Some settings though **do** require a restart, but very few.

**Comment by earthlng** [comment]
I've tested it on twitch which requires 3 prefs to be changed for the page to work.
It narrows down on each pref individually so I needed to run it 3 times but IMO it's still a lot easier and more convenient than doing it as described in the wiki.
I'll create the video and you can check that out and then maybe try the script yourself.

> Some settings though **do** require a restart, but very few.

yes but those are generally not the ones causing problems. I've hardcoded a list of currently active prefs (minus the ones that enforce FF's default value based on FF57.0.4, to keep the list as short and relevant as possible) and removed some other ones that don't interfere with pages. But we can still probably optimize the list a bit.

**Comment by earthlng** [comment]
https://anonfile.com/6eZ9v9d9b6/troubleshooter_vid.zip

**Comment by Thorin-Oakenpants** [comment]
lol - can't drag and drop a webm into firefox's urlbar :) catch-22 .. i need the webm to know how to troubleshoot not being able to load the local webm j/k

That's a long vid :) I'm impressed

> But we can still probably optimize the list a bit.

For sure. all e10s/sandboxing stuff should be on an ignore list. This does not read any prefs from a user.js - its mentioned a couple of times that this works with any user.js? Not sure on the flow/logic of this. Can you elaborate? eg

read prefs.js (wouldn't prefs.js be better than user.js) -> build array of `user set`/`modified` prefs -> remove all prefs from this array that are not in the hardcoded script list -> resort array in order of likely breakage

or -> load hardcoded script list prefs into array in our special order -> reduce to those in prefs.js ie detected as user set etc keeping order

This is like a bunch of 30 prefs that would would be in a relaxed override.js

Question: After troubleshooting, users would still need to edit their overrides.js right?

**Comment by earthlng** [comment]
> That's a long vid :) I'm impressed

thanks, glad you like it

> its mentioned a couple of times that this works with any user.js? .. Can you elaborate?

the script checks each pref in the hardcoded list to see if it's user-set, and if so it stores the actual value as seen in about:config. So for example the script can also be used by users who don't have a user.js but have made changes manually. And it also works if someone made changes to values in their own user.js.
Basically it just means that the values for the hardcoded prefs are not hardcoded themselves to match the ghacks user.js. And because it only works with user-set prefs, we could even include some of our inactive prefs in the list to make it even more useful, see fe. the other issue where someone had a problem with trackingprotection.

> Question: After troubleshooting, users would still need to edit their overrides.js right?

that's correct. It only changes the narrowed down one in about:config (and therefore in prefs.js) - but that also means that for users without a user.js the change will be permanent. But I can easily change that to a prompt as well if that's desired.

So, based on the video do you think this is something that we should offer here? I'm only asking because we haven't gotten any feedback on any of our scripts so far, and I don't want to confuse people more than they already are. And if nobody's gonna use them, I also don't want to waste more time with improving it and documenting exactly how it works etc.

**Comment by Thorin-Oakenpants** [comment]
Ahh, I get it, the user.js was added only to make all those prefs changes. I get it now.

email me the list of hardcoded prefs. It's not all that complicated to use, we could also state: *we refuse to discuss this, so don't ask questions about it - watch the vid - this is for advanced users* - and it is useful. Depends on that list - because I could easily list 30 to 40 prefs right now that would fix 99% of breakage - and maybe that's the better option - just make a sticky of common prefs to check

**Comment by Thorin-Oakenpants** [comment]
hah .. knew that account for ages - ever since you teased about it like a year ago (not sure if you realize just how much shit I look at!), I just happened to send you something for once

Just a quick look at the lists
- why not initially include the `26` hidden prefs into the `244` - just because they are hidden does not meant they couldn't cause breakage (prime example `dom.allow_cut_copy`)
- the current hardcoded list: I just did a quick edit and came up with at least 55 items we can remove: i.e.we focus on SITE breakage ONLY (ignore all UI stuff, caching, prefetching stuff, favicons on shortcuts, download dirs, search geo stuff, session stuff, one-off things like visited links color, password stuff - remove all the things that do not break sites )
- from the 26 hidden active prefs I think we could add nine of these to the hardcoded list (the GMP download stuff might be an issue as in it wouldn't DL instantly and be detected as the cause?)
- so we could end up in the first edit with 150 - 55 + 9 = 104
- I definitely think we could split this / re-order them so the most likely culprits are used first - that is reset first - eg cookies, workers, service workers, RFP, FPI, etc

:question: Do you want to start a new issue or do this via email?

- active prefs is a start for now (but longer term I think it could maybe cover "all" prefs, in case users flip things from inactive->active - not that our hardcoded list would be the lot)

**Comment by earthlng** [comment]
> why not initially include the 26 hidden prefs into the 244

Just needed a list to develop the script. I didn't want to include hidden prefs while dev-ing because they disappear from about:config when reset, that's all.

> remove all the things that do not break sites

totally agree. I didn't spend a lot of time looking at the list in detail, just removed the most glaring things that definitely don't need to be tested for, like app-update stuff, system-addon settings, safebrowsing, telemetry, etc.

> so we could end up in the first edit with 150 - 55 + 9 = 104

Nice, if we can get it below 128 that's 1 "NOW TEST AGAIN" loop less, so only 6 instead of the currently 7 tests needed to narrow down on the culprit.

>  the most likely culprits are used first 

they should be the last ones in the list to make pages fail most of the time, thus shorter page-loading times and therefore faster troubleshooting. Other than that it doesn't matter where they are positioned, it always requires the same number of loops to find the *one*.

Should I just commit the file and then we can take it from there? troubleshooter.js in the scratchpad-scripts folder?

**Comment by Thorin-Oakenpants** [comment]
>  troubleshooter.js in the scratchpad-scripts folder?

Is it run from the scratchpad? Then, yup :)

PS: did you see the PS I added in the previous post
PPS: do you need to add an anti-theft CHEF-KOCH declaration :trollface:

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/scratchpad-scripts/troubleshooter.js

> PS: OT: is this of any use to you?

looks interesting, thanks. Unfortunately doesn't work in ESR

> PPS: do you need to add an anti-theft CHEF-KOCH declaration :trollface: 

lol, I'll let you handle that

**Comment by silviuapostolescu** [comment]
Yes, I am.
Sorry for the late response but I just reinstall FF because my Gmail was
not working anymore.
Dont know why. I could open it but couldnt read messages. I was able to see
the messages title but when I clicked on it shows that it is loading but
never stops or open the message.
So, I decided to reinstall FF.

Silviu Apostolescu

2018-01-08 9:19 GMT+02:00 earthlng <notifications@github.com>:

**Comment by earthlng** [comment]
Hi Silviu, I've posted the script already so if you wanna try it, give it a shot.
I recommend to watch the video first to get an idea about how it's meant to be used.
If it helps you narrow down on the pref(s) that cause your gmail problems, please let us know.
In the video I used a new fresh profile but if you're certain that one of the user.js prefs is causing your problem, you can also run the script in your main profile. As long as you don't close the about:config tab prematurely while there's still an open prompt in it, there's nothing that can go wrong.

[script direct-download](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/scratchpad-scripts/troubleshooter.js) (right click -> save as)
demo video: https://anonfile.com/6eZ9v9d9b6/troubleshooter_vid.zip

**Comment by Thorin-Oakenpants** [comment]
First of all, no offence to Silviu - but he will struggle to run that script. Does anyone know the answers so we can save the time? Otherwise I will see if I can work it out (not that I ever access gmail from this machine, but hey, what the heck)

Silviu's Firefox *had* no user.js. All changes were done one by one via about:config. Reinstalling Firefox **shouldn't have changed his profile**. So why suddenly is gmail breaking. Unless a new profile was set up (and that's what is meant by installing a new firefox). I set Silviu up with a portable FF with the user.js in it - maybe he finally added the user.js to his original profile - IDK. Lacking a little info here

**Comment by earthlng** [comment]
The script is intended to help newbies and techies alike. I've even created a freakin video FFS

> Silviu's Firefox had no user.js.

doesn't matter. As long as someone doesn't close the about:config tab prematurely while there's still an open prompt in it, there's nothing that can go wrong.

**Comment by Thorin-Oakenpants** [comment]
> doesn't matter. As long as someone doesn't ...

I know that. I was trying to work out why Silviu's FF suddenly developed gmail-itis

**Comment by silviuapostolescu** [comment]
Yes, now I'm using only a portable FF and I have a user.js.
When I customize something I make small changes (personal preferences) also
to user.js and via about:config. Is it right?
Ty again for all your support.

Silviu Apostolescu

2018-01-14 13:28 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by Thorin-Oakenpants** [comment]
> When I customize something I make small changes (personal preferences) also to user.js and via about:config. Is it right?

YES :).

If you are just TESTING, then just reset it in about:config. When you have found the one causing the problem it NOT ONLY needs to be reset in about:config but also CHANGED in the user.js, otherwise the user.js will reapply the value you didn't want when firefox starts again

Are you using that portable Firefox I set up for you?

### example
You discovered that `network.http.referer.XOriginPolicy` was causing an issue with accessing your router.

In the current user.js it is this
```js
/* 1603: CROSS ORIGIN: control when to send a referer [SETUP]
... ***/
user_pref("network.http.referer.XOriginPolicy", 1);
```

Rather than change that line to `user_pref("network.http.referer.XOriginPolicy", 0);` it is better to add an override at the end (this makes it easier to update the user.js)

At the END of the user.js add the following
```js
// MY OVERRIDES
user_pref("network.http.referer.XOriginPolicy", 0); // 1603, breaks my router
```

It is advisable to create a `user-overrides.js` file and put your prefs in there for reference or as a master copy, this way you can just replace the user.js with the current one, and then re-paste your overrides to the end - makes updating the user.js easier.

As for your gmail problems, if I have time I will work out what you need to override

**Comment by silviuapostolescu** [comment]
Sorry for the late response/reply.
Yes, I do. I'm usig the portable FF.
Meanwhile, I made a few small changes in both files.
OK, ty for advices. Up to now, all my prefs were made in word file.
I followed also your recommandations from the site to identify the culprit
(when it is one).
I had some problems and made this change: ("security.OCSP.require",
false); true
cause some site breakage (google);

("webgl.min_capability_mode", true); > shrinks the movie image/window;

("full-screen-api.enabled", true); otherwise no full image on videos, no UI;

("network.cookie.cookieBehavior", 0);


On the other hand, I saw that you guys are creating add-ons and not only
regarding WoW that I play for many years.

Silviu Apostolescu

2018-01-15 16:52 GMT+02:00 Thorin-Oakenpants <notifications@github.com>:

**Comment by crssi** [comment]
@silviuapostolescu do you might have sample link for `webgl.min_capability_mode` problem?

**Comment by silviuapostolescu** [comment]
What do you mean by sample link ?
I don't understand what you are asking me.
How come sample link?
Aah, to show you a screenshot of the image that I claimed for?
I don't have, but I think that if I reverse to false that string it should
appear again.
The image was at the normal usually dimensions when you acces a movie. Not
at the full screen.

Silviu Apostolescu

2018-01-21 13:22 GMT+02:00 crssi <notifications@github.com>:

**Comment by kgbm3** [comment]
Just btw., it seems that Google has fixed their **security.OCSP.require** error (after a couple of weeks, since they had made the change).
