### ISSUE TITLE
Notes: Design & Implementation TBB

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#336]
Following on from the discussion in #333 .. I have been re-reading the doc at https://www.torproject.org/projects/torbrowser/design/index.html.en - its been a while since I read it, and seems like its had a few changes and updates

I'll just use this issue to make some notes as I come across them

**Comment by Thorin-Oakenpants** [comment]
> ### 4.1.4. Disabling system extensions and clearing the addon whitelist
> 
> Firefox addons can perform arbitrary activity on your computer, including bypassing Tor. It is for this reason we disable the addon whitelist (`xpinstall.whitelist.add`), so that users are prompted before installing addons regardless of the source. We also exclude system-level addons from the browser through the use of `extensions.enabledScopes` and `extensions.autoDisableScopes`. Furthermore, we set `extensions.systemAddon.update.url` and `extensions.hotfix.id` to an empty string in order to avoid the risk of getting extensions installed by Mozilla into Tor Browser. 

Notes:
- `xpinstall.whitelist.add` doesn't exist in desktop by the looks of it, but [DXR](https://dxr.mozilla.org/mozilla-central/search?q=xpinstall.whitelist.add&redirect=false) seems to indicate its used by android
- `extensions.autoDisableScopes` we set as `15` but TBB sets this as `0` - we should look at this further
   * note: we set `extensions.enabledScopes` = `1` same as TBB
- `extensions.hotfix.id` we do not blank - we should consider this

**Comment by Atavic** [comment]
>setting pref(“extensions.autoDisableScopes”, 0); should make sure nothing is disabled automatically

 see: https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/

**Comment by Thorin-Oakenpants** [comment]
Thanks Atavic, we have that link in the user.js, I've read the article before. I am just highlighting some diffs between us and TBB, and other interesting things

**Comment by earthlng** [comment]
* `extensions.autoDisableScopes`
https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#63
15 is what we want. Not sure why TBB sets it to 0. Maybe because their bundled addons would get disabled with 15
* `extensions.hotfix.id` - ATM it's only used when app update + app auto-install are both enabled. source: search for checkHotfix in https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManager.jsm.
There's also `extensions.hotfix.url` but it's only used when checkHotfix is true.
Since they seem to plan to change the whole hotfix + system addon update mechanism and maybe even get rid of app.update.enabled, I certainly don't mind adding this/these.

**Comment by Atavic** [comment]
Due to an [issue on pyllyukko repo](https://github.com/pyllyukko/user.js/issues/367) I finally had a look at the Tor prefs and most of them have some flaws IMHO

**Comment by earthlng** [comment]
FYI the whole `extensions.hotfix.*` was removed in [FF60](https://bugzilla.mozilla.org/show_bug.cgi?id=1356331) ([meta ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1355935), [wiki](https://wiki.mozilla.org/Add-ons/HotfixRemoval))

**Comment by Thorin-Oakenpants** [comment]
It's also interesting to follow all the tickets for the new Enterprise/Policy thingie which Mike Kaply is working on - lots of new prefs

**Comment by Thorin-Oakenpants** [comment]
OT: https://www.wired.com/story/hansa-dutch-police-sting-operation/

OMG .. so many OpSec failures: IRC (server) logs (reminds me of Lulzsec), and what about the dealers and geolocation metadata in their images .. WTF?

> As they tell it, the police eventually became so brazen that they staged a fake server glitch that deleted all the photos from the site, forcing sellers to re-upload photos and giving Dutch authorities another chance to capture the metadata. That ruse alone snagged the geolocated coordinates of more than 50 dealers

Relevant tor ticket: https://trac.torproject.org/projects/tor/ticket/24965

**Comment by Thorin-Oakenpants** [comment]
Also https://xkcd.com/538/

> Under questioning in a German jail, the two men handed over credentials to their accounts

They were nabbed with their machine's logged in and unencrypted (reminds me of police directives to nab phones when unlocked), this is about their online accounts. So long story short, you can't trust anyone. Mitigate the damage beforehand.

**Comment by Thorin-Oakenpants** [comment]
Closing this. When TBB based on ESR60 comes out, we will do a diff as a long overdue exercise.

I also don't think there is anything I can really do with that document. It's a bit "tattered" with various edits, and has some outdated and/or irrelevant info.
