### ISSUE TITLE
discussion: move section 5000 (personal) to a separate js file

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#338]
the personal section, which is **clearly labelled**, does not belong in this user.js. It is a great resource that can still be expanded/built upon, and does not have to be lost.

I propose that we create a `user-personal.js` (or some other name, eg `user-other.js` or `user-misc.js`) and move all of this into there with a wee header saying that if anyone wishes to, they can incorporate these into their `user-overrides.js` (or append them manually). We would keep the numbering, and maybe in the user.js where section 5000 is/was we can reference the other file

**Comment by Thorin-Oakenpants** [comment]
Reference: incessant whining in #337 xD

**Comment by 2glops** [comment]
It sounds logical to move all personal settings away from user.js.
My "overrides.js" already contains such prefs.

**Comment by overdodactyl** [comment]
Sounds like a reasonable idea to me.

We could account for this in the updater scripts as well if desired.  (if `user-personal.js` file exists, create a backup, download the new one, append to `user.js`)...this would keep the automation of updating things provided here, while keeping `user-overrides.js` for changes not "endorsed" in your repo

**Comment by overdodactyl** [comment]
^^ That method would require the user to initially have downloaded the `user-personal.js` file.  The other option would be to provide a prompt each time asking, but from a personal standpoint, I would rather not see an additional prompt every time the script is run and manually download `user-personal.js` initially

**Comment by Thorin-Oakenpants** [comment]
I don't think we want to incorporate this into the updater - people can view it online or read our changelogs and just add it to **their** "overrides" - this keeps it simple

**Comment by overdodactyl** [comment]
Obviously up to you, but I would consider a couple line `if` statement much simpler than reviewing changlelogs and manually adding, removing or adjusting preferences - or at the very least, less tedious, time consuming and error prone - which was part of what the updater script were aimed to eliminate. If you're going to maintain a separate `.js` file in this repo, why not leverage the already available scripts to make it easy to use and keep up with?

**Comment by Thorin-Oakenpants** [comment]
well if you want to ... and claustro would want to update his windows one as well. we would need to decide on a file name ... i'd almost do the commits now, except I better wait for earthlng

**Comment by overdodactyl** [comment]
I'd be more than happy to update `.sh` file.  I know clasutro's grew to be a little more complicated, so perhaps it's not as easy of an addition (haven't looked at it super recently)...so perhaps we should wait to see what he says about it before roping him into more work haha

**Comment by overdodactyl** [comment]
If you choose to go this route, I've made the necessary changes to `updater.sh`.  Just would need the file name and url and I can submit a PR :) 

No hard feelings if you don't want this included though Pants...I'll just keep the script for my personal use haha

**Comment by grauenwolfe** [comment]
Here's my take on it. Yes, it's clearly labelled as PERSONAL SETTINGS and should be understood as such. It's essentially impossible to cover all bases when dealing with ignorance / laziness on the part of other people using something whether it's the ghacksuser.js or whatever else it may be.

Being that it is clearly labelled as PERSONAL, it's never bothered me but I don't think it's necessary and have always ignored it's entires.

The effort is greatly appreciated but my final verdict is to get rid of it, at least from the user.js.

**Comment by Thorin-Oakenpants** [comment]
it's 6.06kb that we can shave off the MONSTROUS size of the user.js - which it is only read once on startup, and although every pref is held in memory anyway (see about:config), apparently slows down FF when it is running, according to CHEF-KOCH

**Comment by earthlng** [comment]
I don't like the idea tbh. If this is mainly about `ui.submenuDelay` I'd rather just make that inactive.
IMO 5000 is a neat little appendix to enhance the general "Firefox experience". As @grauenwolfe said, nobody is bothered by having that little bit extra at the very end of the file. But I think if you would get rid of it entirely you would start to notice a lot of little annoyances in Firefox. For example I saw a comment on reddit once where someone said he wished he had known about `browser.urlbar.clickSelectsAll` years ago. Similarly IMHO `general.warnOnAboutConfig` absolutely belongs in any extended user.js.
And then there's also the issue that some users are already overwhelmed with just having to deal with 1 file.
So IMO either we deem them not interesting enough and remove them entirely or we keep it as it is.
We can reorganize it a bit which is something I wanted to do anyway but never brought it up. For example
move warnOnAboutConfig to 0000, 5002 fits better right next to 2418 (where we could also add `("full-screen-api.transition-duration.enter", "0 0")`, and maybe most importantly group all the Tabs Behaviour stuff nicely together. That's actually one of the few remaining parts that I never got around to adjust to this user.js and always kept the old 12bytes format because I just like it better that way:
```js
//// === TABS === ////

user_pref("browser.link.open_newwindow", 3);                    // [integer] controls when a new window/tab should be opened - 1=open links that open in a new window in the current tab, 2=open links that open in a new window in a new window, 3=open links that open in a new window in a new tab in the current window
user_pref("browser.link.open_newwindow.restriction", 0);        // [integer] controls when a new window/tab should be opened - 0=divert all links according to browser.link.open_newwindow, 1=do not divert any links, 2=divert all links according to browser.link.open_newwindow, unless the new window specifies how it should be displayed
user_pref("browser.link.open_newwindow.override.external", 3);  // [integer] open links from external programs in: -1=default, 1=the current tab, 2=a new window, 3=a new tab

user_pref("browser.tabs.closeWindowWithLastTab", true);         // [boolean] whether to exit FF when closing last tab
user_pref("browser.tabs.insertRelatedAfterCurrent", true); // open links in a new tab immediately to the right of parent tab, not far right
user_pref("browser.tabs.loadDivertedInBackground", false);      // [boolean] cause links opened from external programs to open in a new background tab
user_pref("browser.tabs.loadInBackground", true);               // [boolean] focus new tabs instead of loading them in the background
user_pref("browser.tabs.selectOwnerOnClose", true);             // [boolean] focus the parent tab when a child tab is closed
user_pref("browser.tabs.warnOnClose", false);                   // [boolean] disable warning when closing multiple tabs
user_pref("browser.tabs.warnOnCloseOtherTabs", true);          // [boolean] disable warning when closing other tabs
user_pref("browser.tabs.warnOnOpen", true);                    // [boolean] disable warning when opening too many tabs
```

**Comment by smithfred** [comment]
> But I think if you would get rid of it entirely you would start to notice a lot of little annoyances in Firefox. For example I saw a comment on reddit once where someone said he wished he had known about browser.urlbar.clickSelectsAll years ago.

This is an argument for having them documented somewhere on the project, yes - whether in the user.js file, or elsewhere if there is a performance impact.

What it doesn't really justify though is having the settings active. While 95% of them are actually settings I'd already customised the same way (so having them active benefits me), I think it makes more sense to have them inactive, and keep the active settings focused on privacy/security.

**Comment by claustromaniac** [comment]
> /*** 5000: PERSONAL SETTINGS [SETUP]
>      Settings that are handy to migrate and/or are not in the Options interface. **Users
>      can put their own non-security/privacy/fingerprinting/tracking stuff here** ***/

By the given definition, I think the items in section 5000 are of the sort the `user-overrides.js` is there for nowadays. 

We're facing, broadly, two usage scenarios: the user manually downloads and edits `user.js` directly, or the user uses the updater scripts. For the first sort of user, having all settings in a single file should be slightly more convenient, even if they come inactive by default. For the second sort, it should be OK either way because if we modify the scripts so they can manage both files, all settings will end up in `user.js` anyway. 

If we wanted to prioritise convenience, we should leave those items in the same file, but maybe we should reorder them and rename the section. If we wanted the project to focus more on its main scope instead, we should move those items to a separate file. Then, there is the middle ground that @smithfred ~~bitched about~~ suggested originally: leaving the section in that file, but making the settings inactive by default. 

If you ask me, I see them all as valid routes. I would personally prefer if that section was moved to a separate `user-misc` file, or something like that, but I don't think of it as being a generally better idea than any of the other options.

**Comment by kgbm3** [comment]
What I don't get is how come that **general.warnOnAboutConfig** has been moved from the _/*** 5000: PERSONAL SETTINGS [SETUP]_ section, where all of the other settings remain (for the time being?) and given it's own (top) section: _/* 0000: disable about:config warning ***/_

P.S. This guy, CHEF-KOCH, when is he -just- going to start giving credit to other people - where he has been using their work... It's such a simple thing to do, right?

**Comment by Thorin-Oakenpants** [comment]
> What I don't get is how come that general.warnOnAboutConfig has been moved from the /*** 5000: PERSONAL SETTINGS [SETUP] section, where all of the other settings remain (for the time being?) and given its own (top) section: /* 0000: disable about:config warning ***/

Not moved because of any upcoming changes - it was put there for practical reasons. Anyone using a user.js is highly likely to want/need to fiddle/test/play/look-shit-up in about:config: it has nothing to do with privacy/security/anonymity/tracking/anti-FPing .. but it has everything to do with working with those things in FF.

That said, it's pretty useless after the first warning, as anyone using a user.js etc would have already ticked the "don't warn me again"

> ^^ Which I'm doing, with Notepad++, since I've not yet figured out how to do the whole script-GitHub thing (for some reason, it's (always) giving me (some) trouble on Windows, blah.)

The easiest way is to keep overrides in a user-overrides.js (just as a master copy), which you can paste on the end of the user.js, which you replace every alpha release. Every alpha release, read the changelogs we provide. The updater.bat does all that for you (except the reading changelog bit).

I'll do the steps for you (you don't even need the updater.bat or user-overrides.js)
- user.js has your overrides/changes/extra things at the very end eg in a section called `// my overrides`
- new alpha release comes out
- open user.js, select everything above your override section and delete, go to the [raw](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/user.js) new release, select al, copy, paste into top of user.js, save
- read changelog for new version and make changes if required to your overrides section

^^ ***ZERO need to do diffs and compares***

Personally, mine is always in sync - since its only myself or earthlng doing the commits. But seriously, living here is detrimental to your health & social welfare, so I recommend most users just check and fiddle around when we do alpha releases, thus leaving time to pursue other things in life

**Comment by Thorin-Oakenpants** [comment]
I have made a decision - all the naysayers about having "personal" stuff in the user.js (like CHEF-KOCH The Plagiarizer) can go and get f**ked.

- It makes more sense to me to keep it all in the one file: easier for end users (lowest common denominators and all that)
- section is clearly labelled (although we could change the title) - most of them are about the UI/Workflow
- a lot of these are relevant to the people who use this (lets face it, we're into tweaking and shit) and it seems that most/a-lot of the active settings are what most people use (eg annoying warnings, opening source in a new tab allows split screen or multi-monitor, etc) - but we can certainly explore making more of them inactive
- ^^ i.e this is an extended user.js, these items make sense being in here
- we could expand on it - see https://www.reddit.com/r/firefox/wiki/aboutconfig where due to the number of times people asked about things, r/Firefox added this wiki section (see Behaviour and Appearance)
- very very very few people have ever complained about the personal section being in here and their main argument would be that 1) it has nothing to do with "hardening" etc (no sh*t sherlock, read the section title) and 2) bitching about bloat (here's some news, it's comprehensive, backwards compatible i.e large deprecated section, and already lengthy even if the section is removed)
- almost everyone else besides those few, actually welcome and like these nuggets

So I'll close this and start a new issue for a section 5000 revamp and new additions. We could order things better & expand the, if need be eg earthlng's idea about the tabs settings, adding delay info to full-screen etc

**Comment by smithfred** [comment]
> all the naysayers about having "personal" stuff in the user.js [...] can go and get f**ked.

This is not good project management.

> (like CHEF-KOCH The Plagiarizer)

Logical fallacy to imply that that person's opinion is relevant either way.

It depends what ghacks-user.js is. Is it a project of "random crap that Thorin-Oakenpants likes, includes privacy stuff"? (Your prerogative if it is). Or is it "this will secure and increase the privacy of Firefox, and is intended for public consumption and contribution"?

**Comment by smithfred** [comment]
I'm going to contend that a better approach would be to modularise this (with a "build" script if necessary).

e.g. "build --shouldersurfing --localaccess --tracking-paranoid --hacking-medium --ux"

Then make the project e.g.:

user-shouldersurfing-minimal.js
user-shouldersurfing-medium.js
user-shouldersurfing-paranoid.js
user-tracking-...

etc.

And you can still include a user.js file, that's just the result of 'build --kitchensink' or whatever, so the build script isn't necessary if someone wants to keep the defaults.

The build script can be trivial (so it's easily user-auditable) too.

**Comment by Thorin-Oakenpants** [comment]
You make it sound so easy :)

There are too many items with multiple aspects to be able categorize this with any consistency based on type of threat, so it becomes subjective. But items could have multiple threat categories which adds even more complexity. Additional parameters for severity (med-hard-etc) are also subjective. And that's only a 2 dimensional approach of slicing & dicing. You would need to look at handling whether prefs should be active/inactive and I'm guessing all prefs should be set up with the same aim (every pref at active *must* restrict, for simplicity), and every pref added must be active(?). Now add a fourth parameter, it would need to handle different pref values for different severity modes. Also note that some prefs need to be kept together for a complete picture which adds more complexity (eg referrers). Not to mention deprecated and RFP alternative issues. And handle references to other prefs which may or may not end up in the build. Also consider that users who leave out certain parameters then have an incomplete user.js lacking in comprehensiveness (and some prefs are inactive and in there for info only) - it is no longer a template or single file for reference.

Not saying that this couldn't be done in some elegant way, but it's not easy - a lot of work to set up and maintain. It's hard enough as it is just categorizing as per our sections in a simple txt based file. What you're proposing is not feasible for this project, and even if it were - whatever we do, and however the prefs are dissected, and whatever settings are for some prefs for relaxed-med-hard, not everyone will be happy - in fact I would say almost everyone would NOT be happy.

What you have in front of you is a single simplified file, 3 years in the making, and the cause of lots of discussions (and some bickering) ... if you want to modularize what is a complex, intertwined, multi-faceted, hot-mess of around 600 prefs into some sort of magical subjectively utopian output per user, that handles all possible combinations, then be my guest.

**Comment by Thorin-Oakenpants** [comment]
Back on topic...

> Is it a project of "random crap that Thorin-Oakenpants likes, includes privacy stuff"?

That is such a disgusting sentence, but I get your drift, phrasing it that way to emphasize your point. Anyone who actually thinks that way clearly has not looked at the user.js.

I have always been subjective. I have actually kept the personal section entries limited - it's not about what I want in there, half them I don't give a damn about. But it is what it is - damn handy information that users have appreciated and suggested. So the question is not about having them, but about ***what to do with them***

***There is no right or wrong answer here*** - some favor a separate file, others don't, and others couldn't care less. ***The decision has been made***. Keep it simple, in the same file.

A new issue has been created to address any concerns: such as making prefs inactive, add/remove items, even renaming the section. There is absolutely no reason why we can't have such a section.

At the end of the day, not everyone will be happy no matter what we do. I'm not dismissive of ideas, I ask for feedback, I consider options. But a decision had been made. Accept it. HOW hard is it for YOU to simply delete the 5000 section - done, solved, your issue is fixed.

**Comment by Thorin-Oakenpants** [comment]
> Is there anything that ties the personal section to the rest of the file? Is it actually part of the hot mess?

No. None of it is directly concerned with the "mission statement" in the readme.md

> The ghacks user.js is a template, which, as provided, aims to provide as much privacy and enhanced security as possible, and to reduce tracking and fingerprinting as much as possible - while minimizing any loss of functionality and breakage (but it will happen).

We can easily fix that by adding something like "We also have collection of other handy prefs for your info (section 5000)", if pedantically minded people really feel the need - I say pedantic, but I guess it should be said (I'm not an outsider looking in, so I have blind spots)

> As per the prev. comment the separate files could be pre-combined into a default user.js for continued "get and forget" use.

This is OT (modularizing), but you said -kitchensink. Also, the problem still arises about providing what as active/inactive if everything is to be included - a switch for severity would be mandatory IMO.

> The file pretty much requires the user knows what they're doing

Even modularizing it does not solve this. WHAT does solve this is having a relaxed branch or a relaxed-user.js for appending or even as a list of items in a sticky topic - so users can apply 90% of what we have with zero/tiny breakage. This has always been on the cards to do.

**Comment by claustromaniac** [comment]
,,,

If I were to script something like that I think I would add tags to every item instead of putting them in separate files. The script could then decide what to ditch and what to keep based on those tags and user preference.

It would be far from trivial, though. I'm not known for writing audit-friendly code. @earthlng knows this first-hand.

Well, actually, I'm not really known for anything at all.

...

Just ignore this comment.

**Comment by smithfred** [comment]
> That is such a disgusting sentence, but I get your drift, phrasing it that way to emphasize your point.

Yep, hyperbole for effect. I wouldn't go so far as to call it "disgusting" ;)

> No. None of it is directly concerned with the "mission statement" in the readme.md

OK, what it comes down to for me is, if a project has a clear focus, and defined intentions/goals, which are applied reasonably consistently, then it makes contributing to the project appealing.

OTOH, if it looks like there are things like a lack of focus, inconsistent adherence to stated project mission/scope, or dictatorial decision-making, contribution becomes less appealing.

To be clear, it's entirely up to a project owner how they want to run their project and I mean that sincerely - you don't owe anything to anyone and have obviously already contributed a great deal to Firefox users with this.

The difference that different approaches to managing things make to how much outside contribution may also be negligible and/or not matter for you, which is also fine. But it's worth being aware of it at least.

I'd look at it as, "how can we make a secure and privacy-respecting browsing experience as easy and robust as possible", and "how can the community desire for this be organised/focused to push Mozilla to prioritise this goal upstream".

A consistent, focused, well-managed project would have a lot more weight in trying to get upstream to make useful changes to compliment (or obsolete) this work.
