### ISSUE TITLE
troubleshooter.js: clean up prefs list

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#339]
* [x] finalize list
* [x] put most common breakage prefs at the start
* [x] group items for possible dependencies
* [x] find a permanent home for video
* [x] update troubleshooting wiki page

**Comment by earthlng** [comment]
Good work on that list mate, thanks!
I've gone over it and removed most of them: https://github.com/ghacksuserjs/ghacks-user.js/commit/a3bffb83bd2e34dc0881692559c28b2e120f95d2
Down to 79. Some of the ones I didn't remove can't break pages but they are standalone prefs and there's no harm to leave them in the list IMO.

I've also removed ...
* all GMP + EME prefs because multiple prefs need to be reset to enable that shit
* all the `media.peerconnection.*` + the 2 `media.navigator.*` prefs (=WebRTC) for the same reason.
* `captivedetect.canonicalURL` + `network.captive-portal-service.enabled`

**Comment by Thorin-Oakenpants** [comment]
Thanks for the commit - GMP+EME etc - yeah, and it may even have to download them.

I kinda disagree with some of the stuff kept - all that `browser.urlbar.`, `keyword` stuff is UI, visited links color is not important - I think we should prune more heavily and focus only on actual website breakage - **but lets revisit the final list later on for refinement** (maybe, probably not, we could get it down to 64! - not likely?)

Next step I guess is to look at `inactive at non-default` and cherry pick them for addition - do we have a list of `inactive at non-default`?

**Comment by earthlng** [comment]
> I kinda disagree with some of the stuff kept 

yeah but it's kinda neat that the script can also help someone narrow down on those things as well.
And since we are most likely not gonna get it down to below 64, it doesn't really matter that they're in the list too.

> do we have a list of inactive at non-default?

<details><summary>inactive prefs by category</summary><p>

```js
// hidden, future-proofing and whatnot:
pref("browser.cache.memory.capacity", 0);
pref("browser.tabs.remote.autostart.2", true);
pref("browser.tabs.remote.force-enable", true);
pref("font.system.whitelist", "");
pref("general.appname.override", "Netscape");
pref("general.appversion.override", "5.0 (Windows)");
pref("general.buildID.override", "20100101");
pref("general.oscpu.override", "Windows NT 6.1");
pref("general.platform.override", "Win32");
pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0");
pref("geo.wifi.logging.enabled", true);
pref("permissions.memory_only", true);
pref("privacy.resistFingerprinting.block_mozAddonManager", true);
pref("privacy.window.maxInnerHeight", 900);
pref("privacy.window.maxInnerWidth", 1600);
pref("security.insecure_connection_icon.pbmode.enabled", true);
pref("security.nocertdb", true);

// non-default:
pref("accessibility.typeaheadfind", true);
pref("app.update.enabled", false);
pref("browser.cache.memory.enable", false);
pref("browser.chrome.favicons", false);
pref("browser.chrome.site_icons", false);
pref("browser.download.autohideButton", false);
pref("browser.privatebrowsing.autostart", true);
pref("browser.safebrowsing.allowOverride", false);
pref("browser.safebrowsing.blockedURIs.enabled", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.safebrowsing.provider.google.gethashURL", "");
pref("browser.safebrowsing.provider.google.updateURL", "");
pref("browser.safebrowsing.provider.google4.gethashURL", "");
pref("browser.safebrowsing.provider.google4.updateURL", "");
pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
pref("browser.safebrowsing.provider.mozilla.updateURL", "");
pref("browser.sessionhistory.max_total_viewers", 0);
pref("browser.startup.homepage", "https://www.example.com/");
pref("browser.startup.page", 0);
pref("browser.tabs.loadBookmarksInTabs", true);
pref("browser.tabs.remote.autostart", true);
pref("browser.urlbar.maxRichResults", 0);
pref("dom.event.contextmenu.enabled", false);
pref("dom.indexedDB.enabled", false);
pref("dom.ipc.plugins.sandbox-level.default", "donotuse");
pref("dom.ipc.plugins.sandbox-level.flash", "donotuse");
pref("dom.ipc.processCount", 4);
pref("dom.storage.enabled", false);
pref("dom.vr.enabled", false);
pref("extensions.e10sBlocksEnabling", false);
pref("extensions.screenshots.disabled", true);
pref("extensions.systemAddon.update.url", "");
pref("extensions.update.enabled", false);
pref("font.name.monospace.x-unicode", "Lucida Console");
pref("font.name.monospace.x-western", "Lucida Console");
pref("font.name.sans-serif.x-unicode", "Arial");
pref("font.name.sans-serif.x-western", "Arial");
pref("font.name.serif.x-unicode", "Georgia");
pref("font.name.serif.x-western", "Georgia");
pref("full-screen-api.warning.delay", 0);
pref("full-screen-api.warning.timeout", 0);
pref("general.autoScroll", false);
pref("gfx.direct2d.disabled", true);
pref("javascript.options.baselinejit", false);
pref("javascript.options.ion", false);
pref("media.flac.enabled", false);
pref("media.mediasource.enabled", false);
pref("media.mediasource.mp4.enabled", false);
pref("media.mediasource.webm.audio.enabled", false);
pref("media.mp4.enabled", false);
pref("media.ogg.enabled", false);
pref("media.ogg.flac.enabled", false);
pref("media.opus.enabled", false);
pref("media.raw.enabled", false);
pref("media.wave.enabled", false);
pref("media.webm.enabled", false);
pref("media.wmf.enabled", false);
pref("media.wmf.vp9.enabled", false);
pref("network.dns.disableIPv6", true);
pref("places.history.enabled", false);
pref("plugin.state.flash", 0);
pref("privacy.clearOnShutdown.openWindows", true);
pref("privacy.cpd.openWindows", true);
pref("privacy.trackingprotection.annotate_channels", false);
pref("privacy.trackingprotection.enabled", true);
pref("privacy.usercontext.about_newtab_segregation.enabled", true);
pref("privacy.userContext.enabled", true);
pref("privacy.userContext.longPressBehavior", 2);
pref("privacy.userContext.ui.enabled", true);
pref("reader.parse-on-load.enabled", false);
pref("security.sandbox.content.level", "donotuse");
pref("security.sandbox.logging.enabled", true);
pref("security.ssl.require_safe_negotiation", true);
pref("security.ssl3.dhe_rsa_aes_128_sha", false);
pref("security.ssl3.dhe_rsa_aes_256_sha", false);
pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
pref("security.ssl3.rsa_aes_128_sha", false);
pref("security.ssl3.rsa_aes_256_sha", false);
pref("security.ssl3.rsa_des_ede3_sha", false);
pref("services.blocklist.addons.collection", "");
pref("services.blocklist.gfx.collection", "");
pref("services.blocklist.onecrl.collection", "");
pref("services.blocklist.plugins.collection", "");
pref("signon.rememberSignons", false);
pref("svg.disabled", true);
pref("toolkit.cosmeticAnimations.enabled", false);
pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256,content-track-digest256");
pref("xpinstall.signatures.required", false);

// matching default value:
pref("browser.stopReloadAnimation.enabled", true);
pref("clipboard.autocopy", false);
pref("dom.ipc.processCount.extension", 1);
pref("dom.ipc.processCount.file", 1);
pref("dom.presentation.controller.enabled", false);
pref("dom.presentation.discoverable", false);
pref("dom.presentation.discovery.enabled", false);
pref("dom.presentation.enabled", false);
pref("dom.presentation.receiver.enabled", false);
pref("dom.presentation.session_transport.data_channel.enable", false);
pref("extensions.webextensions.remote", true);
pref("media.mediasource.webm.enabled", false);
pref("media.wmf.amd.vp9.enabled", true);
pref("network.cookie.lifetime.days", 90);
pref("network.cookie.lifetimePolicy", 0);
pref("network.dnsCacheEntries", 400);
pref("network.dnsCacheExpiration", 60);
pref("network.http.fast-fallback-to-IPv4", true);
pref("offline-apps.quota.warn", 51200);
pref("privacy.cpd.downloads", true);
pref("privacy.trackingprotection.lower_network_priority", false);
pref("privacy.trackingprotection.pbmode.enabled", true);
```

</p></details>

^^ based on the master user.js and compared against FF57.0.4 default values.

**Comment by Thorin-Oakenpants** [comment]
I think I can narrow that lot ^^ down to about 20 or 30 prefs - but I'll have to do it another day - got stuff to see and people to do

**Comment by Thorin-Oakenpants** [comment]
### to consider

```js
// hidden, future-proofing and whatnot:
pref("font.system.whitelist", "");
pref("permissions.memory_only", true);
pref("privacy.window.maxInnerHeight", 900);
pref("privacy.window.maxInnerWidth", 1600);
pref("security.nocertdb", true);

// non-default:
pref("dom.event.contextmenu.enabled", false);
pref("dom.indexedDB.enabled", false);
pref("dom.storage.enabled", false);
pref("dom.vr.enabled", false);
pref("gfx.direct2d.disabled", true); // i think this requires a restart
pref("javascript.options.baselinejit", false);
pref("javascript.options.ion", false);
pref("media.flac.enabled", false);
pref("media.mediasource.enabled", false);
pref("media.mediasource.mp4.enabled", false);
pref("media.mediasource.webm.audio.enabled", false);
pref("media.mp4.enabled", false);
pref("media.ogg.enabled", false);
pref("media.ogg.flac.enabled", false);
pref("media.opus.enabled", false);
pref("media.raw.enabled", false);
pref("media.wave.enabled", false);
pref("media.webm.enabled", false);
pref("media.wmf.enabled", false);
pref("media.wmf.vp9.enabled", false);
pref("plugin.state.flash", 0); // flash sucks
pref("privacy.userContext.enabled", true);
pref("reader.parse-on-load.enabled", false);
pref("security.ssl.require_safe_negotiation", true);
pref("security.ssl3.dhe_rsa_aes_128_sha", false);
pref("security.ssl3.dhe_rsa_aes_256_sha", false);
pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
pref("security.ssl3.rsa_aes_128_sha", false);
pref("security.ssl3.rsa_aes_256_sha", false);
pref("security.ssl3.rsa_des_ede3_sha", false);
pref("signon.rememberSignons", false);
pref("svg.disabled", true);
pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256,content-track-digest256");
```


### ignore

<details><summary>ignore</summary><p>

```js
// hidden, future-proofing and whatnot:
pref("browser.cache.memory.capacity", 0);
pref("browser.tabs.remote.autostart.2", true); // e10s stuff
pref("browser.tabs.remote.force-enable", true); // ditto
pref("general.appname.override", "Netscape"); // lets not encourage UA spoofing this way
pref("general.appversion.override", "5.0 (Windows)");
pref("general.buildID.override", "20100101");
pref("general.oscpu.override", "Windows NT 6.1");
pref("general.platform.override", "Win32");
pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0");
pref("geo.wifi.logging.enabled", true);
pref("privacy.resistFingerprinting.block_mozAddonManager", true);
pref("security.insecure_connection_icon.pbmode.enabled", true);

// non-default:
pref("accessibility.typeaheadfind", true);
pref("app.update.enabled", false);
pref("browser.cache.memory.enable", false);
pref("browser.chrome.favicons", false);
pref("browser.chrome.site_icons", false);
pref("browser.download.autohideButton", false);
pref("browser.privatebrowsing.autostart", true); // requires a restart
pref("browser.safebrowsing.allowOverride", false);
pref("browser.safebrowsing.blockedURIs.enabled", false);
pref("browser.safebrowsing.downloads.enabled", false);
pref("browser.safebrowsing.downloads.remote.block_dangerous", false);
pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false);
pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
pref("browser.safebrowsing.malware.enabled", false);
pref("browser.safebrowsing.phishing.enabled", false);
pref("browser.safebrowsing.provider.google.gethashURL", "");
pref("browser.safebrowsing.provider.google.updateURL", "");
pref("browser.safebrowsing.provider.google4.gethashURL", "");
pref("browser.safebrowsing.provider.google4.updateURL", "");
pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
pref("browser.safebrowsing.provider.mozilla.updateURL", "");
pref("browser.sessionhistory.max_total_viewers", 0);
pref("browser.startup.homepage", "https://www.example.com/");
pref("browser.startup.page", 0);
pref("browser.tabs.loadBookmarksInTabs", true);
pref("browser.tabs.remote.autostart", true); // e10s stuff
pref("browser.urlbar.maxRichResults", 0);
pref("dom.ipc.plugins.sandbox-level.default", "donotuse");
pref("dom.ipc.plugins.sandbox-level.flash", "donotuse");
pref("dom.ipc.processCount", 4);
pref("extensions.e10sBlocksEnabling", false); // e10s stuff
pref("extensions.screenshots.disabled", true);
pref("extensions.systemAddon.update.url", "");
pref("extensions.update.enabled", false);
pref("font.name.monospace.x-unicode", "Lucida Console");
pref("font.name.monospace.x-western", "Lucida Console");
pref("font.name.sans-serif.x-unicode", "Arial");
pref("font.name.sans-serif.x-western", "Arial");
pref("font.name.serif.x-unicode", "Georgia");
pref("font.name.serif.x-western", "Georgia");
pref("full-screen-api.warning.delay", 0);
pref("full-screen-api.warning.timeout", 0);
pref("general.autoScroll", false);
pref("network.dns.disableIPv6", true);
pref("places.history.enabled", false);
pref("privacy.clearOnShutdown.openWindows", true);
pref("privacy.cpd.openWindows", true);
pref("privacy.trackingprotection.annotate_channels", false);
pref("privacy.trackingprotection.enabled", true); // already manually added
pref("privacy.usercontext.about_newtab_segregation.enabled", true);
pref("privacy.userContext.longPressBehavior", 2);
pref("privacy.userContext.ui.enabled", true);
pref("services.blocklist.addons.collection", "");
pref("services.blocklist.gfx.collection", "");
pref("services.blocklist.onecrl.collection", "");
pref("services.blocklist.plugins.collection", "");
pref("security.sandbox.content.level", "donotuse");
pref("security.sandbox.logging.enabled", true);
pref("toolkit.cosmeticAnimations.enabled", false);
pref("xpinstall.signatures.required", false);

// matching default value:
pref("browser.stopReloadAnimation.enabled", true);
pref("clipboard.autocopy", false);
pref("dom.ipc.processCount.extension", 1);
pref("dom.ipc.processCount.file", 1);
pref("dom.presentation.controller.enabled", false);
pref("dom.presentation.discoverable", false);
pref("dom.presentation.discovery.enabled", false);
pref("dom.presentation.enabled", false);
pref("dom.presentation.receiver.enabled", false);
pref("dom.presentation.session_transport.data_channel.enable", false);
pref("extensions.webextensions.remote", true);
pref("media.mediasource.webm.enabled", false);
pref("media.wmf.amd.vp9.enabled", true);
pref("network.cookie.lifetime.days", 90);
pref("network.cookie.lifetimePolicy", 0);
pref("network.dnsCacheEntries", 400);
pref("network.dnsCacheExpiration", 60);
pref("network.http.fast-fallback-to-IPv4", true);
pref("offline-apps.quota.warn", 51200);
pref("privacy.cpd.downloads", true);
pref("privacy.trackingprotection.lower_network_priority", false);
pref("privacy.trackingprotection.pbmode.enabled", true);
```

</p></details>

**Comment by Thorin-Oakenpants** [comment]
Note: we should also update the troubleshooting wiki page with link to the video (is that going to stay there forever?) and script

**Comment by Thorin-Oakenpants** [comment]
Question: this 32-64-128 thing. Probably not important, since we are likely to end up between 64-128 anyway (and prefs that differ from default are unlikely to < 64) ...

The original array is based on the list we provide. Why doesn't the array remove all items already at default (hidden may be problematic) and redim or whatever (and this is the new master list in memory) - this should reduce the size for most users. Again, unlkely to get under 64 so probably not worth it?

**Comment by earthlng** [comment]
Sure why not, it's easy to implement.

**Comment by earthlng** [comment]
> Note: we should also update the troubleshooting wiki page with link to the video (is that going to stay there forever?) and script

Absolutely. You're the wiki wizard - what are you waiting for? :smile: 
"is that going to stay there forever" - IDK but probably not

> // hidden, future-proofing and whatnot:
> // these three are problematic

I agree. It's possible that they require a restart but regardless of that ...
* font.system.whitelist - people messing with this should also know where to look in case of breakage
* permissions.memory_only - I don't think this can cause any site breakage
* security.nocertdb - shouldn't cause breakage but more importantly I don't want to mess with this if someone decides to use it

// non-default:
I agree with most of it except for these:
* gfx.direct2d.disabled
probably restart required and is risky because it used to be in combination with the other HW-accel pref
* javascript.options.baselinejit + javascript.options.ion
very unlikely to cause breakage - performance impact only
and not messing with this because people using this, explicitly don't want the potential risks
* privacy.userContext.enabled - risky and shouldn't cause any breakage anyway
* signon.rememberSignons - can't cause breakage because if someone set it to false they won't have any passwords stored
* urlclassifier.trackingTable - blocking tracking stuff shouldn't case breakage
* media.mediasource.* stuff - probably needs more than 1 pref cleared to un-break something.
* reader.parse-on-load.enabled - impossible to break something
* media.ogg.flac.enabled - relies on media.ogg.enabled
* media.wmf.vp9.enabled + media.wmf.amd.vp9.enabled - rely on media.wmf.enabled

**Comment by Thorin-Oakenpants** [comment]
> javascript.options.baselinejit + javascript.options.ion

it did break stuff in the past. I had these disabled in the past for about 6 months and things like dropdowns and checkboxes could go haywire

> people messing with this should also know where to look in case of breakage

In general this could apply to everything that is inactive and we don't need to do any more! But I get your point, it's not like a boolean :) And yeah, fonts don't typically break things - I didn't leave the default fonts in. Fonts currently also requires a restart AFAIUK, although that may change with RFP+fonts-via-kinto.

> gfx.direct2d.disabled

Yeah, I said I think a restart is required. Now I'm sure it is. Yup, that other HW pref was windows but its not used anymore. However, there are other platforms specific graphic things etc, and I would not be surprised if the UI covers a few prefs via code

> privacy.userContext.enabled

damnit, missed it - its just a UI thing - doesn't matter if its a container used IMO, and the pref only enables/disables the use of them, not the content

> signon.rememberSignons

ok

PS: I'll get to the rest soon

**Comment by Thorin-Oakenpants** [comment]
> urlclassifier.trackingTable - blocking tracking stuff shouldn't case breakage

buuuuut we just had a case of TP being the cause of weird behavior and you manually added TP.enabled to the list. Surely the list type would also be a factor

> reader.parse-on-load.enabled

sure, i'll move it to ignore, but you were the one that thought all these "stand-alone" prefs to do with UI were ok to leave in

> all the media stuff

I get that some require a "parent" pref, but how do we know what the end user has - including them all means it will catch those that it can

**Comment by earthlng** [comment]
I'll add these:
'dom.event.contextmenu.enabled'
'dom.indexedDB.enabled'
'dom.storage.enabled'
'dom.vr.enabled'
'media.flac.enabled'
'media.mp4.enabled'
'media.ogg.enabled'
'media.opus.enabled'
'media.raw.enabled'
'media.wave.enabled'
'media.webm.enabled'
'media.wmf.enabled'
'plugin.state.flash'
'security.ssl.require_safe_negotiation'
'security.ssl3.dhe_rsa_aes_128_sha'
'security.ssl3.dhe_rsa_aes_256_sha'
'security.ssl3.ecdhe_ecdsa_aes_128_sha'
'security.ssl3.ecdhe_rsa_aes_128_sha'
'security.ssl3.rsa_aes_128_sha'
'security.ssl3.rsa_aes_256_sha'
'security.ssl3.rsa_des_ede3_sha'
'svg.disabled'

and remove these:
'media.getusermedia.screensharing.allowed_domains', // webrtc, right?
'media.getusermedia.screensharing.enabled',  // webrtc, right?
'permissions.manager.defaultsUrl', // only affects addons.mozilla.org and only in a minor way

ran it in my ESR with these changes and with the new code that reduces the list to non-default values and it detects 66 prefs. Damn sooo close! what else can we get rid of?? :smile:

**Comment by Thorin-Oakenpants** [comment]
^^ all that urlbar UI crap, keyword, css visited links

**Comment by Thorin-Oakenpants** [comment]
user_pref("network.http.altsvc.enabled", false);
user_pref("network.http.altsvc.oe", false);

Possibly remove these two - I don't think they break anything

**Comment by Thorin-Oakenpants** [comment]
`dom.vibrator.enabled` could go .. no one uses it, it doesn't *break* site content

**Comment by earthlng** [comment]
yeah fuck altsvc + vibrator. thx :smile: 
how about `webchannel.allowObject.urlWhitelist` that's some shit that only a few mozilla domains are allowed to use anyway.
and the 3 dom.push.* also rely on each other.

**Comment by Thorin-Oakenpants** [comment]
it has some account stuff in it (I reset it in my desktop version) but [DXR](https://dxr.mozilla.org/mozilla-central/source/toolkit/content/browser-content.js#993)  -> [1238128](https://bugzilla.mozilla.org/show_bug.cgi?id=1238128) .. but I have no idea what this all means.

my default value is
- https://accounts.firefox.com
- https://content.cdn.mozilla.net
- https://input.mozilla.org
- https://support.mozilla.org
- https://install.mozilla.org

I don't think it has anything to do with sync?

**Comment by Thorin-Oakenpants** [comment]
> and the 3 dom.push.* also rely on each other

Well, this is a limitation of your design (i.e not testing in batches) and that's understandable. However, as I said before, you have no idea what an end-user's prefs are. They could have only one of these 3 not at default, and therefore including them all would catch the culprit. There's just no guarantee it would catch it.

**Comment by earthlng** [comment]
> I say remove it from the list

removed. https://github.com/ghacksuserjs/ghacks-user.js/commit/d1ab8fd10cec818c3def5dbe06b114fcb17c654f

**Comment by Thorin-Oakenpants** [comment]
cool, so 94 prefs .. wonder what my non-default array would come out at? How do I check?

**Comment by earthlng** [comment]
change this
```js
//console.log(aBACKUP.length, "user-set prefs from our list detected and their values stored.");
```
to this
```js
console.log(aBACKUP.length, "user-set prefs from our list detected and their values stored.");
return; // = exit the script
```

**Comment by Thorin-Oakenpants** [comment]
> 70 user-set prefs from our list detected and their values stored.

:cry-face:

**Comment by earthlng** [comment]
we haven't looked the hidden and default ones from the active list. Still have that file I sent you?

**Comment by Thorin-Oakenpants** [comment]
nope, cuz I thought we had it covered

**Comment by crssi** [comment]
FYI:
I have 'dom.event.contextmenu.enabled' set to false and Outlook, maps, street view works flawlessly. IDK for twitter, since I am not using it.

**Comment by crssi** [comment]
But I had breakage when 'security.mixed_content.block_active_content' was set to true.
Same goes for 'security.mixed_content.block_display_content'.

**Comment by Thorin-Oakenpants** [comment]
I have to admit I do not use a lot of these major sites, so some of this is from memory from others - we'll refine the list positions over time

**Comment by crssi** [comment]
OMG... wrong copy paste 2 posts back.

I meant 'dom.serviceWorkers.enabled' instead of 'dom.event.contextmenu.enabled'.

**Comment by earthlng** [comment]
* full-screen-api.enabled - this should be a no-brainer to identify, without needing the script, no?
* intl.accept_languages' - do we really need this? we can keep it but then we should probably move it near RFP (+ same for wifi.uri)
* network.cookie.thirdparty.sessionOnly - this shouldn't cause any problems *or* only after a restart, right?

**Comment by Thorin-Oakenpants** [comment]
groups :+1: 
most to least likely :+1:  I wondered why you had it back to front
camera - cool, we'll pick up on that in 59 diffs then, or should we remove it now :question: 

Some settings are REALLY easy to identify, but if you leave them out, then its not as comprehensive. We just need to find a balance. We could always end up with a small version of 32items and a larger version of 128

- fullscreen - yeah drop it
- int.accept.langauges under RFP is still being worked on, almost ready to land - for now I think this requires a restart. Its one of those ones that is REALLY easy to find and it has a UI interface
- cookie change doesn't require a restart, and yeah, I've never had an issue with blocking 3rd party - I do not log into sites like youtube, gmail, pinterest etc - some of which have those FPI issues with logins because they use 3rd party (google, facebook, etc) use effectively supercookie login flows - so I would leave it in

:exclamation:  we should document prefs that require a restart with `[RESTART]` as we come across them

**Comment by Thorin-Oakenpants** [comment]
> :exclamation: we should document prefs that require a restart with `[RESTART]` as we come across them

On second thoughts this is a lot of work, and individual items may change - eg font whitelist/loading via RFP delivering fonts via kinto - but I will tidy up what we have

**Comment by earthlng** [comment]
>  I wondered why you had it back to front

I explained why, [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/332#issuecomment-356294979)

network.cookie.thirdparty.sessionOnly makes all 3rd party cookies session only ie they get deleted when you close FF. This pref can't break sites at all, I'll remove it from the list.

**Comment by Thorin-Oakenpants** [comment]
> I explained why, here

I know all that, I read it when you posted it. I wondered why (and I should have been more explicit) you would want failures over fixes - who cares about shorter pages loads when finding the culprit is always the quickest option

**Comment by earthlng** [comment]
> why you would want fixes over failures

because it makes a difference when we try to narrow down on more than 1 culprit.

Lets say there are 100 detected prefs. For the first test the 1st 50 prefs are reset to their default values. If the problem re-appears now, we only know for sure that at least ONE problematic pref is within the 2nd half. While looking for a single culprit the script will now set the array to the 2nd half and continue the halfing. But to find *all* culprits the script can only narrow down the list whenever the problem does *not* happen, because only then can it be sure that *all* problematic prefs are within the group that just got reset for this testrun.

**Comment by earthlng** [comment]
network.cookie.thirdparty.sessionOnly - apparently sessionOnly can mess with service workers. FFS!

https://github.com/ghacksuserjs/ghacks-user.js/issues/326#issuecomment-357291615

let's just keep it for now.

**Comment by Thorin-Oakenpants** [comment]
^^ lets not go there - grouping partially solves the multiple-culprits. For a single culprit, as you said, it has to eventually halve and halve again etc to *one* culprit, so **IF** a failure is faster, then known culprits should be last .. but hey .. who said a failure was always faster!! huh!

I'll just leave the list and order up to you then. What else do we need to add? Where can we store the video long term - webm is 62mb

**Comment by earthlng** [comment]
we can upload the video to the wiki assets folder because that's no longer included in the zip files.
People using git would still download that folder though. We'd need a .gitignore file for that.
Or I can upload it to my testpages repo

**Comment by Thorin-Oakenpants** [comment]
I say your repo - I do not wish to cause git users big downloads etc

**Comment by earthlng** [comment]
> Yowza, that’s a big file. Try again with a file smaller than 25MB.

:sad-face:

**Comment by earthlng** [comment]
https://anonfile.com/faq - "How long will my files be online?"

**Comment by Thorin-Oakenpants** [comment]
> Files older than 36 months which has not been downloaded for 24 months.

I DL'd it, so at least once is covered. Just set your calendar alarm once every 2 years to make sure you do a DL

**Comment by Thorin-Oakenpants** [comment]
current js gave me `65 user-set prefs from our list detected and their values stored` ... ooh so close. Mind you, users can easily edit their list - I can chop out the UI ones and be under 64 :+1:

**Comment by Thorin-Oakenpants** [comment]
I've edited the wiki page a little. What did you want to put in the Scratchpad script section?

Thoughts
- something about watch the video, it's ALL explained in there
- does not cover all prefs: some require a restart which the script does not handle, others do not cause breakage: i.e we reduced the number of prefs involved to a much smaller size
- may not find a cause if multiple prefs are involved

Would you like to write it? Do you want to put the scratchpad section before the manual section as it would be a lot shorter & sweeter?

**Comment by earthlng** [comment]
A lot could be written about it but I think we can keep it relatively short.

Before you go on to the laborious task of manual troubleshooting we recommend to try the script first.
In many cases it should be able to either directly identify the culprit or at least narrow it down to a more manageable number of prefs for the manual troubleshooting.
You can just run the script and follow the instructions but we strongly recommend to watch the demo video first.

**Comment by Thorin-Oakenpants** [comment]
sounds good to me - do I use the raw link for the script?
