### ISSUE TITLE
prefsCleaner.bat in Linux [solved: use scratchpad scripts]

### ISSUE THREAD

**Issue by 1xPdd** [ghacksuserjs/ghacks-user.js#340]
Hey, sorry for my ignorance--can anyone suggest what I would need to do in order to get an equivalent cleaning under Linux? I've run all the scratchpad scripts but my scripting is not good enough to rewrite the Windows Batch file into bash, so I imagine I still have plenty of legacy settings hanging around. Thanks.

**Comment by claustromaniac** [comment]
I may be wrong, but I believe you don't need to run `prefsCleaner.bat` if you already ran all the scratchpad scripts, at least as long as you don't have a custom `user.js` file with preferences from different sources or something like that. 

If you used to use a different `user.js` file or just liked to fiddle a lot with settings yourself, you should probably edit `prefs.js` manually to make a more thorough cleanup. For example, you can make a backup of `prefs.js` (or better, a backup of the entire profile) and then proceed to remove all entries in it that don't have anything to do with the UI or with extensions that you still use, and launch Firefox again to have all settings in `user.js` reapplied. 

I did that recently in an old profile and in my case it didn't take as long as it sounds it could take.

**Comment by claustromaniac** [comment]
By the way, I might be willing to port the script to bash if someone is willing to test it for me, but It could take a while since I would need to do some research and I still have to get used to this shitty netbook's shitty keyboard, because my PC decided to die on me the other day.

**Comment by 1xPdd** [comment]
> but I believe you don't need to run prefsCleaner.bat if you already ran all the scratchpad scripts

Ahh, thanks for the clarification. I had thought one needed to do both.

> proceed to remove all entries in it that don't have anything to do with the UI or with extensions that you still use, and launch Firefox again to have all settings in user.js reapplied.

Just so I follow you, you mean, in the **about:config**, clicking reset on everything that is bolded?

>  I might be willing to port the script to bash if someone is willing to test it for me

I can help test, though if I'm the only Linux user here, definitely don't suffer a shitty netbook keyboard just for me.

**Comment by Thorin-Oakenpants** [comment]
> Just so I follow you, you mean, in the about:config, clicking reset on everything that is bolded?

No. Don NOT do that - not everything that is **user set** or **modified** (i.e bolded) is that way because of the user.js or end-user changes - a LOT are internal firefox settings

**Comment by Thorin-Oakenpants** [comment]
re: legacy prefs: If you are on FF57 and have no legacy extensions .. then check for a ton of `extensions.*` ... and `noscript` (from memory it didn't use the normal naming convention)

There are quite a few valid `extensions.*` - but you should be able to pick out things like (from memory) `extensions.findbartweak`, `extensions.umatrix`, `extensions.scrapbook` etc. I know when I removed all mine my prefs shrank from 120kb to around 45kb - some if those legacy extensions like CTR had loads of entries

**Comment by claustromaniac** [comment]
> Just so I follow you, you mean, in the about:config, clicking reset on everything that is bolded?

No, I meant removing lines from `prefs.js` in the profile directory using a text editor, but it's probably not necessary, and it has a few risks so you should never attempt to without backing up first.

Pants, by pure chance I just happened to notice that the links to download the `prefsCleaner.bat` on the wiki don't look right:

> Our prefsCleaner.bat file is [here](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/prefsCleaner.bat)

> Run the [prefsCleaner.bat](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/prefsCleaner.bat) file in your profile directory with Firefox closed. This does not cover prefs we REMOVED from the ghacks user.js, see the Scratchpad section for those.

I mean I guess it's OK to leave them like that, but I think it would be better to use a link for the raw content instead, like: https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/prefsCleaner.bat

**Comment by Thorin-Oakenpants** [comment]
^^ fixed

**Comment by Thorin-Oakenpants** [comment]
@1xPdd closing this as it's not an issue, but if you have any more questions, don't hesitate to ask :)

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/prefsCleaner.sh

download link: https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/prefsCleaner.sh
