### ISSUE TITLE
discuss: remove Presentation API

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#342]
This section
```js
/* 2513: disable Presentation API
 * [WARNING] [SETUP] Optional protection depending on your connected devices
 * [1] https://wiki.mozilla.org/WebAPI/PresentationAPI
 * [2] https://www.w3.org/TR/presentation-api/ ***/
   // user_pref("dom.presentation.enabled", false);
   // user_pref("dom.presentation.controller.enabled", false);
   // user_pref("dom.presentation.discoverable", false);
   // user_pref("dom.presentation.discovery.enabled", false);
   // user_pref("dom.presentation.receiver.enabled", false);
   // user_pref("dom.presentation.session_transport.data_channel.enable", false);
```

is covered by RFP
```js
 ** 1382533 - enable fingerprinting resistance for Presentation API (see 2513) (FF57+)
```

This `2513` should either be moved into `4600 RFP alternative` section or be removed entirely (the defaults are false). These are the only two choices - it will not be staying where it is.

**I am in favor of removing it entirely**. If it should ever change default values we can re-evaluate. To me it's a bit of a waste of space and I doubt anyone uses it. The only downside is losing the info (but again, I doubt anyone will use it). **Any objections?**

**Comment by claustromaniac** [comment]
> I am in favor of removing it entirely.

### +1

**Comment by 2glops** [comment]
For me, this could be removed entirely.

**Comment by Thorin-Oakenpants** [comment]
I'm getting a vibe here .. 3+ to remove, 0 to keep

**Comment by Atavic** [comment]
Remove it, it's a corporate feature rarely used by humans.

**Comment by Thorin-Oakenpants** [comment]
Awesome .. 4+ .. when we get to 10, I'll get rid of it

**Comment by crssi** [comment]
Teaser :)
+1

**Comment by overdodactyl** [comment]
>when we get to 10, I'll get rid of it

+1

**Comment by Thorin-Oakenpants** [comment]
oooh .. at +6 .. i'm getting all excited guys

**Comment by Atavic** [comment]
I have problems with right-clicks, but 
:+1:

**Comment by Thorin-Oakenpants** [comment]
I already counted you in as a +1 .. what does right clicks have to do with anything?

**Comment by Atavic** [comment]
I can't click on smilies.

**Comment by Thorin-Oakenpants** [comment]
I'm confused. Pick a reaction is a left-click

**Comment by Atavic** [comment]
OK. I can't click on smilies and can't open other things here and there: Oldies but Goldies browsers.

**Comment by grauenwolfe** [comment]
Agreed since nothing is changed with any of them.

I know this isn't an open call for edits but consider removing the bit about IPv6 as well.

> / 2621: disable IPv6 (included for knowledge ONLY [WARNING] do not do this)
> This is all about covert channels such as MAC addresses being included/abused in the
> IPv6 protocol for tracking. If you want to mask your IP address, this is not the way
> to do it. It's 2016, IPv6 is here. Here are some old links
>
> _(followed by seven more lines of links)_

**Comment by Thorin-Oakenpants** [comment]
Not sure if I want to remove it - but we could ~~expand on it~~ shorten it. VPNs should hide IPv6 - here is a test site: http://test-ipv6.com/ . Masking IPs should be done at a network level IMO

**Comment by Thorin-Oakenpants** [comment]
@grauenwolfe FYI, some [Telemetry](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-09-21&keys=__none__!__none__!__none__&max_channel_version=nightly%252F57&measure=IPV4_AND_IPV6_ADDRESS_CONNECTIVITY&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-08-02&table=1&trim=1&use_submission_date=0)

data may change, so here's the summary: FF57 from 2017/08/02 to 2017/09/21 (51 days): 6.21Billion sample size, seems to show 95.67% = IPv4 and 4.33% = IPv6. No idea exactly what a "sample" is.

**Comment by kgbm3** [comment]
Hey, um, I'm a little confused. That section, _2513: disable Presentation API_, was there in case somebody wanted to enable dom.presentation. or, WTH?! (Why would you need to)

It's labeled as "disable", but the defaults (really) _are_ False. Not sure I'm able to follow, gah! :-f

**Comment by Thorin-Oakenpants** [comment]
Not really interested in why it was created, or whose job is whose - it's in there, so we have to deal with it :)

A lot of prefs in the user.js are at default. A lot are inactive. It's more about being comprehensive, and also enforcing values (in case users have been mucking around). Also, Mozilla often flips pref values - so some of it can be considered future proofing.

However, it doesn't mean we can't clean up the user.js over time as things change

In this case with the Presentation API, its really only there for info - we don't enforce it, the values already match what we would want. It is also now partially covered by RFP (privacy.resistFingerprinting). And it's pretty much obscure, with users having to know about it to get it to work (under the hood via about:config).

That's all - a chance to clean out some dead wood

**Comment by mazesy** [comment]
Information verses pertinence: I vote to keep the setting.
