### ISSUE TITLE
2 dead prefs

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#344]
As per earthlng's commit: https://github.com/ghacksuserjs/ghacks-user.js/commit/6a0f162d64e91982930577425deff2436003a528

> dom.idle-observers-api.enabled not used anymore since at least FF38 `2416`
> security.xpconnect.plugin.unrestricted not used anymore since at least FF10 `1805`

DXR fails to find either of these. They should be moved to the deprecated section - pref numbers added above. Anyone want to help find the bugzillas?

**Comment by kgbm3** [comment]
DXR, as in: https://dxr.mozilla.org/mozilla-central/source/ ??

Both of those settings are present in a new profile, Firefox 57.0.4 (64-bit) Windows 10.

**Comment by Thorin-Oakenpants** [comment]
I hadn't checked about:config yet, but yeah - that is the exact URL and tree - I get both coming back with 0 results

**Comment by earthlng** [comment]
Yes the prefs still exist but they are **not used** anymore and have been [removed in 59](https://bugzilla.mozilla.org/show_bug.cgi?id=1416703).

`dom.idle-observers-api.enabled` - see [ESR31](https://dxr.mozilla.org/mozilla-esr31/search?q=idle-observers-api) vs [ESR38](https://dxr.mozilla.org/mozilla-esr38/search?q=idle-observers-api)
`security.xpconnect.plugin.unrestricted` - see [mozilla2.0](https://dxr.mozilla.org/mozilla2.0/search?q=security.xpconnect.plugin) vs [ESR10](https://dxr.mozilla.org/mozilla-esr10/search?q=security.xpconnect.plugin&redirect=false)

**Comment by Thorin-Oakenpants** [comment]
Thanks. So should we just action these in 58->59 diffs then? Or slot them in to FF10 + FF38 deprecated?

**Comment by earthlng** [comment]
in 59

**Comment by Thorin-Oakenpants** [comment]
OK, so this is a dead issue then, assuming we do a 58->59 diffs
