### ISSUE TITLE
Webcam not working with ghacks-user.js

### ISSUE THREAD

**Issue by Utini2000** [ghacksuserjs/ghacks-user.js#345]
Hello everyone,
I will need my webcam for an online test but with the ghacks-user.js it is not working.

I thought it might be one of those lines but they aren't fixing my issues:

> /* 2023: disable camera stuff ***/
>user_pref("camera.control.face_detection.enabled", false);
>/* 2026: disable canvas capture stream
>user_pref("canvas.capturestream.enabled", false);
>/* 2027: disable camera image capture
>user_pref("dom.imagecapture.enabled", false);
>/* 2028: disable offscreen canvas
>user_pref("gfx.offscreencanvas.enabled", false);

Any suggestions?

**Comment by Thorin-Oakenpants** [comment]
Hey Utini, if it's for a `one off` online test, then just use a new profile, or grab a one off portable FF (if on windows).

To get the webcam working I would think you need to enable quite a few things - not just the site (cookies exception, maybe web workers etc) but codecs etc

Site Exceptions panel has a camera and mic override
![siteexceptions](https://user-images.githubusercontent.com/16656956/35332174-e5778848-016e-11e8-8eb5-b2029317b024.png)

After that I'm not 100% sure, because I will never use a camera/mic on my browser. Look at WebRTC (Web Real-Time Communication) : you'll need the codecs for it, so `1840` for starters and not sure how to trigger downloading the codecs will take. You may need to reset some of the GMP stuff in `1820` (I am not sure if the OpenH264 is under the GMP umbrella). Then you will probably need to reset all the peerconnection stuff in `2001` & `2002`

This is a lot of compromise - just use a new profile if its a one-off is my suggestion.

**Comment by Utini2000** [comment]
Thank you guys for your responses. Unfortunately none of them helped :/ 

I already modified some of those sections as I expected them to "break" some of my stuff. And so I just copied all the sections you mentioned from my current firefox profile into a new firefox profile. The new profile was able to use the webcam while my current can't. So the error must be in another section.

I also figured that I am using the webcam for more than just this one online test (I will need it for several exams as I too my master studies online, I also use skype in my browser,...).

Any suggestions left? :(
Here are the sections you mentioned from my user.js: 
https://pastebin.com/tPdCKpP1

**Comment by Atavic** [comment]
The URL of the page is needed to look at the requests and scripts.

**Comment by Utini2000** [comment]
@Atavic I used smth simple as: https://www.onlinemictest.com/webcam-test/
But basically any other webcam related website won't work either.

**Comment by Atavic** [comment]
I see a request to *fonts.googleapis* so you have to change: `browser.display.use_document_fonts 0` to **1**.

**Comment by Utini2000** [comment]
Done, didn't help though.

**Comment by earthlng** [comment]
To re-enable WebRTC you probably also need to change 2505

**Comment by Thorin-Oakenpants** [comment]
@Utini2000 .. when are your tests? Are you able to just use a new profile to do them?

Do you still need help or want me to plug in my webcam (and point it at the wall) and test what blocks using it? Can't guarantee it will be soon though.

**Comment by Utini2000** [comment]
@earthlng tried 2505 already -> not the issue :/
@Thorin-Oakenpants -> if you have a chance to test it out then I would be very grateful. I went through my user.js a few times already and can't think of anything that could be the root-cause.

If relevant, here is my current user.js with a few changes made from the original ghacks-user.js (due to compatibility issues): 
https://pastebin.com/RaWyP7xN

**Comment by Thorin-Oakenpants** [comment]
Silly question: But have you tried your webcam etc in a NEW PROFILE?

Also, it's going to be a while before I get to this, and the gmail one. Probably a week or two. But I would like to maybe create a sticky for what breaks some major sites/things (within reason) - eg gmail, google docs, maps, twitch, twitter, etc - except I do not want to re-invent the wheel, and I think a `relaxed` sticky or `js` would be much the same effort

**Comment by Utini2000** [comment]
Yup I created a completely new profile (--no-remote --profilemanager). All the results that I posted here were done in that new profile (without any extensions or what so ever).  

Yes such a list would be really smart. I had a lot of troubles with certain websites and it took me some time to figure out what causes those troubles. It will be a lot easier if you list them somewhere and then people can check those settings and decide for themself weather they want the privacy/security or compatibility.

Off topic question:
What is an easy way to keep my customized user.js up-to-date with the one on github? I mean I could download the new user.js from github but then I will loose all my customized settings?

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

https://github.com/ghacksuserjs/ghacks-user.js/wiki#small_orange_diamond-maintenance

**Comment by Thorin-Oakenpants** [comment]
> What is an easy way to keep my customized user.js up-to-date with the one on github

https://github.com/ghacksuserjs/ghacks-user.js/wiki#small_orange_diamond-maintenance : 3.2 and 3.2
- keep your overrides (changes/tweaks/extra prefs) in a `user-overrides.js` as a master copy
- your overrides content is appended to the end of your user.js, which is just a straight up copy of the one here at guthub
- you can manually update the user.js and manually append your overrides, or you can use the updater.bat (windows)

**Comment by Utini2000** [comment]
Oh crap, wished I had known that before :D 

Well, I will just download the current user.js and check for differences and put those in the user-overrides.js !
Btw, I am on Linux (Arch Linux). Might create a AUR package for easy updating of the ghacks-user.js.

Thanks, you guys are awesome!

**Comment by Thorin-Oakenpants** [comment]
there's an updater for linux - i think it also does the append user-overrides.js - check with the wiki

**Comment by Utini2000** [comment]
Yep there is an update script but by creating an AUR package people on Linux will be notified when an update is released and can then do all the automatic-update via the package manager.

Maybe there already is a package for that in the AUR, will check later :)

**Comment by icpantsparti** [comment]
@Utini2000 That webcam-test link you posted needs media.autoplay.enabled as true btw.

**Comment by Utini2000** [comment]
@icpantsparti that fixed it... the webcam wasn't "auto-playing".  
Hmm that can cause some troubles with my online exams since there is no video/image that I can click on to enable "playing".  

Guess I will just have to generally enable "auto-playing" when doing the tests.

But thanks ! Seems like webcams work now :-)

**Comment by Thorin-Oakenpants** [comment]
> Guess I will just have to generally enable "auto-playing" when doing the tests.

No. You have options dude! Use a new profile, with no user,js (or just a few restrictions if you're paranoid) JUST FOR your tests, no other sites. Don't compromise yourself man!

**Comment by Utini2000** [comment]
Yes ofcourse, that will most likely also be my solution for the tests (new empty profile) !

**Comment by crssi** [comment]
@Thorin-Oakenpants 

> No. You have options dude! Use a new profile, with no user,js (or just a few restrictions if you're paranoid) JUST FOR your tests, no other sites. Don't compromise yourself man!

Why would `media.autoplay.enabled = true` compromise?

**Comment by Thorin-Oakenpants** [comment]
> Why would media.autoplay.enabled = true compromise?

I haven't even tested the site or been bothered to connect my webcam, but I would assume it's because it's alive feed which doesn't normally have play/pause/stop buttons on it, so if it can't auto-start then there's no way for you to do it manually

**Comment by crssi** [comment]
But... this is pref for playing not recording/capturing. Or it does both?

**Comment by Thorin-Oakenpants** [comment]
IDFK .. ask someone else :grr:

**Comment by crssi** [comment]
You didn't need to edit... it was cute... just wanted to ask you why emoticon doesn't work, :)
