### ISSUE TITLE
dom.ipc.processCount.extension >1 breaks extensions

### ISSUE THREAD

**Issue by Marc05** [ghacksuserjs/ghacks-user.js#346]
Setting dom.ipc.processCount.extension >1 breaks extensions

- FF 58
- Tried on all default new profile

This isn't really a user.js issue, but I figured it may be worth mentioning as a comment at least considering it was previously set as 1, albeit commented out.

**Comment by Thorin-Oakenpants** [comment]
"control number of extension processes" .. makes sense, zero processes, zero extensions :)

**Comment by Marc05** [comment]
Wouldn't a number greater than 1 mean more processes - not zero?

**Comment by earthlng** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/91521dbc84dd43e2f6b75ae43ff2056ed9a742c2
