### ISSUE TITLE
12bytes link changes...again

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#347]
**WAIT WAIT WAIT!!!  hold off on this - i have another change to make - will leave a new comment when done**

sorry guys - hopefully this is the last of this - the old links will still work, but here are the correct ones...

[front page, acknowledgments](https://github.com/ghacksuserjs/ghacks-user.js), 12Bytes should be: 
`http://12bytes.org/tech/firefox-mozilla-based-browser-tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs`

[4.3 Search Engines](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.3-Search-Engines), Firefox Search Engine Cautions and Recommendations should be:
`http://12bytes.org/tech/firefox-mozilla-based-browser-tech/firefox-search-engine-cautions-and-recommendations`

thanks again :)

**Comment by Thorin-Oakenpants** [comment]
done .. wonder when that wiki search page is gonna get done

**Comment by atomGit** [comment]
Oak, you're tooooooo fast!!!

i re-edited my initial comment but you changed the links after :)

new links:

[front page, acknowledgments](https://github.com/ghacksuserjs/ghacks-user.js), 12Bytes should be: 
`http://12bytes.org/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs`

[4.3 Search Engines](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.3-Search-Engines), Firefox Search Engine Cautions and Recommendations should be:
`http://12bytes.org/tech/firefox/firefox-search-engine-cautions-and-recommendations`

> wonder when that wiki search page is gonna get done

what wiki search page? did i forget something? LOL

**Comment by Thorin-Oakenpants** [comment]
done .. yeah, earthlng or someone was meant to do it after suggesting a bunch of things to put in it

**Comment by atomGit** [comment]
maybe you want to link to this?:

[Firefox Search Engine Cautions, Recommendations](http://12bytes.org/tech/firefox/firefox-search-engine-cautions-and-recommendations)

that will get updated for v57+ as i get the updates - i use Waterfox, so i'm on v56

other than that, what did you have in mind?

**Comment by Thorin-Oakenpants** [comment]
^^ huh? its already linked in the wiki page

**Comment by earthlng** [comment]
> earthlng or someone was meant to do it

the wiki is all yours.

**Comment by atomGit** [comment]
ok, but @Thorin-Oakenpants said "wonder when that wiki search page is gonna get done"

my question is: what do you want done?
if someone can provide an outline, that would be great

**Comment by Thorin-Oakenpants** [comment]
I re-opened #307 where the search page content was discussed and outlined by **earthlng**

**Comment by atomGit** [comment]
k, thanks - bookmarked and will look at it at some point
