### ISSUE TITLE
FYI: to be taken with a grain of salt

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#352]
You can get your grain of salt from any reputable [salt mine](https://xkcd.com/1637/). If you're not sure why salt is needed, then consider that the data set is not real-world, current, or relevant: it is small, contaminated by repeat visitors and repeated testing and by the very nature of the visitors, uses values over a very long time period, is not reduced to a better more meaningful metric such as "Firefox users", ... and the methods of FP'ing are very limited

I was bored and bike-shedding (still am) so I decided to see what blocking canvas did as per RFP. Note: I used to have issues getting Panopticlick finishing its script if I blocked via ~~CanvasDefender~~ CanvasBlocker, and in this test I told FF to remember my site exception, so now I can't retest CB (well I can but can't be arsed). So previous tests with CB I would fake = always a unique hash = pointless stats

![pan-block](https://user-images.githubusercontent.com/16656956/35761731-c0a690c4-0883-11e8-9403-fdceb59340a6.png)

So for the first time in ages I am actually able to get a stat without being called unique due to the canvas. FYI the figure is one in 110K, which is meaningless for now (TBB is one in 42k btw).

some notes
- User Agent: 90%+ of FF users are on stable, so a better metric would be something like 1 in 10 are on ESR52
- Platform: 2/3rds of FF users are on 64bit, so a better value would be 1 in 1.5
- Canvas: I doubt 2.5% (1 in 40) of the world blocks canvas, most canvas extensions fake IMO. But once RFP is added to PB mode, I would expect `undetermined` within FF users to start being useful

Not concerned with TBB differences, will probably all fall into line anyway with ESR60. I only care about the subset of FF users
- Canvas: TBB gives a static `a273d6a847f0e2a57fa0161158f12fed` value
- Platform: TBB shows 32
- User Agent: TBB excludes the `Win64; x64` in its string
- DNT values differ between FF/TBB, who cares - we use default settings so should be in the majority of FF users

Right .. wasted enough time, 'spose I should wrap up 58 final .. *sigh*

**Comment by Atavic** [comment]
>Panopticlick

Brave Wiki has [some info](https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode#why-does-panopticlickefforg-or-some-other-site-say-that-i-am-fingerprintable).

**Comment by Thorin-Oakenpants** [comment]
Atavic, that reads suspiciously like something I have written before, numerous times - even the mentioning of the DNT metric. Its almost as if the author has come across my words at some stage and then typed it up all nice and elegant after his research etc :) ... in other words, he's absolutely correct :grin:

**Comment by Atavic** [comment]
snyderp reviewed that part.

**Comment by Thorin-Oakenpants** [comment]
> snyderp reviewed that part.

Now I feel vindicated - I wonder if Peter ever read my diatribes @snyderp
- https://github.com/ghacksuserjs/ghacks-user.js/issues/270#issuecomment-344051207
- https://github.com/ghacksuserjs/ghacks-user.js/issues/163#issuecomment-313000495
- https://github.com/ghacksuserjs/ghacks-user.js/issues/150#issuecomment-310440662

More examples of my ~~intellectual prowess~~ rambling abound, but I can't be arsed finding them :)

**Comment by snyderp** [comment]
I feel like I've been brought into some beef (!) so just for the record: I didn't review the panopticlick part of the Brave wiki (but for my two cents, it all seems correct to me), and points to whoever wrote it :)

The part of that I page I wrote is just the [brief blurb](https://github.com/brave/browser-laptop/wiki/Fingerprinting-Protection-Mode/_compare/13049b473777f73d47937bf55cc0503fddf845e3...92bb57587f3a810c24f8c8f6423af6efd893c733) about adding more SVG methods to the set of things being blocked.

**Comment by Thorin-Oakenpants** [comment]
No beef :) Its just that the number of times people harp on about Panopticlick and other All-in-One FP tests (not here but on reddit and other forums) and they don't take all the factors/method into account - it drives me crazy (not that I can reply since these places require accounts) - obligatory [xkcd](https://m.xkcd.com/386/)

Just nice to see someone else say essentially the same thing I have

**Comment by overdodactyl** [comment]
Do you know if there is much than can/should be done about "Screen Size and Color Depth"? My results were nearly identical to yours with that exception:

![screen](https://user-images.githubusercontent.com/33071129/36009288-790b0f46-0d43-11e8-86f1-5e30f84abce0.png)

^ That's in a new profile with only user.js (no adjustments to to window size before testing or anything)

**Comment by Thorin-Oakenpants** [comment]
We will have to wait for RFP to allow more width (opening at 1000 width maximum is silly considering most (90%? 95%?) FF users are on desktop. I would like to see them use 1000, 1400, 1800 if it fits (something like that - needs a little analysis on common screen res). Until then for kicks, I'm using 1366x768 cuz I need 16/9 man!

My screen is 1680x1050 (double height bottom taskbar) - I think FF w/RFP opens at 1000x800 except I use those overrides to get some width (1400x800)

**Comment by overdodactyl** [comment]
Makes sense, thanks! I never really considered how using an extension like Tree Style Tab (that utilizes the sidebar) effects that value.  I guess I should probably override the default to account for whatever standard width I use on the sidebar?

**Comment by Atavic** [comment]
1366x768 34%
1920x1080 18%
Lower Resolutions 6.1%
1440x900 6%
1536x864 6%
1600x900 5%
1280x1024 4%
1280x800 3%
1024x768 2%

[January 2018](https://www.w3schools.com/browsers/browsers_display.asp)

**Comment by Thorin-Oakenpants** [comment]
Noooooo .. look at FF users (although as a decent sized subset should be pretty much the same minus the mobile market) - https://hardware.metrics.mozilla.com/

33% 1366x768
23% 1920x1080
08% 1600x900
06% 1280x1024 etc at time of writing
06% 1440x900
04% 1280x800
04% 1680x1050

1000px in 1366 might be ok (IDK), but the no.s 2+3+5+7 = 23+8+6+4 = over 40% (add in no 1 at 33% because lets face it a lot of sites at 1000px width suck) and you won't get uptake when you annoy 40% or 73% of your target audience

**Comment by overdodactyl** [comment]
^ That does't look good for laptop users

**Comment by anchev** [comment]
Would you please check this too:
https://github.com/pyllyukko/user.js/issues/372

**Comment by Atavic** [comment]
Those issues have been duscussed in this repo recently, dig a little, anchev.

**Comment by Thorin-Oakenpants** [comment]
> Would you please check this too

What's to check? It's a pointless exercise (see first post) except it's handy to see all the values you "leak" in one hit (same with JoDonym and AmIUnique and browserprint.info). You need to trust the science and math behind RFP (note: to ***lower entropy***). FF specific metrics are the only one decent ones worth considering
