### ISSUE TITLE
BrowserAudit results

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#353]
edit: :exclamation: your **linked** results report your IP - just to make that clear

https://browseraudit.com/ - post your **results link** here if you like (report gives away your IP so mask that first) - maybe we can compile a list of common warnings/critical etc to investigate (and lets not forget the stuff that gets skipped) - note: I will do a nilla profile soon and post results

### results

FF nilla normal and PB windows:
 *  :white_check_mark:  373     :warning: 6     :x: 5     :small_blue_diamond: 20
FF nilla with default ghacks user.js (+ cookie exception for `browseraudit.com`)
 *  :white_check_mark:  347 (-26)  :warning: 22  (+16)  :x: 5  (-)   :small_blue_diamond: 30 (+10)

==
FYI: My FF
 *  :white_check_mark:  306     :warning: 31     :x: 5     :small_blue_diamond: 62  (with uM, uBO, see below)
 *  :white_check_mark:  343     :warning: 24     :x: 5     :small_blue_diamond: 32  (`matrix-off`, whitelisted)

FYI: Opera (I think its all at default - no extensions)
 *  :white_check_mark:  374     :warning: 10     :x: 0     :small_blue_diamond: 20

The 5 criticals in common are the same

### notes

I had to allow cookies, and uM was as follows (I usually only allow images & css, wasn't sure what to allow to get it working)
![um](https://user-images.githubusercontent.com/16656956/35774138-25aab23a-095f-11e8-95f0-c835fcf7c5c7.png)

**Comment by Thorin-Oakenpants** [comment]
Here's a nilla FF with just the ghacks user.js (no mods/overrides), but I forgot to allow a cookie exception

![whoops-nocookies](https://user-images.githubusercontent.com/16656956/35774561-41d5c6aa-096b-11e8-91e2-cd9a910c3491.png)

You need to take the warning/critical numbers with two grains of salt.

The only difference between FF nilla vs user.js and/or extensions seem to be that blockage of fonts/APIs/etc erroneously(?) then reports that as a warning or even critical (and some items get skipped). The diff between my FF with uM+uBO off is almost identical (2 differences) to a nilla FF + user.js only.

Interesting, needs a lot more digging. But for starters, why has a nilla FF got 5 warnings?

**Comment by DiPepGuy** [comment]
I am running Canvas Blocker, Https Everywhere, uBlock Origin, uMatrix and Windscribe with only the proxy time turned on in privacy settings here.

https://browseraudit.com/results/4888/309ccaca42215876177a457ff13b10e984d7116e

Here I disabled CB, uBO and uM.

https://browseraudit.com/results/4890/20aa82c7449929daa1f5c73f839aeafa57efacef


Tried posting croped pics but get "something went wrong try again" message. May be due to new account.

**Comment by Thorin-Oakenpants** [comment]
> Tried posting croped pics but get "something went wrong try again" message. May be due to new account

If you mean dragging and dropping (or selecting) an image into the comment field, then look at #233 

rewording earthlng
"You need to allow github-something-something.s3.amazonaws.com in ~~NoScript~~ uBO and the XHR to that domain in uMatrix ~~and/or uBO~~

**Comment by DiPepGuy** [comment]
Tried your way and tried disabling both uBO an uM nd still wont go, except now i am getting unsupported format error (jpg).

That IP is UK i am in the states so unless it is collected somewhere else this is all good.

**Comment by Thorin-Oakenpants** [comment]
^^ so the error that caused the "something went wrong" is indeed fixed - "unsupported format error" is now the **next** error - not seen that before - is that a github error message?

**Comment by Marc05** [comment]
https://browseraudit.com/results/4965/81f35215057c9dd850bc8eec126635994250774b

FF w/ uBlock Medium
341/4/5/54
