### ISSUE TITLE
discussion: revamp 5000 (personal)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#360]
moving on from #338 (the decision is to keep the info in the user.js) lets revamp section 5000 - trim the cruff, condense lines, group stuff

Stuff:
- rename section title?
- sub sections? eg `Appearance` | `Behavior` | `Media` etc - and re-order stuff into their logical groups
- expand where needed (eg full-screen duration)
- make inactive where possible so as to not upset users workflow/UI etc
- new entries (suggestions welcome)
- readme.md - add sentence to end of "mission statement" that we also have this section

Also see https://www.reddit.com/r/firefox/wiki/aboutconfig for ideas

**Comment by overdodactyl** [comment]
Not sure if it would be worth putting in an `Appearance` section (inactive by default), but two I have in my overrides file are:

```js
user_pref("lightweightThemes.selectedThemeID", "firefox-compact-dark@mozilla.org");
user_pref("devtools.theme", "dark");
```

to use the dark theme for the UI and the devtools, respectiely

**Comment by grauenwolfe** [comment]
Simply naming it "5000: OPTIONAL" would be sufficient and about as clear-cut as you can get.
A short introductory paragraph (maximum of two or three sentences) making it clear that the following entries have no bearing on privacy or security and are included as a courtesy.

Additionally, every entry should have a brief but concise explanation of exactly what the user can expect from changing it. Finally, **eliminate all links and references from this section as well. They're extraneous and if any outside source is needed to inform the user about what their getting in to, that entry needs to either be part of the user.js proper or removed entirely.

**_opinion limited exclusively to section 5000 or whatever number this section may rest at_

**Comment by Thorin-Oakenpants** [comment]
^^ I like that. OPTIONAL and a two line description to differentiate it (I don't think we need more than that - oh wait, we already have a two line description that says exactly that - but lets flip the order of the two points). I like the idea of removing all references (unless its ***really*** needed). We can also streamline it more by making each numbered item description a single line. Even something like earthlng said to reduce lines

```js
/* TABS ***/
user_pref("tabs.pref.one", true) // describe
user_pref("tabs.pref.two", true) // describe
```

**Comment by claustromaniac** [comment]
Not trying to sow hate but, is not **everything** in the file optional? _Miscellaneous_ sounds more accurate.

**Comment by grauenwolfe** [comment]
Not showing hate at all, not even a thought. Any collaboration depends on discussion, counterpoints, etc. Please expound your thoughts, I'm curious what's in there that you see as being mandatory to ensure security or privacy?

To be honest, MISCELLANEOUS would be just as suitable for the title.

**Comment by claustromaniac** [comment]
> Not showing hate at all, not even a thought. Any collaboration depends on discussion, counterpoints, etc. 

Some part of me felt the need to make that clear. I expect the title of a section to be a trivial enough matter for some to think it doesn't deserve objections, counterarguments, etc. I'm too used to seeing internet trolls and wouldn't want to become one.

> I'm curious what's in there that you see as being mandatory to ensure security or privacy?

Actually, my point is that whether any of the settings in this `user.js` is mandatory or not for a given individual depends entirely on that individual's needs, which means that everything in this `user.js` is technically optional.

**Comment by earthlng** [comment]
> Not trying to sow hate but, is not everything in the file optional? Miscellaneous sounds more accurate.

I agree

**Comment by earthlng** [comment]
for starters ...
* remove 5024 + 5025
* browser.link.open_newwindow - move to 2204 + also add `user_pref("browser.link.open_newwindow.override.external", 3);`
* remove `browser.stopReloadAnimation.enabled` because `toolkit.cosmeticAnimations.enabled` also disables the stop/reload animation
* remove 5020 because the values we set are the default values in Mac + Windows. Linux sets it the other way around: false+true instead of true+false - IDK why but I guess there's a reason for that.
* remove 5021a-d because they all just enforce the default value which doesn't really make sense for the 5000 section, IMO.

draft:
```js
/*** 5000: PERSONAL SETTINGS [SETUP]
           Settings that are handy to migrate and/or are not in the Options interface.
           Users can put their own non-security/privacy/fingerprinting/tracking stuff here
 ***/
user_pref("_user.js.parrot", "5000 syntax error: this is an ex-parrot!");

//user_pref("accessibility.typeaheadfind", true);		// enable "Find As You Type" - http://kb.mozillazine.org/Accessibility.typeaheadfind
//user_pref("browser.backspace_action", 2);			// Backspace and Shift+Backspace behavior: 0=go Back/Forward, 1=act like PgUp/PgDown, 2=do nothing
user_pref("browser.bookmarks.max_backups", 2);			// set maximum number of daily bookmark backups to keep (default is 15)
user_pref("browser.ctrlTab.previews", true);			// enable "Ctrl+Tab cycles through tabs in recently used order"
//user_pref("browser.download.autohideButton", false);		// disable download button auto-hide (FF57+)
user_pref("browser.tabs.closeWindowWithLastTab", false);	// disable closing browser with last tab
//user_pref("browser.tabs.loadBookmarksInTabs", true);		// open bookmarks in a new tab (FF57+)
//user_pref("browser.tabs.warnOnClose", false);			// disable warning when closing multiple tabs
//user_pref("browser.tabs.warnOnCloseOtherTabs", false);	// disable warning when closing other tabs
//user_pref("browser.tabs.warnOnOpen", false);			// disable warning when opening multiple tabs
user_pref("browser.urlbar.decodeURLsOnCopy", true);		// decode URLs on copy from the urlbar (FF53+) - https://bugzilla.mozilla.org/1320061
//user_pref("clipboard.autocopy", false);			// disable autocopy default [LINUX]
//user_pref("general.autoScroll", false);			// disable middle-click enabling auto-scrolling [WINDOWS] [MAC]
user_pref("layout.spellcheckDefault", 2);			// spellchecking: 0=none, 1-multi-line controls (default), 2=multi-line & single-line controls
user_pref("network.manage-offline-status", false);		// disable "Work offline" autodetection - https://developer.mozilla.org/docs/Online_and_offline_events
//user_pref("reader.parse-on-load.enabled", false);		// disable "Reader View"
//user_pref("toolkit.cosmeticAnimations.enabled", false);		// disable animations (FF55+) - https://bugzilla.mozilla.org/1352069
//user_pref("ui.submenuDelay", 150);				// set submenu delay in milliseconds (hidden pref)
user_pref("view_source.tab", false);				// open "View Page Source" in a popup window instead of a Tab
//user_pref("xpinstall.signatures.required", false);		// disable enforced extension signing (Nightly and ESR only)
```

I just copied the current title and header but we can change that as well.
Also changed some other things:
* "annoying warnings" inactive
* changed spellcheck to 2 because 1 is the default and it doesn't make sense for that pref to be in this section if we just enforce the default
* submenuDelay inactive

The only thing still missing in the draft is 5002, IDK what to do with that one.

**Comment by Thorin-Oakenpants** [comment]
will still trim some more off, and then I am also convinced that we should make the entire thing inactive - header will say something along the lines of: `if any of these interest you, add them to your overrides section` - that way we don't mess with people's setups re UI/workflow etc

**Comment by Thorin-Oakenpants** [comment]
5002 needs to stay in the 5000s or be removed. Full Screen API is already covered, so it's a user decision to go full screen, i.e websites can't trigger it (see `2418`). RFP is building in a maximizing window warning prompt which I assume will bypass 5002 anyway.

It's one of those ones we keep for info sake (and maybe add those two duration prefs), or ditch.

We can easily add a link to the reddit page in the header and be done with most of it - except it seems incomplete - see https://www.reddit.com/r/firefox/wiki/aboutconfig#wiki_fullscreen_behavior does not mention `full-screen-api.warning.delay` which we shouldn't encourage disabling anyway. All the other three are there - so ditch it, and add a

````
/* 5000: blah blah.
 * For some other Firefox UX behavior & appearance see [1]
 * [1] https://www.reddit.com/r/firefox/wiki/aboutconfig ***/
```

My only problem with this is that the reddit page links to privacytoolsio's list which is not a great list. 4 or 5 of the 20 numbered items are deprecated, erroneous info, or bad choices IMO. Also the reddit page itself duplicates a few prefs here which may end up be in conflict. In other words, we can't control what other sites do.

**Comment by Thorin-Oakenpants** [comment]
just thinking out loud, not liking the format with single lines, I personally do not like word wrap, and line lengths start to go off-screen = hard to read in one hit (note, I would use spaces not tabs - lets not go there). And it also causes a horizontal scrollbar ( boo! )

in section 5000 we can still lose the numbering, but for easier visual parsing I think we should go with. We can also lose the "action" word (eg enable/disable) and just list what it *is*. We can still group stuff under one "name" and we can still have some info in inline `//` comments

sample
```js
/* warnings ***/
   // user_pref("browser.tabs.warnOnClose", false);
   // user_pref("browser.tabs.warnOnCloseOtherTabs", false);
   // user_pref("browser.tabs.warnOnOpen", false);
/* appearance ***/
   // user_pref("toolkit.cosmeticAnimations.enabled", false); // (FF57+) 
   // user_pref("ui.submenuDelay", 150); // (hidden pref)
/* content behavior ***/
   // user_pref("accessibility.typeaheadfind", true); // http://kb.mozillazine.org/Accessibility.typeaheadfind
   // user_pref("layout.spellcheckDefault", 2); // 0=none, 1=multi-line controls, 2=all
/* UX behavior ***/
   // user_pref("tabprefone", true);
   // user_pref("two", true);
   // user_pref("three", true);
   // user_pref("view_source.tab", false); // open "page/selection source" in new window
```

I just think it looks cleaner and is easier to scan/read

**Comment by Thorin-Oakenpants** [comment]
we can ditch sub-menu delay for two three main reasons (I know ESR60 is not here yet)
 1. menu bar is off by default
 2. we used to be able to configure the menu bar since extensions could add items, and you could control it thru extensions like s3 menu wizard etc. It was great having 2 or 3 clicks to get to any command. But this ability is now limited/removed 57+, addons can easily be added to the bookmarks toolbar and have panels with loads of functionality (eg see violentmonkey) - so its no big deal to adapt away from the menu bar
 3. as discussed somewhere else, the original value I had was 75 or 100, the new value of 150 hardly differs from default 225 (from memory).

Photon does away with the menu bar and speeds are already "snappy"

**Comment by earthlng** [comment]
> I personally do not like word wrap, and line lengths start to go off-screen

time to buy a new monitor xD

> hard to read in one hit

users just have to read it **once** and enable the ones they want

> I would use spaces not tabs

agreed

> /* UX behavior ***/

isn't everything in 5000 kinda UX (User eXperience) stuff ? alphabetically is just super easy and we don't have to come up with groups for everything.

**Comment by Thorin-Oakenpants** [comment]
^^ `UI` then - user *interface*, or `UIX`

**Comment by earthlng** [comment]
what about the rest of [my proposals](https://github.com/ghacksuserjs/ghacks-user.js/issues/360#issuecomment-366403983) ?

**Comment by Thorin-Oakenpants** [comment]
getting there .. just doing it bit by bit - am a bit swamped man ... unimportant stuff like work, earning money, sleep, llama porn, and downtime

**Comment by Thorin-Oakenpants** [comment]
OT: i have a nagging nag-thing in the back of my mind about extensions clashing and I did not make a note anywhere .. so I'll dump it here

I recently edited the extensions wiki page (updated the wording on legacy NS and GM) - I read somewhere (uM/uBO repos?) where NS ***blocks*** other extensions from seeing "stuff" and this breaks uBO/uM - can't find the issue now

**Comment by overdodactyl** [comment]
Another pref maybe worth considering is the following:

```js
// user_pref("browser.urlbar.openintab", true);
```

which would open anything from the address bar in a new tab.  It doesn't land until FF 60, however.  

[Bug 1394304](https://bugzilla.mozilla.org/show_bug.cgi?id=1394304)

**Comment by Atavic** [comment]
Related:
https://github.com/uMatrix-Rules/uMatrix-Rules-Domain/blob/master/rules.txt
https://github.com/Synzvato/decentraleyes/issues/242

**Comment by Thorin-Oakenpants** [comment]
> * browser.link.open_newwindow - move to 2204 + also add `user_pref("browser.link.open_newwindow.override.external", 3);`

I removed `browser.link.open_newwindow` (5007) since its at default and has a setting in the UI

My `browser.link.open_newwindow.restriction` is at modified value `0` - so what does this do exactly: for anyone who wants to look it up for me. Is it some security minded thing (the word restriction indicates that to me, eg malicious scripts?). I wonder why mine is set to `0`

**Comment by earthlng** [comment]
2204 requires browser.link.open_newwindow=3 to achieve what we want and enforcing it makes sense here.

**Comment by Thorin-Oakenpants** [comment]
it does? 2204 doesn't say that, so I didn't pick up on it. Did you get that from looking at the code or something.

But yeah, if that's the case, then we can put it back in with 2204, and I want to know about that `browser.link.open_newwindow.override.external` one as well for 2200s

**Comment by Thorin-Oakenpants** [comment]
> remove `browser.stopReloadAnimation.enabled` because `toolkit.cosmeticAnimations.enabled` also disables the stop/reload animation

The `stopreload` has bugzillas for being too distracting, for being used on very short load times, etc - there's one open right now. Users might want to allow animations but just disable the stopreload one. So I think its still valid in its own right. I read somewhere that it's probably just a temp pref until they sort it all out - hence why it has a master under `cosmetic`

I guess we can remove it. Personally I don't have any distractions cuz I removed it via css - I assume this is that stupid bouncy ball thing?

**Comment by Thorin-Oakenpants** [comment]
^^ @smithfred (in case you didn't see this)

**Comment by Thorin-Oakenpants** [comment]
PS: I'll leave the parrot in for nostalgia's sake

**Comment by smithfred** [comment]
> ^^ @smithfred (in case you didn't see this)

Aw Oakenpants, you love me 😍
