### ISSUE TITLE
Q: Referers: prefs + uM + Smart Referer

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#361]
No doubt the ghacks-user.js spoof refering solution is very very good, but occasionally I have a need to relax those a bit.

I am just wondering what you guys are using for real to deal with those?
Is it uM or Smart Referer, or something else?

**Comment by Forsaked** [comment]
I disabled every referer spoofing in the user.js and just use uMatrix to handle this.

**Comment by Thorin-Oakenpants** [comment]
@Forsaked commented out does not mean reset .. I assume you meant you use the default values, right? :)

Me: i use the settings in the user.js as is (without checking, I think they're all at default except the 2 cross origin ones), and I use uM to spoof 3rd party requests (and haven't had an issue) ...

so I assume, effectively uM handles ALL cross origin (ignoring my settings) but i have no idea exactly what it "spoofs" as

I keep meaning to test out smart referrer now we're well into quantum

**Comment by crssi** [comment]
Thank you for feedback :+1: 
@Thorin-Oakenpants what are your active prefs then, since I am also leaning toward uM now, to handle cross origins. I have also troubles to find the details how uM hadles those.

**Comment by Thorin-Oakenpants** [comment]
> what are your active prefs then

for referrers: exactly as per the user.js master

**Comment by crssi** [comment]
but... cross origins are already covered by user.js master.
I am puzzled now why you need uM referer spoofing for?

**Comment by Forsaked** [comment]
@Thorin-Oakenpants Yeah, i just use the default values.

**Comment by crssi** [comment]
Cool... the only diff I can see is `network.http.referer.XOriginPolicy` to reset from 1 into 0 (default) and use uM `referrer-spoof: * true

Thank you @Forsaked and @Thorin-Oakenpants

If there are any other ideas... I am open to it. :)

Cheers

**Comment by Thorin-Oakenpants** [comment]
I just wanna know exactly what UBO spoofs as for 3rd party - since the extension overrides any FF prefs - someone dig out that info quick stat!

Other than that, at some stage I need to check out Smart Referrer as it may offer a better solution for some people (like me)

**Comment by Thorin-Oakenpants** [comment]
Will use this issue to finalize the referer section in #350

**Comment by crssi** [comment]
@Thorin-Oakenpants 

> I just wanna know exactly what uM spoofs as for 3rd party - **since the extension overrides any FF prefs** - someone dig out that info quick stat!

I haven't tested (I am your dogmatic believer :smiley:), but from your comment I understand that whatever is set in prefs, for example `network.http.referer.XOriginPolicy`, doesn't matter if I am using uM referer spoofing?

**Comment by Thorin-Oakenpants** [comment]
^^ my understanding is that extensions have the last say - otherwise, how would they work

**Comment by crssi** [comment]
I have tested a few scenarios and here are my findings:

Short explanation:
Here I have web application lets say `https://mypage.mydomain.com/`
On main page I can click a link (out of many) which opens a new window (in my case na new tab) to the same "domain", lets say `https://mypage.mydomain.com/someinfo?id=12345`
In this new tab I have additional info of interest.

**Test 1:**
pref = `network.http.referer.XOriginPolicy = 1`
uM = `referrer-spoof: * true`

A new opened page does **NOT WORK**.

**Test 2:**
pref = `network.http.referer.XOriginPolicy = 1`
uM = `referrer-spoof: * true`, **`referrer-spoof: mypage.mydomain.com false`**

A new opened page does **NOT WORK**.

**Test 3:**
pref = `network.http.referer.XOriginPolicy = 0`
uM = `referrer-spoof: * true`

A new opened page does **IS WORKING**.

If you have some ideas for additional test case, let me know and I will be happy to try.

Cheers

**Comment by Thorin-Oakenpants** [comment]
Oohh .. 1603 is ***when*** to send a referer .. I do not know if that can be overriden by an extension (but we should find out). I'm talking about ***what*** is sent in a referer (eg blocked, spoofed, trimmed, whatever)

**Comment by crssi** [comment]
I am puzzled also, why this case is treated as cross origin when its clearly not?
Maybe FF bug, when the followed new page is opened in a new window/tab?

 Just thinking out loud, my maybe "connected with this case" prefs (specially the second one): `privacy.firstparty.isolate = false` `privacy.firstparty.isolate.restrict_opener_access = true`

Need to test.

**Comment by earthlng** [comment]
@crssi your example makes no sense. IF that page is not working it's most likely because it tries to load something from another domain. Just open the network manager and see which requests are failing.

> Maybe FF bug, when the followed new page is opened in a new window/tab?

does it work when you open it in the same tab then? I highly doubt it

**Comment by crssi** [comment]
I haven't express myself best. Page does load, but application says `You must open main application window`.
Network manager shows no request failing and there is no another domain nor another host.

**Comment by earthlng** [comment]
can you share the page where this happens?

**Comment by earthlng** [comment]
and this only happens if you open the link in a new tab?

**Comment by crssi** [comment]
I cannot share, since its internal application working only on LAN.
The application always opens a new tab/window when clicking on link in the main window.

**Comment by Thorin-Oakenpants** [comment]
Well, I wanted some info on Smart Referer, so I could write something up for the #350 sticky, but I guess that'll never happen because everyone goes offscript

I do not have Smart Referer, I have not used it for a very very very long time - when I did, about 3 years ago, it was, from memory, install and forget - I do not remember seeing a sophisticated options interface in the legacy extension.

AFAIK Smart Referer uses some built in lists which minimize breakage (so these lists will betray you) - go read the repo issues. That's fine if you want the site to work, but not fine if you just want to read the content and couldn't give a sh*t about the pictures or something. This removes user choice (not knocking the product, and I do not have the full info)

I understand there are options to whitelist or blacklist or something. I have not had time to install it - so can someone please tell me if it can offer per site granular control and to what extent (eg do the minimize breakage lists override user rules etc)

**Comment by 2glops** [comment]
options available for SR :
Strict mode = domain and subdomain are considered different hosts
Exceptions = always allow referer (source / destination)
Whitelist source
Rewrite mode

**Comment by Thorin-Oakenpants** [comment]
So you can
- use strict mode (so all cross domain referers are blocked? or spoofed as same host as the 3rd party?)
- then allow exceptions (pairing source + destination)
- this sounds like granular control in my book

Whitelist is what? a whitelist of sources? or destinations? or either - two buckets to enter regex/strings & wildcards?

Rewrite mode I will assume is a mode which prompts, so you can configure it as you go?

If you don't use stricty mode, then I assume the build in "smart" lists of "smart" referer are used?.

Sounds like it can do almost any config to suit any user. I'll have to install it and play with it one day soon, as it's the one area I'm a bit sketchy on in my setup. That and I'm missing my legacy [NoRedirect](https://addons.mozilla.org/en-US/firefox/addon/noredirect/) - @earthlng : how's the API coming along for that?

**Comment by earthlng** [comment]
*crickets* https://bugzilla.mozilla.org/show_bug.cgi?id=1352653

**Comment by crssi** [comment]
@Thorin-Oakenpants 
I am puzzled now. 
Isn't uM referal spoofing control sufficient?
Which limitation, if any, in uM is/are bothering you?

**Comment by Thorin-Oakenpants** [comment]
@crssi - well for starters, as already asked .. WHAT is the uM spoofing rule - you need to answer that first before you can do a comparison

uM only spoofs. It has no fine grained control over source and destination - block, spoof, allow: and also what info to send (port, host, scheme etc)

**Comment by 2glops** [comment]
Whitelist source = simple text list, one should be able to write its own list

Rewrite mode as 3 possible sets, but you can't set it on the fly by site, you have to enter configuration page :
send the destination as referer
send nothing, direct hit
send your own choosen referer

If you don't use strict mode, your rewrite mode is applied on the domain basis

**Comment by Thorin-Oakenpants** [comment]
Thanks @2glops 

@crssi - have you answered your question about uM yet? if not re-open the issue, otherwise one day I will get to it in the sticky about prefs vs extensions etc

**Comment by crssi** [comment]
Thank you, my favorite girl :smile:, to take care of me.
About uM: Not to satisfaction.
But at the moment I have a hard time writing. Had some extreme skiing last week which lead to extreme foobar of my right shoulder, teared every possible ligaments there. So I have now a surgery scheduled soon and a couple of months to recover somehow.

Cheers

**Comment by atomGit** [comment]
also see [#373](https://github.com/ghacksuserjs/ghacks-user.js/issues/373)

**Comment by Thorin-Oakenpants** [comment]
OK, so I looked it up - [here](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches#spoof-referer-header)

> ... the referer information will now be foiled using the root URL derived from the URL of the request. For example, if the URL of a request is `http://www.example.com/blahblahblah/boring.html` and the referer is `http://google.com`, the referer will be spoofed using the `http://www.example.com/` string.

**Comment by crssi** [comment]
It would might be better if uM would have a different kind of implementation for referer spoofing.
What I have in mind is:
added another "referer" column in the swithch panel, beside frame or other.
Then scope would be the "source" and the column square would represent "destination".
green=allow referer
red=spoof referer

and in the config then for example
`referrer-spoof: * * true`
`referrer-spoof: * player.vimeo.com false`

This way we could get rid of "Smart Referer" as additional extension. Don't get me wrong here, I am not saying that "Smart Referer" isn't good, but uM could replace it in this case.

What do you think?
