### ISSUE TITLE
FF60: identity.fxaccounts.enabled

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#366]
https://bugzilla.mozilla.org/show_bug.cgi?id=1434706

```js
/* 0380: disable Firefox Accounts and Sync (FF60+) [RESTART]
 * This also hides all related UI elements ***/
   // user_pref("identity.fxaccounts.enabled", false);
```

Where do we put it .. under "quiet fox" say at 0380? This was added 1. for the new policy thingy and 2 tor want it anyway. Its probably best inactive since users still have to set up an account etc to actually use it, so therefore they willingly wanted it.

thumbs up or bitch about it below so I can make some sort of decision

**Comment by earthlng** [comment]
Sync doesn't make any connections unless someone signed up for it and thus putting it under quiet fox doesn't make much sense IMO. I would put it under 5000

**Comment by Thorin-Oakenpants** [comment]
that makes sense, I'll add it when I do the 5000 revamp which I want to wrap shortly
