### ISSUE TITLE
Cosmetic/readability suggestion

### ISSUE THREAD

**Issue by mazesy** [ghacksuserjs/ghacks-user.js#372]
Latest Firefox 58 user.js dated 3 Feb. 2018 includes 2110 lines.

Just a suggestion, that to separate entries:

```
/* 0203: disable using OS locale, force APP locale ***/
user_pref("intl.locale.matchOS", false);
/* 0204: set APP locale ***/
user_pref("general.useragent.locale", "en-US");
/* 0205: set OS & APP locale (replaces 0203 + 0204) (FF59+)
 * If set to empty, the OS locales are used. If not set at all, default locale is used ***/
user_pref("intl.locale.requested", "en-US"); // (hidden pref)
```

is far easier to read when displayed as

```
/* 0203: disable using OS locale, force APP locale ***/
user_pref("intl.locale.matchOS", false);

/* 0204: set APP locale ***/
user_pref("general.useragent.locale", "en-US");

/* 0205: set OS & APP locale (replaces 0203 + 0204) (FF59+)
 * If set to empty, the OS locales are used. If not set at all, default locale is used ***/
user_pref("intl.locale.requested", "en-US"); // (hidden pref)
```

Only mentioned for readability...

**Comment by Thorin-Oakenpants** [comment]
I know you were just posting an example... but FYI `intl.locale.matchOS` is deprecated in a couple days time: [1414390](https://bugzilla.mozilla.org/show_bug.cgi?id=1414390)

We don't do line spaces between section numbered items because 1) its silly... really really silly... monty pythonesque <sup>no citation</sup> silly 2) it would make spaces between sections insignificant 3) it would blow out the number of lines (more scrolling I guess and less to see in one hit when rerusing) 4) its easy enough to read if you use an IDE that supports some sort of syntax coloring 5) and even with an IDE and syntax coloring... what on earth is wrong with the `/* xxxx` bits to signify a new item.

Sorry, but I do not follow how adding line spaces makes this easier to read than it already is?

**Comment by mazesy** [comment]
> FYI intl.locale.matchOS is deprecated in a couple days time: 1414390

Thanks for the info (what a hazard).

Silly or not may be subjective and it certainly is if you disagree. I won't elaborate intellectually, all I know is that I do include line spaces myself and ever since I do, reading, finding items is far easier.

I'll just continue editing accordingly. After all anyone can do that, even if first edition over 2200 lines takes a little time. I'm surprised that obviously it isn't... obvious.

I'll close the door !=)

**Comment by Thorin-Oakenpants** [comment]
Not all sections are this short (i.e I can see ti all in one hit on my monitor), and not all sections have (almost) every pref active .. but here's a section - the line spaces signify a new section

![ide](https://user-images.githubusercontent.com/16656956/37213430-ea3cf2de-23a9-11e8-89c7-d8c6ea672b27.png)

Note also the sidebar foldable/collapsible elements, and how the one with the current focus is colored red. You can also fold all ... in Notepad++ the menu and shortcuts keys are under `View>``Fold-or-Unfold All` ... but that makes the content jump around and you lose your place, so I prefer to just use the collapse/expand button in the sidebar ... here's a pic
![idefold](https://user-images.githubusercontent.com/16656956/37213726-cf429988-23aa-11e8-82d0-52591442c442.png)

A couple of sections are long and have oodles of disabled content (comments and commented out prefs) and can be hard to spot/read the next item by item. But we're aware of it (eg 2600s)

**Comment by Thorin-Oakenpants** [comment]
> Silly or not may be subjective

Indeed, I gave a `no citation` .. followed by four extra valid arguments.. and now some pretty pictures for you

**Comment by mazesy** [comment]
As for the sections I add a little taste of independence with:

```
// ############################################################################
// 0100: STARTUP
// ############################################################################
user_pref("pants.testing", 100);

// 0101: disable "slow startup" options
user_pref("browser.slowStartup.notificationDisabled", true);
```

Worth mentioning that I always read js files as txt files and therefor no syntax coloring.

No big deal. It's only cosmetic!
Thanks @Thorin-Oakenpants for detailing.

**Comment by Thorin-Oakenpants** [comment]
```js
// ############################################################################
// 0100: MAN THIS IS UGLY OLD SCHOOL AND HIDEOUS UUUGH MY EYES MY EYES THEY BURN
// ############################################################################
```

----------
>  After all anyone can do that, even if first edition over 2200 lines takes a little time.

Just record (and save) a macro to search and replace til end of file, simple as heck

Start recording:
 - Find `/* xxxx` (using regex where x is numeric - I am not a regex person)
- go to start of line
- add line break (hit enter)
- go to end of line
Stop recording, save macro.

Run macro til end of file

**Comment by Thorin-Oakenpants** [comment]
> Worth mentioning that I always read js files as txt files and therefor no syntax coloring

Not my fault then is it? :) As Dot Parker said .. "You can lead a whore to culture, but you can't make her think"

**Comment by Thorin-Oakenpants** [comment]
So how the heck do you update the user.js? Do you use an overrides section and append like you should (because its the easiest way with the least amount of work) so it allows you to just download and replace the whole master js bit? I suspect not since you want to change the formatting. Man, you make life hard for yourself Tom

**Comment by mazesy** [comment]
> Not my fault then is it?
Why consider a suggestion as implying a fault?

> So how the heck do you update the user.js?
I take the time to overview major updates (those concerning FF version) and edit occasionally when reading threads here. Side-advantage is that I have a closer knowledge of the settings. Automatism is nice, of course. I guess I work like a Russian, manually!

```
// ############################################################################
// 0100: MAN THIS IS UGLY OLD SCHOOL AND HIDEOUS UUUGH MY EYES MY EYES THEY BURN
// ############################################################################
```
 That's not an argument. Sounds fancy :=)

**Comment by Thorin-Oakenpants** [comment]
not a single bite on the very clever authentic Dot Parker quotation .. *sigh*

**Comment by mazesy** [comment]
Not one single bit/bite indeed! I know you dislike bloated threads where digressions hide the essentials!

It was only a suggestion!
