### ISSUE TITLE
7 billboards outside ebbing

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#375]
* [x] billboard1: note to self: dom.disable_open_during_load - moved to #371 
* [x] billboard2: note to earthlng:
   * >  I used the short-form for the bugzilla links
   * any reason why we don't do this to the whole user.js? I count 135 instances of "show_bug.cgi?id=" we could remove .. that's 2160 chars (need to check those linking to a comment first)
* [x] billboard3: devtools.onboarding.telemetry.logged : default false, gets set to true by internals. Did we cover this somewhere? We can ignore this, see comments below
* [x] billboard4: investigate `extensions.webextensions.restrictedDomains` - is in diffs 59->60, will dealw ith it there
   *  [reddit](https://www.reddit.com/r/firefox/comments/84mghw/firefox_60_beta_lost_the_amo_working_extensions/)
   * https://hg.mozilla.org/integration/mozilla-inbound/rev/39e131181d44
   * https://bugzilla.mozilla.org/show_bug.cgi?id=1415644 (access denied)
* [x] billboard5: [1436851](https://bugzilla.mozilla.org/show_bug.cgi?id=1436851) group policy: disable system addon updates
   * unfortunately no straight-forward about:config pref available/created
* [x] billboard6: check 59+ if extensions that use [Window.localStorage](https://developer.mozilla.org/docs/Web/API/Window/localStorage) rather than [storage.local](https://developer.mozilla.org/Add-ons/WebExtensions/API/storage/local) still need a cookie exception - see [reddit](https://www.reddit.com/r/firefox/comments/84tvwa/addons_no_longer_working_when_cookies_are_disabled/) for a simple Disconnect test
   * yes, both local storage and IDB are fixed
* [x] billboard7: `xpinstall.whitelist.required` = the checkbox for warn when websites try to install addons
* FYI: [1429153](https://bugzilla.mozilla.org/show_bug.cgi?id=1429153) GPO disable telemetry

**Comment by Thorin-Oakenpants** [comment]
note to earthlng:

any reason why we don't do this to the whole user.js?

>  I used the short-form for the bugzilla links

I count 135 instances of "show_bug.cgi?id=" we could remove .. that's 2160 chars (need to check those linking to a comment first)

**Comment by Thorin-Oakenpants** [comment]
devtools.onboarding.telemetry.logged : default false, gets set to true by internals. Did we cover this somewhere?

**Comment by earthlng** [comment]
> any reason why we don't do this to the whole user.js?

:+1: ! we can also use `buglist.cgi?bug_id=` in certain places, fe:
```js
// 1806: disable Acrobat, Quicktime, WMP (the string = min version number allowed)
   // [-] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1317108,1317109,1317110
```

**Comment by Thorin-Oakenpants** [comment]
^^ sweet. I just tested one with a `#c*` at the end, works fine (we only have three of those anyway)

If you would like to, do a commit with your search and replace wizardry please, and I love that triple :) I have shitty paste in my main FF, I lose all line breaks

**Comment by Thorin-Oakenpants** [comment]
I'll wait for some sort of feedback .. [step1] I can do a commit to shrink the 135 bugzilla urls, and then I can [step2] look at scanning thru the document to see where we can combine them - please advise

**Comment by earthlng** [comment]
combine: 0209 0425 0910 2002 2674 4604 1806

**Comment by Thorin-Oakenpants** [comment]
2609

**Comment by Thorin-Oakenpants** [comment]
^^ please double check

**Comment by earthlng** [comment]
* the 2nd 0209 in 9999 has 1 [1] and 1 [-] - not a good idea to combine them
* 2609 references [2]
* 0374 has a comment for the 2nd link
* 1850 maybe combine the 2 `// FF52` ones and keep the 3rd separate, idk

**Comment by Thorin-Oakenpants** [comment]
Thanks

- fixed: whoops for mixing `[1]` and `[-]`
- fixed: 2609 reference to `[2]`
- 1850: I did that already, combined the two 52s left 53 separate
- 0374: covered that by rewording the comment

**Comment by Thorin-Oakenpants** [comment]
added a 4th billboard to first post .. something about privacy.resistFingerprinting.block_mozAddonManager not working on AMO any more

**Comment by Thorin-Oakenpants** [comment]
man, that ctrl key stuff in RFP is causing havoc

**Comment by Thorin-Oakenpants** [comment]
Regarding items listed under permissions (microphone `2024`, camera `2024`, location `0211`, notifications `2305`) and see #371 about possibly adding `dom.disable_open_during_load` = the permission for "block popup windows"

But, we do not have the pref `xpinstall.whitelist.required` = the the checkbox for warn when websites try to install addons (or the exception list) - is it worth adding this? Added to first post as a checklist item

**Comment by Thorin-Oakenpants** [comment]
`devtools.onboarding.telemetry.logged` - added new in 58 - not listed under earthlng's bugzillas - I think this is the ticket [1418266](https://bugzilla.mozilla.org/show_bug.cgi?id=1418266)

comment 1 (if that's how the code was finally done)
> User out of the experiment
>
>  Services.prefs.setBoolPref("devtools.enabled", false);
>  Services.prefs.setCharPref("devtools.onboarding.experiment", "off");

I don't think we want to disable `devtools.enabled`. Need some insight on this @earthlng if you have time. Does anything even get sent, ever, with our other settings such as URL

Maybe 3 works?

> 3 - User in the experiment, "regular group", not a DevTools user but already went through onboarding
> 
>   Services.prefs.setBoolPref("devtools.enabled", true);
>   Services.prefs.setCharPref("devtools.onboarding.experiment", "on");
>   Services.prefs.setBoolPref("devtools.onboarding.experiment.flipped", true);
>   Services.prefs.setIntPref("devtools.selfxss.count", 0);

**Comment by earthlng** [comment]
`devtools.onboarding.telemetry.logged` is only used [once](https://dxr.mozilla.org/mozilla-central/source/devtools/shim/devtools-startup.js#313) in the code and logs a telemetry probe using standard telemetry. Since we have telemetry disabled six ways from sunday nothing is ever sent.

**Comment by earthlng** [comment]
FYI re: bb5 - when the policies thingy is finalized, policies with `"enterprise_only": true` will only work in ESR. see https://dxr.mozilla.org/mozilla-central/source/browser/components/enterprisepolicies/schemas/policies-schema.json#105

**Comment by Thorin-Oakenpants** [comment]
Thanks for the devtools logging thing - I added it to the list of scattered todos/billboards because of a comment made somewhere else and I just wanted to follow up on it. Have checked it off that we can ignore it.

Re policies: I was kinda hoping that a lot of the stuff they were doing would be behind prefs we could use, but looks like unless it already existed (eg disabling the builtin pdf viewer see [1429160](https://bugzilla.mozilla.org/show_bug.cgi?id=1429160) ) then there is no pref, it's all non pref (eg disabling feedback ability see [1440574](https://bugzilla.mozilla.org/show_bug.cgi?id=1440574) ) .. oh well, shame, missed an opportunity

**Comment by Thorin-Oakenpants** [comment]
I want to test bb6 - **what is an extension that uses the right kind of storage that required a cookie in FF58**? (these two storage things do my head in, and I'll just screw it up and test the wrong one)

Expected test results
- in FF58 block all cookies: settings are not kept or able to be set
- in FF58 block all cookies + allow an extension cookie: settings are kept/set
- in FF59 block all cookies + do not allow an extension cookie: settings are kept/set

**Comment by crssi** [comment]
I haven't tested but if I understood you correctly with FF 59 we don't need to do cookies exceptions workaround, for extension data keep anymore?

**Comment by Thorin-Oakenpants** [comment]
> I haven't tested but if I understood you correctly with FF 59 we don't need to do cookies exceptions workaround, for extension data preserving anymore?

The ticket was about IDB. Extensions can also use local storage **of which there are two types**, only one of which is governed by cookie exceptions. That is what I want to test. I suspect that since cookies control both local storage and IDB (and I think asm.js and something else, don't care right now about those), then removing the cookie restriction should cover both - but I want to test it before I confirm it on the wiki page.

Add to all of this the mass confusion over some 60+ bugzillas over the last three or four releases and counting over all the storage and persistent items and various caches and clearing mechanisms and quotas and non-functional warnings and OA issues and PB restrictions and a ton more items (and side-effects such as orphaned persistent data), that I've basically lost track - I hope to clear all that up with #379 . One of the issues I think, if I can find it, is that clearing local storage clears extension local storage - I need to confirm that, I do not clear local storage myself because I never let any in - and again, extensions are mixing up the two types of storage.

> I'll just screw it up and test the wrong one (Thorin)

So first things first, I want an extension with some local storage settings that I can confirm require a cookie, test in 58, test in 59 - then I can also test it in PB mode (which clears data) and in normal mode clearing on close or manually, etc.

**Comment by earthlng** [comment]
uBO's 3rd-party list-groups collapsed state is stored using localStorage.

I think for localStorage the patch fixed the "able to be set" part but the data is still deleted when you clear Offline Website Data manually or on shutdown.

IndexedDB for webextensions should no longer need an exception either AND the data will be kept.

**Comment by Thorin-Oakenpants** [comment]
Is that what it was, clearing OWD does that? I had a feeling there was another one...  OWD used to mean IDB, but I guess they've been wrapping things up into quotas and combining them (which makes sense - eg you delete a cookie, it should also delete LS + IDB)

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

**Comment by earthlng** [comment]
for nightly: https://dxr.mozilla.org/mozilla-central/source/browser/modules/Sanitizer.jsm

cookies is cookies+deviceIds+plugin data
OWD is appcache+localStorage+serviceworkers cache+QuotaManager (= IDB, asm-cache (etc?))

**Comment by Thorin-Oakenpants** [comment]
^^ ok, thanks: that's handy. QM I think includes service workers, but don't quote me on that

Ahh OK, it requires `dom.storageManager.enabled` (`2750`) enabled so I guess we need to deal with that soon, probably before 60 lands - almost ready to allow all kinds of storage and all-types-of-workers and rely on default-cookie block, uM worker block, and watch my persistent data

**Comment by Thorin-Oakenpants** [comment]
I need a better/real test extension - [reddit](https://www.reddit.com/r/firefox/comments/84tvwa/addons_no_longer_working_when_cookies_are_disabled/) - I tired with AdBlock Plus and it works regardless of cookies blocked or not in 58 - it remembers by custom filters, option changes, even with clearing everything manually .. that redditor lied to me man!

**Comment by earthlng** [comment]
> uBO's 3rd-party list-groups collapsed state is stored using localStorage

!!!

**Comment by Thorin-Oakenpants** [comment]
^^ nah .. I want something easier for my head to follow, plus already been over that collapsed state thing in another thread and it did @grauenwolfe 's head in

Disconnect
- FF58.0.2 nilla profile: Disabled cookies, added disconnect, toolbar icon is stuffed, allowed extension cookie exception, and it works fine. Note: no IDB entries, it is all local storage, the one controlled by cookies
- FF59.0.1 nilla profile: disabled cookies, added disconnect, everything works perfectly

Extra test
- FF59.0.1: added a site exception, closed-reopened, everything is cool baby. Manually cleared OWD and disconnect site exception is wiped

**Comment by Thorin-Oakenpants** [comment]
I am going to test that clearing OWB with Storage Manager enabled/disabled. Because I clear OWD on close and manually, but I never lose anything (maybe its just my extension set)

**Comment by Thorin-Oakenpants** [comment]
Nope, having Storage Manager enabled/disabled does not affect OWD clearing wiping extension local storage data. I guess my extensions all use storage.local (and/or IDB) for the important parts.

**Comment by Thorin-Oakenpants** [comment]
> cookies is cookies+deviceIds+plugin data
> OWD is appcache+localStorage+serviceworkers cache+QuotaManager (= IDB, asm-cache (etc?))

https://bugzilla.mozilla.org/show_bug.cgi?id=1400678 - if I read this right, then when you clear a cookie, you also clear "quotas"? So maybe `+QuotaManager` will be moved from OWD to cookies? IDK

I'm quite keen to add this to the user.js 2800 section header
```
/*** 2800: SHUTDOWN [SETUP]
     Blah blah
     [1] As of FF59 "Offline Website Data" includes appCache (2730), localStorage (2710),
         Service Worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache) 
***/
```

**Comment by earthlng** [comment]
"As of FF59" ?? seems to be the same in [ESR52](https://dxr.mozilla.org/mozilla-esr52/source/browser/base/content/sanitize.js#366)
bugzilla is down atm and I can't check what that link is about.

**Comment by earthlng** [comment]
bb6: update the wiki?

**Comment by Thorin-Oakenpants** [comment]
> bb6: update the wiki?

I [did](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1.1-Setting-Extension-Permission-Exceptions/_compare/e6fdd42cd1f1d42db95e363f7f4ba24a3a5ed604...c759e77babbe509525ec9816b5104d4d93cf6a88) , 20 hrs ago

**Comment by Thorin-Oakenpants** [comment]
> "As of FF59" ??

I wondered about that, because your initial comment says nightly. My intitial idea was to drop the version and just add `this is a work-in-progress` at the end

**Comment by grauenwolfe** [comment]
> I am going to test that clearing OWB with Storage Manager enabled/disabled. Because I clear OWD on close and manually, but I never lose anything (maybe its just my extension set)

> Nope, having Storage Manager enabled/disabled does not affect OWD clearing wiping extension local storage data. I guess my extensions all use storage.local (and/or IDB) for the important parts.

Just a reminder that I tested all of this fairly extensively a while back when having issues with FF57 and uBo's storage and Dashboard settings getting wiped on close [#273](https://github.com/ghacksuserjs/ghacks-user.js/issues/273). At least for me, it's a new issue that started with FF57 and on, never before.

Quick recap:
Reinstalling FF fixed the issue with uBo's filter lists having to be updated every launch but the Dashboard settings are still reset every time if OWD is cleared like not remembering dashboard's last selected tab so always reverting to the default "Settings" tab and not remembering if filter lists were collasped or expanded. These are decidedly very minor issues but still annoying.

**Comment by Thorin-Oakenpants** [comment]
In 57+ I've never had any issues with uBO's storage .. **for the important parts** (lists for me being in normal mode are in IDB)... and never noticed any problems with the dashboard (eg collapsible state) because I'm never really in there. I think we decided this was a Mac problem, if IIRC

I have only just enabled the Storage API (and appCache so it works) and can now see the "Site Data" section in Options - but I've yet to see anything get stored in there, and haven't tested the "Clear All Data" button.

I think I'll re-purpose #379 as a tracking issue to do with "Site Data", QuotaManager and Storage v2 / Storage API, and Sanitize issues. One of which is extension localStorage data is wiped with OWD. Some uBO settings are stored in localStorage

**Comment by Thorin-Oakenpants** [comment]
should we do anything about bb7? default value is what we want, so it would only be for locking it down and info

**Comment by earthlng** [comment]
I don't really understand why this is even available in the UI tbh. Enforcing the default value seems like a good idea to me

**Comment by earthlng** [comment]
It's not really "enforcing" when there can be exceptions, is it? I would just use the same string as in the UI.
And maybe we can ditch "Options" in all the [SETTING] tags?

**Comment by Thorin-Oakenpants** [comment]
:+1: to s&r `Options>` with null - 87 of them (I'll check em first, some might not be right after a [setting*] tag

---
trying to keep our "action" words, the one right after a `number:` to a select few. I'll do a little test .. "Well it's not really warning when there can be exceptions, is it?" - I get your drift though, don't get antsy. Fixed .. enable warning

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/pull/388

**Comment by Thorin-Oakenpants** [comment]
Forgot to deal with this

```
/*** 2800: SHUTDOWN [SETUP]
     Blah blah
     [1] "Offline Website Data" includes appCache (2730), localStorage (2710),
         Service Worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache) 
***/
```

yes? no? reword? did you want to check that [ESR](https://dxr.mozilla.org/mozilla-esr52/source/browser/base/content/sanitize.js#366) link, keeping in mind that ESR still has all the sanitize bugs (except that IDB one)

**Comment by earthlng** [comment]
why the [1] ? we use that for links, no? otherwise :+1:

**Comment by Thorin-Oakenpants** [comment]
see #390
