### ISSUE TITLE
Question: Any way to set default Search engine using user.js?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#376]
Self-explanatory. ;)

**Comment by Thorin-Oakenpants** [comment]
you need to have an engine with the same name already existing in your profile

**Comment by Thorin-Oakenpants** [comment]
enter `search*default*engine` in about:config - these two prefs are FF's internal default search engines - I guess when you reset engines. They do not change when you manually change your default eg from options or from the searchbar dropdown

**Comment by Thorin-Oakenpants** [comment]
I can't see any pref changes when I change defaults - maybe its now stored in an external file

**Comment by Gitoffthelawn** [comment]
Ya, from what I can tell there is no pref to do it.  The default search engine seems to be only stored inside `search.json.mozlz4`.  (Unless I'm happily mistaken.)

I'm not entirely sure what `browser.search.defaultengine*` affects, if anything.

**Comment by Thorin-Oakenpants** [comment]
I just told ya .. the prefs are for FF's regional search defaults

**Comment by Gitoffthelawn** [comment]
But if you change the prefs, you would think that the regional search defaults would change.  No matter what I set those prefs to, they don't seem to affect the search default.

What is it actually affecting?

**Comment by Thorin-Oakenpants** [comment]
dunno, don't care - there is a whole ton of UI for people to deal with search engines, and not something that can be automated in a user.js. Those prefs are meaningless to us

PK has this
```js
// PREF: Set the default search engine to DuckDuckGo (disabled)
// https://support.mozilla.org/en-US/questions/948134
//user_pref("browser.search.defaultenginename", "DuckDuckGo");
//user_pref("browser.search.order.1", "DuckDuckGo");
//user_pref("keyword.URL", "https://duckduckgo.com/html/?q=!+");  
```

Note that it is commented out. First of all, you would need an engine of the same name for it to work. Secondly, and I am not an expert, but search has recently changed (eg see that moz.v4 thing) - the engine and order prefs have nothing to do with you setting **your** default search engine anymore

The value are set by FF internally, and is used, AFAICT, when you **RESET** your search engines (you know, that `restore default search engines` button in about:preferences#search , not when you set a default

**Comment by Thorin-Oakenpants** [comment]
I would keep an eye on https://github.com/mozilla/policy-templates/blob/master/README.md to see if Group Policy ever adds search engine capabilities

**Comment by earthlng** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1428948
