### ISSUE TITLE
Hidden pref browser.cache.disk.enable might be essential

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#377]
When the user turns off the disk cache using Firefox's *Options* UI, `browser.cache.disk.enable` is not set to `false`.

This causes some sites to fail, such as [openmailbox.org](https://www.openmailbox.org/) (try clicking on "Access Openmailbox" in the upper-right corner of that page).

Fortunately, 
`user_pref("browser.cache.disk.enable", false);`
is included within user.js.

But it's really weird that this hidden pref seems to be required for everything to work as expected.

Tested on Firefox 59.

I welcome your feedback and additional testing.

**Comment by Thorin-Oakenpants** [comment]
> When the user turns off the disk cache using Firefox's Options UI

Where is this `options UI` exactly? I don't see one.

**Comment by Gitoffthelawn** [comment]
`about:preferences` or Tools->Options

**Comment by Thorin-Oakenpants** [comment]
need more than that

Do you mean about:preferences#privacy > Cached Web Content > Override automatic cache management

**Comment by Gitoffthelawn** [comment]
Yes, that's it.  (BTW, FF60 completely removes that section :-1: )

**Comment by Thorin-Oakenpants** [comment]
A lot of stuff is happening with storage v2, so I guess this is part of it - FWIW, I could have sworn there used to be an options UI checkbox for disabling disk cache, but I also never added a [SETTINGS] tag in the user.js, so maybe not - can't be arsed downloading an old FF to check.

I will check what pref is changed by that 59 checkbox - just not today

In 60 (and I guess I'll have to download a portable beta as well now), set `2750` to both true to enable the new section, see what pops up in there.

```
user_pref("dom.storageManager.enabled", false); // (FF51+)
user_pref("browser.storageManager.enabled", false); // (FF53+)
```

The 2nd pref is going to be removed (it controls the visibility of the section for now). Even in 59, maybe the first pref is now needed to control cache, IDK. Too many under the hood changes.

https://bugzilla.mozilla.org/show_bug.cgi?id=1286798 - meta
https://bugzilla.mozilla.org/show_bug.cgi?id=1421690 - meta
https://bugzilla.mozilla.org/show_bug.cgi?id=742822
https://bugzilla.mozilla.org/show_bug.cgi?id=1354500

tons of others you can get to from the metas as well

**Comment by Gitoffthelawn** [comment]
For reference, in FF60, both of the following are set to `true` by default:

```
dom.storageManager.enabled

browser.storageManager.enabled
```

**Comment by Thorin-Oakenpants** [comment]
When you check and uncheck about:preferences#privacy > Cached Web Content > Override automatic cache management - it affects the pref `browser.cache.disk.smart_size.enabled` - this is included in the user.js

For the record, the pref `browser.cache.disk.enable` is not a "hidden pref". A hidden pref is one which is not exposed in about:config when `modified` - you can test if a pref is hidden by resetting it, and it should change it's value to a null/blank, and then if you reload about:config the pref will no longer show

All the relevant prefs are active and included in `1001`, so if end users want to disable disk cache (or enable it), then it's all there. If there is a problem with sites described as per OP, then IMO that is a FF bug and someone should lodge a bugzilla

eg: 
Title: when cache override at zero is used then set `browser.cache.disk.enable`=>false
STR: check "Override automatic cache management" and limit cache to zero, go to openmailbox.org and try clicking on "Access Openmailbox" in the upper-right corner of that page
AR: openmailbox.org doesn't work
ER: openmailbox.org should work
Solution: `browser.cache.disk.enable`=> false seems to fix this

I'm not doing it, but someone probably should

**Comment by Thorin-Oakenpants** [comment]
closing, but if anyone lodges a bugzilla, let me know
