### ISSUE TITLE
reminder: deal with offlinecache + storageManager etc

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#379]
- 2750: stop hiding "Options>Privacy & Security>Site Data" via `browser.storageManager.enabled`
   * pref will be removed anyway [1428306](https://bugzilla.mozilla.org/show_bug.cgi?id=1428306)
- investigate items required to get this working
   * 2750: dom.storageManager.enabled
   * 2730: browser.cache.offline.enable
   * in 59 so far this is not enough (maybe it needs a restart)
- list relevant issues with the new section, eg quotas, dealing with offline cache, etc.

I have a feeling that this storage v2 will be ready for 60

**Comment by Atavic** [comment]
>list issues dealing with offline cache, etc.

There are some about [IndexedDB](https://github.com/ghacksuserjs/ghacks-user.js/issues/235#issuecomment-354064787), [serviceWorkers](https://github.com/ghacksuserjs/ghacks-user.js/issues/234) etc.

**Comment by Thorin-Oakenpants** [comment]
- remove `browser.storageManager.enabled` in `2750` - it only shows/hides the UI, and looks like it will be removed anyway

:+1: or :-1: 
- make `dom.storageManager.enabled` => inactive
- make `offline-apps.allow_by_default` ==> inactive

This then allows the section on `Site Data` for users to manually clear and check various site data info (it's not perfect, there are plenty of bugs). The only drawbacks is obviously appcache (I have no idea how many sites use this) and the other is that 1st party sites can check their space/usage which could be a FP'ing vector, IDK for sure

Slighty OT: [ghacks](https://www.ghacks.net/2018/02/26/mozilla-removes-individual-cookie-management-in-firefox-60/) : in 60 the `show cookies` option is removed from the UI - but users can still open any site info dialog and click the security tab and clear the filter, or you can bookmark chrome://browser/content/preferences/cookies.xul

**Comment by earthlng** [comment]
why `offline-apps.allow_by_default` ? that doesn't seem to be necessary. But it does require `browser.cache.offline.enable=true` to work correctly, otherwise it's always "Calculating site data and cache size..." and the buttons are disabled.

**Comment by earthlng** [comment]
```js
user_pref("browser.cache.offline.enable", true);
user_pref("browser.cache.offline.insecure.enable", false);
user_pref("browser.cache.offline.capacity", 1);
```
or maybe set .capacity to 2 + `offline-apps.quota.warn=1` to get a warning/prompt when a site tries to write more than 1Kb? not sure if a warning/prompt is shown at all, though.
On the other hand, limiting the capacity isn't really necessary if we delete OWD on shutdown IMO.
insecure.enable might default to false in FF60+ anyway and we can also ignore it - up to you.

**Comment by Thorin-Oakenpants** [comment]
Sorry, was tired, said the wrong pref name - I mean 2730, not 2731. Edited the post

**Comment by Thorin-Oakenpants** [comment]
PS: as you suspect, AFAIK, warning quotas have never worked, notifications do not happen. This will all get fixed over time with the storage manager v2 and quota manager etc. 

We could probably get rid of 2731+2732. The UI doesn't even match anymore

**Comment by Thorin-Oakenpants** [comment]
https://www.fxsitecompat.com/en-CA/docs/2018/support-for-application-cache-on-insecure-sites-has-been-deprecated/

> Note that the AppCache support itself has also been [deprecated since Firefox 44](https://www.fxsitecompat.com/en-CA/docs/2015/application-cache-api-has-been-deprecated/) and will be completely [removed in the future](https://www.fxsitecompat.com/en-CA/docs/2016/application-cache-support-will-be-removed/) in favour of the richer Service Worker API

That first link in the quote is interesting => [1163545](https://bugzilla.mozilla.org/show_bug.cgi?id=1163545) : Bypass AppCache completely when Service Workers supported & registered. I do not have SW enabled.

Also FF60+ insecure sites no longer have access to appCache. TBH, I'm kinda struggling here to get any sites to dump any appCache on me. I think the downside to allowing appCache is a non-event

**Comment by earthlng** [comment]
> as you suspect, AFAIK, warning quotas have never worked, notifications do not happen.

AFAIK that's not true. try http://devdocs.io/

**Comment by Thorin-Oakenpants** [comment]
I could have sworn I read somewhere in the bugzillas that notifications were (no longer) working, and it was an old ticket linked to (obviously when they were first set up they worked - see [767256](https://bugzilla.mozilla.org/show_bug.cgi?id=767256), so they did at least exist and work 6 years ago)

Anyway, you said "not sure if a warning/prompt is shown at all, though", and I replied that *afaik* they were broken. I guess I read or mis-remembered it (thanks for clearing that up, good to know)...  I planned on listing out all the important issues to do with storage to get a better picture - its a real mess.

... its a real mess, for example
- did you know that clearing site data only clears local storage for those sites that have IDB entries (I think, listing sites vs actual sanitizing) - https://bugzilla.mozilla.org/show_bug.cgi?id=1427234
- did you know session only data is not being cleared - https://bugzilla.mozilla.org/show_bug.cgi?id=1441847
- forget this site doesn't clear SWs - https://bugzilla.mozilla.org/show_bug.cgi?id=1252998

and it goes on... the rabbit hole is very deep and the longer I leave it, the better for my sanity

**Comment by earthlng** [comment]
lol, glad I'm still on ESR :)

**Comment by Thorin-Oakenpants** [comment]
Its quite astounding just how bad all of this is. It's no better IMO in ESR. The only reason its been efficiently dealt with up til now (for me at least) is I did not use any extensions (FPI and orphaned data BS), i block 99.9999% of all cookies (and subsequent localstorage + IDB), and workers+SW and appCache were all turned off.

Not 100% sure what losing workers pref will cause but I have uMatrix, and appCache looks like it isn't used much and will at least warn me and allow me to deny ... other than that, my strategy is still looking damn good

No doubt you've been playing a bit in 57+ .. I just hope you're ready for the shock of jumping from ESR52.9 to 62 .. although I gotta say the stable train was/is bumpy to say the least

**Comment by Thorin-Oakenpants** [comment]
closing this: I will revisit the rabbit hole well into 61 beta or later, at least 10+ weeks of ignoring this issue (yay!) - hopefully by then loads of bugzillas will be fixed re storage quotas sanitize etc. For now 60 looks fine with these slight changes - appcache has to ask (no idea if the site permissions panel is respected), and nothing else really changed.
