### ISSUE TITLE
60+ date testing with RFP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#380]
In FF 60+ they fixed locale/formatting leaks, which is what I want to test - see [1409973](https://bugzilla.mozilla.org/show_bug.cgi?id=1409973)

Note: I do not know if the test sites (see results below) are manipulating the display formatting

**Comment by Thorin-Oakenpants** [comment]
grrr .. its 60+ they fixed it, which is what I wanted to test - see [1409973](https://bugzilla.mozilla.org/show_bug.cgi?id=1409973)

I will retest with 60 later on

**Comment by Thorin-Oakenpants** [comment]
still no 60 portable available *sigh* ... https://portableapps.com/apps/internet/firefox-developer-portable

**Comment by earthlng** [comment]
https://portableapps.com/apps/internet/firefox-portable-nightly

**Comment by Thorin-Oakenpants** [comment]
^^ date updated: 2018-01-29, plus it'll be the wrong release channel if I update it

**Comment by earthlng** [comment]
> date updated: 2018-01-29

the portable nightly installer always downloads + installs the latest nightly of the same version as the installer.

**Comment by Thorin-Oakenpants** [comment]
>  installs the latest nightly of the ***same version*** as the installer

now that I did not know

**Comment by Thorin-Oakenpants** [comment]
### FF60.0b5 (with FF59 in code boxes)

http://browserspy.dk/date.php

Time and date 	Tue Mar 20 2018 16:04:18 GMT+0000 (UTC)
GMT'ed 	Tue, 20 Mar 2018 16:04:18 GMT
Locale String 	3/20/2018, 4:04:18 PM 

```
Time and date 	Sun Mar 18 2018 10:52:36 GMT+0000 (UTC)
GMT'ed 	Sun, 18 Mar 2018 10:52:36 GMT
Locale String 	3/18/2018, 10:52:36 AM 
```

https://browserleaks.com/javascript

System Time	Tue Mar 20 2018 16:02:36 GMT+0000 (UTC)
Time Zone	UTC
toLocaleString	3/20/2018, 4:02:36 PM
toLocaleFormat	n/a

```
System Time	Sun Mar 18 2018 10:53:49 GMT+0000 (UTC)
Time Zone	UTC
toLocaleString	3/18/2018, 10:53:49 AM
toLocaleFormat	n/a
```

**Comment by Thorin-Oakenpants** [comment]
So they didn't change anything then. It still leaks locale, and the format hasn't changed one iota

**Comment by Thorin-Oakenpants** [comment]
I am interested to see what @Forsaked returns in his German language FF60

**Comment by crssi** [comment]
^^upper is correct for German.

cheers

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1287503

Wonder if this API leaks locale etc

**Comment by Thorin-Oakenpants** [comment]
Also, if you're playing with RFP and testing TZ's .. note https://bugzilla.mozilla.org/show_bug.cgi?id=1470161 - you need to restart FF in order to turn off TZ spoofing

**Comment by Thorin-Oakenpants** [comment]
https://trac.torproject.org/projects/tor/ticket/26611

**Comment by Thorin-Oakenpants** [comment]
I don't have time to test this in FF62. If users are using en-US, then I do not think (but I am not sure) that the date format may differ. I hope not. I'll just follow the tortrac tickets and let them see if anything leaks
