### ISSUE TITLE
FHR + Shield vs release channels

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#381]
So I'm playing around with Dev (60) and also noted the changes to normandy for shield (see https://github.com/ghacksuserjs/ghacks-user.js/commit/04f14490035d12c059f4a07a124681be1c843c68)

### stable
![1-stable](https://user-images.githubusercontent.com/16656956/37637976-8632172c-2c02-11e8-96df-1a1cf171c408.png)

### developer (and probably nightly?)
![2-developer](https://user-images.githubusercontent.com/16656956/37637978-8aa8767a-2c02-11e8-88d9-3e97f291b887.png)

In common
- 1 (send technical data) governs `datareporting.healthreport.uploadEnabled` `0333`
   * commit https://github.com/ghacksuserjs/ghacks-user.js/commit/c38ae562326b849b1f73335b4fe31cd72eb96255
- 2 (send crash reports) governs `browser.crashReports.unsubmittedCheck.autoSubmit2` `0351`
   * commit https://github.com/ghacksuserjs/ghacks-user.js/commit/6cb27ca78c01dbd123a3df3a78eed2a228e59cc3

---
So far so good. Developer (and nightly?) has an extra option to do with shield studies (1b in the pics)

- 1b (install and run studies) governs `app.shield.optoutstudies.enabled` not in user.js
- note that 1b is a sub-item
   * if you check or uncheck 1, it auto checks or unchecks 1b
   * BUT, you can check 1 and then uncheck 1b
- Tested on a restart (allow 1 but disallow 1b), it sticks (tested after looking at DXR code to make sure)

So you can allow data reporting but opt out of shield. But you cannot do the reverse (note to self: check what happens if I change values in about:config and bypass the UI)

Should we add this to the user.js in some way in 0512
```
user_pref("app.shield.optoutstudies.enabled", false);
```

**Comment by Thorin-Oakenpants** [comment]
>  note to self: check what happens if I change values in about:config and bypass the UI

![ohnoes](https://user-images.githubusercontent.com/16656956/37638321-1fc12dc8-2c04-11e8-8402-32fcd7133e21.png)

Well, damn: That's probably not intended behavior - someone should lodge a bugzilla to check if it's ok. I am not entirely sure what the code does to handle this situation (I looked but I can't read half that stuff)

more reason for us to lock this pref down in the user.js. FWIW, the pref in my main FF stable is modified false (probably by the reporting pref). Just not sure how to meld it into the user.js

**Comment by earthlng** [comment]
the 2 `extensions.shield-recipe-client.*` in 0512 are removed in FF60 and Normandy/Shield is no longer a system addon. Therefore I would create a new 0503 because at 05**10**+ are the actual system addons.
```js
/* 0503: disable Normandy/Shield (FF60+)
 * Shield is an telemetry system (including Heartbeat) that can also push and test "recipes"
 * [1] https://wiki.mozilla.org/Firefox/Shield
 * [2] https://github.com/mozilla/normandy ***/
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("app.shield.optoutstudies.enabled", false);
```

**Comment by Thorin-Oakenpants** [comment]
good thinking
