### ISSUE TITLE
test: cookies controlling 1st party storage

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#390]
2701: cookies control access to blah blah. Does this control **1st party** storage. Test required.

> [NOTE] This also controls access to 3rd party Web Storage, IndexedDB, Cache API and Service Worker Cache

Note: With Web Extensions it certainly blocked Extensions using IDB (exhibit A: uBO, uM, VM, Stylus). It also blocked them using localStorage as well (see Disconnect test I did a few days ago). Not sure if that means they were treated as first party.

Feel free to test and post STR and outcomes

PS: reminder about HW-A and `gfx.direct2d.disabled`

**Comment by Thorin-Oakenpants** [comment]
### Simple Test No.1

The Setup:
- Nilla profile, FF59.0.1: I allowed 1st party cookies only. I cleared all `Site Data` (from about:preferences#privacy), I cleared history, i.e time range everything, and all check boxes checked (ctrl-shift-del). I checked I had zero cookie exceptions, and I had no cookies. A bit overkill, nilla profile, but hey, ZERO data

The Control:
- load github, open Storage Inspector (Shift-F9, make sure your github page has focus)
   * cookies, yes
   * localStorage, yes (2 items)
   * IDB, no (this is handy for tests later on re santizing, hence why I mention it)

The Test:
- under options, block ALL cookies
- scrub all data (see setup), repeat control test
   * cookies, no
   * localStorage, no

The Picture:
![localstorage](https://user-images.githubusercontent.com/16656956/37966292-93823ef6-31b7-11e8-8871-2bd13e027be6.png)

**Comment by Thorin-Oakenpants** [comment]
I need a test site that only does IDB (not youtube, that uses SWs to push its storage). I'll test YT later

**Comment by Thorin-Oakenpants** [comment]
When I get time I will test SW's->IDB which is what Youtube does

**Comment by Thorin-Oakenpants** [comment]
That's all I ever thought blocking cookies protected me from as 1st party: localStorage and IDB. My assumption was based on experience (eg see issues with extensions) etc. I never did any tests.

I also never thought about service workers (because they are disabled) or appCache (which until now was disabled). I have done some interesting tests with appCache .. see next post

**Comment by Thorin-Oakenpants** [comment]
PS: I am not sure if these tests are definitive, so poke holes in any procedural flaws or assumptions etc

### Simple Test No.3 (appCache)

Site: https://devdocs.io/ (note: secure context required for appCache these days, can;t be bothered looking up which version it kicks in)

Side Quest:
- set `offline-apps.allow_by_default` to false and the site prompts to "allow storing data"
- There is no option to remember - allow or deny. I clicked allow
- There is no change to site permissions panel info.
- Reload the page, it remembers. Clear everything except site permissions, reload, it still remembers.
Clear site permissions and it forgets
- So maybe a bit of a bug re permissions panel info, but ONLY if `Store data in persistent storage` is meant to relate to this

The Control:
- allowed 1st party cookie, scrub all data, load site, "allow storing data" if prompted
- Storage Inspector (which does not display info on appCache) shows
   * cookie, localStorage, IDB = yes
   * cache storage, session storage = no
- profile/OfflineCache/index.sqlite
   * lots of devdocs entries

AppCache Sanitizing Tests:
 - both `Site Data>Clear All Data` and clear everything (ctrl-shift-del) wiped the appCache (yes I did separate tests)

The Test:
- scrubbed all data, blocked 1st party cookie, loaded site
   * profile/OfflineCache/index.sqlite showed lots of devdoc entries

So cookies do not control 1st party appCache - that's what the prompt is for

**Comment by Thorin-Oakenpants** [comment]
@earthlng : does this answer your question?

- The `NOTE` is correct, but it also happens to be that cookies (for now) also control **1st party** localStorage and IDB.
- AppCache, which I tested because we flipped it, is not controlled by cookies, but the sanitizing and prompts work, so we're covered there.
- As for SW cache, I doubt a cookie controls it as 1st party - not even sure how to test it TBH. We don;t even claim it's covered as 1st party. Thoughts?

Can I close this now? PS: I want to ignore the HW-A thing!

**Comment by Atavic** [comment]
Related to: https://github.com/ghacksuserjs/ghacks-user.js/issues/390#issuecomment-376639248

>How does this work?

https://devdocs.io/offline

>Each page is cached as a key-value pair in IndexedDB (downloaded from a single file).
>The app also uses AppCache and localStorage to cache the assets and index files.

**Comment by Thorin-Oakenpants** [comment]
I was testing appCache (since we made it inactive in order to make `Site Data` in the UI work). I tested four things:
- sanitizing on close = same as clear recent history = works
- clearing site data button = works
- if cookies were involved - not used
- the prompt = works

Not sure by what you mean "how does this work?" I don't care if the site works or not (or how it works), I was just testing persistent local data

**Comment by earthlng** [comment]
nicely done, thx! So cookies also controls *some* but not all storage. I assume that means when cookies are blocked storage is also blocked for both 1st and 3rd party. When cookies are allowed for 1st-party only then 3rd party storage should still be blocked.
The UI does now also reflect that better than it used to ie it no longer just says "cookies" but "Cookies and Site Data". If you toggle between "Accept cookies and site data from websites (recommended)" and "Block cookies and site data" you can see that "Accept third-party cookies and site data" also changes from Always to Never and vice-versa.
Pref-wise, selecting "Block cookies and site data" sets `network.cookie.cookieBehavior` to 2.
"Accept cookies and site data from websites (recommended)" sets "Accept third-party cookies and site data" to "Always" which means `network.cookie.cookieBehavior` = 0, and to achieve 1st-party only (= `network.cookie.cookieBehavior` = 1) you then have to set "Accept third-party cookies and site data" to "Never".
Site Data in this context (ie blocked by the cookie pref) definitely covers localStorage + IDB, might cover service-workers cache and maybe some of the other storage behind QuotaManager like asmjs-cache but does definitely not include appCache (aka offline cache).

The NOTE in 2701 needs some correction.

**Comment by Thorin-Oakenpants** [comment]
chucking this here (wanna do some more stuff)

```
/*** 2800: SHUTDOWN [SETUP]
     Blah blah
     "Offline Website Data" includes appCache (2730), localStorage (2710),
     Service Worker cache (2740), and QuotaManager (IndexedDB (2720), asm-cache) 
***/
```

Also fix 2701 that cookies control 1st party localStorage and IDB

**Comment by Thorin-Oakenpants** [comment]
How do we test service workers cache?

**Comment by earthlng** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
there are some links under "See also" at the bottom but I'd say fuck service workers! 
It sounds pretty fucking horrible:
- "Responding to resource requests from other origins" ?!?!
- "pre-fetching resources that the user is likely to need in the near future"

> Service workers only run over HTTPS, for security reasons. Having **modified network requests, wide open to man in the middle attacks would be really bad**. In Firefox, Service Worker APIs are also hidden and cannot be used when the user is in private browsing mode.

the fact that they're disabled in PB means that there's definitely something wrong with them, IMHO.

**Comment by Thorin-Oakenpants** [comment]
Oh I agree with "I'd say fuck service workers! It sounds pretty fucking horrible:", but I'll like to test them so our info is detailed (rather than just omit something - i.e the statement can still be true, just not paint the full picture)

In the 2701 [note] we use the wording `... access to 3rd party Web Storage, ...` etc. This is rather vague, everywhere else we're using the item names in 2700's header. Is `Web Storage` -> `localStorage` in this case?

**Comment by earthlng** [comment]
well there's a [ServiceWorkers cookbook](https://serviceworke.rs/) and a [Service Worker Demo](https://mdn.github.io/sw-test/). Testing the latter shows that SW also uses the storage folder. In my case it went under storage/default/. It also created a serviceworkers.txt file in the profile top directory. Cleaning OWD removed the subfolder and also cleaned the txt-file.
about:serviceworkers + about:debugging#workers might also be useful when testing SWs

**Comment by Thorin-Oakenpants** [comment]
I just struggling with how to indentify where the SW cache actually is or how its marked as SW cache. I mean, Youtube uses SW's to write data to IDB. But IDB data is not SW cache, is it, it's IDB.

Maybe `SW cache` means data stored using already existing storage types but set by a SW? It's a bit over my head TBH

**Comment by earthlng** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

> if you use AppCache and SW on a page, browsers that don’t support SW but do support AppCache will use that, and browsers that support both will ignore the AppCache and let SW take over.

> Note: **localStorage** works in a similar way to service worker cache, but it is synchronous, so **not allowed in service workers**.

> Note: **IndexedDB can be used inside a service worker for data storage if you require it**.

SW cache goes into a `cache` subfolder under storage/default/http.../ and IDB into `idb`. IDK if it always goes into `default` though or if it can also go into `permanent` or `temporary`.

**Comment by Thorin-Oakenpants** [comment]
PS: I think we should move to v60-beta before changing info on storage, site data (which I know is not in ESr52.x), sanitizing etc - because there have been way too many changes, and I am definitely not up to testing in ESR, just adds more complexity

Am happy to do a release and move to 60-beta now - just :+1: if you want

**Comment by earthlng** [comment]
about that, why don't we switch it around and mark it -alpha first and then -beta later for the pre-release used for the changelog? that would make a lot more sense IMHO

**Comment by Thorin-Oakenpants** [comment]
So...
- eg today: `59`-> `60-alpha` and start applying 59->60diffs etc
- eg just after stable lands: when all diffs done etc -> `60-beta` and do an `beta release`
    * no more `-alpha` releases
- weeks later
    * change to `60` and do a legacy-end-of-life release
    * immediately after that I then move to next alpha
   * maybe use `-final` as its only going to be live for 10 minutes

So we're always in a state of alpha or beta, which is technically true, we're always tweaking it. Did I follow that right?

`-alpha` applying new stuff, `-beta` ready for use after stable lands, `-final` for archived releases

**Comment by earthlng** [comment]
yes, more or less. Not necessarily "immediately after that I then move to next alpha" because it can wait until we do a first commit with some actual changes rather than just change the version. I wouldn't do -final either, just the version without -alpha or -beta is fine.

**Comment by Thorin-Oakenpants** [comment]
> Not necessarily "immediately after that I then move to next alpha" because it can wait until we do a first commit with some actual changes

That's problematic. The work-flow, reminder, trigger (for me) is doing the release, otherwise, days/weeks later with the next commit, it's too easy to forget.

IDK, this seems like overkill, adding a third version `build type`, one of which is effectively only used for a single point-in-time. Would you be disappointed in me if we just left it at status quo - I feel its much simpler to follow?

**Comment by Thorin-Oakenpants** [comment]
### SW cache test?

Test Site: https://www.youtube.com/watch?v=nfWlot6h_JM   #TayTay :heart:
 - I wait for the 15 sec advert to finish and then stop the vid after a few seconds of play so nothing else loads
 - to view SW info use `about:serviceworkers` (also if you want `about:debugging#workers` & `profile/serviceworkers.txt`)

Control Test
- 1st party cookies only, SW cache enabled
- close all tabs, scrub all data, load TayTay
- Site Data says 200 KB
  * open Storage Inspector on YT tab
  * yes: cookies, local storage, IDB
  * reload Site Data: now shows 119 KB (probably something expired)
- SW: one YT registered SW

Test A
- 1st party cookies only, disable SW cache `dom.caches.enabled`=`false`
- close all tabs, scrub all data, load TayTay
- Site Data says 176 KB
  * open Storage Inspector on YT tab
  * yes: cookies, local storage, IDB
  * reload Site Data: now shows 119 KB
- SW: one YT registered SW

Test B
- no cookies, SW cache enabled
- close all tabs, scrub all data, load TayTay
- Site Data says 0 bytes
  * open Storage Inspector on YT tab
  * no: cookies, local storage, IDB
  * reload Site Data: now shows 128 KB
  * 64 KB each for YT and tpc.googlesyndication
     * its in the IDB `storage/default` folders
- SW: nothing!!
- Conclusion: this must be a clear cut example of SW cache data?

Test C
- no cookies, disable SW cache
- close all tabs, scrub all data, load TayTay
- Site Data says 0 bytes
  * open Storage Inspector on YT tab
  * no: cookies, local storage, IDB
  * reload Site Data: now shows 0 bytes
- SW: nothing!!

Conclusion (so far):
- I used YT as a test because I knew it used SWs to load the comments section. Probably not the best test site, and don't forget sites can code for fallbacks to blockage. AFAICT, cookies have nothing to do with SW cache and it is solely controlled by `dom.caches.enabled` which makes sense. 

---

Slightly OT: `2711` doesn't belong in 2700s which is about web, not chrome - I think we should stick it with other 2600's extension stuff
```
/* 2711: clear localStorage and UUID when an extension is uninstalled
```

**Comment by Thorin-Oakenpants** [comment]
^^ Test B is weird: no registered SWs (can they unregister themselves?), but we got some data in IDB folders and we know IDB is blocked by the cookie block. I can't quite work it out. If its SW cache then there must be a SW? :headspining:

**Comment by earthlng** [comment]
> > Not necessarily "immediately after that I then move to next alpha" because it can wait until we do a first commit with some actual changes
> 
> That's problematic. The work-flow, reminder, trigger (for me) is doing the release, otherwise, days/weeks later with the next commit, it's too easy to forget.

I said "not necessarily". If you prefer to do it immediately afterwards that's fine too.

**Comment by Thorin-Oakenpants** [comment]
Yup. I get that :) I'd have to do it immediately or I could forget (and being out of sync would highly annoy me as a failure of the system/methodology). Even if I wait til the next commit, to me it's still just an extra version for a single state of the project: the one-off legacy archive. I get that it's more in line with version-naming conventions etc and software build environments.

While I appreciate that the user.js is always a work in progress, I don't like calling the version after the alpha release, a beta. Its not really a beta (to me), its ready to go for that version, we've finished that version's diffs. Every change after that is almost always just improvements (links, revamps) and version+1 diffs getting in ahead of time.

I can tell you really want this. Right? *if* I stuck with the status quo, would you be:
```
 [ ] mad
 [ ] really mad
 [ ] leave the project
 [ ] upset
 [ ] disappointed
 [ ] understanding
 [ ] forgiving
 [ ] keep talking me into it
 [ ] still love me
```
You can tick as many boxes as you like
