### ISSUE TITLE
INFO: Disabling dom.workers breaks Dashlane password manager

### ISSUE THREAD

**Issue by thunderbird-93** [ghacksuserjs/ghacks-user.js#394]
I hope this helps other folks.
- FF 59.0.2(64-bit) Windows 10
- Dashlane 5.9.3

**Comment by Thorin-Oakenpants** [comment]
Thanks. dom.workers.enabled is deprecated/removed in FF60 - see [1434934](https://bugzilla.mozilla.org/show_bug.cgi?id=1434934)
