### ISSUE TITLE
Firefox Features: What they do, and how to remove them

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#397]
I think this would be a good topic for the documentation.

Here's my first take at it, please add more details (and any corrections) to flush it out and refine it...

**Activity Stream	activity-stream@mozilla.org**
*Provides trending topics for the newpage tab*

**Application Update Service Helper	aushelper@mozilla.org**
*Something to do with updating FF - not sure effect of removing it*

**Firefox Screenshots	screenshots@mozilla.org**
*Integrated screenshots functionality - not sure if removing this removes screenshots from the devtools as well*

**Follow-on Search Telemetry	followonsearch@mozilla.com**
*No idea, but it's telemetry, so F it :)*

**Form Autofill	formautofill@mozilla.org**
*Obviously, something to do with autofilling forms... not sure what it really does*

**Photon onboarding	onboarding@mozilla.org**
*Not sure - perhaps just feature announcements*

**Pocket	firefox@getpocket.com**
*Bookmarks sharing functionality via Pocket - removing this removes ability to share bookmarks, but I'm not sure if they still get synced with FF accounts*

**Web Compat	webcompat@mozilla.org**
*I used to know what this did... then I learned something new, and that pushed it out of my brain :)*

IIRC, it's been reported that updating FF in any way will reinstall any of these that are missing.

**Comment by Thorin-Oakenpants** [comment]
This is all in the user.js - section 0500

See #171 and #172

**Comment by Atavic** [comment]
Pocket changed the Terms of Service on February 12, 2018

Now users can sign up with Google or Mail. Pocket seems a different entity from Mozilla:

> COPYRIGHT NOTICE

Read It Later, Inc. All rights reserved.

**Comment by KOLANICH** [comment]
https://github.com/mozilla/one-off-system-add-ons/tree/484be05f87cddeff40ed0797bc849ea1851bf70e/addons/telemetry-coverage-bug1487578
