### ISSUE TITLE
Right click > Save Link as returns error

### ISSUE THREAD

**Issue by theWalkingDuck** [ghacksuserjs/ghacks-user.js#398]
It seems I messed up something. 
 For some reason, `Right click > Save Link as` returns the following error:
```
      The download cannot be saved because an unknown error occurred.
      Please try again.
```
Does anybody have the same problem? Or know how to fix this?

FF 59.0.2 on Linux

**Comment by Thorin-Oakenpants** [comment]
Hey @theWalkingDuck ... I tested in a nilla 59.0.2 profile (I have a userChrome.css that cleaned up all my context menus). With the user.js applied as it is currently, I had no issues either drag n dropping the link to a folder, or right clicking and saving as. I'm on windows. The test was only for an URL.

I assume this is not a linux issue - eg you have tested it works fine in a new profile. And you tested with all extensions disabled, right?

Are you trying to save a pdf, mp3, jpg? Can you give us a working example?

**Comment by Thorin-Oakenpants** [comment]
Did some searching earlier, and it all seems to come down to file type associations, I think. Helps to know what you're trying to download. Here's some possible solution ideas
- https://support.mozilla.org/en-US/questions/1022568

I guess it may also depends on what you use for each application type - always open, ask etc. But I would assume "save as" should save to disk, not try to open (i.e why would file associations be important?).

Anyway, I would have a look at Options>General>Applications (which is controlled by mimeTypes.rdf in your root profile - you can close FF, rename it, restart FF and see what happens - this is a text based file btw, so feel free to edit it and have a play)

**Comment by Thorin-Oakenpants** [comment]
Also, the RFP pref could affect mimetypes/plugins - eg I know it causes Flash to not load/play (depends on the site's code)

**Comment by 2glops** [comment]
@theWalkingDuck 
Running Debian stable with FF 59.0.2 manually installed from Mozilla site

**Comment by theWalkingDuck** [comment]
I was experimenting with uMatrix and forgot to reset a rule.

That means `Right click > Save Link as` can be disabled 
either by removing the rule  `matrix-off: behind-the-scene true` 
or by setting it to **false**       `matrix-off: behind-the-scene false`

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info, added an FYI to make the solution stand out more. Still intrigued as to where/how this was happening. If it's behind the scene, then can I assume you were eg in the dashboard right clicking a hyperlink?

**Comment by Thorin-Oakenpants** [comment]
@theWalkingDuck  and others, also see `https://github.com/uBlockOrigin/uMatrix-issues/issues/5`

**Comment by earthlng** [comment]
FYI blocking requests with type `Other` in Request Control or similar will cause the same error message.

**Comment by Thorin-Oakenpants** [comment]
It's all magic to me (I have no idea how any of this stuff works), but here is my default uM
![um-almost-hard-as-fuck](https://user-images.githubusercontent.com/16656956/39407747-8a712c10-4bba-11e8-95c6-ab4280e855c8.png)

I've never had a problem saving anything (not that I have ever used the right context menu to do so). Guess I've never come across it myself.

**Comment by earthlng** [comment]
`other` in uM is probably not the same as the `Other` [ResourceType](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/ResourceType) available to webextensions that fe. Request Control uses.

**Comment by Thorin-Oakenpants** [comment]
^^ Good point. Not that I meant to imply it was the same. Thanks for clarifying
