### ISSUE TITLE
Addon Updates Now Require Restart

### ISSUE THREAD

**Issue by GuardianMajor** [ghacksuserjs/ghacks-user.js#399]
Hello everyone, I was wondering if anyone knew what setting has caused all addon updates to now require a restart, that wasn't the case before.

Let me elaborate slightly, when I updated an addon, say uBlock0 it would update in place and that's that, no need to restart. Now, everyone, including those that never required it are forcing a restart before they update.

I did some digging and anecdotal observation seems to suggest potentially this item:

> /* 0304: disable background update staging ***/
> user_pref("app.update.staging.enabled", false);

but the description of that seems to not imply it would affect the addons, so I am not entirely sure. The only reason I suspect it, is that now when the addon is requiring a restart, it is holding it in a folder called "staged" so I figured maybe relating to this.

Anyone else experience this and can shed some light? TIA.

**Comment by Thorin-Oakenpants** [comment]
What OS & FF version are you on. My understanding from memory is that that pref relates to Windows only, and if you don't set it as false, installed versions of FF still update the APP (not extensions) even if you disable 0301a+b (app checks and app updating).

**Comment by GuardianMajor** [comment]
@Thorin-Oakenpants My apologies, that was a boneheaded thing to leave out. I am on Firefox 56.02 x64 on Windows 10 Pro x64 (the last one is probably not relevant).

I'd be happy to provide you all that, give me a few to get to it and I will dump it for you and let you know. Thank you again, I have been at it for a while, another pair of eyes would be greatly appreciated before that dent on the wall becomes a complete hole engulfing my entire head 😁

**Comment by Thorin-Oakenpants** [comment]
Just making some notes:
- Context Search (0.6.4) = cannot find it - only [this](https://addons.mozilla.org/en-US/firefox/addon/contextual-search/) which is versions 3.x etc
- DownThemAll = legacy
- FlashGot Mass Downloader = legacy (requires restart)
- Greasemonkey 3.x = legacy
- MinimizeToTray revived = legacy (requires restart)
- [Screengrab](https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/) says it needs 55+ (you're on 52.x branch)
- Search By Image (by Google) (1.1.4) = legacy (requires restart)
- Search Engine Creator = legacy (requires restart)

4 of those legacy extensions, it says on the AMO page that they require a restart

**Comment by Thorin-Oakenpants** [comment]
given that ESR52.x branch is no longer supported in a few releases, I'm not sure if this worth troubleshooting

**Comment by GuardianMajor** [comment]
I am not on 52, I am on 56.0.2 not the ESR.

Yes, there are several legacy, I am not worried about them asking to restart, that's the nature of the beast. And since they are not updated to webext yet, there has not been any updates for them anyway.

I am speaking of the WebExt items, as stated, specifically an example of uBlock0 that never required a restart to update, but now does, behaving like legacy.

**Comment by Thorin-Oakenpants** [comment]
Sorry, was in flying hurry (was getting picked up and had a few minutes to kill) and for some reason had 52.x stuck in my head. The thing is, 56.0.2 is in the SAME boat as ESR re webextensons - it doesn't get patches at all. ESR will be moot at EOL (technically I'm not thinking about it after ESR60 lands, even though 52.x will exist for 2 more releases), .. 56.0.2 is **already** three versions past EOL.

I doubt it is anything to do with FF itself, 56 being the last legacy supported version. And it won't be legacy extensions. It'll most likely be something to do with how extensions declare they need a restart or not, and that has probably been dropped (and the default is a restart is needed?) - IDK. Not a developer. FF doesn't keep tabs on all the extensions, so it must be something **IN** the extension that tells FF.

Even if I was to find the exact cause, I bet no-one will fix it. 56 is not supported. Either deal with the fallout of being so far behind (yup, you tried to troubleshoot it, can't do much more than that), use legacy extensions only, or start moving to Quantum (yes, I know it sucks some extension functionality was lost, I'm guessing DTA is the main reason) - change your workflow, find different methods. You'll have to adapt anyway: i.e I would expect you to NOT still be using an insecure old FF version in 56 for much longer. Its already past it's use-by date and is missing some big security patches, the longer you leave it the worse it gets.

**Comment by earthlng** [comment]
> now require a restart, that wasn't the case before.

what does "now" mean? what has changed?

Maybe some of your addons aren't multi-process compatible or the latest version of uBlock Origin uses some features/permissions that your old and outdated Firefox doesn't support and that somehow triggers a restart prompt.

Using a mix of legacy + webextension addons in an outdated Firefox but with new-ish features like e10s and whatnot enabled, I'd say having to restart for addon updates seems like a minor inconvenience and probably the least of your problems.

**Comment by GuardianMajor** [comment]
@Thorin-Oakenpants No worries, I figures as much, I actually thought on reading your reply that I perhaps typed it wrong, and then I checked it again to make sure I had written it right.

Despite 56's status in the chain of release, it is fully webext capable and in fact has to be forced to accept legacy, although it does it without too much interference. It is not so deprecated in terms of parity with more recent releases to be obsolete or prone to wild issues.

Not really the case with the addons, as stated the legacy always require restart, they are not being updated anymore so no issue and webext don't require restart by their very architecture. And simply removing the user.js restores functionality to them, so I am 100% certain it is a change in the user.js just that I can't figure out which one (or ones combined) are the reason for it. As you can see, going through it ONE BY ONE would be an enormous undertaking and I was hoping that since you guys work with these settings that you would have insight as to which ones might be involved in introducing this behavior.

I don't need anyone to fix it, it is NOT a Firefox issue, as I stated, it has to do with a setting change, I just need to know which one. Proven by removing the user.js and everything works fine, so not something that needs fixing or requiring Mozilla to do anything about it, I think you are entirely focused on the wrong part of the issue as the cause. It is NOT a software issue and as a professional developer, I can guarantee it. I just need to figure out which setting being flipped is triggering the behavior, that's all.

@earthlng Please see my response above, that's not the case and the issue has nothing to do with the addons and are strictly related to some changed setting. I appreciate your other observations and thoughts but not related to the issue at hand and the setup is perfectly secure and functional (albeit with this inconvenience) which is minor at best and can be lived with, just would be nice to know so it can be noted for anyone else who might encounter it. Being able to say in the notes, btw this setting might cause this to happen would just make the list better and serves the userbase, unless that's not our goal here.

**Comment by Thorin-Oakenpants** [comment]
> Proven by removing the user.js and everything works fine

Well damn. Why didn't you say so earlier. I just re-read your first couple of posts and found no mention of this, or am I missing something again (just got up, first coffee)?

You say you suspect `app.update.staging.enabled` - did you test it?

[Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) at your end is probably the only way you'll find the culprit(s), not even sure I can replicate it since I only use portables and there are settings that would differ (which is why I mentions prefs.js). Using that halving method should mean you narrow it down somewhat in 4 or 5 tests

Thinking out loud, you may not even need to reset your test profile, as you can just keep installing an older extension version. ie
- add user.js section(s), restart
- update extension from eg v1.13 to 1.1.4, if no restart prompt then roll back to 1.13 and repeat
- install version 1.14

**Comment by GuardianMajor** [comment]
> Well damn. Why didn't you say so earlier. I just re-read your first couple of posts and found no mention of this, or am I missing something again (just got up, first coffee)?

While I didn't explicitly state that, it was fully implied as this is regarding a user.js and my observations on potential settings that might cause it, sorry I wasn't more explicit about it but did mention that it didn't happen before, now with user.js it happens, so it was implied, anyhow my apologies if I should have been more explicit about it. Sometimes when you are explicit like that it is taken as offensive to the intelligence of the professionals you are communicating with and I was approaching it a bit more matter of factly I thought, my apologies none the less.

> You say you suspect app.update.staging.enabled - did you test it?

Yes, of course, it would be foolish to not have done that. But it didn't resolve the issue, so that's why I mentioned, it might be a "collective" if you will of settings that trigger the behavior, not a single flip. Hence why I reached out, which I never do without extensive effort on my part so I have some context to share, as I hoped your exposure and investigation history of these settings would have that insights that I am lacking which would help figure it out. Usually when there is a combination effect that causes an issue it becomes more difficult to diagnose without some insight or brute force (but as you can imagine, when you have multiple settings involved, that brute force becomes quite mutated and elaborate for the myriad of combinations). I can generally speaking eliminate a great number of the settings as an issue because they are just not related enough to be a cause but the remaining items are still quite extensive.

I actually assumed that it might have been something that changed with the addon itself, but I have confirmed with the developer that it is not the case and they are not seeing it and since removing the user.js restores the proper behavior, they would be absolutely correct that it is not the addon versions again that the issue, but the settings. I need to narrow down the settings that need to be reverted to restore functionality and that was the whole point of this endeavor. Testing this behavior as you offered to do initially is quite easy actually.

1. Install Firefox 56.0.2
2. Install uBlock stable (aka say .24)
3. Go to the latest release and click on a newer version (make sure you pick the webext one)
4. It updates in place, voila, done.
5. Close the browser and load the user.js
6. Go back and try with the next release, it will require restart
7. Now here is when we need to figure out which setting is breaking this in place updating and restoring it back to staging (aka requiring restart)

Step 7 is what I need assistance with and was hoping your existing knowledge would accelerate the debugging if you will. I provided a complete snapshot of that profile simply because you asked and I wanted to be fully forthcoming, not to create distraction in what actually needs debugging, their existence is irrelevant to the issue, this much I am confident based on the initial discussion on top of this reply.

If you cannot or don't wish to assist on that, I understand and that's that and I will venture forward on my own but it would be helpful to leverage your understanding of the settings to help if the motivation is present. Thanks.

**Comment by earthlng** [comment]
It works fine with the latest ghacks-user.js. Must be something you added/changed yourself. 

> I can generally speaking eliminate a great number of the settings as an issue because they are just not related enough to be a cause but the remaining items are still quite extensive

I ran our prefsCleaner with our user.js against your user.js and this is what remains:

http://pasted.co/2190caa4/fullscreen.php?hash=c2f555e7b01abcf1641594809251ed86&toolbar=true&linenum=false

take your best shot :) gl

**Comment by Thorin-Oakenpants** [comment]
> Step 7 is what I need assistance with and was hoping your existing knowledge would accelerate the debugging if you will

Step 7 is using the "halving method" as outlined in the wiki troubleshooting. I can't make any better guesses than yourself, and like yourself, I know what it can't be, in large chucks, because they are not related in any way. The fastest and only way to do this is to go from 100% to 50% to 25% to 12.5% to 6.25% to 3.125% of the user js until you narrow it down. That's 5 tests to get down to a handful of items.

If I get time I will test it, assuming I can get *portable* firefox to request a restart

**Comment by Thorin-Oakenpants** [comment]
I just installed 56.0.2 portable, added uBlock 1.15.14 (that's about 5 versions old), added the user.js and enabled the deprecated ESR52.x section. Restarted and updated uBO and could not trigger a restart required. FF is running multiple processes. I don't see anything in the diffs from earthlng that jumps out at all (which is also why, for the 3rd time, I asked for the prefs.js). I would need to look at your legacy addons and see if any of those are blocking e10s, and maybe test with that. But right now I can't even replicate the problem, sorry.

**Comment by Thorin-Oakenpants** [comment]
56.0.2 portable: added ALL addons as per list
- uBlock Origin (1.15.14 - old version)
- Auto-Sort Bookmarks (3.2)
   * https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/
- Bookmark Dupes (5.7)
   * https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes/
- DownThemAll! (3.0.8)
   * https://addons.mozilla.org/en-US/firefox/addon/downthemall/
- Greasemonkey (3.17)
   * https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.17
- Screengrab! (2.11)
   * https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/

installed as well, (these require a restart anyway, but we're not updating these)
- Context Search (0.6.4)
   * https://addons.mozilla.org/en-US/firefox/addon/context-search/
- FlashGot (1.5.6.14)
   * https://addons.mozilla.org/en-US/firefox/addon/flashgot/
- MinimizeToTray revived (MinTrayR) (1.3.2)
   * https://addons.mozilla.org/en-US/firefox/addon/minimizetotray-revived/
- Search By Image (by Google) (1.1.4)
   * https://addons.mozilla.org/en-US/firefox/addon/search-by-image-by-google/
- Search Engine Creator (1.0.1)
   * https://addons.mozilla.org/en-US/firefox/addon/search-engine-creator/

![restart](https://user-images.githubusercontent.com/16656956/38839032-55fb7036-41c8-11e8-9321-5c6ee1ba7f4a.png)

- :exclamation: Firefox running a single process - so no e10s
- :exclamation: ADDED the entire list of prefs in [GuardianMajor's list](https://gist.github.com/GuardianMajor/7bc33d02543166cbc3e2cf61be126808) to the end of the user.js, i.e on top of the master user.js here at github with the deprecated ESR52.x section enabled.
- saved as my master test profile. This is as close as I can get (with a portable) without further info.
- checked for updates, updated ONLY uBO (greasemonkey update was ignored)
- cannot replicate restart required

**Comment by GuardianMajor** [comment]
I did not see a request for the prefs.js file, if you made the request, I would have provided it. Certainly if you had asked three times. I appreciate all the effort and thanks @earthlng but yes the settings are not a 100% parity with your user.js but contain a lot of overlap. @Thorin-Oakenpants I appreciate that you created the profile and yes I have been ignoring the GM updates until I can port properly all the existing scripts to the new structure before updating so that I can minimize the down time of debugging but will be finishing that by the end of the week.

Since my last post I had already refactored my user.js sections so that I can easier brute force my way through it. I had to do 3 prefs.js deletes along the way (apparently some settings from user.js DO go into permanent prefs.js, didn't realize that could happen) and finally narrowed it down and figured out which SINGLE item was causing it. And it was NOT one of the ones on your user.js, so that's good news for you guys at least but rather the settings we had agreed on with Mozilla when working on e10s involving force disable of accessibility and force enable of e10s. All of them work fine but it seems due to a session regression (aka disabling sessionstore and such), the setting:

> user_pref("browser.tabs.remote.force-enable", true);

forces this behavior and causes the problem. So I have since commented that out and all is fine now. Everything has returned back to normal and updating as usual. I just loaded the latest beta (25rc3) and it installed in place like a champ, no more restart. So thank you again, I guess I was only two days away from figuring it out when I reached out. It's hard to know sometimes, how long you keep banging your head before asking for help, I guess in this case, I know the answer.

**Comment by Thorin-Oakenpants** [comment]
PS: I'm not sure what method you used for testing, but seriously, read the wiki troubleshooting page. It does not matter WHAT your user.js is made up of or in what order - it is very easy and quick to keep HALVING down to a tiny number or a single section of prefs. I already pointed out that five tests will get you down to 3% of the items.

There is not need to mess around with prefs.js and deleting that etc, which has consequences because that holds far more than just user_set prefs or items from user.js, it contains a bunch of FF internal shit. All you have to do is have your profile root dir open, and use copy/paste/rename between tests - takes all of 3 seconds to reset a profile or copy it - seriously, read the wiki page :)

**Comment by GuardianMajor** [comment]
> browser.tabs.remote.force-enable may not be in our user.js, BUT... I applied it as true in my test profile, because I appended all your stuff to the end... and I could not replicate your issue

That's odd, as removing that fixes my problem, and putting it back, kills it. I did have to do an extra step, which is to physically remove it from the prefs.js but given what you said next, that would make sense as it would have been left over.

> Every pref that is not commented out in the user.js goes into your prefs.js, even if it is the default value - they show as "modified" or "user_set" in about:config (they changed the wording several releases ago) is in prefs.js.

Did they change the behavior on this? According the documentation in the past, the user.js is combined with prefs.js and loaded into the browser and then the prefs.js is restored using the prefs-1.js, I guess my info is outdated, that would explain why some of them seem to persist in the actual prefs.js but that defeats the purpose of the user.js as it would mean that after the first load it becomes unnecessary as it would now be in the prefs.js, right? Or am I misreading this? I was under the impression over the years that user.js doesn't modify the prefs.js file for anything it contains simply overrides what is in prefs.js - good to know that's not the case, so anything I remove from the user.js, I need to sanitize out of the prefs.js now, great.

Oh I read the gist request as my user.js file, not the prefs.js file, that's why I provided that. I guess I missed the context of the reference to the prefs.js sorry about that. Also, I debugged NOT on my primary profile, I created one just to install the test addon in question (uBlock) and then ran the user.js modified in chunks until I hit the restart issue, then I knew which block it was in, then it was just a matter of chunking those I can see which one triggered it and that was the one that consistently triggered it. So then I put the modified user.js file in my primary and still encountered the issue, until I removed the same line from the prefs.js and then reloaded and it was fine now. Hence the reference to the realization that they were sticking behind.

**Comment by Thorin-Oakenpants** [comment]
>  I did have to do an extra step, which is to physically remove it from the prefs.js but given what you said next, that would make sense as it would have been left over.

Indeed - read this - https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview (but note some behavior changes re syntax errors in FF60+). AFAIK this is how it has always worked, for me, at least the last 5 years

**Comment by Thorin-Oakenpants** [comment]
https://www.reddit.com/r/firefox/comments/8dmas3/why_does_updating_webextensions_sometimes_require/

I wonder if they OP will reveal what FF version he is on. Not saying it's the same issue, but worth watching for info / confirmation

**Comment by Thorin-Oakenpants** [comment]
^^ @gorhill I now see your issue `https://github.com/gorhill/uBlock/issues/3637` since you commented. As you can see @GuardianMajor found it was some combination of 56 + web.ext + non e10s + `browser.tabs.remote.force-enable`=>`true`

Although there may be more to it. I could not reproduce, but I didn't exactly have every setting or the same setup.

**Comment by GuardianMajor** [comment]
@gorhill I tried updating that to reflect my findings but the new restrictions makes it impossible for me to comment on my own ticket, so I have been trying to find a way to reach outside the issue tracker. I guess this will make that moot now.

**Comment by overdodactyl** [comment]
Just an FYI, there is now this community maintained issue tracker for uBO:

https://github.com/uBlockOrigin/uBlock-issues

and similarly for uMatrix:

https://github.com/uBlockOrigin/uMatrix-issues

**Comment by GuardianMajor** [comment]
@overdodactyl  I am fully aware of that but it is no help for updating an existing issue that was still open and needed and update. I am not going to open a fresh issue just to update an existing issue, that make sense?

**Comment by Thorin-Oakenpants** [comment]
And still no one at reddit has said anything. Maybe they don't know how to click the link in gorhill's comment on reddit, scroll to the bottom, and take the link to here

**Comment by GuardianMajor** [comment]
@overdodactyl I know what you meant, I was just explaining why I felt stuck, since I didn't want to open a new issue for an existing one. Future issues/problems are their own merit.

@gorhill Yes, Raymond, thank you. Best of the worst options I guess, just wish I could have updated it directly without cross repository-jacking it 😞 I had told you that I will dig into it and figure out and when I reached out here and resolved it, came back to report it but alas couldn't. I was going to reach out to you via other channels but @Thorin-Oakenpants was kind enough to link them, so I guess that's as good as we can get. Not the cleanest resolve, but it is what it is and will make due.
