### ISSUE TITLE
wiki: clear window.opener [solved: see top of OP]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#401]
Edit
- Legacy GM & script: no issues
- Web Extensions & Script: disable it and use [window.opener be gone](https://github.com/earthlng/testpages/raw/master/windowopener_be_gone-1.0-an%2Bfx.xpi)
   * this is the same script but injected by an extension to solve the issues

---
OP as follows

issue to deal with `clear window.opener`.
[quick wiki link](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts)
[quick test link](https://mathiasbynens.github.io/rel-noopener/)

note:
- when I say 57+ I am using that as the marker since that is based on our extensions recommendations (we recommend VM in 57+) and is a clean line in the sand and legacy extensions vs web ext. Tests were only done on 59.0.2 (VM is 2.9.1)

summary:
- all three scripts work in legacy GM and ESR52.x which we still support
- in web ext GM and 57+, all three scripts fail (due to document-start?)
- in web ext VM and 57+, only `clear window.opener` "fails"
   * earthlng tested webext GM (correct me if wrong)
- the script [noopener_by_default](https://github.com/jaredsohn/noopener_by_default) in VM and 57+ works
- edit: diff in the two scripts: noopener_by_default is heavy handed and modifies the original/source page, while clear window.opener modifies the new pages
- edit: diffs in how web extensions GM+VM handle document-start
- edit: GM almost has a document start fix in place (different to VM)

conclusion:
- `clear window.opener` if modified might work in VM (see the new script), but see diffs in what the script actually does.

done:
- wiki: I have already edited the top few lines of the wiki to clearly say that the scripts will not work with the web ext version of GM.

to do:
- ~~decide if earthlng wishes to provide a second script for 57+~~
- clearly label the current script as legacy extension only
- otherwise point to the new script **OR** point to an extension
- wait for GM to land the document-start fix and switch to GM
- talk to VM and see what can be done

Awaiting earthlng's decision, insight, knowledge

**Comment by Thorin-Oakenpants** [comment]
earthlng said:

apparently, without looking at the code, just based on your test results, VM uses a different way to inject the scripts and that's why the user-scripts work in their current form. However that method comes with a different set of problems. For example I'm pretty sure the window.opener script doesn't work because the demo page is hosted on a domain with strict CSP rules. That means you can't rely on your user-scripts to work on potentially malicious pages, at all.
I can think of at least 1 other problem but won't bother you with the details.

re: the 2 different scripts: noopener_by_default works by modifying the links on the original page, while "my" user-script works on the "new" page.

noopener_by_default has several issues (1) it's less efficient because it modifies all links targeting a new tab, (2) can easily be tricked to not modify a malicious link, (3) and maybe most importantly, it doesn't clear window.opener when a page uses window.open(). There might be other problems as well, fe. a form can also have target=_blank and it's possible that a page opened that way could also have access to window.opener. If it does then noopener_by_default does nothing against that, either. It can also break a page because adding rel=noopener to a link apparently opens the page without the referer header.
The script in the wiki has none of these problems because it works on the "new" page.

**Comment by Thorin-Oakenpants** [comment]
> VM uses a different way to inject the scripts and that's why the user-scripts work in their current form. However that method comes with a different set of problems.

does that mean the other 2 scripts also suffer from the same issue? Or are they OK because they are not modifying content? A bit over my head.

**Comment by Thorin-Oakenpants** [comment]
> The script in the wiki has none of these problems because it works on the "new" page

So it works then? i.e in VM on 57+? We just get a miscellaneous result because the test expected something else?

**Comment by earthlng** [comment]
> does that mean the other 2 scripts also suffer from the same issue?

you tell me. You're the author of `Conceal history.length`, aren't you? :trollface: 

> - the script [About rel=noopener](https://mathiasbynens.github.io/rel-noopener/) in VM and 57+ works

wrong link?

**Comment by Thorin-Oakenpants** [comment]
> You're the author of Conceal history.length, aren't you? :trollface: 

F no. I plagiarized it, did a CHEF-KOCH. Nah, no idea how I wrote that, I think I just looked at some existing scripts/examples on how to read and return a property - I think I just modifed Conceal window.name

**Comment by Thorin-Oakenpants** [comment]
Question: can an extension overcome these limitations: eg strict CSP, run-at doc-start, modifying every link

https://addons.mozilla.org/en-US/firefox/addon/dont-touch-my-tabs/?src=search - looks like it modifies every link

**Comment by crssi** [comment]
^^ Nah... not every link.

Description says this (pay attention to bolded text):
> Prevent tabs opened by a hyperlink from hijacking the previous tab by adding the rel=noopener attribute to all hyperlinks (**excluding same-domain hyperlinks**).

So somehow interfering when same-domain is undisired also for author.
Thats something I was asking at https://github.com/ghacksuserjs/ghacks-user.js/issues/75#issuecomment-382023964 but being ignored/forgoten. 

Cheers

**Comment by Thorin-Oakenpants** [comment]
> but being ignored/forgoten.

You're always on my mind .. so at least one person still loves you :) PS: I skipped that because I thought earthlng had answered it

**Comment by Thorin-Oakenpants** [comment]
I moved GM in the wiki from legacy to non-legacy, it's had three+ releases to mature.

I'm clearly not a developer (did you guess?), and would like to ask @gera2ld about this, but not waste his time. eg: bypassing strict CSP, how it handles run-at document-start (excuse my ignorance if terms are incorrect)

I don't wish to rehash what already exists ( https://github.com/violentmonkey/violentmonkey/search?utf8=✓&q=document-start&type=Issues = 9 issues with `document-start`) but it's all over my head :sob: and I can't seem to find a dedicated topic on it.

@gera2ld : our wiki has three scripts of which [this one](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts#small_orange_diamond-clear-windowopener) `Clear window.opener` doesn't seem to work in VM (FF59+, VM 2.9.1). Can you give us any heads up or link to an existing topic on this document-start business? TIA

Edit: I see 2.9.2 is out but have not updated yet

**Comment by Thorin-Oakenpants** [comment]
Possible relevant bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1332273

**Comment by Thorin-Oakenpants** [comment]
> I moved GM in the wiki from legacy to non-legacy, it's had three+ releases to mature.

Actually, I moved it back. Doesn't seem to me like any progress on document-start. They no longer have a privacy policy, and the reviews on AMO are not that great. Maybe when it can run our scripts we can re-look at it.

**Comment by Thorin-Oakenpants** [comment]
@earthlng Is an extension a feasible solution? i.e none of the document-start, strict CSP hindrances - and one that works the way you described, by modifying the linked page, not the source page.

**Comment by earthlng** [comment]
Probably.

https://anonfile.com/ef3fm5eab4/windowopener_be_gone-1.0-an_fx.xpi

Very basic extension that injects the user-script listed in the wiki. No whitelist support or anything like that. Not listed on AMO because I don't want to deal with people asking for new features or bitching about how it breaks some sites. It is what it is, take it or leave it. I might improve it when I move away from ESR but hopefully until then GM will be able to correctly run scripts like this again.
The extension also works on ESR52 but it's probably more convenient to use the user-script with legacy GM for an easy way to exclude certain sites.

FYI I would not recommend to run the other 2 scripts with VM either, because if someone would care to look they could easily get your real history.length and window.name.

@crssi it's only my opinion but yes I think it's possible that an attacker can abuse window.opener on same-domain as well.

**Comment by Thorin-Oakenpants** [comment]
I'll give it a test. FWIW I think you should store the xpi here: https://github.com/earthlng/testpages with the other two

conceal history.length was always about "lying" about the array size, I always assumed anyone could/would try to fill bigger arrays. I don't know enough about the property(s) - eg get history.length(item5.name) or something silly

How does windows.name not protect windows.name = it's literally right there in the code
```js
return '';
```

**Comment by earthlng** [comment]
go to http://browserspy.dk/document.php, open a couple of links from the navbar on the left in the same tab and then go back to Document. It will say `Number of pages visited in History = 2`. Now press Ctrl+Shift+K and type in `_history.length` and Enter. What do you get? The same is true for window.name.

With legacy GM in ESR for example, you will get `ReferenceError: _history is not defined` because there's a separation between contentscripts injected by extensions and the site's own JS. That's most likely not the case with the way VM injects the scripts. Without separation, scripts have to be written in a very special way for this NOT to be a problem. Not only can it reveal stuff that it shouldn't, it can also overwrite unrelated functions/variables etc set by the site or vice versa. In general and unless someone understands the In's and Out's of this, I'd very much recommend against using VM for *any* script.

**Comment by Thorin-Oakenpants** [comment]
the xpi - works on the test site perfectly, thank you. Should we link to it in the wiki (with your disclaimers)? eg add it to the extensions wiki page?

What should we do with the scripts wiki page? Red exclamation and disclaimer at the top or something. Don't wish to give people a false sense of privacy

**Comment by Thorin-Oakenpants** [comment]
> Now press Ctrl+Shift+K and type in _history.length and Enter. What do you get?

FF59.0.2 + VM - I get `ReferenceError: _history is not defined`

**Comment by earthlng** [comment]
Oh okay, nvm then. I'll edit/remove my comments

**Comment by Thorin-Oakenpants** [comment]
Got to say I like the icon
![shady](https://user-images.githubusercontent.com/16656956/39407955-3d2043e8-4bbe-11e8-8d1d-c9c098bb95e1.png)

You know way more than I do re VM/scripts etc - your comments may well be true with other scripts. But ours are OK by the sounds of it

Edit my comments as well if you need to

**Comment by earthlng** [comment]
> Should we link to it in the wiki (with your disclaimers)? eg add it to the extensions wiki page?

up to you

**Comment by earthlng** [comment]
> FWIW I think you should store the xpi here: https://github.com/earthlng/testpages with the other two

download link: https://github.com/earthlng/testpages/raw/master/windowopener_be_gone-1.0-an%2Bfx.xpi

**Comment by Thorin-Oakenpants** [comment]
* [x] added to wiki extensions (just the file and link back to this issue)
* [x] wiki scripts, `conceal window.opener` mentioned at the top in that slight mess of explanations, AND mentioned just above the script itself

Feel free to fix anything I did to the two wiki pages

**Comment by earthlng** [comment]
> whereas your modifies the new page (which is better? right?).

it clears window.opener whenever it is not already null. It's better in the sense that it doesn't matter how window.opener was set. There are several tags in HTML that can use `target=_blank` of which at least `<a>` and `<area>` support the `rel=noopener` attribute, according to [mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types). But there might be others besides these 2 that could also result in window.opener being set, like form or whatnot, IDK. And `window.open()` also sets window.opener. `don't touch my tabs` only modifies `<a>` tags.

> `window.opener be gone` covers same-domain

yes

**Comment by Thorin-Oakenpants** [comment]
^^ awesome. You're so patient with my for-dummies mentality. All I'm hearing (and I do understand most of it) is that yours is a superior solution, that's good enough for me. I trust your expertise

**Comment by rusty-snake** [comment]
FYI: A hardened TC can be a replacement for `window.opener be gone`.
