### ISSUE TITLE
scripts to follow up on

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#403]
from @ZIEXED

[Disable AutofillPhishing (By AdguardTeam)](https://github.com/AdguardTeam/Userscripts/blob/master/disableAutofillPhishing/disable-autofill-phishing.user.js)
[Bypass t.co redirection from Twitter external links](https://github.com/kkren/remove_t.co/blob/master/removetco.user.js)

**Comment by Thorin-Oakenpants** [comment]
Not sure if the redirection fits, does it? (security/rpivacy/anonymity). What exactly does a t.co link do (never understood these url shorteners) - do these involve third parties?

AutofillPhishing sounds OK.

Should I add a section in the wiki page for "Others: and just link to them?

**Comment by earthlng** [comment]
the user.js already fully disables any kind of autofill, no? why would we need that script?

**Comment by Thorin-Oakenpants** [comment]
Its specifically for hidden forms (from memory). So if users want to enable autofill for whatever reason, this is an extra layer of protection. IDK. I'd rather focus on the user.js + extensions - don't want to write a book. BUT, scripts are part of extension capabilities (but look where that's getting us what with doc-start and lack of functionality in web extension APIs).

**Comment by earthlng** [comment]
Fair enough. "Others" and just links with a short description sounds good then. Should probably also mention that autofill is disabled by default by the user.js.

**Comment by earthlng** [comment]
> Not sure if the redirection fits, does it?

they won't know which links you clicked, at least when you visit Twitter with JS blocked. It just sucks that that script loads JQuery. Any volunteers to rewrite it in native JS ??

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts#small_orange_diamond-other-scripts

^^ looks a bit naff, Feel free to clean it up
