### ISSUE TITLE
discussion: add extensions.webextPermissionPrompts

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#41]
`extensions.webextPermissionPrompts` : should we enforce this -> true
https://bugzilla.mozilla.org/show_bug.cgi?id=1308292

https://wiki.mozilla.org/WebExtensions/Permissions
Aiming for FF53

What is the default (looking at [DXR](https://dxr.mozilla.org/mozilla-central/search?q=extensions.webextPermissionPrompts&redirect=false) is it false ATM? When does it land? Is it hidden?

I think this is important to enforce as true, as it will prompt users to review the permissions

**Comment by earthlng** [comment]
According to Martin's [article](http://www.ghacks.net/2017/03/06/firefoxs-new-webextensions-permission-system/) you need at least FF53 for it to do something

**Comment by earthlng** [comment]
Also lots of open `depends on` bugs [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1308292) - let's wait with this one, we have enough time and it'll likely show up in a future diff anyway and we can deal with it then.

**Comment by Roman-Nopantski** [comment]
yup, aiming for 53 - moz link added to the first post. We can revisit this when we see the diffs 52-53 (53 lands 2017-04-18). Closing this, as we have a fallback for re-notification
