### ISSUE TITLE
uBO element picker & Stylus

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#412]
@gorhill just so he's aware (if not already)

@overdodactyl This is weird man. Help me troubleshoot this sucker.

First of all, it's not like I use the element picker every day, but I think has only been happening for the last few days. It's not Stylus (which had an update to 1.18 a few days ago, but I rolled back to 1.17 which is April 13 and it's still there) - see https://addons.mozilla.org/en-US/firefox/addon/styl-us/versions/

Secondly, it's not all scripts (more on that). Are you seeing this with any of your copious web site styles? (I know you're a style control freak, so you're bound to have a few hundred loaded!)

OT: how do you make those little browser window gif files? Cuz pasting 4 little screenshots sucks

STR:
- Install Stylus
- Add the Github Dark userstyle
   * https://github.com/StylishThemes/GitHub-Dark (manually)
   * https://userstyles.org/styles/37035/github-dark (userstyles)
- install uBO (I am on stable 1.16.2)
- load a github page
![pic1](https://user-images.githubusercontent.com/16656956/39411405-fc69f962-4bf8-11e8-95b6-1391f2e75bd2.png)
- block an element (web content vanishes as per pic, colors hard to read (as per pic), eg especially if you move the cursor off the dialog box, it gets like totally dark and 100% unreadable))
![pic2](https://user-images.githubusercontent.com/16656956/39411410-0e19a36a-4bf9-11e8-928c-874e7ff92a59.png)
- select `pick` and move your selector around (you can't see what you're selecting)
![pic3](https://user-images.githubusercontent.com/16656956/39411424-4437e862-4bf9-11e8-8423-ad32d4690b48.png)
- no need to escape anything, just toggle the user theme off from the stylus toolbar icon
![pic4](https://user-images.githubusercontent.com/16656956/39411431-63787066-4bf9-11e8-8364-cf56ce16b88f.png)

**Comment by Thorin-Oakenpants** [comment]
Like I said it's not every user style. Some are mine, some are from userstyles

for example: this one for https://www.schneier.com/ causes the problem
```
/*COLORS
BG DARK   #444444 BG DARKER #333333
DARK BARS #1E1E1E
OFF WHITE #E1E1E1
OFF BLACK #0F0F0F
GREEN     #96EB41  solid rgb(150, 235, 65)
PALE GREEN #A4CF79
BLUE      #61B6E0  solid rgb(97, 182, 224)
ORANGE    #EB9641  solid rgb(235, 150, 65)
PALE ORG  #D7CFA5
PINK      #FF7FFF  solid rgb(255, 127, 255)
RED-BROWN: #C23232
*/

/*font size*/
body {font-size: 13px !important;}

/*background*/
body {background-color: #222222 !important;}
#header {background: #222222 !important; height: 65px !important;}
#main {background-color: #111111 !important;; border: 0px !important; color: #C4C4C4 !important;}
#content {background-color: #111111 !important; color: #C4C4C4 !important;}
.sidebar {background-color: #1A1A1A !important}
input, textarea  {background-color: #333333 !important; color: #96EB41 !important;}
div.official {background-color: #343434 !important}

/*nav*/
.nav li.current a, nav li.current a:visited {background-color: #C23232 !important;}

/*borders*/
div.sidesection {border: none !important;}

/*position*/
h1 {margin-top: 0px !important;}
    
/*colors*/
#header h1 a:link, #header h1 a:visited {color: #E1E1E1 !important;}
h1 a {color: #A4CF79 !important;}
div article a {color: #C23232 !important;}
a.earlier, a.later {color: #EB9641 !important;}
p.commentcredit a {color: #EB9641 !important; font-weight: normal !important; font-size: 11px !important;}
div.sidesection h3, div.sidesection h4 {background-color: #000000 !important; color: #A4CF79 !important;}
h2, h3#comments, .entry a {color: #96EB41 !important}
span.commenter {color: #61B6E0 !important;}
div#search-widget.sidesection p.small em a {color: #C23232 !important;}
ul.top-tags li a {color: #D7CFA5 !important;}  
div.sidesection ul li a  {color: #D7CFA5 !important; text-decoration: none !important;}
div.sidesection p a {color: #C23232 !important;}
```

but this one for https://torrentfreak.com/  doesn't
```
/*COLORS
BG DARK   #444444
BG DARKER #333333
DARK BARS #1E1E1E
OFF WHITE #E1E1E1
OFF BLACK #0F0F0F
GREEN     #96EB41  solid rgb(150, 235, 65)
PALE GREE #A4CF79
BLUE      #61B6E0  solid rgb(97, 182, 224)
ORANGE    #EB9641  solid rgb(235, 150, 65)
PALE ORG  #D7CFA5
PINK      #FF7FFF  solid rgb(255, 127, 255)
*/

/*remove some stuff*/
    aside.widg.widget_text, .flag-featured, .flag-dark, .entry-share.floating {display: none !important;}
   
/*remove spaces & big gaps etc*/
    div#feature {height: 5px !important;}
    main#main {margin: -1px 310px 0px 82px !important; min-height: 1000px !important;}
    div.entry-image {height: 40px !important;}
    .entry-kilo .entry-title-wrapper, .entry-micro .entry-title-wrapper, .entry-nano .entry-title-wrapper {padding: 0px !important;}
    .entry-kilo .entry-title, .entry-micro .entry-title, .entry-nano .entry-title {min-height: 5px !important;}
    .entry-title-wrapper {margin: -4.2em 0px 0px 0px !important;}
    .entry-meta {margin: 0.5em 0px -0.5em !important;}
    div.entry-content {padding-left: 0px !important;}
    .stats {padding: 5px 0px 5px !important;}
    p.alignfull  {padding-left: 100px !important;}
    
/*shrink text*/
    .entry-kilo .entry-title, .entry-micro .entry-title, .entry-nano .entry-title {font-size: 1em !important;}
    h1.entry-title {font-size: 1.5em !important; padding-top: 10px !important;}
    p.entry-lead {font-size: 1em !important; line-height: 1.2em !important;}
    .stats-number {font-size: 1em !important;}
    html, body {line-height: 1.1em !important;}
    .entry, .hentry {font-weight: normal !important;}
    div.entry-content {font-size: 14px !important; line-height: 1.2em !important;}
    
/*purpose: to darken background etc*/
    body.home.blog, div#feature {background: #141414 !important;}
    div#feature-background, div.entry-image, body {background-image: none !important;}
    main#main, .entry-title, .entry-title-wrapper, #wrap-main, #wrap-page {background: #333333 !important; color: #E1E1E1 !important;}
    #sidebar {background: #333333 !important;}
    .entry, .hentry, .pbx {border-right: 33px solid #333333 !important;}
    table.css > tbody tr:nth-child(2n) { background: none repeat scroll 0% 0% #444444;}
    table.css > thead th, table.css > tfoot td { background: none repeat scroll 0% 0% #222222; }

/*colors*/
    h1.widg-title, h1.entry-title {color: #96EB41 !important;}
    p.entry-lead {color: #EB9641 !important;}
    div.entry-content p a {color: #61B6E0 !important;}
    div.entry-content p strong {color: #D7CFA5 !important;}
    div.alignfull h3 p span {color: #96EB41 !important;}
    a, a:hover { color: #61B6E0 !important;}

/*disqus*/
    .pbx-alt {background: #333333 !important;}
```

Both of those are my scripts, but F'd if I know what's so special about them that one works and one doesn't re the element picker. 

For another example of a script(s) that *doesn't* cause a problem, on IMDB I use two scripts, they are
- https://userstyles.org/styles/26913/darker-imdb (Dark IMDB)
- https://userstyles.org/styles/98447/imdb-com-nightmode (IMDB.com nightmode)
- in that order I think

No idea if you can work out from all that what the cause is.

**Comment by overdodactyl** [comment]
I've noticed this before, and I think it's been a problem for a while (at least on GitHub using the GitHub Dark theme).  I didn't notice it on my bugzilla one, I'll get it fixed.  The issue boils down to the user style overriding uBO's html page.  The solution is to just increase specificity.  For my style, that means changing 

```css
body {
    background: url(.....)
}
```

to 

```css
html:not(#ublock0-epicker) body {
    background: url(.....)
}
```

When I get the chance I'll take a littler closer look at the GitHub one and see if I can submit a PR for it.

**Comment by Thorin-Oakenpants** [comment]
Well that kinda sucks (not knocking anyone here), but surely it is better to fix the ONE source causing the issue than to edit tens of thousands of user styles

Pretty damn sure it's only been happening for a short while - maybe gorhill could not wrap the picker in a uniquely named element - I'm confused

**Comment by gorhill** [comment]
Looking at uBO's code, I would say it's a uBO issue. I do use user stylesheets for the iframe containing the picker, but I use a plain style tag for the inside of the frame, which is where the issue lies. Solution for uBO is to use user stylesheets for the inside of the frame, but not something trivial to fix, the tricky part is to find out the frame id to use to insert these user stylesheets. I will need to experiment.

**Comment by gorhill** [comment]
> than to edit tens of thousands of user styles

Another approach meanwhile could be to use a user style specific to uBO's element picker rather than trying to create exceptions for all other styles. What about:

    html#ublock0-epicker body {
        background: transparent !important;
    }

**Comment by Thorin-Oakenpants** [comment]
Hah.. I just noticed in those 4 pics, that the uBlock counter increases by 2 each time (page is static, no reloading) .. start 8, load picker 11, flick style off 13 ... don't worry about it, it's just an observation

**Comment by Thorin-Oakenpants** [comment]
> Another approach meanwhile could be to use a user style specific to uBO's element picker

But that's already in there
![llamas](https://user-images.githubusercontent.com/16656956/39676049-2e203d9a-5153-11e8-90aa-515a951ed300.png)

You'd have to make sure that the uBO element picker style is applied last

**Comment by gorhill** [comment]
> But that's already in there

Yes, sorry, I made the mistake of speculating what the issue was instead of investigating it following your repro steps -- I should know better.

I had assumed Stylish was using user stylesheets to implement user styles -- apparently that is not the case. This means that the injected styles were overriding uBO's own styles somehow. Turns out I was not using the `ublock0-epicker` id in CSS rules to ensure very high specificity, and thus the styles injected by Stylish were overriding uBO's ones.

Will fix asap.

**Comment by Thorin-Oakenpants** [comment]
Lemme know when it's verified fixed in the next rc and I'll close this

**Comment by Thorin-Oakenpants** [comment]
PS: :kiss:

**Comment by Thorin-Oakenpants** [comment]
confirmed fixed
![fixed](https://user-images.githubusercontent.com/16656956/39677209-8ae09ada-5166-11e8-953e-4cecce75a6db.png)
