### ISSUE TITLE
Preferences UI Issues etc: [solved browser.sessionhistory.max_entries > 0 as per instructions]

### ISSUE THREAD

**Issue by Cinik** [ghacksuserjs/ghacks-user.js#413]
I am on Linux so this may be a short conversation. And before I forget wana say I really appreciate the work you all do here.

Search, Privacy & Security and Firefox Account tabs will not open but the url does change accordingly. Same situation in about:debugging.

Drop down menu for Windscribe VPN displays only white with outline.

Page reload does not work however stop does.

Also having a problem with my windows tablet freezing while using the same user.js

Was going to try halving method next but thought this may save some time, been at it already a couple hours. I removed section numbers, notes and any preferences (except max_tabs_undo) that would not be changed. This was tested on new profiles so problem is in there somewhere.

[user.txt](https://github.com/ghacksuserjs/ghacks-user.js/files/1966280/user.txt)

**Comment by Thorin-Oakenpants** [comment]
FF version?

**Comment by Thorin-Oakenpants** [comment]
Dig some more quick digging - lets just stick to the linux issues
- first, make sure all extensions are disabled and restart
- try enabling/disabling hardware acceleration (make sure to comment them out in the user.js because you will need to restart FF to take affect)
- make sure it's not a theme - just use the default(s)

**Comment by Cinik** [comment]
Windows 10 tab 1703 59.0.2
On linux I started this with 59.0.2. Today I went ahead an updated to 59.0.3 moving old profile to flash drive an let Firefox create a new profile. Did not change any settings or add any addons. With the new profile the problems listed did not exist until I launched Firefox again with the user.js that you see attached to first post.
Hardware acceleration was one of the first settings I checked, and yes it was disabled in about config.
E10s aswell showed disabled.

**Comment by earthlng** [comment]
> Drop down menu for Windscribe VPN displays only white with outline.

that maybe because that addon might use not ideal storage API and you delete that with `user_pref("privacy.clearOnShutdown.cookies", true);`

**Comment by Thorin-Oakenpants** [comment]
I think fixing the e10s might solve everything (this was one reason I had missing graphics one time). The e10s compatibility system addon was dropped in 59.

VPN is a separate issue - we had one before about HoxyVPN and it hated `security.OCSP.require` see #295 (not saying this is the case here, but worth checking)

**Comment by Thorin-Oakenpants** [comment]
Assuming you can scroll about prefs > general .. what does it say for
1. vanilla profile
2. vanilla profile with user.js (start and close firefox a couple of times)

![perf](https://user-images.githubusercontent.com/16656956/39524384-4eb3e0be-4e08-11e8-9019-3e80ed6ff7ed.png)

**Comment by Cinik** [comment]
As for my tab 59.0.2 portable when it does freeze (every 5-20 minutes) taping on network icon on taskbar seems to temporaraly fix it. Best I can tell it only happens when a page or two is loading, or in the middle of a download. Other wise can switch between tabs ok except then.

**Comment by earthlng** [comment]
A performance impact is to be expected because we disable various things like disc cache, asmjs etc.

**Comment by earthlng** [comment]
I'll never understand how people can trust free VPN providers. This particular one seems shady as fuck.
Users are encouraged to and rewarded for promoting it and you can't trust any comments about it anywhere. That's the definition of shilling. One of their linked "Media Mentions" articles mentions

> ... and that entire thread is full of some pretty solid praise for Windscribe's terms of service and actual performance.

I wonder why that is ;) ...

> Rebilling revshare is available on case-by-case basis and **requires you to keep promoting Windscribe.**

And how is it possible that a yearly plan costs $49 and under https://windscribe.com/affiliate they say a user gets $45 if a referred user signs up for a year??!! They only keep $4?? And since lots of their users probably don't pay at all how is it possible that they have servers in 52 countries and 100 cities?

They also seem to like Monero https://windscribe.com/miner and I wouldn't be surprised if they inject crypto miners into the sites users visit. They have to make money somehow and if it's not miners it's something else. I wouldn't trust them at all but that's just me.

**Comment by Thorin-Oakenpants** [comment]
> A performance impact is to be expected because we disable various things like disc cache, asmjs, http2, prefetching etc.

Err, no - maybe this shit happens on ESR, IDK, but not Quantum. I'm on a 7+yr old PC (win7, 64bit, 8gb ram, fairly bleeding edge at the time, home built, speedy as F, played skyrim for a month solid until I took an arrow to the knee) and (except for first time after a reboot) FF opens in about 1 second, the UI is uber responsive and snappy, nothing hangs or sticks, certainly not chrome. Yup, no HW acceleration despite my card, no asmjs, no disk cache.

I think we'll have to wait for @Cinik to come back and confirm the e10s state. It doesn't take much to narrow down with the halving method, but could be tricky if it's multiple items in combo

**Comment by Cinik** [comment]
E10s are NOT disabled, not sure why I thought that, was something in about:config. Gota say I feel a little stupid for not double checking before answering. My set up looks like your screen shot Pants. about:support >Web Content Processes 2/4

**Comment by Cinik** [comment]
user_pref("browser.sessionhistory.max_entries", 5); fixed it. All issues in Linux now gone :D 

Checking tab now, will be back.

**Comment by Cinik** [comment]
Tablet seems to be working now aswell however user_pref("browser.sessionhistory.max_entries", 5); was already set. Time will tell.

Thanks Pants, Earthlng and Grauenwolfe.

**Comment by Thorin-Oakenpants** [comment]
`0804`
```
 * default=50, minimum=1=currentpage, 2 is the recommended minimum as some pages...
```

Earthlng pointed this one pref out earlier, IDK why I didn't pick up on it being zero (note to self, make a point to READ stuff instead of skimming over it) - I should have read the info in the file on `0804`

**Comment by Thorin-Oakenpants** [comment]
I'll close this for now. Good its all working. The windows tablet thing could be anything : 3rd party, driver, IDK. Let us know if it keeps playing up
