### ISSUE TITLE
[ISSUE] Search Engines for localized FF are not acceptable bloatware

### ISSUE THREAD

**Issue by iWARR** [ghacksuserjs/ghacks-user.js#414]
I'm in the process of migrating from chromium (Opera Dev.) to FF (EME-free) and I got stuck near the finish line. The most signnificant trouble is preinstalled Search Engines workaround and other integrated spying garbage.

I've read "ghacks-user.js" thread, friendly "12bytes.org" website articles (and many others), choose FF Addons and Scripts to install, done "MY OVERRIDES.js" draft, but I remain still confused with Search Engines.

### MESSAGE:

**Search Engines for localized FF are unacceptable bloatware and need for a close attention.**

### ISSUE:

Cleaning/sanitizing of preinstalled localized garbage is important for a wide auditory, doesn't matter which one language was used.

**Example:**

The most ugly thing: localized FF is full of russian bloatware for a non-Russia locales, really. Hope, devs from Mozilla (and all other devs), at last, will understand some day, that "russian language" is not always equal to "Russia" geo/locale or "russians" exactly.

This is important thing for the people over World (>10 countries), who MAY/SPEAK russian as secondary/primary language (~100 millions - w/o native speakers), but live in different countries, have their own official language, and may have completely different priorities, including IT sphere. This means that very common mistake of developers is a linking of local preferences to the language, instead of chosen geo-location (or not chosen).

Wiki: 

> "In March 2013 it was announced that Russian is now the second-most used language on the Internet after English".

[Global Online Presence (Infographics)](https://visual.ly/community/infographic/other/6-un-languages-world-wide)

As well, spying techs don't care about borders and speak with all one language - the language of deception. Actually, **creating of the universal hack would be great for all localized FF versions** were poisoned by the same way.

**1) about:config**

a) search for: `handlerService`

b) search for:
`browser.search.order.3		chrome://browser-region/locale/region.properties`

c) search for: `browser.contentHandlers` and `gecko.handlerService.schemes`
    All of them (a lot) have the same `chrome://` value.

**2)** What's inside (localized FF): Example to make a comparison with EN-US localization

`chrome://browser-region/locale/region.properties`

```
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# LOCALIZATION NOTE: REVIEW_REQUIRED
# Please do not commit any changes to this file without a review from
# the l10n-drivers team (this includes en-US). In order to get one,
# please file a bug, add the "productization" keyword and CC l10n@mozilla.com.

browser.search.defaultenginename = Яндекс
browser.search.order.1 = Яндекс
browser.search.order.2 = Google
browser.contentHandlers.types.0.title = Яндекс.Подписки
browser.contentHandlers.types.0.uri = http://mail.yandex.ru/lenta/add?feed_url=%s
browser.contentHandlers.types.1.title = RSS2Email
browser.contentHandlers.types.1.uri = http://www.rss2email.ru/?rss=%s
browser.contentHandlers.types.2.title = My Yahoo
browser.contentHandlers.types.2.uri = https://add.my.yahoo.com/rss?url=%s
gecko.handlerService.defaultHandlersVersion = 4
gecko.handlerService.schemes.webcal.0.name = Яндекс.Календарь
gecko.handlerService.schemes.webcal.0.uriTemplate = https://calendar.yandex.ru/importics.xml?ics=%s
gecko.handlerService.schemes.mailto.0.name = Яндекс.Почта
gecko.handlerService.schemes.mailto.0.uriTemplate = https://mail.yandex.ru/compose?mailto=%s
gecko.handlerService.schemes.mailto.1.name = Mail.Ru
gecko.handlerService.schemes.mailto.1.uriTemplate = http://win.mail.ru/cgi-bin/sentmsg?mailto=%s

gecko.handlerService.schemes.mailto.2.name=Gmail
gecko.handlerService.schemes.mailto.2.uriTemplate=https://mail.google.com/mail/?extsrc=mailto&url=%s

# The default set of protocol handlers for irc:
gecko.handlerService.schemes.irc.0.name = Mibbit
gecko.handlerService.schemes.irc.0.uriTemplate = https://www.mibbit.com/?url=%s

# The default set of protocol handlers for ircs:
gecko.handlerService.schemes.ircs.0.name = Mibbit
gecko.handlerService.schemes.ircs.0.uriTemplate = https://www.mibbit.com/?url=%s
```

I would like to clean ALL this garbage. Mail.ru, Yandex, Yahoo are HIGHLY untrusted. This is my opinion.

**3)** What is it?

`browser.hiddenWindowChromeURL		chrome://browser/content/hiddenWindow.xul`

### NEXT STEPS (for example, IMO):

**• QWANT** : as main Search Engine (SE): 

a) as primary SE
b) as default SE for the address (location) bar, search bar, etc., i.e. everywhere.

According to my experience, QWANT is SE that matches to all of these requirements :

**PROS:**

[+] safe, widely trusted 
[+] have own index also (hybrid engine)
[+] generate good results for EN-US locale
[+] generate not bad results for other locales also (quality is very important)
[+] have ability to save search preferences as code inside the initial link (and clear home webpage UI)
(make all QWANT web-settings at once -> save as special "smart link" -> use it as starting conditions for any search, no extension needed for this)
[+] nice UI, good fonts, good scale, searching results on the web-page looking accurate and comfortable

**CONS:**

[-] too much Bing-involved (probably).
[-] the way of setting SE by default in FF is under the question (main + address/searching bar + automated local results)

**• DuckDuckGo** : as Secondary choice.

It's not bad, it generates wide localized search results (wider than QWANT) with acceptable quality. Вut it's looks like a (dark) grey horse, if you try to discover more [info](https://github.com/nylira/prism-break/pull/1890) about cons. of DDG. At least, since we have another (a better) choices. Lets give DDG a chance to stay, it's already in the list.

**• searX** : as Tertiary choice.

This SE looks more promising than QWANT, but for now, its searching results are far not as good as QWANT or DDG ones, especially for a local searches. This is good choice for "private" searches, but not for everyday-use. I beleive, searX have a hidden leader potential that will grow in time.

[searx.site Add-on](https://addons.mozilla.org/en-US/firefox/addon/searx-site/) (can save settings)

**• Google** (and all others), IMO, must be excluded (i.e. kicked off) from the all DEFAULT automated search features in the FF.

A compomise of using Google could be a manually saved "quick link", somwhere in the front of UI - Speed Dial, Bookmarks, Quck Panels, or whatever.

As well, today Google offers the best searching quality and quick location/language OPTIONS in the front of web UI, highly effective for a local- or mixed- language searches. At the same time, this SE defined as unacceptable due to aggressive spying behavior and huge privacy leaks.

Of course, people, who still want it as main & address bar SE, should have ability to set it back easily.  Sanitizing is a must.

**• Wikipedia** (appears in FF as localized). 

May stay in the list as additional SE for the quick search from the address/searching bar. Sanitizing is a must.

**• 3-rd party apps** garbage in the FF "Applications" settings

**about:preferences -> Applications**

Should be cleared and write/update-protected (RO, or whatever, if possible). 
After restarting FF some of 3-rd party apps presets restore itself automatically, even when offline.

### TODO:

1) Basic **ghacks-user.js** search presets (i.e "safety from the box")

2) Reorganize Search Engines inside FF completely. **Possible variants:**

	a) Clean preinstalled SE completely (if such method is possible/compatible/acceptable).
	    Wiki: How to clean preinstalled SE and manually install recommended in the most easy and safe way.

	b) Propose already sanitized* SE xml-pack (using **nohamelin**'s [scripts](https://gist.github.com/nohamelin)) "as ready-to-go" feature.
	    Wiki: How to install *.xml files. How to clean the rest of unwanted SE. How to set a new safe SE.

	c) Use existing "chrome://browser-region/locale/region.properties" to hack preffered SE and reorganize already sanitized SE (*.xml files and FF settings).
	    How to protect this setting. Small Wiki.

	* sanitized SE have to support auto-complete feature (under control of FF settings); probably, relaxed Country Redirect (to support ML local queries); working icons will be OK also.

3) Wiki: How to quickly Backup/Restore your own SE preferences.

--------------------------------------------------------------------------------------
**P.S.**

- This is MY vision, probably a bit hardened. Now it's time to ask YOUR advices and ways of resolving this.

- I have almost done text (draft) for the Wiki: "Firefox System Plugins - How to remove"
Not because it's too complicated, but keeping in mind this really important step.
It should appear in the Wiki just to be noticeable and save time for newcomers.
If you are interested in, I can share this. (Say me where I can put the text).

- @Admins : Feel free to edit/delete/cut/reopen this message as you want, keeping it clear and useful.
  (I don't know if project providers (i.e Admins) can do such edits on GitHub within smb. else's inputs)
  My English is not my strong trait, I'm honesly sorry for that.

**Comment by iWARR** [comment]
@Atavic Thanks for your tips and links :)

> a complete wipe of those entries

Yes. But this is only half of the deal. The rest one is a BIG question how to integrate the new ones.

> trusted homepage

OK. As alternative - `about:blank`. If I remember correctly, this question is already done here.
(But in original "ghacks-user.js" v59 I have to change this manually through the OVERRIDES).

> place

Feedback is very important, of course. But a place doesn't matter for the final result.

The main aspects are:

- highly-trusted Search Engines
- clear instruction how to clear/change/integrate/manipulate
- it shoud be not too complicated for the wide auditory

--------------------------------------------------------------

About **ixquick/Startpage** meta-SE (results from Google, Yahoo/Bing, etc) that is not recommended:

- it fetches and uses the already-censored Google results
- it's too slow for me

**Comment by Atavic** [comment]
>highly-trusted Search Engines

I don't trust the Duck search engine.

Issue related to #118

**Comment by Atavic** [comment]
Issue related to #118

**Comment by iWARR** [comment]
@Atavic Ha-ha. We're say "a bit hardened" :)))

**Comment by iWARR** [comment]
Well, in case the SE question is too global (may be), I'm not expecting for resolving this at one shot.
I'll try doing with small and safe steps, one by one, asking your advices.
As I'm newcomer in FF and not a coder, I'm doubting to do radical things.

### Short plan:

**First Step** - manipulating things we already have integrated
**Second Step** - adding new SE

### First Step

Lets imagine, at start point, we have DDG, Wikipedia and Google.
Others were deleted through the FF settings (interface), no hack, nothing unusual.
Lets suppose we want set DDG as only one active SE and disable others.

**1. What can I do with this form:** `chrome://browser-region/locale/region.properties`

How can I edit this form/file?
Can I set DDG as main and emply all other values after `=` ?

```
browser.search.defaultenginename = DuckDuckGo
browser.search.order.1 = DuckDuckGo
browser.search.order.2 = <empty>
.... <empty all other values> ...
```

`gecko.handlerService.defaultHandlersVersion = 4`		- what is it?

**P.S.** I may suppose, that this `chrome://` form needed for "Search Engine Reset"? (see below)
      Am I right?

**2. user.js**

browser.search.defaultenginename .............................. `DuckDuckGo`
browser.search.defaultenginename.US ....................... `data:text/plain,browser.search.defaultenginename.US=DuckDuckGo`
browser.search.hiddenOneOffs ..................................... `Google,Википедия (ru)`

browser.search.official ....................................................... `false`

browser.search.order.1 .................................................... `DuckDuckGo`
browser.search.order.2 .................................................... <empty>
browser.search.order.3 .................................................... <empty>

browser.search.order.US.1 ............................................. `data:text/plain,browser.search.order.US.1=DuckDuckGo`
browser.search.order.US.2 ............................................. `data:text/plain,browser.search.order.US.2=`<empty>

browser.search.openintab ............................................. `true`
browser.search.context.loadInBackground ............ `false`

------------------------------------------------------------------------------------

```
user_pref("browser.search.defaultenginename", "DuckDuckGo"); // default (local) = <Local Search Provider> (i.e. some trash)
user_pref("browser.search.defaultenginename.US", "data:text/plain,browser.search.defaultenginename.US=DuckDuckGo"); // default = Google
user_pref("browser.search.hiddenOneOffs", "Google,Википедия (ru)"); // Search Engines were not chosen

user_pref("browser.search.official", false); // default = true

user_pref("browser.search.order.1", "DuckDuckGo"); // default (local) = <Local Search Provider> (i.e. some trash)
user_pref("browser.search.order.2", ""); // default = Google
user_pref("browser.search.order.3", ""); // default = chrome://browser-region/locale/region.properties

user_pref("browser.search.order.US.1", "data:text/plain,browser.search.order.US.1=DuckDuckGo"); // default = Google
user_pref("browser.search.order.US.2", ""); // default = Bing

user_pref("browser.search.openintab", true); // default = false
   // user_pref("browser.search.context.loadInBackground", true); // default = false (Foreground, new Tab)
```

Extra isurance (redundant, may be):

```
/* XXXX: Search Engine Reset = Disabled
 * Disables Mozilla's ability to warn and restore Search Engine to their defaults.
 * Whitelist is exception from the Reset procedure for the specific Search Engines.
 * https://github.com/ghacksuserjs/ghacks-user.js/issues/42 ***/
user_pref("browser.search.reset.enabled", false);
user_pref("browser.search.reset.whitelist", "");
```

_Note:_

Restoring Search defaults using (about:searchreset) consists from the two parts at once:

1) Reset (offline)	- Restores (localized) Search Engine defaults in the FF Settings. This doesn't touch `browser.search` options, preferred by User in `about:config`.
2) Update (online)	- Check for Search Engines Updates from Mozilla online sources.

**3. Go to sanitize SE.** The most important step before adding new safe SE.

Well, I need to discover this. A bit complicated at the first look...

- Would be enough to make `*.xml` files only for Google and Wikipedia (in case we disable/delete others until next FF update) ? Anyway, having them for all SE is better...

- Can you tell me how to connect ready `*.xml` files to FF, when done ?

**Comment by Thorin-Oakenpants** [comment]
Read #376 and #355 

The user.js is useless for setting search engines, it is useless for changing default engines, it is no good for setting associated files etc - there is a UI for all of this. This is outside the scope of what we can do.

**Comment by Thorin-Oakenpants** [comment]
I'm not closing this because I have a few things I want to explore. But fundamentally we can't use the user.js to dictate end users search engine defaults (or order which does not matter) since it's all essentially in an external file now: `search.json.mozlz4` I think. Plus localization means not everyone will have the search engine (or application) we enforce, so it would fail anyway.

user_pref("browser.search.reset.enabled", false);
user_pref("browser.search.reset.whitelist", "");
^^ these are still the default value. But what is interesting perhaps is `browser.search.reset.status` - mine is modified as `silent` - worth looking at. I think this might be when FF detects a search engine "hijacking" (or whatever they call it) it can roll you back `silently?` to defaults (see numerous reddit posts in r/Firefox about 57+ resetting search engines). IDK, the whole search prefs thing needs a look.

The weird thing is, I used to use [Add to Search Bar](https://addons.mozilla.org/firefox/addon/add-to-search-bar/) and removed all the default engines (except one eg yahoo, since it can't be empty), then added my dozen custom engines (eg google, google images, ddg, etc), and then removed the last default one (eg that yahoo one). These are STILL in my `profile/seachplugins` folder and if I delete them, I lose my engines - they are XML files. Some of these I added like 3 or 4 years ago.

What I plan to do, is probably delete them all and rebuild my custom engines using the add to search little green + symbol thing built into FF, via that mycroft page or whatever it is. So everything is in the moz file. How the whole search mechanism works is a bit of a mystery to me

**Comment by earthlng** [comment]
> These are STILL in my profile/seachplugins folder and if I delete them, I lose my engines

you don't lose them, they were migrated into your search.json file. Try renaming the folder and see what happens. spoiler: nothing - all your engines will still be there

**Comment by Thorin-Oakenpants** [comment]
^^ Been a while since I did anything to them. Might have been 55/56 getting ready for removal of all legacy extensions, but I tested without them and they broke (at the time). Will try removing the leftover files again later on.

**Comment by iWARR** [comment]
Don't close this. A have a lot things to say. But a bit later, when I'll finish my tests.
Also I have to resolve some strage things of FF behaviour.

**Comment by Thorin-Oakenpants** [comment]
I don't know if this means anything - https://bugzilla.mozilla.org/show_bug.cgi?id=1461345 re search.order

**Comment by Thorin-Oakenpants** [comment]
Closing this. As already said, the prefs mean nothing or we can't change them due to what engines end users may or may not have, plus it's all a bit deprecated - its basically stored in external files and has nothing to do with about:config anymore. There's also a whole UI for search, and there are hundreds of engines and tens of thousands of articles and a gazillion-billion-trillion opinions on what engines to use.

Whatever it is you're investigating @iWARR , by all means, let us know - but there's naught we can do via user.js
