### ISSUE TITLE
Enable geo now it can be default blocked (FF60+ branch)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#415]
now we're on 60 (yes, I understand some ESR users will hold out until 62), I propose that geo be relaxed

We can check default for ESR52 branch ( I think it's ask), but in 60+ we can allow geo but instead set the default to block: so:
- 0201 `geo.enabled`=`false` => inactive
- 0211 `permissions.default.geo`=`2` => active

Note: until they reverse it, RFP will still block geo anyway - see [1441295](https://bugzilla.mozilla.org/show_bug.cgi?id=1441295). But for non RFP users, this allows the end user more flexibility

**Comment by Thorin-Oakenpants** [comment]
Can anyone on an ESR52 have a quick look at the default in the site permissions panel (can be any site, eg github) and tell me the default, pretty please

Not sure how prevalent geolocation requests are, but if we do this it could be a case of fatigue prompt for some ESR52 users until they figure it out

**Comment by Pilford** [comment]
Here’s a screenshot of the site permissions panel in 52.7.4 ESR, without user.js. With user.js there’s only one difference: Set Cookies => Block.

https://s17.postimg.cc/i3qiy4e1r/permissions.png

**Comment by Thorin-Oakenpants** [comment]
Thanks. So access location is always ask.

**Comment by Thorin-Oakenpants** [comment]
Not hearing any dissenters
- non ESR users there is no change, with or without RFP, geo is auto blocked - this simply allows end user choice to set a site override *if they want.need it*
- ESR52 users might get prompt fatigue - in which case they can use an override for `0201`
- Android users: NFI what happens there

Heading off for some R&R .. if no objects, I'll do a commit

**Comment by earthlng** [comment]
for non ESR users **with** RFP there's no way to override, is there? That's why they want to undo the geo block in RFP in the 1st place, no?

I'd prefer to wait with this change until FF62 (=ESR52.x EOL)

If or when you make this change, it'd probably be good to make 0211 -> 0201b.

**Comment by Thorin-Oakenpants** [comment]
> for non ESR users with RFP there's no way to override, is there? That's why they want to undo the geo block in RFP in the 1st place, no?

correct. since the default is to ask, there is no privacy risk (except from prompt fatigue and ignorance?), and it would be a barrier to uptake of RFP. Hence mozilla want to remove RFP blocking geo, and this still allows TBB to block geo via the `geo.enabled` pref

I *know* you have 62stable as a changeover, for you, just override the `geo.enabled` pref. There's no "danger" for ESR52 users as the default is to ask. I don't really want to have to track things I want to do over three releases (stable, esr60 and esr52)

PS: happy to leave in 27 lines with ESR52 [SETTING] tags until FF62 because they're just comment lines, whereas this change is actual pref changes

PPS: Yeah, I know 0211 should be next to 0201 .. I hate those `b`s

**Comment by earthlng** [comment]
why change it now if it makes absolutely zero difference to non-ESR users?

> Hence mozilla want to remove RFP blocking geo

yes they **want to** but they haven't yet. Unless they'll backport the coming change, the earliest version that will have it is FF62 anyway

**Comment by Thorin-Oakenpants** [comment]
I know that.

NOT EVERYONE USES RFP, so these values as per the commit BENEFIT users on 58+ - i.e it still blocks geo but allows more flexibility
