### ISSUE TITLE
remove some prefs

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#418]
@earthlng said

nice. If we want to do a spring cleaning here are a couple more I think we can remove:

* [x] `2664` pref("device.storage.enabled", false); - default false everywhere except Android

default true everywhere:

* `0705` pref("network.dns.blockDotOnion", true);
* `1210` pref("security.ssl.enable_ocsp_stapling", true);
* [x]  `1223` pref("network.stricttransportsecurity.preloadlist", true);
* [x]  `2680` pref("security.block_script_with_wrong_mime", true);
* [x]  `2686` pref("security.fileuri.strict_origin_policy", true);
* [x]  `2687` pref("security.sri.enable", true);
* `2705` pref("network.cookie.leave-secure-alone", true);

**Comment by Thorin-Oakenpants** [comment]
- I'm OK with removing `2680`, `2686`, `2687` - I think there are more of these in our sticky to watch items, certainly some were/are on my bugzilla watchlist
- `1223` can go
- ^^ thumbs up if you're OK with removing these four

---

- 2664: keeping the info might be good for android users, but I have no idea what impact this has
- the rest, not so sure for now

**Comment by earthlng** [comment]
the nice thing is we don't have to worry about resetting them because most prefs that are enforcing FF's default value aren't stored in prefs.js. I just tested it with FF59 and for all of the prefs in the above list, once they're no longer in the user.js they automatically show as "default" in about:config.

**Comment by earthlng** [comment]
I'm okay with removing all of them. If you only want to remove 4 for now that's fine too

**Comment by earthlng** [comment]
add https://wiki.mozilla.org/Privacy/Features/ to the wiki References?

**Comment by Thorin-Oakenpants** [comment]
^^ done :+1: 

I think I'll leave the rest: ocsp stapling after all the issues and discussion and scott's link, I'd like to keep it :). Cookie helps round out the full cookie picture. Onion may come in handy down the track with Fusion, besides cookie + network sections are small(ish)

**Comment by earthlng** [comment]
with or without TOR, dns.blockDotOnion=true is always what you want. It even confuses you so that's 1 more reason to remove it IMHO

**Comment by Thorin-Oakenpants** [comment]
how does it confuse me? right now you cannot load a .onion site anyway = this is the dns lookup (yeah we want it true). That said, Fusion may happen and it opens a lot of stuff/prefs/etc up, and keeping this in the js may come in handy

**Comment by earthlng** [comment]
AFAIK there's no reason to change dns.blockDotOnion to false, EVER. You seem to be confused about that because why else would you want to keep it

**Comment by Thorin-Oakenpants** [comment]
>  If you only want to remove 4 for now that's fine too

Fucked if I know then

**Comment by earthlng** [comment]
I don't give a fuck whether you remove it or not, I just tried to clarify a misconception on your part when you said

> Onion may come in handy down the track with Fusion

I know what it does so I don't really fucking care. Just sayin' that having it in the user.js might confuse some users into thinking they need to set it to false if they use FF with Tor. Which seems to be what you thought too

**Comment by Thorin-Oakenpants** [comment]
> You seem to be confused about that because why else would you want to keep it

To educate users. We have lots of prefs inactive or at default for info purposes

> Which seems to be what you thought too

That's not what I thought at all. The only reason I think this *IS* useful (and could be in the future) is to ENFORCE it so it avoids confusion (see next comment). I never said I would ever change its value if that's what you thought re the future and why I would keep it

> Just sayin' that having it in the user.js might confuse some users into thinking they need to set it to false if they use FF with Tor

Good point. It currently doesn't shed any light on said "confusion". If we ditch it then end users are not educated. I'd rather fix up the description

**Comment by Thorin-Oakenpants** [comment]
actually, nvm .. if anyone wants to configure FF to visit onion sites, that's on them. Less shit for us to worry about
