### ISSUE TITLE
discussion: revisit browser.search.reset.enabled

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#42]
I am in the middle of 52 upgrades + changes, revamping passwords section, revamping 800 section, waiting to commit 1600 section revamp, trying to close out the wiki and readme (and have a life and do my other sh*t) .... anyway, I just moved the following pref from the 0800 section where it does not fit, and for the life of me can't remember (or added it before it launched and never fully explored it) what the heck it actually achieves.

```
/* 3025: disable search reset (about:searchreset) (FF51+)
 * http://www.ghacks.net/2016/08/19/firefox-51-search-restore-feature/ ***/
user_pref("browser.search.reset.enabled", false);
user_pref("browser.search.reset.whitelist", "");
```

At first glance it doesn't seem to do anything. It does not block the page or disable the buttons in about:searchreset.. Nor does not disable the button "Restore Default Search Engines" in Options>Search (which I am loathe to click right now, but could do a test later). I'm a bit preoccupied with a dozen things. Can someone please tell me exactly what this does. I would like to either dismiss the pref or clarify exactly what it does.

**Comment by earthlng** [comment]
We added it when it came up in the v50-vs-v51 diff.
I had to look at the DXR for Aurora to find something, so it's likely not implemented to do anything in stable just yet.
https://dxr.mozilla.org/mozilla-aurora/source/toolkit/components/search/nsSearchService.js#2418
I'd just leave it as is for now

**Comment by Roman-Nopantski** [comment]
heh: https://bugzilla.mozilla.org/show_bug.cgi?id=1203168  `browser.search.reset.enabled` FF49 .. these are not the mice you are looking for .. jedi hand wave thingie

**Comment by Roman-Nopantski** [comment]
I think I understand: the pref doesn't disable options to reset things, it disables Mozilla's ability to warn you if you’re using a search engine that came from unknown origin as default.

**Comment by earthlng** [comment]
`enabled in 51` - no, I'm still on FF51 and the default is false

**Comment by Roman-Nopantski** [comment]
oh .. ok, no worries, was killing time until I got your thumbs up on 1409. will revisit this in the future. seems like a dead end to me. It's also false as default in 52, and the whitelist is blank by default too. Beginning to think we should ditch it.

--
The reset button exists when you are not using the default engine(s?) (I have none, i deleted them all and added custom ones via "Add To Search Bar" (which is not e10s, but if you delete the addon, all the search engines stay, and in fact are accessible and editable etc as xml files in `profile\searchplugins` ). I will test one day if clicking the button merely takes you to the about:resetsearch page, which makes sense, because as a landing page it can tell you the engine it wants to install - in this case smelly yahoo - before you decide to actually do it. So I think the Options>Search button is fine to click.

I'm struggling to see why we should keep it.

**Comment by earthlng** [comment]
yeah, lets revisit this at a later point. For now it's fine under 3000 IMO.

**Comment by Atavic** [comment]
>Nor does not disable the button "Restore Default Search Engines"

That's what it's supposed to do, IMHO

>The reset button exists when you are not using the default engines.

It's always there, but it's greyed out while using the default ones. They are stored as .xml in the _searchplugins_ Folder.

The whitelist entry should be a list of your own personal search engines to be kept when you reset the engines list.

**Comment by Roman-Nopantski** [comment]
This doesn't do anything.

BTW: In about:preferences#search if you click "Restore Default Search Engines", it just adds all the default ones back at the top of the list. If even one of those is removed, the button is enabled again 

With all the default engines in place, the pref value does not change. The about:searchreset page does not change. No changes anywhere with it on or off.

Am removing it.  I'm not even sure if want to mess with the ability to reset (I say nah), let alone people's search engines (definitely not). Maybe if it the pref is ever flipped from default false to true, we can revisit.

**Comment by Roman-Nopantski** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/369678e02b2cbdd75ab907014de996ab89d77771

**Comment by Hemmingen** [comment]
This is still an issue in Firefox 66 / ESR 60.6 and I don't know what we could do to disable the reset of search engines. Anyone knows if Mozilla is doing something about that?
