### ISSUE TITLE
Troubleshooting "Conceal window.name" script

### ISSUE THREAD

**Issue by iWARR** [ghacksuserjs/ghacks-user.js#420]
### ISSUE

"**Conceal window.name**" [script](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts) doesn't work for me as expected.

"JoDonym" [test](http://ip-check.info/?lang=en) shows the result as not "green", it's still unprotected : `"window.name" is traceable`
 Script (if no exceptions) brakes some pages, for example DISQUS chat integration, PayPal, etc.

I tested it on FF and Opera Dev - the same results.

**For chromium (probably, for the FF also):**

You need to privide an exceptions via Violentmonkey, under "Excluded Pages" field:	
Options -> "@exclude" rules

`*ip-check.info/*`	- This exception is relative to 1-rd party domain name. It's responsible for the (1-rd party) link on the landing "JoDonym" page. So test can start.

`*disqus.com/*`		- ATTENTION: This exception is relative to 3-rd party frames (not the source pages)! It's necessary for integrated DISQUS chats on different websites.

Other known exceptions: PayPal

**Note:**

-- The most sensitive things are: a correct choice, what domain name needs for exception
-- Very careful and correct name constructions for "@exclude" rules in the Violentmonkey

Then webpages will work properly (but still not protected).

Adding a rules it's annoing pactice. May be allowing any queries (1-st, 3-rd) from the opened page should be better (likely "isolation" have to be taken into account)

--------------------------------------

I found somewhere deep on the Internet forums an old EXTENSION for chromiums that working and protecting `window.name`.

It works in chromiums, testing shows GREEN (protected) result.
A disadvantage if this - exceptions are not possible.

So, may be somebody can have a look inside the .*crx and grab+impove the code to work in FF as a Script (so exceptions should be possible)

### ALTERNATIVE (chomiums):

Extension **"Window Name Eraser v0.1.6"** (29.06.2016).

A *.crx extention for chromiums is able to protect` window.name` and show it as "green", but also brakes some pages functionality.

[Download](http://game-edition.ru/masterskaya/rasshirenie-dlya-chrome-smajly-onlajn/?action=dlattach;attach=11008;PHPSESSID=76cd65c06e38ef4e198b274954e67ac6)

-------------------------------------

**Why saying about chromiums?**

Chromiums (Opera Dev) are very sensible to the proper code of the scripts.

So, I guess, a "good code" should work for both browsers, according to my experiance. Of course it is not a "must" condition. Since I have Opera Dev installed for a while, I may test a new script for both browsers, if somebody make the new one.

**Comment by Thorin-Oakenpants** [comment]
A web extension with whitelisting would be quite nice - i.e breakage could be mitigated. Not come across any myself - I refuse to use paypal and disqus is just another 3rd party that aggregates (the nature of the beast I guess - not knocking the pros/convenience of having one login for hundreds of sites). I'm sure they could function perfectly without trying to access windows.name

Anyway: it is proposed in [444222#c88](https://bugzilla.mozilla.org/show_bug.cgi?id=444222#c88) that FPI take care of this - not sure how they will handle things like paypal, disqus etc if it's anything like those cross-domain logins that break in FPI

**Comment by Thorin-Oakenpants** [comment]
I added "reported breakage (3rd party): paypal, disqus (just add exceptions)" to the wiki

**Comment by Thorin-Oakenpants** [comment]
> Of couse, I did. I don't have isssues running the test

Oh, OK. I thought you did. As for breakage, it's to be expected. The script itself even excludes recaptcha. But of course it's always good to add extra info, especially if it's common sites - the xtra info for the wiki is helpful :+1: thanks
