### ISSUE TITLE
uBO: block workers & add exceptions

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#421]
@gorhill if you have time

With FF60+ having deprecated the `dom.workers.enabled` pref, I thought it would be nice to add an example to our [uBO scripts](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.2-uBlock-Origin) (because not everyone has uMatrix)

Is this correct? <sup>[source](https://old.reddit.com/r/uBlockOrigin/comments/8ieixu/how_to_block_workers_using_ubo/)</sup>

To block all workers
```
||$csp=worker-src 'none'
```

Below is what the reddit answer said for exceptions, but may be impractical for maintaining/reading 20 or 100 exceptions. Is there a way for an additional line(s) to allow an exception
```
||$csp=worker-src 'none',domain=~exceptiondomain.com|~exceptiondomain2.com
```

TIA

**Comment by gorhill** [comment]
Prevent workers everywhere:

    *$csp=worker-src 'none'

Exception, do not prevent workers on `example.org`:

    @@||example.org^$csp=workers-src 'none'

I didn't try it but I am pretty that should work.

**Comment by Thorin-Oakenpants** [comment]
Thanks. The reddit OP said that's what he tried and it didn't work (i.e `*$csp=worker-src 'none';` <- note he has a semi colon at the end which I have no idea if that was just in his post or his filter). I'll test it all out later on

**Comment by Thorin-Oakenpants** [comment]
OK, haven't tested it, but I will put my faith in everyone else :gulp: Added to the wiki. Hope I got the FF58+ and uM v1.2.0 info correct

---

- Workers (requires [FF58+](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src))
   * If you have uMatrix [1.2.0+](https://github.com/gorhill/uMatrix/releases/tag/1.2.0), there is a new switch: "Forbid web workers", use that instead.
   * Note: `dom.workers.enabled` was [deprecated](https://bugzilla.mozilla.org/1434934) in FF60
   * Prevent workers everywhere (first line below)
   * Exception, do not prevent workers on `example.org` (second line below)
```
*$csp=worker-src 'none'
@@||example.org^$csp=worker-src 'none'
```

**Comment by crssi** [comment]
^^ I have tested this a few days ago and I am using it for the last few days and it works as it should.

Cheers
