### ISSUE TITLE
PSA: uBO filter for startpage 1x1pixel images: updated [see wiki]

### ISSUE THREAD

**Issue by ruiumbelino** [ghacksuserjs/ghacks-user.js#425]
I'm using this on uBlock Origin (Vivaldi and Firefox), and I need to add an '*' after ||, to these filters works:

```
! 1x1pixel clear images on startpage and ixquick
||*/do/avtc?$image,important,domain=ixquick.com|ixquick.eu|startpage.com
||*/do/showimage?$image,important,domain=ixquick.com|ixquick.eu|startpage.com
||*/english/web/$image,important,domain=ixquick.com|ixquick.eu|startpage.com
||*/tix2/$image,important,domain=ixquick.com|ixquick.eu|startpage.com
||*/tst2/*$image,important,domain=ixquick.com|ixquick.eu|startpage.com
```
Only I have this issue, or...?

Thanks

**Comment by Thorin-Oakenpants** [comment]
I have no idea about Vivaldi, but it works for me on Firefox (uBO is stable 1.16.6)
![worksforme](https://user-images.githubusercontent.com/16656956/40252895-550b0ef2-5acd-11e8-8513-054e15dd80c3.png)

**Comment by Thorin-Oakenpants** [comment]
What FF version and uBO versions are you running?

**Comment by 2glops** [comment]
Works fine too here on: 
FF 60.0.1 / Linux
uBo 1.16.7b2

**Comment by ruiumbelino** [comment]
@Thorin-Oakenpants ,

Try to disable the EasyPrivacy list, and check again... ;)

**Comment by Thorin-Oakenpants** [comment]
confirmed @earthlng 
![yup](https://user-images.githubusercontent.com/16656956/40340377-32e808cc-5d6e-11e8-993a-3700448ae933.png)

I have not tested with the added preceeding `*` with EasyPrivacy list enabled

**Comment by earthlng** [comment]
1. the rules still work in uBO 1.13.8 (legacy). IDK why such rules are no longer supported in newer versions.
2. [ixquick now redirects to startpage](https://www.ghacks.net/2018/04/02/search-engine-ixquick-eu-redirects-to-startpage-com/)
3. startpage.com seems to be the only TLD. several others exist but are either unrelated to SP or redirect to .com: fe. .fr redirects to .com, .net redirects to www.smartphonemart.net, .co.uk is unrelated, etc

updated filters:
```
! 1x1pixel clear images on startpage.com
||startpage.com/do/*$image,important
||startpage.com/english/*$image,important
||startpage.com/tst2/*$image,important
```
- the 1st filter now matches both /do/avtc + /do/showimage
- the 2nd now also matches /english/pics/ and /english/video/
- `||*/tix2/$image,important,domain=ixquick.com|ixquick.eu|startpage.com` was ixquick related and doesn't exist anymore

**Comment by Thorin-Oakenpants** [comment]
> EDIT: have not tested SP with JS allowed ...

OK, I did it with JS, and this is with the EasyPrivacy list disabled, also I updated the wiki
![nailedit](https://user-images.githubusercontent.com/16656956/40363167-3fbd1d80-5dbe-11e8-9b50-c55b8de7fcba.png)

**Comment by earthlng** [comment]
The filters will work with or without JS but what I meant was that JS could potentially load other shady stuff.
But it's not my problem if people allow JS on sites where it's not necessary so yeah fuck it
