### ISSUE TITLE
RFP & CanvasBlocker 0.4.5a/b [resolved in 0.4.5c]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#429]
@kkapsner et al

I have found some inconsistency between what canvas hash is produced between these two, As per #350 see the canvas section in OP

> strategy
> * set CanvasBlocker to fake. Do NOT set to block as this will disable the API and you will not get the same result as RFP.
> * block sites when prompted: RFP takes over and CB is never used
> * allow sites IF you must: RFP allows CB to take over which will fake
> * use a CB whitelist for sites that MUST have the real thing

---

### STR

FF60.0.1, CB 0.4.5a or 0.4.5b, RFP=true, CB=fake readout API

Start FF
 - Test: [Panopticlick](https://panopticlick.eff.org/)
 - click show full results, note the canvas hash, click `retest your browser`
 - do the above step three or four or five times

Results
 - you should be able to get two different hashs across your tests
 - `a273d6a847f0e2a57fa0161158f12fed` - the TBB/RFP one
 - `65af54d62bad1202c051a955c63d4d7d`

---

So based on this behavior, the strategy above sometimes fails

**Comment by Thorin-Oakenpants** [comment]
Cool. Enabled notifications (and for this test to store the image)
![cb](https://user-images.githubusercontent.com/16656956/40317885-5d9a974e-5d12-11e8-8227-3082b0a3aa9d.png)

clicking `more` shows `toDataUR`L > 2000x2000 white canvas

**Comment by Thorin-Oakenpants** [comment]
Here we go: CB on in fake mode, RFP on

When I get the `a27...` which = same RFP with no CB, or TBB
![a27](https://user-images.githubusercontent.com/16656956/40318976-00e3c738-5d16-11e8-801a-9244a0324c14.png)

When I get `65a...`
![65a](https://user-images.githubusercontent.com/16656956/40319027-2ff19744-5d16-11e8-982b-bb373cf5c33e.png)

It's also wildly inconsistent which result I get. Both results show both `isPointInPath` and `toDataURL` generate a canvas, and for every instance the canvas is a 2000x2000 white (I assume white) png - all four results were compared = they are identical

**Comment by Thorin-Oakenpants** [comment]
:small_red_triangle_down:  4.5b = my main FF profile

results above, interesting only one toDataURL (see below)

:small_red_triangle_down: 4.4a AND 4.5b = vanilla FF profile

a273d6a847f0e2a57fa0161158f12fed
65af54d62bad1202c051a955c63d4d7d

isPointinPath - 2000x2000
toDataUrl - 2000x2000
toDataUrl - 300x150

Was able to consistently get both hashs on Panopticlick - data for both identical. Interesting that I got a second toDataURL compared to my main FF (but not relevant here)

:small_red_triangle_down: 4.4b = vanilla FF profile

a273d6a847f0e2a57fa0161158f12fed

toDataUrl - 2000x2000
toDataUrl - 300x150

Could not get the `65a...` hash which is excellent.

:small_red_triangle_down: conclusion

You're the expert. `isPointinPath` in 4.5a+b seems to be overriding/affecting RFP's 10x10 white canvas, as this is absent in 4.4b (didn't check 4.4a)?

**Comment by kkapsner** [comment]
Thanks for testing. I thought that isPointInPath is protected like the other readout functions with the RFP. Apparently that's not the case. I'm not sure what we should do in that case as isPointInPath can provide fingerprinting information. Any ideas?

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1422890

> canvas.isPointInPath [...] we should have a test case for each of them

What's confusing me are
- where and what exactly is the `65a...` hash coming from?
- why does the test return two results with no changes, i.e what **exactly** causes `65a..` to be produced, is it a timing issue?

**Comment by kkapsner** [comment]
No it's not a timing issue - the isPointInPath is treated differently and is therefore not protected by RFP the same way the other functions are.
I will change that and release a new version soon.

**Comment by kkapsner** [comment]
0.4.5c landed and should be verified soon. Please recheck with it.

**Comment by Thorin-Oakenpants** [comment]
I'm going to have to test this in FF61 and FF62 given these mozilla bugs

- Bug [1412961](https://bugzilla.mozilla.org/show_bug.cgi?id=1412961) (FF61+)
- Bug [1453916](https://bugzilla.mozilla.org/show_bug.cgi?id=1453916) (FF62+)

**Comment by kkapsner** [comment]
My tests/development was done in Firefox nightly (62.0a1 2018-05-10) and I see the correct behaviour there. But you're right: we have to have an eye on this.

PS: just updated to 2018-05-26 and still correct. Fingers crossed.

**Comment by Thorin-Oakenpants** [comment]
and also https://bugzilla.mozilla.org/show_bug.cgi?id=1422890 when they get around to it - see comments 5 & 6

**Comment by Thorin-Oakenpants** [comment]
OK, so I'll close this - I have an eye on the RFP canvas Mozilla stuff. Thanks :)
