### ISSUE TITLE
(Site) Username/Email field menu reveal-privacy issue?

### ISSUE THREAD

**Issue by ZongMan** [ghacksuserjs/ghacks-user.js#43]
Websites i visit  that i have registered onwith a username/Email field drop down reveal them selves when about to sign in, any way to prevent this?  check out attached pic
https://imgur.com/a/cK6Et

**Comment by Atavic** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/29#issuecomment-281868627

**Comment by Roman-Nopantski** [comment]
By your own admission .. you are about to sign in. How did you expect to enter the username data with the contents of it being invisible? The "dropdown" will only show if you click or start typing in the field.

You can disable it entirely - the info is all in the js. You can also enforce a master password, and make it ask every time - this way nothing will come up until you allow it, but will still save you remembering your account name(s) and password(s) - which, by allowing saved passwords/logins, this should also encourage you to use strong passwords.

There's always usually going to be a trade-off between convenience (easy to login, no mistakes/typos, faster) vs security (can now use extra strong unique passwords and different account names etc, no need to remember) vs privacy (shit, some a-hole was spying on with his telescope at a 1000 yards). That last point .. if you are going to log in, at some stage the username will be visible,
