### ISSUE TITLE
wiki: add enterprise-policy-generator extension?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#431]
[Enterprise Policy Generator](https://addons.mozilla.org/firefox/addon/enterprise-policy-generator/) | [GitHub](https://github.com/cadeyrn/enterprise-policy-generator)
Article: https://www.ghacks.net/2018/05/21/enterprise-policy-generator-add-on-for-firefox/

Seems like a nice tool for ESR users. Haven't loaded it or played with it. I think it's worth adding to the wiki, since GP allows some changes that we can't do with prefs alone.

Class, discuss!

PS: also Sören Hentzschel is one of the good guys

**Comment by claustromaniac** [comment]
Nice find. Even if this extension didn't exist, the _Enterprise Policy Engine_ by itself would still be worth a mention in my opinion. The extension is nice in that it makes it user-friendly.

**Comment by Thorin-Oakenpants** [comment]
>  the Enterprise Policy Engine by itself would still be worth a mention

I already have links for that in the [wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-b:-References), and can add the extension link there as well as the extensions page

**Comment by claustromaniac** [comment]
Ah.. great. I see you added it recently. Now, that's efficiency. :laughing:

**Comment by Thorin-Oakenpants** [comment]
done
