### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#441]
@gorhill @earthlng 

If FF has `privacy.resistFingerprinting`=`true` (which in FF60+ until next ESR will spoof the version as 60), and lets say you are on FF61 or FF62, can you still use the web ext APIs to get the true FF version? Or do you have to fall back on feature detection

**Comment by earthlng** [comment]
> ... can you still use the web ext APIs to get the true FF version? 

Yes. [runtime.getBrowserInfo()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getBrowserInfo) is not affected by RFP

**Comment by Thorin-Oakenpants** [comment]
Thanks

**Comment by earthlng** [comment]
you don't get access to the webextension APIs with scratchpads

**Comment by gorhill** [comment]
Enter the following in the browser console you get when debugging uBO (or any extension really):

    browser.runtime.getBrowserInfo(info => { console.log(info); });

Output on my side:

    Object { name: "Firefox", vendor: "Mozilla", version: "60.0.1", buildID: "20180518175514" }

**Comment by Thorin-Oakenpants** [comment]
Now you're all just showing me up .. I can't get to work, or understand, any of that. No need to answer, but
where is a `uBO console`?

> Enter the following in the browser console

Can't paste in the `browser console`, but if I do it in the `web console` (at the bottom), I get an error
- ReferenceError: browser is not defined

**Comment by Thorin-Oakenpants** [comment]
Anyway: FYI, I was trying to solve an issue for the Forget Me Not guy. I was having a nosy there and couldn't imagine that extensions would have this issue (or there would have been a flood of bugzillas)
- `https://github.com/Lusito/forget-me-not/issues/57`

His problem seems to be (after some prodding):
> I know getBrowserInfo is not affected, but it uses a promise based API, i.e. I don't get the results instantly. That's why I've used navigator.userAgent & co to detect the browser version, which gives me the spoofed version. So I'll need to rewrite some code to make this work.

**Comment by gorhill** [comment]
> where is a uBO console?

Go to `about:debugging`, find uBO in there then click "Debug", this will bring up the developer tools for uBO.

**Comment by Thorin-Oakenpants** [comment]
Thanks. Unfortunately for me, `Debug` is disabled - might be a FF pref. I'll troubleshoot it later

**Comment by gorhill** [comment]
Check "Enable add-on debugging" at the top of the page.
