### ISSUE TITLE
"wow ~ monster eats the image" Error on crypto exchanges [solved: network.http.referer.XOriginPolicy]

### ISSUE THREAD

**Issue by 2SI3NX** [ghacksuserjs/ghacks-user.js#444]
Whether you go onto Binance or Kucoin, whether you try to register or login, when trying to complete the puzzle it never accepts the input and keeps asking again and again, there is no end to this.
Im pretty sure it has to do with one of the user.js settings, but i dont know which one.
Any idea?

**Comment by crssi** [comment]
Found once...I don't remember which one, but to wide.
Ending best to use different browser just for this purpose.

**Comment by 2SI3NX** [comment]
Yes i also use a different browser, but that is not a solution. Because this has been pissing off a lot of people and no-one knows why.

**Comment by crssi** [comment]
`https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting`

**Comment by Thorin-Oakenpants** [comment]
> Im pretty sure it has to do with one of the user.js settings

Pretty sure?
- Have you created a new profile and tested that you **can** get in?
- Have you **then** added the user.js and confirmed you **can't** get in?

This would then prove that it was something in the user.js and not something else, like an extension. The only way you are going to find an answer is by troubleshooting.

Also, please state what version of FF you are using. Too many times now, people come up with issues and are using FF56 or something.

**Comment by 2SI3NX** [comment]
Yeah pretty sure, because i disabled all other addons thats why i said that.
Ive tested it on a new profile yes.
and yes to the second question.
FF 60.0.1

Thought someone maybe experienced the same and could have the solution, but if its troubleshooting that has to be done..then it will be done.

**Comment by Thorin-Oakenpants** [comment]
I haven't gone to the websites, I have no idea what this puzzle thing is but some of the more common issues are
- allow a cookie(s)
- privacy.resistFingerprinting (eg screwing up canvas, you can set a site exception for canvas)
- first party isolation
- service workers
- see https://github.com/ghacksuserjs/ghacks-user.js/blob/master/scratchpad-scripts/troubleshooter.js where earthlng put them in some sort of order (this is not every pref of course)

**Comment by Thorin-Oakenpants** [comment]
> because i disabled all other addons thats why i said that

You didn't say that. And disabling all addons doesn't eliminate all possible non-user.js causes (such as 3rd party eg anti-virus, or custom end-user about:config tweaks). But you seem sure, so that's good enough then to start troubleshooting - flip some prefs and clear everything (ctrl-shift-del) and retest - repeat (or use the halving method)

**Comment by 2SI3NX** [comment]
You misunderstood me, "Yeah pretty sure, because i disabled all other addons thats why i said that."

yeah "pretty sure" <-- thats why i said that

Anyway i found where the problem was hiding:

`network.http.referer.XOriginPolicy`

    Only send Referer header when the full hostnames match.
    0 = Send Referer in all cases
    1 = Send Referer to same eTLD sites (Warning: '1' breaks login puzzles on crypto exchanges etc., so set to '0')
    2 = Send Referer only when the full hostnames match`

So this has to be then set to '0'. Ive also found in general that this breaks a lot of other logins on other sites as well.  What exactly is the significance of `network.http.referer.XOriginPolicy` and (in lamens terms) what happens when its set to just 0 ?

**Comment by Thorin-Oakenpants** [comment]
> what happens when its set to just 0

0=always - so in other words, if the site wanted to send a referer, then it would always be sent

The prefs 1601-1605, they ALL break the internet somewhere if you don't have them at default. Firefox defaults means no breakage, standards compliant, end users happy out of the box. But this of course means zero control over tracking via referers.

1601+1602+1605 we have at default. But 1603+1604 we tightened a tiny bit (we could have hardened it more). At the end of the day, if you want **any** control over, then you need an extension
