### ISSUE TITLE
service workers

### ISSUE THREAD

**Issue by jjurkus** [ghacksuserjs/ghacks-user.js#446]
```
*** 2300: WEB WORKERS [SETUP]
<snip>
[WARNING] Disabling workers *will* break sites (e.g. Google Street View, Twitter).
```

Huh? dom.serviceWorkers.enabled seems to be false by default in ESR60 (and on ESR52). I'm not sure what should not work about google street view, but it looks ok here.

**Comment by crssi** [comment]
^^On FF 60.0.2 (Win10) `dom.serviceWorkers.enabled = true` by default, and AFAIK always was.

**Comment by jjurkus** [comment]
I reinstalled FF 60.0.2 ESR, and removed the Mozilla directories in AppData\Roaming and AppData\Local, so it starts with a new profile. Removed any polices and settings in firefox.js (but none had to do with this and any should have made something show up in about:config).

Still: dom.serviceWorkers.enabled;false

Windows 7 Professional N 64-bit SP1 (in a domain)
Hardware of this testmachine is older, but newer computers have this setting also set to false.

**Comment by jjurkus** [comment]
about:debugging shows "Your browser configuration is not compatible with Service Workers"

```
Service workers can be unavailable for several reasons:
If you are using a Private Browsing window.
If your History preference is set to "Never Remember History" or "Always use private browsing mode".
If the dom.serviceWorkers.enable preference is set to false in about:config.
```
None of those apply, except that last one of course (which is the default value here). Why it is set like that might be more suited for somewhere else.
So, uh, to recap: with dom.serviceWorkers.enabled set to false google street view doesn't seem broken.

**Comment by jjurkus** [comment]
[https://hg.mozilla.org/releases/mozilla-esr60/raw-file/2e5dac0cdbee167d6b302aae5645f0f1a67c721d/browser/app/profile/firefox.js](https://hg.mozilla.org/releases/mozilla-esr60/raw-file/2e5dac0cdbee167d6b302aae5645f0f1a67c721d/browser/app/profile/firefox.js)

apparently it is disabled by default on ESR60

**Comment by crssi** [comment]
My bad... didn't read good

> Huh? dom.serviceWorkers.enabled seems to be false by default in `ESR60 (and on ESR52)`.

Missed the "ESR" in. Sorry

**Comment by earthlng** [comment]
Hi, yes 2 prefs have different default values in ESR60: `dom.push.enabled` + `dom.serviceWorkers.enabled` - both are default `false` in ESR and `true` in non-ESR.

> I'm not sure what should not work about google street view, but it looks ok here.

Thanks for letting us know. That warning is apparently a remnant from when `dom.workers.enabled` still existed.

@Thorin-Oakenpants IDK what you want to do here but I'd copy that warning line to the deprecated pref and change the one in the 2300 header from "will" to "might" and remove the example sites.

**Comment by Thorin-Oakenpants** [comment]
Its ambiguous. IDK if the original "workers" meant `dom.workers.enabled` (deprecated), or "workers" in general (workers, service workers, etc) - if it was the former why wasn't it with the deprecated pref to start with.

Fun fact: disabling features *might* break sites! I guess the warning was there for troubleshooting.
