### ISSUE TITLE
discussion: redo 2800s shutdown

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#45]
The shutdown section needs a some love. Using words like "stuff" in 2803 is lame. I'm also not happy with the 2803a and 2804a numbering. Those 2 prefs need to be clarified exactly what they are doing as well. Especially 2803a, because we are shutting down, so how can that differ from what is already in 2803. As for 2804a, does it close current tabs/windows (but leave FF open) or what. I need to do some testing in a nilla FF.

Also, the section header could expanded a tad to explain clearing session data vs keeping it - a bit like the new 0800 (forms etc) section.

**Comment by Atavic** [comment]
/* 2802: enable options to clear FF stored data on close
* [SETTING] Options>Privacy>Clear history when Firefox closes ***/

/* 2803: list of items to clear on shutdown
* [SETTING] Options>Privacy>Clear history when Firefox closes>Settings ***/

**Comment by earthlng** [comment]
> Those 2 prefs need to be clarified exactly what they are doing as well

They are not available in the GUI so maybe they will get removed soon or who knows.
As far as I'm concerned they are there for completeness sake and if some end-user feels like enabling/testing them, they are free to do so. The pref-names are already pretty self-explanatory so IMO they don't need any more clarification.

> Also, the section header could expanded a tad to explain clearing session data vs keeping it

Honestly I like it the way it is - it's pretty clear what it does. But if you think you can make it better then by all means. better is always better.
I sometimes thought if it wouldn't be better to move f.e. the 2 cookie-prefs into the cookie section, etc.
It would make more sense in a way, but it's also nice to have them all together. maybe something to think about.

**Comment by Roman-Nopantski** [comment]
> The pref-names are already pretty self-explanatory so IMO they don't need any more clarification.

`privacy.clearOnShutdown.openWindows` - we are shutting down, what does an open window have to do with anything? We are closing all windows and clearing out types of history/data and ending the firefox.exe. I do not understand what this pref achieves.

`privacy.cpd.openWindows` - same story. We run Clear>History>Everything .. and it clears types of retained data/history. It ALREADY clears the open windows/tabs. Do a test with cache .. leave the window open with a loaded site, clear the cache, inspect the cache - its empty. Again, I do not understand what this pref achieves

I guess I'll go look at the DXR code. I suspect these are legacy.

**Comment by Roman-Nopantski** [comment]
> Honestly I like it the way it is - it's pretty clear what it does. But if you think you can make it better then by all means. better is always better.

Well, you did a patch proposal earlier, so this is me revisiting that. And I agree, as per your patch, the numbering was crap, but you also changed the wording (of the *a prefs), and it totally changed the meaning of what the pref did. So it needs clarifying.

> I sometimes thought if it wouldn't be better to move f.e. the 2 cookie-prefs into the cookie section, etc.
It would make more sense in a way, but it's also nice to have them all together. maybe something to think about.

Yeah, we could move cookie ones to cookie section, form ones to form section - but then we also have to move all the cpd ones as well. This is way easier for people to follow and set in one place, just like the UI does. We also have a startup, and this shutdown - which is a nice symmetry

**Comment by Just-me-ghacks** [comment]
> when I enable them, I get weird behavior when restarting, due to an addon no doubt - eg if I enable 2803a, on restart I get two window launches
Same thing here. I don't think it's an addon related issue.

**Comment by Roman-Nopantski** [comment]
> Same thing here. I don't think it's an extension related issue.

When I last tested 6 months or so ago in a nilla FF (portable), I didn't get the same double launch behavior. I am not sure if I loaded the user.js or not. Maybe it's a combination of settings. Will test again before this ticket is done. And look at the DXR code where useful comments can lurk

**Comment by Atavic** [comment]
- `privacy.clearOnShutdown.openWindows`

Is related to the Sessions Recovery that has been killed.
In  K-Meleon Browser there's a Menu entry _Sessions > Undo Last Closed_.
If the entry value is true, you can't restore any session.

- `privacy.cpd.openWindows` and `privacy.cpd.siteSettings`

Both entries are **not** available if you click on _Settings_ in _about:preferences#privacy_

The available choices are
```
browsing & download
cookies
login
cache
form & search history
prefs
offline data
```
and once picked, turn the entries in about:config to true, while those two entries remain set to false.
Bad choices?

**Comment by Roman-Nopantski** [comment]
Oh wow .. what timing .. just been doing this and your post showed up. So .. my findings:

`privacy.clearOnShutdown.openWindows` (2803a) is not used: see https://dxr.mozilla.org/mozilla-central/search?q=privacy.clearOnShutdown.openWindows&redirect=false . The default is false. This pref can be removed. This confirms Atavic's findings

more to follow

**Comment by Roman-Nopantski** [comment]
`privacy.cpd.openWindows` - same story, it's not even used - https://dxr.mozilla.org/mozilla-central/search?q=privacy.cpd.openWindows&redirect=false

I knew those two seemed strange - the descriptions didn't fit.

**Comment by Roman-Nopantski** [comment]
see https://dxr.mozilla.org/mozilla-central/source/browser/base/content/sanitize.js#664

Interesting that Ctrl-Shift-Del 's time range to clear's dropdown only lists 5 items, but the code has 7. Values 5 and 6 work, I just tested (besides the code looks sweet). When set to those values, the dropdown is blank in the dialog

**Comment by Roman-Nopantski** [comment]
cpd
![untitled-cpd](https://cloud.githubusercontent.com/assets/16656956/23817209/39878c0e-0656-11e7-865e-23d03b35d450.png)

preference ui
![untitled-prefs](https://cloud.githubusercontent.com/assets/16656956/23817226/57e91c08-0656-11e7-9329-a0772b16b96d.png)

**Comment by Roman-Nopantski** [comment]
cpd: I see 7 items listed in the gui, but 9 in the prefs list
`privacy.cpd.downloads` and `privacy.cpd.history` are combined. Passwords is not listed

prefs ui: I see  7 items listed, but 8 in the prefs.
`privacy.clearOnShutdown.downloads` and `privacy.clearOnShutdown.history` are combined in the gui. Unticking the checkbox and applying the change, alters these two values in tandem. No idea what happens if they are set at different values in the js.

**Comment by Roman-Nopantski** [comment]
As confirmed by my tests: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/sanitizeDialog.js#193

```js
 // Keep the pref for the download history in sync with the history pref.
    document.getElementById("privacy.cpd.downloads").value =
      document.getElementById("privacy.cpd.history").value;
```

**Comment by Roman-Nopantski** [comment]
ditto for OnShutdown: https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/sanitize.js#16.

```js
onClearHistoryChanged() {
 let downloadsPref = document.getElementById("privacy.clearOnShutdown.downloads");
 let historyPref = document.getElementById("privacy.clearOnShutdown.history");
 downloadsPref.value = historyPref.value;
 }
```

**Comment by Roman-Nopantski** [comment]
CPD is always synced, because as soon as you open the dialog, they are forced the same as the history value. But shutdown has no trigger, and the same rules do not apply.

Patch for nits/comments
```js
/*** 2800: SHUTDOWN [SETUP]
    These values are a balance between convenience vs privacy. You should set the values
     to what suits you best. Our default settings contain no nasty surprises: We do not
     clear your passwords, or site settings, or even cookies (use an extension for that).
     [NOTE] In both 2803 + 2804, the 'download' and 'history' prefs are combined in the
     firefox interface as "Browsing & Download History" and their values will be synced
 ***/
user_pref("ghacks_user.js.parrot", "2800 syntax error: the parrot's bleedin' demised!");
/* 2802: enable Firefox to clear history items on shutdown
 * [SETTING] Options>Privacy>Clear history when Firefox closes ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
/* 2803: set what history items to clear on shutdown
 * [SETTING] Options>Privacy>Clear history when Firefox closes>Settings
 * [NOTE] If 'history' is true, downloads will also be cleared regardless of the value
 * but if 'history' is false, downloads can still be cleared independently
 * However, this may not always be the case. The interface combines and syncs these
 * prefs when set from there, and the sanitize code may change at any time ***/
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.downloads", true); // see note above
user_pref("privacy.clearOnShutdown.formdata", true); // Form & Search History
user_pref("privacy.clearOnShutdown.history", true); // Browsing & Download History
user_pref("privacy.clearOnShutdown.offlineApps", true); // Offline Website Data
user_pref("privacy.clearOnShutdown.sessions", false); // Active Logins
user_pref("privacy.clearOnShutdown.siteSettings", false); // Site Preferences
/* 2804: set what history items to clear with Ctrl-Shift-Del (to match above)
 * This dialog can also be accessed from the menu History>Clear Recent History
 * [NOTE] regardless of what you set privacy.cpd.downloads to, as soon as the dialog
 * for "Clear Recent History" is opened, both values are set to the same as 'history' ***/
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", false);
  // user_pref("privacy.cpd.downloads", true); // not used, see note above
user_pref("privacy.cpd.formdata", true); // Form & Search History
user_pref("privacy.cpd.history", true); // Browsing & Download History
user_pref("privacy.cpd.offlineApps", true); // Offline Website Data
user_pref("privacy.cpd.passwords", false); // this is not listed
user_pref("privacy.cpd.sessions", false); // Active Logins
user_pref("privacy.cpd.siteSettings", false); // Site Preferences
/* 2805: reset default 'Time range to clear' for 'Clear Recent History' (see 2804)
 * Firefox remembers your last choice. This will reset the value when you start Firefox.
 * 0=everything, 1=last hour, 2=last two hours, 3=last four hours
 * 4=today, 5=last five minutes, 6=last twenty-four hours
 * [NOTE] The values 5 + 6 are not listed in the dropdown, which will display a
 * blank value if they are used, but they do work as advertised ***/
user_pref("privacy.sanitize.timeSpan", 0);
```

**Comment by earthlng** [comment]
> privacy.clearOnShutdown.openWindows (2803a) is not used
> privacy.cpd.openWindows - same story, it's not even used

That's not true at all. Look at what both you and Just Me have said. That should make it pretty clear already that it DOES something. And I thought you'd know by now that you can't always just search DXR for the full pref-name and make assumptions based on that. see [here](https://dxr.mozilla.org/mozilla-central/search?q=openWindows&redirect=false) - that's how you need to search. If it finds too many results you may need to figure out a better way, but mostly this works just fine.

I'll repeat what I said earlier:

> They are not available in the GUI so maybe they will get removed soon or who knows.
> As far as I'm concerned they are there for completeness sake and if some end-user feels like enabling/testing them, they are free to do so. The pref-names are already pretty self-explanatory so IMO they don't need any more clarification.

Plus they are commented out, or have been so far, so it won't impact the dumbasses who don't bother to read any of our Notes and shit. (see reddit.com/r/firefox for some recent examples of such people)

I don't mean to insult anyone and I realize this comment is a bit rude, but with all due respect I really think it's a waste of time re: openWindows

**Comment by earthlng** [comment]
Please don't feel insulted - you did some nice work and testing here. But you also made an outright false statement - but it's not the end of the world - we all make mistakes. Do you not want me to correct false statements or point out mistakes? No need to make this wontfix. I doubt you still care about my nits/comments, but I'll give them anyway.

> Patch for nits/comments

> Our default settings contain no nasty surprises

Clearing the history can be quite nasty - as some earlier comments on ghacks have clearly shown.
Our default settings reflect the way that YOU are using them but if someone doesn't know why and what exactly your way is (fe. block all cookies, allow cookies per domain in siteSettings, and hence don't clear those out) it's just confusing. Pylly has it easier because they can clear everything, while our approach is just not very clear. For example I feel we could make all the cpd's true by default so they'll all be pre-checked. Do you know what I'm trying to say here?

> [NOTE] The values 5 + 6 are not listed in the dropdown

0 is better than 5 or 6, and since they are not in the UI (yet?), it's neat to have that info but it can also be a problem if someone fe. sets that pref to 6 and then one day that doesn't do anything anymore. If it's not in the UI we shouldn't encourage or even point out that there are "hidden" values. You know what I mean?

The rest is okay, except the removal of openWindows for completeness sake, but they are default false anyway in FF, so yeah, zero fucks given. (our new motto 'member)

Sorry if I shut you down with a single comment after all the testing and research you did.
We can try to make this as fool-proof as possible but honestly the fools don't read it anyway.

**Comment by Roman-Nopantski** [comment]
> Clearing the history can be quite nasty

I tried to work that in. But you know what, history is not a life an death experience. Losing all your passwords is. And that *one* guy at ghacks was a trolling

**Comment by earthlng** [comment]
.... and I just feel that while all the additional info may be nice to people who care to read them, it also blows up the size of the file and makes it even more unlikely that the people who don't read it will do so.

**Comment by earthlng** [comment]
I value my history quite a bit that's all I can say

re: reddit:
https://www.reddit.com/r/firefox/comments/5yh4x2/i_used_the_brinkman_privacy_and_security_settings/
https://www.reddit.com/r/firefox/comments/5ympy0/this_time_i_found_a_userjs_that_doesnt_brick_my/

**Comment by Roman-Nopantski** [comment]
Wiping someone's passwords is unforgivable (even if the end user should have them stored in a digital wallet, or have backups), and it happened to someone who used PKs (and he had a backup). Wiping someone's site settings is shitty (lots of custom zoom levels or specific permission overrides) but not he end of the world. Wiping someone's cookies and active logins, not such a big deal (they can log in again). Wiping their history, to me, is probably neither here nor there - depends on the user.

I don't know how many times I have to say SETUP or template, but at some point I am going to draw a line. To me a nasty surprise is wiping passwords or site settings. I even mentioned cookies and pointed out using an extension to reinforce what is said in the readme, on the addon page, in various sections (about using extensions to get better control and convenience). So due to trying to keep the setup small, the one thing I didn't say was history (which we do clear). Well fark. I'll rewrite it, even though the second sentence says to set the values to what suits them. People need to learn to read.

---
"0 is better than 5 or 6" - what does that mean? It is set at 0. If someone keeps wondering why their dialog is always time to clear: <blank>, then that;'s on them. People need to learn to read.

---
The two openWindow prefs do NOTHING that the others already do in terms of sanitizing. I didn't say they didn't cause a change in app behaviour. And I don;'t know if you know, but I am no longer a developer/coder .. I stopped "coding" applications 20 years ago, among many other talents. Been there done that. I am not a code monkey, ok. Even back then, it wasn;t that much - I spent all my time in Information Systems, Database Warehousing/Design/Admin etc. I think I do pretty damn well for a 90 year old. I actually went all over that sanitize js and followed the logic and I cannot in all honesty see how sanitizing open windows on shutdown achieves anything. the cpd one would make sense, but it doesn't behave as expected if it did. And yes, I read the code and saw the comment. Give me some credit for being able to find the relevant sections.

PS: did YOU know they were introduced in 34? I did. Now tell me EXACTLY what they do then. This is your code domain, your expertise. Not mine.

I am still 99% convinced the prefs are useless and a waste of time, especially the onshutdown. Never liked - stuck in in because you brought them up twice, as did ainatar, in your lists on ghacks. Chucked them in as an afterthought for 11, because I'm nice like that. Couldn;t find anything about them, could work out what they achieved in testing, can't find anything about them in searches. So here we are to clean em up, because they bug me.

So by all means, demonstrate what they do.

**Comment by Roman-Nopantski** [comment]
> They are not available in the GUI so maybe they will get removed soon or who knows.

They have never been in the GUI. They were introduced in FF34. The cpd panel and custom history clear on shutdown forms were introduced in FF18 or so. The only change in the UI in all that time has been passwords. I can provide screenshots if you want.

**Comment by earthlng** [comment]
> I didn't say they didn't cause a change in app behaviour.

Sorry but that's exactly what you said. You linked to 2 DXR searches that both didn't list the parts where it DOES something. If that's not what you **meant** - sorry, I can't read your mind either.

> ... the prefs (openWindow) are ... a waste of time

that's what I said from the get-go. I don't know exactly what they do and I don't care what they do - I know whatever it is, it's NOT something I WANT so therefore I have them set to false in my own user.js - for completeness sake and just in case they ever get added to the UI or set to true by default by mozilla.

> stuck in in because you brought them up twice, as did ainatar

That's exactly why I would keep them in, too - so nobody will ever bring them up again for inclusion or asking about them. IMO it can be as simple as

```js
/* 28xx: *.openWindows ***/
user_pref("privacy.clearOnShutdown.openWindows", false);
user_pref("privacy.cpd.openWindows", false);
```

or even:

```js
/* 28xx: *.openWindows
    [NOTE] figure it out for yourself - zero fucks given ***/
```

zero fucks given! include them or not, set them to false or not - zero fucks given - it's a waste of time. period.

**Comment by Roman-Nopantski** [comment]
I take that back (its nowhere near FF18, not sure what I was thinking).. here's a screenshot from FF4 for nostalgia's sake. Only passwords has been removed. The cpd panel hasn;t changed one bit

![untitled-2](https://cloud.githubusercontent.com/assets/16656956/23824502/daba5f4e-06dc-11e7-82e4-60a64a2cc85a.png)

**Comment by Roman-Nopantski** [comment]
```js

/*** 2800: SHUTDOWN [SETUP]
     These values are a balance between convenience vs privacy. You should set the values
     to what suits you best. Be aware that our default settings clears browsing and downlaod
     and form history, but not cookies (we expect you to use an extension).
     [NOTE] In both 2803 + 2804, the 'download' and 'history' prefs are combined in the
     firefox interface as "Browsing & Download History" and their values will be synced
 ***/
user_pref("ghacks_user.js.parrot", "2800 syntax error: the parrot's bleedin' demised!");
/* 2802: enable Firefox to clear history items on shutdown
 * [SETTING] Options>Privacy>Clear history when Firefox closes ***/
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
/* 2803: set what history items to clear on shutdown
 * [SETTING] Options>Privacy>Clear history when Firefox closes>Settings
 * [NOTE] If 'history' is true, downloads will also be cleared regardless of the value
 * but if 'history' is false, downloads can still be cleared independently
 * However, this may not always be the case. The interface combines and syncs these
 * prefs when set from there, and the sanitize code may change at any time ***/
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.clearOnShutdown.downloads", true); // see note above
user_pref("privacy.clearOnShutdown.formdata", true); // Form & Search History
user_pref("privacy.clearOnShutdown.history", true); // Browsing & Download History
user_pref("privacy.clearOnShutdown.offlineApps", true); // Offline Website Data
user_pref("privacy.clearOnShutdown.sessions", false); // Active Logins
user_pref("privacy.clearOnShutdown.siteSettings", false); // Site Preferences
   // user_pref("privacy.clearOnShutdown.openWindows", false); // (FF34+)
/* 2804: set what history items to clear with Ctrl-Shift-Del (to match above)
 * This dialog can also be accessed from the menu History>Clear Recent History
 * [NOTE] regardless of what you set privacy.cpd.downloads to, as soon as the dialog
 * for "Clear Recent History" is opened, it is synced to the same as 'history' ***/
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", false);
   // user_pref("privacy.cpd.downloads", true); // not used, see note above
user_pref("privacy.cpd.formdata", true); // Form & Search History
user_pref("privacy.cpd.history", true); // Browsing & Download History
user_pref("privacy.cpd.offlineApps", true); // Offline Website Data
user_pref("privacy.cpd.passwords", false); // this is not listed
user_pref("privacy.cpd.sessions", false); // Active Logins
user_pref("privacy.cpd.siteSettings", false); // Site Preferences
  // user_pref("privacy.cpd.openWindows", false); // (FF34+)
/* 2805: reset default 'Time range to clear' for 'Clear Recent History' (see 2804)
 * Firefox remembers your last choice. This will reset the value when you start Firefox.
 * 0=everything, 1=last hour, 2=last two hours, 3=last four hours
 * 4=today, 5=last five minutes, 6=last twenty-four hours
 * [NOTE] The values 5 + 6 are not listed in the dropdown, which will display a
 * blank value if they are used, but they do work as advertised ***/
user_pref("privacy.sanitize.timeSpan", 0);
```

**Comment by Roman-Nopantski** [comment]
All this bitching because people dump huge lists on us and expect us to deal with them. Even you don't know what they do - I just think they's BS and don't deserve to be mentioned let alone listed. We're going have people ask us now, why are those commented out. I'll refer them to you xD

**Comment by earthlng** [comment]
```js
/* 2805: privacy.*.openWindows ***/
user_pref("privacy.clearOnShutdown.openWindows", false);
user_pref("privacy.cpd.openWindows", false);
```
renumber 2805 (privacy.sanitize.timeSpan) to 2806, and we can prepare a saved reply with:

```
re: privacy.*.openWindows
We don't know what it does and we don't care what it does. It's there for completeness sake.
If it sounds like something you may want to use, start here: https://startpage.com/
```

> We're going have people ask us now, why are those commented out. I'll refer them to you xD

no need for that anymore if we use my proposal. Nuff said - take it or leave it - zero fucks given :)

**Comment by Roman-Nopantski** [comment]
```js
/* 2805: privacy.*.openWindows (FF34+)
 * We don't know what they do and we don't care what they do ***/
user_pref("privacy.clearOnShutdown.openWindows", false);
user_pref("privacy.cpd.openWindows", false);
```
done
