### ISSUE TITLE
Q: How to resize window on start?

### ISSUE THREAD

**Issue by quantizzed** [ghacksuserjs/ghacks-user.js#453]
With RFP turned on Firefox does not remember the window size and always starts with the same window size (and position). Is there any way to start Firefox with a predefined window size other than manually executing window.resizeTo() in Scratchpad?

**Comment by claustromaniac** [comment]
See #449.

**Comment by Thorin-Oakenpants** [comment]
see the prefs in `4502`

**Comment by Pilford** [comment]
I use another trick (for FF 61):

right click FF icon on taskbar
again right click FF icon => Properties => Run: Maximized

It’s not completely maximized, but it’s close.

**Comment by quantizzed** [comment]
Aha, thanks, the first solution is OK with me.
