### ISSUE TITLE
"run_at":"document_start" seem to be broken [1479059 and more]

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#466]
https://bugzilla.mozilla.org/show_bug.cgi?id=1479059

1 clone https://github.com/KOLANICH/run_at_document_start_doesnt_work.git
2 read the code
3 install the extension
4 open the page
5 report the results

For me:
most of the time
```
test1 broken
test2 broken
```

only sometimes test1 succeds.

**Comment by Thorin-Oakenpants** [comment]
Sorry, been uber busy. We know that for Greasemonkey and ViolentMonkey there are issues with run at doc start. Its why we abandoned one of our scripts ( https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts - and yup, big warning at the top of the page ) , the `clear window.opener` one (scroll down) in favor of an extension that earthlng wrote

Not whole ins and outs of who GM & VM have issues with this, and how TM (tampermonkey) uses some hanky BS or something (don't care about TM, screw them) is discussed and documented all over their github issues. GM were getting close to a solution I think. All over my head, TBH.

But it is a problem. If anything I would get the GM and VM guys involved, or there may even be some other tickets open.

**Comment by KOLANICH** [comment]
I guess it may be possible to workaround that by delaying page and its scripts load untill the success message came from the script by using webRequests, but I don't think this should work this way. IMHO the only point to have `document_start` is to have guaranties that our scripts end their execution strictly before any of the page content started execution and this must work for both scripts hardcoded  into manifest and run using `executeScript` on `onCommitted`. No matter that this may slow down browsing a bit, if a user installs these kind of extensions, it's his decision.

**Comment by Thorin-Oakenpants** [comment]
I agree with the sentiment - we/you shouldn't have to use hacks or workarounds - the advertised product should do what it says on the box

**Comment by KOLANICH** [comment]
Mozilla's QA have verified existance of the bug.

**Comment by KOLANICH** [comment]
There was an error in my test for static script.
