### ISSUE TITLE
Cleaner and Updater scripts: is this a bug?

### ISSUE THREAD

**Issue by RoxKilly** [ghacksuserjs/ghacks-user.js#467]
I am unable to get either the cleaner script or the updater script to affect the following prefs:
```
user_pref("browser.urlbar.autocomplete.enabled", true);
user_pref("browser.urlbar.suggest.history", true);
user_pref("browser.urlbar.suggest.bookmark", true);
user_pref("browser.urlbar.suggest.openpage", true);
```

To reproduce the cleaner script behavior, this is what I did:
* Starting from a browsing profile already modified with a previous version of ghacks-user-js
* Exit the browser (FF 61 x64 portable)
* Put v61-beta ghacks-user-js in the profile directory
* Put the cleaner script v2.1 in the profile directory and run it
* Restart the browser and checkout `about:config`
Result: although the settings above are present in the user.js, they were not cleared from browser prefs.  They still show (well definitely the first one) as user-modified and set to `true`.

To reproduce the updater script behavior, this is what I did:
* Go through all the steps above
* Exit the browser
* place user-overrides.js in the user profile with the following (among other lines)
```
//// --- comment-out --- 'browser.urlbar.autocomplete.enabled'
//// --- comment-out --- 'browser.urlbar.suggest.history'
//// --- comment-out --- 'browser.urlbar.suggest.bookmark'
//// --- comment-out --- 'browser.urlbar.suggest.openpage'
```
* Run updater script v4.5 from within the user profile
Result: although the contents of my overrides are correctly appended to user.js, the matching lines are not commented out.

So after running both the cleaner script and the updater script (they both completed without visible errors), these 4 settings remain unaffected.

Can anyone reproduce?  Am I missing something?

**Comment by earthlng** [comment]
Can't reproduce. Did you check the prefs.js after running the prefsCleaner to see if they're still there?
Maybe something else is setting them again (or at least the 1st one), IDK.

Commenting out prefs with the updater only works with the `-merge` switch, I guess you didn't use that?

**Comment by Thorin-Oakenpants** [comment]
> Cleaner script behavior ... Put v61-beta ghacks-user-js in the profile directory ... They still show (well definitely the first one) as user-modified and set to true.

Umm, all four prefs are active and set to false in the user.js, so they will not be cleared from prefs.js

PS: anything "set" from a user.js will be "user set / modified" regardless of the value used (default or not)

**Comment by RoxKilly** [comment]
@earthlng  thanks for the tip about `-merge`.  I thought it was the default behavior; didn't realize I needed to proactively set that flag.

@Thorin-Oakenpants I expected the preferences to be removed from prefs.js when I run the cleaner script.  Isn't the point of that script to look at everything set in user.js and to remove it from prefs.js?

I decided to start with a fresh profile folder and try to reproduce.  Long story short, I probably did something wrong before, or something else changed that setting as @earthlng wondered. My steps this time:

* move existing profile folder
* start FF -- new profile folder is created, first run "welcome" experience shown
* in about:config, verify that `browser.urlbar.autocomplete.enabled` is at default (true)
* exit FF
* Check prefs.js: no autocomplete setting.
* Put latest user.js (61-beta) in profile folder
* Relaunch firefox: `browser.urlbar.autocomplete.enabled` is now false
* exit FF
* Check prefs.js: the "false" setting was added
* Run Prefs cleaner 1.2 from profile folder (successfully)
* Check prefs.js: the "false" setting was removed!
* Put user-overrides.js in profile folder with contents: `//// --- comment-out --- 'browser.urlbar.autocomplete.enabled'`
* Run updater 4.5 from profile folder (successfully)
* Check user.js: the setting is still live (line was not commented out).
* Thanks to @earthlng, I thought to run updater with `-merge` flag, and the line was properly commented out in user.js

So think I'm all set. Feel free to close.

**Comment by Thorin-Oakenpants** [comment]
>  I expected the preferences to be removed from prefs.js when I run the cleaner script. Isn't the point of that script to look at everything set in user.js and to remove it from prefs.js?

Yes. But as soon as you open FF, active prefs get set again

**Comment by RoxKilly** [comment]
Ah I see. Understood.
