### ISSUE TITLE
ESR52.x EOL: one month to go gals (and guys)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#468]
Are all you ESR52.x peeps ready for the transition to ESR60.2 (or FF62) when your beloved XUL compatible build reaches EOL on Sept 5th?

How will you go about it? The transition that is. Besides backing up your profile.
- Will you do a clean install and start from scratch (obviously you would have a user.js, and be able to export most extension settings such as uM, uBO, CanvasBlocker). Some extensions have new features since the legacy ones, so a simple export/import will not suffice
- Just update FF, then one by one update each legacy extension to web ext and re-enable/test?

Personally (but I do not have to go thru this, because I did all my hard yards riding the bumpy trains), I would create a pristine new profile.

Will you lose (or survive the loss of) any workflow that a legacy ext provided - A lot has been added to the APIs since 57, but its still lacking compared to XUL.

Speak up or the :hamster:   gets it

PS: @fmarier Obviously I am not fully conversant on this, and I can see arguments from both sides, and I assume this is covered under telemetry (its a Shield Study at this stage), but **damn* .. collecting telemetry from PB mode users means you can no longer say that you do not, which I find very sad.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1477042

**Comment by Just-me-ghacks** [comment]
FF52@WinXP
FF6x@Win7

No installs. No updates. No cleaning. I use a brand new profile for every browsing session (thanks to FF portable). 

My FF52 extensions are available for FF6x so workflow won't change much. Thanks to this repository I fell ready for all kind of sh*t.

Did you receive my email a few days ago?

**Comment by Thorin-Oakenpants** [comment]
> Did you receive my email a few days ago?

Nope :-( .. I just sent you an email to c___a__m_2016@a_v.__  if that's enough of a hint with the substituted underscores. Use that email account, as it's my main one. The other one you used to send to, I do check (its just a fallback email provided by my ISP), but maybe your email got blocked

**Comment by Thorin-Oakenpants** [comment]
>  I use a brand new profile for every browsing session (thanks to FF portable).

That doesn't make sense. If there is no FF portable profile dir, then FF creates ones when you open it. You would **then** have to close FF and add the user.js to the new profile dir get any benefit from it. Plus a new profile would have no extensions in it (and browsing with at least uBO with some default filters is sacrilege).

FF is perfectly capable of storing zero persistent data. You can set CA to memory only, same with site permissions and AFAIK, everything else can be sanitized on close.

What am I missing here? What benefit does a new profile every session do? Makes no sense :headscratch:

**Comment by Just-me-ghacks** [comment]
Extract FF portable to a folder. Configure. Connect to the Internet. Browse. Delete the folder. Repeat.

> FF is perfectly capable of storing zero persistent data.

What if Mozilla creates a unique profile ID?

**Comment by Thorin-Oakenpants** [comment]
OK, got your email. Will reply in a day or so.

My point is why waste all that time configuring a profile *each time*. Sounds labor intensive. Even if you set up a clean profile (and add extensions, and configure them, and add a user.js, etc) before you use it - it would be easier in my opinion to copy that profile as a master, and just restore a copy of it to profile before each session.

Mozilla does not create a unique profile ID. There is a throwback to thunderbird code, but it is not used.

**Comment by Just-me-ghacks** [comment]
If Mozilla does not create a unique profile ID: extract FF portable to a folder. Configure. RAR the folder. Connect to the Internet. Browse. Delete the folder. Extract the RAR.

Delete everything and repeat from start when a new version of FF is released.

**Comment by Atavic** [comment]
I'll create a new profile, too.

**Comment by Thorin-Oakenpants** [comment]
You know you can run and create a Firefox portable 61 right now, and start setting it up, right?

**Comment by earthlng** [comment]
I already migrated to Dev-Edition. Just copied my profile folder into the new profile and let FF do its thing. It auto-deleted all my legacy extensions including all the configs and I had to reconfigure uBO, uMatrix and Greasemonkey. But I still had ESR with my original profile installed and working so I just had to copy-paste the settings and slightly merge them with some of the new settings and defaults.

What I'm mainly missing now is a good mouse-gesture extension, a NoRedirect replacement and the ability to see requests made by other extensions due to webextensions API limitations.

**Comment by Thorin-Oakenpants** [comment]
I found I had some manually cleaning to do. Extension leftover files, extension storage, extension about:config entries (which bloat your prefs.js)

I still have some remnants in about:config (toolbar placement for old icons etc), but generally speaking my profile is pretty much squeaky clean, and its about 4 years old (I think)

> a NoRedirect replacement

I hear ya!

> and the ability to see requests made by other extensions due to webextensions API limitations

Yup, this is problematic .. now kkapsner is filing bugzillas and maybe we'll get some traction. Rolling the dice is not how I want to go thru life. I prefer to bet on a sure thing. Hence I'm trying hard AF to not have extensions that conflict in this area (but they probably do)

**Comment by Thorin-Oakenpants** [comment]
> It auto-deleted all my legacy extensions including all the configs and I had to reconfigure uBO, uMatrix and Greasemonkey

Not sure about GM (because it wasn't ready when I did mine, so I went with VM), but uBO and uM had hybrid versions. In order to not lose anything, you can to upgrade to these first, then to the pure web ext. Otherwise you could just export it all, import it all.

**Comment by earthlng** [comment]
> I found I had some manually cleaning to do.

I only keep certain select files in my profile permanently anyway and didn't have much cleaning to do. And most of the leftovers simply don't do anything anymore and getting rid of them is nice but not strictly necessary.

> you were meant to upgrade to these first

I wanted to keep my ESR profile unmodified with the versions I already had installed

> you could just export it all, import it all

yeah but there were some changes made to the default settings in uBO and uMatrix and export+import would have overwritten them

> Rolling the dice is not how I want to go thru life

yeah that's a problem but not what I meant. ATM extensions don't see requests **made** by other extensions, fe updates to blocklists etc, whereas with legacy extensions they saw everything and were able to log/block it. The rolling the dice thing is about header modifications

**Comment by Thorin-Oakenpants** [comment]
> And most of the leftovers simply don't do anything anymore

Yeah, but I'm anal about being tidy :)

> yeah but there were some changes made to the default settings in uBO and uMatrix and export+import would have overwritten them

They're always being changed. But yeah, I had issues with those as well. I actually ended up with a clean install anyway (due to legacy ext + web exts not working nicely and all those weird bugs eg images not displaying etc)

> yeah that's a problem but not what I meant

Ooh. That one. Yeah, I still occasionally monitor traffic. The worse one when migrating was FVD Speed Dial. uBo/uM would block the requests for the icons from google/s3 something. And I mean every dial, on every tab focus where speed dial was open, would request an icon (even though I already had one and in fact they were disabled). As soon as uBo/uM went to web ext, I had to ditch it. The FVD dev wasn't interested in fixing it, and their web ext was a complete :hankey: anyway. Went with Group Speed Dial and some userContent.css tweaks to overcome shortcomings.

But yeah, I do kinda like that extensions can't mess with each other, but then it has its drawbacks. I assume you can still see everything in networking dev tools (I'm never in there).

**Comment by Thorin-Oakenpants** [comment]
PS: headups on mixing profiles & versions: https://blog.mozilla.org/addons/2018/08/03/new-backend-for-storage-local-api/

**Comment by earthlng** [comment]
^^ yeah about that... I think it's time to either remove the IDB pref or enforce it to true (and change the title and explanation). More and more stuff will, or already does, use IDB: Activity Stream, some extensions for parts of the configs, some of FF's blocklists were already moved to IDB and soon **all** extensions settings will be stored in IDB's as well.

**Comment by earthlng** [comment]
> Ooh. That one. Yeah, I still occasionally monitor traffic.

for example lots of extensions on the Chrome store have google-analytics embedded and now there's no easy way to block those requests anymore. You can *see* them in devtools but they are hidden from extensions (for no good reason IMHO!)

**Comment by Thorin-Oakenpants** [comment]
I know, it sucks. That's why I only stick to our vetted and trusted devs and extensions - well, I do have about 4 not listed, but I totally put them under a microscope.

chrome store .. yup, well, screw chrome :)

>  IDB pref or enforce it to true

Kinda weird state at the moment. I mean PB mode can't even use it. And clearing IDB by host or time range (except time range everything) is still an issue. Comes down to strategy for now IMO - eg I block cookies which blocks IDB. Still, I agree with what you say. I'll add an item to the current diffs

**Comment by Thorin-Oakenpants** [comment]
Well, that was a fun chat. Enjoy the migration guys & girls.
