### ISSUE TITLE
something something something dark side: favicons

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#48]
from @Atavic 

> FF 52.0 ESR 
```
// Show favicons in web notifications.
pref("alerts.showFavicons", false);

// No Favicons, Thanks!
pref("browser.chrome.favicons, false);
```
> See [here](https://www.wilderssecurity.com/threads/mozilla-created-shortcuts-favicon-caching-windows.343315/) for `browser.shell.shortcutFavicons`

**Comment by Roman-Nopantski** [comment]
I tested `browser.chrome.favicons`->true (default) and dragged and dropped a shortcut for a weibsite I have never visited before in my life. It has the favicon in it.

I then set `browser.chrome.favicons`->false. I restarted firefox just in case. I went to another site I have never seen before in my life, dragged and dropped a website shortcut - and it still applied the favicon.

**Comment by Roman-Nopantski** [comment]
`browser.shell.shortcutFavicons` works regardless of your favicon cache
`browser.chrome.favicons` will still aplly the favicon if it already exists in your cache: `\profile\shortcutCache` folder full of .ico files
`alerts.showFavicons` I can't test. Where would I get a web notification from?

Before I add these, I need to understand what the privacy risks are here. I understand the windows shortcut one, but not the others exactly - not yet

**Comment by Roman-Nopantski** [comment]
Now I'm confused:

Steps to reproduce:
- Set `browser.chrome.favicons` ->false
- Go to random websites you have never seen in your life
  * https://www.randomactsofkindness.org/
    * I see a favicon in the tab (and bookmark if drag it to my toolbar), but no .ico is generated
  * http://www.strangebanana.com/generator.aspx
    * I see a favicon in the tab (and bookmark if drag it to my toolbar), but no .ico is generated
  * http://www.pointless.com/
    * i see NO favicon, I flip the pref and reload, I get the favicon (still no .ico generated). I bookmark it, still no .ico generated

So, what is up with the sites I see an icon? Are these not really favicons but like a emoji or something else?

**Comment by Atavic** [comment]
1st:
`<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">`
`<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">`

2nd:
`<link href="favicon.ico" rel="shortcut icon" />`

3rd: No icon link in source

**Comment by Roman-Nopantski** [comment]
I knew it would be something like that - cheers.

**Comment by Atavic** [comment]
2nd: It's an actual .ico file, MIME Type image/x-icon

**Comment by Roman-Nopantski** [comment]
So
- http://www.strangebanana.com/generator.aspx - used an favicon and it was displayed despite `browser.chrome.favicons`->false ( see: http://www.strangebanana.com/favicon.ico )

- http://www.pointless.com/ is using a favicon - see http://www.pointless.com/favicon.ico

**Comment by Roman-Nopantski** [comment]
from the link first post
> The shortcut file that is created will contain within it a string showing the full path to the icon file within your profile. That path may contain personal info and/or reveal something about your filesystem, mount points, etc that you wouldn't want put into all the shortcut files you create. 

Man. I think that's stretching it just a little. If they have hold of the shortcut, they are already in your system, unless the shortcuts are on a portable drive. The shortcuts themselves would probably be more revealing (metadata). Look, I totally buy into the separation of application and platform, but the quote is 4 years old (mozilla may have changed something, idk), and while, I appreciate TheWindBringeth was just raising some possible points... 

here's the contents of a shortcut in Windows7
```
[InternetShortcut]
URL=https://github.com/ghacksuserjs/ghacks-user.js/issues/48
IDList=
HotKey=0
IconFile=D:\Portable\FFVanilla\FF52\Data\profile\shortcutCache\iCET2gRyjpdPqJHxREPKUg==.ico
IconIndex=0
```
and here's the contents when `browser.shell.shortcutFavicons`->false
```
[InternetShortcut]
URL=https://github.com/ghacksuserjs/ghacks-user.js/issues/48
```
So, on Windows at least, it only leaks the browser based on the path. That's portable, not sure what an installed one does.

-----
> The storing of the favicons in the shortcutCache

Definitely worth adding. Its one of those [setup] ones - if your device is private/secure, then convenience might trump it for you. I for one, like the icons.

**Comment by earthlng** [comment]
> Steps to reproduce:

Have you restarted FF after setting it? If that doesn't fix it then `browser.chrome.favicons` is definitely not doing what I would expect it to do.

`\profile\shortcutCache` - I don't even have that folder (???) But I have cache enabled so maybe that's the reason it stores it somewhere else.

`browser.shell.shortcutFavicons` - I think we add it to the new 08xx section, set to false and active, fe. 0880+ for all 3 favicons prefs.
`browser.chrome.favicons` - set it to false and comment it out, because I too like the icons
`alerts.showFavicons` - has to do with notifications but IMO we should keep the Favicons stuff together, so add it as false and active (or inactive - zero fucks given ;)

**Comment by earthlng** [comment]
wait... 0800 doesn't seem like the right section. Maybe we need to split them up or can find a section where all 3 fit, idk. `browser.chrome.favicons` maybe fits under quiet fox or cache, but I assume with cache disabled it also doesn't store favicons, right?

> and here's the contents when browser.shell.shortcutFavicons->false

so you need to pull the url to the desktop or something for this? sorry I never do that so I don't have a clue.

**Comment by earthlng** [comment]
Sorry, I should just do my own testing instead of being lazy and asking dumb questions.

**Comment by Roman-Nopantski** [comment]
> I don't even have that folder (???) But I have cache enabled so maybe that's the reason it stores it somewhere else

Well hopefully its not **username**/appdata/something/something/**mozilla**/darkside

**Comment by Roman-Nopantski** [comment]
> so you need to pull the url to the desktop or something for this? sorry I never do that so I don't have a clue.

Yes. Just drag and drop the I for info from your urlbar to a folder, then view that link in an ide

**Comment by Roman-Nopantski** [comment]
just throwing it out there, maybe favicon can go under the cache section

**Comment by Atavic** [comment]
Pointless site has no icon link in source but the browser looks at http://www.pointless.com/favicon.ico if available. By adding an ETag header, Web Servers can fingerprint the browser. ETags allow tracking without cookies, and csan be defeated by cleaning the cache (but still work during th browser's session).

http://lucb1e.com/rp/cookielesscookies/

**Comment by earthlng** [comment]
during a browser session I have the same IP so ETags are irrelevant.
When I open the browser the next day with a different IP, first it loads my previous session completely from the cache. When I reload one of those tabs, I do so by using a FireGestures gesture to force-reload and it never includes the Etag in my request header that way.
Add to that, that I use PB for most of my browsing, and my startup normal window only has the pages I still need to read or something, Etag aren't such a big problem for me.

**Comment by Roman-Nopantski** [comment]
@earthlng But can't you use a nilla FF for these tests?

**Comment by earthlng** [comment]
> But can't you use a nilla FF for these tests?

sure, but do we even need to test this? I mean `browser.shell.shortcutFavicons` is a nice addition regardless,
`browser.chrome.favicons` we don't want to enable anyway but can still include it, and `alerts.showFavicons` is false by default but we can include it too. All we need is to figure out in which section to add them.
What is there to test? It's not our problem as far as I'm concerned.

**Comment by Roman-Nopantski** [comment]
All three belong in cache. If a favicon is generated, it is stored.

**Comment by Roman-Nopantski** [comment]
> What is there to test? It's not our problem as far as I'm concerned.

Probably nothing to test. First we need sites that are actually using favicons (so my test above site 1 was poked), then we need to work out sites that use the `<link href="favicon.ico" rel="shortcut icon" />` (so my site 3 was poked) but still wonder why it was still assigned (etags or whatever), and then we need sites that aren't in the cache, so I'll have to fart around with a portable. I think we know they work for `<link..` otherwise not our problem. So nothing to test I guess.

I still want to *know* what goes on (eg where the favicons are stored for various profiles - eg portable, installed, with+without cache enabled) and to be to properly explain the privacy issue. Then we just write em up I guess. We can just do a draft here and I'll add it to issue #51.

I propose all three be described as "disable favicon on X", and comment them all out

Option1
```js
/* disable favicons...  \profile\shortcutCache of .ico files ***/
   // user_pref("browser.chrome.favicons", false);
/* disable favicons in web notifications ***/
   // pref("alerts.showFavicons", false);
/* disable favicons on shortcuts, use the mozilla firefox icon instead ***/
   //user_pref("browser.shell.shortcutFavicons", false);
```

or

Option2
```js
/* disable favicons in firefox (chrome), web notifications (alerts) and shortcuts (shell)
 * these generate a cache.. blah blah ... cache is located here .. blah blah ***/
   // user_pref("browser.chrome.favicons", false);
   // pref("alerts.showFavicons", false);
   //user_pref("browser.shell.shortcutFavicons", false);
```

**Comment by Atavic** [comment]
`browser.chrome.site_icons`
http://kb.mozillazine.org/Browser.chrome.site_icons

**Comment by Thorin-Oakenpants** [comment]
@Atavic Thanks for bring up favicons. I will close this, since it will be fully explored and covered in #51 (and is in my rough draft already)

**Comment by Atavic** [comment]
The places.sqlite includes a number of tables as follows:
    moz_favicons - Favourite icons - including URL of icon 

http://kb.mozillazine.org/Places.sqlite#Deleting

**Comment by Atavic** [comment]
Stinky favicons fall under `behind-the-scene` requests in _uBlock Origin_ and can't be blocked with user made filters: https://github.com/gorhill/uBlock/issues/1732

**Comment by earthlng** [comment]
"can't be blocked with user made filters" ... 

> if behind-the-scene requests are **whitelisted**

ergo remove the whitelisting and block to your heart's content

**Comment by Atavic** [comment]
Yeah, I behind-the-scene requests are whitelisted as default there.

**Comment by earthlng** [comment]
Just add a `noop` rule that covers behind-the-scene requests (or only BTS requests), which will block all requests that match an entry in a filterlist and be happy. Then you can also block Favicons or whatever else falls under BTS.
My whitelist in uBO is empty and I only have two rules in My Rules:
```
no-remote-fonts: * true
* * * noop
```
and I use uMatrix to do all the granular control.
