### ISSUE TITLE
it's a trap!: full screen browser window

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#49]
>"Maximizing Tor Browser can allow websites to determine your monitor size, which can be used to track you. We recommend that you leave Tor Browser windows in their original default size."

http://whatsmy.browsersize.com/
http://browserspy.dk/screen.php

If you run browser in full screen mode, then you are giving away your monitor resolution.

**Comment by Roman-Nopantski** [comment]
```js
/* 2418: disable full-screen API
 * This setting WAS under about:permissions>All Sites>Fullscreen
 * [NOTE] about:permissions is no longer available since FF46 but you can still override
 * individual domains: use info icon in urlbar etc or right click on a web page>view page info
 * set to false=block, set to true=ask ***/
user_pref("full-screen-api.enabled", false);
```
This stops sites you switch to full screen.
We also have (2203) `dom.disable_window_move_resize`->true
And, commented out, we have (2204) forcing new windows (which can specify a size) to open in a new tab

Unfortunately, there is no preference for `human.do.not.use.fullscreen`. It's also problematic in that the application has resize handles, and maximize buttons - both of which screw up the inner screen measurements. Add to this, users can toggle on and off toolbars, sidebars .. which also affect the result. Long story short .. `can't fix stupid` as my grandad would say

**Comment by Roman-Nopantski** [comment]
FYI: [Something, Something, Something, Dark Side](https://en.wikipedia.org/wiki/Something,_Something,_Something,_Dark_Side)
and [It's a Trap!](https://en.wikipedia.org/wiki/It%27s_a_Trap!)

**Comment by earthlng** [comment]
Maximizing and full-screen aren't the same thing.
re: 2204 - I have `browser.link.open_newwindow.restriction;0` for a long time and never had a problem.
Why is it commented out?

**Comment by Roman-Nopantski** [comment]
> Maximizing and full-screen aren't the same thing.

Indeed. I didn't say they were just in case you meant that. That's why I said "It's ALSO problematic in that the application has resize handles, and maximize buttons" - meaning three methods: fullscreen, maximize, resize.

2204: because I use a few popup windows :) We can revisit if you want. No big deal to me. Actually the tor resize resistFingerprinting is covering this right now with snapping window sizes. But that won't land for a while.

**Comment by earthlng** [comment]
> because I use a few popup windows

oh, ok, may I ask why you prefer that over a new tab? I'm just curious, because I'm quite happy with opening everything in a new tab by default

> We can revisit if you want. No big deal to me.

nah, I don't care, was just wondering

**Comment by Roman-Nopantski** [comment]
Sure you can ask. As for the pref I already flipped it 15 minutes ago

**Comment by crssi** [comment]
Your choice of `browser.link.open_newwindow.restriction` does not bother me, but it is very user specific choice. ;)
Maybe I wouldn't force it.

**Comment by Roman-Nopantski** [comment]
@crssi It's a borderline choice. First of all, the site actually specifics the pop window size (so it's not like it wasn't expecting those results back). Remember we have resistFingerprinting which will only return inner values, but some difference may be inferred/calculated (I would have to check) that gives away external widths/heights (again I would have to check)

**Comment by Atavic** [comment]
>warn users not to maximize their window

[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1403747)

**Comment by Thorin-Oakenpants** [comment]
I'm already tracking that, but weirdly enough it wasn't in the RFP sticky - added it now
