### ISSUE TITLE
dom.forms.datetime

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#495]
set `dom.forms.datetime`=`false`
- [tor 21787](https://trac.torproject.org/projects/tor/ticket/21787)

TBB applied a patch to use "en-US" locale for the date/time picker when privacy.spoof_english == 2 . I've asked Tom Ritter if this patch needs to be upstreamed to Firefox, and he just replied and it's now on next weeks agenda to be addressed.

Meanwhile, since we set the locale to "en-US", then I'm not sure this matters - but for people who don't use that, then this could be disabled in the meantime.

Yes/No? Do we add it active/inactive? Where?

- 0864 is the first free number (0861+0863 are taken in deprecated).
- If it's added as active, that penalizes en-US users. If added as inactive, I doubt any non-en-US users would bother to read and add it to overrides. So I'm kind of in favor of active, and screw date/time picker for forms until Mozilla upstream the patch
- we could just ignore it, and wait for Mozilla to upstream the patch

Class, discuss!

**Comment by claustromaniac** [comment]
I can live without those. I'd say add it active in the meantime. It's relavely new and therefore uncommon; breakage should be minimal.

**Comment by Thorin-Oakenpants** [comment]
- FF51: https://bugzilla.mozilla.org/show_bug.cgi?id=1287503
- FF52: https://bugzilla.mozilla.org/show_bug.cgi?id=1288591 <- i think it was added in this one
- FF53: https://bugzilla.mozilla.org/show_bug.cgi?id=1286182
- FF57: https://bugzilla.mozilla.org/show_bug.cgi?id=1399036 - flipped true

So not sure what to give it as FF+, so I'll leave that out and just use `(FF57+ default true)`

**Comment by Thorin-Oakenpants** [comment]
suggested:

```js
/* 0864: diable date/time picker (FF57+ default true)
 * This can leak your locale if not en-US
 * [1] https://trac.torproject.org/projects/tor/ticket/21787 ***/
user_pref("dom.forms.datetime", false);
```

nits welcome, as usual

**Comment by earthlng** [comment]
diable -> disable

**Comment by Thorin-Oakenpants** [comment]
I can't commit - I keep getting outages at random, it's a lottery
- https://status.github.com/messages

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1492587
