### ISSUE TITLE
[FYI] Heatmap

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#502]
See: http://jrvis.com/red-dwarf/?user=ghacksuserjs&repo=ghacks-user.js

Repo: https://github.com/rviscomi/red-dwarf

**Comment by Thorin-Oakenpants** [comment]
it just says "loading ..." and never finishes

**Comment by Atavic** [comment]
I had it loaded with K-Meleon, it needs JS...  a quick recap follows:

Biggest centers of interest: Germany and USA, then UK and Russia follow.
Other hotspots are Indonesia, Brazil, Australia and a few others are scattered in indochina, like Philippines and Thailand.  There are some followers in South Africa, too.
