### ISSUE TITLE
`extensions.enabledScopes=1` blocks privacybadger installed as archlinux package under FF62

### ISSUE THREAD

**Issue by mabrek** [ghacksuserjs/ghacks-user.js#503]
Under FF62 with `extensions.enabledScopes=1` extensions from `/usr/lib/firefox/browser/extensions/` are not loaded at all. Setting `extensions.enabledScopes` to 4 fixes that.
https://www.archlinux.org/packages/community/any/firefox-extension-privacybadger/ is installed at `/usr/lib/firefox/browser/extensions/` so it doesn't work with `extensions.enabledScopes=1`
Here's some documentation https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Alternative_distribution_options/Add-ons_in_the_enterprise#Firefox_settings

**Comment by earthlng** [comment]
thanks for the info

**Comment by Thorin-Oakenpants** [comment]
Yup, thanks for the info. BTW, we don't recommend Privacy Badger (in fact we explicitly said it was not worth it). That said, what is so special about EFFs extension that it uses a different path on Arch?. Is it just PB ? what happens with other extensions on Arch? What happens on other Linux packages? I am not a Linux expert, so excuse my ignorance.

Do we need to add some more info to the user.js? eg
```
/* 2660: lock down allowed extension directories
 * [WARNING] This will break extensions that do not use the default XPI directories
newline-> * e.g. some Linux packages might require setting enabledScopes at `4`
newline-> * 1=profile 2=user 4=application 8=system
 * [1] https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/
 * [1] archived: https://archive.is/DYjAM ***/
```

**Comment by Thorin-Oakenpants** [comment]
wait, now I'm confused. The MDN link says those values (1,2,4,8) are for `extensions.autoDisableScopes` which to me is incorrect. https://mike.kaply.com/2012/02/21/understanding-add-on-scopes/ says these values are meant for `extensions.enabledScopes` :tired: :needsleep: :zzzzz:

**Comment by Atavic** [comment]
You're right, no need to sleep. I find [this](http://www.favbrowser.com/how-to-create-a-new-default-firefox-experience-in-your-enterprise/) useful.
