### ISSUE TITLE
task: update wiki [userscripts & disabling JS eg uM]

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#505]
Under [Legacy Extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions#small_orange_diamond-legacy-extensions) the link goes to the NoScript AMO page that lists the actual Webext version.

To get NoScript "Classic" (5.1.8.7) for Firefox 52 ESR there's Maone's own site:
https://noscript.net/getit

I know none cares about it, but Maone quickly updated it after [this bug](https://mobile.twitter.com/Zerodium/status/1039127214602641409) was discovered.

**Comment by Thorin-Oakenpants** [comment]
Yup, read about that. Thanks for the reminder - not going to monitor or link to legacy versions - its maintenance I can do without. Will edit wiki extension legacy section

**Comment by Thorin-Oakenpants** [comment]
Actually I stripped out all the legacy extensions but left in GM and NS (sans links) for now. Wiki page needs a little cleanup with info on CSP clashes (and I can work in a recommendation not to use too many extensions together and that we do not recommend NS since we have uM). GM I could add as an alt to VM since it's been a while since WebExt (I assume they should by now be fairly much on a par now)

**Comment by kgbm3** [comment]
@Atavic (GM, VM?) Extensions, or Add-ons needing JavaScript, what? No, why would they... 

Btw., it's unfortunate what happened to NoScript, with the switch to WebExtensions; like, how it died, heh. ;$

**Comment by Thorin-Oakenpants** [comment]
> GM, VM: do they need JS active? I turn JS off on most sites

Same - but the only two scripts I use are to block JS antics (and I might reduce that to one).

---

I never really followed this. Can you elaborate? If the primary domain has no JS allowed, then GM/VM can't function? What happens for 3rd party domains if 1st party JS is denied but 3rd party isn't (yes it can happen)? Does something need to be added to the extensions wiki?

**Comment by Atavic** [comment]
I haven't used in ages, but: https://github.com/violentmonkey/violentmonkey/issues/302

BTW I had one script that warned about malicious JS code, maybe it was the same as yours.

**Comment by Thorin-Oakenpants** [comment]
Well, I suppose I better add this to the wiki list, along with the CSP issue

First of all, screw NS (it's an unwieldy horrible UI PoS)

Here is my uBO (the issue says uBO can disable JS and VM still works)
![ubo](https://user-images.githubusercontent.com/16656956/45595729-937a3b00-b99f-11e8-8474-aa2e64d4a037.png)

Here is my uM
![um](https://user-images.githubusercontent.com/16656956/45595733-9bd27600-b99f-11e8-84da-78f822102f12.png)

As you can see I rely on uM to control JS, so I guess I'm screwed (well, not really). As I said I only use VM to block JS and if JS is already disabled, then I'm fine anyway. Just not sure how to word this on the wiki.

@gorhill - why does uBO blocking JS still allow usrscripts to work, but uM doesn't?

Question: Does GM has this same issue?

**Comment by gorhill** [comment]
> why does uBO blocking JS still allow usrscripts to work, but uM doesn't?

No clue. I tried to find out how VM injects its user scripts but the code is all webpacked and minimized and just too tedious to step in, so best is just to ask the author of VM.

**Comment by Thorin-Oakenpants** [comment]
^^ I just asked on your behalf

**Comment by B00ze64** [comment]
> First of all, screw NS (it's an unwieldy horrible UI PoS)

LOL, yeah, the new NS UI makes little sense (everything is like duplicated every line, I don't really get it) but uB0 does not allow fine-grained control of scripts. When I move from FF52, I intend to use uMatrix to replace NS (along with uB0 and VM, which I already use.) uMatrix offers per-site control, which NS does not do, despite Giorgio sometimes calling some options "per-site" options. Hopefully by then this bug will have been worked-around...

**Comment by Atavic** [comment]
NoScript as Webext has lost some feats like Clickjacking, ABE...

**Comment by Thorin-Oakenpants** [comment]
actually, I've decided to not add anything to the wiki. The scripts page is pretty busy as is. In terms of privacy (which is what our scripts are aimed at), then this is a non-issue. i.e if uM is disabling JS, then window.name and history.length are already protected
