### ISSUE TITLE
discussion: redo 1000s cache

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#51]
I think the 1000s cache section could do with a little love. My thoughts are the header section (or some items) needs a [SETUP] tag and information on session restores (crash recovery etc). 

I gave pk some instructions the other day on how to trigger a FF crash. I'll repost them here. I need to make sure that all the session restore and resume from crash is grouped together, and to make sure it is clear what needs to be done to enable them.

**Comment by Roman-Nopantski** [comment]
## Crash!

- Go to about:config and turn `devtools.chrome.enabled` to true
- Open Scratchpad with Shift+F4
- Switch Environment to Browser and run the following snippet
```js
Cu.import("resource://gre/modules/ctypes.jsm");
let zero = new ctypes.intptr_t(8);
let badptr = ctypes.cast(zero, ctypes.PointerType(ctypes.int32_t));
badptr.contents;
```
- Crash!

**Comment by earthlng** [comment]
1006 -> they call this [Fastback cache](https://dxr.mozilla.org/mozilla-central/source/modules/libpref/init/all.js#218)

1005 -> could use a better explanation. It's confusing because the title says **disable storing extra session data** and the option 0=all. Mozilla uses the following comment for this pref:
```
// on which sites to save text data, POSTDATA and cookies
// 0 = everywhere, 1 = unencrypted sites, 2 = nowhere
```

maybe something like this:
```
/* 1005: disable storing extra session data
 * extra session data contains contents of forms, scrollbar positions, cookies and POST data
 * define on which sites to save extra session data:
 * 0 = everywhere, 1 = unencrypted sites, 2 = nowhere ***/
user_pref("browser.sessionstore.privacy_level", 2);
```

**Comment by Thorin-Oakenpants** [comment]
^^ sweet, got in my draft here now

**Comment by earthlng** [comment]
Oh, okay, I assumed it meant pages as in sites. But if it's memory pages or something like that, then we should not encourage changing it to anything other than 0 or the default -1

**Comment by earthlng** [comment]
Looks like it's "sites" after all and the table on the Zine is still accurate:
https://dxr.mozilla.org/mozilla-central/source/docshell/shistory/nsSHistory.cpp#263

`For the sake of completeness, this option is listed for the truly paranoid.`
We should drop that line or extend it to also mention usefulness to limit memory consumption.

`or any other positive integer` is also not ideal. `for other values see [1]` for example.

**Comment by Thorin-Oakenpants** [comment]
^^^ Yup, needs a cleanup (these were written like 18months ago based on some quick research). I have a reordered draft sitting here, but wanted to finish 1200s first. And before that, the 3 wiki pages and readme

**Comment by Thorin-Oakenpants** [comment]
just to give you an idea - nothing done much, just a really rough draft.

```js
/*** 1000: CACHE
     Blah Blah, relax these if secure device etc blah blah - especially
     session restore and favicons blah blah
 ***/
user_pref("ghacks_user.js.parrot", "1000 syntax error: the parrot's gone to meet 'is maker!");

/* CACHE ***/
/* 1001: disable disk cache ***/
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
/* 1002: disable disk caching of SSL pages
 * http://kb.mozillazine.org/Browser.cache.disk_cache_ssl ***/
user_pref("browser.cache.disk_cache_ssl", false);
/* 1003: disable memory cache as well IF you're REALLY paranoid ***/
   // user_pref("browser.cache.memory.enable", false);
/* 1004: disable offline cache ***/
user_pref("browser.cache.offline.enable", false);

/* 1004: disable (or limit) Fastback caching
/* 1004: disable pages being stored in memory. This is not the same as memory cache.
 * Visited pages are stored in memory in such a way that they don't have to be
 * re-parsed. This improves performance when pressing back/forward.
 * For the sake of completeness, this option is listed for the truly paranoid.
 * 0=none, -1=auto (that's minus 1), or any other positive integer
 * http://kb.mozillazine.org/Browser.sessionhistory.max_total_viewers ***/
   // user_pref("browser.sessionhistory.max_total_viewers", 0);

/* 1005: disable permissions manager from writing to disk (requires restart)
 * https://bugzilla.mozilla.org/show_bug.cgi?id=967812 ***/
   // user_pref("permissions.memory_only", true); // (hidden pref)
/* 1006: disable randomized FF HTTP cache decay experiments
 * https://trac.torproject.org/projects/tor/ticket/13575 ***/
user_pref("browser.cache.frecency_experiment", -1);
/* 1007: DNS cache and expiration time (default 400 and 60, same as TBB) ***/
   // user_pref("network.dnsCacheEntries", 400);
   // user_pref("network.dnsCacheExpiration", 60);

/* SESSION RESTORE ***/
/* 1020: disable the Session Restore service completely
 * [WARNING] [SETUP] This also disables the "Recently Closed Tabs" feature
 * It does not affect "Recently Closed Windows" or any history. ***/
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
/* 1021: disable storing extra session data
 * extra session data contains contents of forms, scrollbar positions, cookies and POST data
 * define on which sites to save extra session data:
 * 0 = everywhere, 1 = unencrypted sites, 2 = nowhere ***/
user_pref("browser.sessionstore.privacy_level", 2);
/* 1022: disable resuming session from crash [SETUP] ***/
user_pref("browser.sessionstore.resume_from_crash", false);
/* 1023: IF you use session restore, increasing the minimal interval between
 * two session save operations can help on older machines and some websites.
 * Default is 15000 (15 secs). Try 30000 (30sec), 60000 (1min) etc - your choice.
 * [WARNING] This can also affect entries in the "Recently Closed Tabs" feature:
 * i.e the longer the interval the more chance a quick tab open/close won't be captured
 * this longer interval *MAY* affect history but we cannot replicate any history not recorded ***/
   // user_pref("browser.sessionstore.interval", 30000);

/* FAVICONS ***/
/* 1030: disable favicons in firefox (chrome), web notifications (alerts) and shortcuts (shell)
 * these generate a cache.. blah blah ... cache is located here .. blah blah ***/
   // user_pref("browser.chrome.favicons", false);
   // user_pref("alerts.showFavicons", false);
   // user_pref("browser.shell.shortcutFavicons", false);
/* are these cached? ***/
   // browser.chrome.site_icons
```

**Comment by earthlng** [comment]
nice! a few nits:
* disabling memory cache - I don't see how that would help the really paranoid, because they would stand out really badly. If anything, it's _maybe_ useful for really old and shitty computers with not much RAM.
=> why do you think this is useful for the truly paranoid?
* SESSION RESTORE - some of them are not only for RESTORE (afaik!) but for session STORE too.
fe with `browser.sessionstore.privacy_level=0` if you scrolled down on a very long page (fe on reddit) and you reload the page, it will scroll back down to where you were. I haven't tested this in a vanilla FF recently but I'm pretty sure that's what it does.
* browser.sessionstore.interval - for the sake of SSD's we should probably enable this with a reasonably high value. (I have 60000, but even 30sec is much better than the default 15sec)
https://www.servethehome.com/firefox-is-eating-your-ssd-here-is-how-to-fix-it/

**Comment by earthlng** [comment]
re: SSD problem
https://bugzilla.mozilla.org/show_bug.cgi?id=1304389
they're working on it. AND with our other settings and bit of smart behaviour (like open links in new tabs and don't keep 10 history on each tab + use PB, etc) my recovery.js at the moment is only 55kb. They talk about files with 1MB and more, so it's not **that** much of a problem.
And my profile never touches my SSD anyway, but that's not the point here.

**Comment by Thorin-Oakenpants** [comment]
I was going to add in something about SSDs and reducing writes, but TBH, with the current gnerations, it'd take 100 yrs to kill one even with heavy use - I think arstechnica wrote some to death

**Comment by Thorin-Oakenpants** [comment]
Yes, we need to take out silly sentences like truly paranoid

**Comment by Thorin-Oakenpants** [comment]
thoughts on this intro, does it cover it?

```js
/*** 1000: CACHE [SETUP]
     You can comment out and and reset this entire section if you don't mind leaving forensic
     data all over your OS, and you trust the security of your device and access to it is
     adequate. Using disk cache (1001) will depend on your needs - latest generation SSDs
     will far outweigh their lives even with heavy use, but we would certainly recommend
     disk cache be disabled for USB sticks
 ***/
```

**Comment by Thorin-Oakenpants** [comment]
> disabling memory cache - I don't see how that would help the really paranoid

I am not a RAM expert, but back in the day you could do these sorts of things - that RAM can hold left over forensic data. I remember one way to grab a key (or whatever) off a phone (way back when) was to power it on so the hashes/other-key-pair/whatever was in memory and to then snap freeze that memory chip or phone and read it as fast as possible before it warmed up :)

Or .. more realistic: ninja attack, dude caught with his laptop open and logged in .. Kremlin spooks use cacheviewer addon to look at the history, because while disk cache may be off, memory cache is used. I would call that paranoid but totally feasible. Exhibit A: DPR & silk road when they nabbed him (not that they needed cache history AFAIK, they already had enough other evidence).

**Comment by earthlng** [comment]
> latest generation SSDs will far outlive their useful lives even with heavy use

my Vertex2 only lasted ~5 years. And I did everything possible to limit the writes. Ok, it wasn't exactly "latest generation" but I doubt my current one will last much longer.

Idk if we really need a description for cache - it's pretty self-explanatory IMO
I definitely don't like the `comment out and and reset this entire section` because for example 1004 can and probably should remain disabled, always. But yeah, i don't really care and I'm certainly not going to start another arguing-war about it

`disabling memory cache ` - oh yeah, cold-boot-attack. Ok you win :)

**Comment by Thorin-Oakenpants** [comment]
True about the SSDs - there's a wide range out there including cheap crap. Plus older machines. I'll reword it or something

description for section header: well, I want to be consistence with allowing people to easily turn on/off the stuff that is minor security vs convenience. Like we did with forms etc (0850+), now this bit. Although I don't want to write a book. :eyes: 

cold-boot-attack ... I win? OMG .. I finally f**k*ng won :1st_place_medal:

**Comment by Thorin-Oakenpants** [comment]
Try this
```
/*** 1000: CACHE [SETUP]
     If you don't mind leaving forensic data all over your OS, and you trust the security of
     your device and access to it is limited, then by all means turn sessions and session
     restore and favicons back on. As for disk cache (1001), if you use a SSD (and definitely
     a USB stick), then we recommend disk cache be disabled to reduce writes
 ***/
```

**Comment by earthlng** [comment]
It makes it sound way worse than it really is. "forensic data" "all over your OS" and then listing literally all the things, with a special note about cache.
I mean we're not dealing with idiots or amateurs here. Everyone will almost definitely know what Cache is and does, and whether they want it enabled or not.
`/*** 1000: CACHE [SETUP] ***/` => done. but

> i don't really care and I'm certainly not going to start another arguing-war about it

just my 2cents

**Comment by Thorin-Oakenpants** [comment]
True. Its a very small section the 1000s. Still, to get more mainstream, you HAVE to lower the bar, just saying. Revised back to `/*** 1000: CACHE [SETUP] ***/` . I'm not afraid to try things, because some of them come up aces. Also, until I do them, I have no idea how dumb or brilliant they are :)

**Comment by Thorin-Oakenpants** [comment]
just the favicons to come then. Note 1023 I flipped to active (at 30secs) and added info on writes and bugzilla link

```js
/*** 1000: CACHE [SETUP] ***/
user_pref("ghacks_user.js.parrot", "1000 syntax error: the parrot's gone to meet 'is maker!");
/** CACHE ***/
/* 1001: disable disk cache ***/
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
/* 1002: disable disk caching of SSL pages
 * [1] http://kb.mozillazine.org/Browser.cache.disk_cache_ssl ***/
user_pref("browser.cache.disk_cache_ssl", false);
/* 1003: disable memory cache ***/
   // user_pref("browser.cache.memory.enable", false);
/* 1004: disable offline cache ***/
user_pref("browser.cache.offline.enable", false);
/* 1005: disable "page memory" (page does not refer to a web page here). This is
 * also not the same as memory cache. Visited "web pages" are stored in memory in
 * such a way that they don't have to be re-parsed. This improves performance when
 * pressing back/forward. Mozilla also uses the term "Fastback caching".
 * 0=none, -1=auto (that's minus 1), or for other values see [1] (which is old and not maintained)
 * [1] http://kb.mozillazine.org/Browser.sessionhistory.max_total_viewers ***/
   // user_pref("browser.sessionhistory.max_total_viewers", 0);
/* 1006: disable permissions manager from writing to disk (requires restart)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=967812 ***/
   // user_pref("permissions.memory_only", true); // (hidden pref)
/* 1007: disable randomized FF HTTP cache decay experiments
 * [1] https://trac.torproject.org/projects/tor/ticket/13575 ***/
user_pref("browser.cache.frecency_experiment", -1);
/* 1008: DNS cache and expiration time (default 400 and 60, same as TBB) ***/
   // user_pref("network.dnsCacheEntries", 400);
   // user_pref("network.dnsCacheExpiration", 60);
/** SESSIONS & SESSION RESTORE ***/
/* 1020: disable the Session Restore service completely
 * [WARNING] [SETUP] This also disables the "Recently Closed Tabs" feature
 * It does not affect "Recently Closed Windows" or any history. ***/
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
/* 1021: disable storing extra session data
 * extra session data contains contents of forms, scrollbar positions, cookies and POST data
 * define on which sites to save extra session data:
 * 0=everywhere, 1=unencrypted sites, 2=nowhere ***/
user_pref("browser.sessionstore.privacy_level", 2);
/* 1022: disable resuming session from crash [SETUP] ***/
user_pref("browser.sessionstore.resume_from_crash", false);
/* 1023: If you use session restore, increasing the minimal interval between two session save
 * operations can help on older machines and some websites, as well as reducing writes, see [1]
 * Default is 15000 (15 secs). Try 30000 (30sec), 60000 (1min) etc
 * [WARNING] This can also affect entries in the "Recently Closed Tabs" feature:
 * i.e the longer the interval the more chance a quick tab open/close won't be captured.
 * This longer interval *MAY* affect history but we cannot replicate any history not recorded
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1304389 ***/
user_pref("browser.sessionstore.interval", 30000);
```

I tested `browser.chrome.site_icons` and for tabs and bookmarks it seems to have the same behavior as `browser.chrome.favicons`.  Will do all this another day

```js
/* 1030: disable favicons in firefox (chrome), web notifications (alerts) and shortcuts (shell)
 * these generate a cache.. blah blah ... cache is located here .. blah blah ***/
   // user_pref("browser.chrome.favicons", false);
   // user_pref("alerts.showFavicons", false);
   // user_pref("browser.shell.shortcutFavicons", false);
/* are these cached? ***/
   // user_pref("browser.chrome.site_icons", false);
```

**Comment by Thorin-Oakenpants** [comment]
Some light reading on [The State of Browser Caching](https://www.mnot.net/blog/2017/03/16/browser-caching) published yesterday .. interesting read

**Comment by earthlng** [comment]
Man! are you not reading my stuff? ;)
Let me try this one more time and you can do with it what you want:

```
/* 1005: disable Fastback caching
 * To improve performance when pressing back/forward, FF stores visited pages
 * so they don't have to be re-parsed. This is not the same as memory cache.
 * 0=none, -1=auto (that's minus 1), or for other values see [1]
 * [1] http://kb.mozillazine.org/Browser.sessionhistory.max_total_viewers ***/
   // user_pref("browser.sessionhistory.max_total_viewers", 0);
```

* `page does not refer to a web page here`-> is incorrect
* (which is old and not maintained) -> but still accurate! I linked to the table in DXR

=> shorter, sexier and accurate => I'd even dare to say "perfect" ;)

**Comment by Thorin-Oakenpants** [comment]
Soz, forgot to remove that info about the old link. It IS old and unmaintained (and could easily be outdated due to changes in tech), but yes accurate for now. I meant to remove that comment which I put in before your link to the code.

This preference limits the maximum number of pages stored in memory - but the value is not directly linked to actual web pages - it is a "page memory". However, yours is secksier, so :+1:

**Comment by earthlng** [comment]
> but the value is not directly linked to actual web pages

what do you mean?

**Comment by Thorin-Oakenpants** [comment]
I mean that the value used in the pref does not mean to only keep that many web pages rendered in memory. I mean 8 = 4gb

PS: cached favicon names are randomized

**Comment by earthlng** [comment]
`but the value is not directly linked to actual web pages` - no, it's per Tab I assume. regardless if you visit different pages on the same domain/site or navigate to another site completely.

**Comment by earthlng** [comment]
yes, for PCs with 4GB ram they cap it to 8 - but they also say that per "page" it's about 4MB, so depending on how you browse, you could easily set this higher. fe. if you always open links in new tabs, you could have 100 tabs open and then have one tab with 100 history "back/forwards" in that tab and 4GB should be easily enough to handle even a value of 100 in that case.

**Comment by Thorin-Oakenpants** [comment]
So my point is that 8 does not mean 8 web pages. We've changed the wording so thatthe word "page" is only used once to mean a web page, so now there is no confusion for readers :)

**Comment by Thorin-Oakenpants** [comment]
Time for some food, a movie and sleep :) Big day tomorrow ... finish wiki and readme and draft Martin's article - gonna ask him if it can be my article as a guest article - will run it thru you first .. nite nite

**Comment by Thorin-Oakenpants** [comment]
from Atavic
> The places.sqlite includes a number of tables as follows:
    moz_favicons - Favourite icons - including URL of icon 

Interesting. They have an expiration. I have 51 in my table.

**Comment by Thorin-Oakenpants** [comment]
Maybe something has changed overt time. I just removed 180 .ico files from my `profile/shortcutCache` directory (they ranged in creation date from March 2017 thru to August 2015. An awful lot are the same file (loads of discogs, wikipedia and github icons).

Removing all these .ico files did not damage any of my icons for bookmarks. And none have been added since - and I went to here, wikipedia and discogs (see above comment).

Needs more cowbell

**Comment by Thorin-Oakenpants** [comment]
Notes:

- dragging and dropping an url shortcut to windows explorer, creates a shortcutCache .ico. Deleting the url shirtcut does not remove the .ico file.
- creating a bookmark does not create a .ico file. Tabs with icons don't do it either.

shortcutCache is exactly what it sounds like - URL shortcut icons used by the OS. This explains why I had so many wikipedia ones. Everything else (web notifications, bookmarks, tab icons) is handled internally.

I've visited several hundreds of different sites, and the moz_favicons table only held 51 items. On a restart it dropped to 50. Entries have an expiration date (maybe some code digging could work out what that time is). The table certainly holds URLS.

Needs more cowbell

**Comment by Thorin-Oakenpants** [comment]
```js
/* 1030: disable favicons in tabs and new bookmarks
 * bookmark favicons are stored in places.sqlite>moz_favicons ***/
   // user_pref("browser.chrome.site_icons", false);
/* 1031: disable favicons in shortcuts
 * URL shortcuts use a cached randomly named .ico file which is stored in your
 * profile/shortcutCache directory. The .ico remains after the shortcut is deleted.
 * If set to false then the shortcuts use a generic Firefox icon ***/
   // user_pref("browser.shell.shortcutFavicons", false);
/* 1032: disable favicons in web notifications ***/
   // user_pref("alerts.showFavicons", false);
/* 1033: no idea what this does ***/
   // user_pref("browser.chrome.favicons", false);
```

1030: Pointless blocking these: favicons used in tabs and everyday browsing are simply stored in cache like any other element. When used for bookmarks, they are stored in moz_favicons as data blobs. This is hardly likely to be anything secret - the bookmark itself already gives away the information. The table maintains itself - If you delete a bookmark, the relevant entry is removed from the table and if you update an icon, the data blob is updated. I actually deleted all moz_favicon entries for a test.

1031: the shortcut may or may not be deleted (may or may not be on a removable stick) - it is the shortcut itself that is worth the information (in forensics). The fact it may point to a firefox location is almost irrelevant (no favicon it will use a the firefox one anyway). The randomly named cached .ico file in and of itself is just an ico file - it does not say where it came from. If anyone wants to, they can add cleaning this directory to their Bleach or CCleaner options/scripts.

1032: I'm going to guess this is just stored in disk/memory cache like the others - and we already have mechanisms to clear all that

1033: NFI

**Comment by Thorin-Oakenpants** [comment]
final patch for nits

```js

/*** 1000: CACHE [SETUP] ***/
user_pref("ghacks_user.js.parrot", "1000 syntax error: the parrot's gone to meet 'is maker!");
/** CACHE ***/
/* 1001: disable disk cache ***/
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
/* 1002: disable disk cache for SSL pages
 * [1] http://kb.mozillazine.org/Browser.cache.disk_cache_ssl ***/
user_pref("browser.cache.disk_cache_ssl", false);
/* 1003: disable memory cache ***/
   // user_pref("browser.cache.memory.enable", false);
/* 1004: disable offline cache ***/
user_pref("browser.cache.offline.enable", false);
/* 1005: disable fastback cache
 * To improve performance when pressing back/forward Firefox stores visited pages
 * so they don't have to be re-parsed. This is not the same as memory cache.
 * 0=none, -1=auto (that's minus 1), or for other values see [1]
 * [1] http://kb.mozillazine.org/Browser.sessionhistory.max_total_viewers ***/
   // user_pref("browser.sessionhistory.max_total_viewers", 0);
/* 1006: disable permissions manager from writing to disk (requires restart)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=967812 ***/
   // user_pref("permissions.memory_only", true); // (hidden pref)
/* 1007: disable randomized FF HTTP cache decay experiments
 * [1] https://trac.torproject.org/projects/tor/ticket/13575 ***/
user_pref("browser.cache.frecency_experiment", -1);
/* 1008: set DNS cache and expiration time (default 400 and 60, same as TBB) ***/
   // user_pref("network.dnsCacheEntries", 400);
   // user_pref("network.dnsCacheExpiration", 60);
/** SESSIONS & SESSION RESTORE ***/
/* 1020: disable the Session Restore service completely
 * [WARNING] [SETUP] This also disables the "Recently Closed Tabs" feature
 * It does not affect "Recently Closed Windows" or any history. ***/
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
/* 1021: disable storing extra session data
 * extra session data contains contents of forms, scrollbar positions, cookies and POST data
 * define on which sites to save extra session data:
 * 0=everywhere, 1=unencrypted sites, 2=nowhere ***/
user_pref("browser.sessionstore.privacy_level", 2);
/* 1022: disable resuming session from crash [SETUP] ***/
user_pref("browser.sessionstore.resume_from_crash", false);
/* 1023: If you use session restore, increasing the minimal interval between two session save
 * operations can help on older machines and some websites, as well as reducing writes, see [1]
 * Default is 15000 (15 secs). Try 30000 (30sec), 60000 (1min) etc
 * [WARNING] This can also affect entries in the "Recently Closed Tabs" feature:
 * i.e the longer the interval the more chance a quick tab open/close won't be captured.
 * This longer interval *may* affect history but we cannot replicate any history not recorded
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1304389 ***/
user_pref("browser.sessionstore.interval", 30000);
/** FAVICONS ***/
/* 1030: disable favicons in shortcuts
 * URL shortcuts use a cached randomly named .ico file which is stored in your
 * profile/shortcutCache directory. The .ico remains after the shortcut is deleted.
 * If set to false then the shortcuts use a generic Firefox icon ***/
   // user_pref("browser.shell.shortcutFavicons", false);
/* 1031: disable favicons in tabs and new bookmarks
 * bookmark favicons are stored as data blobs in places.sqlite>moz_favicons ***/
   // user_pref("browser.chrome.site_icons", false);
/* 1032: disable favicons in web notifications ***/
   // user_pref("alerts.showFavicons", false);
/* 1033: disable favicons in ?web apps? ***/
   // user_pref("browser.chrome.favicons", false);
```

**Comment by earthlng** [comment]
man! you gotta be shitting me??!! ANOTHER full patch to review? we should really use PR for this kind of thing.

**Comment by Thorin-Oakenpants** [comment]
its the same as before with the favicons at the end

**Comment by earthlng** [comment]
`browser.chrome.favicons` - see http://kb.mozillazine.org/Browser.chrome.favicons
* `browser.chrome.site_icons` must be true for this preference to have an effect.
* Conversely, `browser.chrome.site_icons` should be false when this preference is false to disable site icons and favicons completely.

IMO we should put them both under 1031. And we can enable 1030 by default IMO.

**Comment by Thorin-Oakenpants** [comment]
browser.chrome.site_icons added into 1031
1030 flipped to active
I put 1030 as the first pref since it is the only one that cached to disk separately - the rest are either sqlite tables or normal disk/memory cache.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/9d80dfbf450915316a7656410e97d021d5cfa896
