### ISSUE TITLE
atomGit takes toys, moves to GitLab

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#510]
just an FYI...

[https://gitlab.com/labwrat/Firefox-user.js/tree/master](https://gitlab.com/labwrat/Firefox-user.js/tree/master)

screw M$

**Comment by Thorin-Oakenpants** [comment]
thanks, fixed the readme link

**Comment by Thorin-Oakenpants** [comment]
your js may need an update (depends, since enforcing it makes no diff and for all I know you want to use waterfox or something)

off the top of my head
```
browser.bookmarks.max_backups; <- inactive in ours
browser.urlbar.autoFill.typed <- removed it since its covered by the other pref
dom.workers.enabled <- deprecated
network.cookie.cookieBehavior <-- is at 1 already
```

**Comment by atomGit** [comment]
i'm using Waterfox v56 and so i'm using the corresponding version of your js
