### ISSUE TITLE
the fonts issue

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#513]
I had a look at https://browserleaks.com/fonts and was surprised at the amount of information it's able to gather despite `browser.display.use_document_fonts;0`

I tested with 2 profiles, 1 with HW acceleration enabled and 1 without but get the same fingerprint in both.

on Windows with no changes made in `1402`:

* without `1407` (`font.blacklist.underline_offset = ""`)
```
JS Fonts (unicode)
Fingerprint	a79ee4e6

JS Fonts (classic)
Fingerprint	5691776ad0aaf020a397e4b0a9e1fd74
Report	40 fonts and 27 unique metrics found in the list of 512 fonts
```

* with `font.blacklist.underline_offset = ""`
```
JS Fonts (unicode)
Fingerprint	a79ee4e6

JS Fonts (classic)
Fingerprint	fea459f2fed7d5c76f7f3b8b6f6f04c6
Report	38 fonts and 25 unique metrics found in the list of 512 fonts
```

I think these should be the same in all Windows' regardless of additional fonts installed in the system.

The fingerprint is going to be different on MacOS and most likely very different for various Linux distros.

We should get rid of `1402` and `1407` IMO.

**Comment by KOLANICH** [comment]
https://gitlab.com/KOLANICH1/Article-2015-Dull-captaincy-or-the-way-Tor-Project-fights-browser-fingerprinting

don't fork, don't edit, this has some problems with latex to pdf building, the commit will be rewritten. But you can read and test js+html and read and build latex code yourself.

**Comment by Atavic** [comment]
>I think these should be the same in all Windows' regardless of additional fonts installed in the system.

On XP I get:

```JS Fonts (unicode)
Fingerprint	24549697

JS Fonts (classic)
Fingerprint	64963f7dac074102af8df078af9e3b33
Report	 0 fonts and 2 unique metrics found in the list of 512 fonts
```

**Comment by Atavic** [comment]
>I think these should be the same in all Windows' regardless of additional fonts installed in the system.

On XP I get:
```
JS Fonts (unicode)
Fingerprint	24549697

JS Fonts (classic)
Fingerprint	64963f7dac074102af8df078af9e3b33
Report	 0 fonts and 2 unique metrics found in the list of 512 fonts
```

**Comment by earthlng** [comment]
woaw, 0 fonts detected? there's gotta be something else you're doing apart from using WinXP.
Congrats for most likely being uniquely identifiable everywhere you go, though :)

**Comment by Thorin-Oakenpants** [comment]
so the classic method used is css fallback: https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style/fallback .. which seems to only be supported in FF? huh? since FF33 ... I must be reading it wrong

anyway:
```
JS Fonts (unicode)
Fingerprint	5bb0498e

JS Fonts (classic)
Fingerprint	3fdb2da8ab7056d3b6b7a954731c51f3
Report	? 67 fonts and 20 unique metrics found in the list of 512 fonts
```

I then set font.system.whitelist = "Arial, Georgia, Lucida Console" (as per my three fonts in 1402`) and I got this
```
JS Fonts (unicode)
Fingerprint	33562d56

JS Fonts (classic)
Fingerprint	a7f785fb7d13d0a90c3cafa7b7f3f8f6
Report	? 16 fonts and 6 unique metrics found in the list of 512 fonts

Detected Metrics/Fonts:
1879,145	Courier, Courier New Baltic, Courier New CE, Courier New CYR, Courier New Cyr, Courier New Greek, Courier New TUR
1874,145	MS Sans Serif
1856,145	MS Serif, Roman, Times New Roman Baltic, Times New Roman CE, Times New Roman CYR, Times New Roman Cyr, Times New Roman Greek, Times New Roman TUR
```

no idea why it detects all that Times New Roman shit. I was hoping for just 3 fonts detected (not really). Anyway, it uglifies chrome (urlbar, search bar, the lot). It was just a test. Not keeping it like this.

**Comment by Maryse47** [comment]
With `browser.display.use_document_fonts;0` I have always 0 fonts detected. There is some interesting site covering font fingerprinting: https://www.browserplugs.com/

**Comment by grauenwolfe** [comment]
macOS Sierra (10.12.6)

````
JS Fonts (unicode)
Fingerprint 	6da2c6c5

JS Fonts (classic)
Fingerprint	eb5abb887a093bff78b4dd7e7ecb6fd2
Report		1 fonts and 4 unique metrics found in the list of 512 fonts


Fallback Metrics/Fonts:
1977,129	default, sans-serif, cursive, fantasy
1923,128	serif
1844,129	monospace

Detected Metrics/Fonts:
1964,129	Times New Roman

````

**Comment by claustromaniac** [comment]
On Windows without changes in `1402`

- With default `font.blacklist.underline_offset`
```
JS Fonts (unicode)
Fingerprint	d8ccd5a9

JS Fonts (classic)
Fingerprint	c028cc5bf71d3bd08bddf8c8dadaca42
Report	✔ 32 fonts and 19 unique metrics found in the list of 512 fonts
```

- With `font.blacklist.underline_offset = ""`
```
JS Fonts (unicode)
Fingerprint	d8ccd5a9

JS Fonts (classic)
Fingerprint	53f096f20698bc6d105ae84d3abbce10
Report	✔ 30 fonts and 17 unique metrics found in the list of 512 fonts
```

`1407` still works out for me, it seems.

**Comment by earthlng** [comment]
great, so we get different results even on the same OS. Well I guess it doesn't really matter if someone changes `1402` and/or `1407` because chances are we're pretty unique anyway, at least on Windows.
