### ISSUE TITLE
1205: TLS1.3 0-RTT

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#516]
source: https://www.privateinternetaccess.com/blog/2018/09/firefox-hardening-guide/

[emphasis mine]
> Disable 0-RTT – Zero Round Trip Time Resumption (0-RTT) is a feature that is new in TLS 1.3 that allows a client and server to negotiate a connection with fewer steps, allowing https websites to load more quickly. There are two problems with this. First, in order to do this **you lose forward secrecy** (generating a new key for every session and throwing away the key when the session is over). Secondly, 0-RTT **requires special implementation in order to prevent replay attacks**, which some web developers will certainly fail to protect from. Disabling 0-RTT enhances security and privacy.

Is it worth adding an extra line to `1205`?

Edit: I have not verified this

**Comment by earthlng** [comment]
you mean adding the link?

**Comment by Thorin-Oakenpants** [comment]
> you mean adding the link?

No. I just meant expanding on why we block it. But now I'm checking https://github.com/tlswg/tls13-spec/issues/1001 (which is link `[1]`) and you know what .. seems like the blog author used this

> The review focused on two known-issues: the absence of forward secrecy for all data, and the replayability of 0-RTT data. 

So I guess we don't need to do anything. My bad.
