### ISSUE TITLE
4702: navigator.buildID

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#518]
- https://bugzilla.mozilla.org/show_bug.cgi?id=583181
- https://www.fxsitecompat.com/en-CA/docs/2018/navigator-buildid-now-returns-a-fixed-timestamp/

I'm confused by this now. I thought they had blocked this from web content (except some mozilla domains for telemetry etc), but then the compat was changed in the last day (from it's previous edit 4 days ago)  and says that now it always returns a fixed timestamp.

The `4702` entry needs a cleanup (trailing `(` for starters!). Can someone work out if the hidden pref `general.buildID.override` is even used anymore in 64+, and if it is, does it override the now hardcoded timestamp?

**Comment by Atavic** [comment]
Original title: navigator.buildID has been removed

> ...buildID property, that returns the 14-digit build identifier of Firefox, is no longer available from web content.

**Comment by earthlng** [comment]
> Can someone work out if the hidden pref `general.buildID.override` is even used anymore in 64+, and if it is, does it override the now hardcoded timestamp?

the answer is in the commit at https://hg.mozilla.org/mozilla-central/rev/61b6c0110dea#l3.6

**if** RFP is enabled -> return the new fixed timestamp `20181001000000`
**else** if `general.buildID.override` is set -> return that value
**else** if URL is not `https://*.mozilla.org` -> return the fixed timestamp
**else** return the real buildID for all https://*.mozilla.org URLs

The buildID in the User-Agent is still hardcoded to "20100101"

**Comment by Thorin-Oakenpants** [comment]
> The buildID in the User-Agent is still hardcoded to "20100101"

I do not follow. Where is this old hardcoded value of `2010...`? Line 3?
```
L1 if RFP -> `2018..`
L2 else pref -> use that, hidden pref
L3 else if not https*mozzies -> fixed timestamp  <<-- THIS ONE?
L4 else -> real buildID
```

PS: soz for dumping the investigating on you (you know where i'm at with things)

**Comment by earthlng** [comment]
"20100101" is kind of a separate thing by now. Originally the buildID was exposed in the User-Agent string but they hardcoded that to "20100101" a long time ago.
The `if ... else` outlined above is about the JS object `navigator.buildID`.

I think they finally changed it now because for non-RFP users `navigator.buildID` allowed sites to easily detect even dot-releases like FF62.0.1, 62.0.2 etc. which in most cases wouldn't have been possible with feature detection alone.

If JS is allowed it's still easy to detect major FF versions though regardless of any prefs you may or may not have set/changed, including RFP.

**Comment by Thorin-Oakenpants** [comment]
* 1 : `general.buildID.override` only affects navigator buildID, which we already knew, but since the UA both in headers and JS were set as 20100101, then it could be used to hide the exact build date/time.
* 2 : bugzilla 583181 only deals with navigator buildID
* 3 : as per the Big E's code translation: excluding some mozilla domains and chrome, the value returned is `20181001000000`
* 4 : point 2+3 combined means we now have a couple of inconsistencies

---

* <FF64:
> UA (both HTTP & JS) return `20100101`
> buildID: returns `20100101` with RFP (or the override pref or an extension can change it)

* FF64+
> UA (both HTTP & JS) return `20100101`
> buildID: returns `20181001000000`  with RFP (or the override pref or an extension can change it)

Conclusion: So now (I assume this was not backported to ESR), ESR60 and FF60-63 have a different FP to FF64+. For no reason I can see, they may have tightened up on the default not leaking build+time to websites, but they have raised entropy in RFP, and that was what I was trying to work out (but didn't have a 64 set up until today).

**Comment by earthlng** [comment]
> raised entropy in RFP

You have to keep in mind that when you allow JS a site can easily detect your FF version anyway regardless of RFP. It was super easy to do before this change thanks to the buildID (if RFP was disabled) but now in FF64+ buildID is useless. I think it's a welcome change and sites have to work a tiny bit harder to detect the version.

**Comment by earthlng** [comment]
Yeah I don't understand why they didn't keep 20010101 but meh, it is what it is.

**Comment by Thorin-Oakenpants** [comment]
`¯\_(ツ)_/¯ `
