### ISSUE TITLE
1403: icon fonts: flip it and add a related pref

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#521]
reposted from #490 regards `gfx.downloadable_fonts.fallback_delay`

I think we should flip `1403` entirely. Making prefs active should "harden" things. Currently it's the reverse. Default is true which is what we are currently enforcing. Make it inactive, and add the delay pref.

```js
/* 1403: disable icon fonts (glyphs) (FF41) and local fallback rendering
 * [1] https://bugzilla.mozilla.org/789788
 * [2] https://trac.torproject.org/projects/tor/ticket/8455 ***/
   // user_pref("gfx.downloadable_fonts.enabled", false);
   // user_pref("gfx.downloadable_fonts.fallback_delay", -1);
```

Edit: Note on why it was at active true: I assume it's because too much broke for end users when false, and we can always control third party fonts with uM - or is this something else - fonts confuse me, @font-face is usually 3rd party right?. CSS Font Loading API is already disabled (1406). At inactive false, anyone who flips it themselves, then the breakage is on them.

Nits?

**Comment by Atavic** [comment]
> font-face is usually 3rd party, right?

According to the HTTP Archive, 67% of web pages now use custom fonts.
See: https://wp-rocket.me/blog/guide-web-font-optimization/

**Comment by earthlng** [comment]
> Note on why it was at active true: I assume it's because too much broke for end users when false

I think we enforced true because false also breaks fonts/icons in extensions

**Comment by Thorin-Oakenpants** [comment]
^^true, probably: not sure if I ever had mine at false, but I know Linux users can have issues when limiting (1401) `browser.display.use_document_fonts`=0 (and need to change the default serif font or something). And I had issues in extensions with "ligatures" (in Header Editor which gorhill helped me with and the HE guy had a workaround). Right now I still have issues in one extension (Window Resizer, see pic) but the tofu doesn't worry me) - but that's all with the pref `gfx.downloadable_fonts.enabled` at true.

![windowresizer](https://user-images.githubusercontent.com/16656956/47358898-b395cc00-d6ba-11e8-9350-8bd9f124400b.png)
*window resizer tofu!* The three saved sizes (and screen positions) equate to 1920x1080, 1600x900 and 1366x768 inner browser windows - so I can flip between them when I want (and also set it when I start because [Bug 1418537](https://bugzilla.mozilla.org/show_bug.cgi?id=1418537) where in FF62 I am 1px out, you need to check each release). Even when they move to viewport sizing and drop chrome sizing, this extension will still come in handy so I can snap to sizes that eliminate letterboxing (or lessen it to allow for findbar). Soz for going off topic.

Anyway: onus is now on end users :)

**Comment by Thorin-Oakenpants** [comment]
IDK .. I think it's a ligature. Anyway, its not worth worrying about, the missing glyph is a delete symbol :)

**Comment by Thorin-Oakenpants** [comment]
FYI: [here](https://github.com/FirefoxBar/HeaderEditor/issues/46#issuecomment-351438141) is gorhill's comment and sylingd's subsequent fix

**Comment by Maryse47** [comment]
> I know Linux users can have issues when limiting (1401) browser.display.use_document_fonts=0 (and need to change the default serif font or something). And I had issues in extensions with "ligatures" (in Header Editor which gorhill helped me with and the HE guy had a workaround)

@Thorin-Oakenpants It seems fonts are broken again with HE 4.0.0 release :disappointed:

**Comment by Maryse47** [comment]
https://github.com/FirefoxBar/HeaderEditor/issues/46#issuecomment-432600192
