### ISSUE TITLE
Contextual Feature Recommender (extension recommendations)?

### ISSUE THREAD

**Issue by smithfred** [ghacksuserjs/ghacks-user.js#525]
I just saw this appear in FF 63 (I saw the blue "Recommendation" URL bar pill, only briefly since it appeared just as I was navigating away):

https://techdows.com/2018/08/firefox-to-show-extension-recommendations.html
https://www.bleepingcomputer.com/news/software/firefox-to-recommend-extensions-related-to-sites-you-visit/

It didn't reappear on the same domain after revisiting, so I can't interact with the feature to see if it provides any more info. Moz doesn't seem to have any documentation on it either (release notes or otherwise) because they're apparently determined to cram FF full of as much questionable, undocumented crap as possible with no concern for user privacy these days it seems...

Any idea if there's a privacy implication for their implementation, or if it's just a static/local domain->recommendation mapping? The latter would be the competent approach, but I wouldn't put "oh, we just send every domain you visit to our shield studies server, we thought that would be fine" past them either any more. (I'm opted out of everything Shield Studies-related. In theory...)

The mentioned pref. in the above articles to disable it doesn't seem to exist in FF 63 by default BTW.

Edit: I found https://support.mozilla.org/en-US/kb/extension-recommendations which implies no data is sent, though the wording is a bit vague - "Mozilla does not collect or store your browsing history to make those recommendations".

**Comment by Thorin-Oakenpants** [comment]
`browser.newtabpage.activity-stream.asrouterExperimentEnabled`

According to our current diffs (62-63), it's a new pref with a default value of false (so it's in the ignore bin, if it ever flipped to true we would pick up on that. Note: we're also about to deal with activity stream no longer being a system addon).

**Comment by Thorin-Oakenpants** [comment]
I can't find it on DXR, SearchFox is giving me errors (for now). Looking at some bugzillas and google search results, this *was* a shield study but is I *think* is *now* part of core FF

Without finding some code (and the Big E to decipher it), I'm not sure what controls this, if anything. AS (activity stream) can't be disabled by removing the xpi anymore - and there doesn't seem to be a master switch, and until now, I haven't bothered with working AS out. My concern is despite not using AS for any new/blank/home tabs, that parts of it will still run - example: these CRF snippets (I'm not concerned about the data going to Mozilla, it's just annoying), or local data collection for analysis, etc.

Keep this ticket open, so we don't forget to investigate/add it to the likely 50+ AS prefs we will have to add to the user.js

**Comment by Thorin-Oakenpants** [comment]
From [These Weeks in FF 48](https://blog.nightly.mozilla.org/2018/10/27/these-weeks-in-firefox-issue-48/), under AS, is a link to https://mozilla.invisionapp.com/share/YWLSGDZGUSF#/screens

The opting out is in the doorhanger: both per site and a link to manage recommendation settings (under General>Browsing). The Weeks in FF48 As section on this looks incomplete (no link to a bugzilla and an empty bullet point). Like I said, I don't have a 63 right now, so I don't know if the UI has landed

**Comment by earthlng** [comment]
Hi,

from what I can gather CFR is all local at the moment with a [static hardcoded list of recommendations](https://hg.mozilla.org/mozilla-central/file/tip/browser/components/newtab/lib/CFRMessageProvider.jsm) which are triggered when you've visited certain domains x number of times (=based on visit-counts/frecency in your bookmarks/history DB). But it's still in the early testing phase and things can change quickly.

If I had to guess and assuming they'll continue CFR, it's possible that they'll change the mechanism to get updates for the recommendations list remotely but how they're triggered will probably stay the same ie local and no data ever needs to be sent.

Pref-wise it looks like `browser.newtabpage.activity-stream.asrouterExperimentEnabled` was removed in FF63 but there will be a new pref in FF64+ which should also show up in the UI.
If you saw these recommendations I guess you're part of the 10% or so of US users who were randomly selected. AFAIK you can prevent them from enabling these things for you by disabling system addon updates with `0505`.
If you want to disable all the ASrouter stuff which in FF63 seems to be onboarding, snippets and CFR (see `browser.newtabpage.activity-stream.asrouter.messageProviders` - onboarding + CFR = local, snippets = remote), setting `browser.newtabpage.activity-stream.feeds.asrouterfeed` to false should probably do the trick.

**Comment by earthlng** [comment]
Apparently it's not just in the US then and IDK how they enable these things for x% of users. Might be with shield studies, system addons, randomly sending out special app-updates or somehow with the Activity Stream newtab page.

In this case since CFR is all local I think it's not so bad. If they keep doing CFR the way it is I quite like it.
I also saw something that suggests that they're perhaps planning to highlight keyboard shortcuts for often-used actions which is a great idea IMHO. Yeah they maybe should have made an opt-out setting in the UI somewhere but then they might not get the feedback they're hoping for.
It's always easy to criticize but overall I think they're doing a good job with this.

**Comment by Atavic** [comment]
I warned you about Frecency: https://github.com/ghacksuserjs/ghacks-user.js/issues/128

[earthlng's link](https://github.com/ghacksuserjs/ghacks-user.js/issues/525#issuecomment-433614079) above is very frightening with all those amazon whitelists.

**Comment by earthlng** [comment]
frightening amazon whitelists? WTH are you talking about?! those aren't whitelisted, they're the domains you need to visit to be shown the CFR for that extension.

And there's absolutely nothing scary about frecency either. Please stop spreading FUD

**Comment by Thorin-Oakenpants** [comment]
i'll add `browser.newtabpage.activity-stream.asrouterExperimentEnabled` tot he current diffs under AS (so we don't forget) .. and close this

**Comment by Atavic** [comment]
> frightening amazon whitelists?
I now see it's related to this webext: https://addons.mozilla.org/en-US/firefox/addon/amazon-browser-bar/

*Not FUD*:  Amazon Assistant automatically collects information about websites you view where we may have relevant product or service recommendations when you are not interacting with Amazon Assistant. (amazon.com/gp/BIT/privacy)

**Comment by Atavic** [comment]
> frightening amazon whitelists?

I now see it's related to this webext:
https://addons.mozilla.org/en-US/firefox/addon/amazon-browser-bar/

*Non FUD Info*:
Amazon Assistant automatically collects information about websites you view where we may have relevant product or service recommendations when you are not interacting with Amazon Assistant.
(amazon.com/gp/BIT/privacy)

**Comment by earthlng** [comment]
nobody forces you to install that extension and apparently you can disable those questionable features:

> **What Choices Do I Have?** You can control collection of “Information We Collect When You Interact with Amazon Assistant” by disabling the relevant Amazon Assistant features in your Amazon Assistant settings. You can also control collection of “Information We Collect Automatically” by disabling the Configure Comparison Settings.

would I use it? Hell no! But 455,253 users seem to like it and it's currently the 21st most popular extension so who am I to judge?!

**Comment by Atavic** [comment]
[What Choices Do I Have?](https://www.amazon.co.uk/gp/help/customer/display.html/?nodeId=%20502584#GUID-A440AA65-7F7E-4134-8FA8-842156F43EEE__SECTION_392EAF4C83FD47A2A360EF81917F7FBE) Not so many IMHO

**Comment by Thorin-Oakenpants** [comment]
FYI: https://old.reddit.com/r/firefox/comments/9t393d/disabling_all_extension_recommendations_in_ff_v63/

from Dave Townsend, Firefox Architect at Mozilla
>  we're still experimenting with the feature, however Firefox 63 release shouldn't receive these recommendations, they were only targetted at beta. If you're on release are you by any chance running linux, in particular Fedora? We're aware of a bug that is causing recommendations to show up in release in that case

**Comment by smithfred** [comment]
I'm the reason he's asking that question ;)
