### ISSUE TITLE
bash script

### ISSUE THREAD

**Issue by bogachenko** [ghacksuserjs/ghacks-user.js#537]
Hi, I have a question about your script. 
https://github.com/ghacksuserjs/ghacks-user.js/blob/master/updater.sh

There are 2 mentions of two packages, wget and curl. These are packages that load something (in our case, user.js).
In this script, they are selected to choose from, because there is an "if" condition. The first package is "curl", but if it is not available (not installed or broken?), Then "wget" comes into play. However, what if there are none. ALL. NOT What then? second "if" is not there?
_this is not about debian distributions (for which they are available by default), but about (say) archlinux._
_On it, as far as I remember, you need to manually install it (although I could be wrong, I did not use it for a long time)._

and so it is possible to supplement the conditions on the verification (presence or absence) of these packages? Is there a guru js here?

I am not a guru in js, and maybe I’ll repeat myself I don’t understand. Explain to me?

_I hope I wrote without errors_ :cry:

**Comment by Atavic** [comment]
Are you using Arch, right? It's in Extra Repo: https://www.archlinux.org/packages/?name=wget

**Comment by bogachenko** [comment]
now there is no (win10), But I used it. and I don’t remember that he installed these packages by default

**Comment by claustromaniac** [comment]
Sound like a good idea to me.

It still might be a good plan to add a check for simply aborting when even perl is missing, though. There are a gazillion distros out there and more will spawn on time, we can't possibly know for sure whether they all have/will have one of those or not.

**Comment by overdodactyl** [comment]
Good point - do you think we should keep the wget and curl options, or just switch to perl entirely?

**Comment by claustromaniac** [comment]
At just 2 lines per additional check I'd just keep them all :) Then again, I'm not too finicky when it comes to etiquette and saving bytes and such... :sweat_smile:

**Comment by overdodactyl** [comment]
Sounds good! It looks like @claustromaniac already added a check in #540, so we're good there.

If curl is that widely used, the pearl option probably doesn't add a whole lot, but I can throw it in!

**Comment by earthlng** [comment]
Feel free to add a perl fallback but I think every system with Firefox installed will almost certainly also have curl or wget. At least so far nobody reported a problem and OP only guessed about Arch not having it.

**Comment by bogachenko** [comment]
@earthlng 

>and OP only guessed about Arch not having it

I am (practically) sure. 60 percent.
in base and base-devel they are not.
(I don’t know if you are using Linux, but) archlinux is installed along this guide https://wiki.archlinux.org/index.php/Installation_guide.

**Comment by earthlng** [comment]
@bogachenko pacman is a base package and curl is a dependency of pacman

**Comment by earthlng** [comment]
new version of the updater.sh is in the works so I'm closing this
