### ISSUE TITLE
ToDo: reassess [WARNING] and [SETUP] tags

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#545]
* [x] Note to self: we want a (breakage) tag on security.OCSP.require
* [x] update wiki implementation and troubleshooting pages

**Comment by Thorin-Oakenpants** [comment]
@earthlng umm, I just realized looking at someone's overrides, that `privacy.userContext.enabled` (1702) is default false. Is there any reason now ESR60 is out, that we don't make all or most of 1700s active? I vaguely remember an earlier discussion about it, but can't remember why

**Comment by Atavic** [comment]
*Tip* for *Warning* and *Choose* for *Setup*?

**Comment by Thorin-Oakenpants** [comment]
[Earthlng said](https://github.com/ghacksuserjs/ghacks-user.js/issues/438#issuecomment-440748648)
> They're perhaps hesitant about enabling containers because a lot of people still don't even understand what Private Browsing does and doesn't do.

So there's no *technical* reason anymore that we can't make section 1700 active

**Comment by Thorin-Oakenpants** [comment]
- I think we could restrict `[WARNING]` to items that have serious consequences (and this would probably mean they're all going to be inactive). I can see some existing tags can be changed to `[NOTE]`. eg 0850a
- `[SETUP]` could stay the same (stuff to look at when first getting the user.js), and could even supplement/mirror a relaxed sticky
- Those left could use a `[BREAKAGE]` tag, as long as the updated readme line says that it's not all inclusive (and refers to web content). Good example of this would be 1201

Note to self: we want a (breakage) tag on `security.OCSP.require`

**Comment by Thorin-Oakenpants** [comment]
I'm going thru playing with tags and I think we should do away with [SETUP] completely

`[WEB BREAKAGE]`, `[FF BEHAVIOR]`, and `[WARNING]` should be enough. Setting up means uses can just search for the first two for all the common items to consider (and we wouldn't need to use multiple tags for the same item, which we currently do). The definition of what each tag means would be outlined in the readme numbered items at the top.

so things like session restore, clearing shit on close, locationbar dropdown/keywords not working etc is all about FF internally, UX, and chrome behavior. 

By breaking it into app changes vs web breakage, it should also be easier for end users to troubleshoot.

PS: so far got [warning] down to 8 items (I changed em to setup or breakage at the moment).
- warning: 8
- setup: 27
- breakage: 17

----

I have concerns though that people will get the wrong gist of things: eg, consider this

```js
/** SSL (Secure Sockets Layer) / TLS (Transport Layer Security) ***/
/* 1201: disable old SSL/TLS "insecure" renegotiation (vulnerable to a MiTM attack)
 * [BREAKAGE] <2% of secure sites do NOT support the newer "secure" renegotiation, see [2]
 * [1] https://wiki.mozilla.org/Security:Renegotiation
 * [2] https://www.ssllabs.com/ssl-pulse/ ***/
user_pref("security.ssl.require_safe_negotiation", true);
```

^ pref is active and we're saying the pref as active will cause breakage. That's perfect. Now look at this next one

```js
/* 1263: disable DHE (Diffie-Hellman Key Exchange)
 * [BREAKAGE] May break obscure sites, but not major sites, which should support ECDH over DHE
 * [1] https://www.eff.org/deeplinks/2015/10/how-to-protect-yourself-from-nsa-attacks-1024-bit-DH ***/
   // user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
   // user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
```

^ This is not clear. But our logic would say that IF you make the pref active, it breaks (we could clarify the one liner no probs anyway, and do this consistently in the user.js). Now look at a third one

```js
/* 1605: ALL: disable spoofing a referer
 * [WARNING] Spoofing effectively disables the anti-CSRF (Cross-Site Request Forgery) protections that some sites may rely on ***/
user_pref("network.http.referer.spoofSource", false);
```

^ Yes, I know I'm looking at a warning tag, but imagine it's a breakage one. Pref is active but our warning is for when it's the opposite value. This is not consistent.

So we need to be careful here, because anyone quickly skimming thru would find the first breakage, disable the pref, second one, disable it and could end up with the wrong (default) value. Bad example: this pref is actually default false, but you get my point (I hope).

---

Anyway, am still playing. Will do a PR later (maybe tonight, maybe next week), but feel free to chime in with your thoughts.

My methodology
- reduce warning (some to note)
- make all others breakage or behavior
- post PR
- review the info is clear and the method consistent
- add more breakage or behavior tags
- commit

Breakage/Behavior tags form the basis for a relaxed sticky

**Comment by atomGit** [comment]
i think anything that makes it easier for users, as well as for yourselves, is worthwhile

the purpose of the tags is largely/partly so users can easily sift through the file and so why not use the [setup] tag for every option that is marked with [setup], as well as all the other tags - this makes it easy to find and F3 through the file and address everything in one shot, whilst still being able to find options matching a different tag when necessary

**Comment by Thorin-Oakenpants** [comment]
^ I did a PR. It's actually a much secksier and better approach (so far). Feel free to chime in on the PR (or here). It's not finished, we could look at adding/removing some

**Comment by Thorin-Oakenpants** [comment]
Another option would be to use `[SETUP-BREAKAGE]` and `[SETUP-BEHAVIOR], uses could them search for `[setup` and get the lot, or `breakage]` / `behavior]` for a more refined approach

**Comment by Thorin-Oakenpants** [comment]
Wiki Implementation and Troubleshooting pages updated
