### ISSUE TITLE
RFP: comparing TB vs FF [1401493]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#550]
~~Locked topic~~ (no longer locked) because I'm working on it, in dribs and drabs, and I only want to present the results: will keep editing OP as I do them. If you have a question, start a new topic.

edit: @tomrittervg , FYI for the bugzilla

---

### Tickets

Old: [1414001,1413842,1413837,1413707](https://bugzilla.mozilla.org/buglist.cgi?bug_id=1414001,1413842,1413837,1413707)
New: [1401493](https://bugzilla.mozilla.org/show_bug.cgi?id=1401493)

### Test sites

Original list
* [x] https://fpcentral.irisa.fr/
* [x] https://browserleaks.com/javascript
* [x] https://panopticlick.eff.org/
* :x:  https://browserprint.info/ - see note below

Note: browserprint always fails with "An error has occured" message. This is even in a nilla FF profile without RFP. Is it just me?

Let's (maybe) include MOAR tests
* [x] https://amiunique.org/ (it doesn't show anything new)
* [x] https://whoer.net/ (Extended Test)
* [x] https://valve.github.io/fingerprintjs2/  (it doesn't show anything new, except maybe "has lied" logic)

Maybe some individual tests (I have some more ideas, will add later)
* [x] https://browserleaks.com/css
* [x] http://browserspy.dk/math.php (hey, it was worth it! just in case)
* [x] https://www.howsmyssl.com/ (cipher suites)

### Browsers

- TBB 8.0.3 & FF 64.0b11 (and halfway thru my tests I updated to 64.0b12)
   * note: all test images are clearly marked
- New nilla profiles (FF has only one change, to enable RFP)
- Platform: Windows 7, 64bit
- If prompted for canvas, I ignored the prompt, or denied it

### Browserleaks

Browserleaks has a window and an iframe mode. So I compared those as well. The differences are (in TBB):
- Screen Resolution
   * window: `1000x1000...`
   * iframe: `0x0...`
- Permissions API Support
   * window: global for geo, notifications and push: `Prompt`
   * iframe: global for geo, notifications and push: `n/a`

Update: These differences and values were the same between FF and TBB

### Summary

I shall put this the next comment, and update it as I go. I will report differences by result, rather than test site, as a lot of overlap. Subsequent comments are to attach images etc.

**Comment by Thorin-Oakenpants** [comment]
irisa
![compare_irisa](https://user-images.githubusercontent.com/16656956/48943546-77ed5c80-ef1b-11e8-8b7d-fbf29d901f5f.png)

**Comment by Thorin-Oakenpants** [comment]
browserleaks
![compare_bl](https://user-images.githubusercontent.com/16656956/48948930-2b5f4c80-ef2e-11e8-9bca-8e399fead93b.png)

**Comment by Thorin-Oakenpants** [comment]
whoer
![compare_whoer](https://user-images.githubusercontent.com/16656956/48959733-3f6f7200-ef5f-11e8-8bf3-67279566cf41.png)

**Comment by Thorin-Oakenpants** [comment]
fingerprintjs2/: https://valve.github.io/fingerprintjs2/

Note: like browserleaks, the userAgent is the same, which is not what Whoer or Panopticlick, among others, say. This needs investigation. Clearly something is different.

![compare_fingerprintjs2](https://user-images.githubusercontent.com/16656956/48960780-82354800-ef67-11e8-9472-9bb8aa9bf389.png)

**Comment by Thorin-Oakenpants** [comment]
useragent: http://browserspy.dk/useragent.php

It is only the UA from headers that is different. JS is the same.

![compare_ua](https://user-images.githubusercontent.com/16656956/48963126-f2ea5d80-ef83-11e8-9cb5-86ea023d740c.png)

**Comment by Thorin-Oakenpants** [comment]
css media queries: https://browserleaks.com/css
![compare_cssmedia](https://user-images.githubusercontent.com/16656956/48963210-cb949000-ef85-11e8-94d9-19d94d73cc4c.png)

**Comment by Thorin-Oakenpants** [comment]
math: http://browserspy.dk/math.php FYI and peace of mind (not that I expect IEEE standards or lack of them to differ in firefox based builds)
![compare_math](https://user-images.githubusercontent.com/16656956/48963518-fda8f080-ef8b-11e8-93f4-058b97bb8095.png)

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg - the summary in comment 2 uses syntax `Bug xxxx` so you can copypasta it as required for the bugzilla if you want to.

**Comment by Thorin-Oakenpants** [comment]
Well, you want FF default + RFP vs TBB diffs ...

https://gist.github.com/overdodactyl/934ab50cad62166e3a108210e141bcc8

![pbmode](https://user-images.githubusercontent.com/16656956/48964484-49fe2b80-efa0-11e8-998d-86e864aff34e.png)

**Comment by Thorin-Oakenpants** [comment]
That wasn't why we enabled DNT. The Tor patch to change headers to 2 OSes but leave JS at 4 OSes will be upstreamed to Firefox. NFI why they dropped the `Win64; x64;` - that seems a little strange.

And these tests are only on Windows. It would be nice to confirm what http://browserspy.dk/useragent.php says for Mac, Linux, and Android

**Comment by earthlng** [comment]
> It would be nice to confirm what http://browserspy.dk/useragent.php says for Mac, Linux, and Android

probably this: https://dxr.mozilla.org/mozilla-central/source/browser/components/resistfingerprinting/test/browser/browser_navigator.js#39-44

**Comment by earthlng** [comment]
TBB matches nilla ESR60.3 and none of the `security.ssl3.*`  prefs in TBB are set to false.
I assume the discrepancy is because ESR uses an older draft version of TLS1.3 than Release. Or something like that

**Comment by Thorin-Oakenpants** [comment]
FYI: TB patched Pointer Events a few hours ago: https://trac.torproject.org/projects/tor/ticket/25794
