### ISSUE TITLE
ciphers followup

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#552]
Here's a pretty picture: https://www.howsmyssl.com/
![compare_ciphers](https://user-images.githubusercontent.com/16656956/49011271-c7c36200-f16d-11e8-9b22-fef9ec0b87eb.png)

FYI: current js
```js
/* 1263: disable DHE (Diffie-Hellman Key Exchange)
 * [WARNING] May break obscure sites, but not major sites, which should support ECDH over DHE
 * [1] https://www.eff.org/deeplinks/2015/10/how-to-protect-yourself-from-nsa-attacks-1024-bit-DH ***/
   // user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
   // user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);
```
and
```js
/* 1264: disable the remaining non-modern cipher suites as of FF52
 * [NOTE] Commented out because it still breaks too many sites ***/
   // user_pref("security.ssl3.rsa_aes_128_sha", false);
   // user_pref("security.ssl3.rsa_aes_256_sha", false);
```

So it begs the question, why did Tor Browser drop the first red pair, and why don't we add those to the user.js (inactive of course) - assuming they're not new ciphers added since ESR60 (I haven't checked)

**Comment by Thorin-Oakenpants** [comment]
hang on a sec, I better work out what 1261 and 1262 map to

**Comment by Atavic** [comment]
Both red pairs appear in the [HTTP2 Cipher Suite Black List](https://http2.github.io/http2-spec/#rfc.section.A): while firefox de-prioritizes them by putting on bottom, others - like google chrome - blacklist them.

OpenSSL ciphers: https://www.openssl.org/docs/man1.1.1/man1/ciphers.html

Related: https://github.com/mozilla/server-side-tls/issues/115

**Comment by Thorin-Oakenpants** [comment]
The Big E said
> TBB matches nilla ESR60.3 and none of the `security.ssl3.*`  prefs in TBB are set to false.
I assume the discrepancy is because ESR uses an older draft version of TLS1.3 than Release. Or something like that

Well, three of the four red dots are in our js and are old AF. I'll take a stab in the dark and guess TB patched em out, hence no prefs (or they made the prefs hidden). I'll see if I can find any tor tickets. Also, not sure why FF are dragging their heels on them (I do remember seeing a bugzilla about this)

Now, what about the 4th red dot that isn't in our js, we should add that (inactive)

**Comment by Thorin-Oakenpants** [comment]
Here's a 3 year old ticket relating to the two prefs in 1263: https://trac.torproject.org/projects/tor/ticket/17374

**Comment by earthlng** [comment]
https://hg.mozilla.org/releases/mozilla-release/rev/14803cf456f3

**Comment by Thorin-Oakenpants** [comment]
FYI, I read a ticket before about ESNI breaking when a particular ciphers was disabled (although it was marked as fixed).

Definitely not saying we should make any of these active, but (and that link just confuses the F out of me)
- should we add the missing red dot
- if we add the missing red dot, then should we group 1262 better and split off the green dot

Please advise

**Comment by Thorin-Oakenpants** [comment]
Okie dokie

**Comment by Thorin-Oakenpants** [comment]
FYI: https://www.nccgroup.trust/us/our-research/the-9-lives-of-bleichenbachers-cat-new-cache-attacks-on-tls-implementations/

**Comment by Thorin-Oakenpants** [comment]
^^ related to this, but NOT the bugzilla to do with Bleichenbachers :cat2: stuff

Article: (emphasis mine)
> The main difficulty we face is how to perform the thousands of oracle queries required before the browser’s imposed timeout (which is 30 seconds for almost all browsers, **with the exception of Firefox which can be tricked into extending this period**).

new ziilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1511681
