### ISSUE TITLE
ghacks-user.js updater for macOS and Linux v2.0 !

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#553]
new version 2.0 of the **ghacks-user.js updater for macOS and Linux** is out !

Lot's of **new command-line arguments** and prettier than ever with **colored output**! *get it while it's hot*

updated wiki: https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-Updater-Scripts

FYI: the new arguments can be written separately or together. Examples:

```txt
./updater.sh -sdm
./updater.sh -sd -o relaxed.js
./updater.sh -s -d
```

THANKS @overdodactyl ! (and @claustromaniac for your input and help with testing!)

**Comment by overdodactyl** [comment]
Big thanks to @earthlng as well! You helped a ton with that :)

**Comment by earthlng** [comment]
the new arguments can be written separately or together. Examples:

```txt
./updater.sh -sdm
./updater.sh -sd -o relaxed.js
./updater.sh -s -d
```

**Comment by Atavic** [comment]
This will be getting more folks involved #539
