### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by bogachenko** [ghacksuserjs/ghacks-user.js#557]
#550 Do you like ~Elon Musk~?
All actions carried out on firefox

my furyfox
![111111111111111111111111222](https://user-images.githubusercontent.com/8535285/49088629-94f29a00-f251-11e8-9b16-4305f2a8e6c4.png)

my system
windows 10 x64

1. your first screenshot is similar to mine (I will not upload) https://amiunique.org/
2. on this too https://panopticlick.eff.org/
but
3. on this no https://fpcentral.irisa.fr/
for some reason, it's empty here ...
![1](https://user-images.githubusercontent.com/8535285/49086134-b486c400-f24b-11e8-8f5b-b94f53d6cf35.png)
4. https://browserleaks.com/javascript
![2332](https://user-images.githubusercontent.com/8535285/49086188-cf593880-f24b-11e8-9d5e-2fd107dbb72f.png)
![4343](https://user-images.githubusercontent.com/8535285/49086430-67efb880-f24c-11e8-8604-d7c1df382a97.png)
![222222222222](https://user-images.githubusercontent.com/8535285/49086756-2dd2e680-f24d-11e8-86b2-922169fb1b08.png)
![2222222222222222222222222222222211111111111111111111](https://user-images.githubusercontent.com/8535285/49086898-928e4100-f24d-11e8-8982-96a9c1ccba7f.png)
5. https://whoer.net/ (click on Extended Version)
![3333333333333](https://user-images.githubusercontent.com/8535285/49088181-9c657380-f250-11e8-8a78-d4f103ad6a1f.png)
![44444444444444444455](https://user-images.githubusercontent.com/8535285/49088323-ee0dfe00-f250-11e8-87bb-cc11755d695a.png)
![555555555555555](https://user-images.githubusercontent.com/8535285/49088465-3e855b80-f251-11e8-8672-63a5011af6bb.png)

**to be continued**

**Comment by bogachenko** [comment]
My user agent is shown above, but I'll throw it off again http://browserspy.dk/useragent.php
![default](https://user-images.githubusercontent.com/8535285/49088798-f4e94080-f251-11e8-8f5e-690464d72e68.png)

**Comment by bogachenko** [comment]
https://browserleaks.com/css
![default](https://user-images.githubusercontent.com/8535285/49088941-53aeba00-f252-11e8-97ae-31c2e5753b6c.png)

**Comment by bogachenko** [comment]
https://browserleaks.com/css
![default](https://user-images.githubusercontent.com/8535285/49088941-53aeba00-f252-11e8-97ae-31c2e5753b6c.png)
![default](https://user-images.githubusercontent.com/8535285/49089107-b4d68d80-f252-11e8-815e-3637ad7a93d4.png)

**Comment by bogachenko** [comment]
http://browserspy.dk/math.php same here

**Comment by bogachenko** [comment]
SYKA BLAT

I am blind. The first time I watched this thread, it was closed #550 .
the second time (now) did not scroll down .. I thought that it was closed.

**I would not create a new thread ... and would write there ... hell**

**Comment by Thorin-Oakenpants** [comment]
Are all these tests on a new FF profile with just RFP enabled? Because comparing any **modified** profile against the other thread makes no sense. It needs to be like for like (except OS). Yours is also 63, and I used 64 - eg Pointer Events were (partially) covered in RFP in 64+, and more in 65+.

The PB Mode bits are cut n pasted from different screenshots, you can't test normal and PB mode windows in the same page, think about it :)

The global permissions (geo etc), when you load the page it is using top document, and displays the correct value. If you toggle to iframe **and then back**, it sticks with iframes's `n/a`

With so many differences, I think this is your modified profile, which isn't much use for comparisions

**Comment by bogachenko** [comment]
> new FF profile with just RFP

no. I missed it. all modification in the user.js file Which was taken from you. and slightly modified. but essentially identical.

my fool (cubed)

**Comment by Thorin-Oakenpants** [comment]
> cubed

```
<sup>3</sup>
```
MyFool<sup>3</sup> :trollface: 

PS: you should sanitize your images of identifying info. eg all that IP, service provider, ISP local time, etc stuff

**Comment by claustromaniac** [comment]
That's mean :jeans:. Bad, bad :jeans:!

**Comment by bogachenko** [comment]
@claustromaniac By the way, I have long wanted to ask why are you sending jeans? what does it mean

**Comment by claustromaniac** [comment]
:jeans: = pants = Thorin-Oaken**Pants** :grin:

**Comment by bogachenko** [comment]
oooooo
