### ISSUE TITLE
Settings to change over ownbit's user.js

### ISSUE THREAD

**Issue by ngx3** [ghacksuserjs/ghacks-user.js#560]
Hey guys. So Im wondering what the difference in settings is between ghost's user.js and ownyourbit's user.js? Cuz I'm tired of having to put searx.me everytime I need to search something, cuz the homepage doesn't save, I was doin a lil diggin and found this: https://github.com/nachoparker/firefox-ownyourbits-user.js and seems like it's yours but **does not remove your history and stored data**  and it saves/shows me my homepage.

If you ask why i dont use that then it's cuz this is updated frequently.

**Comment by claustromaniac** [comment]
> between **ghost**'s user.js

Are you referring to this @ghost? That account belongs to GitHub (not to a person).

@nachoparker's repository (the one you linked) is a modified fork (clone) of ghacks-user.js (this repository). His is intended to be used as an override of this one. 

I'm not sure which other repo you are talking about, but you should really read the [wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview) to get started with this one :sweat_smile:

It doesn't take that long and it really pays off, I promise!

**Comment by Thorin-Oakenpants** [comment]
- Article: [Customize Firefox for privacy and security with a custom user.js](https://ownyourbits.com/2018/09/08/customize-firefox-for-privacy-and-security-with-a-custom-user-js/)
- OwnYourOwnBits = nachoparker
- OwnYourOwnBits [user.js](https://github.com/nachoparker/firefox-ownyourbits-user.js)
- OwnYourOwnBits [user-overrides.js](https://github.com/nachoparker/firefox-ownyourbits-user.js/blob/master/user-overrides.js)

Note that OwnYourOwnBits is ~~using~~ based on a **2½ month old version** of ours: see his [commits](https://github.com/nachoparker/firefox-ownyourbits-user.js/commits/master) where he has actually modified the user.js itself quite heavily (e.g. [this one](https://github.com/nachoparker/firefox-ownyourbits-user.js/commit/fdd4a6a7c342d4e997746116d47d37a04c81d62e) ), despite having an **overrides** js

His repo doesn't play nice with the original source, it would have been far better if it just had his changes in the one file (overrides). I have no idea why he did it like that, and this is why you can't easily tell what the heck is going on.

Take a copy of `ghacks user.js`, Take `OwnYourOwnBits's user.js` and **append** his `overrides js`. Then compare the two files. You can use [Compare-UserJS](https://github.com/claustromaniac/Compare-UserJS)

Have fun.

**Comment by claustromaniac** [comment]
> he has actually modified the user.js itself quite heavily

I didn't notice that when I listed his overrides here `https://github.com/ghacksuserjs/ghacks-user.js/issues/438#issuecomment-441490649`

I guess I'll create a diff.

**Comment by ngx3** [comment]
Offhand do you know the perf for enabling a homepage? Everytime I open firefox up I need to input the search engine address. How do I append overrides to both user files?
Thanks.

**Comment by earthlng** [comment]
> not sure where to start. Offhand do you know the perf for enabling a homepage?

how about you start at the top? If you're not willing to read through it at least once then this user.js is probably not for you

**Comment by Thorin-Oakenpants** [comment]
> Everytime I open firefox up I need to input the search engine address.

I don't understand. Is this the same question as #559 ?

> perf

perf is short for performance, pref is short for preference. I'm sure you know that, and it was just a typo :) I do em myself, typos .. they overwork me .. at night mostly

**Comment by Thorin-Oakenpants** [comment]
> Everytime I open firefox up I need to input the search engine address.

Or do you mean you want the start page to be google.com or something? As earthlng said, it's at the top.  Settings 0103 and 0104. Comment those out, go to Options >  Home > New Windows and Tabs > and set a custom URL (eg google) for homepage/newwindows and for newtabs

**Comment by ngx3** [comment]
When I open a new tab it's Firefox's default page, I want to put my homepage on there. And when I open a new tab to search (see images below,) results happen. Startpage is my default 
![test search](https://user-images.githubusercontent.com/16364958/49334388-00669f80-f5a3-11e8-9ff2-99f6d755267d.png)
![test search 2](https://user-images.githubusercontent.com/16364958/49334389-00669f80-f5a3-11e8-9302-0c6c276791de.png)
![default search engine](https://user-images.githubusercontent.com/16364958/49334390-00669f80-f5a3-11e8-82d6-363f9e41492a.png)

**Comment by Atavic** [comment]
@ngx3
Related to #559

**Comment by earthlng** [comment]
@ngx3 IDK if you noticed it but the user.js is organized in groups/sections. Here they are:
- 0100: STARTUP
- 0200: GEOLOCATION
- 0300: QUIET FOX
- 0400: BLOCKLISTS / SAFE BROWSING / TRACKING PROTECTION
- 0500: SYSTEM ADD-ONS / EXPERIMENTS
- 0600: BLOCK IMPLICIT OUTBOUND
- 0700: HTTP* / TCP/IP / DNS / PROXY / SOCKS etc
- 0800: LOCATION BAR / SEARCH BAR / SUGGESTIONS / HISTORY / FORMS
- 0900: PASSWORDS
- 1000: CACHE
- 1200: HTTPS ( SSL/TLS / OCSP / CERTS / HSTS / HPKP / CIPHERS )
- 1400: FONTS
- 1600: HEADERS / REFERERS
- 1700: CONTAINERS
- 1800: PLUGINS
- 2000: MEDIA / CAMERA / MIC
- 2200: WINDOW MEDDLING & LEAKS / POPUPS
- 2300: WEB WORKERS
- 2400: DOM (DOCUMENT OBJECT MODEL) & JAVASCRIPT
- 2500: HARDWARE FINGERPRINTING
- 2600: MISCELLANEOUS
- 2700: PERSISTENT STORAGE
- 2800: SHUTDOWN
- 4000: FIRST PARTY ISOLATION
- 4500: privacy.resistFingerprinting
- 4600: RFP (4500) ALTERNATIVES
- 4700: RFP (4500) ALTERNATIVES - NAVIGATOR / USER AGENT (UA) SPOOFING
- 5000: PERSONAL
- 9999: DEPRECATED / REMOVED / LEGACY / RENAMED

with that information now at hand, can you tell me in which of those sections you'd expect the problematic pref to be most likely located?

@Thorin-Oakenpants if you don't want to list the headers in the user.js itself, maybe it would help some people to at least have it in the README.MD?

**Comment by Thorin-Oakenpants** [comment]
TBH, they stick out like dog's :balls: and we expect people to read the thing. In the first scroll (and a bit) of my mouse, I get to clearly see `0100: STARTUP and then `0200: GEO...`. It's pretty obvious.

But, no we don't have an index and the sections are spread over 1800 lines.

Readme can definitely have one, because it can be behind a collapsible element. e.g.
> The ghacks user.js is categorized into logical sections blah blah.Click here for the index

But do we really want to add another 31+ lines to the js before the user even gets to the settings?

**Comment by ngx3** [comment]
> @ngx3 IDK if you noticed it but the user.js is organized in groups/sections. Here they are:
> with that information now at hand, can you tell me in which of those sections you'd expect the problematic pref to be most likely located?
> @Thorin-Oakenpants if you don't want to list the headers in the user.js itself, maybe it would help some people to at least have it in the README.MD?

You guys know exactly where the majority of stuff are organized. I was searching in the vicinity of STARTUP and tbh after I read so much skipping down several sections everything began to seem similar. 

Thanks for your work.

**Comment by ngx3** [comment]
Oh I already found it, but thanks anyways.
