### ISSUE TITLE
uhhh

### ISSUE THREAD

**Issue by bogachenko** [ghacksuserjs/ghacks-user.js#561]
// The time of inactivity of the user through which the browser will begin to save the session
user_pref("browser.sessionstore.idleDelay", 720000);

/* Preloading documents or resources specified via <link rel = "preload"> */
user_pref("network.preload", false);

// Predictor (formerly Seer)
// https://hg.mozilla.org/releases/mozilla-esr45/file/87a22e023b10fc3116f333e313934d38cd533ce0/netwerk/base/Predictor.cpp#l972
user_pref("network.predictor.enable-hover-on-ssl", false);
// https://bugzilla.mozilla.org/show_bug.cgi?id=1016628
// https://bugzilla.mozilla.org/show_bug.cgi?id=1271944
// https://hg.mozilla.org/releases/mozilla-release/file/c1de04f39fa956cfce83f6065b0e709369215ed5/netwerk/base/Predictor.cpp#l1301
~user_pref("network.predictor.enable-prefetch", false);~ do you have it
user_pref("network.predictor.prefetch-rolling-load-count", 0);

Disable preconnects and preresolves
https://hg.mozilla.org/releases/mozilla-release/file/c1de04f39fa956cfce83f6065b0e709369215ed5/netwerk/test/unit/test_predictor.js#l405
why 101? look url
user_pref("network.predictor.prefetch-min-confidence", 101);
user_pref("network.predictor.preconnect-min-confidence", 101);
user_pref("network.predictor.preresolve-min-confidence", 101);

trackingprotection
// https://hg.mozilla.org/releases/mozilla-beta/file/00bcc10b3bdc/browser/base/content/browser-trackingprotection.js#l6
//user_pref("privacy.trackingprotection.introCount", 1);

// PingCentre
// https://bugzilla.mozilla.org/show_bug.cgi?id=1390249
// https://hg.mozilla.org/releases/mozilla-release/rev/944ab211fc31
user_pref("browser.ping-centre.telemetry", false);
user_pref("browser.ping-centre.log", false);
user_pref("browser.ping-centre.staging.endpoint", "");
user_pref("browser.ping-centre.production.endpoint", "");

**Comment by bogachenko** [comment]
was it already?

**Comment by bogachenko** [comment]
// Until https://bugzilla.mozilla.org/show_bug.cgi?id=1446472 is solved fall
// back to old canvas behavior.
pref("privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts", false);
tor
***

**Comment by bogachenko** [comment]
// https://bugzilla.mozilla.org/show_bug.cgi?id=888268
// https://bugzilla.mozilla.org/show_bug.cgi?id=1156249
// https://hg.mozilla.org/releases/mozilla-esr45/file/2786beb35a3825b68651e2bf22ce06b84ff31ee3/modules/libpref/init/all.js#l1219
// https://hg.mozilla.org/releases/mozilla-esr45/file/2786beb35a3825b68651e2bf22ce06b84ff31ee3/netwerk/base/Tickler.cpp#l159
user_pref("network.tickle-wifi.enabled", false);

**Comment by bogachenko** [comment]
_curve translation (my translation) is better to google_
/* Disable the display of the text of the password by clicking on the corresponding input field */
user_pref("signon.rememberSignons.visibilityToggle", false);

**Comment by bogachenko** [comment]
??
https://bugzilla.mozilla.org/show_bug.cgi?id=939318
user_pref("network.notify.changed", false);

**Comment by bogachenko** [comment]
# SO U SAY?

**Comment by Thorin-Oakenpants** [comment]
> browser.cache.frecency_experiment
- deprecated, I don't think we need any more links

> extensions.webcompat-reporter.newIssueEndpoint
- already covered by 0518 extensions.webcompat-reporter.enabled

> app.normandy.api_url
- was there a question with this? it's already in the user.js see 0503

> network.notify.changed
- this is internal AFAICT, and all the necko/seer/telemetry etc stuff is already disabled

> signon.rememberSignons.visibilityToggle
- see https://bugzilla.mozilla.org/show_bug.cgi?id=1183908 - this is just an OLD pref used to toggle a doorhanger when they rolled out a new feature

> privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts
- no need for this, the default is to autodecline (true) and this reduces canvas prompt fatique. Changing it to false would just piss RFP users off. Site permissions always shows if a canvas is present in the urlbar, so users can STILL override it (without being prompted) if there is breakage

> font.system.whitelist
- Let Tor Uplift set the values after they bundle fonts in RFP. Anything else and you will stick out like a :dog2: 's balls. Meanwhile for those that use it `browser.display.use_document_fonts`=0 helps a lot, BUT, as seen with https://browserleaks.com/fonts , we're all f%&^%ked anyway until RFP helps us

> privacy.trackingprotection.introCount
- "sounds" like a simple internal thing for educating users or highlighting a new feature

> network.tickle-wifi.enabled
- haven't looked - maybe the Big E can work out why tickling is a danger

> the rest (basically the first post)
- I don't know where to start, we already cover all of this AFAIK

**Comment by Thorin-Oakenpants** [comment]
did I miss anything? @earthlng , if you see anything that needs attention, lemme know, otherwise feel free to comment if required and then close

**Comment by Atavic** [comment]
> network.predictor.preconnect-min-confidence

Explained [here](https://wiki.mozilla.org/Project_Dory) under *Results*

**Comment by Thorin-Oakenpants** [comment]
> browser.ping-centre.log
- is default false

> ping center stuff
- is controlled by `datareporting.healthreport.uploadEnabled` (0333)

> network.predictor.enable-hover-on-ssl
- on DXR it doesn't seem to be used. We already have `network.predictor.enabled` (0603a). The hover-on-ssl looks like an old pref which could be used as a subset - eg treat secure sites differently to insecure ones (which fits the Mozilla mantra of not adding new tech to insecure sites, and removed old tech from them as well - in the move to deprecate  insecureHTTP)

> network.preload
- is default false
