### ISSUE TITLE
cleanup fixup session restore prefs

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#563]
clean up the tags, descriptions if needed. e.g AFAIK session data is still being recorded despite 1020, and if we have 0102 as 0, then it becomes redundant. And in fact the second pref in 1020 (number of windows) is just an extra hindrance to those who want to enable sessions.

I have also experienced a crash which asked to, and did, restore a window and I think, some tabs (I only ever have one window open).

The Big E even said that thse two prefs 1020 don't block session restore

**Comment by Thorin-Oakenpants** [comment]
current session restore prefs (assuming PR on tag info is kept as is right now)

```js
/* 0102: set START page (0=blank, 1=home, 2=last visited page, 3=resume previous session)
 * [SETTING] General>Startup>Restore previous session ***/
user_pref("browser.startup.page", 0);
```

0102 is fine, this is just telling FF what to start with. Has nothing to do with blocking persistent storage of any kind.

```js
/** SESSIONS & SESSION RESTORE ***/
/* 1020: disable the Session Restore service completely
 * [BEHAVIOR] This also disables the "Recently Closed Tabs" feature
 * It does not affect "Recently Closed Windows" or any history. ***/
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
/* 1021: disable storing extra session data [BEHAVIOR]
 * extra session data contains contents of forms, scrollbar positions, cookies and POST data
 * define on which sites to save extra session data:
 * 0=everywhere, 1=unencrypted sites, 2=nowhere ***/
user_pref("browser.sessionstore.privacy_level", 2);
/* 1022: disable resuming session from crash [BEHAVIOR] ***/
user_pref("browser.sessionstore.resume_from_crash", false);
/* 1023: set the minimum interval between session save operations - increasing it
 * can help on older machines and some websites, as well as reducing writes, see [1]
 * Default is 15000 (15 secs). Try 30000 (30sec), 60000 (1min) etc
 * [BEHAVIOR] This can also affect entries in the "Recently Closed Tabs" feature:
 * i.e. the longer the interval the more chance a quick tab open/close won't be captured.
 * This longer interval *may* affect history but we cannot replicate any history not recorded
 * [1] https://bugzilla.mozilla.org/1304389 ***/
user_pref("browser.sessionstore.interval", 30000);
```

- 1020 doesn't do what it says it does. I'd even say we could make max_windows inactive (if people want session restore, why limit them to the last active window) assuming the pref does what it says it does. I suspect that the value of `0` no longer (or never did) work for these prefs? Something has changed.
- 1021 should be fine (not sure how to test) - keep active
- 1022 should be fine, but needs a test - suggest we could even make this inactive (I have code to trigger a crash)
- 1023 is fine

The other pref to consider is `user_pref("browser.sessionstore.max_resumed_crashes", 0` from someone's massive pref dump. I don't think this will do anything.

The question is, if we cannot block session store data being written to the disk, then we should probably do away with those prefs (looking at you, 1020). Seems pointless limiting number of tabs/windows

**Comment by Thorin-Oakenpants** [comment]
For reference: [source](https://gitweb.torproject.org/tor-browser.git/plain/browser/app/profile/firefox.js) TB 60.3.0esr-8.5-1

```js
pref("browser.sessionstore.resume_from_crash", true);
pref("browser.sessionstore.resume_session_once", false);

// Minimal interval between two save operations in milliseconds (while the user is active).
pref("browser.sessionstore.interval", 15000); // 15 seconds

// Minimal interval between two save operations in milliseconds (while the user is idle).
pref("browser.sessionstore.interval.idle", 3600000); // 1h

// Time (ms) before we assume that the user is idle and that we don't need to
// collect/save the session quite as often.
pref("browser.sessionstore.idleDelay", 180000); // 3 minutes

// on which sites to save text data, POSTDATA and cookies
// 0 = everywhere, 1 = unencrypted sites, 2 = nowhere
pref("browser.sessionstore.privacy_level", 0);
// how many tabs can be reopened (per window)
pref("browser.sessionstore.max_tabs_undo", 10);
// how many windows can be reopened (per session) - on non-OS X platforms this
// pref may be ignored when dealing with pop-up windows to ensure proper startup
pref("browser.sessionstore.max_windows_undo", 3);
// number of crashes that can occur before the about:sessionrestore page is displayed
// (this pref has no effect if more than 6 hours have passed since the last crash)
pref("browser.sessionstore.max_resumed_crashes", 1);
// number of back button session history entries to restore (-1 = all of them)
pref("browser.sessionstore.max_serialize_back", 10);
// number of forward button session history entries to restore (-1 = all of them)
pref("browser.sessionstore.max_serialize_forward", -1);
// restore_on_demand overrides MAX_CONCURRENT_TAB_RESTORES (sessionstore constant)
// and restore_hidden_tabs. When true, tabs will not be restored until they are
// focused (also applies to tabs that aren't visible). When false, the values
// for MAX_CONCURRENT_TAB_RESTORES and restore_hidden_tabs are respected.
// Selected tabs are always restored regardless of this pref.
pref("browser.sessionstore.restore_on_demand", true);
// Whether to automatically restore hidden tabs (i.e., tabs in other tab groups) or not
pref("browser.sessionstore.restore_hidden_tabs", false);
// If restore_on_demand is set, pinned tabs are restored on startup by default.
// When set to true, this pref overrides that behavior, and pinned tabs will only
// be restored when they are focused.
pref("browser.sessionstore.restore_pinned_tabs_on_demand", false);
// The version at which we performed the latest upgrade backup
pref("browser.sessionstore.upgradeBackup.latestBuildID", "");
// How many upgrade backups should be kept
pref("browser.sessionstore.upgradeBackup.maxUpgradeBackups", 3);
// End-users should not run sessionstore in debug mode
pref("browser.sessionstore.debug", false);
// Causes SessionStore to ignore non-final update messages from
// browser tabs that were not caused by a flush from the parent.
// This is a testing flag and should not be used by end-users.
pref("browser.sessionstore.debug.no_auto_updates", false);
// Forget closed windows/tabs after two weeks
pref("browser.sessionstore.cleanup.forget_closed_after", 1209600000);
// Maximum number of bytes of DOMSessionStorage data we collect per origin.
pref("browser.sessionstore.dom_storage_limit", 2048);
// Amount of failed SessionFile writes until we restart the worker.
pref("browser.sessionstore.max_write_failures", 5);
```

**Comment by Atavic** [comment]
- 1020 *browser.sessionstore.max_tabs_undo*

Mozillazine:

> Possible values and their effects
A positive integer

*sessionstore.js* Telemetry for FF29: https://wiki.mozilla.org/Firefox/session_restore

**Comment by Thorin-Oakenpants** [comment]
^^ Yeah, aware of all that. I was just interested in their comments and also if you look [here](https://www.torproject.org/projects/torbrowser/design/index.html.en#new-identity) under Implementation Status, it mentions:

> After closing all tabs, we then clear the searchbox and findbox text and emit "browser:purge-session-history" (which instructs addons and **various Firefox components to clear their session state**)...

The document has been updated over time, but some parts of it are out of date (I re-read the entire thing last night)

~~We~~ **I** will have to do some testing, but I think session data cannot be stopped, only limited. As said elsewhere, my files get written too regardless of trying to kill it, and the one time I crashed, it recovered at least one tab. Our whole Session Restore needs a rethink, rewording etc.

**Comment by Thorin-Oakenpants** [comment]
Ahh, OK. I was just interested in the compiled list and comments. We will make our own decisions on the values and what we include

**Comment by Atavic** [comment]
Checked - those values are the same on https://raw.githubusercontent.com/mozilla/gecko-dev/master/browser/app/profile/firefox.js

Even the value in secs for:
```browser.sessionstore.cleanup.forget_closed_after```

// Forget closed windows/tabs *after two weeks*

**Comment by Thorin-Oakenpants** [comment]
re `1020` : There used to be a `browser.sessionstore.enabled` (introduced in FF2, yup FF version TWO) which was a master switch for the Session Restore service. This has obviously been deprecated.

Just like `full-screen-api.approval-required`=false was replaced by using a zero in `full-screen-api.warning.timeout`, setting the two prefs in 1020 *should* mean no data is stored.

I'm watching my `\profile\sessionstore-backups\*` directory (using my portable [Everything](https://www.voidtools.com/downloads/) ) and it's getting written to every so often - its kinda hard to tell, its probably 30 seconds as per my setting, but it depends if anything changes (eg, I'm just typing in this window and looking things up the user.js in Notepad++ etc), and sometimes nothing may change in that 30 second period. I have 5 tabs open, and the current tab (this one) has had focus for about 5 minutes.

It actually looks like the two files are being updated every 30 seconds, and about 15 secs apart. Clearly the bakz4 file is irrelevant (its just a backup copy).

Interestingly, the jsonlz4 file was 12kb before I started typing this post, and it seems to have grown to double that with no other changes to tabs. I hope that the session privacy setting is being respected

![session](https://user-images.githubusercontent.com/16656956/49529370-c4d31a80-f8ad-11e8-8ea8-6c4e6f12dcad.png)

The interesting thing will be to look at whats inside. And to also do some testing.

**Comment by Thorin-Oakenpants** [comment]
How do you view the contents of a jsonlz4? Gonna crowdsource the answer from you guys rather than google it

**Comment by Thorin-Oakenpants** [comment]
And even ore interesting, as soon as I posted that comment two posts up, the long one, my session restore file suddenly reduced to 12kb. To me this is indicating that it's storing form data when it shouldn't

**Comment by Thorin-Oakenpants** [comment]
Searching central on DXR, all I see for max_tabs and max_undo are default prefs and a bunch of tests, so I'm having a hard time even following the code.Am I doing something wrong here? Or are these prefs NOT even used any more?

**Comment by earthlng** [comment]
> How do you view the contents of a jsonlz4?

we have a recommended extension for that

**Comment by Thorin-Oakenpants** [comment]
^^ Oh, I don;t want to install an extension, but I spose

**Comment by Thorin-Oakenpants** [comment]
heh .. FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=449596: master switch removed in FF 3.1a2 and comment 5 clearly says what I said .. using zero in the other pref(s) is the same as disabling it.

Am busy trying to find the zillas where these two prefs were made 100% not used, so we can move em to section 9999

**Comment by Thorin-Oakenpants** [comment]
side note: browser.sessionstore.max_serialize_back could be a way to reduce session data, but the service itself is probably used by FF, eg in mid session updates

**Comment by Thorin-Oakenpants** [comment]
should we mod `0102` to say that SR is not available in PB mode, or are we stating the obvious?

```js
/* 0102: set START page (0=blank, 1=home, 2=last visited page, 3=resume previous session)
 * [NOTE] Session Restore is not used in Private Browsing mode (see 0110)
 * [SETTING] General>Startup>Restore previous session ***/
user_pref("browser.startup.page", 0);
```

**Comment by crssi** [comment]
^^ It doesn't do a harm if it is mentioned as suggested.

**Comment by Thorin-Oakenpants** [comment]
From [here](https://bugzilla.mozilla.org/show_bug.cgi?id=803806) .. even 6 years ago it seems that the undo = 0 was used but limited it to the last active tab/window. There are some browser.sessionstore.max_serialize* prefs but not 100% sure how they all work into it today.

**Comment by Thorin-Oakenpants** [comment]
I don't want to waste any more time on this. So far:
- SR is integrated internally with history and undo closed* etc
- disabling history **i think** disables SR
-.SR is not used in PB mode.
- `1020` do not seem to be used. DXR indicates they are dead prefs. They certainly do not work as nothing recording at zero (and didn't, probably, ever = at best, in the past, it limited it the last active)
   * inspecting my recovery.jsonlz4 file (my settings for the prefs are 0), it was recording all open tabs in my one window.

I think we should remove `1020`, or if anyone can find a bugzilla that show when they became dead, then we can move them to deprecated.

**Comment by Thorin-Oakenpants** [comment]
I do not like this rabbit hole. Anyway despite having data in recovery .. about:sessionrestore shows nothing

**Comment by earthlng** [comment]
JESUS CHRIST!!

https://dxr.mozilla.org/mozilla-central/search?q=max_windows_undo
Do you not see all those lines in SessionStore.jsm ?!? they're clearly NOT DEAD PREFS!

They do exactly what their name suggests and that's control the max number of stored "UNDO" (ie closed!) tabs and windows

IDFK why I have to keep telling you **not to search for the full prefname when you have such a UNIQUE substring in the pref**
