### ISSUE TITLE
FYI: Security Header: Clear Site Data

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#566]
https://scotthelme.co.uk/a-new-security-header-clear-site-data/

> "storage" - The storage type indicates that the server wishes to remove locally stored data associated with the origin of a particular response’s url. This includes storage mechansims such as (localStorage, sessionStorage, [INDEXEDDB], [WEBDATABASE], etc), as well as tangentially related mechanism such as service worker registrations.

I'd rather trust my browser/client to do this, just a shame sanitizing IDB by host (or time frame) still isn't possible

Class, discuss!

**Comment by Atavic** [comment]
> At a bare minimum, user agents ought to offer the same functionality to users that they offer to web developers.

[Clear-Site-Data RFC](https://www.w3.org/TR/clear-site-data/#user-vs-author)

**Comment by Thorin-Oakenpants** [comment]
Three days is long enough :trollface: Besides, it doesn't really help us (relying on servers).
