### ISSUE TITLE
Index of sections

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#567]
- [x] ~~decide~~: add index ~~to readme.md OR~~  user.js
- [x] perhaps tag section headers eg `/* [SECTION 0100]:`
- [x] orphaned **numbers** with no section

From The Big E ... @Thorin-Oakenpants if you don't want to list the headers in the user.js itself, maybe it would help some people to at least have it in the README.MD?

**Comment by Atavic** [comment]
Just add an index.md
List the Articles, as: /*** 0100: ARTICLE STARTUP ***/
Tell users to look for: *Article* in user.js for a comfortable search. I put Article as a new word that's not used yet. *Section* makes more sense, but it's already present in some entries. Or use another word as CHAPTER

**Comment by Thorin-Oakenpants** [comment]
> Just add an index.md

People won't read it. Would just be another link to tell them about. And an index.md IMO implies it belongs/referes to the repo, not the user.js. In the readme.md is better

> Tell users to look for: *Article*

Wrong word, but I like it. `[SECTION 0100]`, etc.

**Comment by Atavic** [comment]
main user.js is big enough now IMHO

**Comment by Thorin-Oakenpants** [comment]
actually, we don't need to add anything to the wiki or readme.md IF we add to the user.js, and I'm starting to come around to the idea

**Comment by ngx3** [comment]
I would say add it to both for redundancy :) There's already lots of clutter in the user.js, but then again it could help, organizationally speaking.

**Comment by earthlng** [comment]
either or both, I don't really care as long it's listed somewhere

**Comment by Thorin-Oakenpants** [comment]
tag section headers eg /* `[SECTION 0100]:`

There are benefits to this: maybe search and F3? Definitely in parsing (for whatever purpose), eg I can pull those out in one hit, to update/check the index matches *exactly* from time to time, etc. eg for an "online interface" (see #569 )

Note: it does leave out `START` first parrot, `0000` warnOnAboutConfig, `0000` PB mode. None of these should really be changed, but it does leave them as section orphans

I changed my js, and I gotta say, it is *slightly* harder for me to visually parse the section number, but that is probably because I am used to the old version, and because after the line space my eyes have to travel further right and count two spaces. But I'll get used to it.

Will do a commit (if for some reason everyone hates it, then it's easy enough to change back)

**Comment by Thorin-Oakenpants** [comment]
orphaned numbers with no section: suggestions

- `START` (first parrot) - ??
- `0000` (auto:config warning) -> personal?
- `0001` (PB mode) could move into startup, e.g as `0110`?

**Comment by Thorin-Oakenpants** [comment]
That only leaves the `START` & `END` parrots and I don't think we'll come up with a solution for those, they're not meant to be in a section and don't even have numbers, and the pref is duplicitous throughout the user.js.
