### ISSUE TITLE
ToDo: TB diff

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#572]
Locked for now, so all you plebs can't pollute my pristine work environment :)

Just a reminder (because I will shortly wrap up #491 ), that at some stage we should do a TB diff. Maybe when 8.0.4 comes out.

On top of that, this issue is to remind me to look more closely at [this](https://gitweb.torproject.org/tor-browser.git/plain/browser/app/profile/firefox.js) (8.0.3) - there are some things I saw in there that I want to follow up on - not just any new prefs, but information on existing ones.

**Comment by Thorin-Oakenpants** [comment]
I'll just drop this here (doesn't deserve its own topic) .. 

- [Article](https://research.checkpoint.com/50-adobe-cves-in-50-days/): 50 CVEs in 50 Days: Fuzzing Adobe Reader
- [reddit](https://old.reddit.com/r/netsec/comments/a5j4fr/how_we_discovered_over_50_critical/): some of the regulars in `r/netsec` are hilarious (as in sense of humor)

And this, ladies and gentlemen (and :cat2: ), is why I enforce the default in the user.js. Anyway, it's a really good article .. and holy cowabunga, the growth of CVEs is probably well overdue.

FYI: TB uses pdfjs.disabled=false as well, for disk avoidance and application data isolation - but does mean they have to make sure PDF itself doesn't leak (as they recently found in PDF range requests).

**Comment by Thorin-Oakenpants** [comment]
something for @earthlng and @claustromaniac to read: https://www.securitee.org/files/xhound-oakland17.pdf

**Comment by claustromaniac** [comment]
Thanks :jeans:

I've been aware of those risks [for a few months now](https://github.com/claustromaniac/detect-cloudflare-plus/issues/3#issuecomment-419209183), which is why none of my extensions make any kind of changes to the DOM.

I didn't read the full paper yet, but I already saw other interesting things mentioned in there that would make all extensions with content scripts a potential risk (whether they modify the DOM or not). The extensions I published don't make use of content scripts, but it's kind of worrying because an awful lot of extensions do...

**Comment by Thorin-Oakenpants** [comment]
Shadow DOM looks interesting, but of course I'm not a JS junkie - too old to learn new shit - been there, done that, decades of various languages. I just thought it was something that the Big E would play with and see if he could detect our recommended extensions. Obviously some don't need testing - you can already detect uBO via unique blocks in the default lists, and some make no web page injections or whatever.

**Comment by Thorin-Oakenpants** [comment]
I'll just throw this here: https://www.proofpoint.com/us/threat-insight/post/phishing-template-uses-fake-fonts-decode-content-and-evade-detection

That's pretty genius

**Comment by Thorin-Oakenpants** [comment]
Not sure if this is worth it. They're starting 68, the next ESR, on Nightly in a few days. And we still haven't done a full TB 8.* diff. It's taking them a long time to come to grips with all the Quantum changes and Tor Uplift bits and bobs.

Unless someone does a diff, for me to scan over, then I'm not wasting my time. FF is not TB. It just would have been nice to see if anything stuck out that we missed. Closing
