### ISSUE TITLE
Questions about user.js for FF60 ESR

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#573]
Trying to create a user.js for FF60 ESR. I have a few questions:

1. `user_pref("browser.cache.frecency_experiment", -1);` - Should I keep it? Deprecated in FF59 but 0 in FF60 ESR?!?

2. `user_pref("browser.library.activity-stream.enabled", false);` - Why is this commented out and what does it do?

4. `user_pref("geo.enabled", false);` - Can I change this to TRUE in order to reduce entropy? If I click "Don't Allow" I won't become more fingerprintable, will I?
Other prefs which I use include:
`user_pref("geo.wifi.uri", "https://127.0.0.1");`
`user_pref("privacy.resistFingerprinting", false);`

5. Why are these not included in the user.js?
`user_pref("dom.enable_performance_navigation_timing", false);` // (default TRUE in FF60 ESR)
`user_pref("dom.enable_performance_observer", false);` // (default TRUE in FF60 ESR)
Is user_pref("dom.enable_performance", false); a master switch?

6. `user_pref("browser.sessionstore.interval", 30000);` - Can I set it to 600000 (10 minutes) to reduce SSD / HDD writes. I don't care about recently closed tabs.

7. `user_pref("security.pki.sha1_enforcement_level", 1);` - Does removing this pref reduce entropy?

8. `user_pref("middlemouse.contentLoadURL", false);` - Is this Linux only?

9. Are these ALL the prefs I need with **resistFingerprinting** DISABLED:
```
user_pref("browser.zoom.siteSpecific", false);
user_pref("device.sensors.enabled", false);
user_pref("dom.enable_performance", false);
user_pref("dom.enable_performance_navigation_timing", false);
user_pref("dom.enable_performance_observer", false);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.netinfo.enabled", false);
user_pref("media.ondevicechange.enabled", false);
user_pref("media.video_stats.enabled", false);
user_pref("media.webspeech.synth.enabled", false);
user_pref("webgl.enable-debug-renderer-info", false);
```

Thank you very much!

**Comment by earthlng** [comment]
1. https://github.com/ghacksuserjs/ghacks-user.js/search?q=frecency_experiment&type=Issues
2. if you don't want Activity Stream you can just delete the xpi in ESR. It's commented out because we don't disable Highlights and it's part of that. It displays the 6 most recent highlights in the Library menu
3. it's inactive in the user.js for a while now. IDK if ESR already has the prompt for geolocation.
> If I click "Don't Allow" I won't become more fingerprintable, will I?

no more than anyone else who clicks Don't Allow. And definitely less than if you'd click Allow

4. haven't tested it yet.
5. you can certainly do that but it might have some unexpected side-effects because various things are stored in there, IDK.
6. no. Default in ESR is 3 which from a websites perspective is the same as 1 ie it can't detect that
7. yes. middlemouse in Windows doesn't paste clipboard content and the default in Windows is false anyway

**Comment by Thorin-Oakenpants** [comment]
> 3. `geo.enabled", false`

this disables the API, so its not the same as auto-blocking, or ignoring prompts (AFAIK the JS response is different, and this would put you in a very small group). FF & ESR have had geo behind a prompt for a very long time. **The question is, does `0201b` exist for you**. It was added in FF58 so you should have it.

```js
/* 0201b: set a default permission for Location (FF58+)
 * [NOTE] best left at default "always ask", fingerprintable via Permissions API
 * [SETTING] to add site exceptions: Page Info>Permissions>Access Your Location
 * [SETTING] to manage site exceptions: Options>Privacy & Security>Permissions>Location>Settings ***/
   // user_pref("permissions.default.geo", 2); // 0=always ask (default), 1=allow, 2=block
```

Leave the API on, but auto-block if prompt fatigue annoys you. IMO, as E says, it's not really a FP'able item (unless they perhaps timed it - computer vs human speed for blocking), as each user could have different responses per site.

**Comment by Just-me-ghacks** [comment]
1. OK, I will remove it. No surprise I was confused. They forgot to remove the fricking pref! Big E said: "the pref still exists but the code that used it was removed, they just forgot to remove the pref"

2. I don't want Activity Stream. Since I delete all .xpi it's better to keep `browser.library.activity-stream.enabled` FALSE and ACTIVATED, right?

3. Yes, FF60 ESR has the prompt for geolocation. And `permissions.default.geo` is 0 by default.

OK, I will remove `user_pref("geo.enabled", false);`

`user_pref("geo.wifi.uri", "https://127.0.0.1");` would help in case of accidental "Allow" click, right?

4. OK, I will keep these two prefs until someone test it.

5. OK, I will run FF with 600000 (10 minutes) for a while and let you know if I experience any problems.

6. OK, I will continue using it then.

7. OK, I will remove it. Why no LINUX tag in the user.js?

8. `device.sensors.enabled` - Is this mobile phone / tablet only? I thought it covers some laptop sensors as well? Like integrated accelerometers, adaptive brightness, etc.

`dom.gamepad.enabled` - Doesn't it leak info about any USB device (like  thumb drive, printer, etc.) connected to the PC?

`dom.netinfo.enabled` - OK, I will keep it.

**VERY IMPORTANT:**
9. In FF60 ESR with `user_pref("privacy.resistFingerprinting", false);` I should use `user_pref("general.buildID.override", "20100101");`, right? If that's the case you might want to add the value **20100101** to the user.js

**Comment by Thorin-Oakenpants** [comment]
> 7. OK, I will remove it. Why no LINUX tag in the user.js?

Umm, because it's not just a linux pref (it exists for all OSes), but the change is only useful for linux users? The default is false in windows. We set it as false. NFI what the default is in linux

> 9. buildid override

tricky one. ESR is still using `20100101` and [FF64+](https://bugzilla.mozilla.org/show_bug.cgi?id=583181) will use `20181001000000` - i.e when mitigating. It's tricky because you're on Linux, so the actual buildid could be very telling. BUT, (and JS control is your friend, and not every site pulls all this info, they have easier ways to track the bulk of people, so the threat may be low), it could be that by assigning `20100101` and your distro = more unique than without.

**Comment by Thorin-Oakenpants** [comment]
> 3. user_pref("geo.wifi.uri", "https://127.0.0.1"); would help in case of accidental "Allow" click, right?

Yup. If you don't want geo at all, this would be the fallback AFAICT.

**Comment by Just-me-ghacks** [comment]
I use Windows.

**Comment by Thorin-Oakenpants** [comment]
> device.sensors.enabled - Is this mobile phone / tablet only? I thought it covers some laptop sensors as well? Like integrated accelerometers, adaptive brightness, etc.

Good point. Devices are always changing. Laptops have adaptive brightness? Maybe we should re-check this. But I had a feeling that it was android only?

**Comment by Thorin-Oakenpants** [comment]
> I use Windows.

Then don't set it. The number of windows users (IDK 90% of FF users) with ESR who don't spoof it would be like 99% of them. If you change it you'll stick out like a dog's balls (in a worse case scenario). I've never liked this pref being used TBH

**Comment by Just-me-ghacks** [comment]
OK I removed `user_pref("general.buildID.override", "20100101");`

Yes, there are laptops with adaptive brightness sensors.

**Comment by Thorin-Oakenpants** [comment]
>  there are laptops with adaptive brightness sensors

Oh. Maybe we should revisit that pref's inactive state and marking it as optional. 

> how is RFP setting the buidID to `20100101` a good idea

Because RFP is a set of users with **enforced** patches and rules and spoofs and mitigations. Any attempt to lower entropy must be applied to the whole group.

**Comment by Just-me-ghacks** [comment]
Thanks, Pants and Big E! This pretty much answers all my questions. I will leave this thread open for another 24 hours if someone wants to add something and then we can close it.

**Comment by earthlng** [comment]
np, you're welcome

**Comment by Atavic** [comment]
Quoting: https://github.com/ghacksuserjs/ghacks-user.js/issues/573#issuecomment-444378540

> But I had a feeling that it was android only?

Also MacBook Pro: https://trac.torproject.org/projects/tor/ticket/21609#comment:10

**Comment by Atavic** [comment]
Microsoft surface, Lenovo Yoga: https://malwaretips.com/threads/firefox-gets-privacy-boost-by-disabling-proximity-and-ambient-light-sensor-apis.80699/

**Comment by correabuscar** [comment]
For what is worth, you need `user_pref("dom.enable_performance_observer", true);` for github to [work](https://github.github.com/browser-support/) properly, I found out the hard way: https://github.com/github/browser-support/issues/28#issue-1440953988

`enable_performance_observer` was mentioned in other issues but I won't dupe this message there, but just link here to the issues where I see it:
https://github.com/arkenfox/user.js/issues/448#issuecomment-416014813
https://github.com/arkenfox/user.js/issues/457#issuecomment-402200484
https://github.com/arkenfox/user.js/issues/491#issuecomment-444177140

Note that my current use is now:
```
dom.enable_performance	false	
dom.enable_performance_navigation_timing	false	
dom.enable_performance_observer	true
privacy.resistFingerprinting	false
```
So `dom.enable_performance` being `false` doesn't make the `dom.enable_performance_observer` be `false`, they seem unrelated.

The only thing I changed to make github work was set `dom.enable_performance_observer=true`. 
Just to give you an idea how broken github would be with this to `false`:
> the notifications blue dot wouldn't appear unless I manually refreshed the webpage, I wouldn't see any new comments/updates if I were sitting on an issue or PR page, unless I F5/refreshed the webpage manually, and visiting a notification wouldn't move the scroll to the specific item in question, it would always just be on the top of the issue instead. When creating a new gist, changing to public gist on the green button would still show secret gist on the button even though clicking it would create the chosen public gist.
