### ISSUE TITLE
Interactive real-time user.js: Stage 1 [Data Collection] Part 2

### ISSUE THREAD

**Issue by overdodactyl** [ghacksuserjs/ghacks-user.js#578]
We're trying to build an online, interactive, real-time user.js as an extension of this repository.
- The prototype is here: https://nwmviewer.shinyapps.io/ghacks_userjs/
- Previous waffling was in #569, and then in #574
- Feedback and suggestions for what people would find useful to have are always welcome.

This issue will focus on
1. what data we want to include
2. simplifying data collection 
3. ensuring the quality and accuracy of the data being pulled
4. the table structure to facilitate layout

:small_red_triangle_down: DATA COLLECTED

x100s section info
- [x] section No.
- [x] section title
- [x] section header
- [x] ?? multi-line sub-section headers `/** ` - there are only 2
   * /** safe browsing (sb) <- good info
   * /** tracking protection (tb) <- 2 lines not important

always between `/* number` and `***/`
- [x] pref number
- [x] Description: first line
   * [ ] description & subsequent data not picked up if first pref is commented out: see 1202, 2508, but subsequent pref(s) are active
- [x] Info
- [x] Notes
- [x] Warning
- [x] Setup tags
- [x] Settings
- [x] Tests
- [x] Reference Links

always after `/* number` and `***/`
- [x] pref Name
- [x] pref Value

only on user_pref lines, at end after `; //`
- [x] `[HIDDEN*` (icon)
- [x] `[DEFAULT*` (includes value and optional text)
- [ ] ?? comments (do we need them, lets do a count and see what they contain)

always after `/* number` on the first line (applies to **all** prefs for that number) **OR** on `user_pref lines`, not **both**
- [x] `[FF*` (includes number or numbers, eg [FF60+] or [FF40-49]
- [x] `[WINDOWS]` `[MAC]` `[LINUX]` `[ANDROID]`

:small_red_triangle_down: DATA QUALITY / COLLECTION

- [x] get tags out of section headers
- [ ] first line cleanups

:small_red_triangle_down: THINGS TO THINK ABOUT

- [ ] sections that don't have a pref but do have kids
   * I think 0105 -> 0105a/b/c/d is the only one. We should check this. If this is the only one, if so we're OK We don't want to propagate the setting tags anyway and the info isn't needed
- [ ] propagation of something from  `/* ... ***/`  to each pref when a number is multi-pref
  - not good when filtering and the first pref falls off, leaving a blank
  - propagate something like `see parent pref xxxx for info`? Doesn't always work
- [ ] how to pull thru sections like 4600 that use a one-switch char and different syntax

Here's a turtle :turtle: 

:small_orange_diamond:  UI THINGS we've spotted (not important yet)

* [ ] count includes displayed section titles (i.e it shows rows displayed)

**Comment by Thorin-Oakenpants** [comment]
That's me for now. I feel a huge beersies session and pig out coming on .. tis the weekend. It'll be a totally "no pants" episode with loud music and me running naked thru the house yelling and singing. See you in 24 hrs (if I survive)

@earthlng , sorry mate, about the PR. But when you get the time, if you're OK with it, feel free to squash and commit it. (then we can get on with diffs). Oh, and your thoughts would be super welcome on all of this :kiss: :suckingup:

@overdodactyl Take a break buddy, drink some wine ... what can wrong, they said! See if you work out how to propagate from `always between /* number and ***/` to each user_pref for these four items
- has [test
- has [warning
- has [setting
- has [setup* - differentiate between each type, and allow for future appendages (e.g. `[setup-harden]` )

^ I'd rather do that than pollute each user_pref with `[T]`, `[W]` etc.

This would then get us two clearly defined sets of data
- number, first line, links, all the text (info+notes+warning+setup*+tests+settings)
   * pref number, pref first line, pref value, and all the icons we need

**Comment by Thorin-Oakenpants** [comment]
oooh, just checked the prototype ... I love it, the expand etc. See how combining all that text into one field is better - but we still want to propagate some stuff to each user_pref line, basically as already said, so filtering doesn't drop things

**Comment by Thorin-Oakenpants** [comment]
Where are you pulling this from.. 0303 has a windows tag in the first line, but not in the PR.

**Comment by overdodactyl** [comment]
Definitely is improving!  Propagating the info shouldn't be too difficult.

>Where are you pulling this from.. 0303 has a windows tag. 

That admittedly took way too long to figure out haha.  I thought the url for the file stayed consistent within a PR, but nope.  It was pulling from the original commit there, but it's updated to the latest version and the windows tag is gone.

>I don't think we should pull any section header info into the table, or break it up with any extra lines. So don't work on that. If there is any section header text, we can just add it to the index. Single table, one line each pref, it's all fitting in and looks awesome

Perfect! That will be much simpler to implement anyways :)

**Comment by Thorin-Oakenpants** [comment]
^^ well, at least not in Phase 1. Maybe in six months time when we work thru all the wishlists :grin:

**Comment by Thorin-Oakenpants** [comment]
Thinking ahead about filters. When we filter by FF version, users could select from a combo-box. But we only want to provide when that pref was added to FF (or became compatible), so when we build the combo-box data, `[FF52+]` -> FF52 *and* `[FF52-59]` -> FF52. Note that we display the full string. So does that affect how you apply the filter, or do you need to build in a hidden column with the truncated version?

Note, we can use the same method for `[SETUP*`, one column for display (hasSetup=icon) and a hidden one with the full string. Combo-box would all setup tags (eg setup-web, etc) and a custom one for ALL of them.

Am I making sense?

**Comment by overdodactyl** [comment]
>change display of [FF from icon to (bold dark orange?) text

Where do we want to put this info? Do we want it as text in the info column, or just in the dropdown?

**Comment by overdodactyl** [comment]
Section header info is now in the index - needs some formatting work, but it's there

**Comment by Thorin-Oakenpants** [comment]
In the info column it's never hidden (and I hate hiding shit). Orange sucks on white text. But we can talk formatting later :) I know it will look weird with text among icons , but color coding man... you'll see later on. Its just an idea but the icons would be in set columns, rather than concatenated and left aligned, and they would be colored. And the FF version would look like this, you could even strip the FF part

![css](https://user-images.githubusercontent.com/16656956/49701306-b3a64880-fbe2-11e8-8b6f-a64d5c228c68.png)

^^ that's the kind of look I want for setting, test, warning, setup* etc in the dropdown. because its the background, it allows for lighter and a broader range of colors.

Just need to come up with some light/pale colors (not too wish washy). And since our order is always consistent, we should take that into account as well.

> Section header info is now in the index - needs some formatting work, but it's there

Sweet, I was going to ask how hard it would be to put a demarcation line between sections, but since we got stuff in there now, no need. Formatting it will do.

What happens to them when you filter? Does it hide the ones that don't apply? eg if my filter shows nothing from section 1000, does the 1000 section header still show? I know .. jumping the gun.

**Comment by Thorin-Oakenpants** [comment]
Ahh, I misread that. *header* info into the *index*

**Comment by overdodactyl** [comment]
I like the formatting idea - once we get all the info we want there I'll work out the best way to implement that (not sure if we would want actual columns for each, or just align each type of tag with spacing).

>Ahh, I misread that. header info into the index

I thought that's what you meant with earlier...did you want that info to stay in the table?

**Comment by Thorin-Oakenpants** [comment]
Ooh, I see color in some icons.

The header info I think is good in the index, because it gets bulky. But collapsed would be good.

As for the table, in an ideal world, we would want to demarcate each section with the section title (bold, bigger font or whatever, and if there are no items displayed for that section, the section header would be auto hidden. It's always been that way for the last 25+ years in reports - crystal reports, even access 95! showing my age now...

But we're working with what you have, and it's not built in. For now, it's a wishlist item

**Comment by overdodactyl** [comment]
Sounds good! Since I removed the sorting ability, that should be a lot easier to implement

**Comment by Thorin-Oakenpants** [comment]
Well, to be honest. if/when we have section titles in the table at some stage, then a collapsed header would fit best there, so its right next to the relevant prefs. Prototyping lols .. always changing ~our~ my mind. (and the section column would be hidden, it's just used as a foreign key)

**Comment by overdodactyl** [comment]
Works for me - I've changed the index so the descriptions are collapsible, but the same code can be used to create the collapsible elements for the table later on

**Comment by Thorin-Oakenpants** [comment]
heh .. containers has a lot of stuff in the header ...

**Comment by overdodactyl** [comment]
Section details are now rows in the table.

It doesn't work with searching yet, but that will come later.

**Comment by Thorin-Oakenpants** [comment]
PS: Looking awesome .. but take a break buddy ... don't you need to like eat, sleep and ~~pray~~ make sweet sweet love ?

**Comment by Thorin-Oakenpants** [comment]
PS: active count shows all count

**Comment by overdodactyl** [comment]
>we need to talk about that and decide what it's actually meant to do, and filtering

Sounds good - for now I've removed the search box and added a sample filter for "Settings"

**Comment by crssi** [comment]
I kinda liked filter... its easier and faster to find stuff where when filtered are conveniently listed together without needing to jump around the page.
Also list of all prefs (active and inactive) would be nice with an icon or perhaps italic font for inactive prefs.

**Comment by overdodactyl** [comment]
Filtering is definitely still a to-do item.  There is a sample at the top with the checkbox "Settings".

Inactive prefs can be included using the "Show Inactive Prefs" checkbox, and are indicated by an icon.  Though I think I might prefer either dimming them out or changing to italic font or something of that nature to avoid adding an additional column

**Comment by Thorin-Oakenpants** [comment]
^^ slow down there crssi. We'll fine tune function a little later, and formatting after that. But I expect the filter line to look like this (we can pretty it up later) .. and search is a word(s) filter, not a search IMO

```
Setting `[x]` Warning `[ ]` Test `[ ]` OS` [▼dropdown ]` Version `[▼dropdown ]` Setup `[▼dropdown ]`  Keywords `[....comma delimited? string?...]` `[APPLY]`
```

Changes could be auto-refresh of the data, or like tortrac, require hitting an update button (so users can make multiple choices before committing)

**Comment by overdodactyl** [comment]
^^ We'll also have to decide how that filter should work.  i.e. do we have to meet *all* selected conditions or *any* condition

**Comment by crssi** [comment]
@Thorin-Oakenpants don't worry, I am not rushing anywhere and I do not try to persuade into anything... just saying. :wink:

**Comment by Thorin-Oakenpants** [comment]
Just some things to think about: ass to OP if you want under `UI things`
- expand doesn't seem to be sticky when you toggle other items, eg active or settings
- expand controls all lines. Would it be an idea to split section vs prefs. Section headers can be quite

**Comment by earthlng** [comment]
just FYI (not saying anything needs to be done about it!)
https://nwmviewer.shinyapps.io/ghacks_userjs/ doesn't like Tor users: 403 Forbidden

**Comment by overdodactyl** [comment]
>403 Forbidden

I got this the first time I tested, but I switched circuits and it was fine

**Comment by earthlng** [comment]
oh okay, well I must be very unlucky then because every circuit I tried was blocked. But yeah it's no biggie

**Comment by overdodactyl** [comment]
Hmm, or perhaps I was just lucky.  I just tried several more and it worked 2/15 times.

Here's a screen grab to show I'm not totally making it up haha:

<img width="1112" alt="screenshot_tor" src="https://user-images.githubusercontent.com/33071129/49753709-6cb36400-fc71-11e8-85e8-bfc40e9bbe0c.png">

Ideally we could get it working, but with the free tier of `shinyapps.io` you have limited server control.

**Comment by Thorin-Oakenpants** [comment]
^^ FFS @overdodactyl .. that's a sloppy PS job if I ever saw one :trollface: 

https://metrics.torproject.org/bubbles.html#country - not much to hide in. Yeah, I get it, they probably block by ip

**Comment by overdodactyl** [comment]
>So thinking about that, when you output the result, read until you find a comma or ], strip multiple FF's. Is that easy enough to do? Examples above

That's easy to do and sounds like a good approach!

PS: Just as a heads up, I've got a busy week ahead, so I may not be able work a ton on it over the next several days, but I'm not giving up on it!

**Comment by Thorin-Oakenpants** [comment]
2508 lost it's description because it has multiple prefs, but the first one is commented out

```js
/* 2508: disable hardware acceleration to reduce graphics fingerprinting
 * blah blah ***/
   // user_pref("gfx.direct2d.disabled", true); // [WINDOWS]
user_pref("layers.acceleration.disabled", true);
```

**Comment by overdodactyl** [comment]
>These two seem to be the only ones. Should we code around it, or change the order of the prefs so the active one is first (and we'd have to remember to not fuck that up in future edits)

I think it depends on how we want to handle propagating info from one item to the next.

I'm still not sure what should be done with that.  i.e. for multiple items with the same description, should we have the description written for each one, or only the first and have a ref to the pref with the description or what?

I don't love the idea of repeating so much info, but when taking into account things like filtering, it might be the best thing to do...

Thoughts?

**Comment by Thorin-Oakenpants** [comment]
> I don't love the idea of repeating so much info, but when taking into account things like filtering, it might be the best thing to do

Me too. With an Info Systems career, I always like normalization .. until I got into data warehousing, and then speeding shit up was all the shizzle! I dunno right now, it's listed in OP, so we can come back to it.

Are you at a bottleneck waiting for a decision yet?

**Comment by overdodactyl** [comment]
>Are you at a bottleneck waiting for a decision yet?

Unfortunately I think I am a bit :/ I've got some other small things, but that's the biggest thing at this point (which will also have a big impact on how we are able to filter...without duplicating info that will become more tricky as well)

**Comment by Thorin-Oakenpants** [comment]
Possibles for duplicating /`*` to `***/` data except for items we display as an icon (each filter has an icon).

- `1` - leave empty and at top of doc in short blurb where we say a few things explain if a description is empty, look up.
- `2` - everything else looks naff (e.g I thought about just saying `see xxxx` or tooltip'ing the info) and can be problematic to code (several examples which wouldn't follow the rules)

I say we don't propagate info to empty description fields

**Comment by Thorin-Oakenpants** [comment]
closing .. I think the :cat2: caught and ate the :bird:
