### ISSUE TITLE
wiki edit permission

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#582]
i promise i won't write long-winded walls of text pants :)

at the moment i need to change links to my site and i'd rather not bug you guys with stuff like that - plus if i happen to find a typo or some small mistake, i can correct it

**Comment by atomGit** [comment]
ps: you guys want anything more done with the [search engine wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.3-Search-Engines) section?

**Comment by Thorin-Oakenpants** [comment]
I'll have to think about it. Its not that I don;t trust you, but about having a tight rein on content (and also knowing what got changed: wiki edits don't give notifications).

For the occasional site linkage changes, more than happen for you to *bug* us. It only takes a few seconds.

@earthlng

**Comment by atomGit** [comment]
not a problem - can you change these back to what they were then...

https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.3-Search-Engines

Firefox Search Engine Cautions and Recommendations
`https://12bytes.org/articles/tech/firefox/firefox-search-engine-cautions-and-recommendations`

Alternative Search Engines That Respect Your Privacy
`https://12bytes.org/articles/tech/alternative-search-engines-that-respect-your-privacy`

**Comment by atomGit** [comment]
probably, but i'll let you if i find any - wordpress is good about handling those redirects anyway, i just like to be accurate

ot: may (?) want to [add a note in the wiki](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts) that 'Conceal window.name' script breaks google captcha

**Comment by Thorin-Oakenpants** [comment]
> that 'Conceal window.name' script breaks google captcha

It has a google recaptcha exception in it? Canvas Blocker even used that snippet create theirs. Or am I missing something - changes to google, recaptcha v3?

**Comment by claustromaniac** [comment]
Pants, FWIW, I cloned both the repo and the wiki locally, and I pull changes somewhat frequently. No matter what happens to the wiki here we can restore it and no damage will be permanent. In fact, we can even mirror the wiki somewhere else (and I was planning to). Heck, I can even rewrite history if I want, I'm like *ALMIGHTY* right now :metal: Just saying.

**Comment by Thorin-Oakenpants** [comment]
Well, I might as well reopen this to deal with the captcha BS, not to troubleshoot, but as a reminder to edit the wiki

**Comment by Thorin-Oakenpants** [comment]
OK - done that - https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts
