### ISSUE TITLE
random stuff from the Big E

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#585]
:small_red_triangle_down: stuff :earth_africa: brought up

* [ ] remove 0906, 0907, 0908, 0910 - see [comment](https://github.com/ghacksuserjs/ghacks-user.js/issues/585#issuecomment-447243866) below
   * at this stage, `nah` .. see [reply](https://github.com/ghacksuserjs/ghacks-user.js/issues/585#issuecomment-447846238) to comment below, but feel free to keep discussing it
* [x] `0911` remove `network.auth.subresource-img-cross-origin-http-auth-allow`
   * default false in FF59+ anyway - https://github.com/ghacksuserjs/ghacks-user.js/commit/88b747ef36185c460b87a5ca5cd7d964a2dd597e
   * [x]  add to removed prefs scratchpad - https://github.com/ghacksuserjs/ghacks-user.js/commit/f0fbfd3086311548b8863a2a8d0e50593b76b306
* [x]  Add `network.auth.subresource-http-auth-allow` - https://github.com/ghacksuserjs/ghacks-user.js/commit/5bd5f6b28e801b8437e2574fad35f52365a6b593
   * [x] add it to the troubleshooter - https://github.com/ghacksuserjs/ghacks-user.js/commit/5b0952f60a5e9ed0fd62499187c6e62829fcd587
* `1022` does it even do what we expect it to do? remove?
     * this is covered under #575 
* [x] `1700` - add a recommendation for TC - https://github.com/ghacksuserjs/ghacks-user.js/commit/d5ece0f6f44896461a22c0dce46427aac77fcd19
* [x]  `2002 `add test page - https://github.com/ghacksuserjs/ghacks-user.js/commit/778dc89bb6126212d9c897f6e7add88ca5e6a96e
* [x] `2302` add version tag - added in 32, enabled in 44 (still disabled in ESR60!) - https://github.com/ghacksuserjs/ghacks-user.js/commit/23733097a95d9db37028d0ec8c7991bd0bf0a04b

That's right, the three wise "men" now all have emoji's :jeans: :earth_asia: :cat2: 

PS: I don't think I missed anything, but feel free to add anything else minor. We can use this as a miscellaneous checklist.

---

:cat2: said
> - 0911 - remove? or replace with... :cat2:: replace!  (with `user_pref("network.auth.subresource-http-auth-allow", 0);` or `1`? I'd go with `0`, but IDK I'M NEW AT THIS SHIT!!! :scream_cat: \*freaking out\*).

I don't know what :cat2: is drinking, but I want some

**Comment by Thorin-Oakenpants** [comment]
:earth_africa: said
> 
> 
> re: 0911
> 
> `pref("network.auth.subresource-img-cross-origin-http-auth-allow", true);` only prevents IMAGES from triggering a login prompt.
> It was added in FF55 and is default false since FF59 = no need to enforce it anymore. We probably added it before it was set to false
> 
> `pref("network.auth.subresource-http-auth-allow", 2);` was added in FF41 and supports the following values:
> 
> ```js
> // Sub-resources HTTP-authentication:
> //   0 - don't allow sub-resources to open HTTP authentication credentials dialogs
> //   1 - allow sub-resources to open HTTP authentication credentials dialogs,
> //       but don't allow it for cross-origin sub-resources
> //   2 - allow the cross-origin authentication as well.
> ```
> 
> AFAIK HTTP Auth is pretty rare nowadays and 0 should probably be fine. 1 = less breakage

**Comment by earthlng** [comment]
re: 0911

`pref("network.auth.subresource-img-cross-origin-http-auth-allow", true);` only prevents IMAGES from triggering a login prompt.
It was added in FF55 and is default false since FF59 = no need to enforce it anymore. We probably added it before it was set to false

`pref("network.auth.subresource-http-auth-allow", 2);` was added in FF41 and supports the following values:
```js
// Sub-resources HTTP-authentication:
//   0 - don't allow sub-resources to open HTTP authentication credentials dialogs
//   1 - allow sub-resources to open HTTP authentication credentials dialogs,
//       but don't allow it for cross-origin sub-resources
//   2 - allow the cross-origin authentication as well.
```

AFAIK HTTP Auth is pretty rare nowadays and 0 should probably be fine. 1 = less breakage

**Comment by earthlng** [comment]
LOL

**Comment by Thorin-Oakenpants** [comment]
Oh, that's easy then - do it

**Comment by earthlng** [comment]
with the version of when it was added or enabled?

**Comment by Thorin-Oakenpants** [comment]
Always go with added, or in the case of a few I was checking the other day, it wasn't clear, so my second choice was when it was noted as "compatible" e.g on MDN or FF release notes

Definitely don't want to start tracking when shit was flipped

**Comment by Thorin-Oakenpants** [comment]
^^ Actually, that's a big diff in versions. Since `[FF*` is the syntax for picking up versions, and we allow `[FFx-FFx] ... etc, you can put anything you like in there (but the shorter the better)

How about `[FF44-compat]`

**Comment by Thorin-Oakenpants** [comment]
:+1: if you want to do the other two. PR it

**Comment by Thorin-Oakenpants** [comment]
```
/*** [SECTION 1700]: CONTAINERS
     [1] https://support.mozilla.org/kb/containers-experiment
     [2] https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers
     [3] https://github.com/mozilla/testpilot-containers
***/
```

That looks a bit outdated. You guys tell me. AFAIK you don't need the test pilot, and its not an experiment any more. If anything I would just include [2], add a line re TC and a couple of TC links

here's whats on the wiki page
> * [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/) <sup>✔ Privacy (stated on AMO)</sup> | [GitHub](https://github.com/stoically/temporary-containers)
>   * This can achieve *almost* everything First Party Isolation (FPI) does without breaking cross-domain logins. And (with or without FPI), in a hardened TC setup, this can even isolate repeat visits to the same domain, which FPI alone cannot.
>   * Required reading: [1] [AMO description](https://addons.mozilla.org/firefox/addon/temporary-containers/) [2] [Article](https://medium.com/@stoically/enhance-your-privacy-in-firefox-with-temporary-containers-33925cd6cd21) [3] [TC's Wiki](https://github.com/stoically/temporary-containers/wiki)

**Comment by Thorin-Oakenpants** [comment]
@stoically , just FYI. It'll probably end up as something like

```js
/*** [SECTION 1700]: CONTAINERS
     If you want to *really* enhance the power of containers ....we highly recommend TC [2]
     something something article [3] something something wiki [4]
     [1] https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers
     [2] tc amo link
     [3] tc article link
     [4] tc wiki link
***/
```

**Comment by earthlng** [comment]
```js
/* 0906: disable websites' autocomplete="off" [FF30+]
 * Don't let sites dictate use of saved logins and passwords. Increase security through
 * stronger password use. The trade-off is the convenience. Some sites should never be
 * saved (such as banking sites). Set at true, informed users can make their own choice. ***/
user_pref("signon.storeWhenAutocompleteOff", true); // [DEFAULT: true]
/* 0907: display warnings for logins on non-secure (non HTTPS) pages
 * [1] https://bugzilla.mozilla.org/1217156 ***/
user_pref("security.insecure_password.ui.enabled", true);
/* 0908: remove user & password info when attempting to fix an entered URL (i.e. 0802 is true)
 * e.g. //user:password@foo -> //user@(prefix)foo(suffix) NOT //user:password@(prefix)foo(suffix) ***/
user_pref("browser.fixup.hide_user_pass", true);
/* 0910: disable autofilling saved passwords on HTTP pages and show warning [FF52+]
 * [1] https://www.fxsitecompat.com/en-CA/docs/2017/insecure-login-forms-now-disable-autofill-show-warning-beneath-input-control/
 * [2] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1217152,1319119 ***/
user_pref("signon.autofillForms.http", false);
user_pref("security.insecure_field_warning.contextual.enabled", true);
```
- 0906 is default true ever since it was added in FF30
- 0907 is default true since FF51
- 0908 is default true since at least FF22. + it gets removed in FF65
- 0910 same as default ever since they were added in FF52

can we remove them?

**Comment by Thorin-Oakenpants** [comment]
sometimes it's about enforcing a default vs bad advice visa the internet - I'll have to think about them when i'm sober :beer: but for sure, lets revisit them

**Comment by Thorin-Oakenpants** [comment]
Note to self: check all defaults and add more `[DEFAULT` tags - something an earthing script would pick up

**Comment by Thorin-Oakenpants** [comment]
Tis true tho .. we often make prefs active before Mozilla decide to flip them ... we're so cutting edge :)

**Comment by Thorin-Oakenpants** [comment]
here is a draft (it's really rough)
```js
/* 0912: disable sub-resources HTTP-authentication [FF41+]
 * yada yada potentially malicious requests yada yada
 * [SETUP-WEB] HTTP Auth is pretty rare nowadays and 0 should be fine, 1 would be less breakage
 * 0=don't allow sub-resources to open HTTP authentication credentials dialogs
 * 1=allow sub-resources to open HTTP authentication credentials dialogs,
 *   but don't allow it for cross-origin sub-resources
 * 2=allow the cross-origin authentication as well (default) ***/
user_pref("network.auth.subresource-http-auth-allow", 0);
```

Link:
- maybe: https://www.fxsitecompat.com/en-CA/docs/2015/http-auth-dialog-can-no-longer-be-triggered-by-cross-origin-resources/ but that doesn't exactly say what it is, it's just the FF41 name change and that they had to back out (from whatever they set it to or did), that was 3½ years ago
- maybe: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication ?

Add a secondary line: without something this looks like it's all about HTTP (and excludes HTTPS) and drop the

Note: FF59 https://bugzilla.mozilla.org/show_bug.cgi?id=1357835 added
 - network.auth.subresource-img-cross-origin-http-auth-allow which is default false
 - not saying to add this, just pointing it out
 - mozilla telemetry must be saying something, but I'm happy for us to go with `0`

OT: this showed up in one of my searches: https://addons.mozilla.org/en-US/firefox/addon/block-http-authentication/ - just FYI, that's all. It blocks videos & audio as well as images. I do not know if the FF59 new pref only does images.

That's it from me ... @earthlng

**Comment by earthlng** [comment]
```js
/* 09xx: limit or disable ...
 * ...
 * 0=don't allow sub-resources to open HTTP authentication credentials dialogs
 * 1=don't allow cross-origin sub-resources to open HTTP authentication credentials dialogs
 * 2=allow sub-resources to open HTTP authentication credentials dialogs (default)
 * [1] https://www.fxsitecompat.com/en-CA/docs/2015/http-auth-dialog-can-no-longer-be-triggered-by-cross-origin-resources/ ***/
```

I think value 1 should be good enough. Maybe add something that cross-origin images are covered in FF59+ regardless of this pref. (but that's also mentioned in [1] so IDK).
And maybe something like "Hardening against potential credentials phishing" as description.

Since this should not create that much breakage, if any, especially with value 1, I don't think it needs a [SETUP-WEB] tag. If we add these tags everywhere they kind of lose their usefulness

**Comment by Thorin-Oakenpants** [comment]
@earthlng don't forget to add `network.auth.subresource-http-auth-allow` to the troubleshooter

**Comment by Thorin-Oakenpants** [comment]
re: remove 0906, 0907, 0908, 0910 .. IDK, I want to keep them all, see comment re enforcing defaults against the stupidity of the internet, and passwords are pretty important (vs say a tracking cookie)

not calling PK stupid here (from previous general statement), but at least one of these differs from his settings - I think its 0906 and a case can be made for either value. So that one (I'll check what he has) would be good to keep

0908, sure, its goes next release, so no big deal

**Comment by claustromaniac** [comment]
I'd keep `0906`, `0907` and `0910`, but I see little gain in keeping them anyway.

**Comment by earthlng** [comment]
Ok 2:1 then. It's nice to have a 3rd person now as a tie breaker :)
I reopened the PR with the default tags in case you want to commit that.

**Comment by Thorin-Oakenpants** [comment]
Don't believe his lies .. he hedged his bets. Also, just quietly, he'd do anything for a treat (or so I'm told)
