### ISSUE TITLE
[article] 'Who Left Open the Cookie Jar?'

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#588]
interesting reading, fairly recent paper

### [Who Left Open the Cookie Jar? A Comprehensive Evaluation of Third-Party Cookie Policies](https://wholeftopenthecookiejar.eu/static/tpc-paper.pdf)

> In  this  paper,  we  evaluate  the  effectiveness  of  these
> defense mechanisms by leveraging a framework that au-
> tomatically evaluates the enforcement of the policies im-
> posed  to  third-party  requests.   By  applying  our  frame-
> work, which generates a comprehensive set of test cases
> covering various web mechanisms,  we identify several
> flaws  in  the  policy  implementations  of  the  7  browsers
> and 46 browser extensions that were evaluated.  We find
> that even built-in protection mechanisms can be circum-
> vented by multiple novel techniques we discover. Based
> on these results, we argue that our proposed framework is
> a much-needed tool to detect bypasses and evaluate solu-
> tions to the exposed leaks. Finally, we analyze the origin
> of the identified bypass techniques,  and find that these
> are due to a variety of implementation, configuration and
> design flaws.

**Comment by Thorin-Oakenpants** [comment]
yup,,, you might want to check out #489

**Comment by Thorin-Oakenpants** [comment]
Sounds exciting: Under you own repo you could provide details and invite them to partake. Here's a bit of a list

Owners
- Thorin-Oakenpants 
- earthlng 
- claustromaniac 

Frequent commentators
- overdodactyl 
- crssi 
- Atavic

Dedicated watchers/occasional chatter etc
- Gitoffthelawn
- Just-me-ghacks 
- grauenwolfe 
- KOLANICH
- Forsaked 
- ArchangeGabriel
- 2glops 
- Theemim 
- publicarray 
- v1adimir

No typos in that lot, I previewed em with an @ symbol. There are no doubt others. I just compiled it from the watchers list

**Comment by atomGit** [comment]
thanks much pants!

my GitHub repo has been archived - i moved to GitLab - what's the easiest way for you guys to do this?

i can create a private issue on my GL repo, but then you'd have to join and i'd have to add you guys as reporters and you'd have to accept..... yada yada - or i can create a password protected page on my site and you all can post your answers as comments

i like the latter option - i would just need a way to distribute the password to you guys and it doesn't need to be anything super secure - if you have private contact with the others, i can grab your email from a previous comment you left on my site (if you left a genuine email addy) and you can send the pwd to the others - if not, then they can all contact me and i'll return an email with the pwd

i would want to interview....

Owners

    Thorin-Oakenpants
    earthlng
    claustromaniac

Frequent commentators

    overdodactyl
    crssi
    Atavi

**Comment by Thorin-Oakenpants** [comment]
Well, all six of us are here and respond and chatty. I only have one person's email, so I cannot help there. And I have no idea if anyone wants to divulge that. Rather than fiddle around with your github stuff, do the following

Just create a (password protected) page on your site and then invite us (just use this issue) to post answers. At the start of the page, let us add a unique code, so you can confirm its us. i.e, I go there, I type in `213bvhdbjkdw` and then do my answers `Pants here .. blah blah` .. then I pop back here and tell you *my* code so you know it wasn't CHEF-KOCH or some other :hankey: 

Does that sound like a plan?

**Comment by atomGit** [comment]
holy shit, till i figure out what you just said we're in to next week easy

simpler...

go here:

`https://12bytes.org/articles/tech/firefox/ghacksuserjs-interview`

use 'pantsromance'

when yuns are done, i'll ping ya's so you can approve before publishing (which i intended anyway) and if you see something you didn't write, i'll delete it... unless it's really funny

@earthlng @claustromaniac @overdodactyl @crssi -- read [that](https://github.com/ghacksuserjs/ghacks-user.js/issues/588#issuecomment-446767992) post then read this post - everything between you can ignore

pants, ping this guy - you spelled it wrong apparently? GH isn't auto-completing that when i @ it...
Atavi

**Comment by Thorin-Oakenpants** [comment]
the reason for us the interview**ee**s to type in our own one time made up code, and AFTER posting to your form, to tell you here .. is simply so no trolling mad nutter will answer it and claim to be someone he/she isn't - its a means to verify that we are who we say we are

**Comment by Thorin-Oakenpants** [comment]
OK, I had a quick look at the q's - I'll answer it soon .. not today .. today is pants off beer day/night with loud music (hope the meds mix well). Tomorrow is probably beer recovery day. But soon

@Atavic .. you were invited as well . but atomGIT did a typo

**Comment by atomGit** [comment]
65k chars - i'll bump that up - why? did you hit it?

**Comment by claustromaniac** [comment]
If you don't mind, I will patiently wait for others to reply first, so I can save myself some time saying stuff like "I agree with X" :cat:

**Comment by Atavic** [comment]
I answered in a gist and hope @atomGit got the supersekrit link.

**Comment by Thorin-Oakenpants** [comment]
> 65k chars - i'll bump that up - why? did you hit it?

No. But I tend to get wordy. But now I see I'm being taken advantage of ... that sneaky :cat2: ,, I might play a game of cat and mouse .. see who blinks last .. wait .. does that mean I'm the :mouse2:  fuuuuuuk

**Comment by atomGit** [comment]
i could've made this a lot easier ... if anyone wants, just send me your answers from [my contact page](https://12bytes.org/contact) - you need not be logged in nor provide a real email - just make sure to **include your github alias** so i know who to attribute your answers to

here's the questions - just **reference them by number** followed by your answers - don't copy them to my contact form else you might hit the max char limit (65k)...

---

1. What color tape do you tinfoilers use to cover your web cams?

2. What do you think or say when someone says they don't care about privacy because they have nothing to hide?

3. I recall learning of your project when Martin Brinkmann published 'A comprehensive list of Firefox privacy and security settings' on ghacks.net in 2015. Is that were it all started? Did you envision this project expanding to the degree it has?

4. What do you think about the direction Mozilla is taking with Firefox? I started using their browser some time prior to the 1.0 release (i even had a 1.0 t-shirt) and have watched its development over the course. Frankly, i'm not pleased with the direction the company is pursuing regarding many of their [decisions](https://github.com/ghacksuserjs/ghacks-user.js/issues/225) and [projects](https://blog.mozilla.org/blog/2017/08/08/mozilla-information-trust-initiative-building-movement-fight-misinformation-online/). I'm thinking about things like some of the controversial system add-ons and telemetry, their partnerships with ethically retarded corporations and their apparent race to dumb-down the browser on their way to becoming the new Google Chrome. What are your thoughts? Has Mozilla lost its way?

5. Are there any significant changes in the pipeline for this project? Are you considering any ideas which could make it easier for newbies to leverage your user.js?

6. Are there any Mozilla insiders who contribute to this project (obviously you need not identify them)?

7. 'Pants', 'earthing', 'claustromaniac': This seems like quite a time consuming and complex project given the several different skills it requires. I suspect there's a lot more going on behind the scenes which most of us fans (myself included) fail to fully appreciate. Please elaborate on who possesses what skills and how those skills are put to use.

8. 'Pants': In a timeline fashion, could you describe what happens between the time you become aware of a new version of Firefox and the corresponding update to the user.js? There's obviously new and depreciated preferences and features to deal with, merges, [important discussions](https://github.com/ghacksuserjs/ghacks-user.js/issues/225), etc.. What does this process look like?

9. There is an ever-growing number of ways that users and browsers can be profiled and tracked. What is your opinion regarding the various technologies that are available to web developers these days? Do you think these technologies and APIs provide more value than harm?

10. Which one of you is the Russian hacker that [did this?](https://support.mozilla.org/en-US/questions/1083629)

**Comment by Thorin-Oakenpants** [comment]
Sorry for the delay @atomGit .. I typed up a local copy of my answers over 3 hrs (a little web browsing in there as well) and did about 20 revisions, and a gazillion edits .. and it's *rather long*. And then I drank beers and slept for ages. I should get it done and sent to you tomorrow.

If you're just going to cherry pick from what I send you, then I won't bother to clean it up - I probably went off course a bit, as well as giving away too much info - but nothing that can ID me.

**Comment by atomGit** [comment]
thanks claustromaniac! ... now waiting on pants, which is coming (i think he went to the store for more string to bind his novel), and also @earthlng @overdodactyl and @crssi

also need clarification from @Atavic regarding:

> More harm, definitely. 's browsers are technically

's ?

if you're lost, please look [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/588#issuecomment-447481161)

i [published](https://12bytes.org/articles/tech/firefox/ghacksuserjs-interview) the thing publicly so you guys can see the other answers given

thanks guys!!!

**Comment by Thorin-Oakenpants** [comment]
fuck .. I peeked .. it's not that bad, but jesus, you'll need to clean mine up and not post it ad verbatim (in places) .. maybe :lulz:

**Comment by Thorin-Oakenpants** [comment]
I also see one of my answers is shorter than :cat2: 's, so I will fix that

PS: I must have slightly changed my desk vs monitors vs keyboard positions, and I keep typing `:cat..` :cat2: as `:vat...` :vatican_city: (vatican city)  . I think that must be a sign about [this](https://github.com/ghacksuserjs/ghacks-user.js/pull/556#issuecomment-441879758)

**Comment by atomGit** [comment]
don;t feel bad <-- you SEE THAT? been fighting with this stoopid keyboard since i got it - that's how the NSA tracks me! i know it!

**Comment by earthlng** [comment]
> 7. ... Please elaborate on who possesses what skills and how those skills are put to use.

One of my skills is to evade interviews. 1st lesson in the Kremlin's hacker academy

**Comment by Thorin-Oakenpants** [comment]
So it *was* you in Q10? 

PS: I added an extra interview question to mine. At the start
- 0. If you could have one superpower, what would it be, and why?

**Comment by Atavic** [comment]
> 's ?

It was ```<current year>```'s (a Pun, hust ignore it) or simply:
current year's

**Comment by Atavic** [comment]
> is there a word missing?

It was <current year>'s (a Pun, just ignore it) or simply: current year's

**Comment by Atavic** [comment]
There are two words missing.

It was ```<current year>```'s (a Pun, just ignore it) or simply:
current year's

**Comment by Thorin-Oakenpants** [comment]
:cat2: no, my original draft is voluminous to say the least .. I'm on revision 22 and trying to trim it down. But *one* of my answers was shorter than your one, so to be consistent, I'll been adding a bunch of BS to pad it out

**Comment by atomGit** [comment]
hey @Thorin-Oakenpants - any word on when you're going to press with this?

@earthlng - you don't wish to comment? i'd like if you did, but of course you don't have to

**Comment by Thorin-Oakenpants** [comment]
i sent you a message via your contact form

**Comment by atomGit** [comment]
seen that - i'd like to talk to you about the issue you mentioned - can you send me an email addy through my contact page? no one but me has access to anything on my site

**Comment by Thorin-Oakenpants** [comment]
I can't [remember](https://en.wikipedia.org/wiki/Drugs) what I typed. What issue? Can you give me a cryptic hint?

**Comment by atomGit** [comment]
health

**Comment by Thorin-Oakenpants** [comment]
^^ Tis is all good, it's just a one off, like breaking your leg. I pinky swear on the [Lady of Perpetual Exemption](https://en.wikipedia.org/wiki/Our_Lady_of_Perpetual_Exemption)

**Comment by atomGit** [comment]
mr. PANTS, if you please........

you're the one that said, and i quote, "doing an interview is the mega-best idea i ever heard of in my entire life and i promise to be the very first to submit my answers so help me dear lord", unquote

i don't like things hanging out there and that interview page is not linked to from my site, so could you?

**Comment by claustromaniac** [comment]
now I know this was all just a trap to get atavic, crssi and I to reveal our super secret ideologies...
