### ISSUE TITLE
special issue for 65535

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#598]
From [here](https://www.schneier.com/blog/archives/2018/12/friday_squid_bl_654.html)

Hi 65535

---

First of all, you're claiming 5 to 7 mb of data. What are the files or directories. Some files it might be "cleaning" (by removing them) might already have been vacuumed clean, eg sqlite files. Or it could be detecting extension data. CCleaner does detect SiteSecurityServiceState.txt (it lists the items as cookies) - just get a portable version, so you can throw it away afterwards (portableapps.com), because since Avast took it over it's a bit of a PoS (piece of s**t). When you run CCleaner (and you could use it to just clean Firefox in these test runs), then you can click on details afterwards, and it will list the files and sizes. This is the sort of information that is needed to work out what this 5-7 Mbs is made of.

SiteSecurityServiceState.txt - just edit it empty, then deny permissions on it. HSTS is not that big a deal IMO. You have a preload built in of around 50K domains, and HTTPS Everywhere adds another 125K. And the web is increasingly moving to HTTPS, but still .. the default in browsers is HTTP because of backwards compatibility - here's a little read for you: https://www.eff.org/deeplinks/2018/12/how-https-everywhere-keeps-protecting-users-increasingly-encrypted-web

But that file is a few Kbs, not 5 to 7 Mbs.

Safe Browsing used to use google cookies, stored in a separate jar, that you can't touch within Firefox. I've never had one (and yes I do use SB, just not the real time binary checks) so I can't vouch if any cleaner sees them. But SB v4 doesn't even use cookies any more: I have tested this and also been told directly by this guy who built it: https://feeding.cloud.geek.nz/posts/how-safe-browsing-works-in-firefox/ (article is 99% up to date AFAIK). So if you have a SB cookie in a SB cookie jar, and you get rid of it, then you won't get any back.

But a cookie is minuscule. Getting back to persistent local data. Firefox does clear everything when you tell it to. I've tested it all. But of course, and I'm struggling here to think of anything other than HSTS, not everything is listed in the UI.

Note: there is difference between Ctrl-Shift-Del (clear history panel) and On Close. In the clear history panel, you can choose a time range, or "everything" which means no time range. IDB cannot be cleared by time range. So always use "everything" when doing a manual clean (as compared to when you quit Firefox).

- "Cookies" clears cookies.
- "Browsing and Download History" clears what it says, and also clears session restore (all files in your /sessionstore-backups/ directory, including previous and temp upgrade ones), it does this even if you have Firefox set to restore pages on startup (because hello, SR contains your history including some "undo close" tab and window history). Session restore is used in session and removed on close if you do NOT have Firefox set to restore pages on start (but only removed the recovery file, not previous etc ones).
- "Offline Website Data" clears appCache, localStorage, Service Worker cache, and QuotaManager (IndexedDB, asm-cache)
- "Form & Search History" clears what it says - formhistory.sqlite
- "Cache" clears disk cache, which I don't use. Memory cache would be released back to the OS.
- "Active logins" is not what it sounds like. It is not your logins to websites or passwords etc, it refers to FTPs etc - https://en.wikipedia.org/wiki/Basic_access_authentication
- "Site Preferences" clear all your Firefox exceptions (site permissions such as allow notifications/geo/camera etc, zoom settings, cookies preferences such as allow for session/block if they differ from your default) - permissions.sqlite

some locations where WEB data is stored
* cookies : profile\cookies.sqlite
* localStorage : profile\webappsstore.sqlite
* indexedDB : profile\storage\default
* appCache : profile\OfflineCache

Look, there's a lot more to it, and Next Gen Local Storage has landed in Nightly, and for the last several releases there has been a new "Cookies & Site Data" interface in Options. Cookies actually control access to localStorage and IDB (you block a cookie, and the site cannot use that persistent storage). And if you delete a cookie it should delete related persistent storage. Stay away from from cookie extensions - they cannot clear your IDB entries by host, and you will end up with ORPHANED data, and Firefox might not know they're there to clear (not 100% sure on this, its not something I need to test). On Close should use a different mechanism because it doesn't care about selective sanitizing. You can disable appCache (Firfoxe blocks it on HTTPS, and it's basically deprecated in the wild now). And you can control all web workers using uMatrix - that is default deny, whitelist - then clear them on close.

**Comment by Thorin-Oakenpants** [comment]
Also, what the heck is up with the FF51 fixation. There *was* a bug that Firefox didn't clear IDB on close, that was fixed ages ago - maybe it was in FF52 it got fixed.

I will assume you are using ESR60 or FF64+. While I can answer some questions, I'm not going to troubleshoot an outdated version.

**Comment by Atavic** [comment]
Privacy Badger focuses on *3rd party trackers* only. On PB Repo you find the legitimate google.ad & google.ae in these files: *multiDomainFirstParties.js* and *manifest.json*

PB has a big list of *1st party* scripts that are whitelisted. By searching for *google.ad* or *google.ae* on bgp.he.net you get a list of the systems that may respond to those URL queries (just an example of potential multiplexing by big data centers).

Also see: https://github.com/EFForg/privacybadger/issues/222

**Comment by Thorin-Oakenpants** [comment]
If 65535 turns up and needs more answers, I'll re-open
