### ISSUE TITLE
javascript.options.wasm and uBlock Origin

### ISSUE THREAD

**Issue by beerisgood** [ghacksuserjs/ghacks-user.js#599]
Thorin reminder
* [ ] perf tags for WASM, ASM

---

Original Post

uBlock Origin use WASM with version [1.17.4](https://github.com/gorhill/uBlock/releases/tag/1.17.4) and a official benchmark test exist too: https://raw.githack.com/gorhill/uBlock/master/docs/tests/hnset-benchmark.html

I don't know how much WASM is used, but maybe allow it again?
@gorhill maybe you can say anything about?

For my old system (Intel Q9550, 4GB DDR2 RAM, SATA 2 SSD) i got:
> - with WASM - creation:
>  - Set-based x 950 ops/sec ±3.19% (56 runs sampled)
>  - Regex-based x 685 ops/sec ±3.34% (47 runs sampled)
>  - Trie-based (1st-gen) x 136 ops/sec ±3.34% (45 runs sampled)
>  - Trie-based (2nd-gen) x 369 ops/sec ±1.91% (62 runs sampled)
>  - Trie-based JS (3rd-gen) x 813 ops/sec ±1.05% (62 runs sampled)
>  - **Trie-based WASM (3rd-gen) x 985 ops/sec ±1.60% (61 runs sampled)**
> 
> with WASM - lookup:
>  - Set-based x 1,023 ops/sec ±1.23% (60 runs sampled)
>  - Regex-based x 1,524 ops/sec ±0.62% (65 runs sampled)
>  - Trie-based (1st-gen) x 4,671 ops/sec ±0.37% (28 runs sampled)
>  - Trie-based JS (2nd-gen) x 3,860 ops/sec ±0.19% (24 runs sampled)
>  - **Trie-based WASM (2nd-gen) x 4,732 ops/sec ±0.35% (28 runs sampled)**
>  - Trie-based JS (3rd-gen) x 3,592 ops/sec ±0.24% (63 runs sampled)
>  - **Trie-based WASM (3rd-gen) x 4,389 ops/sec ±0.15% (26 runs sampled)**
> 
> 
> without WASM - creation:
>  - Set-based x 962 ops/sec ±3.40% (56 runs sampled)
>  - Regex-based x 692 ops/sec ±4.30% (55 runs sampled)
>  - Trie-based (1st-gen) x 140 ops/sec ±3.31% (47 runs sampled)
>  - Trie-based (2nd-gen) x 359 ops/sec ±2.83% (59 runs sampled)
>  - Trie-based JS (3rd-gen) x 772 ops/sec ±1.61% (60 runs sampled)
> 
> without WASM - lookup:
>  - Set-based x 1,040 ops/sec ±1.24% (61 runs sampled)
>  - Regex-based x 1,594 ops/sec ±0.50% (13 runs sampled)
>  - Trie-based (1st-gen) x 4,778 ops/sec ±0.15% (28 runs sampled)
>  - Trie-based JS (2nd-gen) x 3,823 ops/sec ±0.19% (24 runs sampled)
>  - Trie-based JS (3rd-gen) x 3,530 ops/sec ±0.29% (64 runs sampled)

Or is "javascript.options.wasm" only used for websites and not for addons?

**Comment by gorhill** [comment]
> Or is "javascript.options.wasm" only used for websites and not for addons?

It also controls WASM for extensions, I disable it when testing that the extension is properly falling back on JS version.

The results for "lookup" are the real important ones, as this is called multiple times for every network requests ("creation" is once when loading filter lists).

You should pretty much mind only the performance relative to the Set() flavor, as Set() is the reference implementation here. Even the JS version of any of the Trie improves a whole lot against the Set() version, which is what matters. WASM improves further, but if disabling wholly WASM is seen as beneficial, the JS version is already a big gain relative to Set().

**Comment by gorhill** [comment]
> I'm confused (as usual). On 1.17.4 with wasm disabled

With 1.17.4 and WASM disabled, it's "Trie-based JS (2nd-gen)". It's used to implement the `domain=` option in static network filters.

**Comment by gorhill** [comment]
You are comparing HNTrie 2nd-gen JS with HNTrie 3rd-gen WASM, that is wrong. You have to compare against HNTrie 2nd-gen WASM -- 3rd-gen is dev build, not in 1.17.4.

**Comment by Thorin-Oakenpants** [comment]
sheesh.. now i'm really confused (i see now I mixed up the lines) .. can someone just post the lines to compare - it's doing my head in

**Comment by gorhill** [comment]
2nd-gen does not support WASM for creation, so only lookup matters:

    Trie-based JS (2nd-gen) x 3,860 ops/sec ±0.19% (24 runs sampled)
    Trie-based WASM (2nd-gen) x 4,732 ops/sec ±0.35% (28 runs sampled)

**Comment by Thorin-Oakenpants** [comment]
Thanks. I edited the previous post with the right figures (I hope it did it right)

You're right about the perf from `Set()` to `JS` (and we should stress that I guess) .. I'm just trying to quantify OPs question about having wasm on or off. i.e not `Set()` to `wasm`, but the diff between `JS` to `wasm` because that's the real world diff to him.. and I think I'll stop there :)

beerisgood :beer: you satisfied with all that?

**Comment by beerisgood** [comment]
Yeah i think my question is solved now and we can leave wasm support disabled ATM.
Thanks gorhill & Thorin-Oakenpants !

I leave the issue open for further changes but feel free to close it

**Comment by Thorin-Oakenpants** [comment]
FYI: `https://github.com/EFForg/https-everywhere/issues/17143`  @gorhill
