### ISSUE TITLE
Analysis: overrides+tags+troubleshooter

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#605]
ToDo:
 - [x] flip some things to inactive (relax things a little)
 - [x] remove dead wood if any
 - [x] make sure active items get a [setup] (web/chrome/perf) tag (if required)
 - [x] make sure inactive items use [warning] not [setup] (web/chrome/perf)
    * 4502 is the only exception, as RFP is active, so in effect window sizing is already happening
 - [ ] revisit inactive items (the whole js) to see what we could add [setup-harden] to
 - [ ] create relaxed/hardened sticky for easy overrides cut & paste
 - [ ] add sticky link in readme
 - [ ] add sticky link in wiki implementation
 - [ ] close this issue, relax, drink copious amounts of beer, in the nude

---

### :small_blue_diamond:  Hi guys

First of all, I know.. I know... you're all excited.... but just relax ... I appreciate feedback etc, but please let "us" analyze it first and trim the list down (there's some junk in there) and actually create an end product. We already have the info, so please no suggestions - that can come later when we refine.

### :small_blue_diamond: What are we trying to do?

 Well, based on what's getting changed in overrides, what we already have tags on (we put em there for a reason), what's already in the troubleshooter (TS for short), and what's important (just because someone changed it doesn't mean its worthy):
- cleanup the list
- refine the troubleshooter based on tags/overrides
- refine tags based on ts/overrides
- create draft relaxed & hardened lists - a relaxed list should then practically mirror the setup-tags, and cover the vast bulk of what end users change

### :small_blue_diamond: Notes

Green (relaxed) vs red (hardened) isn't necessarily that but generally fits that pattern (we have active prefs that can actually hardened further). The green is actually active prefs, red, inactive. In general, active prefs should be where almost all our `setup` tags go (to relax), and `warning` and `harden` tags would primarily be on inactive prefs (to harden or warn, doh!). The TS info is a hybrid, as earthlng is trying to cover any end-user's config.

PS: when we create a hardened list you can see immediately that items stand out (from the red lot)

```
1. disable history
2. disable password saving
3. make permissions memory only
4. make certs memory only
5. disable svg
6. block websites setting a context menu?
7. blank restricted domains
8. disable memory cache (not in the results, but I'd add this)
```

The same process is just as easy for relaxed/setup items, just more of them which we can breakup into perf, web & chrome - and we've already done most of it.

---

### :small_blue_diamond: The Data

From #438 I summarized the results manually and have added in tag & troubleshooter info for a more complete picture

- I took everyone's overrides into account, every single line, except some things I skipped, such as changes to SB, PB mode, startup page, SR (since we flipped most of it inactive), cpd shutdowns (since we have clearonshutdown), some clearonshutudown (active logins), containers (since we made em all active), and a couple of other minor items.
- i did not include PK's diff
- I only did krathalan's diff partially, I stopped with all the stuff we had that he didn't (the third part which is super long): his js is clearly a version with cherry picked items for an audience that wants zero issues. We'll end up swamped if I add all that in (the important bits are already listed anyway). Diffs are too big!
- The troubleshooter I stopped at around the HTTP section (or again, we'll end up with too many prefs to manage) and the ones the end are least likely to cause breakage

I have this all in a spreadsheet, and I'll post an image next comment. Someone tell me the syntax in here for table shit and I'll try and replace it with text (or earthlng or :cat2: can just do one for me). Sorry for the big ass picture

In the results, E=earthlng and K=krathalan, W=always web, not warning, SR=smart referer

PS: it's not all totally scientific, because we flipped and changed things in the last 8 or 9 months since people shared their overrides. My shorthand is totally made up, so e.g `2, and 1xbecause=uMatrix` means 2 person relaxed it but 1 didn't really because he's blocking it by default in uM and whitelisting. Hope that all makes sense

**Comment by Thorin-Oakenpants** [comment]
![summary](https://user-images.githubusercontent.com/16656956/50181827-5a869500-0305-11e9-97ce-1f1a58d5e085.png)

**Comment by crssi** [comment]
I see `4001 breaks CAD=not true` line.... that came from me, but its was true back in May, and for sure it is not anymore... which suggests me that you have old overrides (at least from what I have dropped in #438 )
Do you wish get the latest? For sure there was some changes.

**Comment by crssi** [comment]
Mozilla has done a big evolving with FPI in the last half of the year... back then quite a lot login pages, where you have been redirected to another domain for login, had breakages, which is not the case anymore.

I will do a diffs for my overrides from #438 with latest and will report back... but will not be able to do it tomorrow, since I will be "out of office"... so after tomorrow, if that is OK with you.

Cheers

**Comment by claustromaniac** [comment]
> Someone tell me the syntax in here for table shit and I'll try and replace it with text

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

Maybe you can try something like [this](https://www.tablesgenerator.com/markdown_tables) to make your life easier.

**Comment by crssi** [comment]
I have started to make the list before I noticed your last reply... so I will dump it anyway.
And no, no... i didn't take it as criticism. But there are some to drop out for sure and some to add.


For example:
2701 back then was different than ghacks, but now its the same as yours.
Upper 1240 came from my overrides back then, but now its also the same as yours.... upper count is 1 (so its from me) and you can drop it out from upper list.
2030 now its `media.autoplay.enabled` has changed, mine value now is 0.
You can change 2403 from count 1 to count 2 (I have added to overrides)
You can change 2682 from count 2 to count 1 (I have removed from overrides)
You can drop 4001, since that count came from me and I do not differ from ghacks anymore.

New to my overrides:
``` js
/* 5000  */ user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false); // disable CFR
/* 4503  */ user_pref("privacy.resistFingerprinting.block_mozAddonManager", false); // allow addon web site to work as intended, also 2662 must be default
/* 2510  */ user_pref("dom.webaudio.enabled", true); // should be false, except if using WE CanvasBlocker
```
Now I will shut up until I won't. :heart:

**Comment by crssi** [comment]
in upper table under `webgl` you have `2010,1012` but it should be `2010,2012`

cheers

**Comment by Thorin-Oakenpants** [comment]
Well here are 16 items from the relaxed stuff we can ignore
![uh-huh](https://user-images.githubusercontent.com/16656956/56161953-62f09300-5fba-11e9-96f6-fe1dc56be7c2.png)

Two of those are yet to be done: see #691 and #690 

That brings ~~us~~ me down to **50 items exactly** left to evaluate for a relaxed js. And I'm sure I can trim it more - some only need a `[setup` tag for troubleshooting as they would rarely upset anyone. And others I'm thinking of making inactive as well: maybe document fonts, canvas capture stream? mixed-passive? cache? openh264? asmjs/wasm? and a few more. Fonts are fucked anyway, and I'm not sure about it. But the rest really are just creating hoops for people and knowledgeable users can mitigate the rest mostly eg thru hardened uMatrix, eTAG stoppa, etc. Chances of getting bitten by asmjs/wasm are basically zilch, etc.

There comes a point where the law of diminishing returns says "fuck it, enough is enough" - users would still be able to harden things up.

Anyway, nothing would be changed without totally thinking it thru

**Comment by Thorin-Oakenpants** [comment]
actually, I got my math wrong, it was 55 items left, but since then I have done a couple more and well.. here's a new pic

![update](https://user-images.githubusercontent.com/16656956/56167675-4fe4bf80-5fc8-11e9-862d-e3d552bb8559.png)

blue suggesttions: make some stuff inactive since they have almost zero effect: it would be discussed - I am not saying I would do this. It's also just as easy to leave them as is and add an extra few lines to the relaxed prefs

My point is that the user.js should be more friendly. EVERYTHING not active, except those with warnings, are essentially your hardening up list. But we could still denote these for hardening since we've run with them for so long.

Anyway - from an initial `71` items to think about
- the `19` red ultra-minor items or items since made inactive (including the two I will do in a day or so) would bring us down to `52`
- the `12` blue items would bring us down to `40` - and I think we should open a ticket to discuss it

Then we are left with a much reduced, cleaner list of common items for a relaxed sticky or file

**Comment by Thorin-Oakenpants** [comment]
Update:

What I am aiming to do is reduce the list to zero, making sure we're happy with what we have it set as, and make sure everything that needs a `[SETUP*` tag has one (including the new `harden` tag). Then I can make a relaxed (and maybe hardened) sticky/js **based on** tags (just because something has a tag doesn't mean it makes the list), and then over time it can be refined/added to.

From the original list of **68** items (combining all the `2803`'s as one), some items are very minor, and since then some items were made inactive, and some items already have a tag
- **10** items no-one needs to worry about anymore, they are now inactive (two have a harden tag)
- **19** items are now already tagged (so I can find them to help build a relaxed sticky)
- **11** items we can ignore IMO as super minor or on their way out
- **2** items are same as default and don't ~~need~~ deserve anymore attention

![status](https://user-images.githubusercontent.com/16656956/56502982-d7b85580-6503-11e9-9cb3-95c80b44fd49.png)

That leaves me **26** items left to evaluate

![wots-left](https://user-images.githubusercontent.com/16656956/56503122-19e19700-6504-11e9-8a82-61a3b704e498.png)

Comments welcome: although I'm going thru a bit of a mess in my head as to how to position the user.js in terms of making it more relaxed etc (see previous issue about making things inactive) vs payoff in terms of convenience and risk assessment.

**Comment by Thorin-Oakenpants** [comment]
@crssi Can you give me an example of WOFF2 (1405) which is on the list. If all it does is break readability, then I might make it inactive with a harden tag. I never see breakage though - this is just local fonts right?

**Comment by crssi** [comment]
WOFF2 is used quite a lot for Icons, for example a "magnify glass" for search buttons, etc.
Will disable it here and when I stumble on a page, I will post URL here. Expect it soon.

Cheers

**Comment by Thorin-Oakenpants** [comment]
> when I stumble on a page, I will post URL here

Cool. a test page would be awesome. I need to work out if these can be/are affected by other prefs: e.g downloadable fonts, 3rd party, etc. I mean, does Windows come with WOFFs? I'm not a font expert. 3rd party can be controlled by uBO, uM.

I'm just not sure what the privacy risk is here. Pretty sure there is no security risk.

**Comment by crssi** [comment]
Tank you for `1403`. I stumbled around and not yet found glyph breakages, since all the sample pages I had reverted to PNGs in the meantime. But I have found some, where fonts are not the same as with woff/woff2 and the page is uglifyed. But it doesn't matter anymore due to your change today it is OK now. :smile_cat: 

I would vote for `1241` to be `inactive`. Its passive content, leads to breakages like missing images. Is it really security/privacy problem?

Never had a problem with `1406` as it is now, at least I haven't been aware of.

I would vote for `2001` to stay as it is now. Otherwise it is a [privacy/information leak problem](https://www.w3.org/wiki/Privacy/IPAddresses). Or it must be covered by uBO.

**Comment by crssi** [comment]
Voting for `2203` to be `inactive`. Is there really security/privacy issue?
I am not smart enough for `2403`. Smells a bit, but I have this in overrides as `true`, the same with `2402`.
I guess for `0207` we are covered by RFP (`4500`) if `active` and `true`

**Comment by crssi** [comment]
If there is an statement in [implementation](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.3-Implementation) that default search engine must be set to one that is privacy oriented (like DDG or other similar) then `0801`, `0807` and `0808` could go `inactive.` If not, those should stay `active`, IMHO.

**Comment by Thorin-Oakenpants** [comment]
`1241` (passive insecure content) would be off the cards: the breakage lessens everyday with uptake of HTTPS, and yes, there are privacy concerns: sending requests in the clear is enough to disable it. It just needs a setup tag and maybe a warning

**Comment by Thorin-Oakenpants** [comment]
It's very hard to find a balance: there are too many variables. The user.js can only do so much, and we should make it as private/secure etc as we can, **assuming** there is nothing else.

e.g In the case of `1241`, a user can allow passive content, and still be anonymous (e.g VPN, Tor, not logged in to an account and even if they were that doesn't mean it links back to them IRL)

**Comment by Thorin-Oakenpants** [comment]
note to self: currently (readme exlcuded)
- `[SETUP-WEB]`: 15 items
- `[SETUP-CHROME]`: 13 items
- `[SETUP-PERF]`: 4 items
- `[SETUP-HARDEN]`: 4 items
- `[SETUP-non-RFP]`: 1 item

Total: 37. A couple of these are in section headers, and will be moved against the actual prefs. My list of items to check (review active status, maybe add tags) is down to 16 items (5 have tags already).

chrome tags seem high. if we can keep tags (excluding harden) to around 40 numbered items, that seems reasonable - not overwhelming.

**Comment by Thorin-Oakenpants** [comment]
just FYI: here's what's left
![wotsleft](https://user-images.githubusercontent.com/16656956/56853306-5b63af00-6915-11e9-8754-f0db3247c675.png)

**Comment by Thorin-Oakenpants** [comment]
I've cleaned out some old comments. Here is a big ass picture to compare to the one in the second post. I'm almost there

![winter-is-coming](https://user-images.githubusercontent.com/16656956/56952841-bae6d800-6b2a-11e9-9c7c-befe09c9db9b.png)

**Comment by Thorin-Oakenpants** [comment]
OK. I think I'm almost done here. Here is the summary

![Yay-I-finished](https://user-images.githubusercontent.com/16656956/60379041-20681f80-9a1b-11e9-963b-907f9c2915df.png)

```
STATS
=====
excluding personal and deprecated, and parrots

249 active
113 inactive (10 are active in RFP ALTs which is an inactive section)
===
362 total


249 active
 15 active enforced at default
===
234 pref changes (at most)

^^ covered by 42 [SETUP* tags
 1 [SETUP-SECURITY]: SB binary checks
 5 [SETUP-PERF]: AltSvc, cache, SSL Session IDs, asm.js, wasm
14 [SETUP-CHROME]
18 [SETUP-WEB]
 3 [SETUP-HARDEN] HWA, MathML, "open with"
 1 [SETUP-non-RFP]

```

Overall, this should provide a more balanced user.js, but one which is still pretty heavily geared towards `hard` rather than `relaxed`, but one which allows very easy troubleshooting: e.g. 18 set-up web tags should cover 95% of breakage

I can't say it's been fun. I shall close this and open a new issue on whether we even need to provide a relaxed version. AFAIC.. the information is all in the user.js
