### ISSUE TITLE
Location bar search broken

### ISSUE THREAD

**Issue by richter-p** [ghacksuserjs/ghacks-user.js#606]
On 64.0, this breaks location bar search for me.

### Problem
When typing something into the location bar and pressing enter, I would expect firefox to decide if it is a FQDN and, if it isn't, use my default search engine to search for this term. I do not want any dropdowns or suggestions.

Instead, when I type "test" into the location bar and press Enter, Firefox tries to resolve "http://test/" and fails.

### What I've tried
* Deleted my old Firefox profile, created a new one, reinstalled ghacks-user.js
* Deleted all but my default search engine DuckDuckGo
* Tried various tweaks of the Location Bar settings, even completely removed them

Is this expected behaviour?
Can I get the location bar to work like I'm used to?

Thanks for your work.

**Comment by bogachenko** [comment]
user_pref("keyword.enabled", false);

**Comment by richter-p** [comment]
This indeed helped, thank you. I removed the whole section and couldn't get it to work, so I thought this was not the place to change it. I honestly didn't understand the description, too.
