### ISSUE TITLE
Happy New Year

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#609]
Happy New Year everyone!

I wish you all the best for 2019

love you all

**Comment by bogachenko** [comment]
Not late with the date? @earthlng

**Comment by claustromaniac** [comment]
Happy new year, everyone!!! It's good to know you survived the holidays @earthlng!
## :heart: :beers: :ice_cream: :tada: :fireworks: :v: :guitar: :metal:

> Not late with the date? @earthlng

Don't be a buzzkill man, only 1,5981735% of the year has passed. Besides, it's still new year's eve in UTC -150

**Comment by bogachenko** [comment]
@claustromaniac 
>Don't be a buzzkill man

![images](https://user-images.githubusercontent.com/8535285/50733460-e04d8000-11e1-11e9-95ee-735fdf551ad5.jpg)

**Comment by Thorin-Oakenpants** [comment]
OT: buzkilling spoofing: think you can hide your browser or version? Think again! (assumption: you are allowing first party JS, although css alone can leak your browser)

Here's my FF64 in action
![spoofing-doesnt-always-work](https://user-images.githubusercontent.com/16656956/50734010-aa7fab80-118f-11e9-9c01-fff961502ca7.png)

**Comment by Forsaked** [comment]
Also Happy New Year from me, even if we are already 9 days in.

**Comment by StanGets** [comment]
We have until January 31st to wish a happy new year, but I won't wait till the last day:

A Happy, a marvelous, an awesome, a terrific, an outstanding (what did i forget?) New Year 2019 to all!

Said.
