### ISSUE TITLE
Where to install?

### ISSUE THREAD

**Issue by gerroon** [ghacksuserjs/ghacks-user.js#613]
Hi

Just read the wiki, I do not see where this file supposed to go. Can you tell me how I instlal it?

thanks

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview
> A `user.js`, which resides in the root directory of a profile

https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.2-Backing-Up
> [paraphrased] back your profile up

https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.3-Implementation
> [paraphrased] look, you might have backed up your profile, or you may be using a new profile .. but don't just blindly apply the entire user.js  - it's a TEMPLATE. the 1.3 wiki page lists a tiny handful of important things

So unless you're using a brand new profile that you want to play with and tweak until you're happy with it, then PAY ATTENTION or you might **lose** stuff (like all your histories such as form, browsing, download - and all your cookies). Other than that, be aware that extensions are not auto-updated, only checked for. And other than that, you won't lose anything (we don't wipe your site permissions, or passwords etc) - anything else can be flipped back on/off to control web site breakage or Firefox UI behavior (such as suggestions in the urlbar, etc).

I've tried to make the default template as friendly as possible (e.g we do not disable things that protect you such as Safe Browsing), but you still need to be aware of some things - hence 1.3 wiki page.

Anyway .. so the answer was right there on the first wiki page, in the first paragraph, in the first sentence
> A `user.js`, which resides in the root directory of a profile

**Comment by gerroon** [comment]
I am sorry but root of profile directory is not as clear as it seems to you because I have a folder inside the root of my folder and it is not clear if root of my profile means inside of that folder or the literal root of my profile , see please

AppData/Roaming/Mozilla/Firefox/Profiles/zxcxnkwx.default

So is the root of the profile "Profiles" or inside "zxcxnkwx.default" ?

**Comment by Thorin-Oakenpants** [comment]
`Profiles` is plural .. so it would/could contain many profiles. A `profile` (singular) would be the folders inside that.

https://github.com/ghacksuserjs/ghacks-user.js/wiki/2.1-Multiple-Profiles - see the second picture or click this: https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/wikipiki/profiles02.png - that there is the Profiles folder with two profiles in them.

So in your case it would be `zxcxnkwx.default` .. which if you look inside has contents such as bookmarkbackups, extensions, storage, and files such as cookies.sqlite and so on. the `user.js` goes in here.

You can also go to about:profiles (not in Firefox portable though) and create new profiles and locate existing ones etc.

**Comment by gerroon** [comment]
Thanks for the follow up, it is clear now

**Comment by Thorin-Oakenpants** [comment]
no worries .. have fun, and sing out if you need help - I mean, the default user.js will break things like video (DRM, Widevine .. etc e.g Netflix) and we haven't exactly finished sticking in `[SETUP-]`* tags (but we have quite a few in there, just search for them) - and pref names are not always super clear on what they do

**Comment by gerroon** [comment]
Sounds good, I have no problem broken DRM! I will provode feedback as much as I can. 

thanks again
