### ISSUE TITLE
[improved descriptions] for extensions.getAddons.cache.enabled

### ISSUE THREAD

**Issue by v00p** [ghacksuserjs/ghacks-user.js#615]
This config not only disable updating, but fetching as well.
Might worth mentionning in the comment.

Current:
```json
/* 0306: disable extension metadata updating
 * sends daily pings to Mozilla about extensions and recent startups ***/
user_pref("extensions.getAddons.cache.enabled", false);
```

Proposed:
```json
/* 0306: disable extension metadata updating
 * sends daily pings to Mozilla about extensions and recent startups
 * [WARNING]: cause partial fetching of your extension's metadata as well
 * [1] (Before/After) http://i.epvpimg.com/RdFVcab.gif ***/
user_pref("extensions.getAddons.cache.enabled", false);
```
<details not-open>
<summary>Before/Afer sample:</summary>

<img src="http://i.epvpimg.com/RdFVcab.gif" height="600"/>
</details>

**Comment by Thorin-Oakenpants** [comment]
Ahh, I never knew that clicking an extension card to load in it's own "page", actually expanded to show all the text. I just assumed each extension showed a one-liner, and the own page was to set update policy per extension, show version number, etc.

Worthy of a `[note]` perhaps. When the pref is false, it doesn't display the extra information, even though you already had it (from toggling the pref) .. so does this mean that it then connects *every single time* to AMO to get that info?

**Comment by v00p** [comment]
> When the pref is false, it doesn't display the extra information, even though you already had it (from toggling the pref) .. **so does this mean that it then connects _every single time_ to AMO to get that info?**

No it doesn't. Toggling this config on/off never phone to AMO. The only data It fetches is the one your browser has cached during initial installation of the extension.

So, basically, I believe we should remove this config entirely, as all it communicate with is your local storage.

**Comment by v00p** [comment]
> When the pref is false, it doesn't display the extra information, even though you already had it (from toggling the pref) .. **so does this mean that it then connects _every single time_ to AMO to get that info?**

No it doesn't.
Toggling this config on/off never phone AMO. The fetch is performed entirely locally, 
cached from your initial installation of the extension.

Which means that any extensions that you previously installed while this config was set to "false", won't have that missing data present locally. You'll have to reinstall with the config turned on to have em shown.

So, basically, this config has no privacy implications at all. All it communicates with is our cached storage, not AMO.

**Comment by Thorin-Oakenpants** [comment]
I'll reopen, so we can investigate further. The purpose of the pref may have changed over time
- https://dxr.mozilla.org/mozilla-central/search?q=extensions.getAddons.cache&redirect=false

**Comment by Thorin-Oakenpants** [comment]
This is old, probably added when FF4 came out - but it also hasn't been removed or updated AFAICT: https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/

> In order to keep this information updated, Firefox will ask the Mozilla Add-ons gallery for information about the add-ons you have installed once a day. This involves sending the identifiers of each add-on you have installed to Mozilla, as well as information on how long it last took Firefox to start up.

**Comment by Thorin-Oakenpants** [comment]
I am not an expert at reading this stuff....

There is a pref called `extensions.getAddons.cache.lastUpdate` which if you look [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/AddonRepository.jsm#342) you can see it tries to work out if the metadata is stale or not

```js
metadataAge() {
    let now = Math.round(Date.now() / 1000);
    let lastUpdate = Services.prefs.getIntPref(PREF_METADATA_LASTUPDATE, 0);
    return Math.max(0, now - lastUpdate);
  },

  isMetadataStale() {
    let threshold = Services.prefs.getIntPref(PREF_METADATA_UPDATETHRESHOLD_SEC, DEFAULT_METADATA_UPDATETHRESHOLD_SEC);
    return (this.metadataAge() > threshold);
  },
```

 .. and if you follow the crumbs it seems to call `async getCachedAddonByID` (at line 395) and if I scroll further down (line 490)

```js
 /**
   * Fetch metadata for a given set of addons from AMO.
   *
   * @param  aIDs
   *         The array of ids to retrieve metadata for.
   * @returns {array<AddonSearchResult>}
   */
  async getAddonsByIDs(aIDs) {
    return this._fetchPaged(aIDs, PREF_GETADDONS_BYIDS,
                            results => results.map(
                              entry => this._parseAddon(entry)));
  },
```

I need someone like @earthlng to confirm what *exactly* is actually going on, and also that time factor (it's probably once a day)

I guess the question is, does this do any harm - given we set extension update checks = on: I'm not worried about Mozilla getting info TBH, but blocking this would seem to be a bit pointless: so at the very least we could make it inactive (but leave the pref in for those who want to disable it)

I also wonder about `lightweightThemes.update.enabled` - aren't personas dead?

**Comment by v00p** [comment]
> 
> 
> This is old, probably added when FF4 came out - but it also hasn't been removed or updated AFAICT: https://blog.mozilla.org/addons/how-to-opt-out-of-add-on-metadata-updates/
> 
> > In order to keep this information updated, Firefox will ask the Mozilla Add-ons gallery for information about the add-ons you have installed once a day. This involves sending the identifiers of each add-on you have installed to Mozilla, as well as information on how long it last took Firefox to start up.

Hmmm you might be right. I completely forgot the nasty "scheduled fetch" scenario.. 
And they removed all of the former `extensions.getAddons.cache.*` configs... a workaround could have been to increase the `extensions.getAddons.cache.updateThreshold` value, but they removed it as well.. 

I'll digg a little more...

**Comment by Atavic** [comment]
[browser_preferences_usage.js](https://searchfox.org/mozilla-central/source/browser/base/content/test/performance/browser_preferences_usage.js) at line 100 uses function *checkPrefGetters* and says it is accessed in debug only.

**Comment by Thorin-Oakenpants** [comment]
>  EDIT: actually, fuck this. :v: :sunglasses: :wine_glass:

Wots that all about? You getting a bit tetchy there :cat2: ?

**Comment by v00p** [comment]
> EDIT: actually, fuck this.
Each time I engage this underrated task of defusing my FF browser, It ends up triggering that on me as well.. no matter good my day/week was.. Nazzila..

**Comment by Thorin-Oakenpants** [comment]
> Nazzila 'bout to get me switchin browser soon

Nothing wrong with Firefox. Every browser has gazillions of lines of code, old code, spaghettified code, and what not, and old bugs and quirks, and holes (it's the nature of the beast). Since they ditched XUL etc, changes are rapid AF. It's entirely your choice, but (rhetorical question - don't mention forks FFS) what browser would you switch to? Nothing comes close to FF in terms of tweaking and privacy.

**Comment by Thorin-Oakenpants** [comment]
hey @claustromaniac ... found you a birthday pressie
![kittyfoil](https://user-images.githubusercontent.com/16656956/51437736-4afac300-1c9a-11e9-8fa3-0e0e357e6677.jpg)

**Comment by v00p** [comment]
> 
> 
> > Nazzila 'bout to get me switchin browser soon
> 
> Nothing wrong with Firefox. Every browser has gazillions of lines of code, old code, spaghettified code, and what not, and old bugs and quirks, and holes (it's the nature of the beast). Since they ditched XUL etc, changes are rapid AF. It's entirely your choice, but (rhetorical question - don't mention forks FFS) what browser would you switch to? Nothing comes close to FF in terms of tweaking and privacy.

I love Gecko.. I miss XUL .. won't leave the v00p breed, but I find it hard to defuse FF properly, thats all.. ;p

**Comment by Thorin-Oakenpants** [comment]
I hear ya - it was a bumpy ride in stable (including bugs), but I weaned myself off the legacy extensions one by one over months (others chose to stick to ESR and get it all in one hit sans most bugs), but to be honest - I couldn't care less about the UI - it's just some underlying problems (such as [rolling the dice](https://github.com/ghacksuserjs/ghacks-user.js/issues/265#issuecomment-393935989) on CSP header injection/modification) or lack of a API e.g to make a WebExt for NoRedirect: see [1352653](https://bugzilla.mozilla.org/show_bug.cgi?id=1352653).

And I'm sure there are a few other missing APIs for handling web content. All the rest are IMO workflow issues, but just adapt (and hopefully they will get it done) - and by workflow I mean things that enhance how you do things: download managers, session management. I don't mean UI stuff. I actually miss ScrapBookX just a little - I used it to store lots of organized snippets of stuff (and no it wasn't hoarding, I kept it pruned), and even to dump things to revisit: like a ToDo list. Oh well, I adapted :)

**Comment by v00p** [comment]
I keep and still use a legacy-dedic build (ESR 52.9.0) for when I really need it, and i'll progressively discard it's use when quatum and WE mature.

**Comment by claustromaniac** [comment]
> hey @claustromaniac ... found you a birthday pressie: https://mcphee.com/products/tin-foil-hat-for-cats

Great, thanks. Just what I need to protect myself from the [ceiling cat](https://i.kym-cdn.com/photos/images/original/000/570/267/32d.jpg)...

**Comment by Thorin-Oakenpants** [comment]
bump .. anyone any wiser as to when / if addon metadata cache checks for updates?

**Comment by Atavic** [comment]
Not with updates disabled. I have updates disabled, plus the entry
*extensions.update.url* is twartwed with the value *http://0.0.0.0*
This way in *about:Addons* even a manual click on Check for Updates via the top right Icon gives: 
No updates Found

Note: I also have *browser.addon-watch.interval* twartwed with *-1*

**Comment by Atavic** [comment]
^I'm on ESR.

Btw by checking around I see that going to *Help>About Firefox* and clicking for updates still gives me the opportunity to update to the latest ESR version.

**Comment by Thorin-Oakenpants** [comment]
@earthlng bump .. can you work this out (follow the code man!) as in when it gets updated ... I don't mean that we remove it, but maybe make it inactive if it doesn't call home any more than when you update/install

@Atavic it's not about "thwarting" it, it's about does it call home (which is not a risk, but useful for those who want zero outbound) in the background (i.e not when updating/installing)

**Comment by earthlng** [comment]
it's a bit tough to follow but as far as I can tell it's only used on install, update and the daily background update checks. (thanks @claustromaniac for the breakdown and all the links)
There's also something in the new discovery thingy code that uses it but I don't think that's a concern because we disable the "Get Addons" page anyway and that discovery thing also needs telemetry enabled.
Since we don't disable extension updates by default, I think it's fine to make this inactive as well. Or just use the proposed change from OP, IDC

**Comment by Thorin-Oakenpants** [comment]
> I think it's fine to make this inactive as well. Or just use the proposed change from OP

Already did https://github.com/ghacksuserjs/ghacks-user.js/commit/1c09ec36e3275c2ac6c4bf5a7c16d55a928630c7 .. but I think inactive is a good choice as well .. will do some rewording and a commit later

**Comment by Thorin-Oakenpants** [comment]
> it's a bit tough to follow but as far as I can tell it's only used on install, update and the daily background update checks

OK, flipping this to inactive. We check auto-CHECK for updates, so this does nothing except limit information.

**Comment by Thorin-Oakenpants** [comment]
the extra metadata displayed only ends up in your cache when you actually update the extension. I just had CanvasBlocker with a single line (remember, I checked for updates a few hours ago), checked for updates, CB needed one, so I did it, and now CB has a mountain of info displayed

So when "update checking" can be crossed off the list.

**Comment by earthlng** [comment]
> it's only used on install, update and the daily background update checks.

... the daily **background** update checks!

**Comment by earthlng** [comment]
hashtag blackwordsmatter :)

**Comment by Thorin-Oakenpants** [comment]
I was going to check in the next 20+ hours to see if any of the other extensions I have update their meta data then add that in. I'll re-open as a reminder.

IF you're sure, then just do a commit and close

**Comment by earthlng** [comment]
probably `extensions.update.background.url`

**Comment by Thorin-Oakenpants** [comment]
OK .. practically 24hrs after resetting the pref, the addons got their metadata
