### ISSUE TITLE
Custom CSS conflict

### ISSUE THREAD

**Issue by Randomhan** [ghacksuserjs/ghacks-user.js#621]
Hello everyone. I apologize if I am needlessly opening an issue, but I would appreciate it if someone could point me in a general direction regarding a problem discussed here: 

https://github.com/Aris-t2/CustomCSSforFx/issues/163#issuecomment-457909763
https://github.com/Aris-t2/CustomCSSforFx/issues/163#issuecomment-457917962
https://github.com/Aris-t2/CustomCSSforFx/issues/163#issuecomment-457920685
https://github.com/Aris-t2/CustomCSSforFx/issues/163#issuecomment-457939846

It seems to be caused by the default configuration so I find it curios that I am the only one affected by it.

**Comment by Thorin-Oakenpants** [comment]
this repo is for a [user.js](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.1-Overview#small_orange_diamond-what-is-it-what-does-it-do-and-why-would-i-want-one) , not custom css. Try asking in https://old.reddit.com/r/FirefoxCSS/

**Comment by Atavic** [comment]
Maybe this may help: https://github.com/Timvde/UserChrome-Tweaks/blob/52f1eae0c3492d52c33adb9b97bc17a222ce4032/tabs/hide-tabs-windows.css

**Comment by earthlng** [comment]
@Randomhan you can try our troubleshooter script and maybe it can identify the culprit:

see https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting
