### ISSUE TITLE
did you know... just how much shit cookies control?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#622]
Results: cookies control:

If you block cookies, these are not accessible to websites to use.
- cookies
- local storage
- session storage
- IDB
- shared workers
- service workers (and by extension sw cache and sw notifications)

If you set a site exception for cookies (either `Allow` or `Allow for session`) then they become accessible to websites **except workers** where the cookie setting **must be** `Allow`

----
original post

~~.... that blocking cookies also blocks shared workers?~~

~~edit: nvm .. it's something else ... needs jesus (for now)~~

Nope: I was right the first time: blocking cookies also blocks shared workers AND service workers

Class discuss!

**Comment by Thorin-Oakenpants** [comment]
@fmarier Is this expected behavior ?

**Comment by Thorin-Oakenpants** [comment]
Also ... sessionStorage always says it's enabled (despite the cookies being disabled), unlike localStorage, IDB .. that confuses me as well. Seems inconsistent

maybe LSNG changes everything?

**Comment by fmarier** [comment]
I'm not sure. Also, I don't work at Mozilla anymore.

**Comment by Thorin-Oakenpants** [comment]
OK, not sure what in my main FF is causing shared and service workers to fail when I allow cookies (yes I have uMatrix allowing them, and yes I have allowed dom.serviceWorkers.enabled) .. so I'll have to narrow that down.

note: the four empty lines depend on service workers (sw cache and notifications), so when I detect an error I propagate that for those results: otherwise they are empty because I haven't built the tests yet.

Here is a vanilla FF60 with cookies enabled (default)
![cookies-allowed](https://user-images.githubusercontent.com/16656956/51949160-65b00300-2423-11e9-9a0f-bb98c5a7ac2e.png)

and here it is with cookies blocked (as a site exception)
![cookies-blocked](https://user-images.githubusercontent.com/16656956/51949173-73fe1f00-2423-11e9-9c7f-623c0bd06ea4.png)

As you can see, cookies themselves, localStorage, sessionStorage and IDB all work or fail depending on the cookie = to be expected, it says it in the user.js

What I didn't expect was cookies to control shared workers and service workers. Very interesting. I'll do the same test in a nilla 64 (don't have a 65, cuz my portable dev edition is on 66 already and I think NGLS is already enabled, I'll check)

**Comment by Thorin-Oakenpants** [comment]
PS: in PB mode, service workers are not available but I already check `if ("serviceWorker" in navigator)`, and it isn't in PB mode, so the tests are not run.

The "store data in persistent storage" site exception is from another test and does not affect service workers anyway

**Comment by Thorin-Oakenpants** [comment]
Same results in a nilla FF64 and FF66

**Comment by Thorin-Oakenpants** [comment]
@earthlng we should update the info in section 2700. the info about what cookies control is in 2701 but I'm more inclined to move it into the header section. We could also add that sw and IDB are not available in PB mode.

current (which is clearly not true)
```
 * [NOTE] Blocking 3rd party controls 3rd party access to localStorage, IndexedDB, Cache API and Service Worker Cache.
 * Blocking 1st party controls access to localStorage and IndexedDB (note: Service Workers can still use IndexedDB).
```

suggest deleted that from 2710 and adding the following to the section header
```
/*** [SECTION 2700]: PERSISTENT STORAGE
  Data SET by websites including
         cookies : profile\cookies.sqlite
    localStorage : profile\webappsstore.sqlite
       indexedDB : profile\storage\default
        appCache : profile\OfflineCache
  serviceWorkers :

  [NOTE]: IndexedDB and serviceWorkers are not available in Private Browsing Mode
  [NOTE]: blocking cookies also blocks websites access to; localStorage (incl. sessionStorage),
  indexedDB, sharedWorker, and serviceWorker (and therefore service worker cache and notifications)
  If you set a site exception for cookies (either Allow or Allow for Session) then they become
  accessible to websites except shared/service workers where the cookie setting *must* be Allow
***/
```
 nits?

**Comment by Thorin-Oakenpants** [comment]
FYI: with uBO winning the game of dice with uMatrix .. the problem is uBO's `no-remote-fonts: * true` - since I use uM in nightmare mode, I think I can do away with this certainly for 1st party. But i'm not sure if adding a `*$font,third-party` filter would still cause the same rolling the dice issue - @gorhill

**Comment by earthlng** [comment]
I'm using Request Control to block fonts. Pattern: Any URL, Types: Font, Action: Block

> nits?

> blocking cookies also blocks websites access to; localStorage ...

`:` instead of `;` but otherwise :+1:

**Comment by earthlng** [comment]
I think it's probably because of Private Mode/Windows and that everything is session-only there, plus the things that don't support session-only are disabled in PB, like IDB

**Comment by Thorin-Oakenpants** [comment]
@earthlng aww man .. what am I doing wrong with my whitelisting

```
[
  {
    "uuid": "savetheplanet",
    "pattern": {
      "scheme": "*",
      "host": [
        "mozilla.org"
      ],
      "path": []
    },
    "action": "whitelist",
    "active": true,
    "description": "Allow%20some%20fonts",
    "types": [
      "font"
    ],
    "title": "Whitelist%20some%20fonts"
  }
]
```

but it still blocks on bugzilla

**Comment by earthlng** [comment]
you may need `*.mozilla.org` and path: `*`. And read the manual

**Comment by dezhavu** [comment]
> 
> 
> @earthlng I can't find the post where you said how you were controlling fonts. Since I block all and only need to whitelist about 5 sites, I'm more than happy to do it the same way as you. What were you using, and what were the rules - TIA 💋

Why not using uBlock?

My Filters:
*$font,first-party,important
*$font,third-party,important

My Rules:
site.com https://subdomain.site.com font allow
or to have global access to this site fonts
* https://subdomain.site.com font allow

Only trouble is to look into uBlock Logger for fonts location, but in case you have only 5 sites could be feasible.

**Comment by Thorin-Oakenpants** [comment]
@dezhavu Because I want to reduce the risk of two or more extensions fighting over who gets to modify the webpage - only one wins, which means at least one of your extensions is not doing their job as expected - see https://github.com/ghacksuserjs/ghacks-user.js/issues/265#issuecomment-393935989

**Comment by earthlng** [comment]
What Pants said. I don't know about "filters" but AFAIK uBlock "rules" use CSP headers to block fonts and that screws with uMatrix. IDK if filters also use CSP but I think gorhill answered that in the issue Pants linked.

**Comment by Thorin-Oakenpants** [comment]
me
> edit: to be a little clearer, the **rule** for fonts causes an issue, so my question is, does the **filter** behave in the same way and can still cause an issue?

earthlng
> I don't know about "filters" but AFAIK uBlock "rules" use CSP headers to block fonts and that screws with uMatrix. IDK if filters also use CSP but I think gorhill answered that in the issue Pants linked.

Nope. I still have no idea. @gorhill :kiss:

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1413615 - this is an interesting little read

**Comment by slowfar** [comment]
Are there any features of Privacy Possum (data poisoning) that can be implemented with user.js ?

https://github.com/cowlicks/privacypossum

**Comment by Atavic** [comment]
Most of them. Privacy Possum blocks [etag](https://github.com/cowlicks/privacypossum/blob/09981f5cf704582416b62ea4664f3732bc4fd9db/README.md#etag-tracking),
while ghacks user js does it with [Header Editor](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.4-Header-Editor).

**Comment by Thorin-Oakenpants** [comment]
> Are there any features of Privacy Possum (data poisoning) that can be implemented with user.js

A user.js simply controls Firefox (FF) settings. So what can Firefox do (**i.e no extensions**) that Privacy Possum (PP) does. Let's go thru the list (without inspecting the degree to which PP does things - just taking the concepts at face value)

- PP: block cookies that track you
   * FF has a limited tracking protection
   * in FF you can disable third party cookies (but enable them on a site by site basis for the very few sites that need them)
   * in FF you can disable all cookies (but enable them on a site by site basis for the few sites that need them)
  * in FF you can use containers (which can limit some cookie based tracking)
  * in FF you can turn on `privacy.firstparty.isolate` (FPI) which will isolate cookies based on first party, but doesn't stop the actual cookies
  * FF can sanitize cookies and related storage on close, and manually (IDB can be an issue)
  * in combinations of settings, FF can totally control cookies

So in terms of cookies, extensions do almost jack shit, and can cause problems (leaving behind orphaned persistent data). But it's not perfect, because just connecting to a third party is enough (IP, JS, FP'ing) and FPI doesn't protect against repeat visits. Also, PP can be more of an install and forget, whereas FF in a more hardened mode will take time to curate your exceptions.

- Blocks refer headers
   * FF can limit some exposure via prefs, but any hardened approach to minimize tracking via this mechanism just results in a broken web. So I would say NO, you need an extension.

- Blocks etag tracking
   * FF cannot do this on it's own

- Blocks browser fingerprinting
   * There are so many FF prefs (hundreds) that affect your FP (fingerprint). Some good, some bad. Some FP'ing cannot be changed with FF prefs. It's a bit complicated.
   * Note: there are some FP'ing values that neither FF or an extension can change
   * Extensions are limited in some areas that FF can do (because .. you know.. its app code): such as screen resolution detected by css
   * FF has `privacy.resistFingerprinting` (RFP) which covers a lot of areas, but not all. It's a work in progress
      * Examples where it excels (compared to extensions which are limited or can do nothing) are timezone spoofing, screen etc measurements, user agent and navigator objects
      * Examples where its lacking right now (but in the pipeline): fonts, domrect, audio FP'ing, math libraries, css line height, scrollbar widths - it will take some time

In general, if RFP covers it then that is the best option (because app code can do more than extensions in most cases). With PP, it's also a different approach. RFP aims to lower entropy, PP aims to randomly increase entropy. There are pros and cons to both. But mixing them seems like a bad idea
