### ISSUE TITLE
FYI: Firefox Portable writes to appdata/ [solved: nothing to worry about]

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#623]
**C:\Users\YourNameHere\AppData\Roaming\Mozilla\Firefox\Crash Reports**

The file is called **InstallTime2019xxxxxxxx**

Is it possible to prevent this behavior via the about:config?

**Comment by Thorin-Oakenpants** [comment]
~~99%~ 100% sure the answer is no.

I just deleted everything in AppData/Roaming/Mozilla/ .. and the files reappeared within about a minute or two (Firefox is still running). All my FF's are portable. I got

* `/CrashReports`
  * file: `InstallTime20190108160530` (always 10bytes, contents are a 10 digit number, always the same one). That installtime probably reflects when I updated to 64.0.2
  * folder `/events` (empty)
* `/Pending Pings` (empty folder)

Thunderbird portable does the same. I actually just deleted the Mozilla/Firefox folder again, and it hasn't come back (after about ~~5~~ 15 minutes).

There's a difference between being *fully* portable and *stealth*. Firefox portable isn't something officially supported by Mozilla, but instead provided by portableapps.com. So you're always going to get some AppData files. I don't think there's really anything to worry about - just clean em all out of old junk once in a while (I had a peak in Local and LocalLow as well and nuked all them as well for the lulz), and make sure things like crash reports and pings are all fully disabled, and nothing should end up in there (besides the folders and that installtime file.

**Comment by Thorin-Oakenpants** [comment]
I might have been confused about FF recreating the folders etc when it was still open. Anyway, I closed Firefox and make sure everything in appdata was still gone. Then restarted FF.

this is what happens in `/Roaming` - everything is just empty folders except that one file in the pic
![meh](https://user-images.githubusercontent.com/16656956/51970265-5bffbd00-246e-11e9-8e5a-2456aa1fb9bc.png)

`/Local` creates an empty `Mozilla/Firefox`
`/LocalLow/Mozilla` containes tmp files and the directory only exists while FF portable is open

So if that's it, a single installtime file, then you're fine. If someone was on your computer, they could probably go after a hell of a lot of other forensics than dig up dig on when you updated your Firefox (and I'm not even sure if that's when YOU did it, or it's based on the date of the release)

**Comment by Thorin-Oakenpants** [comment]
if you go to about:config, and search for `2019` you will see the date/time values come from
`extensions.lastAppBuildId` - so assuming someone else's 64.0.2 is the same as mine, it's not even unique

psst!: I wouldn't go messing with those values

**Comment by Thorin-Oakenpants** [comment]
the value inside the file comes from `toolkit.startup.last_success`

**Comment by Just-me-ghacks** [comment]
Thanks, Pants! You're absolutely right.

So Mozilla is not spying on us by dropping files containing the lastAppBuildId and last_success? I guess they use other methods :)

I use CCleaner + winapp2 to clean this crap.

**Comment by Thorin-Oakenpants** [comment]
spying? heh .. I get it man, but at some point, draw a line. Mozilla aren't out to spy on you and get your PII. Sure, you want FF to be quiet, or you don't want to leave any forensics. We can already keep FF "quiet", and to be totally sure on forensics, use a VM / tails or something.

You need :cat2: 's tin foil hat: https://mcphee.com/products/tin-foil-hat-for-cats
