### ISSUE TITLE
dom.targetBlankNoOpener.enabled

### ISSUE THREAD

**Issue by WolfgangWeber** [ghacksuserjs/ghacks-user.js#629]
Maybe you should add the following option to your version of user.js:

```
// Add rel="noopener" automatically to links that use target="_blank"
// [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1503681,1522083
user_pref("dom.targetBlankNoOpener.enabled", true);
```
This option is regarded as experimental ATM and should default to true in FF67+. (It's only enabled in Nightly yet.)
Might obsolete using the extension "window.opener be gone" (?)
Additional source:

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#Security

Thanks for your hard work!

**Comment by Thorin-Oakenpants** [comment]
I asked earthlng (but now can't find it)... it is not a substitute for `windows.opener be gone` as it only covers one or a few href types.

As for adding it to the user.js, I'd was going to just wait until it became default true and forget about it - one less thing to enforce and add .. but now I'm kinda keen to add it and point to window.opener be gone as well

**Comment by earthlng** [comment]
in https://bugzilla.mozilla.org/show_bug.cgi?id=1522083 they say that ...

> ... it seems we can enable this by default as there's been nothing thus far in terms of fallout?

I guess the question mark is about the "enabling it by default" part and not about the "no fallout". So yeah I think we can safely enable it already. It's certainly better than no protection and a welcome new feature but it has its limitations fe in all their commits they added "when no rel attribute is set" which means that there are ways around it even with just plain `<a>` tags, not to mention windows opened with JS. But it should cover the most common abuse cases where pages allow user-provided links on their pages.

**Comment by Thorin-Oakenpants** [comment]
moving this to 65 diffs where the item already exists
