### ISSUE TITLE
0850

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#63]
```
/* 0850b: disable location bar dropdown
 * This controls the maximum number of entries that can appear in the location bar dropdown.
 * Zero completely disables it. If you want ANY dropdown functionality, this must be changed ***/
```
Zero **does not** completely disables it.

```
/* 0850c: disable location bar suggestion types
 * [SETTING] Options>Privacy>Location Bar>When using the location bar, suggest
 * [NOTE] If you wish to enable these suggestions, make sure 0850a and 0850b are at default ***/
```
0850b doesn't need to be at default to enable... actually can be anything, but results are funny.

0850a is a master switch, since you have the false value, I don't see a reason to force 0850b to 0.

**Comment by Atavic** [comment]
```
/* 0850b: disable location bar dropdown
user_pref("browser.urlbar.maxRichResults", 0);
```
Maybe with -1 

```
/* 0850c: disable location bar suggestion types
 * [SETTING] Options>Privacy>Location Bar>When using the location bar, suggest
 * [NOTE] If you wish to enable these suggestions, make sure to have 0850a set tot true ***/
```

**Comment by Thorin-Oakenpants** [comment]
> Zero does not completely disables it.

In what circumstances with the dropdown's results limited to 0 entries, does the dropdown become enabled? Can you give me an example? AFAIK, "Zero completely disables it". If it cannot show ANY results, then it won't show - i.e the DROPDOWN is disabled. Maybe if I used the word "hide" instead of "disable" then it would be more obvious that I'm talking about the control, not the functions using it?

> 0850b doesn't need to be at default to enable... actually can be anything, but results are funny.

What does "funny" mean. Can you give me an example?

> 0850a is a master switch, since you have the false value, I don't see a reason to force 0850b to 0.

0850a is a master switch for "some things", not everything - there are other *urlbar* settings such as oneoffsearches etc. Also, not everything uses a dropdown, some items can/could/did/whatever use a doorhanger. IDK. PK uses only 0850b to disable all this, meaning the firefox code is still finding items to stick in the suggestions, but you won't see them. We choose to turn off and/or list as many switches as possible for futureproofing, completeness+knowledge, as well as doing it properly (why just hide something but let the code still run as a useless performance hit, even if that hit is 0.0000001%).

**Comment by crssi** [comment]
Those are the settings I use dfifferent to ghacks
I don't see any reason, not to have a search over bookmarks and open tabs.
``` js
user_pref("browser.urlbar.autocomplete.enabled", true);
user_pref("browser.urlbar.maxRichResults", 10);
user_pref("browser.urlbar.suggest.bookmark", true);
user_pref("browser.urlbar.suggest.openpage", true);
```
Now you can "play" with maxRichResults.
Open a few tabs with for example ghacks github, have a few bookmarks with github.
Set maxRichResults = 0, type into URLbar "github", you will see that 0 does not disables it.
Funny thing is that if you set to any number fro 0-9 you don't exact that number of items.
The only really true is 10, since this is max that FF will show, even when you set to more than that.
Ah, my english... I hope you will understand. ;)

**Comment by earthlng** [comment]
Thanks @crssi! perfectly understandable english right there :)
I played with it and see what you mean. I behaves more like a MIN than a MAX value (now?).
Even when I set it to 1 it sometimes shows 3 or 4 or whatever, depending on the amount of bookmarks and/or history I have for a certain letter (fe. I type "f" and it shows 4 bookmarks + 1 from history)

> I don't see any reason, not to have a search over bookmarks and open tabs, since it speeds-up productivity.

I agree. I mean there's a potential problem with shoulder surfers, but I don't have that problem on my home machine.

**Comment by earthlng** [comment]
> The only really true is 10, since this is max that FF will show, even when you set to more than that.

You can show more than 10 but it looks like you need some custom CSS to make it work.

**Comment by earthlng** [comment]
Idk what we should do here, but it seems the only way to effectively "hide" it, is to disable the suggestions for bookmarks, history, open tabs and search. So at least I think we should comment out the `maxRichResults`, also because I assume most users don't mind having that useful feature

**Comment by Thorin-Oakenpants** [comment]
I honestly can't see this being referenced or used by anything. It's like a dead function nothing ever calls: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/urlbarBindings.xml#1499

So I fired up a clean FF52, defaults for all five 0850s, added some quick history and bookmarks .. blah blah blah .. same as you guys. This does nothing to stop suggestions. I didn't only tried with the three in 0850c, didn't bother to try with combos involving search in urlbar.

I also didn't bother to test the observation that as a MAX value (eg 1), it's over-ridden (see earthlng's 4 results with a value of 1).

Looks like a load of ineffective, does-not-work-as-advertised code to me.

**Comment by Thorin-Oakenpants** [comment]
```js
/* 0850b: disable location bar dropdown
 * This value used to control the maximum number of entries that could appear in the location
 * bar dropdown. This is no longer the case, and thus, it does *NOT* hide any suggestions ***/
   // user_pref("browser.urlbar.maxRichResults", 0);
```

**Comment by Atavic** [comment]
There's a difference between never enable such url features and disable them: in the latter case, without erasing the leftovers, they will appear again.
