### ISSUE TITLE
0304 and 0305

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#64]
If 0304 is set to false, then 0305 does not to be forced to false.

**Comment by Atavic** [comment]
But if you check manually for updates, with 0305 True it will update automagically.

https://support.mozilla.org/t5/Firefox/Difference-between-extensions-update-autoUpdateDefault-and/m-p/671289

**Comment by crssi** [comment]
Aaaa... got the point. Nasty one.
