### ISSUE TITLE
0307: lightweightThemes.update.enabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#648]
Section 0307 reads:

```
/* 0307: disable auto updating of personas (themes) ***/
user_pref("lightweightThemes.update.enabled", false);
```

Is the description accurate?  Does the pref really disable auto-updating of personas (themes)?  I think if the pref is `true`, but `Update addons automatically` is not enabled in `about:addons`, then the personas will not be auto-updated.

**Comment by Thorin-Oakenpants** [comment]
Looks like a rubbish pref to me. I don't even know if it's a thing any more, since Quantum. And themes are not an issue AFAIK (unlike extensions which can go rogue). If you look at themes vs addons in options, you will see they actually use the same cog wheel and menu for controlling them.

So yeah, I think we can remove this pref altogether - after the Big E scopes it out

**Comment by Thorin-Oakenpants** [comment]
when the big E says its OK to remove it, if he doesn't, I will ..so just waiting on @earthlng

**Comment by Thorin-Oakenpants** [comment]
lightweightThemes are, I guess, what they are using for themes? e.g I use the inbuilt dark theme, and I use compact .. and I have this
- `lightweightThemes.selectedThemeID` - `firefox-compact-dark@mozilla.org`

But if we set extensions to not auto-update, then we should also set themes to not update to be consistent. I will install a theme on a test profile, an older version of a theme and see what happens when I check for updates

**Comment by Thorin-Oakenpants** [comment]
> If you look at themes vs addons in options, you will see they actually use the same cog wheel and menu for controlling them

Exactly. I set all updates to manual. Installed an older version of a theme. When I went to about:addons > Extensions> cog wheel > check for updates ... it dutifully found an update for the theme.

So it really begs the question of do we want to keep this or ditch it because it has no privacy etc issues. And if we keep it, maybe make it inactive - but then what purpose does it serve? None, so I think we should ditch it - **and update* the extension pref to include the word themes

**Comment by Thorin-Oakenpants** [comment]
the pref doesn't seem to affect any updating
![themes](https://user-images.githubusercontent.com/16656956/52707946-d35e4200-2f80-11e9-9041-57b7bb72becf.png)

**Comment by Thorin-Oakenpants** [comment]
I wonder if search update is the same

**Comment by earthlng** [comment]
`lightweightThemes.update.enabled` is used in [updateThemes()](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#354-356) which is called from only 1 place in the code and that's in [backgroundUpdateCheck()])(https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManager.jsm#1276) but only if `extensions.update.enabled` is true.

So what @Gitoffthelawn said in OP is correct ...

> if the pref is `true`, but `Update addons automatically` is not enabled in `about:addons`, then the personas will not be auto-updated.

Some people might want to have extensions updates enabled but lightweightThemes updates disabled. I'd prefer to keep the pref for that reason

**Comment by earthlng** [comment]
`Update addons automatically` seems to toggle `extensions.update.autoUpdateDefault` and IDK if there's a UI setting for `extensions.update.enabled`

**Comment by Thorin-Oakenpants** [comment]
> UI setting for extensions.update.enabled

The cog wheel in about:addons: toggling the check mark on the menu item for "Update Add-ons Automatically" only changes `extensions.update.autoUpdateDefault` - I took copies of prefs.js and compared them between changes.

So we should remove this from 0301b - yes? no?
```
 * [SETTING] about:addons>Extensions>[cog-wheel-icon]>Update Add-ons Automatically (toggle) ***/
```

**Comment by Thorin-Oakenpants** [comment]
> Some people might want to have extensions updates enabled but lightweightThemes updates disabled. I'd prefer to keep the pref for that reason

But I tested it, the pref did not prevent the update checking or the update itself, see the pic above

**Comment by earthlng** [comment]
yeah it's apparently only checking the pref in the **background** update check. I guess doing a manual check ignores the pref

**Comment by Thorin-Oakenpants** [comment]
OK, AFAICT the theme pref doesn't actually stop any updates of themes

Nilla profile

- set extensions to update automatically:
    - extensions.update.enabled = true
    - extensions.update.autoUpdateDefault = true
- block themes from "auto"? updating
    - lightweightThemes.update.enabled = false
- add an out of date extension
   - i installed https://addons.mozilla.org/en-US/firefox/addon/arc-dark-theme-we/versions/
   - version 2018.8.24
- add an out of date theme
   - i installed https://addons.mozilla.org/en-US/firefox/addon/etag-stoppa/versions/
   - version 0.3
- go to about:addons and view metadata for extension and theme and check versions are the old one, they are
- do a manual check: it auto installed the update for ETag Stoppa (to 0.4) **AND** the theme (to 2018.9.24)

What am I missing here, except doing the same test with extensions.update.enabled = false

**Comment by Thorin-Oakenpants** [comment]
I'll redo that same test, to make sure. I **THINK** that it didn't notify me about the theme update.

**Comment by Thorin-Oakenpants** [comment]
OK, so I turned off `extensions.update.autoUpdateDefault` and reran the test. When checking manually for updates, it returned two updates available, and both were auto-checked to include in the updates

**Comment by Thorin-Oakenpants** [comment]
Am I missing something here?

Do I set all three to false?
extensions.update.enabled = false (master switch?)
extensions.update.autoUpdateDefault = false (so I can see what is going to be updated)
lightweightThemes.update.enabled = false (which is WTF we're trying to see if it has an effect)

Then when I do a manual check, see what is listed? :headspin: :needcoffee:

**Comment by Thorin-Oakenpants** [comment]
I've basically tired every combination of these
- extensions.update.enabled
- extensions.update.autoUpdateDefault

with this
- lightweightThemes.update.enabled = false

and in every single case the theme pref does nothing

**Comment by Marc05** [comment]
The amount of effort put into this seemingly absolutely insignificant issue is the kind of work that makes this project outstanding. Thank you, and please keep doing it for as long as I use Firefox :P

**Comment by Thorin-Oakenpants** [comment]
LWT (lightweight themes), also known as personas, were introduced in [FF3.6](https://blog.mozilla.org/addons/2009/10/21/personas-now-on-amo/). Starting in FF55, Firefox released a new [Theme API](https://blog.mozilla.org/addons/2018/03/08/theme-api-update/), which is more powerful, etc

So the pref still works as advertising (I assume), but LWTs will be a thing of the past, soon. AMO stopped accepting them quite some time ago. And existing LWTs will be converted - see [this](https://blog.mozilla.org/addons/2018/09/20/future-themes-here/) (scroll down to Migrating Lightweight Themes) and all LWT code stripped out in good time.

So, @Gitoffthelawn : yes the pref does actually do what it says. It stop the updating of LWTs or personas
