### ISSUE TITLE
Any plans for System Wide Settings (syspref.js)

### ISSUE THREAD

**Issue by return42** [ghacksuserjs/ghacks-user.js#652]
Hi and thanks for this interesting project. Are there any plans to support System Wide Settings?  

E.g. in my debian systems I always modify `/etc/firefox/syspref.js` to apply it to all users.

**Comment by Thorin-Oakenpants** [comment]
Well, it already *supports* syspref - just change the type (`user_pref` to `pref`). Same goes for autoconfig (`lockPref`, `defaultPref`, `clearPref`, `pref`, etc) - there's no point in having multiple copies of essentially the same thing

unless I'm missing something - I am not linux savvy - in which case, feel free to elaborate and re-open
