### ISSUE TITLE
Problem with time on PiHole webinterface

### ISSUE THREAD

**Issue by beerisgood** [ghacksuserjs/ghacks-user.js#653]
With this user.js i got another time range on my PiHole webinterface which running on a local RaspberryPi.

Of course i config the right time on the Pi itself, but the support tell me that the webinterface use the browser time for the timeline querys.

I wonder which setting give me the wrong time (-1 hour compared to my time "Berlin")

**Comment by Thorin-Oakenpants** [comment]
Sorry, you'll have to explain

Your PC or whatever sends all it's traffic thru PiHole. In a normal vanilla profile, the time displayed in your Firefox Browser is e.g Berlin time. You then add this user.js and restart and the time displayed in Firefox is now Berlin -1?  This user.js uses RFP which spoofs your time zone as UTC 0

Right now as I type, it is basically 4PM in Berlin. At the same time it is 3PM in UTC 0 time.

Does that explain it?

**Comment by Thorin-Oakenpants** [comment]
![ticktock](https://user-images.githubusercontent.com/16656956/53250512-71a18480-36b2-11e9-9df1-746d0b04926c.png)

**Comment by beerisgood** [comment]
Thanks, your hint was right.
Because of RFP and the switch to UTC 0, the webinterface don't display latest entries.
