### ISSUE TITLE
Firefox doesn't process the user.js file for me

### ISSUE THREAD

**Issue by anonsubmitter** [ghacksuserjs/ghacks-user.js#660]
I've downloaded the user.js files and changed a few false values to true. When I put the user.js file into the profile folder (AppData/Local/Mozilla/Firefox/Profiles/[randomlettersandnumbers].default) and start and close Firefox twice, nothing has happened. No about:config values have changed. What am I doing wrong?

**Comment by anonsubmitter** [comment]
I finally saw what was wrong, I was in the Local directory, not in Roaming.

**Comment by Thorin-Oakenpants** [comment]
damnit .. I need :coffee:
