### ISSUE TITLE
RFP & 2505 enumerate media devices

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#661]
note/reminder to follow up on this

```js
/* 2505: disable media device enumeration [FF29+]
 * [NOTE] media.peerconnection.enabled should also be set to false (see 2001)
 * [1] https://wiki.mozilla.org/Media/getUserMedia
 * [2] https://developer.mozilla.org/docs/Web/API/MediaDevices/enumerateDevices ***/
user_pref("media.navigator.enabled", false);
```

https://wiki.mozilla.org/Security/Fingerprinting
> When RFP is enabled, enumerateDevices reports that the user has one camera (named 'Internal Camera') and one microphone (named 'Internal Microphone'). The devicechange event is also suppressed.

```
 ** 1372073 - spoof/block fingerprinting in MediaDevices API (see 4612) (FF59+)
```

Ummm .. how did I miss moving this to RFP alternatives? I only moved the devicechange pref

@earthlng Just confirm I'm not missing something here, and that 2505 -> RFP alt section - edit: bugzilla link https://bugzilla.mozilla.org/show_bug.cgi?id=1372073

**Comment by earthlng** [comment]
IDK, there's probably a lot more troubling stuff behind media.navigator than just enumerateDevices.
I don't remember exactly but a while ago I played with it a bit and do remember that despite there being a prompt, it still allowed to fingerprint screen resolution without triggering the prompt, for example.
I would keep it where it is.

**Comment by Thorin-Oakenpants** [comment]
PS: FYI:
https://privacycheck.sec.lrz.de/active/fp_e/fp_emoji.html
https://privacycheck.sec.lrz.de/active/fp_ml/fp_ml.html

and other pages

**Comment by Thorin-Oakenpants** [comment]
OK. I'll have to think about this. It will alter your FP (but lets face it, everyone's FP is fucked anyway if someone digs deep enough) from other RFP users on this metric. But that's probably better than leaking more accurate metrics

I think I could add a line in the header `1372073 line` re "see 2505 which we are opting to keep disabled" - I'll close it when I do the commit

**Comment by Thorin-Oakenpants** [comment]
I kinda feel like 2505 could do with a `[SETUP-RFP]` tag to allow some people (who need to use their webcam) to relax it (and give them some peace of mind) . but then again, if they want to use their webcam, then they would anyway.

It's just so odd to have something RFP addressed not in the RFP alts. Keeps me awake at nights...
