### ISSUE TITLE
enable flash detection

### ISSUE THREAD

**Issue by gourya** [ghacksuserjs/ghacks-user.js#666]
I am trying to enable flash in Firefox 52 like I changed the "plugin.scan.plid.all" to true and "plugin.state.flash" to 2 but flash in not detected in net.

I see the flash plugin in firefox addon page and is always activated. I am using the latest flash version.

It's there anything else, which I have to make so I can have enabled flash in firefox?

**Comment by earthlng** [comment]
`privacy.resistFingerprinting` hides the contents of navigator.plugins - might be that, IDK

**Comment by gourya** [comment]
@earthlng thank you. Flash is working now.

**Comment by Thorin-Oakenpants** [comment]
ermmagerrrrrd... issue #666 was about Flash :imp:
