### ISSUE TITLE
FYI: I think we're on the right track...

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#668]
I had a little downtime, and was just doing some light reading on browser fingerprinting from Slovakia, as one does (it was either that or drinking some boring beer), and came across a reference to the ghacks user.js ... cool :sunglasses: 

PDF: http://virpo.sk/browser-fingerprinting-hraska-diploma-thesis.pdf - page 45

>  Firefox settings can also be imported and exported using a single file. This possibility encouraged its users to create a comprehensive open-source template for Firefox settings called ghacksuser.js [4]. The latter contains a predefined configuration that strengthens Firefox’s security, privacy, and anti-fingerprint character. Browsers with these settings are less likely to be unique. Moreover, all browsers using this settings template will, in most cases, have the same fingerprint.

This is a 2018 master's thesis by Peter Hraška - totally digging the sample size and real-world data-set, as well as focusing on a stable and minimum set of FP'ing items. Shame it lacked DOMRect and a better math test suite.

---

@ViRPo

Not sure if you're still into all this stuff given you have finished your masters. I have some more info for you - especially about math functions detecting platform and architecture and 32 vs 64bit builds, as well as DOMRect fingerprinting, which is probably as revealing as Canvas. 

I found the information on math FP'ing very scarce and tan(-1e300) to be old and no longer reliable (within Firefox, i think, I didn't keep the limited test data I did: I would be interested in your data set on this metric for Firefox). Instead I found a Japanese research paper from mid to late 2018 that highlighted eight `math.cos` values that do more than enough. BUT, then I added in some ECMAScripts 6th Edition math functions which also added entropy in their own right, and combined I can get more than just platform and browser. Chrome (non webkit) is the same on all platforms and 32 vs 64 builds, but I don't care about Chrome - however this signifies that the Tor Uplift or Firefox could do the same.

FYI: I am actively working on these over at [TorZillaPrint](https://github.com/ghacksuserjs/TorZillaPrint) - the link to the test site is in the readme. It's a work in progress. I'm also interested in the data you have on error messages, and maybe a few other things :)

PS: For the record: I've been working fairly closely with the Tor Uplift guys at Mozilla for a while - that's the team behind the  `privacy.resistFingerprinting` and `privacy.firstparty.isolate` etc prefs

PPS: Thanks for the reference :kiss:

**Comment by Thorin-Oakenpants** [comment]
No point leaving this open. For those interested, I have reached out to Peter via email, and if he's interested then we can talk in TZP's repo (or here)

**Comment by ViRPo** [comment]
Hi there!

I am sorry to keep you waiting
It is funny, that you mentioned a Japanese research - I am currently travelling all around Japan, which is why I couldn't reply sooner :)

I am super glad to hear you found my work useful and I will gladly provide you with more information and answer further questions once I get back from my travels (~2 weeks)
I will probably post the answers here for future reference

Would that be ok? :)

Also, could you give me a hint on where to find the Japanese paper?

I am not doing a hardcore research on browser fingerprints anymore, but I am still trying to keep myself up to date with the topic and haven't lost my interest :)

**Comment by Thorin-Oakenpants** [comment]
> Also, could you give me a hint on where to find the Japanese paper?

Sure. Email sent. Let me know if you don't get it

> I am super glad to hear you found my work useful ...

It really backed up almost everything I thought I knew (I've been dabbling in this stuff ever since Eckersle), especially real world stats vs sites such as Panopticlick etc.

> I will probably post the answers here for future reference... Would that be ok? :)

Sure. Or you could post em at TZP's repo which would be a bit more relevant: https://github.com/ghacksuserjs/TorZillaPrint/issues - just open or find a relevant issue

> once I get back from my travels (~2 weeks)

Enjoy :) Ignore my impatience .. and have a great holiday :beers:

**Comment by KOLANICH** [comment]
@ViRPo,

>We were able to collect 566,704 browser fingerprints with 323,746 distinct browser IDs.

I guess that count of fingerprints is a natural number, so `,` is a digit group separator, not decimal one.

>By far the largest source of data on which we were able to apply **our** browser fingerprinting script was a web application used for enhancing audience interaction on events by allowing them to ask questions or answer polls. Since this web app is mainly used by event participants, most of them will use their smartphone to access it. Indeed, around 65% of its, approximately, 200,000 active users per week use mobile phones/smartphones, and 4% use tablets to access it.

So ~ 307692 `active users` at total. Assumming that a user has 2 device and almost noone uses private mode in average it results in ~153846 users per week.

1. Feels like too many. Especially too many, if one take in account that not everyone uses these webapps. I don't beleive that such popular platforms for building conference webapps exist. Is `,` used consistently as a groups separator?
2. How could you make an author of such a platform to risk his business interests and insert the backdoor? I don't beleive that Comenius University has enough money to buy successful businesses in order to create datasets for students' mastertheses.

**Comment by Thorin-Oakenpants** [comment]
I know this was directed at ViRPo but ....

I can't understand or follow what you're asking. What is a "group separator"? Do you just mean a comma? If it was decimal it would be a period. These are clearly numbers in the hundreds of thousands. I've never written a master's thesis, but using the comma in the number is the expected / universal / standard format in such a document.

566,704 FP's collected (five hundred and sixty six thousand... etc)
323,746 FP's were "distinct" (i.e unique - no one else had the same FP)

---

Where is the figure `307692` "active users" coming from? The 3rd test was a JS web app (see 4.1 Sources of data). This is the source that harvested 566704 FP's. I'm not Peter and I didn't run this test, but each browser was assigned an ID (cookie, local storage)

From the paper
> This way, the browser ID will be stored even if the cookies are unavailable, which occurs frequently

However, at least in Firefox, this hasn't worked for many years - for as long as I have known and tested, if you block cookies within Firefox's settings, localStorage (among other APIs) is not available. Also Private Browsing mode (and incognito?) etc don't keep local persistent data. Maybe Peter can elaborate on the dataset. e.g does the dataset include those browsers that blocked persistent storage. Even if it didn't, it still allows for repeat visits by the same browser if they sanitize local storage, e.g on the fly or manually or on close, or with third party apps. 

Still totally confused where 307692 active users comes from. And why does it matter if users have one device, or a hundred. The fingerprint is a "browser" fingerprint - who uses the browser on what platform is immaterial. Unless I'm missing something you're trying to convey. Almost 243 thousand (out of the 566+ thousand) shared FP's (at least two had the same) seems very high and suggests multiple visits by the same browser+device: i.e the browser id tracking failed. Then again, it could be that high because of the number of smart phones in the set (although I'd have to re-read the whole thesis, but I think Peter, and others, have found smart phones leak more entropy?) - e.g in my experience, the font signature on say iOS and Android are fairly set in concrete, and the OS by design harder to "play with" (esp for the average end user).

I also wouldn't call client side JS a [backdoor](https://en.wikipedia.org/wiki/Backdoor_(computing))

Anyway, sorry for the ramble. **Yes**, those are numbers formatted with [commas](https://en.wikipedia.org/wiki/Comma#In_numbers)

> In representing large numbers, from the right side to the left, English texts usually use commas to separate each group of three digits in front of the decimal. This is almost always done for numbers of six or more digits and often for five or four digits but not in front of the number itself.

**Comment by KOLANICH** [comment]
>I can't understand or follow what you're asking. What is a "group separator"? Do you just mean a comma? If it was decimal it would be a period.

Decimal separator is point in US. In mainland Europe (Slovakia is in Europe) it is comma.

![](https://upload.wikimedia.org/wikipedia/commons/a/a8/DecimalSeparator.svg)

>Where is the figure 307692 "active users" coming from?

`200000 users of mobile devices among users of the third app / 0.65 share of such users`

>However, at least in Firefox, this hasn't worked for many years

My experience says me that noone among the people I know uses any privacy extensions, adblockers and settings tweaks (except the ones who have them installed by me), and all of them think it doesn't worth the mental load it takes to worry about all these stuff. And these is not about IT knowledge and skills, it is about mentality. I assumme that share of users using private browsing mode among conferences visitors is negligible.

>I also wouldn't call client side JS a backdoor

Of course it is. How we define a `backdoor`? Supply chain attack is inserting malicious functionality  by someone who is part of supply chain. And we call this malicious functionality a `backdoor`. What is the supply chain in this case? `App developers -> ??? -> conference`. Is browser fingerprinting a malicious functionality? It is used to track users and most of users prefer it be missing, even if they don't care enough to do any actions about it. So I consider this functionality malicious. So the described case satisfies this definition of a `backdoor`, doesn't it?

>And why does it matter if users have one device, or a hundred.

Because it affects correctness of estimation of count of people using this app. Count of people using this app is a measure of success of that app. Measure of success of that app can be used try to guess odds that in the case of app being commercial its owner would be willing to risk its business for someones masterthesis. In the case of popular free open source software contributors will likely detect that and fork the app and banish its original dev for that. Also estimation of count of users can be used to check if enough conferences with enough visitors exist in the world to have that count of users (I don't believe in it, but it should be really checked by finding some website aggregating stats about conferences).

>Almost 243 thousand (out of the 566+ thousand) shared FP's (at least two had the same) seems very high and suggests multiple visits by the same browser+device: i.e the browser id tracking failed.

I don't believe that randomization of fingerprints is used in large scale by ordinary people, like the ones visiting conferences. Wnd as far as I understand, fingerprint2js was used, which is a pretty mature library.

**Comment by Thorin-Oakenpants** [comment]
> Decimal separator is point in the US. In mainland Europe (Slovakia is in Europe) it is comma.

Really? I never knew that, then again I'm not European - https://en.wikipedia.org/wiki/Decimal_mark

> Because it affects correctness of estimation of count of people using this app

It's not counting people, it's counting browsers. Numbers of people are immaterial.

> Where is the figure 307692 "active users"...

"566,704 browser fingerprint samples, 65% of which are from smartphone device" - from the thesis. Ahh, OK, that then is **368358** FP's.

> My experience says me that noone among the people I know uses any privacy extensions, adblockers and settings tweaks.. [and from earlier] ... Assuming that a user has 2 devices and almost no-one uses private mode in average it results in ~153846 users per week.

You can't make assumptions, and you can't use anecdotal evidence. It's a shame the FP didn't allow for detecting PB/incognito mode (which can easily be done). But at least it tries to store a "browser id" to reduce duplication - which is why I said it "seemed" to be a little high (for non-unique FPs). Your argument that most end users aren't tech savy and/or too busy and just use the browser in a default state (or close to it) actually supports that repeat visitors would be re-identified by the stored browser id.

However, what I am saying is that it "seems" that 43% of the 566 thousand FP's were not unique is rather high given your statement, and the above fact that a browser id was used.

There are studies (but I'd have to re-dig them up, so it's from memory) that increasing amounts (percentages) of users are resorting to privacy extensions and PB/Incognito etc modes. 83% of users would switch browsers in one study by DDG if it increased their privacy- and that was almost 2 years ago). And awareness is increasing. Since that study (which might be an outlier), it's only gotten "worse", what with all the data breaches and fallout over FB etc. Even main stream everyday news is full of this stuff in my experience - articles that were mainly the preserve of tech blogs like arstechnica, wired, etc, are now becoming common on sites like the guardian, la times, etc. The public may not know what to do, but they sure do know about it and most care if given an easy choice.

Adblockers here have nothing to do with it (except that detecting an abdblocker was a metric) - the script is 1st party (at least on the demo site) and not blocked for results (or else a FP would not be generated). So while, e.g for Firefox I have read (from memory) that 30% of users have 1 extension, and that 1 extension is an adblocker. And IDK, 50% of Firefox users have no extension. Old figures from memory. That doesn't leave many people.

I actually agree with you that only a small percentage (IDK, 1% to 2%?) would actually have reasonable setups. But in terms of FP'ing, **almost no-one would**. Almost no-one in Firefox would have RFP on. Other browsers lack inbuilt ability to mask FP metrics - hell, even FF hasn't got us our fonts sorted out.

So it seems strange that the non-unique percentage is so high. But I think we can partially lay that at the FP script (see below)

Again, the number of people is not relevant - it's not called a People Fingerprint, is it? If a person has an android device with chrome, and a windows 10 laptop with Firefox, then that's two FPs, not one person. And number of users per week is meaningless. Nothing is measured against time here.

> So the described case satisfies this definition of a backdoor, doesn't it?

No, it doesn't. It's not even malicious, for starters

> as far as I understand, fingerprint2js was used, which is a pretty mature library

The fpjs2 script is fairly small and simple. Given most people are auto-updated, and most people use one of 5 main browsers - things such as HTTP headers, UA strings, tan, cookies+ localstorage + sessionstorage + IDB, IE plugins, DNT - are going to be the same within the same browser by default. They only serve to help differentiate the browser (chrome vs firefox etc), or catch out a few users or tell fibs or tweak some settings.

The real FP'ing comes from items like audio and canvas, and maybe fonts. Given those metrics were included, **THAT** is why I find it so surprising that 43% of users were not unique. The high number of smartphones probably played a role - stock safari/chrome on stock iOS/Android = bound to be duplication. (but I thought Peter said smartphones gave more entropy?).

Anyway .. time for some nudity and beer drinking

**Comment by KOLANICH** [comment]
>Again, the number of people is not relevant - it's not called a People Fingerprint, is it? If a person has an android device with chrome, and a windows 10 laptop with Firefox, then that's two FPs, not one person. And number of users per week is meaningless. Nothing is measured against time here.

As I understand, distinct browsers are counted by cookies, and I assummed that assumming that noone clears them would not make a big error. So I have assummed that a conference visitor has accessed the webapp from 2 devices: a laptop and a phone, and divided 307692 by 2 and as an estimation of count of people users per week. Seems like too many.

>It's not counting people, it's counting browsers. Numbers of people are immaterial.

Yes, but I want to calculate count of people. I don't quite understand how a research institution managed to make a popular and succesful web app to install own backdoor into it on the market where competition is present.

>You can't make assumptions, and you can't use anecdotal evidence.

Why not? It is a GH issue, not a paper. We use the assumptions to quickly estimate the number and ask the author some questions about his ressearch.

>Given those metrics were included, THAT is why I find it so surprising that 43% of users were not unique.

Fonts fp gives identical results in identical environments (os + libs + browser). Canvas fp should give identical results in identical devices, like most of phones are (again, in my experience almost noone (among my collegues) changes ROM and almost everyone (among my collegues) uses chinese devices by companies spotted on inserting backdoors.

**Comment by Thorin-Oakenpants** [comment]
> Why not? It is a GH issue

Well, actually, it's a discussion about Peter's thesis and FP'ing. But, OK, I thought you were "attacking" (for lack of a better word) the integrity of the data, method of stats etc. But I see you're just fixated on other aspects of it (e.g "Yes, but I want to calculate count of people"). The paper (should) outlines limitations as far as I remember

I still do not follow what all this stuff about a conference is. I read that paper, slowly, over several cups of coffee (but just the once mind you), and never saw anything about a conference. I did take in the bit about smart phones and something about "web app" - maybe I should re-read it again when I get time.

> As I understand, distinct browsers are counted by cookies ... and I assumed that assuming that noone clears them would not make a big error.

That's what I understood, and also by localStorage in case cookies were blocked, which doesn't make sense to me. Maybe non-FF browsers allow one but not the other, but FF doesn't.

**no-one clearing them would eliminate duplicates (or errors) of browsers allowing a cookie**. That's the whole point :grinning: Which is why **I, me, myself** am surprised by the 43% being not-unique. But I did then say that smartphones which make a big percentage, have the same FP in a lot of metrics because, as you said, they are the same OS and default browser and auto-updated, and these OSes tend to be fairly locked down. But there is a bit of a wider distribution of hardware, which would then add more entropy in e.g canvas/audio - but still, many people have the same phone models - so ti should be easy to not be unique, especially as the test size gets bigger and bigger.. So again, we're on the same page.

Anyway .. when Peter stops getting drunk in that Tokyo strip club and returns to GitHub, I'm sure he'll address your questions :)

**Comment by KOLANICH** [comment]
>never saw anything about a conference.

Neither did , but

> were able to apply **our** browser fingerprinting script was a web application used for enhancing **audience interaction on events**
>used by event participants, most of them will use their smartphone to access it

sounds like if an `event` was a synonym to a `conference`.

**Comment by Thorin-Oakenpants** [comment]
from a 266 page 2018 thesis I'm currently reading...

> Nikiforakis et al. (2014a) established that smartphones frequently shared the same fingerprint ID because they have few attributes that can be accessed by the browser fingerprinting technique.

Not that I have looked up the source (Nikiforakis et al) or read it. But it strikes a chord with what we were both saying

**Comment by KOLANICH** [comment]
>Edit: FYI: the 266 page pdf if you want some light easy reading and you have a few spare minutes: https://eprints.soton.ac.uk/427361/1/Final_Thesis.pdf .. I'm up to page 62

thanks.
