### ISSUE TITLE
Possible to set default search engine with user.js?

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#669]
In earlier FF versions, it was possible to set the default search engine with user.js.

With FF 66, is it possible to set the default search engine with prefs?

**Comment by Thorin-Oakenpants** [comment]
> is it possible to set the default search engine with prefs?

No.

AFAIK: The default search engines are in `omni.ja` (FF34.0.5+). The searchplugins folder was used for add-on search engines from Firefox 34 thru 44. In Firefox 45+ the add-on search engines were moved to a new `search.json` file. Note that current Firefox releases use a single compressed `search.json.mozlz4` file in the profile folder to store search engine data including keywords

I just did a test by pulling up any "search" files in my profile and watching the lastmodifed time stamps when I changed my default search engine via options. It looks like that info is in `search-metadata.json`

It certainly is not available via prefs

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants Thanks.  You're talking about something different than what I meant.  Sorry I wasn't clear.

What I mean is not the available search engines.  I mean the setting of which search engine is used by default in the location bar (aka omnibar).

**Comment by Gitoffthelawn** [comment]
BTW, we used to have `browser.search.defaultenginename`

**Comment by crssi** [comment]
Do you mean something like
``` js
/* 5000x */ user_pref("browser.urlbar.placeholderName", "DuckDuckGo"); // Set DuckDuckGo as a search provider
```

**Comment by Thorin-Oakenpants** [comment]
> What I mean is not the available search engines. I mean the setting of which search engine is used by default

As I said, it (default search engine) is stored in the `search-metadata.json` file. So no, you can't set it from a pref. There's a whole thread about this somewhere in here, but I can't find it (haven't looked and it's probably a year old, and things change)

**Comment by Gitoffthelawn** [comment]
@crssi wrote: 
> 
> Do you mean something like https://github.com/crssi/Firefox/blob/master/user-overrides.js#L188 ?:
> 
> ```js
> /* 5000x */ user_pref("browser.urlbar.placeholderName", "DuckDuckGo"); // Set DuckDuckGo as a search provider
> ```

Yes, exactly something like that.  It looks like it no longer works though and, as @Thorin-Oakenpants mentioned, it may now only be stored in `search-metadata.json`.  Or do you have a different experience?

**Comment by Gitoffthelawn** [comment]
Oh wait, `search-metadata.json` is deprecated.

**Comment by Thorin-Oakenpants** [comment]
I still have one. My Firefox (65) updated it when I changed my default search engine in my test for you

**Comment by Gitoffthelawn** [comment]
Weird.  I actually preferred when they were using `search-metadata.json`, but to test, I just created a nilla FF66 profile, then changed the default search engine, and no `search-metadata.json` created.  My FF65 profiles don't have it either.

**Comment by Thorin-Oakenpants** [comment]
IDK .. maybe it's because I have no inbuilt search engines, only custom ones? Or it uses that because it exists from earlier?

**Comment by earthlng** [comment]
I think you can set the default search engine with a policy.json file but not through a user.js. Policies apply to all profiles for a certain installation but if that's acceptable, it's probably the easiest solution for you.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/mozilla/policy-templates/search?q=search+engine&unscoped_q=search+engine&type=Issues

**Comment by crssi** [comment]
@Gitoffthelawn 

> Or do you have a different experience?

No. In FF 66 for sure it doesn't work anymore.

**Comment by earthlng** [comment]
I just checked and it turns out that "SearchEngine" is the only policy left that is "enterprise_only" ie not allowed on the release channel. You could use a simple autoconfig but it's very likely that they won't allow disabling the autoconfig sandbox for much longer in release either, unfortunately.

**Comment by Thorin-Oakenpants** [comment]
^ about:policies is a handy resource .. click on #documentation and yup, says it right there - ESR only

**Comment by Gitoffthelawn** [comment]
Just a quick note... I copied my main FF profile to a new folder... byte for byte.  Then I ran FF using the new folder as the profile.  Everything worked identically to my main FF profile... with the sole exception that the search engine used in the urlbar got reset to the evil Google.

**Comment by earthlng** [comment]
Yes it says "ESR only" but the code doesn't match that. The correct wording for what the code actually does, would/should be "non-Release only" ie it's also allowed in beta, dev-edition and nightly. Just FYI for whom it may concern :)
