### ISSUE TITLE
media.gmp-gmpopenh264.autoupdate is deprecated

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#671]
While reviewing the source code of FF 66, I noticed `media.gmp-gmpopenh264.autoupdate` is deprecated.

You may want to update user.js.

**Comment by earthlng** [comment]
No, I'm pretty sure it's not deprecated. They just access it in a generic way ie not by its full name:

https://dxr.mozilla.org/mozilla-central/search?q=KEY_PLUGIN_AUTOUPDATE
https://dxr.mozilla.org/mozilla-central/search?q=GMP_PLUGIN_IDS
https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/GMPInstallManager.jsm#223-232

**Comment by Thorin-Oakenpants** [comment]
It's a hidden pref too, at least on windows - should we add that? @earthlng

**Comment by Gitoffthelawn** [comment]
@earthlng Yes. You are correct.  It is defined here: https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/GMPUtils.jsm#124

I didn't find it at first because they used the replacement string in the middle.

Besides being a genius, how did you know to search for `KEY_PLUGIN_AUTOUPDATE`?

**Comment by earthlng** [comment]
> how did you know to search for `KEY_PLUGIN_AUTOUPDATE`?

I think I started by searching for `autoupdate`, found 380ish results (= a bit too much for my taste) and noticed that it also matched strings like `AutoUpdateViewBatch` so I limited it to "autoupdate end of word" using regex (`regexp:autoupdate\b`) and quickly spotted the line `KEY_PLUGIN_AUTOUPDATE:        "media.{0}.autoupdate",`
