### ISSUE TITLE
security.enterprise_roots.enabled

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#675]
Read: https://www.ghacks.net/2019/03/26/firefox-shield-study-to-import-windows-root-certificates/

Even if I did install an AV, I for one do not want it's certs auto-imported. I have seen enough AV setups for clients and seen how they use dark patterns to trick the end-user into upgrading to trial versions from free versions, nag them to death about BS, re-enable web browsing protection which was explicitly turned off and warning about it disabled (and here at least FF would fall over as a back-stop), and to trick users into turning on extra BS features.

That said, each to their own. Is this worth adding to the user.js?

**Comment by crssi** [comment]
I have
``` js
user_pref("security.enterprise_roots.enabled", true);
```
for years now in my overrides, not because of the problem described by Martin, but because I need it in enterprise environment, to make also internal secure sites working, that has certificates issued by internal CA Authority.

Never had a problem with it.
If you decide to include it in user.js, then there is one line less in my overrides :cat:

**Comment by Thorin-Oakenpants** [comment]
^ I was proposing that it be `false` (which is the current default)

I guess we can forget about it and pick up on it in diffs **if** and when they flip it

**Comment by Atavic** [comment]
Certificates are a big issue both at system level and application level.
I remove some of them, I mean... just look at the list of the CAs of your desktop OS, mobile OS or browser... I have some far-away police CAs, many banks from other continents...

Re: https://github.com/pyllyukko/user.js/issues/133

Old: https://github.com/pyllyukko/user.js/issues/17

...someone changed his mind about CAs: https://github.com/CHEF-KOCH/Windows-10-hardening#root-cas
