### ISSUE TITLE
have fun: test it yourself: fonts

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#678]
A bit of font f^ckery:  https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#fonts

1 down :+1: , 3 to go  :hammer:  .. have fun

Myself: css font fallback
- `browser.display.use_document_fonts` = 0 = 75 fonts
- `browser.display.use_document_fonts`= 1 = 102 fonts
- TB windows = 61 fonts (46 with doc fonts = 0 but don't do that!)
  * ad4ccd607603041d3e89aa8e03e2e203fc184653 [61/878]
  * feel free to share your TB hashes on various platforms

@earthlng why don't you come help me out bro!? you mad? :kiss:

**Comment by Atavic** [comment]
FF 52 ESR

- browser.display.use_document_fonts = 0

  - c06821ad41ad63534637801621b999835806f23e [12/878]

**Comment by yssmcl** [comment]
Firefox 66.0.1 (64-bits) on Arch Linux:
- `browser.display.use_document_fonts = 1`
    - `49275cfcee901f77fb09588af863537ced9592a1 [65/878]`
- `browser.display.use_document_fonts = 0`
    - `53c34d51be41c6f66f2946845c4ace5d8fe41b14 [30/878]`

**Comment by Daystar1998** [comment]
Firefox 66.0.2 (64-bit) on Windows 10
 - `browser.display.use_document_fonts = 1`
      - `4c9b4fae65b9865e1fc71edf803e3a02f84e80f8 [97/878]`
 - `browser.display.use_document_fonts = 0`
      - `26a1e8dac23f730a8b0fa4ba79112610fc819878 [55/878]`

**Comment by Thorin-Oakenpants** [comment]
actually .. i have no idea why I called it css font fallback .. because it has nothing to do with that, ima gonna rename it

Also, I'm going to disable it on droid - it's really slow on droid and all you get is a bunch of notosans (16 of em on my droid5), and if you're on droid you have bigger issues

**Comment by 2glops** [comment]
FF 66.0.2 (64-bit) on Debian
browser.display.use_document_fonts = 0 = [26/878]
82b1df6efb3cc683940543a06b150b5cb1581260
browser.display.use_document_fonts= 1 = 50 fonts
7acfab50665d22bc655e41f19f58fd11e1209fdf [50/878]

TB 8.0.8 Linux (64-bit)
09a4ee037c9082b9b8f0b7ae981c656d517faffa [34/878]

**Comment by Thorin-Oakenpants** [comment]
@2glops I have the same hash with TB on Debian and Mint as yours, which is reassuring and to be expected, as TB ships with bundled fonts (which differ slightly for Windows/Linux/Mac) and limits them to that list. Mozilla won't be doing that for at least a year+, and it may not even happen.

**Comment by Thorin-Oakenpants** [comment]
Interestingly enough, with doc fonts = 1 (default), I got the same number in Chrome as Firefox: 102 fonts: my windows is a 8yr old build and while pretty clean, I used to do a lot of graphics work and have adobe (&MS office) stuff on here, as well as loads and loads of fonts for said graphics work - but I do use NexusFont portable to store them all and load/unload sets on demand

But the hash differed. So I did a compare. Note: you need to UTF-8 (for non-western chars), and they did indeed differ, by two fonts. That's kinda weird
- FF could detect `Marlett`, Chrome couldn't
- Chrome could detect `Calibri Light`, FF couldn't

@Atavic `[12/878]` .. sheesh, what is this? A pristine VM with nothing else installed. What OS? I have a Win7 VM here (not even SP1 on it) and no installed software, just portable FF/TB. I wonder what that returns.

PS: I have played before with `font.system.whitelist` but it's really starts to fubar everything

**Comment by Thorin-Oakenpants** [comment]
Also interesting, that if I disable doc fonts (i.e leave at default 1), and set `font.system.whitelist` to the same value as my Windows TB, they are almost identical - I am only missing 5 noto sans fonts

Here they are, bundled in the Tor Browser
![tb noto sans](https://user-images.githubusercontent.com/16656956/55203728-57ccf300-51c4-11e9-9856-eea83a095846.png)

So... I installed them. You need to restart Firefox for them to  get picked up.
![twins](https://user-images.githubusercontent.com/16656956/55204245-27865400-51c6-11e9-934c-28dee7ba154f.png)

I'm not saying this is the way to go. The above pic is named `twins.png` but that's like calling  Arnold Schwarzenegger and Danny DeVito [twins](https://www.imdb.com/title/tt0096320/). Since almost everyone has a fairly unique set of fonts (there are more tests to add, not sure if they will detect anything new), at least the TB Windows hash has some numbers behind it. And font FP'ing doesn't need to inspect huge amounts of fonts - 1, it's resource intensive (detrimental to keeping users on sites? etc) and 2) see fingerprintjs2 and they use a small set (65 fonts at the time) with an option for a larger extended set to be added - as Peter Hraška's paper (see #668,) explains that there is a balance to be found between efficiency and entropy

It would also mean I need to keep track of any changes to TB's font whitelist. But I think I might actual surf this way for a while

PS: You can't add the pref values to your user.js because it's not UTF-8

**Comment by Thorin-Oakenpants** [comment]
gee, if I allow for cookies and also keep my browser window at 1000x1000, I get the same FP as TB with https://valve.github.io/fingerprintjs2/ - which is immaterial because 1. I ain't allowing cookies by default cuz because in session sanitizing is still lacking (and I block most JS so the attack vector is a lot smaller) and 2. I need the real estate and my inner window for lack of a better option is always 1600x900

Note: fpjs2 doesn't detect that indexeddb is actually fubared on TB due to PB mode
Note: fpjs2 detects 10 fonts (I assume the default list is still 65 fonts)

PS: I also reset my default fonts. I'm kinda liking this. I think it's the best setup right now to mirror TB on your platform. I just didn't realize how easy on Windows it would be

**Comment by Thorin-Oakenpants** [comment]
I had a play around, looking at the defaults in the languages UI for other languages and doing some searches for fonts and strings like `굴림` etc

The whitelist from TB is obviously so characters can shown instead of `tofu`. And if you remove the five noto sans fonts which we clearly don't need, or even have in stock Firefox windows, then the list is 56 items. Sure might be able to remove Arial (which is three items, but that's used by other languages)

Digging around options, here's a basic list, trying not to repeat items, it's not very scientific
```
arabic   - times new roman
armenian/georgian - sylfaen
bangali   - vrinda
chinese   - simsun, Microsoft Yahei
chinese   - mingLiU_HKSCS (monospace)
chinese   - mingLiU (monospace)
cyrillic/greek/hebrew - times new roman, arial and courier new
devanagari - mangal
gujarati  - shruti
gurmukhi  - raavi
japanese  - MS PMincho, Meiryo, MS Gothic
kannada   - tunga
korean    - batang, malgun gothic, gulimche
malayalam - kartika
odia      - kalinga
sinhala   - iskoola pota
tamil     - latha
telugu    - gautami
thai      - tahoma
tibetan   - MS Himalaya
```

and these are AFAICT
```
바탕         = part of batang
굴림 & 굴림체 = part of gulim
ＭＳ ゴシック    = part of MS Gothic
ＭＳ 明朝     = part of MS Mincho
ＭＳ Ｐゴシック  = part of japanese 
```

And by removing *some* stuff I will never need (everyone's needs are different), the best I could do was reduce the results in that test to 28 items. Look, I might not really need chinese, korean or japanese fonts in everyday life - but I do when I want to read that list of fonts! - but it's good for translating, detecting language etc, copy/pasting into you know, font lists, etc. So I left those in. I mean I cut out tibetan, sinhala, what I assume are indian (gujarati, gurnukhi), armenian (sorry armenia peoples) and a few others, but I run the risk of just screwing things up.

But it's not worth it. Long story short, it means characters will break, which is not good. So @Atavic .. I have no idea about your 12 items. Seems like a bad idea, and very FP'able. Then again, I think we're screwed on this one until RFP saves us. TB has it the best, nothing breaks, minimum set, everyone on the same platform looks the same.

Have fun guys :)

**Comment by crssi** [comment]
Computer 1: FF 66.0.2 (64bit), Win 10:
`browser.display.use_document_fonts=0` = `ebb725423a9a9c9fc82b12c8e9ee0050d4e0d340 [49/878]`
`browser.display.use_document_fonts=1` = `aa10d372ddef2856f23fd14449ac0e3dbe0fc243 [87/878]`

Computer 2: FF 66.0.2 (64bit), Win 10:
`browser.display.use_document_fonts=0` = `ebb725423a9a9c9fc82b12c8e9ee0050d4e0d340 [49/878]`
`browser.display.use_document_fonts=1` = `8208f8e620a74304a51424980fdb5447f92b31ba [73/878] `

Computer 3: FF 66.0.2 (64bit), Win 10:
`browser.display.use_document_fonts=0` = `454d3b40a753e255aa5eebc98a1d7028bec83cf9 [48/878]`
`browser.display.use_document_fonts=1` = `ebe0cf6e8d779f14a766182339ff7efa95187135 [69/878]`

All computers have the same profile.

`gfx.downloadable_fonts.woff2.enabled`: `true` or `false` give the same result.

**Comment by StanGets** [comment]
Firefox 66.0.2 (x64) / Windows 7 (x64)

`browser.display.use_document_fonts = 0`
d7bf52997f1558cba6e67a38117888545aa6e90d [96/878]

`browser.display.use_document_fonts = 1`
f3ca4099b343632996d603d51645b4c141484a34 [131/878]

**Comment by GitCurious** [comment]
Firefox 66.0.2 (x64) - Windows 7 (x64)

browser.display.use_document_fonts = 0
42199d7e11ad81d238667839788b079131574d67 [11/878]

browser.display.use_document_fonts = 1
c74dad7bbeaa804ff9d1d059ef49c00fe52c9c14 [24/878]

**Comment by Atavic** [comment]
>what is this?

Win XP.

**Comment by Atavic** [comment]
>what is this?

Win XP.

>Seems like a bad idea

Most probably, I'm just testing. BTW if these hashes do the same job of the font fingerprints I met before, the less recognised number of fonts, the better.

The best combo should be a minimal set of common fonts from main OSes (Win, Debian, Mac) that leave no hints at what OS is actually running.

**Comment by KOLANICH** [comment]
>Win XP.

Without M$ Office 2007+, I guess.

**Comment by Thorin-Oakenpants** [comment]
It's a bit of a resource hog that test. And I'm adding more. So instead I added a `[run tests]` button - you now have to do it manually. Which is quite cool, cuz now you can flip your document font pref and hit the run test button. the font whitelist pref though requires a restart. Note: you can leave the details open when you retest.

I should get the other four tests added in the next week

**Comment by Thorin-Oakenpants** [comment]
Ahh OK, now I understand how you're getting down to the teens

overrides
```
/* font stuff */
  // user_pref("browser.display.use_document_fonts", 0);
     //NOTE: ^^ reduces fonts from 107 to 61
  //user_pref("font.system.whitelist", "");
    //NOTE: ^^ set same as TB for Windows, reduces fonts from 61 to 40
  //user_pref("gfx.downloadable_fonts.enabled", false);
  //user_pref("gfx.downloadable_fonts.fallback_delay", -1);
    //^^ NOTE: ^^ reduces font enumeration from 40 to 13
```

That's just my notes. remember I "installed" those 5 noto sans fonts from TB. So yeah, doc fonts brings it down (and blocks fingerprintjs2 entirely), and using the whitelist for your OS as per TB will help block any weird shit you have, and then the `1403` pref(s) brings it down even further (and I guess will fubar a lot of languages)

**Comment by Thorin-Oakenpants** [comment]
you all know about TZP now, and no point leaving shit open :grinning:
