### ISSUE TITLE
Border between web page and window [solved: 4504 letterboxing]

### ISSUE THREAD

**Issue by Tealk** [ghacksuserjs/ghacks-user.js#679]
I have updated from version 12 December 2018 to 27 March 2019 and now have a margin. See screenshot.
![image](https://user-images.githubusercontent.com/12276250/55216591-73082480-51fd-11e9-9f1a-2adcf6425d8e.png)

**Comment by Thorin-Oakenpants** [comment]
Do you mean you updated Firefox from an older version, or you updated the user.js ? It's not clear.

I don't think there is anything in the user.js that even touches this, but it's definitely something Firefox releases can add/change. In fact, AFAIK, that's a Firefox issue/bug. If you use Activity Stream, you also get a scrollbar if you don't need it (if I toggle off my floating scrollbars I also get one in a section of my speed dial homepage). I also think you get them on youtube in places you don't want them. I've seen a few reddit posts about it. If I find one again, I'll link back to it and any bugzillas if they're mentioned.

The only other thing I can think of, and it's not something the user.js covers (as it's not a privacy etc thing), is some `layout*scrollbar` in about config which I think was added. I'd have to look. Will do so later when I return if no-one else pipes up.

**Comment by Thorin-Oakenpants** [comment]
here's one post: (which i don;t have time to re-read right now)
- https://old.reddit.com/r/firefox/comments/b5rrmd/most_of_the_website_now_have_a_scrollbar_attached/

**Comment by Tealk** [comment]
Oh sorry @Thorin-Oakenpants i mean the user.js and i dont have touch it
Firefox had no update
I only have a scrollbar when I need it.

**Comment by Thorin-Oakenpants** [comment]
Those pictures aren't telling me anything. I can turn off my floating scrollbars and try to replicate, but I need a bit more direction / info.

Can you tell me what the hell I'm looking at in the first pic, and show a bigger section of the screen if you can. If I want to troubleshoot it, I'll need some STR (steps to reproduce) .. like an URL

**Comment by Tealk** [comment]
So I haven't changed anything about Firefox except adding the latest user.js.
I don't know what you want to see on the screenshot.
Here one from Github with scroolbar
![image](https://user-images.githubusercontent.com/12276250/55219045-19efbf00-5204-11e9-85e9-bfe2634e5835.png)
and here's one without
![image](https://user-images.githubusercontent.com/12276250/55219075-3ab81480-5204-11e9-976d-586f391ef22a.png)

**Comment by Thorin-Oakenpants** [comment]
I don't understand. The github scrollbar is there because the page is longer than the window you have. I do not know the URL of the second image

**Comment by Tealk** [comment]
between the scroolbar and the browser border is a distance that should not be there.
The second image should only show that it is not about the error you linked.
It is a local vmware page.

**Comment by Thorin-Oakenpants** [comment]
OK .. now it makes sense I can see the whole picture (I didn't spot it with the larger github one because I got sidetracked/fixated on scrollbars .. which have nothing to do with it. Now that first tiny pic makes sense and I can see what I'm meant to.

So you're on FF67 or higher then. It;s called letterboxing - pref `4504`

add this to your overrides
```
user_pref("privacy.resistFingerprinting.letterboxing", false);
```

but be aware that this is what you are going to have to get used to at some stage if you want to use FF's built in anti-fingerprinting, as it will become enforced and part of the whole deal
