### ISSUE TITLE
crssi's own special little topic :)

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#68]
No issue really.
This doesn't belong here, but don't know how to post otherwise.

I would just like to thank all you guys for your hard work. Especially @Thorin-Oakenpants  and @earthlng.

**Comment by Thorin-Oakenpants** [comment]
Just post in an open issue rather than create a new one - I like to keep things clean and tidy :). BTW, you're welcome crssi. Wait til the masses arrive. Plus we have a way a little way to go yet overall - I have plans.

**Comment by earthlng** [comment]
Thanks @crssi for your issue of appreciation :) You're welcome and I'm glad you like our work here

And `Thank you` too for all your contributions here, we're happy to have you here :)

> Wait til the masses arrive.

LOL, I hate to burst your bubble but the masses are very unlikely to ever arrive here IMO. Most people on ghacks seem to hate Firefox and mozilla now, but I guess we'll have to wait and see ...

**Comment by crssi** [comment]
This was a big issue and needed its own topic. :)

**Comment by Thorin-Oakenpants** [comment]
@earthlng I think you might be surprised. Most people don't hate FF on ghacks (its a small sample of commentators to start with) - its a small group of users who just have to have their dig at every turn. Those who know better don't bother wasting their time. You can see the traffic graph/figures, right? Time will tell, but remember those figures for 5 days DL's when v11 came out. I expect some sort of flow-on, as well as maintaining new contributors, visitors via the 6 weekly articles. Almost there. Gotta finish those wiki pages, clean up the readme to be readable shorter cleaner - and voila .. big article for martin to do, which I wanna draft and run past you - just not sure how to get it to you (gajim is a PITA to set up on Windows)

**Comment by crssi** [comment]
Where are those comments from folks?
Are those seen only for members?

**Comment by Thorin-Oakenpants** [comment]
@crssi A bunch of FF and Mozilla haters commented on www.ghacks.net articles - they still harp on about pre-Australis and the good ole days

**Comment by earthlng** [comment]
You don't have to setup gajim. You said you already have a pidgin portable setup, that should work.
I can go online in gajim now so we can have "first contact" if you want ;)
Or send it to a random throw-away mail address and tell me the address on IM. or pastebin it and send me the link, or if it's possible to send files over IM send me a pdf. lots of ways to get it to me.
