### ISSUE TITLE
have MOAR fun: DomRect

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#681]
https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#domrect

I added a `re-run tests` button. I also added logic to combine the four types of tests into one, if the hashes for the four types were the same (it's just a toggling of showing/hiding table rows). The logic for that is hidden behind the show/hide details click, but also used when re-running the tests and the details are showing (took me a while to work that out).

So what you can do now, is play with settings in CanvasBlocker or your favorite extension (or prefs if and when they come around, or testing random spoofing on every request) without having to load the whole page again. However, the extension needs to be enabled before loading the page. But toggling settings then works sweet as, see below

CB on: Load page, expand details .. oooh, all the same
![DR-Same](https://user-images.githubusercontent.com/16656956/55331628-33526e80-5483-11e9-96dc-eebf83ed5a28.png)

Flip a setting in CB and hit the `re-run tests` button ... oooh ... details expands out, as the hashes are no longer all identical
![DR-Different](https://user-images.githubusercontent.com/16656956/55331688-51b86a00-5483-11e9-9b09-b705c4c849dd.png)

Change the setting back and rerun the test again, and it will compact again.

I also built in a tiny artificial delay so you can visually see all entries being cleared before being populated again - this also helps eliminate any screen jitter otherwise it kinda blinks at you as it blanks and refills.

Have fun.

**Comment by Thorin-Oakenpants** [comment]
Today entry: stardate ehr9q234nndf

So I changed the button style (and made the info text style similar) so that they weren't so bright and shiny, and I put it on the first results line. Oh, and I now have all hashes (or the whole section sometimes like Canvas, else it looks weird) using monospace. After adding the DomRect rerun button, I also built one in for Canvas

Here (see pic) I have disabled RFP, and enabled CB, loaded the page, and I I can change CB canvas settings and hit the rerun to check things. I'm not 100% sure, I guess it depends on settings - but if you reloaded the whole page, all values would change due to random fake values - but the rerun only changes those you toggle on off, because we're not reloading the whole page - @kkapsner, is that right?

![MOAR](https://user-images.githubusercontent.com/16656956/55387547-19ea1900-558e-11e9-8c93-1c37b966cc6f.png)

But wait .. there's MOAR!! Because the font code is slow and while running seems to block other usability (such as drawing on the screen, if you scrolled really fast you could see the painting had stopped - such as clicking on things) - I changed it to a run button. Once you run the tests, the button text changes to rerun. See pic below.

![evenMOAR](https://user-images.githubusercontent.com/16656956/55387634-469e3080-558e-11e9-9444-1c4141b9603c.png)

I will also add re-run buttons where appropriate [1], such as Audio, when I sort out getting the individual values in the details. ATM it is just summary hashes from kkapsner's work.

[1] I can see quite a few places where a rerun button really fits saving full test reloads. Such as running `forget this site` or manual sanitizing tests and my zombie persistent data subsection (when I add it). Or toggling RFP and rerunning the hardware/device section. Or a subsection in canvas for extra canvas detection tests. Or the navigator/UA properties to check spoofing with extensions on each request - yeah, ok, that last one sucks, because I don't support random UA spoofing - and I don't want to go overboard.

**Comment by Thorin-Oakenpants** [comment]
PS:
- Enjoy, and keep checking the site, because I'm tinkering every day.
- Feel free to give me encouragement (I need it - I feel like everyone abandoned me: kkapsner, :cat2: and :bird: were there at the start, but the last two seem to have vanished - maybe Batman finally got them)
- Tell me how to improve something: I haven't built a website or actually used JS since 1999 (true story), it's just that an insane amount of languages (lots of old ones) and old coding skills were usually enough to let me kinda follow things in DXR etc

Anyway, closing this now since you all seem to know about TZP by now. I was hoping I would get a few more people to help because while I can pick JS pretty fucking up quickly due to my background, it's going to take me a long while to become really good at it. As it is, it takes me insane amounts of time to code cool shit, as I learn.

**Comment by kkapsner** [comment]
The rerun may return different results depending on CB settings. For the canvas it's mainly the canvas cache. But also the random number generator plays a role.

**Comment by Thorin-Oakenpants** [comment]
^^ thanks :kiss: I thought I read somewhere, maybe a comment in your code or on your test pages where it said a refresh only changed certain things. But I think I get it. I mean my settings were to fake every request but only those values I unchecked changed.

I'm not worried about it - it's clearly up to the tester to know what their settings/extension is meant to do.
