### ISSUE TITLE
Request Time API down to fractions of seconds

### ISSUE THREAD

**Issue by Atavic** [ghacksuserjs/ghacks-user.js#688]
Long story short - https://normandy.cdn.mozilla.net/api/v1/ has a **"classify-client"** in its framework with this feature:

```
{"request_time":"2019-04-09T19:57:*42.694161Z*"}
```

That's YYYY-MM-DDThh:mm:ss.*sTZD* - Complete date plus hours, minutes, *seconds and a decimal fraction of a second* according to the [W3C](https://www.w3.org/TR/NOTE-datetime).

**Comment by Thorin-Oakenpants** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API

It's used by the **application** AFAICT, not content. And how else do you expect telemetry (normandy in this case) to return precise timing for analysis. We're talking about tiny tiny measurements to improve speed etc.

Any **content** timing attacks are mitigated by RFP

**Comment by Atavic** [comment]
Used for most mozilla services IMHO, it uses HSTS and appears in SiteSecurityServiceState.txt

I looked [here](https://github.com/search?q=classify-client.services.mozilla.com%2Fapi%2F&type=Code)

**Comment by Atavic** [comment]
I'm not saying it is bad per se, I'm just pointing at

**Comment by Thorin-Oakenpants** [comment]
no worries. I want to leave this open, because I'm intrigued if it's usable by content, seeing as it's a standard. I'm not worried about it with RFP, but would like to know more

**Comment by Thorin-Oakenpants** [comment]
https://mdn.github.io/dom-examples/performance-apis/Using_the_Resource_Timing_API.html - well, that demo didn't seem to work

**Comment by Thorin-Oakenpants** [comment]
nilla Ff on the left, RFP=true on the right
![well-look-at-that](https://user-images.githubusercontent.com/16656956/56157186-667e1d00-5fae-11e9-99c0-dc533b9d3755.png)

I was massively overcooked last week. Of course it can be used in content, because a webpage can request new resources and time them from dns lookup etc - and if I had read the MDN fully I would have seen the link to the demo

Not sure why RFP seems to block this rather than round to 100ms. Anyway, there have been plenty of other high res timing implementations in HTML5 (hence why bugzilla get RFP breaks x game, or causes jitter / jank, etc).

I think we can close this - right?

**Comment by Thorin-Oakenpants** [comment]
> I think we can close this - right?

**Comment by Atavic** [comment]
Repo has *dom.enable_resource_timing* and *dom.enable_user_timing* as false.
Maybe add *dom.performance.enable_user_timing_logging* as false, too.

**Comment by Atavic** [comment]
The [High Resolution Time specification](https://www.w3.org/TR/resource-timing-2/) can be used by: User Timing, Resource Timing, Server Timing and Paint Timing APIs.

On the Servo repo I get the following from [performanceobserver.rs](https://github.com/servo/servo/blob/5da10694912fa43b673f74445f4f249eaf46b451/components/script/dom/performanceobserver.rs):

> List of allowed performance entry types.
"mark", // User Timing API
"measure", // User Timing API
"resource", // Resource Timing API
"navigation", // Navigation Timing API
// "frame", //TODO Frame Timing API
// "server", XXX Server Timing API
"paint", // Paint Timing API

**Comment by Thorin-Oakenpants** [comment]
> Repo has _dom.enable_resource_timing_ and _dom.enable_user_timing_ as false.

dom.enable_resource_timing <- is in RFP ALT section which is disabled by default
dom.enable_user_timing <- deprecated in FF55

> Maybe add _dom.performance.enable_user_timing_logging_ as false, too.

logging is not a threat
