### ISSUE TITLE
Block CSP reports in uBlock - will it break any addon?

### ISSUE THREAD

**Issue by ReporterX** [ghacksuserjs/ghacks-user.js#689]
I just want to ask for certain.

If I enable **Block CSP reports** in uBlock, will it break [any of your recommended addons](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions) and Prviacy Badger?

Thank you.

**Comment by Thorin-Oakenpants** [comment]
Not that I know of, but i am not an expert - ask at [r/ublockorigin](https://old.reddit.com/r/uBlockOrigin/new/) . Also see the link provided in uBO's dashboard: https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#block-csp-reports.

AFAICT this is simply blocking outgoing and doesn't modify anything - I for one haven't had an issues with other extensions with this setting - not that I use all the extensions

PS: I have no idea about Privacy Badger, but again, I can't see why this setting would affect it

**Comment by Atavic** [comment]
CSP Reports go to webservers and [don't have any use for your browser](https://www.ghacks.net/2017/10/19/ublock-criticized-for-blocking-csp/).

An abnormal CSP can also be [used for tracking](https://www.ghacks.net/2017/10/19/ublock-criticized-for-blocking-csp/), as it can be sent to 3rd parties.

CSP Reports shouldn't matter any webextension whatsoever, except abnormal cases (which I have no knowledge about).
