### ISSUE TITLE
privacy.clearOnShutdown.sessions

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#69]
Hey... pardon my stupidity, but what exactly is cleared when `privacy.clearOnShutdown.sessions = true`?

**Comment by Thorin-Oakenpants** [comment]
```js
user_pref("privacy.clearOnShutdown.sessions", false); // Active Logins
```

I guess the answer is "Active Logins". This is the wording used in the `Options>Privacy>Clear history when Firefox closes>Settings` and also in the `Clear Recent History` panel (`privacy.cpd.sessions`). 

So what is "Active Logins" (and no, it is not login info/status kept in cookies!)

"Active Logins" have to do with servers that use basic authentication (usually FTP servers that give a pop-up for the user name and password)

https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by crssi** [comment]
OK... thank you @Thorin-Oakenpants. I was guessing this way.
Why would be good not to have forced it to "true"?

**Comment by Thorin-Oakenpants** [comment]
Dunno. Should we have a vote and first to a million wins?

It is in a section marked as [setup] and also mentioned in the forms section, so whatever we decide, no one will die as a result of it. We clear cache, downloads + form + browsing history. Clearing active logins would be good. BA is crap anyway - its over http. It is even widely used anymore?

**Comment by crssi** [comment]
Thank you :)

**Comment by Thorin-Oakenpants** [comment]
Wow .. slow down there missy ... I'm proposing that we flip it to true and also match the same in the cpd

**Comment by crssi** [comment]
Aaaa... must been hit the left button instead of the green one. ;)

**Comment by earthlng** [comment]
> BA is crap anyway - its over http

also works over https. Not crap either - with some brute-force protection it's just fine

> It is even widely used anymore?

It's definitely still used. Widely? idk

> I'm proposing that we flip it to true and also match the same in the cpd

I see no problem with that. People unlikely clear cpd stuff while logged in.

**Comment by Thorin-Oakenpants** [comment]
> also works over https

My bad. Got hung up the description in that wiki article, not the fine print: "HTTPS is, therefore, typically preferred used in conjunction with Basic Authentication"

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/f4f739929b46aba73120325f1a1cf10a11ac641c
