### ISSUE TITLE
Mozilla possibly plans enabling hyperlink ping in future, unknown if 606 will remain

### ISSUE THREAD

**Issue by Solomon1732** [ghacksuserjs/ghacks-user.js#696]
According to a [BleepingComputer ](https://www.bleepingcomputer.com/news/software/mozilla-firefox-to-enable-hyperlink-ping-tracking-by-default/) report Mozilla plans to enable hyperlink ping in the future. One part of Mozilla's response to BleepingComputer that got me slightly worried is:

> When we asked if they felt that users should at least be given the ability to disable the feature if they wish, Mozilla stated that they did not believe it would have any "meaningful improvement" to a user's privacy.
>>"We don’t believe that offering an option to disable this feature alone will have any meaningful improvement in the user privacy, since website can (and often already do) detect the various supported mechanisms for hyperlink auditing in each browser and disabling the more user friendly mechanisms will cause them to fall back to the less user friendly ones, without actually disabling the hyperlink auditing functionality itself."

I don't know if it means that 606 will remain on by default, will be hidden, or will be removed all together. Apparently [Ghacks](https://www.ghacks.net/2019/04/20/mozilla-plans-to-enable-hyperlink-ping-tracking-by-default-in-firefox/) (in their coverage of the same BleepingComputer article) aren't sure of it themselves:

> Firefox users can check browser.send_pings on about:config to configure it. Whether that preference will remain in Firefox once Mozilla enables Ping functionality remains to be seen.

I think it is advised keeping an eye out on the whole issue.

**Comment by Thorin-Oakenpants** [comment]
- If they flip the switch, we have nothing to do, as it's already enforced: future-proofed
- If they remove the pref, then we pick up on it in diffs between releases, and then I'm sure a solution will be found - e.g uBO or uM might add a global pref to block pings or something

Until the pref is officially removed, and that's not even known, then nothing to do

**Comment by Thorin-Oakenpants** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditing

disable hyperlink auditing in uBO already covers this

**Comment by Atavic** [comment]
[Privacy concern with ping attribute](https://github.com/w3c/html/issues/1456#issue-327212516)
