### ISSUE TITLE
revisit 4503

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#698]
As I type crssi pipes up with `4503`: I need to re-evaluate it. 2662 is inactive. The two together allow extensions to function on these domains. But since we don't have 2662 as active, then what does 4503 achieve on it's own? That's the question.

currently
```js
/* 2662: disable webextension restrictions on certain mozilla domains (also see 4503) [FF60+]
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
   // user_pref("extensions.webextensions.restrictedDomains", "");

/* 4503: disable mozAddonManager Web API [FF57+]
 * [NOTE] As a side-effect in FF57-59 this allowed extensions to work on AMO. In FF60+ you also need
 * to sanitize or clear extensions.webextensions.restrictedDomains (see 2662) to keep that side-effect
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true); // [HIDDEN PREF]
```

**Comment by Thorin-Oakenpants** [comment]
clearly we don't make 2662 active as that reduces security (think of extensions being about to fuck with sync accounts etc).

So the question is, what exactly does 4503 do that harms end users. Nothing AFAICT: there is no loss of security, and in fact, it actually, maybe, increases privacy - the thing is, WTF spends that much time on AMO. This is simply mozilla's "special" treatment for itself as not counting as itself as a tracker - but it is one less thing for those of us who want extensions to work everywhere to have to override.

WTF is earthlng to confirm (or correct me)?

**Comment by Thorin-Oakenpants** [comment]
@crssi 

>  and I really do not believe that Mozilla would do FPing on us.

Not `FP'ing`, you mean `analytics` (not tracking: none of that PII etc and selling it). It's about collecting their own metrics etc as any large web platform does. Nothing sinister about that. But it's the GA part (even with their special agreement on using it on AMO).

> When true there is a breakage which is as side effect when disabling FP on AMO site

What do you mean there is breakage? None for me. Can you elaborate?

**Comment by crssi** [comment]
Open for example [uBO AMO](https://addons.mozilla.org/firefox/addon/ublock-origin/)
Pay attention on a [button](https://imgur.com/gallery/lW2UhN0).
Change the value of `4503`, reload AMO page and see the button (if it doesn't work, do it in overrides and restart FF).

Cheers

**Comment by Thorin-Oakenpants** [comment]
Thanks for the info :+1: 

I actually don't even get a `remove` button instead it says `install`. What Mozilla are doing here is tying your local data to the webpage to add a tiny bit more usability - I guess I never noticed that. Users would or should we well aware of their extensions, and they can easily remove them via about:addons.

So I don't consider this an issue, TBH.

**Comment by crssi** [comment]
I do not ether.
But I don't believe that `4503` is really needed for tightening a profile, then why not relax for easier install/de-install WE's.
What ever you decide is OK, or I will keep it in overrides or not.

Cheers <3

**Comment by Thorin-Oakenpants** [comment]
I only want to relax things if they make a difference: so mathml breaks readability, which is rather important. Or if they make no sense. This kinda makes no sense, but is so minor we can just ignore it. The pref itself is only useful when used with 2662, and most of our users hate GA with a passion .. *sigh* ... all this for just AMO

But I get your point.
