### ISSUE TITLE
dom.workers.enabled;false breaks 'Country Flags & IP Whois' add-on

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#70]
moved from [Issue #60](https://github.com/ghacksuserjs/ghacks-user.js/issues/60)

@zymase wrote:
FYI there is (at least) one Firefox add-on which will not perform correctly with `dom.workers.enabled` set to _false_ : **Country Flags & IP Whois**

I've had difficulty finding the culprit when I noticed that _Country Flags & IP Whois_ wasn't displaying the country flag & IP address in the urlbar because switching `dom.workers.enabled` to default = true wouldn't make it before restarting Firefox.

If it is possible, and that's what I was doing, to set `dom.workers.enabled` to true on a per-site basis (_Google Street View_ mainly, here) it leads to a choice setting vs. add-on when an add-on won't run if set to false. I'm keeping the add-on in this case because I really use it quite a lot.

@Thorin-Oakenpants wrote:
> If it is possible, and that's what I was doing, to set dom.workers.enabled to true on a per-site basis

When XUL goes, AFAIK, web extensions will not allow add-ons to change (maybe even to read) preferences that are not their own. Extensions to flip prefs will be obsolete. That said, we have until 57 (and after that the ESR extended life). Also e10s is almost enforced, just to make matters a little tougher.

There are quite a few add-ons that flip prefs with whitelists. Maybe you can hunt one down and all it would need is a little code change - but, IMO, that's not a very elegant solution as it doesn't handle multiple pages on the fly. Probably easier, a simple toggle button extension of which there are hundreds of these, but no idea if any are e10s compliant.

@zymase wrote (and got a :thumbsup: from @Atavic):
If it weren't this _Country Flags & IP Whois_ Firefox add-on which requires `dom.workers.enabled` set to its default _true_ value  to perform I'd include `dom.workers.enabled` to a _Custom Buttons_ (Firefox add-on itself) button called Pref Toggler (http://custombuttons.sourceforge.net/forum/viewtopic.php?f=4&t=381) which allows a quick access & edit to about:config settings chosen by the user. But as I said when it comes to an add-on which requires a default about:config setting to be left unchanged then it's either the add-on or the setting when this add-on runs and performs on each and every Web page.

I'll add that I was surprised that a very add-on depended on `dom.workers.enabled`, when I thought up to now that this setting concerned Web sites only.

@Thorin-Oakenpants wrote:
FWIW: [Flagfox](https://addons.mozilla.org/en-US/firefox/addon/flagfox/) does all this and more, and is e10s. I'm always wary of these sorts of things (yes I know country data is local csvs etc) - you want to be careful what data is being sent to who (and how, is it https) in order to look info up (and is it automated or only when you go to check?).

@zymase wrote (and got a :thumbsup: from @Atavic):
The country flag and server IP is performed automatically, the DB is local (included in the add-on) but the IP Whois is only performed on demand. So there's no automatic external call.

Concerning the IP Whois the one used by the add-on is, IMO, clumsy. I've mentioned this together with an improvement proposition for performing Whois with another site, on the add-on's GitHub page at https://github.com/andy-portmen/country-flags/issues/1

I really like this add-on, runs fine and allows the user to have quick and substantial info about the visited site .... but it needs `dom.workers.enabled` set to _true_ ...

@Atavic wrote:
@zymase Good hints!

**Comment by Thorin-Oakenpants** [comment]
Right, so its established that `dom.workers.enabled` when set to false breaks a particular add-on. Awesome. Nothing we can do about it. Go talk to the developer, but the info is good, and we can use that later. Meanwhile 2301 already contains a warning. We have another dom.*workers thread going and I will be creating a 2300 section revamp in future - so this is closed

**Comment by zymase** [comment]
I mentioned the issue with the add-on as a FYI, not for getting it resolved, remember?

**Comment by earthlng** [comment]
Damn, Thorin need some sticky icky? calm down ;)

**Comment by andy-portmen** [comment]
Regarding "Country Flags & IP Whois" add-on, it does the IP to country conversion in a webworker asynchronously; https://github.com/andy-portmen/country-flags/blob/master/common.js#L49
