### ISSUE TITLE
Default Content Blocking option

### ISSUE THREAD

**Issue by AMihail1** [ghacksuserjs/ghacks-user.js#700]
Is it possible to change this via about:config/user.js? Mines defaulting to custom every time I open FFox.

**Comment by Atavic** [comment]
Are you referring to about:home about:newtab activity-stream and snippets feeds?

They are covered.

**Comment by Thorin-Oakenpants** [comment]
^^ No, AMihail1 is talking about:preferences#privacy "Content Blocking>Custom"

**Comment by Thorin-Oakenpants** [comment]
![default](https://user-images.githubusercontent.com/16656956/56552344-81d2c480-657a-11e9-9d5a-e53b47c03119.png)

As soon as you change your content blocking options (including cookies), then you are no longer "standard". Normally you would do this through the UI, and click on "custom", etc. The user js doesn't change your tracking protection lists or options, but it does change your cookies to block all 3rd party - this then means your about:preferences#privacy shows as "custom" (and you can see lots more things to turn on/off etc)

![custom](https://user-images.githubusercontent.com/16656956/56552312-6b2c6d80-657a-11e9-94d3-a36bfb796a2d.png)

Look, it's not the sexiest UI with a blue warning box inside another blue box, but it's just a settings page, which is displaying exactly what you are **meant** to see

If this is not what you meant, then reopen and clarify

**Comment by Thorin-Oakenpants** [comment]
to be more precise, the user.js pref that changes this, is the cookies>block 3rd party, which is pref `2701`
- user_pref("network.cookie.cookieBehavior", 1); the default is 0

**Comment by Atavic** [comment]
Ah ok, those are the blacklists commented in:

*// user_pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256"); // basic*

**uBo** webextension does it better.

**Comment by Atavic** [comment]
Ah ok, those are the blacklists commented in:

*// user_pref("urlclassifier.trackingTable", "test-track-simple,base-track-digest256"); // basic*

uBo webextension does it better.
