### ISSUE TITLE
0303: app.update.service.enabled

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#708]
```js
/* 0303: disable background update service [WINDOWS]
 * [SETTING] General>Firefox Updates>Use a background service to install updates ***/
user_pref("app.update.service.enabled", false);
```

I think we should just remove this
- Does not come with (or apply to) portable FF
- Does not come in Nightly (installed, AFAICT)
- Is Windows only
- FF installs that use a stub auto-install Mozilla Maintenance Service (no option to uncheck it) and grabbing FF from the website gives you a stub
- If you uninstall the Moz Maintenance Service, the option is now gone from the UI (no idea if it comes back with an update, I doubt it)
- I think they are deprecating this option, or at least hiding it, which is probably immaterial- I an dig out the bugzilla(s) on this if needed

I don't see the point of disabling this, or EVEN having it in the user.js. Either you disable auto-updating in windows via the options (there is no pref for this in windows) or just get your updates. Who cares if it uses Moz Maint. Service or not?

Class, discuss!

PS: this was one of the items in the analysis of overrides

**Comment by Atavic** [comment]
As long as Mozilla deprecates:

```
user_pref("app.update.auto", false);
```

**Comment by Thorin-Oakenpants** [comment]
`app.update.auto` is (now) a non-Windows setting. I'm talking about removing a specific windows setting that doesn't really control anything important (in terms of privacy, security etc)

**Comment by claustromaniac** [comment]
Why was this added to the user.js in the first place? Does anyone even know?

#112 seems to be the earliest discussion about it that GitHub managed to find for me. Back then this repo probably had like 50 stars, 20 watchers, :jeans: still had some hair, and I was not even aware of this repo's existence. I was like.. modding videogames and shit. Anyway, back on topic... it seems back then the reason to keep that active `false` had to do with preventing system addons from updating, or something of the sort (didn't read the whole thing). Does that hold true in this day and age?

**Comment by Thorin-Oakenpants** [comment]
> Does that hold true in this day and age

No idea. System addons have been reduced to around 4 items by default - webcompat, screenshots, formfill - they seem to want to build them into FF main now. (see normandy, followon search etc -> tie in with Activity Stream). There's a bug that with a certain setup, we wouldn't get a critical system addon update pushed - e.g pdfjs (yes, it's a system addon, apparently) - we actually have a issue on it somewhere.

But long story short, I doubt if the background update service being used or not would have any affect. It's not needed on Linux or Mac.

I think the reason this was added in the first place was the thirst by ghacks readers for a "quiet" fox and being in control of all aspects of their browser.

I'm going to remove it

**Comment by Thorin-Oakenpants** [comment]
and the staging pref, 0304

**Comment by Thorin-Oakenpants** [comment]
and 0305: the default is false anyway

**Comment by Thorin-Oakenpants** [comment]
> I can dig out the bugzilla(s) on this if needed

FYI:
- [1343669](https://bugzilla.mozilla.org/show_bug.cgi?id=1343669) meta update ticket
- [1461755](https://bugzilla.mozilla.org/show_bug.cgi?id=1461755) remove option in preferences

read the tickets, there are still changes to be made, but it looks like the UI option will be removed, but the pref will stay., who knows, don;t care :)

**Comment by Thorin-Oakenpants** [comment]
FF71 changes : pref("app.update.staging.enabled", false); // prev: true
