### ISSUE TITLE
gmp, cdm + eme

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#709]
I recently made 1840 inactive. The reasoning being that this is only used in WebRTC, and that's already disabled. It would also just be yet one more thing for users to have to jump through (and they still have to reset 1820)

```
/* 1840: disable the OpenH264 Video Codec by Cisco to "Never Activate" [SETUP-HARDEN]
 * This is the bundled codec used for video chat in WebRTC ***/
   // user_pref("media.gmp-gmpopenh264.enabled", false);
   // user_pref("media.gmp-gmpopenh264.autoupdate", false);
```

Since then, nothing has happened to my profile. No downloads or updates of gmp files (because of 1820). **We could even remove 1840 as dead wood - yes/no?**

---

GMP:
```js
/* 1820: disable all GMP (Gecko Media Plugins) [SETUP-WEB]
 * [1] https://wiki.mozilla.org/GeckoMediaPlugins ***/
user_pref("media.gmp-provider.enabled", false); // default true
user_pref("media.gmp.trial-create.enabled", false); // default true
user_pref("media.gmp-manager.url", "data:text/plain,");
user_pref("media.gmp-manager.url.override", "data:text/plain,"); // [HIDDEN PREF]
user_pref("media.gmp-manager.updateEnabled", false); // disable local fallback [HIDDEN PREF]
```

`media.gmp.trial-create.enabled` can be removed, it is not needed if the master switch is used. The two URL prefs can also go: FYI: Tor browser only set
- user_pref("media.gmp-provider.enabled", false);
- user_pref("media.gmp-manager.updateEnabled", false);

So at a bare minimum, I will remove three prefs as being redundant. The hidden `url override` is a bitch anyway for end users to add to overrides, since it's a hidden pref. I will do a commit shortly

I shall make them all (1820s) inactive and reset in my profile and see what downloads for info's sake
- profile/gmp  <- currently empty
- profile/gmpopenh264 <-- currently does not exist
- profile/gmp-widevinecdm <-- currently does not exist

And then we can discuss making 1820 inactive, what risk it carries. And then we can discuss what to do with cdm and eme

Class, discuss!

**Comment by Thorin-Oakenpants** [comment]
Actually, what I'll do is leave enabled as active, and just see what unblocking just the update does

me
```
user_pref("media.gmp-provider.enabled", false);
   // user_pref("media.gmp-manager.updateEnabled", false); // [HIDDEN PREF]
```

Time will tell. It might also be that as soon as I hit a GMP, it then downloads. Maybe I need a test page or something to trigger it

**Comment by Thorin-Oakenpants** [comment]
Here's what I think I'll do (assuming my knowledge is correct)

- set cdm and eme -> inactive (as they are covered by the gmp master switch)
- leave gmp -> active (just the `.enabled` pref)
   - this then *might* auto download the dlls etc and keep them updated - I will test over the next day
- this reduces it to one item for people to override to get all their video needs
- we only need the one `setup` tag 
- like we did with service workers, the setup tag says to look at the other prefs to harden
- add something to WebRTC about needing to allow gmp

Class, discuss! PS: thanks for all the discussion :)

**Comment by Thorin-Oakenpants** [comment]
PS: am removing redundant / irresponsible widevine prefs

**Comment by Thorin-Oakenpants** [comment]
actually, `media.gmp-widevinecdm.autoupdate` seems to have been removed (FF66), `widevinecdm.autoupdate` returns zero results in DXR

And `media.gmp-widevinecdm.visible` seems to be a toggle to hide annoying messages about FF needs DRM - it doesn't block the video? https://bugzilla.mozilla.org/show_bug.cgi?id=1451762#c9

https://dxr.mozilla.org/mozilla-central/source/dom/media/eme/MediaKeySystemAccess.cpp#124

We should probably work out what it does exactly and add that info to the js, e.g if we make 1825 inactive, but people want it on, they probably don't want to get spammed with FF notices: so we should differentiate those two

**Comment by claustromaniac** [comment]
`media.gmp-widevinecdm.visible` seems to do more than just that. I'm sorry to say reverse engineering that shit is pretty time consuming (and you're not the most patient person I've ever known), but from what I saw it's pretty clear to me that whoever wants cdm will want both that and `enabled` set to `true`. 

The case presented in that bugzilla is presumably that of someone with `enabled` set to `false` but `visible` set to `true`. I'd say lump both together as if they were a single switch (after you do your tests or whatever).

**Comment by Thorin-Oakenpants** [comment]
> but from what I saw it's pretty clear to me that whoever wants cdm will want both that (visible) and enabled set to true

Ahh, visible is default true, so we could probably get rid of that pref. That bugzilla comment seemed a bit daft - his solution was to kill blow up the bridge (kill cdm) rather than employ a troll on it (block annoying messages)

**Comment by Thorin-Oakenpants** [comment]
Not seeing any more gmp file downloads with all the update prefs inactive. Maybe I need to try to play a test file? Failing that, it might be widevine/eme need to be enabled.

**Comment by claustromaniac** [comment]
> his solution was to kill blow up the bridge (kill cdm) rather than employ a troll on it (block annoying messages)

Actually, I was referring to the person that opened that bug. (S)he likely had `media.gmp-widevinecdm.enabled` set to `false` and `visible` set to `true` and was getting annoying messages because of that. Setting `visible` to `false` apparently solves that issue, so I guess if you don't want cdm, it's better to set both prefs to `false`. Looking at the code, `visible` seems to be pretty important though, so if you use cdm, you most likely want both set to `true`. That's what I meant when I said to lump them together as one switch in the user.js. They're already next to each other, but if you leave both in, this might be worth a mention (because if someone disables cdm specifically and doesn't set `visible` to `false`, they may run into issues). You can even link to the bugzilla if you want, but that's probably overkill.

**Comment by Thorin-Oakenpants** [comment]
multitasking leads to great expectations, and we all know what happened to Pip in the end

**Comment by Thorin-Oakenpants** [comment]
current setup
```js
/* 1820: GMP MASTER SWITCH */
user_pref("media.gmp-provider.enabled", false);
   // user_pref("media.gmp-manager.updateEnabled", false); // [HIDDEN PREF]
/* 1825: CDM */
user_pref("media.gmp-widevinecdm.visible", false);
user_pref("media.gmp-widevinecdm.enabled", false);
   // user_pref("media.gmp-widevinecdm.autoupdate", false);
/* 1830: EME */
user_pref("media.eme.enabled", false);
```

test site (at least for Widevine)
- https://shaka-player-demo.appspot.com/

obligatory pic
![videostuff](https://user-images.githubusercontent.com/16656956/56946878-fda0b400-6b1a-11e9-8f48-ba1c8e607a7f.png)

Part1:
- with gmp/cdm/eme as false, the only codec downloaded and updated is the openh264 (webRTC: disabled)

Part2:
- with gmp/cdm/eme as false, try to load some gmp stuff: you can't, so nothing is triggered/downloaded - see pic where Widevine  options are disabled

Part3:
- we need to change something, I will try a few things out and report back

**Comment by Thorin-Oakenpants** [comment]
I thought I would have a look what my nightly did (and as I do with some test setups, I tweak a few things quickly in options, but that's all). I had unchecked [SETTING] General>DRM Content>Play DRM-controlled content -> the eme setting. This too blocked all the widevine tests on that page.

So with just 1830-EME as false, I got a yellow DRM notification, which I clicked to allow DRM (which flipped the 1830 pref) and the yellow message changed to "Nightly is downloading.. blah components", and within about 5 seconds I was good to go. And then all the widevine components were available.

I think I know my order of testing now. And good to see that the DL of components seems to be as quick as fuck

**Comment by Thorin-Oakenpants** [comment]
Part3:
- enable cdm and eme, leave gmp as false (restart)
- as soon as I opened the test page, it auto downloaded the components = good
  * I got a `profile/gmp-widevinecdm` folder with goodies
- widevine options are no longer disabled
- I could play all the widevine test vids

So two things
- 1820 gmp is not a master switch (and what risk does it carry if enabled)
- 1825+1830 are kind of linked (maybe not all cdm uses eme?) but anyway, both are required for netflix as noted by an overrides comment

I will:
- remove the two `.update` prefs. The widevine one does nothing if you have cdm/eme disabled so it just becomes redundant and yet another item to override. Am I am not interested in documenting how to block updates in general

That leaves
- `1820` - what does this actually do?
   * its not a master pref, yes it was still at false in about:config
- `1825` - can we remove the `.visible`  pref?
   * with both true, there's no yellow message
   * will test  with it at false, but cdm/eme enabled (if that creates a message then we'll have to keep it)
- how to default these: active/inactive and tag cleanup

Thanks for all the testing guys, appreciate it

**Comment by Thorin-Oakenpants** [comment]
With `.vis` true and  `.enabled` false, then you get annoying "enable DRM" messages, so yeah, it needs to stay

**Comment by Thorin-Oakenpants** [comment]
AFAICT, all media.gmp-provider.enabled does is hide the information in the plugins panel. I'm not an expert of this gmp / video stuff. Now Tor Browser disables it but they also disable widevine and cdm and openh264 etc, along with all the background update checks etc.

So I will set this as inactive (unless someone tells me otherwise)

![plugins](https://user-images.githubusercontent.com/16656956/56950880-01860380-6b26-11e9-88d1-5dc3b5529c1d.png)

This then allows users, if they want, to set the openh264 plugin to never activate if it makes them feel more secure (it doesn't make them any more secure).

Setting Widevine CDM to "never activate" simply flips `media.gmp-widevinecdm.enabled` - and is identical to [SETTING] General>DRM Content>Play DRM-controlled content

Additionally, it's not blocking information from the end user  and it also allows the user to go into Options for each plugin and change the auto-updating.

**Comment by Thorin-Oakenpants** [comment]
So commit to follow
- `1820`-> inactive
- `1825` & `1830` -> active, but better setup tag/info
