### ISSUE TITLE
plugins: useless prefs

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#714]
The only plugin (outside their own bundled stuff) is Flash. Flash state is deactivated with 1803. Flash is also disabled by RFP. And if you do have flash, who cares if the plugins panel displays it.

So we do not need the following, and we can remove them
```js
/* 1801: set default plugin state (i.e. new plugins on discovery) to never activate
 * 0=disabled, 1=ask to activate, 2=active - you can override individual plugins ***/
user_pref("plugin.default.state", 0);
user_pref("plugin.defaultXpi.state", 0);

/* 1805: disable scanning for plugins [WINDOWS]
 * [1] http://kb.mozillazine.org/Plugin_scanning
 * plid.all = whether to scan the directories specified in the Windows registry for PLIDs.
 * Used to detect RealPlayer, Java, Antivirus etc, but since FF52 only covers Flash ***/
user_pref("plugin.scan.plid.all", false);
```

Class, discuss! I'll be back after Game of Thrones

**Comment by Thorin-Oakenpants** [comment]
FYI: It's a 2 hr episode, so you have a little extra time on your side

**Comment by crssi** [comment]
Just no spoilers, please.

**Comment by Thorin-Oakenpants** [comment]
Winter is coming, and ant-man flies up Thanos' ass .. and then enlarges himself .. that's all I know

**Comment by claustromaniac** [comment]
> Winter is coming, and ant-man flies up Thanos' ass .. and then enlarges himself .. that's all I know

I'm so glad I didn't keep watching GoT...
