### ISSUE TITLE
FYI: some telemetry stats

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#717]
I was just on https://telemetry.mozilla.org/ checking TLS 1 + 1.1 results and as I come across anything interesting I will post more

This one sticks out, especially after some recent criticism about IPv6 being actively disabled. My argument was that is can't do any more harm that leaking your IP, and for those on a VPN, it can only help. I also tried to point out just how little it is actually used. Here's some stats

PS: I am only looking at Nightly 68 (auto dates 2019/03/18 to 2019/04/30)

:small_red_triangle_down:  IPv4/6 stuff

- Sample count: 3.95 billion
- 85.64% successful connections to an ipv4 address
- 7.94% failed connection an ipv4 address
- 4.64% successful connection to an ipv6 address
- 1.78% failed connections to an ipv6 address

I'm not sure how to interpret failed connections but I would guess that have nothing to do with the protocol. So of successful connections **95%** are ipv4

![ipv4-6](https://user-images.githubusercontent.com/16656956/57050977-a9a6e400-6c6e-11e9-94b8-62105b12f9e2.png)

**Comment by claustromaniac** [comment]
> I'm not sure how to interpret failed connections but I would guess that have nothing to do with the protocol.

How would they be relevant then? Since they're being so general about it, I'm more inclined to think they don't discriminate and just lump together all network errors to build those stats.

**Comment by Thorin-Oakenpants** [comment]
It could just be refused connections (adblockers) etc

**Comment by Thorin-Oakenpants** [comment]
Sample Count: 2.59 billion
- 0.53% v1
- 0.01% v2
- 84.38% v3
- 15.08& v4

![ssl](https://user-images.githubusercontent.com/16656956/57051809-ec6abb00-6c72-11e9-9a10-0b3801b8f91d.png)

**Comment by Thorin-Oakenpants** [comment]
OK, closing this. You know how I hate open tickets. This little exercise was brought to you by :jeans: and resulted in two commits: today's number is TWO ... One, ha ha ha ... Two, ha ha ha

**Comment by Atavic** [comment]
IPv6, The future of internet - as advertised - isn't ready yet.

See [here](https://en.wikipedia.org/wiki/IPv6_deployment#Coexistence_with_IPv4)

So few ISPs provide native IPv6 connectivity to their customers, how many have bothered setting up tunnels to IPv6?
Very few.

**Comment by Thorin-Oakenpants** [comment]
https://scotthelme.co.uk/deprecating-tlsv1-0-and-tlsv1-1-with-cloudflare-workers/

TLS 1  0.3% of the top 1M sites (that use HTTPS) .. 1.1 doesn't even register

**Comment by Thorin-Oakenpants** [comment]
FYI: https://hacks.mozilla.org/2019/05/tls-1-0-and-1-1-removal-update/

> As of this week, there are just over 8,000 affected sites from the one million listed by Tranco.

so 0.8% (of sites) then .. seems legit. And looks like everyone will dump it in approx a year. and FF traffic looks like 0.3% of traffic? Obviously the bigger more popular sites have already moved. Anyway, interested read
