### ISSUE TITLE
Whitelisting about:config entries per site

### ISSUE THREAD

**Issue by AMihail1** [ghacksuserjs/ghacks-user.js#718]
Is something like this a possibility?

**Comment by claustromaniac** [comment]
Unfortunately, nope. The closest thing is using multiple profiles.

**Comment by AMihail1** [comment]
Is there a quick and dirty hack to add "open with x profile" to Firefoxs context menu?

**Comment by claustromaniac** [comment]
Not that I know of, but there are [command line parameters](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options) for that. You'd want to use the `-ProfileManager` and/or the `-P "profile_name"` ones.
