### ISSUE TITLE
Is there a notification for addons updates when auto update is disabled?

### ISSUE THREAD

**Issue by GIPeon** [ghacksuserjs/ghacks-user.js#719]
Hey there!

First and foremost thank you deeply for saving my profile addons. If you head up to /r/Firefox there is some really serious SNAFU going on right now about addons getting nuked from orbit. (The most hilarious is this IMHO https://old.reddit.com/r/firefox/comments/bkfpe8/they_need_to_issue_a_statement_about_this_on/emgdi7v/)

All of a sudden all my addons got obliterated in a profile I use only for streaming music like Spotify. No ghacks user settings are active on this profile because lots of this damn sites want to fingerprint every single damn bit of my browser; I made a dedicated profile and didn't care much about particular user.js settings, so the default autoupdate addons setting was active. 

The very cool part is that my main profiles with the autoupdate setting off, weren't affected at all! :tada: 

I saw also that you discussed here #690 about leaving it on by default, but maybe in light of these possible "mishaps" it should be reconsidered.

That said, my question is: is there a notification for addons updates when auto update is disabled?? Because I had to manually check for updates and some dates to 3-4 days ago, not a single notification has been displayed before.

Thank you again guys! :100:  :trophy:

**Comment by GIPeon** [comment]
ups, apparently I've naively misinterpreted the situation, according to the bug filled here https://bugzilla.mozilla.org/show_bug.cgi?id=1548973 is a certificate related issue. So digging a bit I found that I got lucky with `app.update.lastUpdateTime.xpi-signature-verification = 1556856861` so the system checked before this whole thing happened. 

But soon ... the ticking clock of doom ... will be upon me...  :clock12:

**Comment by claustromaniac** [comment]
Ouch. Thanks for letting us know. I hope Mozilla gets this sorted out quickly. 

As a temporary measure you can try the following to avoid getting affected:

1. backup your profile
2. download [nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly) or [developer edition](https://www.mozilla.org/en-US/firefox/developer/) & install it (or grab the portable version from portableapps.com)
3. run nightly or developer edition with the `-ProfileManager` switch or go to `about:profiles` and load your profile.
4. go to `about:config` and set `xpinstall.signatures.required` to `false`

Apparently, I haven't been affected because I use dev edition on a daily basis (so I can use custom unsigned addons).

**Comment by claustromaniac** [comment]
Uh... I kinda forgot to reply the actual question...

> is there a notification for addons updates when auto update is disabled??

Nope. :sweat_smile:

**Comment by Thorin-Oakenpants** [comment]
https://trac.torproject.org/projects/tor/ticket/30388 - but that pref doesn't apply to ESR

**Comment by Thorin-Oakenpants** [comment]
I just manually did an extentions update check, and I'm sweet AF. Am on 66 stable, and have not applied `xpinstall.signatures.required` because it won't do anything for me.

**Comment by GIPeon** [comment]
> > is there a notification for addons updates when auto update is disabled??
> 
> Nope. :sweat_smile:

That's quite inconvenient. Time for a ridiculous addon "Mind the check". :rofl: 

Anyway yea soon as I realized something was utterly wrong I backed up my profile, after a while it inevitably borked like the rest. Interesting though I replaced the borked folder with the backup and as of now looks like working, I set to false the signature check but I think I'm on stable as well

> I just manually did an extentions update check, and I'm sweet AF. Am on 66 stable, and have not applied `xpinstall.signatures.required` because it won't do anything for me.

So it actually worked for you?

**Comment by GIPeon** [comment]
Anyway can't help to imagine this as the current situation at Moz Dev HQ:

"WHO THE HELL WAS SUPPOSED TO CHECK THE DAMN CERTIFICATE!?!?!!?"

![dunno fire snake mgs](https://user-images.githubusercontent.com/34616429/57174646-a6a82100-6e31-11e9-889e-914eff0d86c9.gif)

**Comment by Thorin-Oakenpants** [comment]
Lets not get sidetracked.

The issue of the expired cert = everything is working as intended e.g. if cert was compromised or something. But it does highlight that there is a single point of failure. It should not take them long to update the cert, and they will no doubt at the fallout and re-visit things, look at countermeasures, checks etc. Many platforms, gmail, youtube, FB, etc have all had single points of failure. FFS, my chromcast wouldn't work for a day late last year. Also, even if they did allow the pref to be used in stable, it would have default disabled (and 99% of users wouldn't know what to do).

The issue of extension update checks is a completely different thing. It's just the trigger that highlights the bigger problem. Again, it would be default checking enabled, default updating enabled = 99% of users need this. If you disabled those checks, then it is UP to you to keep up to date and secure. It's not up to Firefox to remind you

YES, there is an update info. But it is on the addons page. Or you can manually check. I for one have auto-check (and install) for extensions off, so I can easily see what needs updating, read the release notes etc: so I can keep up to date somewhat with any changes that may affect us.

PS: don't post shitty memes here :) If I wanted that sort of carry on, I'd go to geocities in a time capsule

**Comment by Thorin-Oakenpants** [comment]
> So it actually worked for you?

- I have auto-check and auto-install as off
- I did a manual auto-check - about:addons > cog wheel> check for updates
- Note: all my extensions are actually up to date

I do not know at what point the event is triggered - surely it needs the cert to connect and compare versions, and that is when it falls over. My time zone is well ahead of the USA, and even lots ahead of Europe - I've been asleep the last 10 hrs as it happens, but I did not get hit by this at all - obviously some timing as to my timezone, the cert expiration date, and my FF doesn't auto-check extensions (but for those who do, the timing of that matters as well). That said, the first reports from this, 5 or 6 hours ago I guess = midnight somewhere, and that will work it's way around the globe in 24 hrs. 

So I missed the window, but update checks were off, and while I slept, my FF was closed anyway. I am thinking that by now, the cert is fixed.Because if anything, I would be one of the first affected timezone wise, and can't reproduce.

**Comment by bitpixl** [comment]
It's still hapenning on my system while I'm typing this. I read that a possible quick fix is setting the pc date one day back (so Mozilla can fix it today), testing this atm.

**Comment by GIPeon** [comment]
> PS: don't post shitty memes here :) If I wanted that sort of carry on, I'd go to geocities in a time capsule

Aw that's too bad but totally understandable, better not crap on the the track list! I didn't mean to trip on house rules.
  
> I do not know at what point the event is triggered - surely it needs the cert to connect and compare versions, and that is when it falls over. My time zone is well ahead of the USA, and even lots ahead of Europe - I've been asleep the last 10 hrs as it happens, but I did not get hit by this at all - obviously some timing as to my timezone, the cert expiration date, and my FF doesn't auto-check extensions (but for those who do, the timing of that matters as well). That said, the first reports from this, 5 or 6 hours ago I guess = midnight somewhere, and that will work it's way around the globe in 24 hrs.
> 
> So I missed the window, but update checks were off, and while I slept, my FF was closed anyway. I am thinking that by now, the cert is fixed.Because if anything, I would be one of the first affected timezone wise, and can't reproduce.

Interesting, lucky you! I have exact same setting and did exact same things few times, at start all fine, later everything got disabled. I think it has something to do with `app.update.lastUpdateTime.xpi-signature-verification` and the rest. 

Yea this is not the end of the world, still it's quite worrisome that out of the blue something up the chain can cripple everything like this.

Anyway I guess this can be safely close as my question got answered already.

Thank you!

**Comment by Thorin-Oakenpants** [comment]
quote of the year (from some forum) ... :grinning: 

> Look, it’s not all bad. Without all my extensions re-captcha solving is a little bit improved :-)

**Comment by Thorin-Oakenpants** [comment]
PS: It did finally hit me, about an hour ago. I've always have a backup of my entire portable FF which is always less than 24 hrs old. I have simply nuked my live FF and am using a portable dev with a copy of my profile. When they release a 66.0.4, then I'll move back to stable. Shouldn't be more than a day or two

**Comment by claustromaniac** [comment]
> but hey letterboxing is fun

Except that Firefox still never launches maximized regardless of how it is when you close it. I fixed that with a tiny extension of my own (dev edition :heart:)

**Comment by Thorin-Oakenpants** [comment]
each to their own - I detest maximized apps. I always have a dozen apps open, and I like to be able to select em, even though I'm dual screen and fucking huge res

But yeah, the letterbox is independent, not tied to RFP yet, but it will be, The question is, will they keep the sizing for new windows so many users start in a small FP bucket, or do away with it? I hop its the former

**Comment by Thorin-Oakenpants** [comment]
PS: I'm back using stable, I just changed my last update stamp to buy me another 24 hrs. It'd be nice if I could import that new cert

**Comment by kabo** [comment]
The fix from firefox seems to be to enable studies.
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

I had to enable the checkbox to be able to tick it, we'll see if it works...
