### ISSUE TITLE
Change the recommended addon in 2030: disable auto-play of HTML5 media

### ISSUE THREAD

**Issue by jeriko5** [ghacksuserjs/ghacks-user.js#72]
Please change the recommended addon in **2030: disable auto-play of HTML5 media** to:

https://addons.mozilla.org/en-US/firefox/addon/disable-autoplay/

Works much better and more flexible in the settings.

**Comment by Thorin-Oakenpants** [comment]
They both seem to have issues.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/cd0d2de04ce6cad54a875d79678a75d3b7cbc60b
