### ISSUE TITLE
[FYI, 1551592]: RFP causes blur in pdf.js

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#725]
https://bugzilla.mozilla.org/show_bug.cgi?id=1551592

**Comment by ArchangeGabriel** [comment]
Not new, duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1428331.

**Comment by KOLANICH** [comment]
Thank you for the info. IMHO not quite a duplicate - it is easier to solve this issue for pdf.js only (I mean browser component, not a library) than to every website.

**Comment by Thorin-Oakenpants** [comment]
don't forget
- https://bugzilla.mozilla.org/show_bug.cgi?id=1533787
- https://bugzilla.mozilla.org/show_bug.cgi?id=1532859

**Comment by Thorin-Oakenpants** [comment]
its a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1537955
