### ISSUE TITLE
Reddit Enhancement Suite Addon [solved: layout.css.font-loading-api.enabled]

### ISSUE THREAD

**Issue by Entoji** [ghacksuserjs/ghacks-user.js#726]
I can't open RES options when i use ghacks user.js, try it at new fresh profiles and it works fine

**Comment by Thorin-Oakenpants** [comment]
Are you talking about `about:addons > RES > Options` or something?

Toggle off privacy.resistFingerprinting`, reopen the addons page, and try again

**Comment by Entoji** [comment]
Yes, i toggle off privacy.resistFingerprinting and the issue is still happen, i create new profiles and toggle on privacy.resistFingerprinting and open RES options and it works, seems like the privacy.resistFingerprinting is not the problem

**Comment by Thorin-Oakenpants** [comment]
it is the pref `layout.css.font-loading-api.enabled`

Step 1: always look in the console for error messages

**Comment by Thorin-Oakenpants** [comment]
I've added a note to #391 , and this item is one of the last few for me to re-assess in #605 - where it will be either made inactive by default, or given a setup tag for troubleshooting

Meantime, you can just toggle the pref when you change your settings and then flip it back (or override it permanently: up to you).
