### ISSUE TITLE
extensions.enabledScopes breaks default (incl. dark) themes starting FF68 #16

### ISSUE THREAD

**Issue by brainscar** [ghacksuserjs/ghacks-user.js#729]
Including default dark theme.

https://github.com/librevixen/LibreVixen/pull/16

**Comment by brainscar** [comment]
To be clear, you would need to run the current beta version FF68.

**Comment by Thorin-Oakenpants** [comment]
or 69...

**Comment by claustromaniac** [comment]
[bug 1553779](https://bugzilla.mozilla.org/show_bug.cgi?id=1553779)

**Comment by claustromaniac** [comment]
^ [Resolved invalid. ](https://bugzilla.mozilla.org/show_bug.cgi?id=1553779#c2) Interesting... I wonder if system addons are affected by this change too. I'll try to remember to test that later.

**Comment by Thorin-Oakenpants** [comment]
It doesn't happen with `5` = `1` (SCOPE_PROFILE) + `4` (SCOPE_APPLICATION)

I don't see a problem with allowing the app scope. Whatever they changed in 68, I guess it's not considered a regression, or it could be planned, IDK - or this is such a minor, hidden pref with probably 0.0001% of users that MK just closed it down. I slightly better explanation would have been nice.

**Comment by claustromaniac** [comment]
> I don't see a problem with allowing the app scope. 

Yeah, actually, including this pref at all made way more sense before FF57. With web extensions and especially now that Mozilla is not even allowing obfuscated code, this should be a lot less important (at least for users of stable).

**Comment by Thorin-Oakenpants** [comment]
... aaaaaaaand Tor Project are realizing the same thing for ESR68 ... https://trac.torproject.org/projects/tor/ticket/30845
