### ISSUE TITLE
browser.privatebrowsing.autostart: means no "normal" mode right?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#73]
If you start FF in "normal" mode, any new private windows will display a badge/icon in the top right (a mask image). (Side note: themes do not load either)

If you start FF in PB mode, there is no PB mode icon shown anywhere. If you then open a new "normal" window, there is no difference to that visually from the PB mode window (I have never started in PB mode so I would like to clarify this).

I have tested this with multiple vanilla FF52s. To me, this either a bit of a failure and/or ambiguous. @fmarier 

==
below are three concurrent profiles (vanilla FF52), all with `Options>Privacy>History>Firefox will use custom settings`, starting in "normal" mode (i.e "always use PB mode" is unchecked), with spawned PB windows (just reusing the image from the wiki to show the PB mode badge and loss of theme)

![](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/385aeaa54e082ccba39d5363372fa99db7577331/wikipiki/concurrent02.png)

And here is a `browser.privatebrowsing.autostart`->true. If you spawn a "new window" or a "new private window", they are indistinguishable

![untitled-2](https://cloud.githubusercontent.com/assets/16656956/24390314/a92acf3a-13e4-11e7-88e2-bbdc5c5efd01.png)

==
So am I missing something here?
- The wording in options is "*ALWAYS* use PB mode", which at face value means that if you start in PB you can only spawn PB mode windows - regardless of the command (new window or new private window).
- ^^ Is this correct? @fmarier 
- If this is true (start PB mode = ONLY PB mode windows), then why even allow the command "new window". This is misleading. It should be disabled IMO or (to keep the ctrl-n which people use) the icon changed to the same as "new private window" - whatever, also needs to cover context menus/menus/hamburger buttons/key-combos?. It needs to be clear.
- Also, why is the PB mode badge missing. This should, IMO, be enforced. See [this](https://support.mozilla.org/t5/Protect-your-privacy/Private-Browsing-Use-Firefox-without-saving-history/ta-p/4473) from mozilla support: "Private Browsing windows have a purple mask at the top", but also "When Firefox is set to Never remember history you won't see a purple mask at the top of each window, even though you are effectively in Private Browsing mode". Who dreamed that up?
- While people should be responsible for their own tweaks etc, what if an addon or script changed the start mode back to normal. An end-user wouldn't pick up on it.

 I do not start in PB mode myself (never have until now), but read/assumed that you could spawn a "normal" window (because the menu item/key-combo/hamburger buttons/context menus are all there) - indeed I have suggested this to others to test if the cause of an issue was PB mode (recently it was containers not working, then SDC addons not working - and both times the reply was, yes, that's it - not 100% sure if that means they followed my advice exactly - I'm guessing not)

So which is it: PB start mode->new window-> is this a normal window or a private window?

**Comment by Thorin-Oakenpants** [comment]
I'll assume the PB mode icon can only be 100% enforced in default themes - and this is why "always use PB mode" doesn't show it so people can enjoy themes, and why normal mode's "new private window" ignores themes.

Maybe this will change with XUL deprecation.

**Comment by earthlng** [comment]
> If you start FF in PB mode, there is no PB mode icon shown anywhere. If you then open a new "normal" window, there is no difference to that visually from the PB mode window (I have never started in PB mode so I would like to clarify this).

Because all windows are private windows it doesn't make sense to display an icon only in "new PB window". It would be confusing if it did.
Idk why themes are not available in PB windows when that mode is off. Maybe to make the PB windows visually different additionally to the PB mask icon.

**Comment by Thorin-Oakenpants** [comment]
> Because all windows are private windows

I get that (now) because of the wording in options and behavior of UI - but it is NOT obvious. First time I've bothered to start in PB mode and it surprised me. File>New Window is misleading. The purple PB mode mask should be should for ANY PB window regardless of start settings IMO. But now it's cleared up and we have a patch and then at least it's covered.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/commit/5397d2a39a7a013c58e59eeb2296f42c5686ab30
