### ISSUE TITLE
reminder: language/locale

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#730]
from the discussion in #674 

I will need to do some [more] tests, and I already scoped out Tor Browser different language bundles when adding the DTD locale leak for TZP.  It's all a bit hazy right now, but I believe I can pinpoint the right prefs (assuming no extra patches were made in TB) for non-English users to flip without losing entropy (or at least matching TB).

RFP doesn't enforce en-US, and maybe we shouldn't either: it just fucks with people's downloaded bundles/packages - and those who download en-US for example are already fine.

There's at least three or four parts to this: requesting a language from a site in the header (which from memory TB is always en-US), the UI language (which is pref `0205` which I made inactive), the languages themselves (settings, choose languages= web site languages), and locale prefs. It's all a bit messy. And the language UI settings are changing to make matters even messier. Fun times.

Anyway, this is just a reminder to myself to follow up on that. Either:
- add info in the section header on what to flip
- or make [some] settings inactive

I just need to find time to do a butt load of testing. And yes, a butt load is 126 gallons. Look it up. Stop laughing @crssi :grinning:  I might even put this off for a week and drink a butt load of beer.

**Comment by Thorin-Oakenpants** [comment]
FYI:

A `butt` is 108 imperial gallons. It is also half a `tun` which is 216 gallons. A third of a tun, 72 gallons, is a `puncheon`, and a third of that is a `tierce`. Half of a butt, 54 gallons, is called a `hogshead`. A boring old `barrel` is just 36 gallons, and a `kilderkin` is 18 gallons. The smallest unit is nine gallons, and it’s called a `firkin`. You can also call it a `rundlet`, but I firkin like to call it a **firkin**, true story.

An "Imperial gallon" is approx 1.2 "American gallons" - hence why I said a butt load is 126 gallons .. in case anyone wanted to pick a fight with me :)

**Comment by Thorin-Oakenpants** [comment]
for my info: https://trac.torproject.org/projects/tor/ticket/30605

**Comment by crssi** [comment]
Thanks for explanation. I, for sure, would not know what a butt load is (or the origin of saying).
You really know a butt load of stuff, hat down.

love you, cheers

**Comment by Thorin-Oakenpants** [comment]
FYI:

Here is TB7.5 `fr` (french), the header also says english
![7 5](https://user-images.githubusercontent.com/16656956/58754988-3e993900-84ca-11e9-9a32-d900ed7757e0.png)

Starting with 8.0 (pictured below), I think they decided to stop making everyone use en-US for headers and web sites: e.g currency, date-pickers etc, and reveal it all. The header matches the languages.
![8 0](https://user-images.githubusercontent.com/16656956/58755003-92a41d80-84ca-11e9-9d94-66e0660013c8.png)

And here is 9.0a1 `fa` (Farsi)
![9 0a1](https://user-images.githubusercontent.com/16656956/58755012-a8b1de00-84ca-11e9-898a-fa7a1d42f1d2.png)

**Comment by Thorin-Oakenpants** [comment]
^^ Now this is all from TB which is based on ESR60. I will check FF68 later. But here's what I have found

TB use these (example french)
- `intl.locale.requested` = `fr` = GOOD, this is the menus/UI/notifications lang = not web content.
   * we have this inactive in the user.js now
- `intl.regional_prefs.use_os_locales` = `false` = GOOD, use APP locale over OS locale

TB do NOT use these
- `javascript.use_us_english_locale` = not used / hidden pref = `true` means enforce US English locale regardless of the system locale
  - ^^ this fixes (most of) the date/times: intl.DateTimeFormat formatToParts still leaks but I think that was patched after ESR60
  - it does not fix language(s) or locales
- `intl.accept_languages` = `fr, fr-fr, en-us, en` = not sure: preferred lang for displaying web pages
  - header: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3 | fr
change to: user_pref("intl.accept_languages", "en-US, en");
  - header: en-US,en;q=0.5 | en-US
  - also fixes formatToParts and all locales etc

Yet to check FF68, but at this stage it seems as if one pref is used to control all language locales, i.e `intl.accept_languages`, but that if you're using en-US, you should also use `javascript.use_us_english_locale`. So two prefs at most to flip things. And I guess TB rate usability here and they believe that the language buckets will be enough to keep users anonymized.

**Comment by Thorin-Oakenpants** [comment]
Note to self
- test effect after a restart (e.g why did Intl.Date* not change).
- test language build e.g `fr` made to look like `de`

**Comment by Thorin-Oakenpants** [comment]
OK, forget all that: I've come across an anomaly: I was testing the TB language packs using my local `file:///` copy of TZP: seems that returns the "leaks" I saw, UNTIL i go online and visit a web page. Weird AF man. I blame the kitten.

**Comment by Thorin-Oakenpants** [comment]
not really interested in this anymore - maybe someone else can look into it if they want to
