### ISSUE TITLE
css font loading API [1406]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#731]
as part of #605

Ref : https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API

I don't think this does anything for font FP'ing, but I could be wrong. I've written a simple test that detects if this API is enabled/disabled. FWIW, Tor Browser (who have a better handle on font control via the whitelist pref) do not change this from default true in any of the three security levels.

Regardless of the pref `layout.css.font-loading-api.enabled`, this does not affect any of the following font FP tests
- Arthur Edelstein's enumerating fonts [here](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#fonts)
- fpjs2 [here](https://valve.github.io/fingerprintjs2/)
- neither test at browserleaks [here](https://browserleaks.com/fonts)

Because obviously none of them are using the API - doh!

I can't see how this API can be used for FP'ing fonts - allowing a downloadable(?) font (FontFaceSource) has nothing to with your device/browsers FP. I'm just not seeing any attack vector here.

Also, struggling to find any decent examples of this API

**Comment by claustromaniac** [comment]
> Because obviously none of them are using the API - doh!

They are though. If I understand correctly, when you use `@font-face`, technically, you're using the API. 

The only difference I noticed in my 5-minute test is that `document.fonts` is defined when `layout.css.font-loading-api.enabled = true` (and `undefined` when `false`), but for some reason the promise never seems to resolve to anything useful.

> FontFaceSource
>     A mixin providing all of the fonts used in font-related operations, unless defined otherwise. It defines the FontFaceSources.fonts property available to Document and WorkerGlobalScope.

I'm sorry to say I'm not sure how this API works (yet, becauz, you know, I'm no web dev, what I know I just know because I fiddle a lot, and I don't find fonts particularly interesting), but here is something for you, because I know you're an avid reader https://www.w3.org/TR/css-font-loading-3/

**Comment by Thorin-Oakenpants** [comment]
Hah .. I should upload my code. Both work. I forget which way round, but one you can rerun, the other you need a full refresh (when testing the pref flipping).

```js
	/*** layout.css.font-loading-api.enabled */
	//if(!("FontFace" in window)) {dom.fontCSS="disabled"} else {dom.fontCSS="enabled"};
	try {
		var fontCSS = new FontFaceSetLoadEvent('serif'); dom.fontCSS="enabled";
	} catch(e) {dom.fontCSS="disabled";};
```

But I need to learn more about this. AFAICT the font-loading API just lets you load fonts and check their status and stuff. And that's a `JS `thing. Whereas @font-face is a `CSS` thing. Capisce? But I'm no expert. That's just my take on it

**Comment by claustromaniac** [comment]
My take on it: it's a web API. There are JS and CSS aspects to it. But then again, I didn't read the full spec (linked above), and I don't have time for that ATM.

**Comment by claustromaniac** [comment]
https://drafts.csswg.org/css-font-loading/#priv-sec

>  Privacy & Security Considerations
> 
> The FontFaceSet object leaks information about the user’s installed fonts, but in the exact same way as the existing @font-face rule; no new information is leaked, or in any appreciable easier manner.
> 
> This specification introduces no new security considerations.

**Comment by Thorin-Oakenpants** [comment]
^^ IDK, I'm not a flerkin like you (that's a captain marvel reference, not an insult)

I haven't delved into this font stuff much, but I was also thinking of
- `document.fonts.check("12px fontname")`

You don't even need to try and load anything, just cycle thru a list. I wonder if that would reveal anything more than my current 14fonts - since request control blocks the fallback.ttf, and this wouldn't invoke that. So it may be that blocking css font-loading api may close a FP hole?

Also, while you;re at it, I also need (for the moment), css font loading for my WOFF2 test

```js
	var supportsWoff2 = (function(){
		if(!("FontFace" in window)) {
			return false;
		}
		var f = new FontFace('t', 'url( "data:font/woff2;base64,d09GMgABAAAAAADwAAoAAAAAAiQAAACoAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmAALAogOAE2AiQDBgsGAAQgBSAHIBuDAciO1EZ3I/mL5/+5/rfPnTt9/9Qa8H4cUUZxaRbh36LiKJoVh61XGzw6ufkpoeZBW4KphwFYIJGHB4LAY4hby++gW+6N1EN94I49v86yCpUdYgqeZrOWN34CMQg2tAmthdli0eePIwAKNIIRS4AGZFzdX9lbBUAQlm//f262/61o8PlYO/D1/X4FrWFFgdCQD9DpGJSxmFyjOAGUU4P0qigcNb82GAAA" ) format( "woff2" )', {});
		f.load()['catch'](function() {});
		return f.status=='loading' || f.status=='loaded';
	})();
	if (supportsWoff2 == true) {dom.fontWoff2="enabled"} else {dom.fontWoff2="disabled"};
```

**Comment by Thorin-Oakenpants** [comment]
^^ Otherwise instead of returning false for WOFF2, I can then test loading an actual WOFF2 font. Trying to get myself a tiny sized one with just a single character in it

**Comment by claustromaniac** [comment]
According to the W3C this API (as described in the spec) brings no new privacy/security implications of its own (see my previous comment). Don't know about Firefox's implementation. It's still experimental stuff so it's something worth keeping track of, I guess.

`document.fonts.check('12px fontname')` returns `true` no matter what `fontname` I use (even '12px fuck' works, and I can assure you I don't have a `fuck` font. It throws a syntax error if I don't use letters though.

As for your woff2 test, I suspect that can be simplified, lemme try a few things...

BTW your first snippet can be simplified too... 
```js
dom.fontCSS = !!document.fonts
```

**Comment by Thorin-Oakenpants** [comment]
Cool. BTW I went to http://fontello.com/ selected one icon, the font-awesome check mark on the second line, and then clicked download webfont (top right). This is what I'm after. I now have tiny .eot, svg, ttf, woff and woff2 files

**Comment by Thorin-Oakenpants** [comment]
> Have you had any issues with that? [woff2]

Haven't really tried. As I said, it's relying on the css loading api, so I need to fall back to something else

**Comment by claustromaniac** [comment]
Shall we comment out/remove this in the meantime? 

My argument: we **know** `layout.css.font-loading-api.enabled = false` **raises** entropy (because it can be detected), and as far as the latest W3C draft goes, leaving it at default (`true`) does not carry any new risks. It can be argued that since the implementation is experimental, it *may* introduce vulnerabilities, but...
1. There is no evidence of this so far (that we know of).
2. This is not a security feature. I reckon no-one would expect this to open up any significant holes, even in a worst-case scenario. It's not HTTP/2 we're talking about, its fonts FFS.

My two cents.

**Comment by Thorin-Oakenpants** [comment]
I think I'll leave everything as status quo, for now. I want to finish building my tests and get a better overall picture on fonts in general.

PS: in a new html
```js
	// default proportional font
	var dfPF = window.getComputedStyle(document.body,null).getPropertyValue("font-family");
	console.log ( "default proportional font: "+ dfPF );
	// default serif/sans-serif proportional font size
	dfPF = window.getComputedStyle(document.body,null).getPropertyValue("font-size");
	console.log ( "default serif/sans-serif font size: "+ dfPF );
	// default monospace font size
	var dfItem = document.getElementById("element with font-family monospace");
	dfPF = getComputedStyle(dfItem).getPropertyValue("font-size");
	console.log ( "default monospace font size: "+ dfPF );
```

These are the settings in General>Language and Appearance>Advanced. I'm also positive that I can detect the font-family of the three default fonts (serif, sans-serif, monospace) by comparing them to the output from enumerate fonts.

**Comment by Thorin-Oakenpants** [comment]
I'm with :cat2: on this one. The API, if blocked, doesn't really stop anything FP'ing wise - you can already tell if a font is loaded by other means. And it does nothing to stop fonts (@font-face ). Correct me if I'm wrong.

**BUT**, at the same time I'm going to make `1401` active again: that's the document fonts pref. My reasoning for this is
- it actually blocks `fpjs2` font enumeration, and that is a popular FP script, e.g used by reddit as a 1st party script, and the method is quick and performant and used widely
- I believe a zero fonts FP is better than a likely unique font FP

There's no real data on this but it doesn't take much to alter your OS fonts: no idea about Macs, but on Windows, even TB's font list varies on different OS installs (a Win7 Ultimate vs a Win10 clean installs no other software, etc), and they're locking it down with a whitelist. Imagine what happens when you install MS Office, or MS SQL, or Adobe products.

I would expect Linux distros to be widely different as well. I'm not Linux knowledgeable, but surely packages can add fonts to the system?
