### ISSUE TITLE
[NSFW] a media streaming site, many buttons unpushable

### ISSUE THREAD

**Issue by sadfacensfw** [ghacksuserjs/ghacks-user.js#734]
Even with adblocking disabled.
fresh profile
user.js latest
no changes
repeatable problems

PornHub.com

can signup, email verify, use.
later cannot push yellow login button.  Can login with chromium

once logged in after email verification initially cannot click any preferences buttons

https://www.pornhub.com/user/prefs

CAN click yellow "finish editing" button.

https://www.pornhub.com/user/edit

cannot click "upload photo" button.

https://www.pornhub.com/chat/index

cannot click "new message" button

**Comment by Thorin-Oakenpants** [comment]
Use a dedicated browser or profile. Otherwise, try [troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting)

**Comment by Thorin-Oakenpants** [comment]
FYI: [1581492](https://bugzilla.mozilla.org/show_bug.cgi?id=1581492) [resistFingerprinting] Performance API spoofing prevents site from loading login scripts

> STR:
> * Set privacy.resistFingerprinting.enabled = true.
> * Visit <NSFW> https://pornhub.com/login </NSFW>.
> * Click on the login button (no account required).

**Comment by pintassilgo** [comment]
uBlock Origin dashboard
My Filters
add new line:
`pornhub.com##+js(set-constant.js,  performance.timing.loadEventEnd, 1)`
Apply changes

Then reload the site and try again.
