### ISSUE TITLE
middlemouse.paste & autoScroll & clipboardevents [1528289]

### ISSUE THREAD

**Issue by gwarser** [ghacksuserjs/ghacks-user.js#735]
You already have clipboard covered, but I think this pref and it's side effects is worth knowing about.

https://bugzilla.mozilla.org/show_bug.cgi?id=1528289

**Comment by Thorin-Oakenpants** [comment]
So, until the bug is fixed, this would be `middlemouse.paste` then? It's false in Windows. What is it on Linux? I have a shit tonne of VMs here, so if no-one tells me I'll check it myself.

**Comment by gwarser** [comment]
On Linux it's true.

**Comment by Thorin-Oakenpants** [comment]
And does setting it to false prevent the leak?

**Comment by gwarser** [comment]
> And does setting it to false prevent the leak?

Yes.

>middlemouse.contentLoadURL

This is `false` on my side in 67.

`dom.event.clipboardevents.enabled` also prevents this, and you already have it set to `false`

**Comment by gwarser** [comment]
`middlemouse.contentLoadURL` probably disabled here: https://bugzilla.mozilla.org/show_bug.cgi?id=366945 I did not read it all.

**Comment by Thorin-Oakenpants** [comment]
I could have sworn there was a LINUX mouse thing already in our js

**Comment by crssi** [comment]
^^ `user_pref("clipboard.autocopy", false);`

**Comment by Thorin-Oakenpants** [comment]
wait a minute

> `dom.event.clipboardevents.enabled` also prevents this, and you already have it set to `false`

So I didn't need to add the new pref. I need to rethink this and tie those two prefs together: reopening so I remember what to do

**Comment by Thorin-Oakenpants** [comment]
@gwarser -> https://trac.torproject.org/projects/tor/ticket/32766

**Comment by gwarser** [comment]
Leaking on Tor Browser 20190402030101 Manjaro KDE. Middle clicking on imgur.com shows "Sorry, URL failed to upload." bubble.

Both `dom.event.clipboardevents.enabled` and `middlemouse.paste` are `true`

**Comment by rusty-snake** [comment]
FWIW
```javascript
/* 6904: enable middlemouse paste and disable autoScroll
 * The middlemouse paste clipboard leaking in 2403 occurs only
 * after autoScroll, so disabling autoScroll is an alternative fix. ***/
user_pref("middlemouse.paste", true); // 2403
user_pref("general.autoScroll", false);
```

**Comment by Thorin-Oakenpants** [comment]
this is in the 5000s
// user_pref("general.autoScroll", false); // middle-click enabling auto-scrolling [WINDOWS] [MAC]

autoScroll is default true in windows (and mac looking at the notation), so I can't go disabling it for all users. Whereas middlemouse.paste is already false on windows, so enforcing it doesn't do any harm but helps linux privacy (not sure about mac)

Not sure how to add that 5000s pref into 2403 - but it would have to be inactive

**Comment by Thorin-Oakenpants** [comment]
@rusty-snake Are you sure that pref applies to linux? I only ask because the 5000s notation says windows/mac

**Comment by Thorin-Oakenpants** [comment]
pending draft awaiting rusty-snake (or anyone else)
```js
/* 2403: disable middlemouse paste leaking clipboard content on Linux after autoscroll
 * Defense in depth if clipboard events are enabled (see 2402)
 * Alternatively, you could disable autoScroll (see 5000s: general.autoScroll)
 * [1] https://bugzilla.mozilla.org/1528289 */
user_pref("middlemouse.paste", false); // [DEFAULT: false on Windows]
```

**Comment by rusty-snake** [comment]
@Thorin-Oakenpants yes. I assume that it says window/mac because the default for linux is false. https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#197-201

**Comment by Thorin-Oakenpants** [comment]
ok, that makes sense .. i.e the notation means this pref is useful for windows/mac

So if autoScroll is already false on Linux, then why do we need to do anything here? The bug says it occurs on Linux "after autoScroll" - so does that mean the linux user must have enabled autoScroll?

**Comment by rusty-snake** [comment]
Linux: bug occurs only if user set general.autoScroll = true.
Windows: bug occurs only if user set middlemouse.paste = true ??

I think the default for these values just follow the platform defaults. Therefore its a workflow decision what the best solution is.

> why do we need to do anything here?

Since autoScroll has a GUI and the user may not know (and never assume) that it can leak the clipboard, it should be there as an information. But we can maybe comment it.

enforcing `"middlemouse.paste", false` breaks a typical linux workflow, while enforcing `"general.autoScroll", false` breaks a typical window workflow.

**Comment by Thorin-Oakenpants** [comment]
> Windows: bug occurs only if user ...

Wait! So when did this become a windows bug, because that changes things? I was under the impression it was a Linux only one (not that I have followed it). I'll go read the bugzilla top to bottom

But what also changes things (now that I have a clearer picture) is that Linux users have to flip autoScroll, and windows users have to flip middlemouse ... and both as user.js users have to override clipboard ..

**Comment by Thorin-Oakenpants** [comment]
Linux
- default autoScroll = false <-- hence no bug
- default middlemouse.paste = true
- default clipboard = true (false in user.js = no bug)

Windows
- default autoScroll = true
- default middlemouse.paste = false <-- hence no bug
- default clipboard = true (false in user.js = no bug)

The bug also requires two changes by our user.js users: flipping middlemouse or autoscroll *and* overriding clipboard. Overriding clipboard events has a setup tag and from memory was a frequent override in our small sample/feedback

We do have autoScroll in the personal section (inactive) which could encourage Linux users to flip it (so I do feel *some* responsibility), but until this issue, we didn't even have middlemouse.paste. 

There's no way to "win" here: middlemouse as actively false takes away default Linux functionality. Likewise, we can't go disabling autoScroll for the same reason for Windows

The cleanest solution is to remove `2403` altogether but put the bug info into `2402` (and I'll clean up the autoScroll notation)
