### ISSUE TITLE
What is the suggested "pace" to update the user.js file?

### ISSUE THREAD

**Issue by GIPeon** [ghacksuserjs/ghacks-user.js#736]
Hei there!

Sorry maybe the title is not clear, how often is suggested to update the user.js file based on new commits on master?
In other words, what is the best practice to stay up to date with the project?

For ex. when a new FF version is out is it recommended to wait for the user.js beta release of the new version before upgrading firefox and updating the user.js file?  
After this update to the user.js, is it recommended to update on every commit or so?

Thank you all again for your time and efforts in this project!

**Comment by claustromaniac** [comment]
*Thou shalt update thine copy of our scripture once, before the first beams of daylight pierce the darkness.*
*Then once at the exact time when the great Sun reacheth the center of the sky.*
*Then once before all diurnal creatures finally retreat to the safety of their resting places.*
*Then once at midnight. Twice if the Moon is full.*
*And finally, once MOAR after saying thine bedtime prayers.*

Of course, that only applies if you update your client just as frequently. If you're an ESR user, go for the archived version (in the [releases](https://github.com/ghacksuserjs/ghacks-user.js/releases)) that matches your version of Firefox.

**Comment by jotyGill** [comment]
The poetry made me lol

**Comment by GIPeon** [comment]
I see thank you for your answer, I vote for this sonnet to have a spotlight in either home readme or somewhere in the wiki! :notes:
