### ISSUE TITLE
FF67 Content Blocking vs Extensions

### ISSUE THREAD

**Issue by bitpixl** [ghacksuserjs/ghacks-user.js#738]
With Firefox 67 there's now more options when it comes to content blocking.
I'm just wondering which options to enable/disable when I already have the recommended extensions installed.

Currently Trackers and Cookies are enabled, but doesn't uBo take better care of trackers? Or do they complement each other?

**Comment by Thorin-Oakenpants** [comment]
The user.js currently sets blocking all 3rd cookies. This will auto-magically put you into custom mode in Option>Privacy & Security>Content Blocking

The user js does not set what "tracking" lists to use - that's up to your or Firefox (when they turn them on for you: see https://www.ghacks.net/2019/06/04/mozilla-enables-tracking-protection-by-default-in-firefox/ ). 

I certainly can't hurt to have TP (tracking protection, that's what it used to be called in the UI) on - feel free to turn on the crypto and FP ones. This is `content` blocking, not spoofing or limiting or blocking actual fingerprints so don't confuse the FP one with RFP.
