### ISSUE TITLE
Any way to enable ESR user settings with the updater.bat script ?

### ISSUE THREAD

**Issue by xago9** [ghacksuserjs/ghacks-user.js#741]
I'm currently using the auto user.js updater.bat. With the Linux script, the -e option enable the ESR settings but there's no option for Windows, I tried a few different way by playing with the script code but I can't achieve anything, the only solution for now is to put every entry 1 by 1 in the user.js-overrides but if any entries is changed or added I'll miss it. So, how can I auto enable those entries with the script ?

Thanks

**Comment by claustromaniac** [comment]
There is currently no simple way (other than the one you mentioned). I'm going to add this functionality as soon as I can spare a few minutes.

**Comment by claustromaniac** [comment]
Added this in v4.8. If there are any other improvements you would like to see, let us know.

**Comment by xago9** [comment]
The script doesn't work on my side. It seem to active the ESR option before downloading the user.js and do my overrides so the ESR activation is replaced with a deactivated one coming from the new user.js file.

**Comment by xago9** [comment]
Ok, it's activating the 9999 pref, that's not what I was taking about. The pref I want to enable is the 4600 one.

**Comment by claustromaniac** [comment]
> that's not what I was taking about

Well, actually, you *did* say ESR, so you *were* talking about ESR 😁 Even if that's not what you meant, it wasn't a waste of time, so that's OK.

The code needed for activating section 4600 should be almost the same. Let's add that too.

**Comment by claustromaniac** [comment]
Quality control (AKA @earthlng's review) is still pending, but you can test it before then if you want.

https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/updater.bat--RFPalts-option/updater.bat

**Comment by xago9** [comment]
@claustromaniac I was talking about ESR because of this "IF you DO NOT use RFP or are on ESR... then turn on each ESR section below" at the beginning of the section, I think it's also what "-e" enable in the linux script. I didn't even know there were an ESR section in 9999 my bad ! :disappointed:

**Comment by earthlng** [comment]
> I think it's also what "-e" enable in the linux script

no, -e in the linux script only enables the ESR section in 9999.

There's a now an `-RFPalts` switch in the windows script but it's primarily for people who don't use RFP.
It's not possible to have a 1-char switch group within another 1-char switch group so we can't just enable the parts of 4600 that ESR60 users would need.
I'd just use the -esr switch for 9999 and copy the 2 prefs relevant for ESR60 from 4600 to your overrides and keep an eye on the next changelogs for anything new moved to 4600.

**Comment by claustromaniac** [comment]
> I didn't even know there was an ESR section in 9999 my bad !

No problem!

@Thorin-Oakenpants, what do you think about adding a `[SETUP-ESR]` tag or something like that? @xago9, do you think something like that would've helped?

**Comment by Thorin-Oakenpants** [comment]
IDK: I don't want to encourage ESR users to use stable releases: even though we're careful to not impact them (e.g dead wood removed that was at defaults I checked back to 60). Upcoming changes like removing css font loading, intersection observer etc are close to 68 release.

And I don't want to use too many SETUP-names. The ESR section info is in the readme at the top which also points to the wiki which also highlights ESR stuff as one of 4 things to look at
