### ISSUE TITLE
1400: font revision

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#744]
Suggestions: fonts is all about FP'ing

* [x] remove `1402` as we shouldn't encourage users to change default fonts
* [x] remove `1407` font.blacklist.underline_offset
* [x] remove `1406` CSS Font Loading API

**Comment by Thorin-Oakenpants** [comment]
@earthlng how do you detect the default font with doc fonts = 0? I have some ideas, a fast(ish) easy measurement one using a small list based on default fonts in various language packs. What did you have in mind when you said it was FP'able?

**Comment by earthlng** [comment]
> @earthlng how do you detect the default font with doc fonts = 0?

IDK how reliable or possible it is across various OS's/OS versions/languages etc but I have a test page that works for me on Win7 latin/western. I could tell you how but then I'd have to kill you :)
No but seriously, I don't want to help "the other side" by giving them more material to FP and track people, like you do with your page. I kinda get why you're doing that but it could take TB and/or mozilla years (if ever) to address and fix these things and until then you're not doing anyone a favor by searching/finding and listing every little possible FPing vector, IMHO. Certainly not by doing it publicly. Sorry, just my opinion

**Comment by Thorin-Oakenpants** [comment]
As mentioned in  the above referenced commit:

`1407` handles "correction" of "underline offsets" for some fonts: namely [CJK characters](https://en.wikipedia.org/wiki/CJK_characters). When you whitelist fonts or when RFP kicks in with it's protection, this will alter your FP.

brb .. I need to double check something

**Comment by earthlng** [comment]
AFAIK you don't need RFP or a font whitelist for 1407 to alter your FP

**Comment by earthlng** [comment]
> and I know from other tests that these fonts and more (e.g SimSun) etc are not actually blocked from use

no I'm pretty sure they're blocked but it's just that some fonts produce the same fingerprint as others and that's why these test pages aren't accurate in a sense ie they can't tell if you use font x or y if they both share the same FP.

**Comment by Thorin-Oakenpants** [comment]
>  but I have a test page that works for me on Win7 latin/western. I could tell you how but then I'd have to kill you :)

I'm sure I can work it out - I have a dozen proofs here to follow up on, just on fonts. I'm only getting started. So far I haven't publicly revealed anything that wasn't already public. And not everything I've done has been public. Anyway, TB need to up their game :) I'm not waiting another five years (I think that's how long it took to get user agent sorted out)

**Comment by Thorin-Oakenpants** [comment]
> no I'm pretty sure they're blocked but it's just that some fonts produce the same fingerprint

Hrmmm ... that kinda makes sense... you could test it (I'm feeling a bit overburdened right now), just load a page in Chinese (zh-CN): default fonts are SimSun (serif), Microsft YaHei (sans-serif), SimSun (monospace) and look at the inspector, I guess. **SimSum** is in the 1407 default value

**Comment by Thorin-Oakenpants** [comment]
I'm happy to remove `1402`, but add a note to `1401` that if this breaks extension glyphs e.g uMatrix, then change the serif font in the UI (pretty sure it's only on some linux packages and it's serif and they change to deja something: i'll check)

:1: if you agree

**Comment by earthlng** [comment]
I thought you meant "block" by using the whitelist pref.
1407 AFAIK does NOT block fonts in any way. All it does is change how those fonts are displayed or rendered and clearing the pref just increases entropy hence I suggested to remove it.

**If** you'd use a very restrictive whitelist that doesn't include any of the fonts listed in the default value of 1407 then I guess clearing 1407 wouldn't matter but since we don't use the whitelist pref at all, 1407 just increases our entropy among the crowd that blocks document fonts and it's better to get rid of it (as you already did)

just to clarify what was said earlier

**Comment by Thorin-Oakenpants** [comment]
^^ no worries. As I said, the whitelist and the 1407 default value contain a font overlap (lots)

**Comment by Thorin-Oakenpants** [comment]
Anything else you want to do in this section?

- I think we can remove `1406` entirely
- Probably remove `1405` as well
- `1403` does limit enumeration, but I fail to see how it helps FP'ing, but we could leave it in if you have any more insight on that.

Apart from that the rest look fine, for now

**Comment by Thorin-Oakenpants** [comment]
^ bump .. I'm going to go ahead and remove `1406` CSS Font Loading API, see #731 and/or feel free to correct :cat2: and I

**Comment by Thorin-Oakenpants** [comment]
So just FYI: `gfx.downloadable_fonts.disable_cache` is a separate cache specifically for L'able fonts and is not FPI'ed yet. [1560580](https://bugzilla.mozilla.org/show_bug.cgi?id=1560580). The fix is pretty straight forward so I expect it to land relatively sooner than later (and TB to backport it).

IMO, this pref would be a good addition `active` item to add to the fonts or cache section with a perf tag

@earthlng

**Comment by Thorin-Oakenpants** [comment]
^^ bump

**Comment by Thorin-Oakenpants** [comment]
FYI:
- Here is the paper about font glyphs FPing: https://www.bamsoftware.com/papers/fontfp.pdf
   - Note: the sample FP on the second to last page: the 43 unicodes used match the test at https://browserleaks.com/fonts
- Here is a demo: https://www.bamsoftware.com/talks/fc15-fontfp/fontfp.html#demo
   - Note that they didn't use a giant font size for demo purposes
   - flip on visible and slow, and it you can see the tofu when you're blocking something :)

**Comment by Thorin-Oakenpants** [comment]
^^^ bumpitty bump @earthlng @claustromaniac

**Comment by claustromaniac** [comment]
> Probably remove `1405` as well

That is only in the user.js for security reasons, right? is it inactive just because it breaks stuff? It doesn't have even a minimal description explaining why it is there. That's inconvenient.

As for `1403` I'd have to research for a while first to give useful input. @earthlng will already have helped you by then (maybe?).

**Comment by Thorin-Oakenpants** [comment]
If a font is downloadable, then it's not a fingerprinting issue, it's a tracking issue. And there are other ways to control third party fonts (think google fonts).

AFAIK, WOFF2 are always downloadable fonts? `gfx.downloadable.`* are also downloadable fonts. Hence both `1403` and `1405` are inactive. But they are in there for users who would like to block them outright without relying on an extension. WOFF2 is not in there for security reasons.

Disclosure: I am not a font expert

**Comment by claustromaniac** [comment]
> WOFF2 is not in there for security reasons.

I thought it had to with [this](https://www.w3.org/TR/2015/WD-WOFF2-20150414/).

**Comment by Thorin-Oakenpants** [comment]
Well, it wasn't added for security reasons, unlike graphite or SVG OpenType. I don't think it's any more of a risk than jumping into a volcano .. no, wait, I meant .. than most things: i.e slim to none

**Comment by earthlng** [comment]
> gfx.downloadable_fonts.disable_cache

IDK man. I guess it depends on whether it just reuses the same font file directly or whether it sends some kind of request or something. But yeah, because I'm too lazy to test it and because we'll probably never really know for sure, I'd say it's fine to just disable it. But I'd add it in the Fonts section instead of Cache.

AFAIK 1403 is mainly inactive because it also breaks fonts used by extensions. And it's also more convenient to have the pref inactive and control downloadable fonts with uBO, IMO.

1405 will be removed in FF69 if I remember correctly. Let's just wait until then and then move it to 9999.

> I thought it had to with this (see security considerations).

same here. Some of these shitty font formats definitely have potential security problems.
We don't disable shit just to annoy people :)

**Comment by Thorin-Oakenpants** [comment]
> 1405 will be removed in FF69 if I remember correctly

cool, one less thing

> gfx.downloadable_fonts.disable_cache ... But I'd add it in the Fonts section instead of Cache

It's not a font problem, it's a cache problem. The FPI is a separate issue which simply alerted me to the fact that this is a separate cache. **Assuming** it works like other cache: it would allow cache-based timing attacks / tracking etc: see cache section header? Pretty sure an ETAG can be applied to a font

FYI: I think there are other caches as well (that may or may not be covered by the main cache pref) - there's one about media (video) which TB has been grappling with for the last 6 months. Not that every cache has a pref.

**Comment by Thorin-Oakenpants** [comment]
I'm probably not testing this correctly

- gfx.downloadable_fonts.disable_cache -> true
- restart Firefox in case
- clear everything
- load https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#fonts
- open network inspector
- run enumerate fonts
- re-run enumerate fonts
- It uses the cached version

![test](https://user-images.githubusercontent.com/16656956/61236683-21da5d00-a728-11e9-8c65-64f055f658a7.png)

**Comment by earthlng** [comment]
> - gfx.downloadable_fonts.disable_cache -> true
> ...
> - It uses the cached version

so the pref doesn't work?

I think you'd need to test this with 2 domains anyway to see if it would reuse/send any ETAGs or whatnot set by one domain on the other domain as well.

fe. foobar.com loads FontA from google fonts and then example.com also loads the same google FontA. Assuming you're using a VPN so that google won't know it's you just based on your IP; will they be able to know that you visited both foobar.com and example.com because the font request sent the same identifier. That's the question, right?

**Comment by Thorin-Oakenpants** [comment]
> so the pref doesn't work

Not sure: I've put out a feeler. Maybe the separate cache isn't being used? Maybe memory cache takes precedence? Could be regressions. It was just a quick test in my main FF. I should do these in a vanilla one: because there are more parameters and as you said: same font over two domains

**Comment by earthlng** [comment]
Personally I'm not too worried about this because I rarely allow fonts and TC should isolate them anyway.
But that doesn't mean that we shouldn't deal with this for people who love their fonts and may not use TC.

**Comment by Thorin-Oakenpants** [comment]
Oh, indeed: I think it needs to be added, but I think I need to make sure it works first :)

I also rarely allow DL'able fonts, and when they add FPI to it, that's as good as TC (but not quite as good as TLC in hard-mode). But we'd still have to cater for font lovers with no TC and no FPI

**Comment by Thorin-Oakenpants** [comment]
@earthlng ... OK, I got an answer back

> This cache isn't at the network layer, it's about caching the parsed font in the graphics layer. You might be able to observe a timing difference on a large/complicated font file with the pref enabled/disabled.

So if that's the case, then we don't have a "disk" cache issue, which is the only reason I wanted to add it. So we can ignore this pref IMO: FPI will get to it soon enough.

**Comment by Thorin-Oakenpants** [comment]
closing this: when woff2 is deprecated, then that leaves the font section small, clean and simple

**Comment by earthlng** [comment]
> This cache isn't at the network layer, it's about caching the parsed font in the graphics layer.

that's exactly what I suspected might be the case with this being a `gfx.*` pref vs anything else.
Thanks for asking around and getting us a definitive answer! 👍

**Comment by Thorin-Oakenpants** [comment]
@earthlng FYI: enabling/disabling HWA affects your font FP: i.e the detected fonts type tests - see https://bugzilla.mozilla.org/show_bug.cgi?id=1121643#c84
