### ISSUE TITLE
0503 normandy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#746]
https://blog.torproject.org/comment/282460#comment-282460

@earthlng This isn't a system addon anymore, right? I think we can remove this - yes/no?

**Comment by earthlng** [comment]
section 0500 is also about experiments, not just system addons. I don't know/care about the state of normandy in ESR but in newer versions it's definitely still used:
https://dxr.mozilla.org/mozilla-central/search?q=app.normandy

like fe

https://dxr.mozilla.org/mozilla-central/source/browser/components/preferences/in-content/privacy.js#31
https://dxr.mozilla.org/mozilla-central/source/toolkit/components/normandy/lib/RecipeRunner.jsm#39

I would not remove it.

**Comment by Thorin-Oakenpants** [comment]
OK, just thought I'd delegate some of the work load :+1:
