### ISSUE TITLE
sticky: user scripts

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#75]
Use this issue to suggest scripts for our wiki section [Further Hardening: Extension Scripts](https://github.com/ghacksuserjs/ghacks-user.js/wiki#small_orange_diamond-further-hardening). We're looking for scripts that enhance privacy and security, and block tracking and fingerprinting.

Please try to stick to general/global or major site specific scripts (such as google), rather than obscure sites no one really cares about.

**Please note: The comments here will be regularly cleaned out to keep this sticky usable**

**Comment by crssi** [comment]
Some sites are trying to set tracking ID by adding ?something after the img url
see example: http://somedomain.com/blahblah/blah/image.jpg?21dd8daded_61880689
Maybe its nothing, but I just don't trust the hash after "?"... maybe someone can comment about it?

I am using REDIRECTOR to strip those out:
Include pattern; `(.*\.(gif|jpg|png|svg))\?.*`
Redirect to: `$1`
Pattern type: regular expression
Apply to: Images

**Comment by Atavic** [comment]
Reek's script: https://github.com/reek/anti-adblock-killer

**Comment by zymase** [comment]
Having a discussion thread discussing about user scripts is a great idea.

Just had a look at the scripts already available on the https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-User-Scripts page. I already had two of them mentioned by their developers (earthlng and Thorin-Oakenpants) on gHacks, but I noticed that the _Conceal history.length_ script had been slightly modified since.

Of course many scripts are available on sites like _GreaseMonkey_, but fewer focusing on privacy and security as I believe this is what is most called for here. Slick, tight little scripts like the ones made available here already are fantastic, a few lines of code and quite a deal of efficiency. Browsers evolve, scripts remain.

I don't code myself (I did 30 years ago with something like Visual Basic!!) but if I happen to meet a pertinent script I'll pass the information.

**Comment by Thorin-Oakenpants** [comment]
I really want to ramp up the scripts section. I have a few choice ones myself. The problem is they break or don't get maintained. There's nothing decent in the way of add-ons that clean up tracking in urls. It's more a case of finding working scripts for various sites, such as FB, google services, soundcloud ... I mean, FFS (that's short for "For F**ks Sake, if you didn't know tom) even AMO want to track your exit clicks

**Comment by zymase** [comment]
Thorin-Oakenpants, you must know better than I that before _GreasyFork_.org (and not _GreaseMonkey_ as I mistaked above!)  the reference site was userscripts.org, now abandoned but mirrored by https://userscripts-mirror.org/ at least as an archive. Many old scripts but I'll have a look there, may inspire ideas, some scripts are possibly still functional or at least "updatable".

[...]_There's nothing decent in the way of add-ons that clean up tracking in urls_.  About crssi's post above, and linking to your comment, I do use three Firefox add-ons for this purpose, _Pure URL_, _Redirect Bypasser_ and _No Resource URI Leak_ : maybe they can come in handy for crssi's purpose, even if, if a script can do what an add-on can do then it's always better. One can also dig into an add-on in quest of the valuable script lines (won't be as obvious with WebExtensions though!).

I knew the three words of FFS but not associated :)

**Comment by crssi** [comment]
I am using _redirector_ for some other purposes and since I have it installed, I have used it for the purpose written in my previous post. ;)
I am using the same AMOs as @zymase except _skip redirect_ instead of _redirect bypasser_.

@Thorin-Oakenpants where AMO want to track exit clicks?
Unfortunatelly FF doesn't deserve my full trust either, sometimes I get feeling that they break some anti-tracking in purpose or they don't want to implement some for unknown reason, like _No Resource URI Leak_. :(
So, then I got to section 0400, where I would enable only mozilla stuff, but...

**Comment by fmarier** [comment]
> And why the hell in FF you need to opt-out every time for untrusted certs.
> The checkbox should be cleared by default as this addon does https://addons.mozilla.org/en-US/firefox/addon/y-u-no-validate/
> What this addon does should be default in FF.

Have you tried filing a bug about it? This checkbox has been around for a really long time, I'm not sure people thought a whole lot about what the default value should be. The majority of users [have no permanent certificate overrides](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-04-01&keys=__none__!__none__!__none__&max_channel_version=nightly%252F55&measure=SSL_PERMANENT_CERT_ERROR_OVERRIDES&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-03-08&table=1&trim=1&use_submission_date=0).

**Comment by crssi** [comment]
@fmarier 
Thank you for respond. :)
I am taking you as very smart man and my "rant looks like" wasn't meant for you and I hope that was not taken that way.

No I haven't filed a bug, since I strongly believe that it will not be taken seriously.
For example `No Resource URI Leak` is serious and still its open already for 2 years.
Then who will even blink an eye at FF for the checkbox I mentioned. ;)
Also it might not be even a bug, but a feature. But I still believe that opt-out way is a wrong way.

I also don't need any glory filling a bug, that's why I have asked you about this problem and since I respect your knowledge as security expert, you can decide to fill it or not.

I didn't understand well the link you provided with a cert overrides statistics.
If it means that a majority removes then checkbox, so not to store exception, it would be easier if that was a default setting. Also if others who stores the cert, are they even aware they have done that.
For a user that is not secure aware and does not understand what this checkbox mean it is a security risk.

Cheers

**Comment by fmarier** [comment]
> No I haven't filed a bug, since I strongly believe that it will not be taken seriously.

At the end of the day, just like with any large Open Source project, there are many more bugs in Firefox than we have time/people to fix them. So yes, it's possible it won't get fixed any time soon. At the same time, if nobody suggests changing it, it's pretty much guaranteed not to change :)

**Comment by crssi** [comment]
True and fair enough. I guess will have to live with it.
Anyway, thank you @fmarier for taking a time to answer, I appreciate it much.

**Comment by Atavic** [comment]
Obscure annoying sites from Google search results:
https://github.com/curipha/userscripts/blob/master/google_personal_blocklist.user.js

A personal blocklist, which has to be modified, but the idea is good IMHO

**Comment by Thorin-Oakenpants** [comment]
@earthlng : see if you can shrink [this](https://github.com/jaredsohn/noopener_by_default/blob/master/noopener_by_default.js) will ya xD

**Comment by earthlng** [comment]
> see if you can shrink this will ya xD

Doesn't get much shorter than what we already have, to deal with [window.opener](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-User-Scripts#small_orange_diamond-clear-windowopener)

**Comment by publicarray** [comment]
@crssi sometimes these are used as unique links and sometimes they are part of the authentication mechanism. e.g. Only users with the exact link are allowed to see the file or image. 
e.g. Facebook: https://scontent-syd2-1.xx.fbcdn.net/v/t34.0-1/p160x160/16176889_112685309244626_578204711_n.jpg?oh=21587895d22fb2b678e2f60285c4e240&oe=59CAC063 without the ?oh= or &oe= fb replies with 403 (Forbidden)

**Comment by crssi** [comment]
@publicarray thank you.
Months ago I have dropped REDIRECTOR, since there are some problems with it.
For this "tracking" over the images I am using now [Request Control](https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/) with additional exclusions.

The rule definition:
```json
[ { "pattern": { "scheme": "*", "host": [ "*" ], "path": [ "*.jpg?*", "*.gif?*", "*.png?*", "*.svg?*" ] }, "types": [ "main_frame", "sub_frame", "image" ], "action": "filter", "active": true, "skipRedirectionFilter": true, "paramsFilterPattern": ".*", "paramsFilter": { "values": [ "w", "h", "crop", "s", "q", "auto", "fit", "size", "v", "height", "width", "dl", "sigh", "displayname", "oe", "oh" ], "invert": true }, "title": "Filter%20rule%20for%20*" } ]
```

RC also has "problems", but not in this case and this rule is the only rule I am using under RC.
For everything else about URL manipulation I am using now [Skip Redirect](https://addons.mozilla.org/en-US/firefox/addon/skip-redirect) for redirection control (its best one and works without a glitches out-of-the.box) and [Neat URL](https://addons.mozilla.org/en-US/firefox/addon/neat-url) for parameters stripping with the following configuration (default + quite big of additional chunk):
```
$/ref@amazon.*, _encoding@amazon.*, _hsenc, _hsmi, _openstat, action_object_map, action_ref_map, action_type_map, algo_expid, algo_pvid, aqs, bav, bih, biw, btsid, bvm, cn, cp, csi, cvid@bing.com, dpr, dq, ech, ei@google.*, fb_action_ids, fb_action_types, fb_ref, fb_source, feature@youtube.com, form@bing.com, forward, ga_campaign, ga_content, ga_medium, ga_place, ga_source, ga_term, gclid@youtube.com, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd@google.*, iact, icid, iid, ijn, kw@youtube.com, mkt_tok, ncid, ndsp, nid, nr_email_referer, oq, pbx, pd_rd_r@amazon.*, pd_rd_w@amazon.*, pd_rd_wg@amazon.*, pf, pf_rd_i, pf_rd_m, pf_rd_p, pf_rd_r, pf_rd_s, pf_rd_t, pq, pq@bing.com, prmd, psc@amazon.*, psi, qs@bing.com, ref_, refsrc, sa, sc@bing.com, sclient, scroll, sei@google.*, sk@bing.com, sp@bing.com, sr_share, stick, tbnid, utm_campaign, utm_cid, utm_content, utm_medium, utm_name, utm_place, utm_pubreferrer, utm_reader, utm_source, utm_swu, utm_term, utm_userid, utm_viz_id, ved, ved@google.*, vero_conv, vero_id, vet, ws_ab_test, yclid, yv
```

**Comment by ZIEXED** [comment]
https://github.com/AdguardTeam/Userscripts/blob/master/disableAutofillPhishing/disable-autofill-phishing.user.js

**Comment by Thorin-Oakenpants** [comment]
thanks @ZIEXED - sorry, have been away for 2 days. I haven't forgotten these - its my todo list to look at more (I had a quick nose before I left) and probably add

**Comment by Atavic** [comment]
UTM usage:
https://github.com/silvermind/rack-utm#common-scenario
means cookie synching:
https://github.com/ghacksuserjs/ghacks-user.js/issues/11

**Comment by Thorin-Oakenpants** [comment]
@earthlng & co - see https://github.com/snyderp/web-api-manager/issues/75 re thwarting Page Visibility API and peter's comments. Can this be beefed up to cover the things mentioned?

> It doesn't handle the vendor prefixed versions of each feature, so the same information might be accessible through document.mozHidden or document.webkitHidden, etc

while not really necessary from a privacy/security perspective, I'm quite keen on it. I came across it on a reddit thread about a month ago, and then this [reddit thread](https://www.reddit.com/r/firefox/comments/7wzpzy/the_reason_i_open_tabs_in_the_background_is_so/) reminded me I had it

**Comment by mazesy** [comment]
[Clear window.opener](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts) script appears to be unsuccessful when tested at [About rel=noopener](https://mathiasbynens.github.io/rel-noopener/)

There is another script which is flawless: [noopener_by_default](https://github.com/jaredsohn/noopener_by_default)

**Comment by Thorin-Oakenpants** [comment]
### "clear window.opener"

`Click me!!1 (same-origin)` :x: 
- loads malicious in a new tab and displays "Why don’t you go back to the previous tab?"
- the previous tab has been changed to `...#hax` so it displays `0m6 you’ve been h4ck3d!!1one!shift!!!1` at the top

`Click me!!1 (cross-origin)` :heavy_check_mark: 
- loads demo/opener in a new tab and displays "Why don’t you go back to the previous tab?"
- the previous tab is unchanged

---

### "noopener by default"

The script says  "@description  blah blah blah. **For Chrome only**. blah blah", but I tested it anyway. Seems fine.

`Click me!!1 (same-origin)` :heavy_check_mark: 
- loads a new tab with malicious.html and displays "The previous tab is safe and intact. window.opener was null; mischief not managed!"
   * WTF does "mischief NOT managed" mean? sounds back to front to me!
- the previous tab is unchanged

`Click me!!1 (cross-origin)` :heavy_check_mark:
- same result as clear window.opener

---
Note: for both scripts, cross-origin causes CSP console errors. There are no console errors for same-origin.

I'll leave this in earthlng's hands

**Comment by crssi** [comment]
Why would window.opener be a problem on same-origin?
Asking, since I blindly do not see the real problem there might be.

**Comment by earthlng** [comment]
1. if the cross-origin test `displays "Why don’t you go back to the previous tab?"` you probably didn't allow JS on that page. Flawed testing. just sayin' ;)
2. FPI together with `privacy.firstparty.isolate.restrict_opener_access=true` already covers cross-origin window.opener tampering
3. my script is not flawed, thank you! it works perfectly fine with legacy Greasemonkey in my ESR. The problem is that webextension user-script addons apparently can't guarantee that `@run-at      document-start` works reliably or works at all. The greasemonkey [wiki](https://wiki.greasespot.net/Metadata_Block#.40run-at) has this to say:
> `@run-at` **document-end** ... *The only guaranteed working value, in Greasemonkey 4.0.*

I assume the same is true for Violentmonkey and others.

The greasemonkey wiki provides a code example to test if any `@run-at document-start` script actually runs at **document-start**:
```js
if ('loading' == document.readyState) {
  alert("This script is running at document-start time.");
} else {
  alert("This script is running with document.readyState: " + document.readyState);
}
```
I tried it numerous times and **not once** did I get an `This script is running at document-start time.` alert! So the problem is much worse than just my script not working reliably (or at all) because **any and all** user-scripts which need to run at document-start don't work. Nothing I can do about it, it's up to either mozilla to fix this or to the addon devs to come up with a workaround.

**Comment by earthlng** [comment]
> Why would window.opener be a problem on same-origin?

because of user-generated content on a website

**Comment by mazesy** [comment]
I'm not at all into coding, need to repeat. I just happened to run a test page, noticed a script _apparently_ wasn't doing the job when another performed correctly.

Javascript never disabled here.
The other script, _noopener_by_default_, doesn't include any `@run-at` ... and yet works.

I'm not discussing, only submitting. I'm fully aware this could be a false-positive. No idea, really.

**Comment by crssi** [comment]
> because of user-generated content on a website
yes, but its the same origin... isn't that quite normal by some web apps to pass some data to a new window/tab
I still don't see the problem until this is not happening cross origin

**Comment by earthlng** [comment]
> EDIT2: middle-clicking a link opens the tab in such a way that document-start scripts work correctly

to clarify, middle-clicking let's a script (reliably?) run at document-start but it's not guaranteed that the script works as expected. Something fundamentally changed with webextensions vs legacy which means some scripts need to be rewritten to work with webextension user-script addons. For example the `Conceal history.length` user-script from the wiki doesn't work anymore even if it happens to run at document-start. `Conceal window.name` most likely doesn't work anymore either but I haven't tested it.

**Comment by mazesy** [comment]
> Something fundamentally changed with webextensions vs legacy which means some scripts need to be rewritten to work with webextension user-script addons.

That explains why _**clear window.opener**_ runs flawlessly with legacy Greasemonkey in ESR, OK

About _**conceal history.length**_ : impossible to determine its validity here considering I always get
`Number of pages visited in History 	1`  on dedicated _BrowserSpy_ test page

About _**Conceal window.name**_ : seems to do the job considering I get, on dedicated JoDonym test page,
`Tab name -- "window.name" has been anonymize`d.when script is active
`Tab name -- "window.name" is traceable. Your unique ID: xxxxxxx` with script deactivated

Really odd, and triggers an alarm if it appears that scripts run by a legacy script manager run differently when applied with a webextension script manager. This would be a scoop.

**Comment by mazesy** [comment]
@Thorin-Oakenpants ,

> The document [noopener_by_default] run is in the script settings of the VM dashboard

So true... I had forgotten that!
Nevertheless, concerning the _**noopener_by_default**_ script, I had simply copy/pasted it without modifying its settings pane, so I have there`Run-At -- (Default)`

So then, concerning our _**Clear window.opener**_ script, it appears I had as well not set its `Run-At` -- to `document-start` in its setting pane. I installed again, set this time `document-start` but the script continues as before with  `Run-At -- (Default)` : inefficient (_apparently_ considering what @earthlng mentioned afterwards), anyway still inefficient when run with ViolentMonkey (webext) on FF52.0.2.

**Comment by Thorin-Oakenpants** [comment]
### conceal history.length

works fine on both browserspy and jodonym. They are both run at document start in VM.

STR
- disable conceal history.length
- go to the wiki in a NEW TAB, click around and load five or six pages in that tab, the last one being the user scripts page
- click the browserspy link and the number of pages in (tab) history will be correctly shown
- enable conceal history.length from the VM toolbar button and the test page reloads and history is now `2`
- toggle it on and off. It works

^^ Ditto for same script tested on JoDonym's "tab history"

---

### conceal windows.name

Exact same thing, except I already had the JoDonym open in that tab (the one I had lots of history in), so instead I toggled conceal windows.name. The script works.

---

### noopener by default

works every time: is run at document-start: And as I type Tom just said it works as run at Default. I do not know what "default" means.

**Comment by earthlng** [comment]
> Can you do your document start test in VM?

your test results clearly indicate that VM doesn't work correctly either.

@mazesy 

> I always get `Number of pages visited in History 1` on dedicated BrowserSpy test page, script activated or not

you need to click a couple of other links on that page to increase the number of pages in your history

**Comment by mazesy** [comment]
conceal history.length and conceal windows.name indeed both do it, but here both are set to Run-At -- [Default)

Now, one thing I ignore with ViolentMonkey : does a script's setting pane prevail on the script's settings (when available) or not? I mean, if the script itself states // `@run-at   document-start `and if its settings pane instructs `Run-At (Default) ` will the script be ran at document-start in this example? I guess it will.

**Comment by mazesy** [comment]
@earthlng ,

> you need to click a couple of other links on that page to increase the number of pages in your history

I had done that, aware. Opened several other tabs, reloaded BrowserSpy, Always got **1**
That's why I was puzzled...

**Comment by earthlng** [comment]
> Opened several other tabs

that doesn't work. history is per tab, you need to open a couple of links in the **same tab**.

**Comment by atomGit** [comment]
if there's any chance these scripts will be modified at some point, i might suggest adding the update URL param to them and host them in an appropriate repo

> Wiki can hold two versions, a legacy GM version and a 57+ VM version

far as updating scripts based on browser version, i don't know if that's possible, but it sounds like there may be a need for it ... OR, can the script itself determine the browser version and run the appropriate code maybe???

**Comment by mazesy** [comment]
> that doesn't work. history is per tab, you need to open a couple of links in the same tab

Oh, right. Gosh, so logic... testing ...

**Comment by Thorin-Oakenpants** [comment]
> your test results clearly indicate that VM doesn't work correctly either

Say what? On VM, with run @ document start, I just showed the two tests work, as does the new one. The only one failing out of all four is clear window.opener.

**Comment by Thorin-Oakenpants** [comment]
Tom - make them run @ doc start. Default (from some quick searches) seems to be run at document end, meaning that as soon as the initial HTML document is ready, the script may be executed. I am not an expert, but content scripts can already be done and dusted before that, so user scripts can in those cases, not work.

**Comment by mazesy** [comment]
@Thorin-Oakenpants , doesn't change anything:
If ViolentMonkey / script / settings states Run-At (Default) then the default is, I presumed, that indicated in the script itself. I read you when you write  

> Default (from some quick searches) seems to be run at document end

Nevertheless, as I wrote above, even if I enforce Clear window.opener / settings / Run-At bocument-star, the script remains inefficient.

**Comment by Thorin-Oakenpants** [comment]
> If ViolentMonkey / script / settings states Run-At (Default) then the default is, I presumed, that indicated in the script itself. I read you when you write

Look at the settings tab - some options have "include original" - meaning the comments in the script. Run-at does not have one. Hence it defaults to DEFAULT

**Comment by mazesy** [comment]
> Look at the settings tab - some options have "include original" - meaning the comments in the script. Run-at does not have one. Hence it defaults to DEFAULT

'Keep Original' it is, OK, but it's explicit. Concerning Run-At my belief is that {Default) is the script's default if stated by the script and perhaps at document-end otherwise considering what you wrote above.

**Comment by Thorin-Oakenpants** [comment]
I really don't care if VM "imports" the setting when you first save it or not, or what default means exactly (I have no such line in my script, and yet I can set it as default - so CLEARLY this is not a setting read from the script). This is just muddying the waters. For the last time, just use doc start

**Comment by Thorin-Oakenpants** [comment]
Case in point: change `Conceal history.length` to run-at-default. Now test it. It FAILS. use doc-start!!!!!!!

**Comment by mazesy** [comment]
I have` Conceal history.length` with settings = Run-At (Default) and it works...

**Comment by Thorin-Oakenpants** [comment]
VM may be smart enough to read a script setting. I HAVE NONE in my script. you may have. Paste your script

**Comment by mazesy** [comment]
Surprise with Conceal history.length: 
I've changed the script's itself to:` // @run-at      document-end`
I've changed in ViolentMonkey, the script's / Settings to `Run-At - document-end`
I open BrowserSpy's test page... and the script runs perfectly!

**Comment by Thorin-Oakenpants** [comment]
I have nothing in the script. I changed it to run-at-end and it FAILS.

**Comment by Thorin-Oakenpants** [comment]
What does that mean. What FF version are you doing this all on?

**Comment by mazesy** [comment]
Firefox 52.0.2 ... x64 ... no more I'm aware of :=)

**Comment by Thorin-Oakenpants** [comment]
Well FFS ... no wonder. You're using a 7 version OLD release (in terms of features, not security updates). FFS!! `what a waste of time`, comapring apples to oranges. We KNOW the legacy version of GM and the scripts work. This is ALL ABOUT 57+ and web extensions (seems to fail in GM but work in VM except that one script which I am sure can be fixed if earthlng wants to, otherwise we can point to the new script or use an extension).

**Comment by mazesy** [comment]
@Thorin-Oakenpants , I'm missing something: what's this 7 version old have to do here?  corrected: I'm running anr running these tests on Firefox 59.0.2 64-BIT.
Ouf!

**Comment by Thorin-Oakenpants** [comment]
In fact 52.0.2 isn;t even the latest ESR

2017-03-07: 52.0 - over a year old

**Comment by mazesy** [comment]
It's not 52, it's 59; me have mistaked numbers!

**Comment by Thorin-Oakenpants** [comment]
>  I'm running anr running these tests on Firefox 59.0.2 64-BIT.

Then why did you say you were doing it on 52.0.2. I give up

**Comment by mazesy** [comment]
Because I typed wrong, I had the 2 from Firefox 59.0.2 in mind, I guess!
Don't give up!

**Comment by Thorin-Oakenpants** [comment]
This sticky has become a massive useless thread now on a side issue of how VM uses run-at. END of STORY - use doc-start. I don't care HOW yu do it. Its on you.

What we need to do it decide if earthlngs script can be changed to work on 57+ VM, or we just go with the new one, or point to an extension (there are several from memory), and edit the wiki accordingly.

**Comment by Thorin-Oakenpants** [comment]
And in order to move forward, we just need earthlng to decide what he wants to do

**Comment by mazesy** [comment]
@Thorin-Oakenpants it's getting late, indeed (in EU anyway).

As I said above,

-` Conceal history.length` : no problem
- `Conceal window.name` : no problem
- `Clear window.opener` : problem

There's one problem and one only: `Clear window.opener `ran with _ViolentMonkey 29.1_ on _Firefox 59.0.2 (x64)_ and maybe in other configurations.

I'm off to bed. Sleep well, sweet dreams.

**Comment by Thorin-Oakenpants** [comment]
> There's one problem and one only: `Clear window.opener` ran with ViolentMonkey 29.1 on Firefox 59.0.2 (x64) and maybe in other configurations.

No. VM stable is currently 2.9.1 (or 29.1 in your typo) and the script DOES NOT WORK (on 59.0.2). It does not `ran`. That's the whole reason you brought it up.

**Comment by earthlng** [comment]
apparently, without looking at the code, just based on your test results, VM uses a different way to inject the scripts and that's why the user-scripts work in their current form. However that method comes with a different set of problems. For example I'm pretty sure the window.opener script doesn't work because the demo page is hosted on a domain with strict CSP rules. That means you can't rely on your user-scripts to work on potentially malicious pages, at all.
I can think of at least 1 other problem but won't bother you with the details.

re: the 2 different scripts: noopener_by_default works by modifying the links on the original page, while "my" user-script works on the "new" page.

noopener_by_default has several issues (1) it's less efficient because it modifies all links targeting a new tab, (2) can easily be tricked to not modify a malicious link, (3) and maybe most importantly, it doesn't clear window.opener when a page uses window.open(). There might be other problems as well, fe. a form can also have target=_blank and it's possible that a page opened that way could also have access to window.opener. If it does then noopener_by_default does nothing against that, either. It can also break a page because adding rel=noopener to a link apparently opens the page without the referer header.
The script in the wiki has none of these problems because it works on the "new" page.

**Comment by Thorin-Oakenpants** [comment]
new issue opened. It may be we recommend an extension

**Comment by mazesy** [comment]
@Thorin-Oakenpants 

> No. VM stable is currently 2.9.1 (or 29.1 in your typo) and the script DOES NOT WORK (on 59.0.2). It does not ran. That's the whole reason you brought it up.

What's this useless nagging? Of course it's VM 2.9.1, of course I meant _There's one problem and one only: `Clear window.opener` **when run  with** ViolentMonkey 29.1 on Firefox 59.0.2 (x64) and maybe in other configurations, and run-at may not be the culprit..._, the whole context of the thread makes it obvious! If we start focusing on typos and grammar we're loosing time, Pants.

I brought up this issue, indeed, which makes my typos and language issues irrelevant.

@earthlng ,
OK, looks like indeed the script manager (VirtualMonkey) influences the way a script is deployed.
I reported the issue, it is acknowledged and reveals a deeper problematic. From there on what's to be done is above my skills.

**Comment by Thorin-Oakenpants** [comment]
> What's this useless nagging?

Wot. That was to clarify so there was no more misunderstanding. You're reading too much into what is just TEXT (which does not emote well). Nothing was meant by it

**Comment by mazesy** [comment]
> That was to clarify so there was no more misunderstanding. 

Everyone, anyone having read the thread understood what I meant. It was late, for us all. Further emphasizing would bring this very comment useless as well. Let's stay focused on the scripts and on what appears to be a ViolentMonkey interference.

**Comment by Thorin-Oakenpants** [comment]
> Further emphasizing would bring this very comment useless as well

Then stop going on about it

> Let's stay focused on the scripts and on what appears to be a ViolentMonkey interference.

Wot. I am trying, and always do, try to stay on target. And this is NOT a VM "interference" - that's just ignorance on how shit works (but I am not an expert either, and I get that english is not your native language). I'm 2/3rds into a beersies session, about to call some hookers and cocaine, so read into all that what you want.

**Comment by mazesy** [comment]
> Then stop going on about it

Who started dabbing?
I don't read into people, your personal life is neither of my concern nor of my curiosity. Remains the fact you become picky quite easily when other times you are the most sympathetic person I can imagine; fortunately the latter compensates the former.

**Comment by Thorin-Oakenpants** [comment]
> Who started dabbing?

You did. Drop it. Don;t reply unless it is to do with business in hand, My tolerance right now is very low. I appreciate you input at times, other times it is very trying (put that down to language or whatever, I know your intentions are "pure"). Thank you for the info on the script not working, that was never in question. Any more of this and I will just block you (yeah nasty to here huh, I DO NOT WANT to do this). You're constantly off topic, but I value you. Leave it at that. Stay and contribute (with a bit of fun, always), but FFS stay on topic if you can (yes I'm a hypocrite at times)

@mazesy :kiss: lobe you dude, but for some reason you rub me the wrong way a bit of the time. Adapt.

**Comment by mazesy** [comment]
> Any more of this and I will just block you
A threat as a last resource. Well just do it then. 

> for some reason you rub me the wrong way a bit of the time

You rub as well, and not only me.

Calm down or block, it's up to you. But I never adapt to threats and, should I be forgotten here that I'd forget it as quickly. Think about it.

**Comment by crssi** [comment]
@earthlng, could you take a look at this please https://github.com/ghacksuserjs/ghacks-user.js/issues/401#issuecomment-382205775
Thank you so much
Cheers

**Comment by Thorin-Oakenpants** [comment]
Wiki page now asks for further submissions on scripts to be a new issue. This sticky is over!

**Comment by Thorin-Oakenpants** [comment]
@mazesy Your 24 hr block is now lifted. You're welcome to contribute etc, that's up to you. Just don't come into *my house* and attack *my integrity* - WTF did you think would happen?
