### ISSUE TITLE
discussion: do we need a relaxed sticky/branch/.js ?

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#751]
After the overrides topic where users shared info, and after #605 analyzing those and making tweaks to the user.js, and adding in items to consider from the troubleshooter....

here are some stats as of right now

```
excluding personal and deprecated, and parrots

249 active
113 inactive (10 are active in RFP ALTs which is an inactive section)
===
362 total

249 active
 15 active enforced at default
===
234 pref changes (at most)

^^ covered by 42 [SETUP* tags
 1 [SETUP-SECURITY]: SB binary checks
 5 [SETUP-PERF]: AltSvc, cache, SSL Session IDs, asm.js, wasm
14 [SETUP-CHROME]
18 [SETUP-WEB]
 3 [SETUP-HARDEN] HWA, MathML, "open with"
 1 [SETUP-non-RFP]
```

234 pref changes are obviously going to cause surprises / breakage: and everyone has different needs / threat models / etc blah blah blah.

I have always thought that the vast bulk of these prefs make no discernible (i.e noticeable) difference. See the last release where pref changes were trimmed down from around 300 to 234, with no change in affect.

And while one pref !== one setup tag, I feel the `14 chrome` and `18 web` tags **are enough** of a gimme for users to know WTF they need to relax to suit them. Additionally, maintaining yet another item regardless of it's form (branch, sticky issue, user-relaxed.js) is not something I really want to do.

Class! Discuss.

Feel free to show your vote (non-binding: its just to get an indication and save me counting)
- :+1: to provide a relaxed list/branch/whatever
- :-1: to leave as is: `[setup` tags are enough
- :beer: pants deserves a beer

**Comment by Just-me-ghacks** [comment]
I don't think we need a relaxed user.js config. The amount of breakage is negligible anyway. Leaving a comment / tag if a certain pref causes breakage should be more than enough for anyone interested.

**Comment by Thorin-Oakenpants** [comment]
That's what I was thinking: because all a relaxed one would be is a the same but a bunch of prefs that have setup tags made inactive (or listed as an overrides.js or listed in a sticky) = **redundant** and more maintenance.

> The amount of breakage is negligible anyway

Well, I agree. Looking at website breakage, in the scope of flipping 230+ prefs, it's SFA (sweet F all).

PS: edited my first post with instructions of how to indicate what you feel with emojis

**Comment by claustromaniac** [comment]
> discussion: do we need a relaxed sticky/branch/.js ?

No, we never **needed** one. Is that a subtle attempt at affecting the outcome of the discussion? :trollface: The questions should be if it would be worthwhile and if we want one or not.

Anyway, what you did with the tags is great. You deserve a barrel of your favorite beer, IMO.

**Comment by Thorin-Oakenpants** [comment]
beersies is always my preferred method of payment and thanks

**Comment by KOLANICH** [comment]
IMHO: we need a pair of WebExtensions. One is a WebEdtension Experiment creating WebExtension API to access about:config. Another one is an addon mapping about:config prefs to GUI widgets, allowing users to apply presets and downloading and updating lists of presets. It should also keep an own copy of about:config entries changed for the case of sabotage from Mozilla side like unsetting prefs on browser update.

**Comment by claustromaniac** [comment]
> a WebEdtension Experiment creating WebExtension API to access about:config

In a best-case scenario that would be hard to install (not user-friendly). Unless you're talking about forking Firefox (but that would be hard to maintain).

With the existing APIs something like that should already be possible though. The [runtime API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime) has functions that allow extensions to talk to native applications. One would have to write a cross-platform command-line application that writes to `user.js` and/or `user-overrides.js`, and then use those functions to communicate with it. 

The changes wouldn't take effect immediately, though. In that case, it would make more sense to just write an external UI for this `user.js` and leave it at that. No need for an extension.

Anyway, just sharing some thoughts. Realistically, I can't afford the time for that ATM. My platter is already overflowing with less than a handful of small projects to maintain. If anyone is willing to start such a project, I'm sure people will flock to it in no time, though.

**Comment by Thorin-Oakenpants** [comment]
OT: https://www.fastcompany.com/90369697/googles-new-recaptcha-has-a-dark-side

**Comment by KOLANICH** [comment]
>that would be hard to install

Should not be harder than installing 2 XPIs (order matters, first the one providing the API, second the one using it), if one is using Firefox editions allowing experiments (devedition and nightly). A webext passing about:config seems to be quite easy to implement, the main complexity is in the webext doing GUI.

Native messagging has the drawbacks you have mentioned.

**Comment by claustromaniac** [comment]
@Thorin-Oakenpants 
... Google could really use some Jesus https://invidio.us/watch?v=YA1ROa_-zgc

@KOLANICH 

> find an XPCOM API doing the stuff and wrap it into WebExt promise-oriented API

Is there any simple way to use XPCOM in beta? Anyway, the `user.js` targets stable, not beta. Even if it did target beta, users would have to install beta and load their profile from there: it still wouldn't be intuitive, which would kinda defeat the purpose of making things more newbie-friendly IMO.

**Comment by KOLANICH** [comment]
>Is there any simple way to use XPCOM in beta? 

the docs mentions nightly and devedition.

>Anyway, the user.js targets stable, not beta.

As I know, stable ff in linux distros allows disabling extensions signature check. I wonder if it is possible to enable webext experiments support there too.

**Comment by Thorin-Oakenpants** [comment]
so ... 6 to 1 so far ... seems legit
