### ISSUE TITLE
visted link color

### ISSUE THREAD

**Issue by y0y0z** [ghacksuserjs/ghacks-user.js#752]
i provided my `user-overrides.js` to restore previous session and it works for me. yet, there is something which i was not able to tweak ---- how to color a visited link.

skipping STR step 2 (see blow), i am able to color a visited link.

- browser version: firefox 67.0.4 (64-bit)
- steps to reproduce (STR):
1. fresh installation of firefox
2. install `ghacks user.js`
3. install [vistedlinkenabler][1]
4. open [duckduckgo.com][2] and search for something
5. visit any search result
6. navigate back to the search result
- actual result: the search result, which was picked in STR step 5, is not colored
- expected result: the same result, which was picked in STR step 5, to be colored

[1]: https://addons.mozilla.org/en-US/firefox/addon/visited-link-enabler/
[2]: duckduckgo.com

would appreciate your assistance.

**Comment by claustromaniac** [comment]
Hello there.

The culprit is `0805`
```js
/* 0805: disable CSS querying page history - CSS history leak
 * [NOTE] This has NEVER been fully "resolved": in Mozilla/docs it is stated it's
 * only in 'certain circumstances', also see latest comments in [2]
 * [TEST] http://lcamtuf.coredump.cx/yahh/ (see github wiki APPENDIX C on how to use)
 * [1] https://dbaron.org/mozilla/visited-privacy
 * [2] https://bugzilla.mozilla.org/147777
 * [3] https://developer.mozilla.org/docs/Web/CSS/Privacy_and_the_:visited_selector ***/
user_pref("layout.css.visited_links_enabled", false);
```
Add this line to your overrides and try again:
```js
user_pref("layout.css.visited_links_enabled", true);
```

**Comment by y0y0z** [comment]
@claustromaniac: *THANK YOU!*

**Comment by Thorin-Oakenpants** [comment]
FPI to the rescue ... one day .... waiting .... https://bugzilla.mozilla.org/show_bug.cgi?id=1398414
