### ISSUE TITLE
PSA: Very weird issue with IPV6 and php local server :omg:

### ISSUE THREAD

**Issue by GIPeon** [ghacksuserjs/ghacks-user.js#757]
Hei there, this PSA is for any PHP fiddler out there. Many times I fire up a PHP local server via CLI just to test few things. I got stuck on firefox without a damn clue on why it wasn't able to reach the localhost address, with a very helpful and super detailed "server not found" error. 

After quite a bit of digging I found [this](https://www.php.net/manual/en/features.commandline.webserver.php#120449):

>I painfully experienced behaviour that I can't seem to find documented here so I wanted to save everyone from repeating my mistake by giving the following heads up:
>
>When starting php -S on a mac (in my case macOS Sierra) to host a local server, I had trouble with connecting from legacy Java.
>
>As it turned out, if you started the php server with
>"php -S localhost:80"
>the server will be started with ipv6 support only!
>
>To access it via ipv4, you need to change the start up command like so:
>"php -S 127.0.0.1:80"
>which starts server in ipv4 mode only.

Can't really thank and upvote this guy enough. So with:

    network.dns.disableIPv6: true

you can't reach a PHP local server fired with a `localhost` address.  

This is really more a PHP quirk than a user.js stuff, but maybe this can be a handy reminder for someone who is in php programming or similar (for ex. the python server was fine and dandy with no IPV6, I should check node...).

**Comment by Thorin-Oakenpants** [comment]
thanks for the info:
