### ISSUE TITLE
request: Mac Tor Browser 8.5* or 9.* user

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#758]
Hey guys and gals

Could someone running an up-to-date Tor Browser (stable or alpha) on **Mac** please paste me the value of `font.system.whitelist` - TIA :heart:

**Comment by aesthicc** [comment]
AppleGothic, Apple Color Emoji, Arial, Courier, Geneva, Georgia, Heiti TC, Helvetica, Helvetica Neue, .Helvetica Neue DeskInterface, Hiragino Kaku Gothic ProN, Lucida Grande, Monaco, Noto Sans Armenian, Noto Sans Bengali, Noto Sans Buginese, Noto Sans Canadian Aboriginal, Noto Sans Cherokee, Noto Sans Devanagari, Noto Sans Ethiopic, Noto Sans Gujarati, Noto Sans Gurmukhi, Noto Sans Kannada, Noto Sans Khmer, Noto Sans Lao, Noto Sans Malayalam, Noto Sans Mongolian, Noto Sans Myanmar, Noto Sans Oriya, Noto Sans Sinhala, Noto Sans Tamil, Noto Sans Telugu, Noto Sans Thaana, Noto Sans Tibetan, Noto Sans Yi, STHeiti, STIX Math, Tahoma, Thonburi, Times, Times New Roman, Verdana

**Comment by Thorin-Oakenpants** [comment]
Thanks :kiss:

**Comment by bitpixl** [comment]
@Thorin-Oakenpants for future use, go to "[Default Preferences, Tor Browser Bundle page](https://gitweb.torproject.org/tor-browser.git/tree/browser/app/profile/000-tor-browser.js?h=tor-browser-60.8.0esr-9.0-1), select the latest version from the top right menu and press "switch". After that scroll down (to the 
#ifdef MOZ_BUNDLED_FONTS part) or just search for "font.system.whitelist".

**Comment by Thorin-Oakenpants** [comment]
Thanks guys
