### ISSUE TITLE
0864 is patched in FF68

### ISSUE THREAD

**Issue by Aeriem** [ghacksuserjs/ghacks-user.js#759]
Preference 0864 was patched in FF68 to respect RFP: https://bugzilla.mozilla.org/show_bug.cgi?id=1492587

Sorry for the new issue, #20 is locked so I couldn't remind you there.

I'll be posting a PR shortly and update this post accordingly.

EDIT: My PR: #760

**Comment by earthlng** [comment]
Thanks for bringing this to our attention and thanks for the PR! 👍 
We'll discuss and deal with it in the PR so I'm closing this. Thanks mate!

**Comment by Aeriem** [comment]
Oh, didn't see your comment here. Forgot to check my notifications.
I'm glad I could be of assistance, thank you for the continued work on this repo. 😄

**Comment by Aeriem** [comment]
Off-topic: BRUH!
I just realised I'm now a "contributor" to this repo since my PR got merged.
@claustromaniac, the creepy stalker is finally coming out of the shadows!

**Comment by claustromaniac** [comment]
Congrats.

I went from nothing to collaborator, then to owner, and *then* to contributor. Looks like I may end up taking your place as a stalker at this rate.

**Comment by Aeriem** [comment]
Don't worry, we'll take good care of you, in the shadows. 😈

**Comment by Thorin-Oakenpants** [comment]
>  then to owner, and then to contributor

Yeah, what's up with that? Where did the three amigos go? -> https://github.com/orgs/ghacksuserjs/people  <- did you demote yourself?

**Comment by claustromaniac** [comment]
> Don't worry, we'll take good care of you, in the shadows. 😈

That's... creepy. \*hides in da box\* Wait... I was already there. NVM

> did you demote yourself?

I left the organization. I had been hiding my "rank" from non-members for some time anyway (I set it to *private*); most people won't notice the difference.
