### ISSUE TITLE
FYI: When WebDriver session is active inline scripts are not blocked

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#762]
It turns out that selenium does some about:config modifications, like disabling browser security features.
More precisely, it sets `security.csp.enable` into False.

**Comment by claustromaniac** [comment]
1f y0u2 1n73n710n w45 ju57 70 m4k3 7h15 1355 5342ch4813, why n07 3nc0d3 7h3 519n1f1c4n7 p4275 1n 845364 02 h3x 1n5734d 0f 1337?

17 w0u1d 83 1355 c2yp71c.
