### ISSUE TITLE
noopener

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#765]
@earthlng 

`dom.targetBlankNoOpener.enabled` = true, as per user.js
`dom.noopener.newprocess.enabled` = true (default)
I have E's extension

At https://mathiasbynens.github.io/rel-noopener/ there are five yellow boxes with links. I swear on my luscious beard, that all five links used to report the same result .. but now the second link says "Why don’t you go back to the previous tab?" instead of "The previous tab is safe and intact..." like the others

What am I missing here? 🕵️‍♀️

**Comment by earthlng** [comment]
you probably didn't allow JS on https://mathiasbynens.be/ ?

**Comment by Thorin-Oakenpants** [comment]
Yes, I did allow JS

**Comment by earthlng** [comment]
because the other 4 are on mathiasbynens.**github.io**, not mathiasbynens.**be**

the last 3 are not vulnerable anyway, they're there to show devs ways to prevent the issue

**Comment by Thorin-Oakenpants** [comment]
Ahh .. good. That's why I pay you the big bucks: for when I miss things 💋
