### ISSUE TITLE
Youtube missing controls.

### ISSUE THREAD

**Issue by ZongMan** [ghacksuserjs/ghacks-user.js#77]
Do you know what section in the user.js would cause the player controls YouTube to break or become missing>

**Comment by ZongMan** [comment]
/* 2671: disable in-content SVG (Scalable Vector Graphics) (FF53+)
 * [WARNING] SVG is fairly common (~15% of the top 10K sites), so will cause some breakage
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1216893 ***/
user_pref("svg.disabled", true);  set to false fixes it.
END

**Comment by earthlng** [comment]
Thank you for the report

**Comment by crssi** [comment]
@ZongMan, but I have `user_pref("svg.disabled", true); ` and I can't reproduce your problem. Here everything is OK.
Are you sure there is not some other extension you are using that blocks those icon and enabling svg just resolves your specific configuration problem?
I am using FF 52.0.2 x64

**Comment by earthlng** [comment]
@crssi that pref is only doing something in FF53+

**Comment by crssi** [comment]
OK @earthlng  but @ZongMan  didn't say nothing about the version of FF he is using.

**Comment by ZongMan** [comment]
Sorry for the confussion this all occurs on FirefoxDev 54 .oa2 portable
clean the install and my nodded. User.is install . I'm sure you can even
try it for yourself right now just get it from the portable apps website
and install. Switch that one pref and you will get my problem. Maybe its
just me then and my user.js config? Funny it alo worked up until the 30th
of last month.

**Comment by earthlng** [comment]
Just tested in FF55 nightly and can confirm `svg.disabled=true` breaks youtube

**Comment by ZongMan** [comment]
https://github.com/earthlng  I thought as much i wasn't going crazy was man......

**Comment by earthlng** [comment]
https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%20Developer%20Portable/

older versions are still there but they're "online" installers and idk if the older versions download and install older versions of FF or if it's always the latest DevEdition. It's the same for nightly portable btw.

**Comment by ZongMan** [comment]
https://imgur.com/a/RMTyT they dont install even with Admin privileges tested on FirefoxPortableDeveloper_53.0_Alpha_2_English_online.paf .  Its cool knew it wouldn't but just to test it.
 
So i guess you will be adding a notation to the master user.js about main issue though for the SVG pref. 
We can button this thread up now, we know what issue i was having and how to solve it. Thanks for your support and getting back to me even after i closed the thread sorry i was more specific from the get.

**Comment by earthlng** [comment]
ok, thanks. maybe the dev edition is special. the nightly setup I have, downloads 
archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-55.0a1.en-US.win32.installer.exe +
archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-55.0a1.en-US.win64.installer.exe
into a randomly named subfolder of the temp directory (with some other portable-specific stuff, so easy to find) fe. nsdABC1.tmp/Downloaded for the 32bit and /Downloaded-2 for the 64bit.
So I assumed it may be possible to put the files in there manually but the archive.mozilla.org/pub doesn't list any DevEdition so maybe this would only work for nightly portable-app "online" setups.

**Comment by Thorin-Oakenpants** [comment]
FYI: https://github.com/pyllyukko/user.js/issues/305 - uBo element picker also uses inline-SVG
