### ISSUE TITLE
Firefox extension merging ghacksuserjs into about:config

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#771]
https://github.com/KOLANICH/webext-experiment-config

**Comment by KOLANICH** [comment]
P.S. There are lot of bugs in WebExtensions experiment subsystem of firefox. For example tonns of time have been spent on undocumented bugs such as `get` name is unsupported and problems when importing 2 experiments into a single addon.

**Comment by KOLANICH** [comment]
ToDo:
1. implement counter in a background script
2. implement subscribtions manager addon
3. implement auto update
4. implement parsing of comments
5. gui looks terrible

**Comment by crssi** [comment]
That is so cool. I have been thinking about the same stuff for a quite long time now, but I lack of programming experience. That is why I have started recently with simpler webextension, which is already on AMO.

I would like to try this out, but obviously I do not understand the right procedure.
I did make `experiment` xpi and install, then `extension` xpi and install.
I get the Action icon in FF, but click on it doesn't do anything.

What did I miss?

Cheers

**Comment by KOLANICH** [comment]
1. download the latest nightly. It seems that mozilla doesn't test this feature ~~at all~~ at anything but nightly. Currently it works on devedition, but some weeks ago all the experiment were broken on devedition and when I have opened a bug on bugzilla, mozilla employee has tested on nightly and on nightly everything was warking for him.

So this feature periodically breaks.

So what is your browser version?

2. you can also try to go to about:debugging and tap into addon's JS console. console.log was broken in nightly in such consoles today, in the sense that its output was going not to the extension console but into browser global console.

When you are in the second extension console, you can try to call the experimental api from it directly. Please note that all the api is promise-based, so you need `.then(e => console.log(e))` to print

**Comment by Thorin-Oakenpants** [comment]
not sure what I'm supposed to do with this

**Comment by KOLANICH** [comment]
I have updated the extension to make it work with the latest DevEdition. Also implemented downloading of the user.js from this repo automatically.

**Comment by crssi** [comment]
Is there any ETA for when this would work on release edition and not only dev?

**Comment by rusty-snake** [comment]
WebExtensions API experiment are only supported in DevEdition (and Nightly???). Mozilla will likely never implement it to release or add a about:config API to release.

**Comment by KOLANICH** [comment]
I want to persuade linux distros to build with MOZ_DEV_EDITION flag, allowing WebExts experiments. They already allow unsigned exts, IMHO they should go further.  Mozilla is not currently in position to insist on not having this pref. And even if they insisted, IceWeasel branding can be revived.
