### ISSUE TITLE
Firefox may stop reading user.js unles about:config pref is set...

### ISSUE THREAD

**Issue by gwarser** [ghacksuserjs/ghacks-user.js#780]
https://blog.nightly.mozilla.org/2019/08/30/these-weeks-in-firefox-issue-63/

>Mandy has a patch up to avoid doing more main-thread IO during start-up, **and also has her eyes set on one other bug before her internship closes out**

https://bugzilla.mozilla.org/show_bug.cgi?id=1543752

"Stop reading user.js from the profile to modify default prefs unless prefs.js opts in to doing so"

***

ghacks-user.js is niche and not updated by 2 years :)

**Comment by Thorin-Oakenpants** [comment]
I'm not fazed by this: as long as they don't disable it entirely, or move to app rather than profile.

**Comment by Thorin-Oakenpants** [comment]
We'll pick up on this with diffs, and/or notice when shit breaks (unlikely as it will become set as modified for you if you use a user.js), or watch the ticket :) When it lands, I will modify the wiki
