### ISSUE TITLE
0370: pocket -> 5000s

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#787]
currently
```js
/* 0370: disable Pocket [FF46+]
 * Pocket is a third party (now owned by Mozilla) "save for later" cloud service
 * [1] https://en.wikipedia.org/wiki/Pocket_(application)
 * [2] https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/ ***/
user_pref("extensions.pocket.enabled", false);
```

The [2] reference does not exist (and is probably out of date)

Note: The pref only directly applies to the pocket service, **not AS suggestions and sponsored stories**: see  [DXR here](https://dxr.mozilla.org/mozilla-central/search?q=pocket.enabled&redirect=false)

It's under the `quiet fox` section: but does it actually make any outbound calls if not used? I'm pretty sure it doesn't (but could be wrong). Even if it did do an occasional call, there is no PII involved (and don't say IP address: if that's your concern then fix the underlying problem instead of screaming about symptoms). For all intents and purposes, this pref is only about visuals. Some people might like Pocket, and this would just be another pref they have to flip to unbreak things. On the flip-side, a lot of us would have to add an override :) Still, my argument stands

Note: Users can also just hide the icon in the urlbar, right-click remove (not sure if that also hides context and library menus). And we'll still have the pref in the user.js for reference.

Class, discuss! Change my mind!

**Comment by Just-me-ghacks** [comment]
`user_pref("extensions.pocket.enabled", false);` remains as it is here. No icon in the urlbar either.

OFFTOPIC - Microsoft, please stop this "verify your device" bullsh*t during github login.

**Comment by Thorin-Oakenpants** [comment]
Well, that's your personal choice (mine too), to not have the icon or library or context menu items showing .. but not a valid argument to disable it **by default** in the **template**

**Comment by claustromaniac** [comment]
> does it actually make any outbound calls if not used? I'm pretty sure it doesn't

Not here. Tested on FF70.0b4.

This no longer belongs in section `0300`, IMO.

**Comment by Thorin-Oakenpants** [comment]
> Users can also just hide the icon in the urlbar, right-click remove (not sure if that also hides context and library menus)

Removing the icon in the urlbar, still leaves the empty`View Pocket List` in the library, clicking it send you to a pocket webpage. Likewise the web page context menu item is still available. Just thought I would clarify that. Using the pref removes all of that.

![context](https://user-images.githubusercontent.com/16656956/64471269-f891e800-d13e-11e9-8a18-217949c1ca84.png)
![library](https://user-images.githubusercontent.com/16656956/64471270-faf44200-d13e-11e9-800d-020cdd180c12.png)

**Comment by earthlng** [comment]
really??? enabling one of the most hated features in Firefox? so now ~99.9% of our users will have to add another override?!

If it doesn't fit in `0300` anymore, just move it somewhere where it'll still be active by default fe. MISC

**Comment by Thorin-Oakenpants** [comment]
It somewhere else, because it doesn't have any privacy, tracking, security issues by default. I'm not saying that there aren't others that fit this criteria either, so please don't point at them and say "but..." (however, feel free to point them out so I can move them as well).

The `personal` section is where it belongs. When we start arbitrarily deciding personal decisions for others, we start to lose credibility: that's why everything in personal is inactive.
