### ISSUE TITLE
corroborator.enabled

### ISSUE THREAD

**Issue by tartpvule** [ghacksuserjs/ghacks-user.js#791]
I saw this mentioned in https://github.com/ghacksuserjs/ghacks-user.js/issues/743, but no discussion anywhere.

I propose adding `corroborator.enabled` to ghacks-user.js.
- It is defaulted false for RELEASE_OR_BETA. (https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#1932)
- "Check bundled omni JARs for corruption" means verifying the signature of onmi.jar. (https://dxr.mozilla.org/mozilla-central/source/toolkit/components/corroborator/Corroborate.jsm#52). People who modify their omni.jar (e.g. to change some jsm files) would trip this.
- The pref is checked for here in the source code: https://dxr.mozilla.org/mozilla-central/source/browser/components/BrowserGlue.jsm#2127
- Discussions in https://bugzilla.mozilla.org/show_bug.cgi?id=1533818 suggest it would be defaulted true in the future.

**Comment by Thorin-Oakenpants** [comment]
IDK. Modifying omni.jar seems very niche to me, and I don't really want to add this: it's just clutter. We can always review it again in diffs when it gets flipped, but I am loathe to

If @earthlng has anything to add, then re-open it as required
