### ISSUE TITLE
CORS errors ruining browsing experience

### ISSUE THREAD

**Issue by privacyguy123** [ghacksuserjs/ghacks-user.js#794]
Latest FIreFox, latest user.js - can't get my head around it at all. Modified "security.fileuri.strict_origin_policy;false" also and still no dice. CORS errors are flooding my Console and totally lagging my browser out on some pages.

Any quick fix here?

**Comment by privacyguy123** [comment]
I guess it's addon related then - time to dig deeper.

**Comment by Thorin-Oakenpants** [comment]
let us know what it was when you find out
