### ISSUE TITLE
whatsapp web not displaying QR code

### ISSUE THREAD

**Issue by fu8765** [ghacksuserjs/ghacks-user.js#809]
web.whatsapp.com is not displaying the QR code for signing in.
haven't identified the cause yet.

**Comment by Thorin-Oakenpants** [comment]
it'll probably be RFP (or FPI) - I remember seeing a similar bugzilla

**Comment by Thorin-Oakenpants** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1446472

STR:
- nilla profile
- go to https://web.whatsapp.com/
- expected: I can see the QR code
- about:config, flip RFP
- reload the page (it actually auto removed the canvas anyway)
- QR code doesn't show

Solution:
- click on the canvas icon in the urlbar and allow canvas, reload the page

![whatsapp](https://user-images.githubusercontent.com/16656956/66252432-23298d80-e74b-11e9-84ac-c020a87d32df.png)

**Comment by Thorin-Oakenpants** [comment]
FYI: due to #783 , I checked with FPI on (and a restart), and the solution still works
