### ISSUE TITLE
FYI: search engines

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#815]
https://blog.mozilla.org/addons/2019/10/15/search-engine-add-ons-to-be-removed-from-addons-mozilla-org/

I don't use any of Mozilla's built in search engines. I added my own via some extension years ago. I used to have about 20, I pruned it down to 9. I can probably clean out another 5 before then and just bookmark the site (since I don't use them often and the sites have their own search feature).

**Comment by Thorin-Oakenpants** [comment]
Pro Tip: I check [this site](https://planet.mozilla.org/) once a day

**Comment by KOLANICH** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1486837
https://bugzilla.mozilla.org/show_bug.cgi?id=1486820
https://bugzilla.mozilla.org/show_bug.cgi?id=1567430

But these tickets are not about dropping OpenSearch completely. IMHO it is a very stupid idea to allow confusion between extensions capable running JavaScript and extensions serving as just a declarative description of search.

**Comment by Thorin-Oakenpants** [comment]
`October 21, 2019 update` [from my [original link](https://blog.mozilla.org/addons/2019/10/15/search-engine-add-ons-to-be-removed-from-addons-mozilla-org/) in OP]
> We also want to clarify that this announcement and the dates we specified only cover our plan for AMO. As long as Firefox supports OpenSearch, those features **in the browser** will remain unchanged

Such a fucking confusing post. The original content still says
> For Search Engine add-ons to continue working, they must be converted to an extension using the WebExtensions API by December 3, 2019


I have already pruned my search engines down to seven: two built in from mozilla and the other five are from the old pre-WebExtension days (via the legacy AddToSearch addon). At this stage I'm just going to assume everything will keep working **in the browser** (their words). Not sure if how I added them used OpenSearch: NFI. The point of the addon was you could add a search engine based on any site, OpenSearch or not.

**Comment by Thorin-Oakenpants** [comment]
Closing this (I hate open tickets) ... **if** and when my custom search engines like `hot.alpacas.com` stops working (don't judge me! and you try finding an extensions for that) stop working **then** I'll deal with it. I suspect **my** engines will be fine since they were never extensions to begin with

On top of that, we don't do anything here in this repo with search engines as that can be subjective (and covered to death by everyone else) and also dependent on builds/regions. It's really outsite the scope of what we can do
