### ISSUE TITLE
reminder: privacy.fuzzyfox.enabled

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#816]
- https://trac.torproject.org/projects/tor/ticket/28709
- https://bugzilla.mozilla.org/show_bug.cgi?id=1432429

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg

I'm going to flip this puppy on in my main Firefox and take it for a spin. Does fuzzyfox require a Firefox restart to take affect? How does one test if fuzzy if working?

time travel... :)
> when we first enable FuzzyFox via the pref, we use CeilToGrain to avoid time going backwards

**Comment by crssi** [comment]
If you will do it on FF 69, it will slow do FF to not being usable. 😉

**Comment by Thorin-Oakenpants** [comment]
> it will slow down FF to not being usable

Well, they're about to flip in Tor Browser - not sure which release, not the first 9.5 stable

I see one ticket for fuzzyfox issues: https://bugzilla.mozilla.org/show_bug.cgi?id=1506295

**Comment by crssi** [comment]
I was waiting for a time when I could say: I told you so.

lol ❤️

**Comment by tomrittervg** [comment]
Yeah it needs some study in the profiler - but I haven't had time to... https://profiler.firefox.com/docs/#/

**Comment by Thorin-Oakenpants** [comment]
> but I haven't had time to

you could try using `FloorToGrain` so time can move backwards /lame-jk

**Comment by Thorin-Oakenpants** [comment]
> Closing firefox left processes hung

for those who want something to track ... https://bugzilla.mozilla.org/show_bug.cgi?id=1589958
