### ISSUE TITLE
FF70 + VP9

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#819]
@Dragomir7 [said](https://github.com/ghacksuserjs/ghacks-user.js/issues/805#issuecomment-545371211)
> In version FF70, I discovered new suspicious functionality related to youtube. When user use youtube video in first time it create folder **mediacapabilities** with two files (data.mdb and lock.mdb) inside folder ******.default-release. In previous versions FF, this was not. I tested a little and found out that it is connected with youtube codec vp9 (webm). You can stop it just by switching pref **media.mediasource.webm.enabled** to false. But unfortunately after that the maximum resolution that can be selected in youtube player is 720p. I haven’t found another way to stop creating folder :( . Knowing the close collaboration of google and mozilla ...  I think it's better to find a way to disable the creation of a folder without harming the functionality of youtube.
 What do you think about this?

**Comment by Thorin-Oakenpants** [comment]
First of all, cut this out: "Knowing the close collaboration of google and mozilla" .. if you seriously believe that then you're deluded

Now down to business. We'll have to do some testing etc to confirm everything I guess. It's a shame TB didn't get this and we could lean on their results. For example they made media cache memory only and bumped up the memory space allocated for it. But first I would want to know what is in that database. Is it permanent? Is it isolated by first party? Is it session only? Etc.

Downgrading resolution isn't the answer - besides, your media capabilities fingerprint will change, and that's about 20ms of JS code to do that (and easily deployed). And neither are solutions outside of the application (such as crssi's suggestion), sure it might work but it's not universal and applied easily. What happens on Mac, on Linux, on Android etc?

And I would want to see what happens in PB mode. What happens when you block cookies. What happens when you go disk cacheless, etc.

So first: is it an actual threat? Can you bypass it by watching YT in PB mode? etc. etc. etc. If I get around to this by Xmas, I'll be doing well.

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg .. what's happening with [1436226](https://bugzilla.mozilla.org/show_bug.cgi?id=1436226) now 70 is landed? What are the FPI, disk persistence implications?

> We would hardcode it into VP9 for Windows and Linux and into VP8 for MAC and Android

**Comment by Dragomir7** [comment]
> So first: is it an actual threat?

Such a probability exists. Only youtube site create this folder. I tried several other video hosting services (even porn) and nothing. So it can be used for user identification. Notice it override master switch **media.media-capabilities.enabled**. I could be wrong and pref **media.media-capabilities.enabled;false** still work and this folder it's only an echo from override.

> Can you bypass it by watching YT in PB mode?

No. It is created anyway.

I`m always use:

**network.cookie.cookieBehavior;2**
**dom.storage.enabled;false**
**dom.indexedDB.enabled;false**

and always remove **//** from all pref in user.js

I'll try to play some more with media.cache.* prefs. Maybe help.

**Comment by Thorin-Oakenpants** [comment]
> > Can you bypass it by watching YT in PB mode?
> >
> No. It is created anyway.

Is it deleted after your PB mode session? If not, then it sounds like a PB mode bug that someone didn't think of.

> Only youtube site create this folder

OK. So other sites **could** also do this. I guess it depends on what is it in, and what Firefox allows to be put in it, etc: i.e does it pose a privacy risk?

IDK the answers, sorry. I've already pinged Tom, so Netflix and chill 😁

**Comment by Dragomir7** [comment]
> Is it deleted after your PB mode session? If not, then it sounds like a PB mode bug that someone didn't think of.

No. Folder permanent.

> OK. So other sites could also do this. I guess it depends on what is it in, and what Firefox allows to be put in it, etc: i.e does it pose a privacy risk?

IDK the answers, sorry. I've already pinged Tom, so Netflix and chill 😁

I`m sorry. I`m not using paid services like Netflix etc.

**Comment by Thorin-Oakenpants** [comment]
> Folder permanent

Right. So first things first, what is in it (and who controls it and what goes in it). For all I know, it's completely harmless and created by Firefox for diagnosis / caching speed things with no PII etc. I don't expect you to answer, and I don't have time right now: just pointing out the steps to take in the risk assessment

> not using paid services like Netflix

No need to apologize :) "Netflix and chill" is slang for something (duckduckgo it)

**Comment by Dragomir7** [comment]
Ok. Some new testing information:

Changing media.cache.* has no effect. Folder still creating after video starting.

If disable ALL webm in browser and enable mp4 instead, youtube create folder. But others video hostings sites which use mp4 codec not create this folder. Why is that? Why youtube video player can create this folder but others are not allowed? Where do such privileges come from and why are they generally given exclusively youtube player? Too suspicious.

**Comment by Thorin-Oakenpants** [comment]
Using my nightly 72, I loaded up youtube and opened a vp9 video and hit HD for 1080. This is not a totally scientific test, as I forgot to filter for all files while watching, and missed what happened when I first started the HD video. Two files were modified, both definitely on close (not sure if relevant, but I have everything set to clear on close: everything)

![mdb-files](https://user-images.githubusercontent.com/16656956/67480881-48296600-f650-11e9-9493-54ef6d9d88cc.png)

We can ignore the lock files. Looking at the mdb databases we have
- `security_state`
- `notification_store`
- `xulstore`
- `mediacapabilities`

Wonder what stuff gets packed into these files. I'm going to guess there is zero privacy concern, and these are normal files used by FF internally. Might try and have a peek in them

**Comment by Thorin-Oakenpants** [comment]
1. Websites cannot access this info: the directories and permissions are out of scope etc
2. see [15779760](https://bugzilla.mozilla.org/show_bug.cgi?id=15779760) as an example of twitter also triggering mediacapabilities/data.mdb writes - i.e it is not website driven, it is content driven and controlled by Firefox

Closing all of this as a waste of my time

**Comment by KOLANICH** [comment]
>data.mdb
>lock.mdb

The filenames look like the files are used by either BerkleyDB (a legacy embedded DB used for example in rpm) and its fork LMDB (an extremily fast key-value database used in highload services). IDK what is the reasons to use them in a video codec.  I personally don't watch youtube in browser, so I cannot check. But you may want to try to open these files with the databases, they have python bindings. You may also want to try to search dxr and the codec source code for usage of these dbs.

**Comment by Thorin-Oakenpants** [comment]
https://www.ghacks.net/2019/10/22/firefox-70-0-release-information/#comment-4442555
- `media.mediacapabilities.from-database` = `false`

Well at least we can find the ticket now we have a pref and find out whats stored in there. When I say "we", I meant anyone else who is interested

**Comment by KOLANICH** [comment]
Thanks.

**Comment by theWalkingDuck** [comment]
`media.mediacapabilities.from-database = false`


Has anyone tested this on Linux ?
It dosen't work for me.

- I set the pref to  `false`
- deleted the mediacapabilities directory
- restarted firefox.

but it gets created 
Did I miss something ?
