### ISSUE TITLE
How to disable these newish Firefox features?

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#820]
Are these prefs enough to _completely disable_ the features that I don't want?

**1. How to disable "Show alerts about passwords for breached websites"?**
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.enabled", false);

**2. How to disable "Suggest and generate strong passwords"?**
user_pref("signon.generation.enabled", false);

**3. How to disable Tracking Protection - Cryptominers?**
user_pref("privacy.trackingprotection.cryptomining.enabled", false);

**4. How to disable  "What's new" gift icon from toolbar and main menu?**
user_pref("browser.messaging-system.whatsNewPanel.enabled", false);

**Are these prefs of any interest to us?**
user_pref("browser.contentblocking.report.lockwise.enabled", false);
user_pref("browser.contentblocking.report.monitor.enabled", false);
user_pref("media.mediacapabilities.from-database", false);

Thank you in advance!

**Comment by rusty-snake** [comment]
> user_pref("media.mediacapabilities.from-database", false);

#819

**Comment by Thorin-Oakenpants** [comment]
Hey just-me 💋 long time, no see .. you don't call, you don't write ... 😀  how's the spelling and grammar etc in the user.js. Anything amiss?

> Are these prefs enough to completely disable the features that I don't want

IDK: probably, they *look* like it. None of these are anything I want to add, so I haven't fully investigated them.

3. **Cryptominers** - yup, and there's also `privacy.trackingprotection.fingerprinting.enabled` which will get flipped to true at some stage (without checking I think it's in FF71: it just needs a little more time to reduce breakage)

4. **Gift icon**: click and it goes away. I'm not going to block end-users getting some info on some/each update about a new feature. I think that's how it works: the message is local to alert you to things. I can't see immediately where anything was set in prefs to say I clicked it: but sure, that `enabled` pref looks like it kills it dead (there's also a `badge` one)

I'll have to double check, but as for the rest: monitor doesn't do anything unless you sign up for it, and lockwise is the the new password manager built into Firefox, and the old password thing will get stripped out. It's not a system addon or anything. All the signon stuff looks fine, but I haven't really read about it. Why disable password generation: it's just a sub-menu in a context menu. Not sure how signon breach works - I though that was part of lockwise. So I clearly need to dig a bit more so I'm in the know, not because I think any of it is a privacy issue

Don't close this: I'll use it to remind me to check on a few things

**Comment by Just-me-ghacks** [comment]
Hey, Pants! I'm quietly following you along the way. Every day...

I don't know how these are implemented, but I don't want Firefox to call home / send visited URLs anywhere / download files from servers, etc.

**1.** There is no way this is done locally.

**2.** I like to generate my passwords by myself (KeePass). Do I need this one as well:
`user_pref("signon.generation.available", false);`

**3.** I use uBlock Origin & uMatrix with custom filters. Tracking Protection means redundancy, lack of control over the filters and harder troubleshooting when something is broken. I will add this one as well:
`user_pref("privacy.trackingprotection.fingerprinting.enabled", false);`

**4.** If it's local and doesn't fetch info from some server, I might leave it alone. Otherwise I will add this one as well:
`user_pref("browser.messaging-system.fxatoolbarbadge.enabled", false);`

**5.** I don't want to send any info (including my IP) to any server on certificate error (or any error for that matter). I will add these two:
```
user_pref("security.certerrors.mitm.priming.enabled", false);
user_pref("security.certerrors.mitm.priming.endpoint", "");
```

**6.** fxmonitor sounds like a spyware:
`user_pref("extensions.fxmonitor.enabled", false);`

**7.** Is this local or info is being send over to Mozilla?
`user_pref("browser.fixup.typo.scheme", false);`

**8.** Is this being used to fingerprint users? Rising / lowering entropy?
`user_pref("layout.css.text-decoration-skip-ink.enabled", false);`

**In summary:**
```
user_pref("browser.contentblocking.report.lockwise.enabled", false);
user_pref("browser.contentblocking.report.monitor.enabled", false);
user_pref("browser.fixup.typo.scheme", false);
user_pref("browser.messaging-system.fxatoolbarbadge.enabled", false);
user_pref("browser.messaging-system.whatsNewPanel.enabled", false);
user_pref("extensions.fxmonitor.enabled", false);
user_pref("layout.css.text-decoration-skip-ink.enabled", false);
user_pref("media.mediacapabilities.from-database", false);
user_pref("privacy.trackingprotection.cryptomining.enabled", false);
user_pref("privacy.trackingprotection.fingerprinting.enabled", false);
user_pref("security.certerrors.mitm.priming.enabled", false);
user_pref("security.certerrors.mitm.priming.endpoint", "");
user_pref("signon.generation.available", false);
user_pref("signon.generation.enabled", false);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
user_pref("signon.management.page.enabled", false);
```

Is anyone else going to use some of these prefs?

**Comment by rusty-snake** [comment]
```javascript
/* 6602: disable firefox's buildin tracking-protection
 * uBlock origin can do this better ***/
user_pref("privacy.trackingprotection.enabled", false);
user_pref("privacy.trackingprotection.pbmode.enabled", false);
user_pref("privacy.trackingprotection.cryptomining.enabled", false);
user_pref("privacy.trackingprotection.socialtracking.enabled", false);
user_pref("privacy.trackingprotection.fingerprinting.enabled", false);
/* 6603: disable updates of the trackingprotection lists ***/
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
```

**Comment by Just-me-ghacks** [comment]
FF 70 keeps uploading and downloading stuff to 99.86.243.90 upon start and during use. Unlike FF 60.9.0. Any ideas?

99.86.243.68, 99.86.243.71, 99.86.243.73, 99.86.243.90, etc.

I will test the versions between 60 and 70 to narrow down the possibilities.

**Comment by rusty-snake** [comment]
2. already killed by not using FFX PW-safe?
6. removed in FFX70 (the pref)
7. Looks hardcoded things like `htp://` and so on. 

> user_pref("browser.contentblocking.report.lockwise.enabled", false);
user_pref("browser.contentblocking.report.monitor.enabled", false);

Only disable the suggestions on `about:protections`.

99.86.243.90 is AWS, look at `about:networking` for the domain.

**Comment by Just-me-ghacks** [comment]
Request URL:https://content-signature-2.cdn.mozilla.net/chains/remote-settings.content-signature.mozilla.org-2019-12-01-23-34-03.chain
Request method:GET
Remote address:99.86.243.90:443
Status code:
200

https://trac.torproject.org/projects/tor/ticket/31575

**Comment by GitCurious** [comment]
I am also seeing content-signature-2.cdn.mozilla.net - I was under the impression it was something to do with 'certificates' whether checking or updating  [?]

They never seem to make it easy to figure out what they're up to.

**Comment by JOsamson** [comment]
That would be [content signature protocol of autograph service](https://github.com/mozilla-services/autograph/blob/master/signer/contentsignature/README.rst).

Prior to FF69, a call to content-signature-2.cdn.mozilla.com would accompany a daily fetch of remote-settings. It would seem to be working incorrectly right now. 

Funny how it’s gone unnoticed.

**Comment by Thorin-Oakenpants** [comment]
@earthlng do you see anything in here that merits inclusion? I don't (i.e no privacy issue, not talking about blocking all outbound connections).

Also, not sure what JOsamson 's comment warrants: not even clicked the link: is something broken and we need to let Mozilla know?

Other than that, can we close this?

**Comment by Thorin-Oakenpants** [comment]
>  Is this being used to fingerprint users? Rising / lowering entropy?
> user_pref("layout.css.text-decoration-skip-ink.enabled", false);

I did some research and testing on the new decorations (not this skip-ink one) for URLs to see if they could be used to detect visited links... hang on ... `text-decoration-thickness` was one .. but it's protected.

I would guess that the css properties can be read back, so changing the default would make you FP'able. You can run a modernizer script that does IDK 1000 or something feature detections to create a FP. It runs in about 100ms. So don't fuck with settings unless it is tested and has a proven benefit.

**Comment by earthlng** [comment]
There's nothing we can really do about RemoteSettings because that's also how some of the useful features like blocklists, revoked certs etc get their data.

> 6. fxmonitor sounds like a spyware

maybe not the best name for a security feature but it's definitely not spyware, last I checked. There may be some telemetry in there but since fxmonitor is now a builtin component, any such telemetry would/should probably be covered by disabling the main telemetry thing.
The necessary data for fxmonitor gets downloaded via RemoteSettings regardless of whether you enable or disable the feature and based on that, now local data, it can inform users about (recent) server breaches when they visit such sites so that they can change their password if they have an account on that site.
All they need to store locally for that is an up-to-date list of breached domains.
The records in the fxmonitor RS database look like this:

![1](https://user-images.githubusercontent.com/25846669/67683009-74165580-f988-11e9-99ca-49a803d292d5.png)

You can also sign up to get notified if your email address shows up in any data dumps from such server breaches but that's entirely optional.

Unless someone can show some proof that there's more than the intended functionality outlined above hiding somewhere in fxmonitor and because I don't feel like doing an in-depth code-review every time someone brings up a "suspiciously named" pref, I don't see a reason to disable a security feature that doesn't seem to have any downsides

**Comment by Just-me-ghacks** [comment]
Thanks everyone for the help! As far as I understand:

**NOT IMPORTANT:**
```
user_pref("browser.contentblocking.report.lockwise.enabled", false);
user_pref("browser.contentblocking.report.monitor.enabled", false);
user_pref("browser.fixup.typo.scheme", false);
user_pref("signon.management.page.enabled", false);
```


**TO CONSIDER:**
```
user_pref("extensions.fxmonitor.enabled", false);
user_pref("media.mediacapabilities.from-database", false);
user_pref("privacy.trackingprotection.cryptomining.enabled", false);
user_pref("privacy.trackingprotection.fingerprinting.enabled", false);
user_pref("privacy.trackingprotection.socialtracking.enabled", false);
user_pref("security.certerrors.mitm.priming.enabled", false);
user_pref("security.certerrors.mitm.priming.endpoint", "");
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.management.page.breachAlertUrl", "");
```


**SIMPLY ANNOYING:**
```
user_pref("browser.messaging-system.fxatoolbarbadge.enabled", false);
user_pref("browser.messaging-system.whatsNewPanel.enabled", false);
user_pref("extensions.abuseReport.enabled", false);
user_pref("signon.generation.available", false);
user_pref("signon.generation.enabled", false);
```


**TO INVESTIGATE:**
- firefox talking to remote servers for unknown (to me) reason since v68.
- a small empty bar appears when you type (maxRichResults - 0)
https://www.wilderssecurity.com/threads/new-firefox-browser-version-released.361562/page-99#post-2867105

**Comment by GitCurious** [comment]
I hadn't seen that empty bar before ! (I very rarely type into the address bar)

I fixed it with a CSS rule:

`#urlbar-results {display: none !important;}`

**Comment by Thorin-Oakenpants** [comment]
This is getting out of hand: it's like someone dumping a massive list on me. 23 prefs mentioned 59 times. What you do with them is up to you.

<details><summary>23 prefs</summary><p>

```js
browser.contentblocking.report.lockwise.enabled
browser.contentblocking.report.monitor.enabled
browser.fixup.typo.scheme
browser.messaging-system.fxatoolbarbadge.enabled
browser.messaging-system.whatsNewPanel.enabled
browser.safebrowsing.provider.mozilla.gethashURL
browser.safebrowsing.provider.mozilla.updateURL
extensions.abuseReport.enabled
extensions.fxmonitor.enabled
layout.css.text-decoration-skip-ink.enabled
media.mediacapabilities.from-database
privacy.trackingprotection.cryptomining.enabled
privacy.trackingprotection.enabled
privacy.trackingprotection.fingerprinting.enabled
privacy.trackingprotection.pbmode.enabled
privacy.trackingprotection.socialtracking.enabled
security.certerrors.mitm.priming.enabled
security.certerrors.mitm.priming.endpoint
signon.generation.available
signon.generation.enabled
signon.management.page.breach-alerts.enabled
signon.management.page.breachAlertUrl
signon.management.page.enabled
```

</p></details>

- tracking protection: I don't care: it's constantly changing, it has a full on UI, no privacy issues
- lockwise: i don't care: there's nothing wrong with it: it's the new password manager, no privacy issues
- whatsnewpanel: I don't care: it;s not a privacy issue: just click the fucker and be done with it
- monitor: I don't care: no privacy issues
- cert error mitm: I don't care: ask earthlng and :cat: there's no privacy issue here
- signon generation: I don't care
- SB urls: not needed, don't care
- layout.css.text-decoration-skip-ink.enabled - no privacy issue here

Fuck that's a lot of don't cares .. anyone sensing a pattern here... like, you know, no privacy issues

What's left
- extensions.abuseReport.enabled - where did this come from (I'm too lazy to look anything up), I'm just going to assume it requires end-user interaction, so I am going to ignore it
- browser.fixup.typo.scheme - where did this come from? I'm going to assume it's local, why would string manipulation need to make outbound calls, so I'm going to ignore it

What's left after than
- media.mediacapabilities.from-database - don't know for sure what is it in, but it will not have PII in it, it's for video playback perfs or whatever. Disk avoidance is overkill, and we relaxed and "snappened" a lot of shit in the user.js so it was more lightweight and put the onus on the end-user to secure their device - so, don't care

I think that wraps up 23 "don't cares" and I'm closing this. If you're really concerned, then feel free to keep chatting away and if you find definitive proof that something needs changing in the user.js, open a new issue.

Thanks for playing :)

**Comment by theWalkingDuck** [comment]
> TO INVESTIGATE: a small empty bar appears when you type (maxRichResults - 0)

get rid of it with  `userChrome.css` 
    
```
/* remove urlbar drop down */
#urlbar-results {display: none !important;}
.urlbarView {border: none !important;}  
```
