### ISSUE TITLE
fixup wiki + scratchpad nomenclature

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#822]
https://bugzilla.mozilla.org/show_bug.cgi?id=1565380

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1519103 ... FF72+

**Comment by Thorin-Oakenpants** [comment]
@earthlng , do you want to fixup the information in your wiki page: that in FF72+ the scratchpad no longer exists and to use the **multi-line editor mode in the console**

I don't think we need to change anything re our scratchpad dir/names: just the wiki

**Comment by earthlng** [comment]
I think I'm just gonna rip it out because that's how we do things around here apparently.

**Comment by earthlng** [comment]
updated [1.4-Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) and [3.1-Resetting-Inactive-Prefs-[Scripts]](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-Resetting-Inactive-Prefs-[Scripts])
