### ISSUE TITLE
Cannot login to Reddit: details "TWO_FA_REQUIRED"

### ISSUE THREAD

**Issue by brakenow** [ghacksuserjs/ghacks-user.js#823]
Hello,

Running FF 70, and have two factor login enabled. A json page apperars with the text in the topic when I try to login.

**Comment by Thorin-Oakenpants** [comment]
You already have an issue open at https://github.com/pyllyukko/user.js/issues/477

**Comment by brakenow** [comment]
It was because of uMatrix. Sorry!
