### ISSUE TITLE
widevine not downloaded after 1825+1830? [see Private Virtual Network]

### ISSUE THREAD

**Issue by ZeDeedIsDone** [ghacksuserjs/ghacks-user.js#825]
I'm at my wits end here. After 5 hours of troubleshooting to make other things work, I'm exhausted and the only thing left is getting widevine to install. One of the configs is blocking the url for it's installation and for the life of me I can't find out which one. Please help

I get this at about:addons > plugins
"Widevine Content Decryption Module provided by Google Inc. will be installed shortly."

**Comment by claustromaniac** [comment]
See section 1825

https://github.com/ghacksuserjs/ghacks-user.js/blob/e4f80225d8f2c5c70681e53a9ca607293a5695ed/user.js#L888-L891

**Comment by ZeDeedIsDone** [comment]
> 
> 
> See section 1825
> 
> https://github.com/ghacksuserjs/ghacks-user.js/blob/e4f80225d8f2c5c70681e53a9ca607293a5695ed/user.js#L888-L891

These are enabled, but it's still not installing. I suspect a kinda hostblock on installing plugins or something. I think it could install itself at this point, it just won't download the file.

**Comment by Thorin-Oakenpants** [comment]
Did you also allow DRM content - `1830`?

And, silly question (just checking), but you aren't just resetting these in about:config, but also adding them as overrides (or commenting the lines out) in the user.js (for when you restart)?

---

I'm keen on finding the culprit as well, because I want the setup tags to work. Assuming the above is correct, and it's still failing

It seems like you started with a new profile (otherwise you would already have had widevine), so do you intend to stay with that, and import your bookmarks, extension settings etc. If the answer is yes, then your workaround to get widevine first and then apply the user.js might suffice (for now)

But this just raises questions: will regular widevine updates fail (security)? I'll see if I can have a play later on, but I'll need some sort of link to trigger the widevine download (I do not have a netflix account)?

---

https://support.mozilla.org/en-US/questions/1226162 = same problem, the person flipped "remember history" and then netflix worked.

Maybe it's some weird Netflix thing: what happens if you visit https://bitmovin.com/demos/drm

**Comment by Thorin-Oakenpants** [comment]
> After 5 hours of troubleshooting to make other things work, I'm exhausted

I'm sorry about that. The widevine issue aside, it shouldn't be that hard. And you seem to be pretty knowledgeable. If you get time, can you elaborate on the things you had trouble with so I can improve the troubleshooting setup tags

**Comment by ZeDeedIsDone** [comment]
> Did you also allow DRM content - `1830`?

media.eme.enabled is enabled
> And, silly question (just checking), but you aren't just resetting these in about:config, but also adding them as overrides (or commenting the lines out) in the user.js (for when you restart)?

I didn't know they was a way to override, what I did was manually reset about:config values that I wanted to change, and also commenting it out in user.js before restarting firefox.

> It seems like you started with a new profile (otherwise you would already have had widevine), so do you intend to stay with that, and import your bookmarks, extension settings etc. If the answer is yes, then your workaround to get widevine first and then apply the user.js might suffice (for now)
> 
> But this just raises questions: will regular widevine updates fail (security)? I'll see if I can have a play later on, but I'll need some sort of link to trigger the widevine download (I do not have a netflix account)?

I don't intend to stay on this new profile because of what you've mentioned, I most likely will not get widevine updates.

> https://support.mozilla.org/en-US/questions/1226162 = same problem, the person flipped "remember history" and then netflix worked.

Remember history is default, I tried toggling it off and on as a ditch effort, and I'm not surprised it didn't work.

> Maybe it's some weird Netflix thing: what happens if you visit https://bitmovin.com/demos/drm

Same issue, this happens on any website that needs DRM; Netflix and Spotify to name a few.



> 
> 
> > After 5 hours of troubleshooting to make other things work, I'm exhausted
> 
> I'm sorry about that. The widevine issue aside, it shouldn't be that hard. And you seem to be pretty knowledgeable. If you get time, can you elaborate on the things you had trouble with so I can improve the troubleshooting setup tags

Thanks for the concern. I'll try it again knowing I can override should be a little simpler than manually removing/adding preferences one by one.
Could you point a way to the troubleshoot wiki for overriding? Ctrl + F 'override' doesn't show up anything or I'm extremly tired. I'm assuming from google that I just need to add in a override-user.js file.

**Comment by ZeDeedIsDone** [comment]
I found the culprit, and it is a stupid culprit.
Firefox's new Private Virtual Network was what was blocking widevine from downloading.

You may have to also reset all media.gmp-widevine* configs if firefox got tricked into installing widevine when it actually installed nothing.

Thanks for letting me know about the override function. If anything, I'd say please make it more obvious in the wiki that the tool exists. Thanks for your help again and sorry for the stupid conclusion to this mess.

**Comment by Thorin-Oakenpants** [comment]
re-opening because I want to remind myself to dig a little deeper, and improve the user.js

**Comment by Thorin-Oakenpants** [comment]
overrides: https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes

I don't use the updater scripts or keep a separate overrides.js as a master copy. Basically add anything you want overriden to the end of the user.js, and manually update once per release by copy/pasting (and read the release logs we do).

You can also use your overrides section to add prefs we don't have

e.g here's mine
```js
// OVERRIDES
/* experimenting */
// user_pref("privacy.fuzzyfox.enabled", true); // FF65+
/* urlbar FF71+ */
user_pref("browser.urlbar.megabar", false);
/* startup */
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage", "moz-extension://0639706b-0794-46b6-b5f4-9f28aa9cbf20/dial.html");
/* reset this in case I forgot when toggling */
user_pref("privacy.file_unique_origin", true);
/* updates */
user_pref("extensions.update.autoUpdateDefault", false);
/* AS crap */
user_pref("browser.library.activity-stream.enabled", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
/* hide/disable pocket, sync, reader, screenshots icons and various menu items */
user_pref("extensions.pocket.enabled", false);
user_pref("extensions.screenshots.disabled", true);
user_pref("identity.fxaccounts.enabled", false);
user_pref("reader.parse-on-load.enabled", false);
/* cookies */
user_pref("network.cookie.cookieBehavior", 2);
user_pref("privacy.clearOnShutdown.cookies", false);
user_pref("privacy.cpd.cookies", false);
/* warnings & whats new */
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("full-screen-api.warning.delay", 0);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("browser.tabs.closeWindowWithLastTab", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
/* findbar etc */
user_pref("findbar.modalHighlight", true);
user_pref("findbar.highlightAll", true);
user_pref("accessibility.typeaheadfind", true);
/* use last dir for downloads */
user_pref("browser.download.folderList", 2);
/* font stuff */
  //user_pref("font.system.whitelist", "");
  //NOTE: ^^ set manually due to UTF-8 same as TB for Windows
/* OCSP */
user_pref("security.OCSP.require", false); // too much breakage
/* RFP */
user_pref("privacy.window.maxInnerWidth", 1600);
user_pref("privacy.window.maxInnerHeight", 900);
/* other */
user_pref("dom.allow_cut_copy", true); // for autocopy extension
user_pref("browser.backspace_action", 2);
user_pref("browser.urlbar.decodeURLsOnCopy", true);
user_pref("browser.bookmarks.max_backups", 0);
user_pref("network.manage-offline-status", false);
user_pref("extensions.webextensions.restrictedDomains", ""); // allow extensions on AMO etc
user_pref("browser.sessionstore.interval", 120000); // make SR once every 2 mins
/* UI */
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.oneOffSearches", false);
user_pref("browser.urlbar.autoFill", false);
user_pref("toolkit.cosmeticAnimations.enabled", false);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true); // userChrome/userContent
user_pref("ui.key.menuAccessKey", 0); // disable alt key toggling the menu bar [RESTART]
user_pref("browser.tabs.extraDragSpace", false); // stop theme turning drag space on

/* END: internal custom pref to test for syntax errors ***/
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");
```

**Comment by Thorin-Oakenpants** [comment]
> Firefox's new Private Virtual Network was what was blocking widevine from downloading

Thanks for working that one out. We don't even have that in the user.js. I'll have to read up on it's deployment etc

**Comment by Thorin-Oakenpants** [comment]
- [blog](https://blog.mozilla.org/blog/2019/09/10/firefoxs-test-pilot-program-returns-with-firefox-private-network-beta/) - available for US only (for now)
- [website](https://private-network.firefox.com/)

So my question would be: does the widevine update blocking happen when its off (i.e the extension is enabled but using it is not), or just because the extension is installed. I suspect it's the former

Has anyone told the Mozilla team behind it? - https://github.com/mozilla/secure-proxy/issues

Since it's an extension, I don't think there's anything I can do about it, and the problem should be fixed upstream. I'll post something for Mozilla and link back here

**Comment by ZeDeedIsDone** [comment]
> 
> 
>     * [blog](https://blog.mozilla.org/blog/2019/09/10/firefoxs-test-pilot-program-returns-with-firefox-private-network-beta/) - available for US only (for now)
> 
>     * [website](https://private-network.firefox.com/)
> 
> 
> So my question would be: does the widevine update blocking happen when its off (i.e the extension is enabled but using it is not), or just because the extension is installed. I suspect it's the former
> 
> Has anyone told the Mozilla team behind it? - https://github.com/mozilla/secure-proxy/issues
> 
> Since it's an extension, I don't think there's anything I can do about it, and the problem should be fixed upstream. I'll post something for Mozilla and link back here

Sorry I was vague on that answer but yeh the former. If I switch the proxy off, it allows the installation.
