### ISSUE TITLE
Automation shortcuts/URL

### ISSUE THREAD

**Issue by Bumbadawg** [ghacksuserjs/ghacks-user.js#827]
Hi,
using Firefox, as you know we can't keep track of local files. 
But what i'm doing is :
1 - using a localhost server to make a grabbable URL for FF, 
2 - edit with vim with autoCmd to start a FF page on :w
3 - on FF, click install confirm on the updated script and ^+w to close the tabs opened.

Here's what my alias looks like for those interested in doing so:
```bash
cd ~/soft/scripts/***
http-server -c-1 -a 127.0.0.1 >/dev/null &
vim '+normal Go' -c 'autocmd BufWritePost * !firefox localhost:8080/***.user.js && qdbus org.kde.KWin /KWin setCurrentDesktop 3' ***.user.js
```
NB: qdbus command is to change to Firefox virtual desktop.

**QUESTION:** is there a URL or a shortcuts to automate the install confirmation of a script ? So i don't have each update to click "confirm install" and close those tabs.

Thanks.

**Comment by Thorin-Oakenpants** [comment]
Just saying hi so you don't think I'm ignoring this issue. I have no idea, sorry. Maybe someone else can help (and I'm assuming this is relevant to this repo?)

**Comment by Bumbadawg** [comment]
Hi @Thorin-Oakenpants , thanks for showing some life =)
It should be relevant to the features, either hidden or not yet implemented. Making a register API/URL should be doable.

**Comment by earthlng** [comment]
I have no idea what you're asking or what you're trying to do.
Just based on the title, maybe [Marionette](https://firefox-source-docs.mozilla.org/testing/marionette/index.html) is what you're looking for but I've never dabbled with that and couldn't really help you, sorry.

> wrong section to be written in

and what does that mean?
