### ISSUE TITLE
SyntaxError: unexpected token: ':' Non-rooted device

### ISSUE THREAD

**Issue by Parlotten** [ghacksuserjs/ghacks-user.js#829]
Hi. I'm new here. During the installation of user.js in scratchpad at the end I get the following error: 
/*
Exception: SyntaxError: unexpected token: ':'
@Scratchpad/5:1700
*/
And the changes don't take effect. I have read the wiki page but I didn't find the solution on how to fix it. Firefox desktop version is 70.0.1. I have tried older versions but the same error occur.

**Comment by earthlng** [comment]
Hi

The scratchpad scripts don't have syntax errors. If you copy-paste files from github always click the Raw button first and copy the raw script or download the [master.zip](https://github.com/ghacksuserjs/ghacks-user.js/archive/master.zip) and use the files from in there.

**Comment by Parlotten** [comment]
> 
> 
> Hi
> 
> The scratchpad scripts don't have syntax errors. If you copy-paste files from github always click the Raw button first and copy the raw script or download the [master.zip](https://github.com/ghacksuserjs/ghacks-user.js/archive/master.zip) and use the files from in there.



Thanks for the answer. I did it but it doesn't work. What am I doing wrong?
1. I have clicked the raw button
![Desktop Screenshot 2019 11 02 - 13 29 57 99](https://user-images.githubusercontent.com/57270598/68070976-87089b80-fd75-11e9-98ef-4aa864f7e9eb.png)
2. I have copied the script
![Desktop Screenshot 2019 11 02 - 13 31 41 20](https://user-images.githubusercontent.com/57270598/68070980-9c7dc580-fd75-11e9-9ec8-f97bb5bea491.png)
3. I have pasted it to the scratchpad and in the // place I have pasted all the user.js's content then clicked the Display button and I get an error
![Desktop Screenshot 2019 11 02 - 13 32 15 84](https://user-images.githubusercontent.com/57270598/68070988-b4ede000-fd75-11e9-9e98-68ed8c10c300.png)

**Comment by earthlng** [comment]
1. What exactly are you trying to do?
2. Where did you get that code-snippet from? None of our scratchpad scripts contain that function.
3. in your 2nd picture the visible part of the URL points to a file on your own fork or repo. Why?

If you're just starting to use the ghacks user.js you don't need to use any of our scratchpad scripts.

Basically just download our master.zip and extract the user.js into your profile directory. But I highly recommend that you re-read and make sure you understand the wiki pages, starting with the Basics at 1.1 and up until at least 1.3. Once you got that going, read or re-read the Maintenance section that explains how you can easily make your own changes and still keep up-to-date. You don't have to create your own fork of this project to do that.
If something in the wiki is unclear don't hesitate to ask any questions you might have.

**Comment by earthlng** [comment]
Oh nvm, I see what you're trying to do now.

You can see the problem in your 3rd image at line 25 in that scratchpad. You need to remove the first 2 slashes on that line and then it should work. By keeping the 2 slashes in the front there, you commented out the first line of a multi-line javascript comment, resulting in a broken JS file.

**Comment by earthlng** [comment]
I changed the line on that wiki page to
```js
//paste your user.js file content on the next line
```
instead of 
```js
//paste your user.js file content here
```
Hopefully that will prevent any future misunderstandings.

**Comment by Parlotten** [comment]
> 
> 
> I changed the line on that wiki page to
> 
> ```js
> //paste your user.js file content on the next line
> ```
> 
> instead of
> 
> ```js
> //paste your user.js file content here
> ```
> 
> Hopefully that will prevent any future misunderstandings.

Finally I have got the same an error as on 4th image so I clicked enter. Then I have opened the user.js by notepad++ then I selected all content and I have just put content into new line. I clicked display button and idk how installation was successful. Btw it is normal that mobile firefox have "Clear private data on exit" isn't turned on by default? 
![Screenshot_20191102_234735_org mozilla firefox](https://user-images.githubusercontent.com/57270598/68077831-3d4aa000-fdcb-11e9-9b0b-be37f9374b77.jpg)
When I have installed user.js on desktop I had blank page as start page. In about:config on phone I have set about:blank but it looks like default home page. 
![Screenshot_20191102_234632_org mozilla firefox](https://user-images.githubusercontent.com/57270598/68077827-1e4c0e00-fdcb-11e9-9c8a-e34cf171ae50.jpg)

I'm also almost sure that after the install on the desktop browser history was turned off. 
![Screenshot_20191102_234904_org mozilla firefox](https://user-images.githubusercontent.com/57270598/68077840-666b3080-fdcb-11e9-816a-953711b53da7.jpg)

Sry for my English.

**Comment by earthlng** [comment]
While we do have that wiki page on how to load a user.js into Android, we don't really support Firefox on Android. It's up to you to customize the user.js to do all the things you want it to do on Android.

If you find the Android prefs to fix the things you listed, you can share them here and we can list them on that wiki page. Maybe if such a list would get long enough, we might add it to the user.js or create a custom Android overrides.js files or something like that but until then it is what it is, sorry.

**Comment by Thorin-Oakenpants** [comment]
So there's a couple of things going on here
- 1. you get a syntax error
- 2. you aren't getting the same results

So, `1`: I wonder if something in the user.js further down is causing it, e.g one of out 1 char switches? IDK. `2`: if something that applies in both android **and** desktop, but doesn't get written to Android, then the syntax error would be the cause (I guess it writes the changes until it errors? IDK). But I actually wonder if any of the prefs are being written.

You can load `about:support` and scroll down to "Important Modified Preferences" and see if something was applied that you know you didn't do manually : e.g `privacy.firstparty.isolate`

Back to what I said about prefs being applicable to both OSes. So looking at the start page on Android, you go to `Settings>General>Home>Set a homepage`, so I did that, and changed it to "about:blank", and sure enough, I get a blank page (on startup) - this doesn't seem to be in any pref that I can find - certainly not `browser.startup.page` or `browser.startup.homepage` (and nothing shows in about:support). Android is a very different kettle of fish, and probably not something we can help with.

As for the syntax error, IDK without fucking around with my phone which I do not want to do. I'm not even sure I can since it's now encrypted, my computer doesn't see it

**Comment by Thorin-Oakenpants** [comment]
I have a new clean install of FF on my android, and the only thing I have changed is RFP and FPI, the search engine and not much else (some items via the settings UI like clearing on close etc). And I don't have the top sites tab. I always open to the bookmarks tab. And all these changes don't show in about:support except RFP and FPI.

---

@earthlng : I think we should add something to that wiki, that the user.js is designed for desktop etc, and then in the user.js itself, under the version or something we can state that this is primarily designed for desktop, and android users can run this shit at their own risk - whaddya think, how would we phrase it (I'm likely to say rude/harsh words)

**Comment by Thorin-Oakenpants** [comment]
Oh, I know why I don't have "Top Sites" = Settings > General > Home > Panels > Top Sites > turn it all off

**Comment by earthlng** [comment]
yeah, mentioning that on the android wiki page SGTM.
IDK if we should add something to the user.js itself. If it needs to be mentioned somewhere else besides that wiki page then I think the README.MD would be the place

**Comment by Thorin-Oakenpants** [comment]
I still think the js file could do with it (a very short one liner, or just add `dekstop` to the version line but that probably fucks up the updaters), but for sure the other two for starters. How would we phrase it?

**Comment by Thorin-Oakenpants** [comment]
readme has two places we could be more descriptive, rather than add a whole new line

> The `ghacks user.js` is a **template**  [add something here] which aims ...

> Also be aware that this `user.js` is made specifically for Firefox [add something here]. Using it as-is in other Gecko-based browsers can be counterproductive, especially in the Tor Browser. [or add something here]

The template line is already quite long, but the second one looks ok?
