### ISSUE TITLE
12bytes repo change

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#830]
i moved my shit from GitLab to Codeberg cause... well, just cause

https://github.com/ghacksuserjs/ghacks-user.js/blob/master/README.md

The 12bytes article now uses this user.js and supplements it with an additional JS hosted at ~~GitLab~~

The 12bytes article now uses this user.js and supplements it with an additional JS hosted at [Codeberg](https://codeberg.org/12bytes.org/Firefox-user.js-supplement)

**Comment by earthlng** [comment]
Hi, the codeberg link points to gitlab ... ;)

**Comment by atomGit** [comment]
oooooooook. so we'll not be drinking that brand of beer anymore

link fixed :)

**Comment by earthlng** [comment]
Done. Thanks

**Comment by Thorin-Oakenpants** [comment]
> so we'll not be drinking that brand of beer anymore

Which brand is that .. I want to order a truckload of it .. sounds like my kinda beer

**Comment by atomGit** [comment]
don't remember, but it was probably the same brand i was drinking when i wrote some gibberish on my site about stupid people not being stupid because.... quantum physics - i read that the next morning and thought someone must've hacked my site :)

**Comment by Thorin-Oakenpants** [comment]
now **that's** what I'm talking about ... process of elimination ... let me know when you find out
