### ISSUE TITLE
Wiki - Recommended CSP settings

### ISSUE THREAD

**Issue by eggplanting** [ghacksuserjs/ghacks-user.js#831]
Hi together,

sorry for opening an issue regarding this topic, but there's no better place for asking this question.

The wiki states that only one extension wins when CPS injection is used to modify the header:
https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions

I knew that uBlock Origin and Canvas Blocker interfere if the mentioned settings are checked for both. But how does it look with extensions like Canvas Blocker + Clear URLs?
The wiki doesn't mention a special setting for a range of extensions which needs to be unchecked.

Do some extensions use CSP injection by default, which means that I need to uncheck my Canvas Blocker settings (Block data URL pages) when using Clear URLs for example?

Would you even recommend to check special settings to increase privacy?
The wiki states only how to uncheck these settings, there's no recommendation about what should be checked.

Is the setting "Block data URL pages" of CanvasBlocker recommended to be checked?

Best regards

Edit: I'd really appreciate if someone could tell me what would be the best CSP setting for following extensions:
- uBlock Origin (Does it per Default do something with CSP?)
- CanvasBlocker (It enabled "Block data URL pages" per default - Is this recommended?)
- ClearURLs (What does it to with CDP? Or does it nothing and is just a recommended extension?)

**Comment by Thorin-Oakenpants** [comment]
see #664 - there is no definitive answer

> The entries below are some features you could **consider** disabling (or achieving another way) to **reduce** CSP header injection issues, **depending on what extensions you use**. It is up to you to determine what mix you want

It also depends **how** you use those extensions. For example, I want uMatrix to always win, so I try and disable/lessen all other extensions using CSP header injection e.g. I don't use uBO to block any fonts and instead use a different method/extension, etc
