### ISSUE TITLE
SB and UA and RFP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#834]
someone ranting [here](https://old.reddit.com/r/privacytoolsIO/comments/drwbex/why_its_harmful_for_privacytoolsio_to_describe/)

However:
![fyj7a1](https://user-images.githubusercontent.com/16656956/68194962-e5b85a00-ffad-11e9-9107-298f35368628.png)

This is an old image (FF52.5) but what I want to ask is
- does safe browsing requests respect the RFP UA spoof
- If it does, is this by design or an artifact: i.e  could this change inadvertently if RFP was exempted in some privileged contexts?
- does it send the major version only or also the minor (e.g below it shows 52.5)
- how do I capture this to test it?

Class, discuss

@earthlng

**Comment by earthlng** [comment]
> how do I capture this to test it?

either with the browser console by enabling XHR + Request logs (top right) or with an external local proxy software that supports HTTPS inspection like [Fiddler](https://en.wikipedia.org/wiki/Fiddler_(software)) or Burp Suite for example.
It's possible that the browser console doesn't show all requests or if it does, doesn't show fully accurate data information like Headers, POST data etc. So, ideally you would test both ways and see if what FF shows you in the browser console actually matches what's really sent.

> could this change inadvertently if RFP was exempted in some privileged contexts?

that's certainly possible. Anything could change at any point. That's why they have so many test files; to try to make sure that everything keeps working the way it should after any code changes

**Comment by Thorin-Oakenpants** [comment]
Damn, I just uninstalled Fiddler because it sat there unused for over a year :) And I'm guessing I would need to fire up a new profile with no SB lists and await the update check

**Comment by earthlng** [comment]
the update checks are probably tied to a timestamp pref that you could reset. Or maybe toggling SB off and on again might also trigger the update, idk.
You might also want to find a way to trigger the hash-check requests for a given website and since I believe those are cached as well, a way to reset that cache too. Have fun ;)

**Comment by Thorin-Oakenpants** [comment]
> Have fun ;)

~~F Off~~ No way :) I think I'd rather just ask @tomrittervg (or get him to ask someone like @groovecoder .. no idea if Luke will even see this ).. because if it did send the real UA (and minor version?) to google (despite the legal agreement between mozilla/google) then that wouldn't be the optimal setup

**Comment by Thorin-Oakenpants** [comment]
So I used my Nightly
- wiped everything in `\AppData\Local\Mozilla\Firefox\Profiles\xxxx.default-nightly\safebrowsing`
- started Nightly, opened network inspector, checked all
- within about 2 minutes the SB folder updated
- the inspector shows nothing

So I guess someone (or me if I ever get time) will need to use an external app. If anyone already has one set up, it'll take you five minutes

**Comment by earthlng** [comment]
I can't believe that after all these years you still don't know the difference between the browser console and the network inspector.

All the Devtools like the Inspector, Console (="Web" console!), Debugger, Network Monitor, etc are always attached to a certain tab whereas the Browser Console logs messages triggered by the browser itself and by addons. If you enable the "Show Content Messages" checkbox it'll also show you the same things as the Web Console but from **all** tabs.

There's also the Browser **Toolbox** which basically attaches the Devtools to the browser context and lets you fe inspect the Storage (ie IDB databases etc) used by FF itself and things like that, but it's hidden by default and you'll rarely need that anyways.

for more details see:
https://developer.mozilla.org/en-US/docs/Tools
https://developer.mozilla.org/en-US/docs/Tools/Web_Console
https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox

**Comment by Thorin-Oakenpants** [comment]
There is no `Show Content Messages` in nightly. The console below is just an empty one and not related to the one underneath. I am aware of results being attached to a specific tab - I simply didn't have the right "content" when I opened it the first time round - my bad.

![meh](https://user-images.githubusercontent.com/16656956/68348489-e3f7af00-00f1-11ea-999b-6d2e7b0c4b23.png)

**Comment by Thorin-Oakenpants** [comment]
IDK if this is enough info, but the request header respects RFP
![meh](https://user-images.githubusercontent.com/16656956/68349083-ccb9c100-00f3-11ea-8aa0-000f98c8945e.png)

**Comment by gwarser** [comment]
> There is no `Show Content Messages` in nightly.

Under cogwheel in top right corner.

**Comment by Thorin-Oakenpants** [comment]
Actually, it doesn't matter if google ever gets sent the real version for non 60, 68, 78 (ESR) releases: because loads of others will be as well (and you should kept your Firefox up to date). In this respect even the minor version doesn't matter. And I'm pretty sure google ain't interested in tying a FF release version to an IP: because it's flawed for starters: as an IP addy is not a single computer, person, or application.

Closing this as a waste of time, but thanks everyone for helping out

**Comment by Thorin-Oakenpants** [comment]
> Under cogwheel in top right corner.

Still nothing there: but it's already getting all windows. I guess it depends from where I opened it. Thanks: I did look under there earlier for a toggle in the menu: I should have gone deeper into the cog wheel.
