### ISSUE TITLE
spring cleaning / fixups

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#840]
I will post some shit in the next comment to keep OP small for a checklist

* [x] `0308` browser.search.update - see [1444426](https://bugzilla.mozilla.org/show_bug.cgi?id=1444426) - https://github.com/ghacksuserjs/ghacks-user.js/commit/df1732745d84b1f7b163d6345fc66db4bb31402b
   - we should clarify what this means
   - this is not built in search engines, and it's not for "newer WebExtensions"
   - "it provides/stops the option to update the definition of an individual (non-WebExtension) engine that's been installed manually"
* [x] `1703` privacy.usercontext.about_newtab_segregation.enabled - https://github.com/ghacksuserjs/ghacks-user.js/commit/0cfb2fb06d68639b3e491a98b80a380ad48ec0d4
* [x] `1031: inactive` browser.chrome.site_icons - https://github.com/ghacksuserjs/ghacks-user.js/commit/fb263f5624dd4990a537ff351f70f3e4ed033bb9
   - is this really needed (NO): disk avoidance is overkill (go use tor browser or PB mode), some responsibility has to fall on the end-user such as securing a device and stopping shoulder surfers etc
   - check what TB do (it's default true: but they use PB mode)
   - is this already mitigated by history settings and/or sanitizing on close (YES)
   - is this mitigated by PB mode (YES)
* [x] `1032` alerts.showFavicons - https://github.com/ghacksuserjs/ghacks-user.js/commit/fb263f5624dd4990a537ff351f70f3e4ed033bb9
   - what is the threat here if it's ever flipped? (they can be cross origin?)... asking for a "friend"
   - default false anyway -> lets make it inactive
* [x] `1201` + `1270` - https://github.com/ghacksuserjs/ghacks-user.js/commit/4074a37e1d3a2492e0fd28bcc9289b8b88e94b58
   - 1270 only applies if 1201 is false, and it's not a red red padlock
   - see discussion from #805 for details
* [ ] `2032` media.block-autoplay-until-in-foreground
   - make inactive at least but keep so all the relevant prefs are kept together?
* [x] `2680` security.csp.enable - https://github.com/ghacksuserjs/ghacks-user.js/commit/a0e0a2a6c96167735b1f684da385ddb2ae6c6fbb
   - just wondering why we ever added this, was it false at some stage (when first added?)
* [ ] `4002` privacy.firstparty.isolate.restrict_opener_access
  - make inactive?

---

discarded items
* `2620` pdfjs.disabled
    * [x] fixup first word from "enable" to "enforce" - https://github.com/ghacksuserjs/ghacks-user.js/commit/a3611b7cf89b64b7b9814259cb5fdbde3ebbcd3e
    - maybe make inactive: this is one of those situations where enforcing the default could be really bad, although the chances of Mozilla needing to flip it is almost zero IMO. On the flip side, leaving it active can help people with shit like adobe acrobat reader
   - ignoring this proposal for now since I know it will only cause way too many arguments
* `2684` security.dialog_enable_delay
   - I like the fact that this is added so people know what a "security delay" is
   - 700ms vs 1000ms is not important, what is important is that people know not to set it to zero
   - ~~at the very least we could set this as inactive (and add a warning tag): 1 less modified pref to deal with~~
* `2720` dom.indexedDB.enabled
   - [deprecated](https://bugzilla.mozilla.org/show_bug.cgi?id=1488583) in 72, but I don't mind getting rid of 9 lines we've had inactive for years
   - lets leave it in so people know it got deprecated

...

**Comment by Thorin-Oakenpants** [comment]
reserved

**Comment by Thorin-Oakenpants** [comment]
`https://github.com/CHEF-KOCH/FFCK/commit/20c9c19edb12aaec31199b7666568e6e4c1cc2f8#diff-a3bb2d58559a1d805c029d08d26a7b34R466` .. ooh look, there's someone following all my work like a little puppy

**Comment by crssi** [comment]
Add new pref "_info" with string "FU CK" 😉

**Comment by Thorin-Oakenpants** [comment]
currently
```js
/* 1031: disable favicons in tabs and new bookmarks
 * bookmark favicons are stored as data blobs in favicons.sqlite ***/
   // user_pref("browser.chrome.site_icons", false);
```

I did a heap of testing in a vanilla FF70, and rather than bore you with all the test results and permutations, basically `1031` `browser.chrome.site_icons` doesn't really do anything to boost privacy (but I do possibly see one edge case)

- icon blobs -> `favicons.sqlite` are set by two things. Bookmarks and history. If you have any bookmarks (where the URL has a favicon) or history, then *not* having the favicon doesn't add any privacy: you already have persistent data as the actual full URL
- clearing history clears history related favicons
- removing a bookmark removes the bookmark's icon
- pb mode: does not record history and thus does not record a history favicon (tested)
- pb mode: bookmarks are not limited to pb mode, so a bookmark added in pb mode does store a favicon (tested)
- however, I *think* the favicon.sqlite sanitizing is is only done on close
- I am not sure what "forget about this site" does
- I do not know what history cleaning extensions trigger

The only edge case I see here, is possibly being caught in-session with some history/bookmark that you though was wiped, leaving an in-session eTLD+1 favicon.

In this threat model / level, a user is better off disabling history, or using pb mode, or Tor Browser.

@earthlng : what do you think. two options
- remove it ?
- 2a. fix it: e.g. "bookmark favicons are stored..." -> "bookmark and history favicons are stored..."
- 2b: improve it: e.g. favicon.sqlite sanitizing is done on close. If you want proper in-session protection do x or y or z

Please advise

**Comment by Thorin-Oakenpants** [comment]
currently
```js
/* 2680: enable CSP (Content Security Policy)
 * [1] https://developer.mozilla.org/docs/Web/HTTP/CSP ***/
user_pref("security.csp.enable", true); // [DEFAULT: true]
```

Default true in ESR60+, FF60+. IDK if the pref was added in 23 as per the MDN link

I don't see any reason to keep this, unless you have an objection or any other info about it @earthlng . If we keep it, we should at least make it inactive (and change the word to enforce to be consistent). Thus it will be one less modified pref at default.

Please advise

**Comment by earthlng** [comment]
CSP is a very important and very widespread and commonly used security feature. But it can interfere with some extensions and thus some users might be tempted/advised to disable it, which would be a horrible idea. Therefore enforcing it (back) to true makes some sense.
It can also be useful to know that this pref exists to debug certain extension-related issues and I've used it exactly for that at least once. I only knew that this pref exists because I saw it in the user.js.

Keeping it but making it inactive is definitely the least ideal action here. Either we keep it and enforce it, or we remove it. IDK, up to you.


re: icons - if we remove it then that FAVICONS subsection will only have 2 prefs left, with 1 of them matching FFs default value. Since we *do* have that subsection I'd definitely expect there to be the one pref that actually disables favicons and I don't see why we should remove that. The pref is inactive by default but available for those who don't want favicons for whatever reason.
If you wanna do 2a or 2b, that's fine.
ps. looks like it all started here: `https://github.com/ghacksuserjs/ghacks-user.js/issues/48`

**Comment by Thorin-Oakenpants** [comment]
CSP: ok, so we keep it for the info factor - but I am wary of enforcing defaults: or rather that I'm maybe more aware of this as a factor when deciding what we do (and likewise: anything we have as active can be a potential banana skin).

That said (a bit like pdfjs I guess), the chances it gets flipped in an emergency by mozilla is pretty slim: it would probably be more likely that something else is changed (a subsequent pref, or something is backed out). I didn't bother to check when it was actually added, but if FF23 is correct that's a long time

So lets just tweak it a little - use `enforce` and add a warning : to be consistent.
```js
/* 2680: enforce CSP (Content Security Policy)
 * [WARNING] CSP is a very important and widespread security feature. Don't FUCK with this!
 * [1] https://developer.mozilla.org/docs/Web/HTTP/CSP ***/
user_pref("security.csp.enable", true); // [DEFAULT: true]
```

thumbs up if you think that's OK - @earthlng 

----

favicon: well, I was looking at almost removing `alerts.showFavicons` but had yet to investigate it further.  OK, I'll do something later using 2 (i.e parts a + b: they go together)

**Comment by Thorin-Oakenpants** [comment]
list in op is just items to debate/consider (feel free to chime in)

update/ thoughts:
 - security delay: this is good as active: a) in case someone changed it to zero to "speed" things up b) I cannot see any risk in this pref (we're essentially enforcing a default: i.e a set time limit)
- added the `1201` + `1270` item (from 69->70 diffs) to the list

**Comment by Thorin-Oakenpants** [comment]
Will add to the list about `0308` - see https://bugzilla.mozilla.org/show_bug.cgi?id=1444426

**Comment by earthlng** [comment]
re: 0308 - "disable OpenSearch search engine updates" or something like that maybe?
They only removed the UI in that ticket but not the pref or the code behind it.

I reckon a lot of people have OpenSearch engines installed since that was pretty much the only way to install a SE for the longest time and the vast majority of OpenSearch engines have an updateURL.

**Comment by Thorin-Oakenpants** [comment]
Yeah, I know. IDK what to call it, maybe just use Mark Banner's wording

```
/* 0308: disable search engine updates (non-built-in, non WebExtension)

/* 0308: disable search engine updates (e.g. OpenSearch)
 * [NOTE] This does not affect Mozilla's built-in or Web Extension search engines
```

I don't really know enough to know if OpenSearch covers it, the (e.g. OpenSearch) is optional

**Comment by earthlng** [comment]
I like the 2nd one better

**Comment by Thorin-Oakenpants** [comment]
@earthlng 

How do you feel about the last two items being made inactive since they are at default?

**Comment by earthlng** [comment]
2032 - I think there were some issues with this on Twitch at some point. Other sites could still act up weird when it's true, IDK. I'd lean more towards keeping it, just in case - but removing it is fine too because it's not *that* important

4002 - No. It doesn't make sense IMO to have inactive prefs with values matching FFs default value.

**Comment by Thorin-Oakenpants** [comment]
If there are compat issues, that's the same for everyone (default setting), and Mozilla usually gets bugzillas on these things (esp the big sites), and they usually reach out to the sites involved. By enforcing the default we would only make it worse - e.g. we'd be seen as causing the problem and an override would be needed

> but removing it is fine too because it's not *that* important

Yup, absolutely not that important. Out it goes :)
