### ISSUE TITLE
Startpage is now on the way to the cyber landfill.

### ISSUE THREAD

**Issue by theWalkingDuck** [ghacksuserjs/ghacks-user.js#841]
[Company updates](https://www.startpage.com/blog/company-updates/startpage-and-privacy-one-group/)

[Who are the owners of Startpage ?](https://support.startpage.com/index.php?/Knowledgebase/Article/View/1260/17/who-are-the-owners-of-startpage)

> We most recently welcomed **Privacy One Group Ltd**, a privacy-focused division that is a separate operating unit of **System1 LLC**, as a significant new shareholder. 

And guess what System1 LLC is ?

A behavioral ad company.

**Comment by bitpixl** [comment]
So what's the recommended searchpage now? DuckDuckGo, which is based in the US?

**Comment by Thorin-Oakenpants** [comment]
There is no recommended search engine. It's outside the scope of this repo and what a user.js can do, and it's also a personal choice
