### ISSUE TITLE
"Bad substitution" errors with updater and prefsCleaner

### ISSUE THREAD

**Issue by theltalpha** [ghacksuserjs/ghacks-user.js#845]
Hallo!

Both updater.sh and prefsCleaner.sh produce a "Bad substitution" error. Specifically:
```
./prefsCleaner.sh: 12: ./prefsCleaner.sh: Bad substitution
./prefsCleaner.sh: 15: ./prefsCleaner.sh: Bad substitution
```

and

```
./updater.sh: 13: ./updater.sh: Bad substitution
./updater.sh: 14: ./updater.sh: Bad substitution
```
I use Debian GNU/Linux 10.2. I have both files in my Firefox profiles directory and invoke them in bash via "sh ./prefscleaner.sh" and "sh ./updater.sh".

What am I doing wrong?

**Comment by rusty-snake** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/blob/8f76d9439f1b7998d100bc0cda316a8f2dcba741/prefsCleaner.sh#L1

The shebang is `bash` and not `sh`. Line 12,15 contains `${BASH_SOURCE[0]}` where `shellcheck --shell=sh prefsCleaner.sh` says  `^---------------^ SC2039: In POSIX sh, array references are undefined.`. Maybe you need to start with `bash prefscleaner.sh`

**Comment by gwarser** [comment]
Debian probably uses "dash" as "sh". Call scripts using "bash".

**Comment by theltalpha** [comment]
Oh man, how stupid of me. You are absolutely right. Thank you!
