### ISSUE TITLE
Position of last parrot when using updater.sh

### ISSUE THREAD

**Issue by theltalpha** [ghacksuserjs/ghacks-user.js#846]
Hallo!

I noticed when using updater.sh with existing user-overrides.js the last parrot is located _before_ the user-overrides section. In my understanding it should be located _after_ the user specific section, so you can verify also the user-specific prefs have been parsed correctly. I moved the parrot now manually to the end of the user.js. It would be nice if the script did that automatically. Or if there was at least a note in the wiki to change the position of the last parrot manually after running updater.sh.

Thank you in advance for consideration!

**Comment by Thorin-Oakenpants** [comment]
Look at the second picture [here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes)

Just add your own parrots
