### ISSUE TITLE
Doesn't work playstation store

### ISSUE THREAD

**Issue by Myrai** [ghacksuserjs/ghacks-user.js#86]
Hi!
with script doesn't work playstation store.
somewhere another place - https://www.esetnod32.ru/download/home/trial/ doesn't work js.
What need for normal work playstation store?
only install this script and ublock.

**Comment by Atavic** [comment]
ghacks-user.js doesn't change javascript behaviour.

On uBlock there are blacklists loaded by default, as EasyPrivacy, that will break some sites.
Are you facing problems like when you click on _Для Microsoft Windows, 32/64-битные версии_ nothing happens? The issue is a JS script blocked by uBlock.

**Comment by Thorin-Oakenpants** [comment]
No url given, no description of behavior broken, no testing or narrowing down of possible preferences, no troubleshooting attempted - how about turning off ublock, for instance. Cannot test or replicate. Invalid.

**Comment by Myrai** [comment]
Sorry, haven't place for wrote message.
1. clean firefox 53 and you script.
when we login on https://store.playstation.com/#!/en-us/home/games
{"error":"invalid_client","error_description":"Bad client credentials","error_code":4102,"parameters":[]}
and see that.
What's wrong?

**Comment by Thorin-Oakenpants** [comment]
I do not have a login so I cannot test that, but loading https://store.playstation.com/#!/en-us/home/games causes zero issues for me (I enabled all scripts in NS, allowed all thru uBo and uMatrix).

See this: https://community.us.playstation.com/t5/PlayStation-Network-Support/Cannot-login-PSN-store-via-Chrome/td-p/45352485  (and there are more google search results)

The solution in the above link was to do with allowing cookies

> The trick is that you need to allow cookies from `sonyentertainmentnetwork.com`

**Comment by Myrai** [comment]
First this manual i've read and do it and all nothing.
We have problem.
Developers nobody have psn for test?

**Comment by Thorin-Oakenpants** [comment]
@Myrai Have you enabled cookies? You can use an extension to control cookies and third party cookies on a site by site basis. The actual cookie setting in the user.js is 2701: `network.cookie.cookieBehavior`. A value of 0 allows both cookies and 3rd party cookies, which from the previous link I gave is what you will want.

**Comment by earthlng** [comment]
@Myrai it could also be network.http.referer.XOriginPolicy. Try setting it to 0. If that doesn't help, reset all prefs in about:config for which there's a [SETUP] or [WARNING] tag in the user.js.
If you follow the [Troubleshooting tutorial](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4:-Troubleshooting) you should be able to identify the prefs that cause the problem. NOTE it can be more than 1 pref that is causing the problem!

**Comment by earthlng** [comment]
FF53, new profile, latest master user.js, no addons - created an account @ https://store.playstation.com/ with only changing `network.cookie.cookieBehavior` to 0. It was a pain in the ass to register but in the end it worked and signing out and logging in again also worked fine. I don't know what your problem is but it's definitely not this user.js. closing this again

**Comment by Thorin-Oakenpants** [comment]
Thanks @earthlng . I suspect English is not @Myrai 's first language, but there may be several reasons

- cookies, which we highlight as a pref to look at (this could be his problem, I suspect it is)
- Myrai mentions uBo in the first post, but on a subsequent test doesn't - anyway, XSS blocking would not help as it is needed - see earlier comment about `sonyentertainmentnetwork.com`
- There could be a MiTM AV (although sony would have decent ciphers) interfering for all we know

> it's definitely not this user.js

Well to be fair, it probably is this user.js - re cookie setting - BUT, we mention this, lots! Maybe I should add a line to the short readme in the user.js ?

```
- Search this file for the "[SETUP]" tag to find SOME common items you could check before
  using to avoid unexpected surprises: eg COOKIES are DENIED by default (see 2701)
```
