### ISSUE TITLE
Can't add shortcuts to uBlock Origin

### ISSUE THREAD

**Issue by crazyyzarc** [ghacksuserjs/ghacks-user.js#861]
I don't know any user.js setting that prevents blocking shortcuts.
In my other Firefox profile (same add-ons) it works, but with the Ghacks-user.js adding shortcuts does not work
![2019-12-14 12_49_59-uBlock₀ — Dashboard](https://user-images.githubusercontent.com/4954535/70848409-ea074b00-1e68-11ea-9834-7eb21446b4aa.png)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/issues/391#issuecomment-486137363
