### ISSUE TITLE
4YI: some issue with camera claimed to be being used for tracking

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/ghacks-user.js#868]
https://medium.com/@mva.name/browser-activating-the-front-facing-camera-big-brother-or-just-a-bug-e7a2ff9d6856

**Comment by Thorin-Oakenpants** [comment]
- [1578073](https://bugzilla.mozilla.org/show_bug.cgi?id=1578073) - probably this one, but it says android
- [1492223](https://bugzilla.mozilla.org/show_bug.cgi?id=1492223)
- [1466148](https://bugzilla.mozilla.org/show_bug.cgi?id=1466148) - might be relevant

All mention permissions being bypassed, and all are to do with WebRTC (which we disable)

**Comment by Thorin-Oakenpants** [comment]
I was already tracking/aware of this: and it's not a problem for us in several ways (don't get me wrong, it's a bug and I didn't dig into the specifics a lot) but it requires WebRTC. RFP also mitigates the enumerate devices

```
 ** 1372073 - spoof/block fingerprinting in MediaDevices API (FF59+)
      Spoof: enumerate devices reports one "Internal Camera" and one "Internal Microphone" if
             media.navigator.enabled is true (see 2505 which we chose to keep disabled)
```

closing
