### ISSUE TITLE
canvas leak when isolation on

### ISSUE THREAD

**Issue by bchtrue** [ghacksuserjs/ghacks-user.js#871]
Firefox 71 / Linux + CanvasBlocker addon

Look like default ghacks-user.js settings lead to a complete privacy loss cross-browser, cross-virtual-machines. 

Cause by canvas leak by javascript. Test page: https://browserleaks.com/canvas
As you can see firefox isolation not work and no canvas popup with allow/disallow.

This test page show signature. The same signature will be at each instance of firefox (multi browser instances) on the same machine. Tor Browser also leak by the way. 

I found that to prevent leaking need to switch off at `user-override` this settings:

`user_pref("privacy.resistFingerprinting.block_mozAddonManager", false);
user_pref("privacy.resistFingerprinting", false);`

and after installing CanvasBlocker addon it can fake/hide this leak. If this settings switched ON then CanvasBlocker addon show that he successfully fake canvas, but it's not and browser leak. 

**EDIT:** Seems this signature is for all instances of all firefox browsers across the web? False alarm from me? Sorry. What signature do you get? :-)

**Comment by Thorin-Oakenpants** [comment]
- https://github.com/kkapsner/CanvasBlocker/issues/158
- https://github.com/ghacksuserjs/ghacks-user.js/issues/767
- https://github.com/ghacksuserjs/ghacks-user.js/issues/350 - see first post, scroll down to `Canvas`

If RFP is on, you will return a white canvas
- [browserleaks](https://browserleaks.com/canvas) = `E054455A135647B16D017742944E3B03`
- [CB tests](https://canvasblocker.kkapsner.de/test/test.html)
   - `e5d9fd78536844cc8a4144ddb7a03eb9628f12c7c8b7828f942cadf6efb79ac0`
   - `03fedeb80c3f8ebf2ed864024e9967256468d64dbe847f202ad06a60f2b3d9b3`
- [TZP#canvas](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#canvas) - it tells you with a red or green

Extensions can't modify the RFP **canvas** protection (this is not true for all RFP stuff). However, you can set a site permission to allow canvas (there will be a canvas icon in the urlbar), and *then* canvas blocker can do what you tell it to
