### ISSUE TITLE
Settings which break icloud.com

### ISSUE THREAD

**Issue by CyBiS** [ghacksuserjs/ghacks-user.js#872]
Hi,

this is a follow-up thread to https://github.com/ghacksuserjs/ghacks-user.js/issues/850 as unfortunately additional settings also break `icloud.com` for me.

As discussed in previously mentiond issue, following configuration regarding `network.http.referer.XOriginPolicy` are necessary.

- Install the [Smart Referer ](https://addons.mozilla.org/de/firefox/addon/smart-referer/) addon.
- Use the addon's `strict` mode, disable the whitelist, disable the rewrite mode and use following manual exceptions (`source -> destination`) in order for all iCloud apps to work:
`*.icloud.com -> *.apple.com`
`*.icloud.com -> *.icloud.com`
- Configure `network.http.referer.XOriginPolicy = 0`.

Unfortunately additional configuration changes are necessary in order to get all the iCloud apps to work. Consider **changing them only temporarily** if you really needs those apps.
- As iCloud Notes needs WebGL, following setting needs to be changed in addition:
`webgl.min_capability_mode = true`
- Unfortunately for iCloud Drive one of the subdomains seems to use the insecure SSL cipher suite `TLS_RSA_WITH_AES_128_CBC_SHA` which is vulnerable to the [robot attack](https://robotattack.org/). Therefore the SSL safe regonition would need to be disabled:
`security.ssl.require_safe_negotiation = false`

BR

**Comment by crssi** [comment]
Just out of curiosity...

1. Why set SR to `strict` and not `lax`?
2. How `webgl.min_capability_mode = true` works when `webgl.disabled = true`?

**Comment by CyBiS** [comment]
> 1. Why set SR to `strict` and not `lax`?

I'm using following [base confiugration](https://www.privacy-handbuch.de/download/moderat/user.js) with some additional settings from this user.js here. Sorry for the confusion, I should have mentioned that. In that base configuration `network.http.referer.XOriginPolicy = 2` is used, so the `strict` mode is what I'm looking for within Smart Referer.

> 2. How `webgl.min_capability_mode = true` works when `webgl.disabled = true`?

Thanks for the hint, the correct setting is of course `webgl.min_capability_mode = false` assuming that `webgl.disabled = false` which is true for the base config I'm using.

The purpose of this discussion is just to document the settings I had to use in order to get the iCloud page working. Might be useful to other users as well.
