### ISSUE TITLE
Detection test problem

### ISSUE THREAD

**Issue by bugrepo** [ghacksuserjs/ghacks-user.js#873]
Detection test does not pass on Firefox 71 with user.js version 71 Release.

https://canvasblocker.kkapsner.de/test/detectionTest.html

All must be green, nothing red.

![Test problem](https://user-images.githubusercontent.com/47493656/71758220-f80f2100-2e94-11ea-8e1f-956cfe9a0a0b.png)

**Comment by Thorin-Oakenpants** [comment]
RFP
- uses a static canvas: 10x10pix white canvas: therefore it's detectable: e.g I paint a canvas as all red, it returns white
- users all present the same result, therefore it's not an entropy issue
- RFP is not trying to hide that it exists (or that Tor Browser is the Tor Browser etc: you get the same results using TB)

The two tests above are for when you **fake** a canvas
