### ISSUE TITLE
Removing a pref from user.js via user-overrides.js? (Enabling a checkbox)

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#876]
So I use the recommended way of applying my changes documented [here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.2-Applying-Your-Changes).

(I am trying to enable the the DRM-controlled content checkbox: General>DRM Content>Play DRM-controlled content).

I want to add something to my user-overides.js so that I am given back control of it (via the checkbox, because I like this flexibility) rather than it sticking to what is stated in user.js (or user-overrides.js).

I can delete the pref from user.js but I'd rather add something to my user-overrides.js so that it is remembered after updating the user.js.

Is this something I can do?

**Comment by Thorin-Oakenpants** [comment]
The user-overrides.js is only used with the updater scripts (windows only I think, not sure about the other one) - so that when you update it re-applies your overrides to the user,.js. Firefox itself does not look at the user-overrides.js file..

If you want to change an active pref (active meaning that the pref is not commented out), then add them to the very end of the user.js

```js
/******
* name: ghacks user.js
 ....
 blah blah
*/

/* END: internal custom pref to test for syntax errors ***/
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");

/* zdat's overrides */
user_pref("media.eme.enabled", true); // allow DRM, see 1830
user_pref("_user.js.parrot", "zdat's overrides applied");
```

**Comment by earthlng** [comment]
@zdat 

> I want to add something to my user-overides.js so that I am given back control of it (via the checkbox, because I like this flexibility) rather than it sticking to what is stated in user.js (or user-overrides.js).

only the updater script **for Windows** supports that in an automated way.
If you're on Windows you can use the updater's -merge parameter and add a special command in your user-overrides.js to comment-out the EME pref.
see https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.3-Updater-Scripts

The easiest way to use the same set of parameters repeatedly is to create a shortcut to the updater.bat, add the parameter(s) you want to the command line in that shortcut and then always use that shortcut to run the updater.

---

> The user-overrides.js is only used with the updater scripts (windows only I think, not sure about the other one)

both updater scripts support user-overrides.js.
