### ISSUE TITLE
gumtree.com.au secure connection failed

### ISSUE THREAD

**Issue by fu8765** [ghacksuserjs/ghacks-user.js#877]
Works well with standard firefox.
and being that gumtree is owned by ebay, I wouldn't think they'd leave a security bug in there?

any ideas?

**Comment by Thorin-Oakenpants** [comment]
You will have to provide more information. What is the error message, what are the steps to reproduce. Have you actually tired to [troubleshoot](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting) it? Have you confirmed it is a user.js setting that causes it (new profile, no extensions etc). Did you look at the `[SETUP` tags?

Feel free to reopen if you need more help or have more information

**Comment by rusty-snake** [comment]
`Fehlercode: SSL_ERROR_UNSAFE_NEGOTIATION`

https://github.com/ghacksuserjs/ghacks-user.js/blob/e431b324c8433117c90e3e5d72eed258bc54d613/user.js#L644-L653
