### ISSUE TITLE
A noob question

### ISSUE THREAD

**Issue by ScaryMimikyu** [ghacksuserjs/ghacks-user.js#885]
After implementing the user.js and checking the browser console for any errors, i found this message about the FPI. Would that be an error/something to fix or is everything ok?

I can browsing normally, but I have doubts if everything is ok.

![error](https://user-images.githubusercontent.com/59137729/73126384-d0017200-3fa9-11ea-86b0-0d686e726fed.png)

**Comment by gwarser** [comment]
uMatrix?

**Comment by ScaryMimikyu** [comment]
@gwarser Yes, umatrix is installed.

**Comment by ScaryMimikyu** [comment]
Question solved, thanks @gwarser .
