### ISSUE TITLE
No Scratchpad in Firefox 72

### ISSUE THREAD

**Issue by arnauldb** [ghacksuserjs/ghacks-user.js#886]
Hello,

How can I run the scripts as there is no Scratchpad anymore in Firefox 72 +?

Thank you.

**Comment by Thorin-Oakenpants** [comment]
Use the console's multi-line editor mode (ctrl-B) - go [here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/3.1-Resetting-Inactive-Prefs-[Scripts]) and scroll to the very bottom of the page and click where it says "How To Run Our Scratchpad Cleanup Scripts in FF72+"
