### ISSUE TITLE
Resource URI Leak add-on setting causes Firefox 53 login/password problems

### ISSUE THREAD

**Issue by kaliostro2** [ghacksuserjs/ghacks-user.js#89]
Hello.

I use recommended add-ons. Everything was fine until this time. But with the release of Firefox 53, everything has changed. I sometimes began to lose forms of filling in the login and password on many sites.

<a href='https://hostingkartinok.com/show-image.php?id=5837f0d3be7281a6cffef9da22c4e651' title='picture hosting'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/5837f0d3be7281a6cffef9da22c4e651.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=4f75f0dc35b83baba6050de2ccc1f3b3' title='хостинг скриншотов'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/4f75f0dc35b83baba6050de2ccc1f3b3.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=d7c9cfcfd118340050a14aec8f8f8d64' title='разместить изображение'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/d7c9cfcfd118340050a14aec8f8f8d64.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=ee30224243ef24a9d32942c398b856da' title='бесплатный хостинг картинок'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/ee30224243ef24a9d32942c398b856da.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=8e1d15f8900087b56d7ad2f592d689f2' title='хостинг фото'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/8e1d15f8900087b56d7ad2f592d689f2.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=4f999e54616283bde9972a9b2a4ac0ab' title='хостинг изображений'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/4f999e54616283bde9972a9b2a4ac0ab.png'  /></a>

**Comment by crssi** [comment]
Try without plugins... otherwise here: [Troubleshooting](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4:-Troubleshooting)

**Comment by earthlng** [comment]
Hi, if you give us the links to those sites we can take a look and try to help

**Comment by kaliostro2** [comment]
It's not just these sites. This problem manifests itself on many sites. I do not use plugins. If I add any addon that does not support e10 then it (e10) shuts down and everything works fine.

**Comment by kaliostro2** [comment]
Ok. I think I found the source of the problem. It calls addon "No Resource URI Leak" if it has an option enabled in it "Block Web-exposed subset of chrome:// URIs from Web". The author honestly warns "Enabling it may break certain extensions or badly designed Web sites". But until Firefox 53, this was not even with the option enabled. Previously, this only affected the settings of Decentraleyes. They did not show up, but the addon worked fine.

**Comment by earthlng** [comment]
LOL I didn't even know that Decentraleyes had an options page. Thanks for pointing that out :)
The "No Resource URI Leak" causes quite a lot of problems. We can only hope that mozilla deals with the underlying problem soonish and in a way that doesn't cause all those problems. For example http://httpbin.org/headers sends JSON but doesn't load any resources or chrome files, but FF then pulls in some devtools-jsonview resources to "try" display the JSON which is then blocked by the addon.
Tbh the addon seems to do more harm than good, so I'm considering disabling it completely.

**Comment by Thorin-Oakenpants** [comment]
> The "No Resource URI Leak" causes quite a lot of problems

None for me (default settings)

> We can only hope that mozilla deals with the underlying problem soonish and in a way that doesn't cause all those problems

Good luck with that. It was started, stalled, got stale, grew some mold, .... and finally, a few weeks back, after sitting in the ACTIVE bugs (of tgor uplift) for like a year (I mean, come on man, they even had a patch and all and were so close) .... it has been shoved way way down to the bottom of the heap as unassigned and no-one cares.

It got a lot of attention 11 months ago after renewed interest when the add-on came out. After 3 months everyone dumped it and couldn't be arsed, IMO. The leak is now 4 years old .. FOUR. YEARS.! FFS

https://bugzilla.mozilla.org/show_bug.cgi?id=863246

**Comment by Thorin-Oakenpants** [comment]
So @kaliostro2 Can you confirm exactly that it is the setting "Block Web-exposed subset of chrome:// URIs" which carries a warning, in "No Resource URI Leak" that causes this issue. If so, then please edit the title which implies the user.js causes this.

**Comment by earthlng** [comment]
> None for me (default settings)

so that site I linked works for you?

**Comment by kaliostro2** [comment]
Yes. I can confirm "Block Web-exposed subset of chrome:// URIs" which carries a warning, in "No Resource URI Leak" that causes this issue. On a firefox browser without e10, this problem does not appear. I never said that user.js created this problem, but I will remove the mention of it.

**Comment by Thorin-Oakenpants** [comment]
> title which **IMPLIES** the user.js causes this

It's all good, I will amend the title

**Comment by kaliostro2** [comment]
I found some more issue that create this addon with enabled option "Block Web-exposed subset of chrome:// URIs" and active e10.

1: Disappears vertical scrollbar on sites.
2: Disappears search form on sites.

**Comment by earthlng** [comment]
Ok, Pants has no problems with the addon because he doesn't "Block Web-exposed subset of chrome:// URIs". But same as OP, I also block chrome URIs and that's why I sometimes had some problems I guess.

What you can do if you want to keep blocking chrome URIs is to "Enable debugging messages" and check the console for what needs to be whitelisted for a page or addon to work.
I think whitelisting ("Exposing domains") is still preferable over disabling that protection completely.

Fe. the new JSON viewer doesn't work unless "devtools" is added as a whitelisted domain for both chrome and resource. (testpage: http://httpbin.org/headers) [with NoScript installed you need to enable scripts for that domain and make sure "Block scripting in whitelisted subdocuments of non-whitelisted pages" is unchecked, for the JSON Viewer to work]
So, atm I have "Exposed resource:// domains" `devtools` and "Exposed chrome:// domains" `devtools, decentraleyes`

**Comment by Thorin-Oakenpants** [comment]
This add-on will become legacy anyway. It cannot be ported to WE.

**Comment by Thorin-Oakenpants** [comment]
FYI: you can track the developer's issue here: https://notabug.org/desktopd/no-resource-uri-leak/issues/13

**Comment by Thorin-Oakenpants** [comment]
Appreciate the info on recommended add-ons having issues (and yup, definitely take the issue up with the developer in each case).

I have added a link to this issue under the add-on in the wiki so people are aware of it. Thanks.

**Comment by Thorin-Oakenpants** [comment]
It also seems this add-on has stopped working in FF55 - see https://notabug.org/desktopd/no-resource-uri-leak/issues/14 . I will add a note to the add-ons wiki page
