### ISSUE TITLE
Pants ToDo: noopener v2.0 troubleshoot

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#891]
a clean new ticket so I don't have to wade through anything

[from #860](https://github.com/ghacksuserjs/ghacks-user.js/issues/860#issuecomment-574308366)
> console for window.opener be gone script says
> - `Cleared window.opener @ https://mathiasbynens.github.io/rel-noopener/malicious.html`
> - `Cleared window.opener @ https://mathiasbynens.be/demo/opener`
> 
> But the test page still updates to #hax . There is nothing else in the console. I'll try it in a new profile when I get time, to see if I can troubleshoot it.

See if I can troubleshoot what in my setup causes this, as it may be something common

**Comment by Thorin-Oakenpants** [comment]
don't hold your breath .. I have other yaks to shave, and bicycles to shed :)

**Comment by Thorin-Oakenpants** [comment]
note to self: https://bugzilla.mozilla.org/show_bug.cgi?id=1522083 is about to land

**Comment by Thorin-Oakenpants** [comment]
Firefox Nightly 79, no extensions, practically a vanilla profile
- installed GM
- added the script
- had to manually add `http://*/*` and `https://*/*` to user matches
- test site: https://mathiasbynens.github.io/rel-noopener/
- `dom.targetBlankNoOpener.enabled` = false

**First link**
- clicked, opens `malicious.html`
- console says `Cleared window.opener @ https://mathiasbynens.github.io/rel-noopener/malicious.html`
- close malicious
- original page is now `#hax`

reload the test page

**Second link**
- clicked, opens `https://mathiasbynens.be/demo/opener`
- console says `Cleared window.opener @ https://mathiasbynens.be/demo/opener`
- close demo
- original page is now `#hax`

Either I'm doing something wrong, or the script doesn't work. This is the [same result](https://github.com/ghacksuserjs/ghacks-user.js/issues/860#issuecomment-573950924) I got 4 months ago

> Anyway, the first two tests fail and tell me I am hacked (and I reset to the original page for each test)

**Comment by Thorin-Oakenpants** [comment]
@earthlng

**Comment by earthlng** [comment]
I tested it just now in nightly and the latest beta and can confirm that the script doesn't run at document-start with GM. It does work 100% with Firemonkey!

Then I tested the script again in my main profile with GM and it sometimes works but only when I load a page for the very first time in a fresh container. When I refresh the page the script runs too late but when I shift-refresh it *sometimes* run correctly at document-start.
So the way that GM injects scripts which are supposed to run at document-start is just not reliable enough!

When I said in https://github.com/ghacksuserjs/ghacks-user.js/issues/860#issuecomment-566132112 that 

> I tested GM (v4.9) and FM and both are able to run scripts at document start.

I apparently didn't notice that it doesn't reliably run at document-start in all circumstances (with GM).

ps:

> - had to manually add `http://*/*` and `https://*/*` to user matches

why? the [script](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.1-User-Scripts) already has the `@match` keys for both http+https

**Comment by Thorin-Oakenpants** [comment]
> had to manually add http://*/* and https://*/* to user matches

I got no console warning, so it wasn't being applied. So I took a stab in the dark and added those manually under settings and **then** it was applied

**Comment by earthlng** [comment]
I added a warning to the wiki page

**Comment by Thorin-Oakenpants** [comment]
I only have one script now: `windows.name` - I thought the JonDoNym site tested that? But now I'm confused
