### ISSUE TITLE
FF 73 override services.settings.server pref

### ISSUE THREAD

**Issue by Asukaromba** [ghacksuserjs/ghacks-user.js#892]
Almost 1.5 years ago, with the release of the new version, I noticed that firefox connects one time every 24 hours with **firefox.settings.services.mozilla.com**. Not finding then a solution to the problem, I just disabled it globally with killswitch **user_pref("services.settings.server", "");**. But today I realized that it doesn’t work anymore. Mozilla set me up again. I "play" with every new prefs from https://github.com/ghacksuserjs/ghacks-user.js/issues/883, but it did not help. What's going on? Why killswitch not work anymore? When they stop taking control from users?

**Step to reproduce:**
1: Open about:config
2: Find **services.settings.server** pref and remove everything.
3: Find **app.update.lastUpdateTime.services-settings-poll-changes** and remove everything. This is pref where the time of the last connection attempt is marked (in order not to wait 24 hours).
4: Close browser and open again.
5: After 30 sec. there will be an attempt to connect to **firefox.settings.services.mozilla.com**

I need to disable this. What do you advise?

**Comment by Thorin-Oakenpants** [comment]
The ghacks user.js does not have the pref `services.settings.server` in it, as it is not a privacy, security or fingerprinting issue. If you want to disable update checks, then use Enterprise Policies

**Comment by Asukaromba** [comment]
Are you kidding? The browser "calls home" for no reason, but you don't care? OMG.

Update check disabled long time ago.

**Comment by Thorin-Oakenpants** [comment]
Prove to me that there is a privacy, tracking, security or fingerprinting issue instead of just seeing things in black and white

**Comment by crssi** [comment]
@Asukaromba you are overreacting without any proof.
Did you do any analysis of that traffic or you are grunting "just in case"?
I am even against telemetry, since it helps to improve the product (FF in this case).

**Comment by Kurbatov863** [comment]
They lock it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1598562
