### ISSUE TITLE
v73: Making connections at startup

### ISSUE THREAD

**Issue by waqas** [ghacksuserjs/ghacks-user.js#893]
I have setup config in a way that FF never made any connection to any server by default when opening (blank for homepage). Now same profile and in v73 it makes 2 connections to cloudflare.net servers, I suspect these are to mozilla but don't know why. There is nothing in release notes to suggest anything like this. Please help. Thanks.

**Comment by Thorin-Oakenpants** [comment]
What are you trying to achieve here? There are many legitimate reasons for Firefox to make background connections: although I assume that most of these are disabled: e.g. sync, snippets, activity stream, revocation lists, etc etc. One thing we don't block is update checks (see #883 )

What are the cloudflare addresses?

**Comment by crssi** [comment]
Interestingly similar to #892... and both OPs first issues ever. 😉

**Comment by Thorin-Oakenpants** [comment]
thanks crssi - I linked to the wrong issue
