### ISSUE TITLE
Firefox android ReferenceError: user_pref is not defined

### ISSUE THREAD

**Issue by Parlotten** [ghacksuserjs/ghacks-user.js#894]
Hi again,
I'm using Frefox 70.0.1 and my mobile version is 68.5.0. I do everything according to the wiki guide. When I am trying to install I get the following error:
/*
Exception: ReferenceError: user_pref is not defined
@Scratchpad/3:83:1
getEvalResult@resource://devtools/server/actors/webconsole/eval-with-debugger.js:151:28
exports.evalWithDebugger@resource://devtools/server/actors/webconsole/eval-with-debugger.js:122:31
evaluateJS@resource://devtools/server/actors/webconsole.js:1167:38
evaluateJSAsync/<@resource://devtools/server/actors/webconsole.js:1065:29
exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:111:22
*/
If needed I can provide a link to a yt video that shows what I'm doing

**Comment by earthlng** [comment]
it should all be explained here: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android

**Comment by Parlotten** [comment]
There you go
https://youtu.be/ey8ruvXFa5I

**Comment by earthlng** [comment]
I think you're running it in the context of the debugging page. Click on the Inspect button behind the about:config thing under Tabs after you connected to the device (instead of pressing F12?).

Then instead of "Display" also try "Run" or "Execute" or whatever it's called.

And if it still doesn't work, check the console tab for any additional information that could be useful.

**Comment by Parlotten** [comment]
https://youtu.be/KCZ7uc6z_zA

Console tab is empty
![Desktop Screenshot 2020 02 14 - 19 12 28 51](https://user-images.githubusercontent.com/57270598/74556643-ca6eca80-4f5e-11ea-891e-69e1ee88d957.png)

**Comment by Parlotten** [comment]
https://youtu.be/7TCO14h06ZU
![Desktop Screenshot 2020 02 14 - 20 00 01 11](https://user-images.githubusercontent.com/57270598/74559423-a8784680-4f64-11ea-9b94-8c423fbc0c4b.png)

Fortunately, I forgot to turn off the recording. I know quite long but I consider it's worthwhile. 
I am not a native English speaker so sorry for spelling I'll edit it later

**Comment by Parlotten** [comment]
if you want, you can use my video for the wiki. On request I can trim it so that are no Shadowplay inserts at the beginning and at the end.

**Comment by earthlng** [comment]
so the solution was to reload about:config on the phone and then run the script again, right?

> if you want, you can use my video for the wiki

Thanks but I don't think we need it, I'll just add a note to the wiki about this particular error

**Comment by earthlng** [comment]
> add a note to the wiki about this particular error

[done](https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android/_compare/dd1a95bbbf889319282b9dde9db19f9ba5a7d1f2...560812a32d51449f58147ef83fb03d29ec54eb42)
