### ISSUE TITLE
anyone else? disabled exts get auto-re-enabled [solved: restart FF]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#897]
I'll post a short gif to illustrate, but I just went to flip HTTPS-Everywhere to see what life it without would be like and I can't

I click the little slider to off, and as soon and I lose focus/click-off to the side, it re-enables itself. It does it for all installed extensions. I think it might have something to do with trusted domains. Pretty sure this didn't happen in 72 (when I was flipping earthling's window opener be gone extension on and off so I could test his script instead). If need be, I can retest in an old 72 I have backed up.

**Comment by Thorin-Oakenpants** [comment]
![ext](https://user-images.githubusercontent.com/16656956/74819828-e379d180-52f8-11ea-8472-551c1ff321ea.gif)

**Comment by 2glops** [comment]
Disabling extensions remains here - FF 73 Linux

**Comment by Thorin-Oakenpants** [comment]
I've contacted someone at Mozilla who works on extension stuff. I've narrowed it down to a timeout - the extension is not shutdown, and therefore it fails (and is not moved to the disabled section). Instead, after x milliseconds, the state of the control is refreshed to indicate that its still enabled

```
Timeout while waiting for extension child to shutdown: "window.opener be gone" (ID: window.opener-be-gone@earthlng.org, moz-extension://14ac0ff2-5b86-49d0-aefe-6bbb8aace5e0/) Extension.jsm:2473
    shutdown resource://gre/modules/Extension.jsm:2473
    AsyncFunctionNext self-hosted:696
```

I haven't tried to troubleshoot it yet to see if any prefs are responsible.

**Comment by Thorin-Oakenpants** [comment]
NFI why extension shutdown would suddenly fail after a short time (browser was only open for a couple of hours) - but I restared Firefox and now all is fine. So I'll just chalk this one up to experience

**Comment by Thorin-Oakenpants** [comment]
This is not invalid - the image attached clearly shows that!
