### ISSUE TITLE
binance.com doesn't display right 

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#899]
If you go to binance.com, the site doesn't display right at all. If you compare it to how it displays on a default Firefox; you can't even see or click the login button.

First issue I'm having that is like this.

**Comment by Thorin-Oakenpants** [comment]
I just applied the entire user.js to a new profile in FF73 and the site looks and works just fine (not sure about logging in: I mean the look etc). Mousing over the nav bar at the top produces drop down menus, I can select different inputs (USD)/outputs (ETH etc), and can click on login, register etc - it all looks and seems to work just fine.

The QR code will fail unless you allow a RFP canvas exception.

If the site is in the 1000 pixel wide RFp window, the nav bar is slightly different. Just widen the browser window and the nav bar will change automatically as it gets more width <-- that's the only visual difference I see - unless you mean `letterboxing`, which doesn't change how the site looks or behaves, it just boxes up the site in set viewport sizes

If you're talking about anything different - then check your extensions or overrides aren't doing weird things. Feel free to re-open if I'm off the mark in my analysis - but you need to troubleshoot things first - marking as invalid

**Comment by Thorin-Oakenpants** [comment]
I even wrote a wiki page on troubleshooting
- https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.4-Troubleshooting

**Comment by zdat** [comment]
> 
> 
> I just applied the entire user.js to a new profile in FF73 and the site looks and works just fine (not sure about logging in: I mean the look etc). Mousing over the nav bar at the top produces drop down menus, I can select different inputs (USD)/outputs (ETH etc), and can click on login, register etc - it all looks and seems to work just fine.
> 
> The QR code will fail unless you allow a RFP canvas exception.
> 
> If the site is in the 1000 pixel wide RFp window, the nav bar is slightly different. Just widen the browser window and the nav bar will change automatically as it gets more width <-- that's the only visual difference I see - unless you mean `letterboxing`, which doesn't change how the site looks or behaves, it just boxes up the site in set viewport sizes
> 
> If you're talking about anything different - then check your extensions or overrides aren't doing weird things. Feel free to re-open if I'm off the mark in my analysis - but you need to troubleshoot things first - marking as invalid

Can't say the same for me. Tested it in a fresh firefox profile with a fresh user.js; so many elements are missing. For some reason I can't attach an image to show you, not sure if that could be to do with the user.js lol.

**Comment by Thorin-Oakenpants** [comment]
What OS are you on (not that I think it makes a difference)?

The fact you can't upload an image on github also strikes me as unusual - if you wanted to, you could attach it using a fresh profile **before** you apply the user.js

Does the site/elements all look OK in a fresh profile without the user.js? - This is step one in the troubleshooting

What does the console show when you get missing elements?

**Comment by earthlng** [comment]
@zdat you should really learn how to use the troubleshooter script. It took me ~30 seconds to find the problematic pref with the script. But I'm not gonna spoil it yet ;) Just try it yourself

**Comment by Thorin-Oakenpants** [comment]
> It took me ~30 seconds to find the problematic pref

Lucky you. I can't even find the problem

**Comment by zdat** [comment]
Thanks guys. I used the troubleshooter script for the first time, it seems to be very useful :)

> 
> 
> @zdat you should really learn how to use the troubleshooter script. It took me ~30 seconds to find the problematic pref with the script. But I'm not gonna spoil it yet ;) Just try it yourself

I found it hehe. It was `user_pref("network.http.referer.XOriginPolicy", 1);` ;)

**Comment by Thorin-Oakenpants** [comment]
I am going to label invalid because OP didn't use troubleshoot (guide, tags, script) - and the pref is already clearly marked with a setup tag
