### ISSUE TITLE
discussion: change version numbers and do releases

### ISSUE THREAD

**Issue by Roman-Nopantski** [ghacksuserjs/ghacks-user.js#9]
I propose that we start using version numbers to match Firefox. When the user.js is ready for the next stable, eg 52, I commit changes to the date and version number and create a release. I assume the release will be an archived version of all files (so far license and use4r.js) - right?

This way users can easily get the version that is applicable to their FF - starting from 51+. I know it doesn't exactly help ESR but is a good starting point i.e take version 45-51 as applicable and uncomment deprecated for ESR 45, etc - any pref active not used in code is harmless, if that makes sense.

So, should we do this? Change the current user.js to version 51, change the release date to today, and make a release with the tag `51` ?

**Comment by licaon-kter** [comment]
So you'll maintain multple versions ESR and current and dev/aurora/whatever?

**Comment by Roman-Nopantski** [comment]
No, just stable. I meant I will archive off a v51 (like right now, as its all set for this version), then in 6 or 8 weeks time when we're ready, I'll archive off a v52, then 53 etc from now on.

Based on the stable releases, a user should be able to create an ESR version if they want (by uncommenting deprecated which is version numbered) - there will be prefs that don't apply because not everything lands in ESR at the same time, but they will be harmless.

**Comment by earthlng** [comment]
I like the idea. It would make it easier for everyone who doesn't follow this project closely.
'I assume the release will be an archived version of all files - right?' - idk, try it and see how it goes.

**Comment by Roman-Nopantski** [comment]
@earthlng Indeed, the v51 has everything in the user.js. Future versions we will strip out the readme etc and appendices and they will be in the readme (and wikis?). I think the whole thing becomes a zip for download. Just waiting for some more comments before I do anything rash

PS: I am awaiting you to accept being a collaborator, and then I can assign you write permissions

**Comment by earthlng** [comment]
Yeah sorry, took me a while to find it but I've now accepted your invitation.

**Comment by Roman-Nopantski** [comment]
Cool, you are now a repo admin. Don't f**k up buddy .. I know where you live.

**Comment by Roman-Nopantski** [comment]
Done, easy as pie. Check the commit, it has a link to releases and I also fixed up the new home url and author info
