### ISSUE TITLE
uMatrix 0.9.3.6 user-agent leak

### ISSUE THREAD

**Issue by kaliostro2** [ghacksuserjs/ghacks-user.js#90]
Just accidentally discovered the leak a real user-agent for which spoofing is responsible uMatrix.

In order to reproduce the leak it is necessary:

1: Go to https://mega.nz
2: Open about:config in new tab and change **dom.storage.enabled** to **false**
3: Go back to the tab with https://mega.nz and you will see a window with an error and your real user-agent.
<a href='https://hostingkartinok.com/show-image.php?id=d3da6d0a08a678cc483aa95114132616' title='фотохостинг'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/d3da6d0a08a678cc483aa95114132616.png'  /></a>

**Comment by Atavic** [comment]
Do you actually logged into mega before? Do you have cookies stored from that site?

**Comment by kaliostro2** [comment]
No.

**Comment by kaliostro2** [comment]
Is there a good add-on for UA Spoofing?

PS: With e10 support.

**Comment by kaliostro2** [comment]
Tested all the add-ons specializing in UA Spoofing. They all have the above problem. Damn.

**Comment by Thorin-Oakenpants** [comment]
Appreciate the info on recommended add-ons having issues (and yup, definitely take the issue up with the developer in each case).

FWIW (and its a shame uMatrix which we recommend has a UA spoofing feature), we do not recommend UA spoofing. See #23 simply for this reason (as outlined in this issue) - that there are so many holes and other means of detecting various parts of the UA, that all you do is raise entropy (by adding more bits when these are detected and the values differ).

There are a couple of tor uplift tickets to enforce UA spoofing with privacy.resistFingerprinting, and hopefully this is the answer (large number base, an enforced set of values, and holes closed eg leaks via JS, via iframes, etc)

**Comment by earthlng** [comment]
@kaliostro2, very good report, thanks mate!

@Thorin-Oakenpants, why is this closed? It's not fixed yet is it? And just because we recommend against spoofing UA, there's still a bug in one of the main addons we recommend. This should remain open until it's fully fixed IMO.

**Comment by Atavic** [comment]
As @earthlng said: https://github.com/gorhill/uBlock/issues/2240#issuecomment-267057840
