### ISSUE TITLE
discussion: create containers section

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#91]
1. Where do we put it, numbers wise?
2. Items to throw in
```js
/*** 1700: CONTAINERS [SETUP]
     [1] https://support.mozilla.org/kb/containers-experiment
     [2] https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers
     [3] https://github.com/mozilla/testpilot-containers
***/
user_pref("ghacks_user.js.parrot", "1700 syntax error: the parrot rests in peace!");
/* 1701: enable [SETTING] Options>Privacy>Container Tabs (FF50+)
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1279029 ***/
user_pref("privacy.userContext.ui.enabled", true);
/* 1702: enable Container Tabs (FF50+)
 * [SETTING] Options>Privacy>Container Tabs>Enable Container Tabs ***/
user_pref("privacy.userContext.enabled", true);
/* 1703: use a private container for thumbnail loads (FF51+) ***/
user_pref("privacy.usercontext.about_newtab_segregation.enabled", true);
/* 1704: set long press behaviour on "+ Tab" button to display container menu (FF53+)
 * 0=disables long press, 1=when clicked, the menu is shown
 * 2=the menu is shown after X milliseconds
 * [NOTE]: the menu does not contain a non-container tab option
 * [1] https://bugzilla.mozilla.org/show_bug.cgi?id=1328756 ***/
user_pref("privacy.userContext.longPressBehavior", 2);
```

**Comment by crssi** [comment]
Hey, I am using containers where I need to login with different users on the same page.
But I have enabled only `privacy.userContext.enabled`
I have no clue what does `privacy.userContext.ui.enabled`
Anyone knows?

**Comment by Thorin-Oakenpants** [comment]
@crssi https://bugzilla.mozilla.org/show_bug.cgi?id=1279029

**Comment by Thorin-Oakenpants** [comment]
longpress is quite cool. 0 means you just open a new normal tab, 1 always brings up the menu, but it only lists container tabs, so you can't open a non-container. But 2 allows a single click for a new tab, and a long press (IDK, 0.2 sec) to bring up the menu. Nifty.

No idea what they were going on about in the tickets I listed about right-click. Right click on the + tab button only brings up the standard menu. Middle click I will need to investigate if it propagates the current window context - but right now, I haven't restarted FF since I enabled it all, and I have no colors or icons for the default containers.

**Comment by Thorin-Oakenpants** [comment]
OK, this sucks a tad - I have no icons or colors displayed either in menus, in tabs (across the top) or in about:preferences#containers ... because I am using FT DeepDark

**Comment by Atavic** [comment]
`2100`

Isn't UI elements?

**Comment by Thorin-Oakenpants** [comment]
@Atavic But it's not about UI at all (that's just a consequence of building in a new feature and a test-pilot at that - so one pref which will probably be legacy once they turn containers on). Is that why you said to go for 2100? Cuz it's UI and somehow that fits just-before `2200 UI Meddling`?

**Comment by Thorin-Oakenpants** [comment]
I'm confused. Does this required the extension to be installed from https://testpilot.firefox.com/experiments/containers? I thought it was now part of FF (certainly seemed to work without the extension earlier besides a few issues - eg opening github in a container prompted me for a password/login, so definitely a container. It also showed the color in the tab when not focused, etc)

I installed that extension and it fixed the color indicator on open tabs with and without focus, it fixed icons in the File>menu, but that's it. It also has a "mouse over" popup menu on the + Tab button (and the icons are missing and colors and text placement are all screwed up probably due to my theme). And if I load a page in a container tab I now have a context menu entry "Always open in this container". Everything else mentioned earlier is still broken.

**Comment by crssi** [comment]
No. The extension is not required. This extension is only a test bed for future implementation.

**Comment by Atavic** [comment]
@Thorin-Oakenpants Because many people will find a new icon before reading about containers.
/*** 2600: PRIVACY btw it's a privacy feature.

**Comment by earthlng** [comment]
The draft in the first comment looks good, but containers are probably not quite ready yet so I would comment the prefs out for now.

**Comment by ArchangeGabriel** [comment]
@Thorin-Oakenpants Some features are only in the extension for now (like “Always Open…”). But they will end up landing in Firefox.

**Comment by Thorin-Oakenpants** [comment]
@ArchangeGabriel Thanks :) Worked that out now. It really doesn't like full themes, which compounded the issue

The test pilot has a really annoying mouse-over menu on the +Tab button, which overrides the longpress behavior. I've since removed the test pilot extensions. I'm going to leave all my prefs enabled, so I can monitor changes as they happen.

@earthlng Good idea. 1700's all inactive it is. I'll also add a [SETUP] tag to the section and add a parrot

**Comment by kaliostro2** [comment]
Is there any possibility of using "always open in this container" without addon?

**Comment by Thorin-Oakenpants** [comment]
@kaliostro2 No. Any successful test-pilot fixes/additions will eventually land in stable. I only removed the two extensions myself do I could strictly see what was baked into FF.
