### ISSUE TITLE
addons.mozilla.org marked as untrusted site

### ISSUE THREAD

**Issue by desk7** [ghacksuserjs/ghacks-user.js#912]
- Firefox 74.0 fresh installation
- ghacks user.js  date: 11 March 2020 version 73

When I try to install an addon (e.g. Ublock Origin) from addons.mozilla.org a  pop-up suggests me to install it only if the site is reliable, as if I was installing the addon from a third party site.
Is this a intended behavior?
How to restore the default one?

**Comment by crssi** [comment]
``` js
/* 4503  */ user_pref("privacy.resistFingerprinting.block_mozAddonManager", false);
```

**Comment by Thorin-Oakenpants** [comment]
Yes, it's a side effect. Why restore the default behavior, ow often do you install extensions, it's only one extra click/safety-check - however, it's a not a big deal if you flip the pref - unless you want extensions to also be able to work on AMO

**Comment by atomGit** [comment]
> ... unless you want extensions to also be able to work on AMO

i thought that was controlled by `extensions.webextensions.restrictedDomains`

**Comment by geeknik** [comment]
According to [Security/Fingerprinting](https://wiki.mozilla.org/Security/Fingerprinting):

`window.navigator.mozAddonManager is only exposed to addons.mozilla.org. In Resist Fingerprinting mode, we keep it exposed; however if the additional preference 'privacy.resistFingerprinting.block_mozAddonManager' is true, then it is not exposed to AMO `

**Comment by atomGit** [comment]
'exposed' doesn't equal 'enabled' though, does it? in other words, even if mozAddonManager were not exposed to AMO, wouldn't add-ons still work on AMO as long as `extensions.webextensions.restrictedDomains` doesn't include the domain?

**Comment by geeknik** [comment]
`privacy.resistFingerprinting.block_mozAddonManager` has nothing to do with AMO outside of about:addons. If you want to run extensions on the actual AMO website, you have to edit `extensions.webextensions.restrictedDomains`.

**Comment by atomGit** [comment]
that's what i thought, but [pants' comment](https://github.com/ghacksuserjs/ghacks-user.js/issues/912#issuecomment-604984828) threw me off...

**Comment by Thorin-Oakenpants** [comment]
why don't you guys test it?

here's what the user.js says
```
/* 2662: disable webextension restrictions on certain mozilla domains (also see 4503) [FF60+]
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
   // user_pref("extensions.webextensions.restrictedDomains", "");

/* 4503: disable mozAddonManager Web API [FF57+]
 * [NOTE] As a side-effect in FF57-59 this allowed extensions to work on AMO. In FF60+ you also need
 * to sanitize or clear extensions.webextensions.restrictedDomains (see 2662) to keep that side-effect
 * [1] https://bugzilla.mozilla.org/buglist.cgi?bug_id=1384330,1406795,1415644,1453988 ***/
user_pref("privacy.resistFingerprinting.block_mozAddonManager", true); // [HIDDEN PREF]
```

4503 says "you **also** need" - now that may be incorrect, depending on how you read it. Maybe it was correct but isn't any longer. And 2662 just says to also see 4503, but doesn't say it's a prerequisite

Feel free to test it (vanilla profile, restarts between changes) - otherwise I'll get around to it one day

**Comment by atomGit** [comment]
ok, so `privacy.resistFingerprinting.block_mozAddonManager` DOES need to be 'true' for add-ons to work on AMO (in addition to of course removing the domain/clearing `extensions.webextensions.restrictedDomains`)

yes, the *also* is the key word there

thanks pants :)
