### ISSUE TITLE
Network ID ?

### ISSUE THREAD

**Issue by 2glops** [ghacksuserjs/ghacks-user.js#913]
Not sure this is an issue.

Firefox 74.0 Linux
Page about:networking#networkid shows a "Network ID"

What is that ID ?
My researches were not successfull ...

That "Network ID" page / value doesn't appears on Firefox 68.6.0esr

**Comment by Atavic** [comment]
It appears as an hash value obtained by your current IP plus the telemetry values they get.
Note that telemetry includes DNS settings and MAC adresses. I got this from:
https://hg.mozilla.org/releases/mozilla-beta/log?rev=networkid

**Comment by 2glops** [comment]
Thanks Atavic !
