### ISSUE TITLE
Wiki - Appendix - A: Test Sites - Invalid link listed

### ISSUE THREAD

**Issue by westmyers** [ghacksuserjs/ghacks-user.js#916]
The "Browserprint - https://browserprint.info/test" link doesn't work any more on the "Appendix - A: Test Sites" page.

**Comment by Thorin-Oakenpants** [comment]
Thanks

**Comment by Thorin-Oakenpants** [comment]
heh ... https://129.127.194.63/ works if you accept the cert risk

- I'll comment it out rather than remove it for now
- there wasn't much on there that other tests do anyway
