### ISSUE TITLE
Firefox establishes TCP connections to CloudFront

### ISSUE THREAD

**Issue by Just-me-ghacks** [ghacksuserjs/ghacks-user.js#917]
Since version 68 Firefox has been establishing TCP connections to **CloudFront** (52.84.112.*) for no apparent reason (to me anyway). How to make it stop?

50.84.112.35 50.84.112.46 50.84.112.51

52.84.112.0/21

server-52-84-112-35.sof50.r.cloudfront.net

Firefox versions prior to 68 are completely quiet after applying my custom user.js

This is not a new problem but I'm still struggling to find a solution.

**Comment by rusty-snake** [comment]
remote settings are using cloadfront server. 
`about:config`: `services.*`

**Comment by Just-me-ghacks** [comment]
Hey, rusty-snake, thanks for the idea!

I already have these prefs in my user.js
```
user_pref("services.blocklist.addons.collection", "");
user_pref("services.blocklist.gfx.collection", "");
user_pref("services.blocklist.onecrl.collection", "");
user_pref("services.blocklist.plugins.collection", "");
user_pref("services.blocklist.signing.enforced", false);
user_pref("services.blocklist.update_enabled", false);
```

I flipped all **services.*** prefs however Firefox is still establishing TCP connections to CloudFront.

**Comment by rusty-snake** [comment]
I tested with a Nightly (w/o user.js, mosly clean profile) after 3min I check the domains on about:networking, the following resolve to clodfront:

content-signature-2.cdn.mozilla.net
archive.mozilla.org
aus5.mozilla.org

**Comment by Just-me-ghacks** [comment]
I already have:
```
user_pref("media.gmp-manager.url", "");
user_pref("media.gmp-manager.url.override", "");
user_pref("media.gmp-provider.enabled", false);
```

I flipped all **app.update.url** prefs but that didn't make a difference.

In **about:networking** I see these:
firefox.settings.services.mozilla.com
content-signature-2.cdn.mozilla.net

**Comment by Just-me-ghacks** [comment]
Up until now I was using these prefs:
```
user_pref("browser.newtabpage.activity-stream.asrouter.providers.snippets", "");
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.newtabpage.activity-stream.disableSnippets", true);
user_pref("browser.newtabpage.activity-stream.feeds.discoverystreamfeed", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.showSponsored", false);
user_pref("browser.newtabpage.activity-stream.telemetry", false);
user_pref("browser.newtabpage.activity-stream.telemetry.ping.endpoint", "");

```

To partially* disable **firefox.settings.services.mozilla.com** connections I added:
`user_pref("browser.newtabpage.activity-stream.feeds.asrouterfeed", false);`

*This pref won't prevent Firefox from establishing a connection to firefox.settings.services.mozilla.com upon FIRST run (after clean install).

Also: how can I prevent Firefox from establishing a connection to ALL bookmarks upon first run (after clean install)?

**Comment by Dupond** [comment]
Hello !

Couldn't you simply add some lines in your hosts file ?

E.g. in Linux, add this to /etc/hosts :

```
127.0.0.1 firefox.settings.services.mozilla.com
127.0.0.1 content-signature-2.cdn.mozilla.net
```

**Comment by Thorin-Oakenpants** [comment]
> I flipped all **services.*** prefs however Firefox is still establishing TCP connections to CloudFront.

Just FYI: the pref `services.settings.server` in FF73+ is protected [1598562](https://bugzilla.mozilla.org/show_bug.cgi?id=1598562)

I know you say since 68, but this is not something that I'm going to waste my time on. Update checks, blocklist updates, SB updates, etc are a normal part of browser functionality, and there are no privacy, security, tracking, FPing issues here (unless there's a bug). You're free to do as you like though and stop everything imaginable by any means you want

by all means, continue your conversation, but I'm going to close this
 - e.g #892 marked invalid
 - e.g #893 marked invalid

PS: I won't mark as invalid out of respect for Just-me-ghacks

**Comment by Just-me-ghacks** [comment]
It looks like you can't prevent Firefox (68, 69, 70, 71, 72, 73, 74, etc.) from calling home.

Firefox is the only software (on my computer) that has to be blocked via hosts file:
> 127.0.0.1 content-signature-2.cdn.mozilla.net
> 127.0.0.1 firefox.settings.services.mozilla.com

**Dupond**, thanks for the suggestion.

**Pants**, you're too kind. Thank you and **Big E** for the amazing work. My browsing experience would have been unbarable without you :)

**Comment by travankor** [comment]
@Just-me-ghacks @rusty-snake 

is there a tl;dr of what settings, I should add to the user.js

**Comment by travankor** [comment]
@Just-me-ghacks 

also if this issue can't be fixed in the about:config, then look at GNU Icecat

**Comment by rusty-snake** [comment]
> is there a tl;dr of what custom settings I should add to the user.js

Unfortunately no. It depends on what you want, what limitation you can accept, which AddOns you use.

A good reference is this:
https://codeberg.org/12bytes.org/Firefox-user.js-supplement/

As a FYI my current user-overrieds.js
https://gist.github.com/rusty-snake/5c54e91b602b869e99a5d403243b09ca

I started a manual for my config which however still needs months to be reasonably complete.
https://gitlab.com/rusty-snake/firefox-config

**Comment by travankor** [comment]
I looked at the 12bytes stuff and it's kind of unorganized -- also lmao conspiracy theories on that site

Your repo looks good though 👍 -- I added parts of it to my config

**Comment by crssi** [comment]
You might find some info also at `user-overrides.js` in [https://github.com/crssi/Firefox](https://github.com/crssi/Firefox).

Cheers

**Comment by Thorin-Oakenpants** [comment]
> also if this issue can't be fixed in the about:config, then look at GNU Icecat

Seriously? WTF? It hasn't been updated for 10 months and is based on ESR60.7. Don't take offense, but please don't suggest other forks in this repo: they are all liabilities, and effectively anything they do can already be done in Firefox stable. I don't go to all this trouble just so people can mention shitty forks /mild-rant over

**Comment by Just-me-ghacks** [comment]
Thanks, **rusty-snake**! I already use most of your overrides, but I will add these:
```
user_pref("browser.contentblocking.report.monitor.enabled", false);
user_pref("browser.contentblocking.report.lockwise.enabled", false);
user_pref("browser.contentblocking.report.proxy.enabled", false);
user_pref("browser.slowStartup.notificationDisabled", true);
user_pref("browser.slowStartup.maxSamples", 0);
user_pref("browser.slowStartup.samples", 0);
```
Not essential, but will save a few CPU cycles / disk writes. Hopefully!

**Can anyone comment on crssi's decision to rely entirely on CanvasBlocker by using with these two**:
```
user_pref("webgl.disabled", false);
user_pref("dom.webaudio.enabled", true);
```
It sounds logical but what's the official policy here? :)

**Comment by crssi** [comment]
^^ There is no official policy... it depends whats you need and it is entirely up to you.
I am making a profile for my folks and friends who are not geeks and they care only to browse with near zero breakages.
Also I do not believe in government proof browsing on a daily basis.

**Comment by travankor** [comment]
@Just-me-ghacks 

So... is your ping issue fixed?

**Comment by Just-me-ghacks** [comment]
No. You can't prevent Firefox (68, 69, 70, 71, 72, 73, 74, etc.) from calling home.

Use your **hosts** file to block Firefox.

**Comment by travankor** [comment]
Sigh.. :(

I hope someone will maintain a list of such addresses on a repo (ghacks maybe???, or someone else?) since I can't manually tracking every FF change down... btw I personally don't need or use Mozilla services (except addons but I update manually not automatically).

**Comment by travankor** [comment]
Would be interesting to see where in the source code this is from, if someone has time to burn

**Comment by Atavic** [comment]
Firefox RemoteSettings Content signature (Autograph integration) explained at:
https://github.com/mozilla-services/autograph/tree/main/signer/contentsignaturepki
