### ISSUE TITLE
clipboard issues [solved: dom.allow_cut_copy]

### ISSUE THREAD

**Issue by zdat** [ghacksuserjs/ghacks-user.js#918]
I couldn't find the pref that is responsible for click to copy.

Have `user_pref("dom.event.clipboardevents.enabled", true);` and `user_pref("dom.allow_cut_copy", true);` but still no luck.

Any help?

Trying to use this site; https://beautifuldingbats.com/whitespace/

**Comment by atomGit** [comment]
`clipboard.autocopy` maybe? not a ghacks pref i don't think, but you can try it (def=true)

**Comment by zdat** [comment]
Mine was on false, weird. Just changed it to true but it's still not working.

**Comment by Thorin-Oakenpants** [comment]
What is "click to copy" ?

**Comment by atomGit** [comment]
i half-assumed he meant 'copy on select' - i had trouble with that too for a bit (linux) but it either fixed itself or i fixed it

**Comment by Thorin-Oakenpants** [comment]
So I loaded up a vanilla profile, added the user.js and tested. On that website, copy to clipboard doesn't work. Changed `dom.allow_cut_copy` to `true`, reloaded the website, and it now works

**Comment by Thorin-Oakenpants** [comment]
One other thing you can look at, and this is not in the user,js, is `dom.events.asyncClipboard`which controls the Clipboard API
