### ISSUE TITLE
discussion: dom.presentation.*

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#92]
My understanding is this poses a possible hardware leak/fingerprint. The defaults are all false anyway, so this is for completeness.

https://wiki.mozilla.org/WebAPI/PresentationAPI
> Presentation API enables web content to access external presentation-type displays and use them for presenting web content. With this API, web page can initiate and control an presentation request. 

More info on retrieving available devices information: https://wiki.mozilla.org/WebAPI/PresentationDeviceInfoAPI

^^ So it can enumerate devices. It can initiate requests, i.e requires user confirmation/action, so that is not an issue.

> The Presentation API requires user permission for a page to access any display to mitigate issues that could arise, such as showing unwanted content on a display viewable by others.

[updated as per comments]
```js 
/* 2513: disable Presentation API
 * [1] https://wiki.mozilla.org/WebAPI/PresentationAPI
 * [2] https://www.w3.org/TR/presentation-api/ ***/
user_pref("dom.presentation.enabled", false);
user_pref("dom.presentation.controller.enabled", false);
user_pref("dom.presentation.discoverable", false);
user_pref("dom.presentation.discovery.enabled", false);
user_pref("dom.presentation.receiver.enabled", false);
user_pref("dom.presentation.session_transport.data_channel.enable", false);
```

- Not 100% sure what `presentation.discover*` do exactly - maybe see https://bugzilla.mozilla.org/show_bug.cgi?id=1180596
  * `dom.presentation.discoverable.encrypted` default true (the only pref at default true)

Any objections, corrections, enlightenment? Since they all seem to be off (except *encrypted), we can either add this for info, active or inactive, or just drop the whole thing.

**Comment by Atavic** [comment]
Explained [here](https://www.w3.org/TR/presentation-api/#introduction).

**Comment by earthlng** [comment]
It sounds pretty terrible and I'm all in favor of adding them and setting everything to false.
Let's include `dom.presentation.session_transport.data_channel.enable` too, then we have everything covered. They are probably not all needed but heck, I can't be bothered to check, so let's just make absolutely sure none of this nonsense ever sees the light of day in our hardened FFs.

**Comment by Thorin-Oakenpants** [comment]
Lack of interest? Bump? :)  Never mind. We enforce a lot of API's to be disabled, as does TBB. Since this is all off by default, then we'll just close this ticket and ignore the prefs. If they ever change we'll pick them up in diffs between Firefox releases.

Ahhh .. now I see earthlngs comment. Wow ... so heck .. let's add it. Commit to follow - will add in `dom.presentation.session_transport.data_channel.enable`

Should I add `dom.presentation.discoverable.encrypted` as true (default) - I guess it's fallback that if discover is enabled, only encrypted connections are allowed?

**Comment by earthlng** [comment]
> Should I add dom.presentation.discoverable.encrypted as true (default) 

not necessary. If everything else is disabled it shouldn't matter what .encrypted is set to.

**Comment by Thorin-Oakenpants** [comment]
cool .. will do
