### ISSUE TITLE
FF76-77: 0709 disable_unc_paths can break extensions: see OP for solution [1634267 resolved 78]

### ISSUE THREAD

**Issue by CrendKing** [ghacksuserjs/ghacks-user.js#923]
Thorin: hijacking OP to post MOAR info: June 2nd 2020

This was fixed somewhat but then reared it's ugly head again. It is [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1634267) in FF78. If it happens to you
- set `network.file.disable_unc_paths` = `false` (hidden pref, default false)

Note: I have already added this a second time to the user.js as a hotfix-override, until after 78 lands. That way you can update the user.js, and forget about it getting reset later - it'll just happen for you

Alternatively, and not recommended, is the pref below
- set `dom.quotaManager.useDOSDevicePathSyntax` = `false` (default true)

I assume a restart is required.

----

original post

I'm using the Firefox Developer version. It auto updated from 75 beta 12 to 76 beta 2. Upon restarting the browser, I noticed all extension settings are gone and behaving incorrectly. Upon checking the browser console, I found tons of errors about extension IndexedDB with no error code associated. I attached some samples of those error messages. Upon doing binary search on what caused the issue, I narrowed it down to the `network.file.disable_unc_paths = true` from prefs.js, which was pulled from the user.js of this project. Since it is a hidden preference, I do not know if this is an intended change around Firefox 76 or a regression. Can any of you verify?

```
IndexedDB UnknownErr: ActorsParent.cpp:615
UnknownError: IndexedDB: main/anti-tracking-url-decoration getLastModified() IndexedDB:  open() The operation failed for reasons unrelated to the database itself and not covered by any other error code. Database.jsm:28:5
IndexedDB: main/hijack-blocklists getLastModified() IndexedDB:  open() The operation failed for reasons unrelated to the database itself and not covered by any other error code. Database.jsm:28
IndexedDB: main/hijack-blocklists getLastModified() IndexedDB:  open() The operation failed for reasons unrelated to the database itself and not covered by any other error code. Database.jsm:28
sendRemoveListener on closed conduit {506e023c-7f2b-40a3-8066-bc5deb40aebe}.137438953472 ConduitsChild.jsm:108
sendRemoveListener on closed conduit {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}.137438953473 ConduitsChild.jsm:108
IndexedDB UnknownErr: ActorsParent.cpp:615 2
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
IndexedDB UnknownErr: ActorsParent.cpp:615 2
Problem getting stored prefs for feeds.section.topstories SectionsManager.jsm:235
Problem getting stored prefs for feeds.section.highlights SectionsManager.jsm:235
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. aboutconfig.js:452:9
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
IndexedDB UnknownErr: ActorsParent.cpp:615 4
undefined history-persistence.js:32:15
IndexedDB UnknownErr: ActorsParent.cpp:615 2
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Unchecked lastError value: Error: An unexpected error occurred storage-util.js:14
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
IndexedDB UnknownErr: ActorsParent.cpp:615
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 4 ExtensionStorageIDB.jsm:831
IndexedDB UnknownErr: ActorsParent.cpp:615
2147746065 BrowserGlue.jsm:2300
IndexedDB: blocklists/ getLastModified() IndexedDB:  open() The operation failed for reasons unrelated to the database itself and not covered by any other error code. Database.jsm:28
Log warning: The log 'Services.Common.RESTRequest' is configured to use the preference 'services.common.log.logger.rest.request' - you must adjust the level by setting this preference, not by using the level setter Log.jsm:24
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 3 ExtensionStorageIDB.jsm:831
Unchecked lastError value: Error: An unexpected error occurred 2 storage-util.js:15
IndexedDB UnknownErr: ActorsParent.cpp:615
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. 2 ExtensionStorageIDB.jsm:831
item is undefined common.js:941
Unchecked lastError value: Error: An unexpected error occurred common.js:940
item is undefined common.js:929
Unchecked lastError value: Error: An unexpected error occurred common.js:928
IndexedDB UnknownErr: ActorsParent.cpp:615
```

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1536796

**Comment by CrendKing** [comment]
I see it is fixed. Assuming it indeed fixes this particular issue, what's the recommended course of action for average users? Keep the pref and wait for the fixed version or comment out the pref?

**Comment by gwarser** [comment]
No, this bug implements using long paths to access storage files on disk.

**Comment by gwarser** [comment]
This pref was implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1413868
High chance it does not affect you.

It will be best to bisect Firefox to test if it's really [1536796](https://bugzilla.mozilla.org/show_bug.cgi?id=1536796) causing your issue. If yes, It will probably require some follow-up fixing on Firefox, especially that it affects Tor Browser.

I cannot test this because I'm on Linux.

**Comment by CrendKing** [comment]
Well, I have issue with that pref, that's why I opened the issue. Maybe leave the issue open for a while so if others have the same issue they can reply?

**Comment by basilisk0315** [comment]
For me this pref causes firefox 76 beta 2 (Win64) to spin it's wheels trying to connect to websites with no result. Commenting it out (or setting it to false) corrects fixes the problem.

**Comment by gwarser** [comment]
Do you see `dom.quotaManager.useDOSDevicePathSyntax` in `about:config`?

**Comment by basilisk0315** [comment]
No, I don't see `dom.quotaManager.useDOSDevicePathSyntax`.

**Comment by earthlng** [comment]
@CrendKing + @basilisk0315, do you still have these problems in beta 4?

**Comment by CrendKing** [comment]
It is working fine under beta 4 now, for me.

**Comment by basilisk0315** [comment]
Beta 4 is working ok for me as well.

**Comment by Thorin-Oakenpants** [comment]
so are we good here: i.e no pref to add to the user.js or anything?

**Comment by CrendKing** [comment]
It is up to you guys. But personally I would keep it off on my computer, as it has history of being messed up, who knows when Mozilla would trigger again? I do not want to spend another hour bisecting every part of Firefox to find this culprit pref.

**Comment by basilisk0315** [comment]
Yeah I think we're ok.

**Comment by Thorin-Oakenpants** [comment]
if this patch was the fix - the problem seems to not be fully resolved - see [comment 33](https://bugzilla.mozilla.org/show_bug.cgi?id=1626846#c33)
