### ISSUE TITLE
Wiki update (section 4.1)

### ISSUE THREAD

**Issue by Aeriem** [ghacksuserjs/ghacks-user.js#936]
- [ ] ClearURLs deals with ETags since version 1.16.0.
Its implementation is very close to ETag Stoppa's (poke @claustromaniac), as explained [here](https://gitlab.com/KevinRoebert/ClearUrls/-/issues/440#note_308991510).

- [x] Neat URL's repository is now located at https://github.com/Smile4ever/Neat-URL.

**Comment by Thorin-Oakenpants** [comment]
thanks, fixed neat urls repo link

I don't want to start listing **all the cross over functionality** - that's up to end users to work out themselves: especially as devs expand: e.g.
- CB now has UA spoofing
- ClearURLs now has hyperlink auditing
- and so on

It would also make a mess of the page

**Comment by Aeriem** [comment]
You're welcome. 😃

> It would also make a mess of the page

Good point, have a beer! 😄
