### ISSUE TITLE
about: network.http.referer.hideOnionSource

### ISSUE THREAD

**Issue by kaliostro2** [ghacksuserjs/ghacks-user.js#94]
I'm not sure that this option worth adding to user.js. It is important only for Tor browser. For Firefox, it does not do anything.

**user_pref("network.http.referer.hideOnionSource", true);**

**Comment by Thorin-Oakenpants** [comment]
agreed it does nothing for "Firefox" out of the box , but users can make FF use TOR. It's also good info for the sake of comprehensiveness/knowledge I guess. It's harmless to leave it in... harmless to leave it active but....

Go ahead and vote
:+1: = leave as is (active pref)
:confused: keep it in but make it inactive/commented-out
:-1: = remove it, it does not belong here

First one to 10 wins.

**Comment by Atavic** [comment]
@kaliostro2 Leave it as it is.

@Thorin-Oakenpants A rare example Uniformity in my bag.

**Comment by kaliostro2** [comment]
> The ghacks user.js is a template, which, as provided, aims (with add-ons) to provide as much privacy and enhanced security as possible, and to reduce tracking and fingerprinting as much as possible - while minimizing any loss of functionality and breakage (but it will happen).

**network.http.referer.hideOnionSource** does not do any of the above. Therefore, I voted to remove.

**Comment by Thorin-Oakenpants** [comment]
Hey @kaliostro2 , that's fine buddy, you're allowed to vote however you like - but it actually does enhance privacy, albeit in certain circumstances.

The other part of the readme also says "Comprehensive" - I have added items simply for information's sake, and this would fit that category as well. Hence I voted to keep it (but changed my mind about it being active - but at least it's there for knowledge).

**Comment by Atavic** [comment]
It should tell if you are on Tor and which TBB version, see [here](https://github.com/qqTYXn7/browserprint/blob/2f7d870eef3858e2b7a326da0ab33443db67023c/src/util/browserPrediction/Predictor.java#L93)

**Comment by 2glops** [comment]
my choice : leave as is, active pref
There is no harm and it could benefit

**Comment by Thorin-Oakenpants** [comment]
@2glops If so, then vote :) I'm using the emoji's on the first post as counters

**Comment by 2glops** [comment]
👍
voted ! :-)

**Comment by earthlng** [comment]
Leaving it in may give users the wrong ideas about using their main FF profile over TOR.
That's the opposite of "dispel bad advice", as we wrote on our flags in the Readme. :thumbsdown:

**Comment by Thorin-Oakenpants** [comment]
well if that's the case, then all it needs an extra line (not that I think we are giving the wrong idea at all - we're not explicitly saying to use TOR). With an extra line it then actively dispels bad advice (as you and probably others perceive it), AND enhances privacy and knowledge

```
 * we recommend that you use the Tor Browser Bundle for TOR
```

**Comment by earthlng** [comment]
I don't think it's such a valuable pref in the first place to warrant it's inclusion, especially since it doesn't do anything in Firefox without TOR. Yeah, you don't leak referrer information between onions, but nobody knows who you are anyway. And I doubt that too many darknet sites care to keep that information around anyway. But if you're the only one coming to that onion with a FF user-agent rather than the TBB one, that's a much bigger problem. I wasn't sure I should vote because all 3 options are acceptable for me, but with the 2nd one being the least preferred. :thumbsup: or :thumbsdown: from me - let the majority decide or go with whatever you think is best. my 2 cents

**Comment by Thorin-Oakenpants** [comment]
It's no big deal to me. Anyone using AdvOR or TOR over VPN/VPN over TOR, or whatever will/should know what they're doing. First one to 10 wins. Just wish people would vote so I can close this :)

**Comment by Thorin-Oakenpants** [comment]
>  FF user-agent rather than the TBB one

Umm, you do realize that ESR uses the same UA right (spoof it the same as TBB does, the same holes still exist in both releases). Not sure that's the best example of fingerprinting :)

**Comment by earthlng** [comment]
> Umm, you do realize that ESR uses the same UA right

I do. But this user.js is targeting FF stable (not ESR) and if someone uses it with TOR then there are likely not too many other darknet clients with that same UA
