### ISSUE TITLE
Do you think it's worth updating Firefox Android wiki to include a note about browsers major version compatibility?

### ISSUE THREAD

**Issue by hunkjazz** [ghacksuserjs/ghacks-user.js#943]
## I had a problem

Last week, I was able to use my personal `user.js` on Fennec 68.8.0esr.

It took me like two hours, until I could successfuly paste my settings to Fennec. 

The problem was that my **browsers wouldn't sync**, so I could remote debug. Thanks to one of those Mozilla's documentations, I figured that it is impossible to remote debug if two browsers are **more than one major version apart**.

### The solution

* Downloading Firefox 69.0.1 for desktop, from [here](https://ftp.mozilla.org/pub/firefox/releases/);
*  After that, both browsers were, at least, one major version apart: **68** and **69**;
*  Then, I could remote debug perfectly fine.

Now, this is not because I'm lazy and didn't want to update my mobile browser, so it would match my desktop. It's just that newer versions are not available for my Android device.

---

## My suggestion

I think it's worth adding an extra note, next to these:

>**Note**: The `ghacks user.js` is designed for desktop Firefox;
>
>* Fennec [68 or lower]: some prefs may not apply, or may cause issues, or may be missing
>* Fenix [69+]: Don't do it! The differences in prefs is massive, and FYI: `about:config` is not available on release builds

**It would become something like this:**

>* The **non-rooted wiki** requires remote debugging and it won't work if your browsers are **more than one major version apart**.
>   * If necessary, you should update your browsers or download a compatible Firefox for desktop version, from [here](https://ftp.mozilla.org/pub/firefox/releases/).

What are your thoughts?

---

referenced wiki: https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android

**Comment by Thorin-Oakenpants** [comment]
> It's just that newer versions are not available for my Android device.

Well actually, there is preview and nightly. I have them both alongside stable (which is fixed on ESR68)

> What are your thoughts

The 68-69 issue is not permanent: i.e one version, AFAIK.

anyway - https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Connection_to_Firefox_for_Android_68

I don't think it's worth the maintenance TBH. Once Fenix ships as stable, it's a moot point

**Comment by gafarma89** [comment]
@Thorin-Oakenpants it would be great to support android devices. Very simple example:

**Comment by gafarma89** [comment]
@Thorin-Oakenpants it would be great to support android devices.

Very simple and important example:

I have inject user.js file but when I open Firefox on android, the first page shows me the news. And they are updating every time.

At least please support the important or simple preferences for android.

Thank you

**Comment by Thorin-Oakenpants** [comment]
@gafarma89 just change your settings from the graphic user interface

68 is meatball menu (that's the three vertical dots) > settings > general > home >
Here's mine
- homepage is set as about:home
- use for new tabs is disabled
- panels >  (tap it) all three disabled
- bookmarks: default
