### ISSUE TITLE
0709 = true breaks CB and as a result also FF 77

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#951]
``` js
/* 0709 */ user_pref("network.file.disable_unc_paths", true);
```

Breaks CanvasBlocker and as a result all communication fails in Firefox 77.

Removing and reseting `0709` (FF restart is needed) restores all functionality.

Cheers

**Comment by collinbarrett** [comment]
Confirmed, that fixes it. Thanks!

**Comment by Thorin-Oakenpants** [comment]
Isn't this the same as #923 and you can also fix it by adding
`dom.quotaManager.useDOSDevicePathSyntax`=`false`
which E suggested adding to the user.js for 77 (it's fixed in 78)

can someone test please

**Comment by crssi** [comment]
Tested.
You and Big E are right as always, or most of the times. 😄 👍

**Comment by Thorin-Oakenpants** [comment]
OK, I already pinned the other one, so I'll close this, and on the other one cleanup the title and add something to OP

**Comment by sgabe** [comment]
I have just encountered this with Firefox 77. I can confirm that resetting `0709` fixes the issue.
