### ISSUE TITLE
Troubleshooter does nothing.

### ISSUE THREAD

**Issue by OdinGitDat** [ghacksuserjs/ghacks-user.js#954]
I think the troubleshooter is incompatible with the new about:config page. When I run the script in console it only outputs 'undefined' and shows the msg prompt.

**Comment by Thorin-Oakenpants** [comment]
@earthlng

**Comment by earthlng** [comment]
It works for me on the new about:config page and the old. If it shows the prompt it's working.
You just have to follow the instructions in the prompt.

**Comment by OdinGitDat** [comment]
Oh okay, I remember more console output last time I used it (long time ago so maybe I remember it wrong) with regards to settings changed.

Maybe you could add that then to avoid confusion like mine.
