### ISSUE TITLE
1223 breaks Firefox AMO styling

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#955]
``` js
/* 1223  */ user_pref("security.cert_pinning.enforcement_level", 2);
```

breaks Firefox [AMO](https://addons.mozilla.org/) styling.

Cheers

**Comment by Thorin-Oakenpants** [comment]
AFAICT it doesn't break anything for me: I have no third party MitM like an AV
- What is broken, do you have a cropped pic of the damage, or is the css file blocked?
- Do you have an AV or something?

**Comment by crssi** [comment]
I have this on a computer where ESET AntiVirus is installed. Tested before with a plain vanilla firefox profile, even without ghacks-user.js.
Tested now on a plain vanille Win10 up-to-date OS and plain vanilla firefox profile (no ESET here) and everything is fine.

Sorry for false alarm, my bad. I blame it to a bad coffee. 😉 

Cheers ❤️

**Comment by Thorin-Oakenpants** [comment]
moral of the story: **always** have good coffee ☕
