### ISSUE TITLE
OT: Extensions does not work when profile copied to another computer

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#957]
I have troubles that, when I copy Firefox profile to another computer, the web extensions does not work.

Sometimes helps to restart Firefox to safe-mode and then back to normal.
But always works when on a new computer I disable extensions and enabled them back on.

If I remember correctly, this behavior started with Firefox 68.

Do anyone know why this is happening, and how to correct it?
Is there any preference that should be modified?

Thank you and cheers

**Comment by Thorin-Oakenpants** [comment]
> If I remember correctly, this behavior started with Firefox 68

More like since at least Quantum (FF57)

- [1429838](https://bugzilla.mozilla.org/show_bug.cgi?id=1429838)
- [tor 27604](https://trac.torproject.org/projects/tor/ticket/27604)
- [portable apps 60496](https://portableapps.com/node/60496)

**Comment by Thorin-Oakenpants** [comment]
solution: don't move your shit around :)

**Comment by crssi** [comment]
> solution: don't move your ~shit~ stuff around :)

I don't, its am clean newly created profile salted with your wisdom, but I agree than I need to do additional sanitation.
But you have helped me anyway pointed me to the right direction.
I need to do some special care with `extensions.json` file. 

Thank you and cheers <3
