### ISSUE TITLE
This is a no-issue issue

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#961]
Girly and guys...

Just a very important thing and nothing else: **THANK YOU**

I know this sounds a little melancholic, but I really appreciate all your work and I am sure there is quite a lot of others sharing my opinion.

Love you all ❤️ 👍

**Comment by atomGit** [comment]
i second this motion and, furthermore, retroactively apply it to you too crssi :)

**Comment by Cade66** [comment]
One can be tough and grateful :=) I don't feel any melancholy in saying "THANKS for your work, to all of you!"
Not sure I'm that tough, though!
