### ISSUE TITLE
changing UTC timezone check

### ISSUE THREAD

**Issue by zgierlach** [ghacksuserjs/ghacks-user.js#965]
I was just wondering how I could enable a custom time zone with the user.js file. I searched and seen something for UTC and timezone in my terminal. I deleted it and it was showing as a different timezone by a tracking company so I thought I was good. Now its been set back to its original UTC time zone default value that I believe you guys set. This happened after I exited and came back to the window. I've been looking overnight and can't find the setting or anything to change this. If someone could point me in the right direction that would be great.

Thanks

**Comment by Thorin-Oakenpants** [comment]
RFP (`privacy.resistFingerprinting`, number `4501`) controls spoofing timezone as `UTC 0`. You can't change it or disable it on it's own - you have to disable the entire thing (by setting it to false), and then you lose a **lot** of anti-fingerprinting protections (seriously, it's LOTS).

If you want to override the timezone, then you can use an extension: but none of these are foolproof: they **all** leak via workers, and most (all?) do not cover all the methods. If such an extension existed, ideally you would one that only changed the timezone based on a whitelist (so you don't compromise your fingerprint except on those few sites) - but I do not know of any of those: instead they all apply the spoof, then whitelist sites to **not** apply to (i.e. the reverse).

If you **really** need the timezone to be your real one for a few sites (e.g. when you use gmail), then I suggest you compartmentalize - I'm sure you have more than one browser. e.g. use chrome for all your google stuff you log into, or for sites like checking local event times such as sports, concerts.
