### ISSUE TITLE
Is there anyway to stop a some firefox phoning home from in user.js?

### ISSUE THREAD

**Issue by CarlosMerc** [ghacksuserjs/ghacks-user.js#966]
Currently running the lastest user.js with 78.0.1 ESR
Upon a fully clean profile, firefox makes contact with content-signature-2.cdn.mozilla.net and firefox.settings.services.mozilla.com amoungst others such as aus5.mozilla.org (which i have seen before and is prolly fine).

There seems to be talk that browser.newtabpage.activity-stream* are the ones you need to look at to silence firefox. I don't mind blocklists, certificate checks etc, but any other activity is suss.

**Comment by Thorin-Oakenpants** [comment]
- signatures seems pretty important IMO
   - https://dxr.mozilla.org/mozilla-central/search?q=content-signature&redirect=false
- aus5 looks like updates and certs
   - https://dxr.mozilla.org/mozilla-central/search?q=aus5.mozilla&redirect=false
- services, IDK
   - https://dxr.mozilla.org/mozilla-central/search?q=settings.services&redirect=false

^^ not that this tells us everything

services
- open `chrome://global/content/config.xhtml` and search for `services.mozilla` 
- https://dxr.mozilla.org/mozilla-central/search?q=services.settings.server&redirect=false

Maybe @earthlng or someone can dig deeper. AFAIConcerned, AS is not used, and accounts is disabled, and pocket is disabled, and so on. If something is still connecting, it's probably important

**Comment by CarlosMerc** [comment]
content-signature-2.cdn.mozilla.net seems to be pointing to certs and other stuff, but it also seems to point to normandy (telemetry) and other related browser.newtabpage.activity-stream s? Or so the following link suggests:
https://bugzilla.mozilla.org/show_bug.cgi?id=1617392

There's suggestions at the bottom that the following helps:

    Set browser.newtabpage.activity-stream.feeds.asrouterfeed to false - disables firefox contextual feature recommendations and certain other notifications from Mozilla
    Set messaging-system.rsexperimentloader.enabled to false - disables new feature experiments
    Set app.shield.optoutstudies.enabled to false - Disables the running of experiments. Not necessary if app.normandy.enable is also set to false.
    Set app.normandy.enabled to false - Disables all Normandy remote actions, including studies, feature rollouts, and emergency hotfixes.

A couple of those i didn't see in the user.js

**Comment by Thorin-Oakenpants** [comment]
telemetry is disabled already. You can easily check this by seeing that nothing is collected locally. No experiments exist. No health data exists. Shield experiments are part of normandy, and are a subset of the telemetry master switch (`0341`)

IIRC, normandy also has a remote part which they used (and modified afterwards) to help mitigate the addons cert failure a year ago (but I'm not sure how all of that works exactly).

The only part of "telemetry" not covered by the master switch, is coverage pings, which is under `0331` (and that's a separate exe: `pingsender` IIRC). Also, for the record, the master switch also stops the windows scheduled task.

---

> A couple of those i didn't see in the user.js

- correct: a couple are already there: `app.normandy.enabled` and `app.shield.optoutstudies.enabled` are in the user.js, active and set to false
- `messaging-system.rsexperimentloader.enabled` was added in 76 see [1620021](https://bugzilla.mozilla.org/show_bug.cgi?id=1620021)
   - it didn't raise any concerns in the FF76 diffs: it's just part of the new "central" messaging API (before this they used individual prefs per experiments etc or built them into each system addon / experiment). Normandy is already covered (see the first paragraph). And "first welcome" or "first run" stuff I don't care about: if used, they're a one time thing and then set internally, and the contents are usually local anyway (or they load a mozilla webpage)
- `browser.newtabpage.activity-stream.feeds.asrouterfeed`
   - we don't use AS, so if you're not using it, not loading the actual AS page, then I don't think this is doing anything really. We already disable the topstories, pocket, sponsored, discovery, snippets. If you're not interacting with the AS page then you're not going to get any contextual features of messages

I'm just not into deep diving AS. Put quite simply: there's zero privacy, tracking, etc issues here AFAIC
