### ISSUE TITLE
2031

### ISSUE THREAD

**Issue by wvxwxvw** [ghacksuserjs/ghacks-user.js#969]
/* 2031: disable autoplay of HTML5 media if you interacted with the site [FF78+]
 * 0=sticky (default), 1=transient, 2=user
 * 2 - breaks playback on some sites ( i.e. https://coub.com/hot ) ***/
user_pref("media.autoplay.blocking_policy", 1);

ESR 78

**Comment by atomGit** [comment]
for me (ff v78 on linux) a value of 2 causes a problem where an embedded YT video needs to be clicked twice before it plays - i believe it also causes problems with Vimeo videos

**Comment by Thorin-Oakenpants** [comment]
AFAIK it's a timing issue (see https://bugzilla.mozilla.org/show_bug.cgi?id=1509933#c22 ): all the various video platforms are different. If they use 1000ms it messes up on siteA, but works on siteB. If they use 5000ms, now SiteA works, but SiteB is fubared. As long as you can live with the double click and nothing actually breaks, be happy 🍻

**Comment by rusty-snake** [comment]
FWIW: On some sites you need to change to video-quality to workaround such bugs.

**Comment by wvxwxvw** [comment]
@Thorin-Oakenpants 
What does the double click have to do with it? The video doesn't work completely.

**Comment by rusty-snake** [comment]
> FWIW: On some sites you need to change to video-quality to workaround such bugs.

… and some to add a autoplay exception in the site settings.

**Comment by atomGit** [comment]
all i know is that before 78 with my settings, no videos auto-played and i didn't have to double click anything

i had this same issue many moons ago, then it was fixed, nowit's busted again - i wish moz would solidify and simplify these settings once and for all - now there's...

```
dom.media.autoplay.autoplay-policy-api	
media.autoplay.allow-extension-background-pages	
media.autoplay.block-event.enabled	
media.autoplay.block-webaudio
media.autoplay.blocking_policy
media.autoplay.default
```

these settings are about as clear as mud to me
