### ISSUE TITLE
Firefox Containers is ... AWESOME!!!

### ISSUE THREAD

**Issue by kaliostro2** [ghacksuserjs/ghacks-user.js#97]
I just got acquainted with the experimental function of firefox "CONTAINERS" and it's just wonderful. Advertisers are in shock. It's unlikely they will tolerate this. I hope the developers of the browser Firefox will not give up this function under the pressure of advertisers (Google including). Although the bank check with nine zeros can make anyone change their mind. Google lose more if this feature is implemented completely.
 I also found an experimental add-on that extends the possibilities of containers allowing you to assign any site to a separate container without unnecessary movements. So it is still essentially in the alpha version, use it at your own risk.

https://testpilot.firefox.com/experiments/containers
https://github.com/mozilla/testpilot-containers

**Comment by Thorin-Oakenpants** [comment]
Ummm .. this is all covered under #91, and is in fact already in the user.js (committed it today).

Yes, the functionality is already in FF itself (I have it enabled in mine for testing), but the test pilot has extra features (such as "always open in this container", and icon and other fixes). I personally see it as a "light" version of running separate profiles.
