### ISSUE TITLE
font-visibility

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/ghacks-user.js#970]
Putting this in a separate issue

earthlng [wrote](https://github.com/ghacksuserjs/ghacks-user.js/issues/959#issuecomment-652490759)
> `layout.css.font-visibility.level` looks nice at first glance but doesn't it just add another vector to detect locale?
> Like, fe on my system the arabic fonts are "hidden" in my OS and font-visibility.level=1 would make them not accessible for CSS anymore but someone with an `en-US` FF (spoofed or not) on an OS in arabic would have those fonts exposed in the list. I don't see how this improves privacy TBH

more to follow. I removed my earlier comments in the diffs, as I wanted to reframe the narrative, and use cleaner tests: rather than some quick results. I've been following this particular anti-FPing setup since at least FF76 (and others from well before that)

**Comment by Thorin-Oakenpants** [comment]
reserved

**Comment by Thorin-Oakenpants** [comment]
reserved

**Comment by Thorin-Oakenpants** [comment]
> but I don't think it's worth it

I block doc fonts, I use TB's whitelist with Twemoji Mozilla added). Top is visibility `3`, bottom is visibility `1`. As you can see I don't gain much: except that the `fingerprintjs2` type test is awesome to have empty: that's the fast common test using in FPing. The fallback one is a lot slower but catches more: I don't think anyone uses it.

![eeek](https://user-images.githubusercontent.com/16656956/86929497-7212b200-c125-11ea-9490-77aa5de2d5eb.png)

**Comment by Thorin-Oakenpants** [comment]
Update:

This is (essentially) no different to just curating your own whitelist in `font.system.whitelist` and the feeling (so far) seems to be, engineering wise, when `font.system.whitelist` is used, to ignore the visibility pref, so that change may or may not happen: I wouldn't call it high priority because Tor Browser can control the pref in ESR78+, and the pref is at default 3 anyway (because it's early days and experimental)

That said, I wouldn't mind adding it as a FYI. It's quite good in the sense that users don't have to fiddle around with non-ANSI chars (e.g. `굴림` ) in a pref, and the kBase, kLangPack lists are already somewhat curated for them. And bundled fonts are auto allowed. Level `2` is a good setting for most people (but I still expect Linux to be somewhat messy)

Also, thanks for everyone's input and help on this :) Also, where is everyone?

@earthlng What do you think?

**Comment by earthlng** [comment]
oof there's a lot here ... 1st of all thanks for writing this all down and all the testing etc! 👍 

I think I misinterpreted a dev's comment(s) and the call to `isHidden()` (or something like that) in the code. I thought it uses an OS API to retrieve the visible/hidden state of installed fonts but apparently that's only used for a few weird system fonts on Mac OS. Everything else seems to based on those manually curated fontlists and therefore the OS locale leak I was worried about shouldn't happen.

There are a few other weird things that I don't quite understand like fe in your test when you set the level to 2 it didn't detect Meiryo and MingLiU_HKSCS anymore even though they're both in the kLangPackFonts list.
MingLiU-ExtB from the kBaseFonts also mysteriously dropped with level 2. Any idea why that is?

Overall I think this looks promising and a good first step forward, especially once they make value 2 the default. Maybe a that point we could even consider relaxing "no-doc-fonts" and just use this instead.

**Comment by Thorin-Oakenpants** [comment]
> in your test when you set the level to 2 it didn't detect `Meiryo` and `MingLiU_HKSCS` anymore even though they're both in the kLangPackFonts list. `MingLiU-ExtB` from the kBaseFonts also mysteriously dropped with level 2. Any idea why that is?


Woohoo .. been hanging out to use this 😃 
![flakeytest-or-code](https://user-images.githubusercontent.com/16656956/88081830-7bae0800-cb70-11ea-982d-9a5280d431bd.png)

---

Note: I **do** have those three fonts

`font.system.whitelist` = `Arial, Courier New, Meiryo, MingLiU_HKSCS, MingLiU-ExtB, Times New Roman`
- **all three show up**

`Arial, Arial Black, Arial Narrow, Courier, Courier New, Helvetica, MS Sans Serif, MS Serif,` **Meiryo, MingLiU-ExtB, MingLiU_HKSCS**, `Roman, Small Fonts, Times, Times New Roman, 宋体, 微软雅黑, 新細明體, 細明體, 굴림, 굴림체, 바탕, ＭＳ ゴシック, ＭＳ 明朝, ＭＳ Ｐゴシック, ＭＳ Ｐ明朝`

---

`visibility` = `2`
- **all three do NOT show up**

`Arial, Arial Black, Arial Narrow, Batang, BatangChe, Calibri, Cambria, Cambria Math, Courier, Courier New, Dotum, DotumChe, Ebrima, Estrangelo Edessa, Euphemia, Gautami, Georgia, Gulim, GulimChe, Gungsuh, GungsuhChe, Helvetica, Impact, Iskoola Pota, Kalinga, Kartika, Khmer UI, Lao UI, Latha, Lucida Console, Lucida Sans Unicode, MS Gothic, MS Mincho, MS PGothic, MS PMincho, MS Sans Serif, MS Serif, MS UI Gothic, MV Boli, Malgun Gothic, Mangal, Marlett, Meiryo UI, Microsoft Himalaya, Microsoft JhengHei, Microsoft New Tai Lue, Microsoft PhagsPa, Microsoft Sans Serif, Microsoft Tai Le, Microsoft YaHei, Microsoft Yi Baiti, MingLiU, MingLiU_HKSCS-ExtB, Mongolian Baiti, MoolBoran, NSimSun, Nyala, PMingLiU, PMingLiU-ExtB, Palatino Linotype, Plantagenet Cherokee, Raavi, Roman, Segoe Print, Segoe Script, Segoe UI, Segoe UI Light, Segoe UI Semibold, Segoe UI Symbol, Shonar Bangla, Shruti, SimHei, SimSun, SimSun-ExtB, Simplified Arabic, Small Fonts, Sylfaen, Symbol, Tahoma, Times, Times New Roman, Traditional Arabic, Trebuchet MS, Tunga, Twemoji Mozilla, Utsaah, Verdana, Vrinda, Webdings, Wingdings, 宋体, 微软雅黑, 新細明體, 細明體, 굴림, 굴림체, 바탕, ＭＳ ゴシック, ＭＳ 明朝, ＭＳ Ｐゴシック, ＭＳ Ｐ明朝`


So ... confirmed. There **may** be a few others like this. Meiryo UI, MingLiU, MingLiU_HKSCS-ExtB show up FWIW.

There's clearly a difference in how `whitelist` and `visibility` accept font names/families or something. [line7](https://dxr.mozilla.org/mozilla-central/source/gfx/thebes/StandardFonts-win10.inc#7) "TODO: check whether we need to list legacy styled family names like "... Light" <-- I don't think this it, since it can pick up on Arial Narrow for example.

I have a gut feeling it's to do with CJK names (western vs non-western): I am so not a font expert. Maybe it's to do with GDI? IDK

PS: sent you an email
PPS: I'll ping the moz dev

**Comment by Thorin-Oakenpants** [comment]
... aaaaand so it begins ... https://old.reddit.com/r/firefox/comments/i1jfzl/several_fonts_gone_in_80_beta/  .. RFP

**Comment by Thorin-Oakenpants** [comment]
when the font whitelist is used, font vis will be ignored - starting in FF81, may be back ported to FF80 for Tor Browser - I'll keep you posted

**Comment by ganego** [comment]
Tor Browser just [removed](https://gitlab.torproject.org/tpo/applications/tor-browser/-/commit/ce4889c9f51d60761ffcbd416eac50ed6490fed9)  `font.system.whitelist`. I used the one from TB in my FF (I don't use 'resist fingerprinting').  
Any advice what I should do now because it seems they also use a [custom](https://gitlab.torproject.org/tpo/applications/tor-browser/-/merge_requests/1316/diffs?commit_id=5333f6385870e556723fe04efc904c5d2643269c ) hardcoded visibility though I don't know what that exactly means.

**Comment by Thorin-Oakenpants** [comment]
> I used the one from TB in my FF

So you bundled all the fonts that TB does, and changed all the relevant `font.name-list` prefs?

> Tor Browser just removed ...

The pref is still there, we just removed the pref values. If whitelist is blank, code falls back to using `font.vis` - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/43322 - in TB15 (based on ESR140) we're moving to using our own font.vis lists. Both whitelist and font.vis do the same job, as in allowing what font-families can be used. But whitelist is only used by TB and isn't technically supported upstream. font.vis on the other hand has lots of eyes on it and it then enables fontFace. At some point, up to jfkthame and upstream, we expect whitelist pref and code to be ripped out.

**Comment by ganego** [comment]
> So you bundled all the fonts that TB does, and changed all the relevant `font.name-list` prefs?

No that was not necessary according to my tests with https://coveryourtracks.eff.org/.

FF without whitelist: 1:14,000 had the same font list
FF with whitelist: 1:68
TB with whitelist 1:68

So just the whitelist is enough for a normal FF to appear - in this regard - similar to a TB.

If one uses no whitelist but 'layout.css.font-visibility:1' & 'layout.css.font-visibility:standard:1' the result is 1:1,147 - so far worse.

So can that new method TB uses also be easily applied to a normal FF like the whitelist?

**Comment by Thorin-Oakenpants** [comment]
> according to my tests

That's not it works - you need real world studies and one test per profile to even have an inkling of what the possible entropy is
- read: https://forum.torproject.org/t/the-impact-of-privacy-addons-on-tor-browser-fingerprinting/18007/2
- **_all entropy figures on all test sites are complete nonsense_**

In some metrics, you know or can estimate/derive entropy in a closed set such as TB users per OS, because your code tightly controls the outcome
- e.g. TB linux users are identical (assuming they don't delete a font in the `/browser/font` dir), because _all_ fonts are bundled, therefore the entropy is `0` within this group and is equivalency of OS (linux, which can't be hidden)
- e.g. TB users are all identical with timeZoneName

When resisting fingerprinting, you do not care about (and cannot control) anything outside your own "crowd".

The font.vis use is not new, it's been in FF since IIRC FF80'ish, and is used by RFP and FPP in Firefox. It will now (in TB15+) be used by TB as well, but TB compiles it's own font lists - you won't be able to do this in FF unless you build and patch your own - which is pointless, given you approach is completely flawed.

**Comment by Thorin-Oakenpants** [comment]
This is not how you check entropy. I have not **_claimed_**, I have **_shown_** that one single metric that is only used by RFP and Iceland, is so massively over-represented that that claimed probabilities and entropy is useless. And RFP comes with protections for some of the other metrics. RFP is only available in gecko. If that one metric is skewed, then all the other are. This is fact, not mere claiming. Even if I didn't bother to show such egregious results, the fact that it is not a real world test with one result per profile (as it is always done is peer reviewed papers) stands on it's own merits.

In case you didn't know, I work in this field, and have been part of Tor Browser and RFP efforts for many many years. I am a core contributor at Tor Project because of my FPing knowledge and work (you have to know what you're doing and _earn_ it!), go to their annual all-hands and other meetups, etc etc etc.

Locking discussion as this is an old ticket, and I do not have time to argue with lay people - with all due respect, you do not know what you are talking about - **_JFC, you're advocating for tainting test data_**
