### ISSUE TITLE
Gradient caused with resistFingerprinting enabled

### ISSUE THREAD

**Issue by matthewdavis** [ghacksuserjs/ghacks-user.js#972]
With resistFingerprinting=true

![image](https://user-images.githubusercontent.com/298426/87052147-fc274d00-c1ef-11ea-8f69-1e1c92bfd54e.png)

with resistFingerpringing=false

![image](https://user-images.githubusercontent.com/298426/87052241-12cda400-c1f0-11ea-95bd-596138452ad6.png)

I'm using a stock user.js 78-alpha on FF 78.0.1. I've reproduced this on a fresh profile. I suspect this may be an artifact of the resistFingerpringing option. I poked around in the SECTION 4600 and played with some of the options there with no avail. Notably 4615-4617. None of the others looked like it would matter.

Is there any hope to have resistFingerpring enabled and have this chart look normal?

**Comment by atomGit** [comment]
where is this image from? can you provide a link?

**Comment by matthewdavis** [comment]
Unfortunately its from the app [organizr](https://github.com/causefx/Organizr) which I am hosting internally. Specifically this is scrap of a [netdata](https://www.netdata.cloud/) widget.

Fwiw, when I disabled resistFingerprinting.autoDeclineNoUserInputCanvasPrompts, I was prompted for the site to store canvas image data. I said yes, then it showed up properly.

Attached is the section of html in question if that will make any difference. At least I have a workaround.

[ghacks-user-issue-972.txt](https://github.com/ghacksuserjs/ghacks-user.js/files/4897539/ghacks-user-issue-972.txt)

**Comment by rusty-snake** [comment]
If `resistFingerprinting.autoDeclineNoUserInputCanvasPrompts=true` you get "promptet" too, but without pop-up. Just click on the icon right from the padlock in the urlbar.

**Comment by Thorin-Oakenpants** [comment]
That's randomized canvas, it's a pretty distinct and blatant pattern: https://canvasblocker.kkapsner.de/test/test.html RFP canvas has never been subtle, it doesn't even hide itself on second passes (it's not trying to hide)

![pattern](https://user-images.githubusercontent.com/16656956/87068863-bd03f680-c205-11ea-96ab-a84661dc7b38.png)

As rusty-snake says, allow a site exception

If need be Canvas Blocker can then fake it, and CB's faking is to only change most pixels, not all, and only some combinations of rgb, and to only move the rgb values by 1: assuming it doesn't ignore flat solid colors. In other words it's a lot more subtle and you might not even visually notice it

I've been working on noise fingerprints cuz I'm a sneaky bastard

**Comment by Thorin-Oakenpants** [comment]
^^ just to clarify: if you have CanvasBlocker (CB)

RFP = on, canvas = random, CB never sees the canvas
RFP = on, allow a site exception for canvas, CB sees the canvas and randomizes

And then on sites you **really need to** give away your real canvas, you allow an exception in CB.

See #350

**Comment by matthewdavis** [comment]
Thanks all for the help!
