### ISSUE TITLE
security.ssl3.ecdhe_rsa_aes_256_sha; false - broke uBlock Origin "MVPS HOSTS" filter update.

### ISSUE THREAD

**Issue by ChamliBro** [ghacksuserjs/ghacks-user.js#974]
When user_pref("security.ssl3.ecdhe_rsa_aes_256_sha", **false**); this breaks the connection to https://winhelp2002.mvps.org/ and prevents the uBlock Origin "MVPS HOSTS filter from updating. Decision at your discretion.

**Comment by Thorin-Oakenpants** [comment]
There's a reason they are not disabled by default: because they are still used in the wild. I did the stats on them all and it was about 3% of nightly/beta traffic used the ciphers in 1263+1264

**Comment by Thorin-Oakenpants** [comment]
@gwarser FYI

**Comment by Thorin-Oakenpants** [comment]
for the record: (from when I looked them up a few weeks ago)

- the code numbers are [here](from https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsNSSCallbacks.cpp#903)
- telemetry from SSL_CIPHER_SUITE_FULL: 
   - go to https://telemetry.mozilla.org/
   - click Measurement Dashboard, etc

```
   // user_pref("security.ssl3.ecdhe_rsa_aes_128_sha", false);   //  3: 0.33%
   // user_pref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false); //  4: 0.01%
   // user_pref("security.ssl3.ecdhe_rsa_aes_256_sha", false);   //  5: 0.91%
   // user_pref("security.ssl3.ecdhe_ecdsa_aes_256_sha", false); //  6: 0.00%
   // user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);     // 21: 0.17% DHE [DEFAULT: false FF78+]
   // user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);     // 23: 0.30% DHE [DEFAULT: false FF78+]
   // user_pref("security.ssl3.rsa_aes_128_sha", false);         // 61: 1.16% NOPFS
   // user_pref("security.ssl3.rsa_aes_256_sha", false);         // 63: 0.83% NOPFS
```

So excluding the DHE which are now disabled by default, that's approx 3.24%. `ecdhe_rsa_aes_256_sha` is about 1%

**Comment by gwarser** [comment]
"MVPS HOSTS" is available, but not enabled by default.
