### ISSUE TITLE
OT: uBO processing filters

### ISSUE THREAD

**Issue by crssi** [ghacksuserjs/ghacks-user.js#975]
@gorhill

Is it just me or... latest uBO (1.28.2) on Firefox has some troubles with processing filters.

Visiting `https://www.worldometers.info/` says prevented access because of `||info^` in `https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt`, but there is no such filter in this list.

Do anyone else have similar experience?

**Comment by crssi** [comment]
I have found a culprit...

it is the space just after the dot `.` in the line `aggiornamento. info`.

Hmmm.... uBO should ignore such errors, I think.

**Comment by gorhill** [comment]
> uBO should ignore such errors, I think.

uBO does not know what is an error. The new parser is just bringing to view filters that were erroneous.

**Comment by crssi** [comment]
I am not native English speaker and I am might not use the right word... but and I am sure you know what I meant.

If there is something that helps you to improve your really great product, there you have, if not, then not.
My intentions here are only pure.

And thank you for your work... I mean it from the bottom of my heart. ❤️ 

Cheers
