### ISSUE TITLE
reminder: dom.disable_window_open_feature

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/ghacks-user.js#979]
FF76+: sort out `2200`: `dom.disable_window_open_feature` - see [1507375](https://bugzilla.mozilla.org/show_bug.cgi?id=1507375), [compat](https://www.fxsitecompat.dev/en-CA/docs/2020/browser-ui-can-no-longer-be-controlled-with-window-open-features-parameter/)

Pants wrote:

>  - if anything has really actually changed then it would be nice to get into 78 since it's ESR
> 
> I tried doing various tests [here](https://arai-a.github.io/window-open-features/test.html), and I have my own tests, and I just don't get it. I can still remove all those items: menubar, personalbar and toolbar (but I can't add them?). I also got some really whacked out results, where I loaded the test in a popup and the changes were being applied to the parent window (and I could show/hide things like the menu, toolbar etc)

**Comment by Thorin-Oakenpants** [comment]
[1660524](https://bugzilla.mozilla.org/show_bug.cgi?id=1660524)

**Comment by earthlng** [comment]
It looks more like they're dead prefs since at least FF78:

https://searchfox.org/mozilla-esr78/search?q=disable_window_open_feature

there's no code repo anymore for FF76, 77 or 79 so the above link is for ESR78.

Either they're dead or IDK how they're reading these prefs if nothing comes up for "disable_window_open_feature"

**Comment by Thorin-Oakenpants** [comment]
`¯\_(ツ)_/¯` IDK

**Comment by earthlng** [comment]
I'd say we can close this issue and move those prefs to 9999 when we work on the diffs for FF82

**Comment by Thorin-Oakenpants** [comment]
Looking at .. [this](https://hg.mozilla.org/mozilla-central/rev/bf0e49a9ceff) ... you're right - just search for `open_feature`. [They're dead, Jim](https://en.wikipedia.org/wiki/Leonard_McCoy#%22He's_dead,_Jim!%22). That link even says at the top to remove the prefs (they forgot).

So we can actually move these to deprecated already

**Comment by Thorin-Oakenpants** [comment]
weird, your comment didn't show until I posted mine. We don't need to wait for 82, they were **legacy** in 76 (`DEPRECATED / REMOVED / LEGACY / RENAMED`)
