### ISSUE TITLE
test site: Ping Spotter

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#980]
[Ping Spotter](https://armin.dev/apps/ping-spotter/) might be a worthy addition to the [Appendix A Test Sites](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-A---Test-Sites)

the developer is [Armin Sebastian](https://addons.mozilla.org/en-US/firefox/user/12929064/)

**Comment by Thorin-Oakenpants** [comment]
done
