### ISSUE TITLE
is there firefox mobile specific settings?

### ISSUE THREAD

**Issue by hunkjazz** [ghacksuserjs/ghacks-user.js#981]
I'm using Fennec.

I noticed that even though I've successfully set my custom `user.js`, some settings seems to not do their role in mobile, for example: cleaning data when quitting.

The mentioned example requires me to use browser settings manually.

So I was thinking there might be some preferences specific to mobile browsers or even Fennec, that I am not aware of.

Can you tell me if this is true and how I can reference these preferences?

_I feel bad for using this issue to ask for help for something that's probably not your responsibility. If you can only share links to proper forums, I'd be happy._

**Comment by Thorin-Oakenpants** [comment]
https://github.com/ghacksuserjs/ghacks-user.js/wiki/1.6-Firefox-Android

> **Note**: The `ghacks user.js` is designed for desktop Firefox;
>  - Fennec [68 or lower]: some prefs may not apply, or may cause issues, or may be missing
>  - Fenix [69+]: Don't do it! The differences in prefs is massive, and FYI: `about:config` is not available on release builds

The `about:config` in release builds thing may change. It wasn't available on preview, but preview is now gone, and of course stable is still ESR68. It is available in Nightly.

Once Fenix lands it's pretty much a **very** different beast (GeckoView), and I'm just not into maintaining a mobile version, sorry
