### ISSUE TITLE
privacy.clearOnShutdown.openWindows

### ISSUE THREAD

**Issue by Gitoffthelawn** [ghacksuserjs/ghacks-user.js#99]
Has anyone had the time to figure out what `privacy.clearOnShutdown.openWindows` actually does?

**Comment by Thorin-Oakenpants** [comment]
```js
/* 2805: privacy.*.openWindows (FF34+)
 * We don't know what they do because we don't care what they do ***/
user_pref("privacy.clearOnShutdown.openWindows", false);
user_pref("privacy.cpd.openWindows", false);
```

> We don't know what they do because we don't care what they do

See the discussion in #45

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants I took a quick gander at #45, but too much info there, so sorry in advance if the following is not new info.

After I set `user_pref("privacy.clearOnShutdown.openWindows", true);`, Firefox would open two tabs at launch instead of one.  Allowing it to be false fixed this issue.  Tested on FF53.

**Comment by Thorin-Oakenpants** [comment]
Yes, that is covered in issue 45 - not only that, but you can also get double windows on a the next restart. (Even on a new nilla FF from memory?). Both myself and @Just-me-ghacks had the same results. Those two have never been activated in the user.js until we revamped section 2800 and fixed the description and enforced them false. They really don't do anything useful (but clearly do something eg why else trigger two tabs/two windows), and we checked out all the code.

Forget about em. PK's js just added them, as true. So I guess they'll find out when someone eventually says .. WTF? IDK.

**Comment by Gitoffthelawn** [comment]
@Thorin-Oakenpants Thanks!

**Comment by Thorin-Oakenpants** [comment]
Wow .. that didn't take long for the issue to be raised at PK
