### ISSUE TITLE
CSS Exfil Protection dev needs help

### ISSUE THREAD

**Issue by atomGit** [ghacksuserjs/ghacks-user.js#993]
Mike Gualtieri, the developer of [CSS Exfil Protection](https://github.com/mlgualtieri/CSS-Exfil-Protection), is having trouble solving a performance issue with his ext. and i thought maybe somebody here could have a peek at what he's dealing with

the issue is here: [high cpu usage for some sites](https://github.com/mlgualtieri/CSS-Exfil-Protection/issues/26)

**Comment by Thorin-Oakenpants** [comment]
nothing we can do: STR are known, the cause(s) are known .. sorry. Mike said "I did have one new idea I was playing around with many weeks ago. I'll try to explore that asap path again and get this release out.", otherwise looks like he will add allowlisting for problematic sites
