### ISSUE TITLE
Fingerprinting Test Fails

### ISSUE THREAD

**Issue by foxxo-hacker** [ghacksuserjs/ghacks-user.js#999]
I did a test on firstpartysimulator.org aka PanoptiClick after dragging user.js into profile folder  but it seems like the site can still fingerprint me and get my info. I did not modify anything nor i don't have any add-ons.

**Comment by foxxo-hacker** [comment]
![Proof](https://user-images.githubusercontent.com/57807810/90985249-3cf1e000-e56a-11ea-9999-50d388f4c4ec.png)

**Comment by Thorin-Oakenpants** [comment]
you'll have to explain more: are you talking about the third party stuff, or the actual fingerprinting results
